### ISSUE TITLE
Stat Changes

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#1]
Several stats are fundamentally changed from TBC --> Wrath.

**Comment by jimmyt857** [comment]
Armor pen becomes a rating, and the calculation is different. Great reference: https://www.youtube.com/watch?v=EwOIqvw-kUw

**Comment by CharWS** [comment]
Reference for Stat Diminishing Returns:
https://web.archive.org/web/20080831105624/http://elitistjerks.com:80/f31/t29453-combat_ratings_level_80_a/

**Comment by tywtyw2002** [comment]
some references.
https://github.com/ariel-/rawr-2.3.23/blob/dddccced1ba9cf97dba4e4cba8d49a4dbe1acbbe/Rawr.Base/StatConversion.cs

**Comment by lologarithm** [comment]
closing this as initial work is done. we can open new tickets if we find new issues
