### ISSUE TITLE
Item Effects

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#10]
Implement special effects for all equippable items.

**Comment by jimmyt857** [comment]
Should have almost all effects now, except for healing trinkets which will come later. The remaining notable exception is Shadowmourne, and possibly other weapon effects if there are any.

**Comment by jimmyt857** [comment]
Shadowmourne has been implemented, but we still need to implement some healing effects.

**Comment by WantToSignUp** [comment]
https://www.wowhead.com/wotlk/item=50641/heartpierce
This missing energy regen effect.
