### ISSUE TITLE
Is it possible to deactivate raidbuffs?

### ISSUE THREAD

**Issue by Apfelloot** [wowsims/wotlk#1001]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For clarity and comparability i'd love to be able to deselect all raid buffs.

**Describe alternatives you've considered**
Either select single buffs or turn them all on/off at once.

**Additional context**
If this is possible already please describe how :)

**Comment by rosenrusinov** [comment]
Right clicking on a buff/debuff icon deactivates it
