### ISSUE TITLE
Missing Expertise items

### ISSUE THREAD

**Issue by dylanbanter** [wowsims/wotlk#1023]
Missing some TBC expertise items and others, not sure if I found all but the ones missing on my character are:
https://www.wowhead.com/wotlk/item=29947/gloves-of-the-searing-grip
https://www.wowhead.com/wotlk/item=30106/belt-of-one-hundred-deaths
https://www.wowhead.com/wotlk/item=30055/shoulderpads-of-the-stranger
https://www.wowhead.com/wotlk/item=30052/ring-of-lethality
https://www.wowhead.com/wotlk/item=28757/ring-of-a-thousand-marks
https://www.wowhead.com/wotlk/item=24259/vengeance-wrap

**Comment by jimmyt857** [comment]
Thanks for the report! We don't include pre-Hyjal gear from TBC, except where there are special interactions. All of the items listed there are very quickly replaced while leveling in wrath.
