### ISSUE TITLE
MS Warrior: More customization options for rotation in execute phase

### ISSUE THREAD

**Issue by Otinnn** [wowsims/wotlk#1027]
**Is your feature request related to a problem? Please describe.**
Currently the Sim for MS Warrior always uses Slam instead of Execute in the Execute phase. 

**Describe the solution you'd like**
Add the following 2 options in Settings -> Rotation:
Use Execute instead of Slam in execute phase if rage >x
Use Execute instead of Slam/MS in execute phase if rage >y

**Comment by TheGroxEmpire** [comment]
The option to ``Spam Execute`` will change it to spam execute instead of using slam. I'm not sure if any average players would prio execute / slam on certain rage as execute rage cost is capped in this expansion and dealing more damage per GcD is pretty crucial at this late of a fight.

**Comment by jimmyt857** [comment]
No response from OP and this seems to be a non-issue, closing.
