### ISSUE TITLE
Fury Warrior: Settings option "Slam over Execute"

### ISSUE THREAD

**Issue by Otinnn** [wowsims/wotlk#1028]
**Describe the bug**
When the option **Slam Over Execute** is enabled, Execute is pretty much not used at all in the sim and GCDs are often not used whenever BT and WW are on cd.
When the option **Slam Over Execute** is disabled, the sim prioritizes Slam over Execute whenever Bloodsuge procs and uses Execute if BT/WW are on cd.

**Comment by TheGroxEmpire** [comment]
Can you link the settings for this?

**Comment by jimmyt857** [comment]
No response from OP, closing.
