### ISSUE TITLE
Enable glyphed hunter's mark while not having it yourself

### ISSUE THREAD

**Issue by sannitie** [wowsims/wotlk#1036]
As far as I can tell there's no way to sim as if another hunter is playing with both specced improved hunter's mark and also using glyph of hunter's mark. If there is I apologize and please ignore this.

**Comment by jimmyt857** [comment]
The Hunter's Mark option under 'Debuffs' controls the debuff from another hunter. The option in the 'Player' section controls your own hunters mark (it doesn't have separate values for talent/glyph because those are controlled by your own talent/glyph settings).
