### ISSUE TITLE
Meta socket requirements broken

### ISSUE THREAD

**Issue by Buddylee007** [wowsims/wotlk#1040]
**Describe the bug**
Meta socket requirement for Relentess Earthseige Diamond (2 blue gems)

**To Reproduce**
1. Go to 'Hunter Sim
2. Click on add meta gem with gem requirements
3. run any set without blue gems and with blue gem requirement
4. results are not impacted and meta is still gained without requirements

**Expected behavior**
Meta gem should be disabled if missing required gems

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox 
 - Version 104.2

**Comment by jimmyt857** [comment]
Going to need more specifics in order to debug this.

**Comment by jimmyt857** [comment]
Closing because OP hasn't responded.
