### ISSUE TITLE
Talent tooltips

### ISSUE THREAD

**Issue by ccboblet** [wowsims/wotlk#1041]
Talent tooltips only display the rank that they are initially set to. Removing a point from a multi point talent does not change the tooltip. If a multi rank talent is empty, adding a point does not change the tooltip. Creating a preset and loading talents with that preset seems to correctly display the tooltip.

**Comment by Wumblesnarf** [comment]
which talent specifically? this is not a universal issue

**Comment by ccboblet** [comment]
It seems to just be a issue with not loading the tooltip while it is open. Moving the mouse from hovering over the tooltip off and back on fixes the issue.

I'll close this. Doesn't seem like a big issue.
