### ISSUE TITLE
Add Tricks of the Trade Glyph option for misc raid buffs

### ISSUE THREAD

**Issue by Akmandorr** [wowsims/wotlk#1069]
**Is your feature request related to a problem? Please describe.**
Tricks of the Trade glyph for +4secs on tricks duration is the default for Rogues and thats the default in the Sim but theres no option for unglyphed tricks or an indicator that that is the case outside of checking the timeline

**Describe the solution you'd like**
Add the option to have Tricks glyphed or unglyphed

**Comment by jimmyt857** [comment]
This seems like something we might want to support only in the raid sim, where extra UI for this isn't necessary.

**Comment by jimmyt857** [comment]
#1943 does a small bit of cleanup to prepare TotT for the raid sim. To clarify, the reason it's hard to have this option in the individual sims is that there's already a variable number of TotT's which is configured by left/right clicking, so this would make it a 2D input.

Also note that the Misc Buffs version DOES default to using glyphed TotT.
