### ISSUE TITLE
Conqueror's Siegebreaker Shoulders add too much Hit.

### ISSUE THREAD

**Issue by Montoya289** [wowsims/wotlk#1075]
Conqueror's Siegebreaker Shoulders add too much hit rating to the character sheet.  When equipped, the character sheet gains 69 rating instead of the correct 46.

**To Reproduce**
Equip the item with no talents and no other gear on a warrior.

**Expected behavior**
46 Hit Rating should be added to the character when the item is equipped.

**Sim Links and Screenshots**
[Sim Link](https://wowsims.github.io/wotlk/warrior/#eJzjkuFgMmDKYCxgrGBsYGRcwch4gZHxBSPjD0amC0xMTvwKTA5AuQ6wzA5GRiEGqSksTYxsATmJlalFHBwCnFKaXAxAyC5w9AWTEiMDFx6oxAu0iy2AJYKlAmgik9YJJoZRQBVQxcLBKMFUFMzlMIGRUYFRg9ERIu7n4AlheDoEgumGQIdIiIieQyKE8cEeHvsd4Ajm5YRIuDgIAA19xCjBseIyk8Csy0wSMy4zKbRcZtLY85/JoPUy0wtGlg+MTLMYGW4xMigtYYZoa0hzEIToF3GQnDUTBE7aW0JELtgrpoHBNXujL0wFc2qreAISS5IzylOLshWMTBWCJTgGbaJocaCGKQ0nj1BijoGFVoEjsYrBgd4w+7SDIyQaftp7MAIAo9ZNOQ==)

![Warr Sim Error](https://user-images.githubusercontent.com/113744028/190840882-04f2e1c7-c550-43b2-a49a-ae17be4b07dd.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102 (Official Build) (64-bit)

**Comment by jimmyt857** [comment]
I think this should be fixed now.
