### ISSUE TITLE
Suggestion for Pawn Export String including class and specialisation 

### ISSUE THREAD

**Issue by Padparadscha** [wowsims/wotlk#1077]
I would Suggest to add a Information to the Pawn export String.
At the moment its like 
`( Pawn: v1: "WoWSims Weights": Class=Shaman,Strength=1.000,Agility=1.157,Intellect=1.647,SpellDamage=1.614,SpellHitRating=1.060,SpellCritRating=0.149,Ap=1.000,CritRating=0.240,HasteRating=0.295,ArmorPenetration=0.041 )`

so in Pawn it will overwrite always the "WoWSims Weights"

My suggestion is to add the Information for which one are the weigts like

`( Pawn: v1: "Enhancement Shaman WoWSims Weights": Class=Shaman,Strength=1.000,Agility=1.157,Intellect=1.647,SpellDamage=1.614,SpellHitRating=1.060,SpellCritRating=0.149,Ap=1.000,CritRating=0.240,HasteRating=0.295,ArmorPenetration=0.041 )`

**Comment by jimmyt857** [comment]
Thanks for the suggestion; added in https://github.com/wowsims/wotlk/pull/1511
