### ISSUE TITLE
Virulence Issues

### ISSUE THREAD

**Issue by ColdsnapJoji** [wowsims/wotlk#1079]
**Describe the bug**
Specing into 3/3 Virulence vs 0/3 Virulence causes a dps loss, even though it should be causing a gain, or at a minimum breaking even. I don't mean replacing those 3 points elsewhere, I mean literally not including those 3 points sims higher DPS. 

**To Reproduce**
Build a level 70 2H Frost DPS spec. (The same issue DOES NOT occur in a DW spec - DW sim also linked for reference.)
Sim the regular spec.
Remove 3 points from Virulence (do not place them elsewhere, run 58 points instead of 61)
DPS is now higher - not sure what interaction is causing this.

**Expected behavior**
Specing into virulence should not be a dps decrease compared to not placing points at all.

**Sim Links and Screenshots**
2H Sim:
https://wowsims.github.io/wotlk/deathknight/#eJzjYtVgbGBkdGIQYpD6ydLEyBaQk1iZWsTBKMAlNYmRi0fg124mJbZlpxh/7Wbk4hTYP4lJiRnE5BH4A5K4vRsswSLw4wgTF7/AD6AYJ1AMKswl8AKongXIZOBiF/gJlAQzbk4CM1gEfu9mApKnJoHI3WDyfweI/HoERnIIHJ/IJPFgATMXSP2KTUxKTBWMWieYGEYBVUAVwy9Gay4RD8ZCCP+DfSWY7jjsAEwQipxgjkOCgyBMWoFRi5vjPwwwdjEqGBjrGhsZGJkamBoamxoZGRgbGBoZGxoaGBgbGgBFDB8xighMv8Ik8fYpk8KMK0waM64yGcy8yjSLkYOLjYuFY2s38y1GBqWpzBC7GOxgdok4SM6aCQIn7S0hIhfsFdPA4Jq9EdCwYAmOQZsSWhyoYUrDySNUMYcYAAljn7sOjhD+D3sPxgRGAPGUbRs=
DW Sim:
https://wowsims.github.io/wotlk/deathknight/#eJzjYtVgbGBkdGIQYpBqYm1iZAvISaxMLeJgFOCSmsXIxSPwazeTEtuyU4y/djNycQrsn8SkxAxi8gj8AUnc3g2WYBH4cYSJi1/gB1CMEygGFeYSeAFUzwJkMnCxC/wESoIZNyeBGSwCv3czAclTk0DkbjD5vwNEfj0CIzkE5k5ikri/gBnKugtksQis2MSkxFTBqHWCiWEUUAVUMfxitOYS8WAshPA/2FeC6Y7DDsCEocgJ5jgkOAjCpBUYtbg5/sMAYxejoq6xkYGBqbGpobGpkZGBsYGhERAbGBsbGgBFDHUNjB8xighMv8Ik8fYpk8KMK0waM64yGcy8yjSLkYOLjYuFY2s38y1GBqWpzBDLGOxglok4SM6aCQIn7S0hIhfsFdPA4Jq9EdCwYAmOQZsUWhyoYUrDySNUMYcYAAljn7sOjhD+D3sPxgRGAMYsb5U=

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.127

**Additional context**
Obviously this sim is meant for level 80 specs, but I don't see why that would cause a DPS loss in a +%Hit talent.
It would seem that leave those points out is causing an increase in Frost Strike damage, resulting in the difference in dps.

**Comment by ColdsnapJoji** [comment]
Upon looking at this further, I have also noticed that have 3/3 Virulence is not resulting in a lower % miss. I get about 5.9% each sim regardless of points in Virulence

**Comment by rosenrusinov** [comment]
The sim decides to use Frost Sub Blood vs Frost Sub Unholy rotation based on amount of talent points spent in the trees. Right now the sub unholy rotation is wip so thats probably why its coming out as a dps loss.

After looking again into Virulence I could confirm the hit chance bonus is working properly for DK spells (It only affects Spells not Weapon Abilities)
