### ISSUE TITLE
Red Belt of Battle appears with 3 gem sockets when it only has 2

### ISSUE THREAD

**Issue by LUC4S4L** [wowsims/wotlk#1085]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Wumblesnarf** [comment]
this is most likely due to the extra socket added by the belt buckle

**Comment by rosenrusinov** [comment]
Red Belt of Battle has 2 base sockets + 1 for belt buckle == 3
