### ISSUE TITLE
Spore Bat (Hunter pet) 

### ISSUE THREAD

**Issue by Firsthunterz** [wowsims/wotlk#1100]
The Spore Bat shows its casting Spore Cloud but doesnt show any damage from it. Also Wolverine Bite doesnt show up as being used and it results in much less dmg than it should.

**Comment by Francoporto** [comment]
https://github.com/wowsims/wotlk/issues/848

Yes so currently we can't know which pet is better depending of the spells.

**Comment by jimmyt857** [comment]
Thanks for the reports. Note that there's still a bug where certain ability icons dont load, so you'll see a blank icon for wolverine bite (but if you mouse over the empty space you'll see the correct tooltip).

**Comment by Francoporto** [comment]
> Thanks for the reports. Note that there's still a bug where certain ability icons dont load, so you'll see a blank icon for wolverine bite (but if you mouse over the empty space you'll see the correct tooltip).

Yes but there is no Wolverine bite in the data at the end, when you want to know the dps of your pet, they is only the Bite and auto-attack, meaning there is a lack of dps by the lack of Wolverine ?
