### ISSUE TITLE
Crash Report -931279947

### ISSUE THREAD

**Issue by caige13** [wowsims/wotlk#1102]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1oFEEY3ffNetkdifliRMZU5zaKGJjb5cBUu1qlsAjYpNTCYGGhVsbqEIWYpEgTSM7GUi8ERYkoBhES0Ku8wpzgL4jRKyScpgk2+u3uxdriCgsf8/fe++bNMIwOPGKydA4XUAFuA/eAZ0ADaAHboAbRCS6SRYIxqZnMavY6g81dV1EYPX9m4uwlD6wHP0Mzt2eVefmBgsLDVWr+Iu3zck0Favkx6V7+IeZzMdWdekpXtsg8etuhzJvi1oUWhKb1e3hzWpk1UVyhju7nLeGvl1TQIzyT+nhlWgV+TtM9zN8l5cuipPxR7teUacmuHcXn6zOdK/n8rtpZuvzkhpLxaU3pAa7NKPPxVh59N2vaEfPmlAr6PLK9xzDqjrmX08c48oKc/+gKrrgeDP3EIb0/wQgu5mo7nsjmydVEft3u/h21iCkcDSNbtqEtR9baKLJRGJVs2ktRuTRkwyHxw9Qri/0Jxvu6QfygSebbBhXnX9Hh+XWyC+vUgttGTxXOGzjBnPKzIyrjSeewfcmB6kKKejycK4344HiGZhxK1Cnj/bP/4FrSjZRKfa0rOX+D/I1Pvk+O53w7HsFp/AZMD5Gw

RNG Seed: 1187984281

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe2540, 0x11cc060})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:362
github.com/wowsims/wotlk/sim/common/wotlk.init.2.func15.2(0x8a7e2c0, 0x8323c00, 0x8ab6000, 0x8aa6b60)
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/enchant_effects.go:420 +0x44
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:829
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalizeInternal(0x8aa6b60, 0x8323c00, 0x8ab6000)
	/home

**Comment by JooperGH** [comment]
DRW is unimplemented in the sim, I'll be removing the Blood DPS presets to try and avoid these kinds of reports, those sims are very low priority at the moment.
