### ISSUE TITLE
Blood of the North Tooltip

### ISSUE THREAD

**Issue by FalcunPunch** [wowsims/wotlk#1103]
**Describe the bug**
3 points in blood of the north shows tooltip for rank 2, and vice-versa

**To Reproduce**
1. Go to 'Death Knight'
2. Click on 'Talents'
3. Scroll down to 'Blood of the North' in the 'Frost' tree.

**Expected behavior**
3 points in blood of the north shows tooltip for rank 2, and vice-versa

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 16
 - 
![image](https://user-images.githubusercontent.com/26085123/191191811-cd215ecb-4b11-4913-b9de-96936ca3e9d8.png)
![image](https://user-images.githubusercontent.com/26085123/191191897-38da811b-3983-4e05-9843-e5283a338c77.png)

**Comment by lologarithm** [comment]
ah, that is just a UI issue. The talents are correctly handled in the simulation.

**Comment by JooperGH** [comment]
Like lolo said this is just a UI bug which I've fixed, the talents worked fine regardless.
