### ISSUE TITLE
Crash Report 551260234

### ISSUE THREAD

**Issue by jere357** [wowsims/wotlk#1111]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFoU1EUfef+b3x9pfJaHJ6dvh9EEQLv/88HnfLj1MEh0KVjHezkEJysUygOtpNLBwtCp0ZFwcEhCElEDTWllZrB0gSDCEJwaoVCaAW9P8HdIYODZ7i8e+6591weV3mSNFm6ghnMoUgl4AHwAvQa2AV6wLVJCY8sEhRSBR4DU2K6fGoJmcKtG4s3b8uMxnQNSutX22R2uuRnGm/osELK1b0qqQn9ZIPMFvPOepOU1CsNMqs/HG44eUmm2eEGLrS5YVz/LJNpMQOhzug+l/eeO77LZcHyfpXM8jPHz3yoUK2SjuqyfKmRejzdJ9NjrVMbGC+z8Zg++sim7QFxWE7j92ra9egLmc1Omh9X03i/Rr6SsCi4c+4dXH5P4j9GgrtSQpOhIsILaorfMPCQFWI+HwtRzPMlTahx+esPsIKLsY3C0EZBEEdREHESRJGNOWcumw1tbG1kg/ArjOzUSe/VyezXyTvu0qW3LbKbLerBPcDpNYg2hL/qjA1WKS0kk8Olzibn1h6maOauDpnd3PmFAT7lwm/kzRr5z97AvWQUU0rNdyOZ8zcY/vH1z0l+mPdzM5jHb4RZhuI=

RNG Seed: 818867506

Unknown proc mask on {SpellID: 48463}
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xbd900, 0x88e2180})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalizeInternal(0x88e01c0, 0x8325c00, 0x88d3520)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:257 +0xda
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalize(0x88e01c0, 0x8325c00, 0x88d3520)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:233 +0xa
github.com/wowsims/wotlk/sim/core.ApplyEffectFuncDirectDamage.func2(0x8325c00, 0x83e7800, 0x88d3520)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:421 +0x1b
github.com/wowsims/wotlk/sim/core.TickFuncSnapshot.func1.1()
	/home

**Comment by jere357** [comment]
this happened while i was trying to sim boomkin dps idk what caused it

**Comment by psiven** [comment]
@jimmyt857 
Likely related to this update: https://github.com/wowsims/wotlk/pull/1107

Link:
https://wowsims.github.io/wotlk/protection_paladin/#eJztVD1ok1EUzTkvTV8+KbxWh2dxiN8UhMr7EgPqkujk4BBw6aiDnRzETadiHKIULIJKg2KpIoIVqihExIp/0IpKjBC0UivS0IyxVOjofQk6O2Rw8PAOnPvuuZfL4/KC3ZqGjntxFCcxDkwC09hQd4A5oAZ8A1pAG9wEy8TBUMPAIkWHIkalpuwLIP5p4pO3YX9sKDb8tO8sEsUTx04fPyUV8eHXCIx59Jb2/VeGiYcvOfWYQdxcqjMYMKXbtNdXGCp/qc21z7RL91Sw1Vxch73yk2FyrUo5Pr3FPBD3pLgRk+CqeCvrygfGlG7Rnp9VYaJR5ULVd569Sdu8+6fzR3G3v3j1YoZ244MS9WMVHRU3z+b9SKszPv9E8jfmIOpdjba84jOleYZax91AUY2qXQuM/UdPcEbLitAyhTdIBymNoR0Bdb9QCxNCCClUwj7ZLlp1AekRl3MuF2VzGeeiPZlsFGUFkRcjOQlcxkWSyn6H1csNmonntPebTLXqTK/V6Zp1thBvo7+C5OBYB418FVhCLLyskp3ZxscKg90ptxW2V6Y8FvP7uje1/M7fVRlpe8Tqf3YpzhV60WV88VVP+vwNum98eLlwoBtv5g/JH/ULA2yKog==

RNG Seed: 2853485420

Unknown proc mask on {SpellID: 20182}
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xbd900, 0x77c2010})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalizeInternal(0x77ba150, 0x56b3880, 0x77b6680)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:257 +0xda
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalize(0x77ba150, 0x56b3880, 0x77b6680)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:233 +0xa
github.com/wowsims/wotlk/sim/core.ApplyEffectFuncDirectDamage.func2(0x56b3880, 0x7741800, 0x77b6680)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:421 +0x1b
github.com/wowsims/wotlk/sim
