### ISSUE TITLE
Crash Report 258928639

### ISSUE THREAD

**Issue by mrAbra** [wowsims/wotlk#1112]
Link:
https://wowsims.github.io/wotlk/raid/#eJztm2tsFNcVx+femTXjsYEbF9FhVaUTtyVb2pVmZlkJKrVewI2cNpVcUBtaqWocMOAUcLpAk/gTAdLwaEpUNcRAgxGgVDSkpUAte3dtwDYBAzZgg6khPEowuOIR84iEaAM9594Z79qsXYcuVT7M8c76PmZm0fo3//O4F23DC9pVvxb3LSG5xdHyhUZxydySmWXzVR9T/PuIxtjfDlO99SzNz9rVSNfWUk1hv2uj2nC29F2qv3OO5ss4qLI/dFL91Puy9gW2+ibR13xC87Mv11B44XQO2wFnvwlnEwk6b8O5627K2GFs6Raqr9gm52d11NADNXjnbZup3vVe753b4eye09hq2ET128dkaN24SHhLYbvr8Z90cRPOx2G+ajuBVstRqi8/hzNL62m+qirm8GJ5ujzuAJU8y4hVSAdJQDNUkvcljarD4FDhyIKDwEHhkOHw5Ul+qssrSSBohk0zbIXCtmla4+2QZYXALGwEw9AxbdOCqdAFoqtnOij7zV6q/7WLGt1tNHC5jZpdbbSbKD1k2DqS/dgsbh0FNYScAoi2Ib2T55aXzzQKX1xgFH4f6NX8e5HeSyepfgTprW6kHfepls3ufAhkJTho1xJU33/W6aosFqN6DYAGV8FE82m4akMzxbkRbGWc6k0wokBXgn43nHHyfTlfuYT9XNYRE2fDC66/CrOXgOAsOFvce3Ud1bvh8chmnSedD1TYKv447Ynh+5UjeNoe+JjzG2VNgpHVcMuRKjWHTyDFynTlZbKcEA/gjFmFdJcYGo0QQFR/TIz1FBhkXI563zWykoyzQ0CubYZDJtAZMkNArIkHoGwFgzBr2yaeItC93EXZzg6qXwV0K4/TQOUJaq490YuuhLi+hrhOKZ/3fMlCY2r57EWlgGuWvx5x3ZlI4tra0ovrn5oR12oX1w1VXBfjQnGHs9MOrnxiBDtR7bDaKFjd7rJ6F/vZrAnAknfXIKi7XFDh1EYO6lvVAlSFreR0rkvg+9U6fD/TiWdsgjMOCz2Oi5bC9sZRZanpK1aeUzxIM2YV0k/z4ItWdGrKEyiQqjCqA5UB0NIQyKUZtkNB0wZRDVucwbAJdCKe0LPssHWB5KoNwOT+Lqp3HunLITp99alo+YKFrmQ29ZfMFAbTSiYy+JklM5EimdDuJ5nO9UnJVNg/d6ZXy09rqX5uo+y0UDc91XzEhqo5XhsdIUXkl2Kkp+AV/nt5Y2RwJR3LlRTADCK5YUAVggHUTggCuLYKTUUVXX+csrePU/3aICq6C1W08FnjR/PnlM99xSU4kY5ghX2683+Ed308DbyOv1fZpRiHFz5inZBP18OnkvvbLUly2xw/r7L3Ei65/z7skfsIDckdp2mM6ATpLUa/7++lVScP8BrknI4PIbOmjZ4eWBWe3rYwjDUtaFshCGRNge07gC04fn3N8QGxzZO0W37t98Bu9hRw/4XRRWUz1SxG/DUI7toU948A9ZHePz9Ibz/3L9Dtdf8c1Rx2xtFdgr7/jZhzHmNXTiaDVAyNh7OdMQfe1pqk63+j3sVWiK/Kmhy3j0FqSzXcAKAFZD1WM2YV0g7yuDZapUCrzyDfliRjUsRX9PjPsIEpFZu5knw9CApqm7YFISnoKLp8yKcgNjVBSSGlCkJQEObyimx

**Comment by jimmyt857** [comment]
Sorry, raid sim isn't supported yet!
