### ISSUE TITLE
iOS sims website crashes

### ISSUE THREAD

**Issue by ghost** [wowsims/wotlk#1123]
**Describe the bug**

When loading wowsims.github.io on iOS both using safari and chrome the page repeatedly reloads until the page crashes with error `A problem repeatedly occurred on "https://wowsims.github.io/wotlk/hunter/".` 
'

**To Reproduce**

1. using a semi-recent iPhone navigate to the wowsims website
2. wait

**Expected behavior**

I expect wowsims to work as it does on the web. Perhaps a clunkier ui, but still work :)

**Sim Links and Screenshots**

![IMG_4106](https://user-images.githubusercontent.com/112895848/191582976-3ac991fc-a86c-49aa-830a-2c80f9677b90.jpeg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12]
 - OS: [e.g. iOS15.6.1]
 - Browser safari, chrome
 - Version unknown

**Comment by jimmyt857** [comment]
#1509
