### ISSUE TITLE
Please add draenei racial hit % to the character sheet

### ISSUE THREAD

**Issue by suzumiya999** [wowsims/wotlk#1130]
Draenei racial hit % isnt being added

Add Draenei racial hit %

Really awesome sim, so much easier to use then the other ones. hopefully you can work out all the kinks.

**Comment by jimmyt857** [comment]
It is being added.  :)

If you want something more you'll need to provide a sim link.

**Comment by jimmyt857** [comment]
No response from OP; closing.
