### ISSUE TITLE
Missing items: Feral Druid Tier 4

### ISSUE THREAD

**Issue by schristiansson** [wowsims/wotlk#1153]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=29100/mantle-of-malorne
https://www.wowhead.com/wotlk/item=29096/breastplate-of-malorne
https://www.wowhead.com/wotlk/item=29097/gauntlets-of-malorne
https://www.wowhead.com/wotlk/item=29098/stag-helm-of-malorne
https://www.wowhead.com/wotlk/item=29099/greaves-of-malorne

2 set bonus needs to be taking in to account as well.

**Comment by lologarithm** [comment]
Generally speaking we have tried to keep to only sunwell and wotlk items. We have a few exceptions but anything like the t4 set are so far behind anything in wotlk it isn't really worth including.

**Comment by schristiansson** [comment]
I'm probably grasping for straws but the 2 set bonus of the set might allow cats to stay cats instead of bearweaving.

**Comment by jimmyt857** [comment]
Going to close this; if you really want to get these items included, hop in our discord and ask the feral dev. I think this is probably not remotely close to being worth though.
