### ISSUE TITLE
Crash Report -618371311

### ISSUE THREAD

**Issue by darvoso** [wowsims/wotlk#1171]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1FGWJka2gJzEytQiDi4BNqk9jFwCAq9/M0p0PGFUYpv5l/Hcb0YuFoGWP4xcHAKTu5kkbjwEsQ7/YZS40snExS+w5ROjEidQERBdASrlE5jQyyRxqZNJiQUowsAlKHCoh0mioZlJif3Ob8Y7ICEugX+9QGkwm1dg6ydGifvPGJWYQbp5Bfr7mCS+3wFy74Dt3dnDBCQ//gWxV/SC2PPA9i/8yCgxfwOIdayBCcxiETgzgUmJA+h31gCWBBatCUwMowAFVLFwMEowRYlx8QiwSDBpMBkwWzA5sALTAIsAULyLUcXAwNTASNfAyNTIwNTQAAiMTQ0MTY2MjA1BMoZGpoa6xo8YOTjunmcSuHOe6QUjxwdGrlmMDLcYGZTeMHGCLWlIcxCEWCfiIDlrJgictLeEiFywV0wDg2v2RnuYCubUVvEEJJYkZ5SnFmUrGJkqBEtw0DzaWhyoYUrDySOUmGNgoVXgSKxicOA1zD7t4AgJzp/2HowA7d9/Pw==

RNG Seed: 571823188

Spell {SpellID: 13964} missing CritMultiplier
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xbf340, 0x7238850})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*SpellEffect).applyAttackTableCrit(0x7232f00, 0x723e3c0, 0x67e9000, 0x2067680, 0x3fe05e486aea7458, 0x7215038)
	/home/runner/work/wotlk/wotlk/sim/core/spell_outcome.go:582 +0x29
github.com/wowsims/wotlk/sim/core.(*Unit).OutcomeFuncMeleeWhite.func2(0x67f4a80, 0x723e3c0, 0x7232f00, 0x2067680)
	/home/runner/work/wotlk/wotlk/sim/core/spell_outcome.go:252 +0x30
github.com/wowsims/wotlk/sim/core.(*SpellEffect).calcDamageSingle(0x7232f00, 0x67f4a80, 0x723e3c0, 0x2067680)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:289 +0x7e
github.com

**Comment by Horiwix** [comment]
Got the same, only reproduce after putting points in `Hack and Slash` combat talents (sword spec) and running sim
