### ISSUE TITLE
Pala Prot Chose strategy for Stat weight calculation

### ISSUE THREAD

**Issue by Padparadscha** [wowsims/wotlk#1184]
At the moment the Stat weights are calculated for 3 strategys, but each has in my oppinion sometimes different equipment. So it would be usefull to sim only for one like DPS or Threat or Survivability. I think this would also reduce the ammount of Iterations

**Comment by psiven** [comment]
The sim does not support separating these calculations; there are some improvements in store for how to represent Survivability especially for Stat weights, but it is not feasible to run them individually.

The best way to improve the iteration speed is to use the precompiled Binary version of the sim on your PC. It will run much faster than the web interface.
