### ISSUE TITLE
Optimize Gems Button without functionality

### ISSUE THREAD

**Issue by yebber** [wowsims/wotlk#1187]
**Describe the bug**
Like the title mentions pressing "optimize gems' in the stat weights tab does not work. I have changed the gems to non optimal ones to test and it does not change them back.

**To Reproduce**
1. Go to 'stat weights'
2. Click on 'optimize gems'
3. See that nothing happens

**Expected behavior**
It should change all non optimal gems to the highest simming choice

**Comment by jimmyt857** [comment]
This was fixed awhile ago. There are still issues with the optimize gems feature, but it does work.
