### ISSUE TITLE
i dont see stuff

### ISSUE THREAD

**Issue by kilarions** [wowsims/wotlk#1188]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lologarithm** [comment]
If you could explain what you mean by "I can't see stuff" we could help you better :)

**Comment by jimmyt857** [comment]
#1509
