### ISSUE TITLE
Incorrect number of sockets on Belt of Tasseled Lanterns

### ISSUE THREAD

**Issue by Melvinel** [wowsims/wotlk#1189]
[Belt of Tasseled Lanterns] (https://wowhead.com/wotlk/item=37648)  should have 1 blue socket, on wowsims it has 2.

**Comment by Wumblesnarf** [comment]
that's due to https://www.wowhead.com/wotlk/item=41611/eternal-belt-buckle, all belts are automatically given an extra prismatic socket. not a bug, but I can see how its unclear
