### ISSUE TITLE
SHAMAN / Enhancer / Using Sim do determin Dps regarding LIGHTNING BOLT WEAVE

### ISSUE THREAD

**Issue by 56shish56** [wowsims/wotlk#1190]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Rotation'
3. Scroll down to 
 Enable Weaving Lightning Bolt <check>
 Minimum Maelstrom Stacks to Weave <4>
 Weaving Reaction Time <0> or <1> or <2> or <any>
 Enable Weaving Lava Burst <check> or <unchecked>
 Minimum mana to cast Fire Nova <any>
 Mana % to use Shamanistic Rage <any>

5. See error !
   Lightning Bolt does not appear in tab 'detailed results'

**Comment by Wumblesnarf** [comment]
did you turn the setting off? its on by default, has been in for a while now and hasn't caused issues ever

**Comment by jimmyt857** [comment]
No response from OP, closing.
