### ISSUE TITLE
Crash Report 1360695815

### ISSUE THREAD

**Issue by lewie-donckers** [wowsims/wotlk#1194]
Link:
https://wowsims.github.io/wotlk/hunter/#eJztUr9rFEEY3ff2kpuMBEYRWQ+LyzUeQmT2lgVPkF1TXWER8B+IhaksopVaBRGUCJLOGIRITKKNaCMmRUBBMBHlwgXOXEyQqIQUKVKmUfxmt7G0iJ2PeR/zPr5fM3y6pGhoeQaDHMII74IvwRVgBxjoVSizihTX8Qw44pUedN1C9+CVSzcuX1O+YekRtDL3Vlmh5+mC2V6k6J9PGHxfo+j5DnWvubPOoLnBij8+T33ITMwxWOr4FXgifj1lsPWFThTN1Ex2UWZWQr5uQxvzYlpyJbh76zXlSM39WWdfzTm7u+js/RnXtdNh0N6gdvnvXdZbVpSihbyscGpcBvyPP3FTKRgGHMHZq/pcg1UezvzpVDpwQlN1CYvCHqESaqEvRDj50GEhqUcZVhNZjNOKpWOySZBt8Rv+BPAG/hKwBvTl/faS+qePDrtJFWM4Gdtav43iKIrDKLSRtWFUiyLxWJFx2B9bh9o3BOpxk2a6yWDhB8ufW6x+aNG2W9xBYQ/FSXjr8Cqb7MnajA6n+Tu8o+nxfNLlpJ57VpK+4QztpPac5YuB+ud7cTs9iCqjy+8OpM7fIP+rC5vp+VzvJw0M4TfiTX49

RNG Seed: 2428397891

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe5720, 0x1216e80})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/hunter.(*Hunter).registerReadinessCD.func1(0x51442a0, 0x510ea00, 0x5137e00)
	/home/runner/work/wotlk/wotlk/sim/hunter/talents.go:799 +0x1b
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x5137e00, 0x51442a0, 0x510ea00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:411 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x51442a0, 0x510ea00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:284 +0x12
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Fixed by #1337
