### ISSUE TITLE
Crash Report -2050584336

### ISSUE THREAD

**Issue by Tsotik** [wowsims/wotlk#1207]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUk9IVEEcft+3Dx1HzDFCJk/bO8WCMPteC3Z6z04eOix08VgHpUOH6pSdFukgeukSqAcRi+gPG0EQS2wRrRDvoG6gBokFgbakgeAh6WLz3ibhrYPd/GCYme/7fd9v3puRnqCi4VVcRwl4BDwH3gJ1oAHsgXXygsrSIMKgrRlLa046PfvuKFqK166MDN0UULLnFaRST2rUS5/ptbyscXGB0lX3HlB2qB9V6veWz1QrlEI9W6aurNEaNq0Qr1nDTMxEa1cTNmLeMnDkCdWw8sdyxnOt5shOVf8Or82uFyq0BuuP56g3n/71C/XzPnWjnLGtxx9StqrdD2mWq7ZfJ+fZWkqKHr+j/jKbkQk/8YZep6Dp6EPRHXRvJZ+Yu0vnGIdw2xXQ/IVzsjvCAG402Z1wJJ3HapF9E7rrgM0i1y72D4Bx5PzAFIxvCoExJghM4Ad5k4x8UMj39lrV901SYoKv0OLbBtWLVertDWYnl3l2coVmaoUNuDtonYbzCY63zra0W2k4+tP3VHR6eipBHJ5vMvXwzHCK1dAvM3tJi/9+tXeio0gpxfNHkvMvaP6ri+tRf3O/Fw7gMn4DENGLRA==

RNG Seed: 4014849243

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe4dc0, 0x1208e80})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:390
github.com/wowsims/wotlk/sim/common/wotlk.init.2.func16.2(0x5e4a2c0, 0x53ffc00, 0x5e583c0, 0x5dadf20)
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/enchant_effects.go:423 +0x4c
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:829
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalizeInternal(0x5dadf20, 0x53ffc00, 0x5e583c0)
	/home/runner

**Comment by JooperGH** [comment]
Blood dps is not fully implemented.
