### ISSUE TITLE
"Arcane Focus" Bug on mage sim

### ISSUE THREAD

**Issue by neopls** [wowsims/wotlk#1210]
The Talent "Arcane Focus" doesn't apply the extra 3% hit when the arcane spec is chosen. 

It's only on the arcane spec.

The spell hit from talents should be 6% for the arcane spec. 

Screenshots:

![image](https://user-images.githubusercontent.com/84713662/194053345-0ce6438f-7473-4da8-a7a6-70470c1f6c5a.png)
![image](https://user-images.githubusercontent.com/84713662/194053277-fcf389ed-04af-40be-9522-6ad5f52bcad8.png)

This was tested on Chrome Desktop.

**Comment by mormigil** [comment]
This is just a visual bug. The hit in the display doesn't show spell type specific hit increase like arcane focus. I could overwrite it to show though and have been considering doing so.
