### ISSUE TITLE
Missing items: Titan-Forged Mail Helm of Dominance, Titan-forged Ringmail Helm of Salvation

### ISSUE THREAD

**Issue by relynq** [wowsims/wotlk#1214]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=44896/titan-forged-sabatons-of-dominance
https://www.wowhead.com/wotlk/item=44897/titan-forged-sabatons-of-salvation

Missing from ele-sham sim.

**Comment by jimmyt857** [comment]
Added now!
