### ISSUE TITLE
Crash Report -546455484

### ISSUE THREAD

**Issue by RbiesBakes420** [wowsims/wotlk#1215]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztUT0sQ1EYved7Tz1XcDWGq4M8nTCJiUH6mCSWJmYJCZ0MIhamMhGRiE0XBoPEz0BC/bZJS9PEXwgNDRERacJgM/I9ZTBZ2JzcfLn3nJPvfPdeqSyqp0YEqQt3QA5o9VqwqR9hYA5YAKKAlzR8cXMUnmBf91DvgOVR8O1AKjWzQ/rklvye9QTNpkmaamSTZIlaYT7FvOGSljrfJv16ZbCQZSGd/RRK1cU66SQfzeMoCVmsbljOLBt+CPZObpEeXzL8Bouc9ZQh/bjIWZko8WLDGhty7DY2HkkWqekj7rsbdaeY2HRrfMutz7vuCEke4TBLUjAzvsdd+OIImnVTJP7xDcOmBU2rqJUVCrrARrMQdotT0FbV6W68wlcmi623L0D13ENbBzFS8w+k92NkRy6oJnVG9YkzysF8QWEE4hrCn6Wij4RwyCnPZ1U4lZEZF+lAU545DVSHPnAZaFgku0PTn3/RoPMbXcLp5A992n8lx0X+rcYSTssn4XThHc7ueFM=

RNG Seed: 3127260429

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe58e0, 0x1218020})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/druid.(*Druid).CurrentMangleCatCost(...)
	/home/runner/work/wotlk/wotlk/sim/druid/mangle.go:124
github.com/wowsims/wotlk/sim/druid/feral.(*FeralDruid).doRotation(0x7a63000, 0x6ffe7e0)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/rotation.go:424 +0x24e
github.com/wowsims/wotlk/sim/druid/feral.(*FeralDruid).OnGCDReady(0x7a63000, 0x6ffe7e0)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/rotation.go:22 +0x7
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x6ffe7e0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:310 +0xe
github.com/wowsims/wotlk

**Comment by jarveson** [comment]
Link here seems super messed up, no race selected, and listed cooldowns is weird, assuming this might have been from addon importer while it was still getting finished?
