### ISSUE TITLE
Hunter Hitrating

### ISSUE THREAD

**Issue by hasuwary** [wowsims/wotlk#1220]
HUNTER !!

In the Simulation, "Hit" still provides DPS even after beeing Hitcapped!

Hit should provide 0 additional DPS after beeing capped (8%)

**Comment by klingo** [comment]
Same issue can be found in the Stat Weights.
Although I'm above hit-cap (8.03%), the calculator ends up with a statweight of > 0 for "Hit" when re-calculating.

**Comment by BocaDaddy** [comment]
This issue happens with Fire Mage as well.

**Comment by jimmyt857** [comment]
Thanks for the reports, this will be fixed in #1481!
