### ISSUE TITLE
Hunter shows melee stats

### ISSUE THREAD

**Issue by klingo** [wowsims/wotlk#1228]
The Hunter simulator shows melee stats instead of the ranged ones (or at least the label is wrong):

- Melee Hit -> Ranged Hit
- Melee Crit -> Ranged Crit
- Melee Haste -> Ranged Haste

![image](https://user-images.githubusercontent.com/14639044/194551235-a063dc38-fbc6-4398-b412-117feb37aa9a.png)

**Comment by jimmyt857** [comment]
Yep this is just a label issue, but will be fixed by #1468. Thanks for reporting!
