### ISSUE TITLE
Missing items: Enchant Staff - Spellpower

### ISSUE THREAD

**Issue by hyperactivated** [wowsims/wotlk#1229]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
[Enchant Staff - Spellpower](https://www.wowhead.com/wotlk/spell=62959/enchant-staff-spellpower "https://www.wowhead.com/wotlk/spell=62959/enchant-staff-spellpower")

**Comment by jimmyt857** [comment]
This is added now
