### ISSUE TITLE
Include standard deviations in the wotlk sim

### ISSUE THREAD

**Issue by moricodes** [wowsims/wotlk#1237]
Hey there! So, on the sim, you have a ± range for the simmed DPS. I think it would be quite useful to add standard deviations to this, perhaps as a setting which displays them in addition to, or as a replacement for this number.

I've attached an image which depicts 3 standard deviations along a normal distribution.

TLDR: 68% of results are within 1 standard deviation, 95% are within 2, and 99.7% are within 3. This helps to provide a good perspective on the possible ranges of simmed DPS.

[Here's the page which describes it in more detail, and where I got the image from.](https://s4be.cochrane.org/blog/2018/09/26/a-beginners-guide-to-standard-deviation-and-standard-error/#:~:text=Standard%20deviation%20tells%20you%20how,standard%20deviations%20of%20the%20mean.)

I would offer to write it myself, but I don't have experience in Go. That being said, if you think this is a feature that would not get implemented for time reasons, or if it would take too much time, I am happy to try to code it myself. I am a dev by trade. At the very least, please reach out if you would like help with implementing the formulae.

Let me know if this idea interests you. Thanks!

![Image-1-Standard-deviation-Standard-error--768x555](https://user-images.githubusercontent.com/29949841/194723850-c4e3b71b-911b-4744-a3ea-2a14bac9a8ee.jpg)

**Comment by Teebown** [comment]
If you look at the detailed results histogram, the +/- on the main screen corresponds with+/- 1stdev, it's not the total range of dps.

**Comment by moricodes** [comment]
Oh, that's great. Thanks so much!
