### ISSUE TITLE
Crash Report 1390812251

### ISSUE THREAD

**Issue by RiziPagle** [wowsims/wotlk#1238]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztkk9oE0EUxve9XZLpUMsY0K4BYd1TKQQnWRbqabeePEnAi8dWqQh6CEVQC0KQQpMeJEUotnpoPFhBixLQxlZBSS/VSmIOjTZ4UKsNIij0oEKhvt0lEnMS1Jsfw8C895vvzZ/H9zIUKLEPkjgAKcwA5gDuAlYAGgAHdzEwoAdcSMI5yADcBLiCEFGis6GLEEqeHjw/NMzCAqJ3gAsxv4J6Zh3M0P0SbpSQa2J0C3inKEygGXozjzQ4E5VZ1NfmVMrWJ5GHRXESTVAIG7uBem1ONVFReJfI0Sp7WzW1WhEV3iHSeTRVz2GHGL+EeoNAdaKIlNl8QRmiyHFzxps/PfLm16+8akuLqJfqyBXa97KOevkJwXQ4cydDqdK9taPaAPqX681R5f9q1QhjIFDHFBQgxBX6eGUcYraVkKS4FZOWbUk7LuPS8tYJy6KItOIUi9nSh96CzmbKKK6XUX+wjkatij1PqyhXq9gA7QuEp6FGzcM1lh/DCAvqfnN4N1fZ++6IaAaer3ja7/rovUVoohGXR3kXy+42tpv6maNG8ugPt9QWY+H1ZQF+jbCFfBvDPmaxLTLVzojLC03m8eHgZJ+/tjBroJjvsCMAjrl7pqc8LTsHAqDi7Dvha9VJPMTUtQsjncnBM8dPnh0aPmUkbOOIzv55T466f8Mlvbz0Jz6yrzfV/7uw/3jpq8/c/uA5vzuH4AfRoKun

RNG Seed: 0

ResourceType set for spell {SpellID: 48477} but no cost
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xc06a0, 0x7a2e4c0})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources(0x7a470e0, {{0x0, 0x59682f00, 0xd09dc300, 0x0, 0x0}, 0x0, 0x0, {0x7a192a8, 0x8bb2c97000}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:115 +0x39
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFunc(0x7a470e0, {{0x0, 0x59682f00, 0xd09dc300, 0x0, 0x0}, 0x0, 0x0, {0x7a192a8, 0x8bb2c97000}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jarveson** [comment]
Link here seems super messed up, no race selected, and listed cooldowns is weird, assuming this might have been from addon importer while it was still getting finished?

**Comment by RiziPagle** [comment]
Hi Jake,

I cannot recall and honestly did not expect to get a response. This is super cool of you, so thanks! The sim tool has been working out quite nicely!

- Dylan
