### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by Ddwilkerson** [wowsims/wotlk#1241]
[Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
](https://www.wowhead.com/wotlk/item=38206/wand-of-blinding-light)

**Comment by jimmyt857** [comment]
This item is below our ilvl cutoff, so it's intentionally omitted. Thanks for the report though!
