### ISSUE TITLE
Crash Report 1608672776

### ISSUE THREAD

**Issue by Yoshimosh817** [wowsims/wotlk#1252]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1IHFEQ3m9u1edGzVNEXqzOq0QiPHcjxGo3VhYpBBtLLSIWFppKrY5gIVpoqQZCSiEcBAKiRkHwQK6Id8Q/8KIEQTnRgOUhiM7bOxE7i7PLB292vvm+meHtrhMTJEnTIIYRBxaB78AGkAFyQB6UIeqUUdII0MueydBTZzVOl31CefdQ/9iHj6JMOo1JOFKeHZBKH1OsfGmTtn+RUynzfygWWVsmp1r+WyO1dVykQu78JLWcJdPFQirLXV9SZLQaOcVakis2U4t5jh0HiUiRV8n9VXZzzg3cf8nq2beHfiFn1knlEhHHluc/iOP0iokbqyZepI3jZoXU368Rzn7zrnTWKDM89aUgXf0W3XavPWou2zJL1n88wrgtoOgab5yGAF0YKVSv/LHwObkZ8N+hau+rUbS8ELf3wBReu55u93R4tOdpz/XaOGn1XENbWTWJ285Bt51Aic+7JC9PSV2cUnRul5rn9kjP71EO9hUqFmAdwoodUWW4Lz4QFDfXB68W5g1SfkehkvGbBkLs+26Coj1KPPvHnQhKMSWeSpZkzlNQeFfvj4J3BZ73u9CHO8qlkLw=

RNG Seed: 3935505628

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe6640, 0x1231060})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).applySuddenDoom.func1(0x72f71e0, 0x72667e0, 0x7305680, 0x72f2f00)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_blood.go:312 +0xd
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:829
github.com/wowsims/wotlk/sim/core.(*Spell).DealDamage(0x7305680, 0x72667e0, 0x72f2f00)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:238 +0x6a
github.com/wowsims/wotlk/sim/core.(*Spell).CalcAndDealDamageMeleeWhite(0x7305680,

**Comment by JooperGH** [comment]
I've fixed the crash from this config. However, keep in mind a build so off meta like this one isn't supported at all, so you'll get no meaningful results.
