### ISSUE TITLE
Spell hit EP

### ISSUE THREAD

**Issue by wentsa** [wowsims/wotlk#1253]
**Describe the bug**
Sometimes when I calculate EP being hit capped (>= 17% ~= 289 hit rating), the EP for hit is not 0, but something like 0.75. Even though I check the detailed results and there is 0.00% miss on every spell

**To Reproduce**
1. Fill out gear with hit at least 289 hit rating (17%)
2. Click on 'Stat weights'
3. Click 'Calculate'
4. See Spell Hit EP is > 0

**Expected behavior**
Spell Hit EP be 0 when hit capped

**Sim Links and Screenshots**
[Gear link](https://wowsims.github.io/wotlk/shadow_priest/#eJztkj1oFFEUheecmV2eo5EXq2eqdUAIQuDNDANJtWOqFCJBm5RamMpisdNqCVok1TYpTBnBxGL9AYtNYEMQV4xRiQtG0V0LQViiiKsgKb2zU9lZxC6nuNz33T+47/olRU3LcUxhBhVWgRrwENwEdoAeMDmkUKJFigpWgRPOyHtvDsXpq5evX7mmfF0Y2YSv9dpLmlefGBRbT/i6Qd/TvSb9IX3vLs0L4e4tgUovtGgWf7pSUNuleTYvBRsN/pLYUd2/Q/OxwwCOf1zvPaZ5V3cDr9+g4x/T+01JlTzJluKuROdaQqTr4qDx/Q2aXt0Vb75J0+lk7Ply7nl6r5nZ/kpGHwl9O6Bv1jP7e5mBUrCYLswUztToHOov3ZDlaBpWcEH7nnJ1dgNFOQqMYgGnbWLjyMbh2FgcJTaKbRJGYkOhcZiE4sVJ+BlGrWxTP9imWfvC0tc2R7+1ab+32YP3A+4SnA9wgi6PDGZWZ9PhfPr59OTS7Uxb5Ymc7JRPzQ60W47qLF006r9/2s30ILpUt54eSJ9/Ub6rc930bP7eL0/hEv4A3ph7iw==)
![cap1](https://user-images.githubusercontent.com/6526193/194922094-fee4614b-565f-4480-a80a-02e0f051aa05.png)
![cap2](https://user-images.githubusercontent.com/6526193/194922104-84b55311-0349-4fe4-8d2d-3b083660d0e4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 105.0.5195.127

**Comment by wentsa** [comment]
Strange behaviour I have discovere is, that exporting Pawn EP string doesn't include hit rating (seems like it really is 0):
( Pawn: v1: "WoWSims Weights": Class=Priest,Intellect=0.560,Spirit=0.650,SpellDamage=1.000,Mp5=0.328,SpellCritRating=0.659,SpellHasteRating=0.914 )

**Comment by JooperGH** [comment]
Hey thank you, I will look at this since its likely just a bug.

**Comment by jimmyt857** [comment]
This should be fixed now thanks! The pawn EP isn't fixed yet but should be soon.

**Comment by Ironlenny** [comment]
I am having the same issue. I am over spell hit cap, but when I go to calculate my EP, it values spell hit at around 1.40.

[Gear Link](https://wowsims.github.io/wotlk/balance_druid/#eJztU01oE0EY3fc1SbdTS6fBwxgSiWsPIVCZ3TWgXnb11GNQxHjTg8WDhdaDoKdUULReqsagAUE8iXgQemkbNUUKNaJQhCouKpgI1h9oEFpqLzrbtXhQC4F6EHyHj/ne+953mHnDunXiJGkHepHDAOWBEeAGClvvgiaBGWAO2NOlI0kSLrL+FG4BUWWJvQ6fRiR77PDJI8f1CEdsFKyTf3hL4nPCiNy5QA/GiLXxhVdktHjquIEX75GoJYwWX2jl5QkSlzcryxVFLymLon2F8TNlEsWoAY118EtKLMSNkFI0NTtVJ3ExbkS8YLaTF5R+9qe5lU8rohhnIT4yTqp+rPm1UfZrZcIfqL4nsZhgmiKGymS065DIhnLhc8BNekrsKmn/8VtEZbOOU7oOToIGYBlMxYhDUEpFqdeP0iPEOli7/m0VGMaBjLQtKW3TytiqqMa0bZmxTdOyzR65JnosmVFWqWy/oAahP6kQf1kh8aJCyelnlFp+Q7I0SyrgDYRK0M7/eHfL9aCVSDPq1LZC5PvcrkDa6G4qXfNRdXYGzIyzpW8Fzx1rlJL7RDj9l/PTGHLXY02+OrUue5pBcGf3593dQb/kHMLeNX/cp8fp28t1z9l+cGHcG551ArbhrOq51PWvu/YvOg/H0rEvk3PO0RP9g/Pb3jl/2vevofkf9x1W26cE)
