### ISSUE TITLE
Belt slot enchant eternal belt buckle

### ISSUE THREAD

**Issue by wappakappa** [wowsims/wotlk#1255]
One of the possible enchants is the "eternal belt buckle" which adds an extra meta gem slot to the belt. Although cross implementing that might be difficult, it's likely the most common modification to the belt slot for most classes, so it would be nice to be able to add it and then say which gem is inserted. 
thanks for the work you put into this.

**Comment by Wumblesnarf** [comment]
the socket is already added by default, and its technically not an enchant and wont conflict with the engineering tinkers.

**Comment by wappakappa** [comment]
my mistake, I selected the wrong belt with the same icon and it tripped me up. thanks
