### ISSUE TITLE
Export Addon generates the wrong race for Undeads.

### ISSUE THREAD

**Issue by MikaB07** [wowsims/wotlk#1256]
**Describe the bug**
Currently when using the Wowsimexport addon it generates my characters Race = Scourge. 
When pasting this data into the import on the website it says incorrect race.
Changing race to Undead manually in the string solves the problem.

**To Reproduce**
1. Go to a udnead character and open the addon's interface
2. Click on generate data
3. Paste data into the import
4. See error that race is unknown/incorrect
5. Edit race manually to "Undead"
6. See that import is now succesfull

**Expected behavior**
A paste of the data would succesfully put in the data into the sim.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 106.0.5249.103 (64 bit)

**Comment by jimmyt857** [comment]
This is fixed now, thanks!
