### ISSUE TITLE
Heroes' Frostfire Leggings wrong item

### ISSUE THREAD

**Issue by Dizturbd** [wowsims/wotlk#1260]
**Describe the bug**
Heroes' Frostfire Leggings (ilvl 213) is not the right item, it is the same as Frostfire Leggings (ilvl 200).

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
This looks like an issue with wowhead's data, which is where we scrape our database from.
