### ISSUE TITLE
Crash Report -1474921766

### ISSUE THREAD

**Issue by Ruca777** [wowsims/wotlk#1261]
Link:
https://wowsims.github.io/wotlk/hunter/#eJztUs9rE0EU3vdmEycjkdGDHXMxXZQGobjZZcF42W29FLwU9A+wYIuHHkJBsMFDEQ/Wk+ilVjBQaxFqVYRqowQiLdRIa0qU1LTag7QhasCe6kn07e7Jm6De/Jhv3uz78c2+4YkER4kmHoNePANZvAL4CHAFoAnQHeeQxBR4cAHuAezTEp8ilyDaO9g33D/klyUKIKR8uoSqsoFG9Mk85ssodNkoouDy+x1Uixv+6cFbVGszjHJvzaIqr1NucQ5rP1Dslo8nUC2QBzSxR96m8OoMM/TXc6iJuMxPohq9zwzm63J5dwpVYxpJ5yFVNSkxSgGSojtnp1DE5PVlNFgrcLSK/v6h7hfW66jm11FodF6k0soLNDhHE6ht/cg11P7jF+Q4B4kKs3B8WJzogRRy2BtEvLzXnRTII8RdxBiREwWREZEI6fGbPgpuxg7wxqXZMWliDib20w40UqyHjQGUgL0EeAfQHt677WaWl3y03BRchcNOp2k6tu1YtknLTNuWbadtx7TTlpPudEwf1kdQfHIL5UQFVWETk6tVTL2qolmrYhP0bRDjcFREhc4b0yywO2MgIoLxrbbg8/Mo+lbeeBZY/vUbWwPN+IKx4J9GBrywde2QdyBsrOxmQs+K2z4QoOZazzG7czEXP9k/2HH63Plc39mk5SRPKf7Px+uy9zdURsoLf6JTsjqGun43OXi9Utt7ryt8PfR+ApLcoCk=

RNG Seed: 1889176454

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe6640, 0x1231060})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/hunter.(*Hunter).registerSteadyShotSpell.func1(0x7305760, 0x722b260)
	/home/runner/work/wotlk/wotlk/sim/hunter/steady_shot.go:20 +0x3
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x7305760, 0x722b260)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:586 +0x126
github.com/wowsims/wotlk/sim/hunter.(*Hunter).registerSteadyShotSpell.func5(0x722b260, 0x72fa000, 0x7308780)
	/home/runner/work/wotlk

**Comment by jimmyt857** [comment]
Fixed by #1337
