### ISSUE TITLE
Crash Report 1183741375

### ISSUE THREAD

**Issue by Tyestor** [wowsims/wotlk#1265]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmn9sE+cZx+9975ycLz/2kjF69R/rYaHVi+TpfK4lMmmKA3RKNSpFQ1uzaZXIIJSskCA3dMx/0bQImo4VdaKCIBrUMm0rsB+AohA7CeDQECAJTSApyZIwikO2sjYdmoRQW/Y87905dhw2xNiYxD3Jne/9ce8l9sff93ne51WGn1W2PqpscTWQ/IpIXb1WUbWuanVNrexikucUURjb0k7VvnHqzTmaoM3NVJFYIkaVArYN6vdOUK84dJsqMhuJUXXkkAg3vAwNPaNwA/QeaqVKHrvQQtUd0JUISiF7BZqb/i56pdOtVIDu/dD46kHRmwNl+IWhtkOP5AF8xq+gbeqQ6BV3H8MH/6IDzwfgOp81f2A+wWy5+jbeuBv+hvOjeHUerrZNYMvLHdQry5JeUCFWisU7qOBYhkWFM6RY8Xo0hco5cMhwuOGgcIhw5MJB4HAVCR6qio3E59dDuh4KBEOGrgeCRjAQCIIFjKAR8IegoBt6AJqCV4gqjw1R9vMTVP1jkmpTA9R3bYDqyQE6RaRpkttE3PPWcBsqbSVkBPD4q9RACpYAgrWrqrVlkY01q+UcRjwdCOIv41TtRRBPnaT7eqjiZv/4E+A30oqkvAmNZ6BRxJYClhym6k6AjLcytjNuIQmtHVBTyKagwwDUSB1IYSF7A3oMA2lmuYB9GjepFDs4ktNQbDiFV91xjiSQ1R9DvnZw/jrb8Dwdwx5ngb3uUSxv5rUvxahXkYlOKqRK1ybiMJhlUcFYqDwiE5WEBGFl2WLypCBsKHsaTxUEuJOQwUbyeEgPIliBQAh4C0IByNNDUAYI/X4DuQwCewje5gnKhjupeqmTarfGqS8B4HXPgCcgbJ8AbPllkfUvaM9URSI1dREQPbenFVk7D59yP7LWkqC/5azdRNbinLUBaOxG1iY5G4OW8hWwUQszEW8pZI3Q0IWMnUSm8tiYxRg82s22t1n9GPuijaqTB+BhoKTmkK+3m5C52aVh6Ab3A0dNcTx/1I/n423Y7Tg84ByQJkDNiRjqHNVzQOckh7EsiwqRbyiLGNlBSJlZ81T4Kf6qvxj+gVlTEl5LNnHgGFEpSB1omYHMGSBwoQDIHdc2g6ueEQr4gT7ALsilrnmQsr2DVN01SLWtg9QXv031LYOZxI0DcXllkVVVtdXa01XPVcsSEz0nEbjLsRlxQ8nJELcPY5a43Wi1xW3kcErcrgxb4gb3zS1uE7F0cXOjuJnCxtifY1zY+M03OHsfpwTudT7dmjLXftiWOZmdSwnc+1zgGo4iekTPq5BWOvKWbVFhSRG8bVI4vzyngiJeMlVXNZJiI6jzmTQIaIGSBVDf4NoIgagZfj3oR/BA0vQAArYHJO2TXqre7qXaVZhLL4Ok3RzPBKwN/Dj3iu9r5Rtr66sjMHdSc+48lqZnzTN61swny5itZ+0ZesbYuE0W9GvnZI20WZLWniVpoIuWJ8fHYey1mCVrUDR9xGQKrcZjM4p2vR3PY5ewRxfck+CKJqOiqf0nTFUji2H2dNDKsqjwzZ8qZeXER+fxcrg5vAQ9OZflubktj06xvDn06kigaTfasdKSILfBUmBSlyl7zLMAzsRHwmK5uIuQ40Q8TcgHhCw0nzZdWtJ7Du16qQ/nYz8gCxIY0MHxA5KBXnzBIRFg8BCBaZidEd59/ZS9k6TqfnAEhwHeMwDvUOZ8XCQoHxfBJz+C0/LSuvU/rqrXvlv33MZqmJZzTIyPpGHc15vC+F2OcYuN8VvNd5iWsaGQXWyxGE6Y6vgH2

**Comment by lologarithm** [comment]
Sorry, raid sim isn't fully completed at this time!
