### ISSUE TITLE
Crash Report 2020451095

### ISSUE THREAD

**Issue by Weakflood** [wowsims/wotlk#1271]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1IW1EUft/J0968Yr0VkVunmEkCws17DdTpPTs5OAhdHOugOHRQJ3UK1UF0sFujghQnQSJOksYfBIWSoTVgNFirgqBkUHAMgq3nJRFxc9Ct33Du/b7znXO4P1ZYkCRNfehHHFgAloFNIAsUgCIoS/RehkjDQxd7xkueOqNxtOozqjs/dQ/3DApIq3EDlpTneVI7xxSuXtmiXz/JCsriHwoH1lJk1cjLNVI/jitUyN1VUqlD8qs4kTnkqrkM+blXcoJz26yYTA3mBXbkk4EKD8qbNLdhNxf/TZM6X7wvFnJqnVQhGWDbQb4yzZST3/14se7HpXnftskzTr4FLIOVKe5XK0jXvEOn2WUO+ceMfCHjPx5gxBRQdI23VoOHdgyU1St3uLSOb3n8L9TrOzWEyEvx7w6YQMR2dCxq65ijtXYc7dhOVLOmo04s2tLCO9vWbOHkKZSYzZH8miN1eUahRI6aE3ukp/eoAPMKL2Zg/IYRPqJgaVq816vMrffezEz7yLitZSXrNvWWsO/aSQp9UOLZn3bMe4ou8cz2k/R5DMp31XHktZV50W3HR9wC5jmMcQ==

RNG Seed: 1135587026

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe6640, 0x1232060})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:396
github.com/wowsims/wotlk/sim/common/wotlk.init.2.func16.2(0x72fc2c0, 0x72667e0, 0x7306b40, 0x722eb40)
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/enchant_effects.go:427 +0x4c
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:829
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalizeInternal(0x722eb40, 0x72667e0, 0x7306b40)
	/home/runner/work/wotlk/wotlk

**Comment by JooperGH** [comment]
The blood DPS sim for Death Knights is not close to being alpha ready, I'm going to remove the presets for it as they're just giving people the idea that it is functional.
