### ISSUE TITLE
Missing items: Titan-forged Hood of Dominance, Titan-forged Hood of Salvation

### ISSUE THREAD

**Issue by hyperactivated** [wowsims/wotlk#1272]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
[Titan-forged Hood of Dominance](https://www.wowhead.com/wotlk/item=44910/titan-forged-hood-of-dominance "https://www.wowhead.com/wotlk/item=44910/titan-forged-hood-of-dominance")
[Titan-forged Hood of Salvation](https://www.wowhead.com/wotlk/item=44909/titan-forged-hood-of-salvation "https://www.wowhead.com/wotlk/item=44909/titan-forged-hood-of-salvation")

**Comment by jimmyt857** [comment]
These are added now.
