### ISSUE TITLE
CoI instead of IT option

### ISSUE THREAD

**Issue by Fancybreakfast** [wowsims/wotlk#1277]
I'd like to replace Icy Touch with Chains of Ice in the unholy/sub-frost rotation so I can see how the pvp gauntlets perform in a Death Coil heavy rotation. In general, how can I add a custom rotation?

**Comment by rosenrusinov** [comment]
To add a custom rotation you can checkout the repo and you can find all the rotations in files named `rotation_` in the dk folder. Then you can change the rotation to whatever you like and test stuff like this by hosting the local sim.

Apart from that I dont think your suggestion makes any sense to be a dps increase over the pvp items and the pvp skills. If proven wrong by some data i might add it but as it is now I won't waste time on it
