### ISSUE TITLE
Request: UH DK weapon swap during simulation rotation

### ISSUE THREAD

**Issue by Bioamp09** [wowsims/wotlk#1281]
Currently in the detailed results black magic is shown to be procing multiple times for unholy death knight simulations. Typically when put into actual practice, the unholy deathknight would weapon swap to their main offhand weapon that is enchanted with rune of the fallen crusader. I am requesting that you take a base weapon (I would suggest grasscutter) that is enchanted with black magic and once the gargoyle is snapshotted, the weapon swap to the offhand with rune of the fallen crusader takes place.

**Comment by rosenrusinov** [comment]
Added weapon swaps to UH DK
