### ISSUE TITLE
simulating the item options.

### ISSUE THREAD

**Issue by PrimeIndy** [wowsims/wotlk#1282]
**Is your feature request related to a problem? Please describe.**

i guys, i am a big fan of your tool. good job.
i used GuyBrush Sim. for many months nonstop and loved it.
Your tool has same potential but i missing one key feature:

your tool is not simulating the item options.

the predicted DPS gains or loses in the item swap window are based on the setuped current stat weights which makes it static.
thats why the values are all wrong, not only by the normal simulation error, they cant be right since you do setup it according to your gear including the item in the slot which is going to be changed. 

since the statweights include the stats of an item that is no longer eqiped after you choose one of the item swap options the predictions are kind of useless. you would have to clear the slot empty before calculating statweights in order to make the predicted values usefull.

the key fueature that made guy brush tool not only good but phenomenal is that it solved that problem,
it acuatly simulate through the shown item options by swapping them with your current gear from the same slot.

the additionaly gained information by not only see what would be an update according to my current stat weights but actualy the results of a simulation with that option equiped introduces a whole new dimention to the fun of planing your game with the tool.

**Describe the solution you'd like**

maybe you can add the option to genrate the predicted DPS gains dynamicly.
if acitivated your item option window dont open in an instant and shows you the static results but it goes through every item option and simulate x times with you current gear and presents you the difference. 

**Describe alternatives you've considered**

**Additional context**

if its not possibly, no problem, still good tool, ty

**Comment by jimmyt857** [comment]
#1512
