### ISSUE TITLE
Wowhead link translations

### ISSUE THREAD

**Issue by DavidBabel** [wowsims/wotlk#1283]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It is VERY simple to translate the wowhead links. Just by adding the language setting to the URL.
- https://www.wowhead.com/wotlk/item=44253/darkmoon-card-greatness
- https://www.wowhead.com/wotlk/fr/item=44253/carte-de-sombrelune-grandeur

So a little combobox is very easy to implement, for a very efficient result. And you don't need to translate the whole app, juste items would be far from enough

**Comment by jimmyt857** [comment]
Implemented this via automatic detection using browser language, would prefer to avoid comboboxes unless its truly necessary.
