### ISSUE TITLE
[DKTankSim] Presence

### ISSUE THREAD

**Issue by Kekiqt** [wowsims/wotlk#1298]
Sim:
https://wowsims.github.io/wotlk/tank_deathknight/

I know it is in 'WiP' and completely unfinished, but I like to give my takes and findings :).

Settings:

- Blood Elf
- Engineering
- Jewelcrafting
- Completly naked, no gear at all
- 0 (zero) talent points are set
- no buffs activated
- nothing

Although 'Frost Presence' is active and got a 100% uptime, there is no buff applied on the stats report on the left side. Stamina is still 160 with no additional buffs. It should be 172 (160 + 8% = 172.8 ~ 172 Stamina). Same for Armor but in this setting irrelevant, because the character is naked.

It should be more clear which presence is active. Sure it is for tanking purposes always the frost one, but who knows :). Possibly a presence toggle could be cool.

https://wowsims.github.io/wotlk/tank_deathknight/#eJzjYnBisGIQYpB6x9TEyBaQk1iZWsTBKMAlpcTFQAgqMWhNYGIYBSigiqGJiYOLiYMRGKYMjxgZXjCyfGBkn8XIKZgGBtfsdzAy3mJkUHrIxAnWcKDIQXLWTBA4aW8JMeOCvSJMsdEupoI5tVU8AYklyRnlqUXZCkamCsESHDQP+Q/21DCl4eQRBwq0G1hoFTgSqxgaeB/soTpe2AMAwmwsdw==

**Comment by JooperGH** [comment]
I'll add a presence toggle (not sure the usefulness of it) but as far as the character stats side of things this doesn't reflect the presence because its not applied until a sim is run, and you would not see this there, I'm not sure it's relevant to see this in the character sheet.
