### ISSUE TITLE
[DKTankSim] Veteran of the Third War

### ISSUE THREAD

**Issue by Kekiqt** [wowsims/wotlk#1299]
Sim:
https://wowsims.github.io/wotlk/tank_deathknight/

I know it is in 'WiP' and completely unfinished, but I like to give my takes and findings :).

Settings:

- Blood Elf
- Engineering
- Jewelcrafting
- Completly naked, no gear at all
- 0 (zero) talent points are set
- no buffs activated
- nothing

Veteran of the Third War increase your total stamina by 3%. In my setting where I got 160 Stamina that should lead to 164.8 Stamina. Unfortunately I do not know the rounding system used so I do not know which one is weird.

My Stamina with 3/3 Veteran of the Third War = 164 Stamina which leads to 9581 HP
DKTankSim with 3/3 Veteran of the Third War = 165 Stamina which leads to 9589 HP

Should be the rounding issue.

Attack Power also I got ingame 2 less than in DKTankSim (1065 ingame vs 1067 DKTankSim).

https://wowsims.github.io/wotlk/tank_deathknight/#eJzjYnBisGIQYpCax9zEyBaQk1iZWsTBKMAlpcTFQAgqMWhNYGIYBSigiqGJiYOLiYMRGKYMXYy6BgampoYGhqbGxsYGxsaGhkYGhgZAbKxrbGBqBJQ0MDA2MDIGigBVGj1iZHjByPKBkX0WI6dgGhhcs9/ByHiLkUHpIRMn2IIDRQ6Ss2aCwEl7S4idF+wVYYqNdjEVzKmt4glILEnOKE8tylYwMlUIluCgeUx9sKeGKQ0njzhQoN3AQqvAkVjF0MD7YA/V8cIeAEmpNZE=

**Comment by jimmyt857** [comment]
It looks like this talent is implemented correctly, so the only possibility here is strange rounding behavior in-game. Fixing this will require a much bigger overhaul of our stats, so going to close this for now as the talent is fine.
