### ISSUE TITLE
(DK) Adding Unbreakable armor to a custom rotation breaks the DPS sim when pressing simulate

### ISSUE THREAD

**Issue by Davski** [wowsims/wotlk#1300]
See title.

**To Reproduce**
1. Go to Settings
2. Click on Rotation and choose Custom
3. Add the spell Unbreakable armor to the rotation.
4. Press Simulate
5. See error

**Expected behavior**
When following  these steps you will get a simulation that breaks and does not simulate.

**Sim Links and Screenshots**

https://wowsims.github.io/wotlk/deathknight/#eJztUk1IFGEYnuedafv8/OkrOnx5mvYUC8K3MwzYaaZOHRe8eJVQFuqwSFAKwSIexA52qtVEpEMEIQSB6GogKMRecqFVIUNCaJl+BI/ixd4ZN6JbUN16hudlnvd53vdjhk9mBSkyVEQJZeA58BJYA+pADByB6kTXlUsGEfo5M5FmLljd82fGkCncHhgZHBZQsnsVUqnmDunNPcpmFtepskyyTR19oKw9VyPZqQ5WSb/Za0mh3q2QXtqlZIqN2i5PsfGsSbJLTbK3wR2HpcU65sTOgt3SHWq7yml+T9JKfWO3+eJnR6ip16TjBVs66vMr4vpgOalr1aR+3UwSbxdJf5y3pcWdKd52TpDp7EXB6XfuJR+Ze0jWf/yCUUdA0zH6ZFABPYUrSdhMMImZYTrMLqZgtke4gSJG0uGJ9YgvjT5/uuowdJFrFyc/gEnkPL/H94wJ+PEDzzO+yXtMY/y8yftBvocV+74J9qHFkwapxw3SB5/IrTToSmWLzPQWxXAOcXYG1ntY2S/Ulp5WHopa516MLs1MJ6iFV0879fDyUIrt0KtSafb+aEdh4M7N4t3B4VuuF7h9WvzzqzAe/Y0t5drGn+wxvbnStd8Npz+v/Gg/ak3E4XdylpWn

**Desktop (please complete the following information):**
Windows 11
Firefox

**Comment by JooperGH** [comment]
I've fixed this. Let me just remark that the intention behind Custom Rotation is to set up simple prio systems for short AoE encounters. Its really just a terrible way to detail the rotation for a FDK. As you can check by the timeline, also, the gem optimizer is giving you Epic gems that do not exist in the current live version, you should be careful with this.
