### ISSUE TITLE
Missing items: [Brunnhildar Axe]

### ISSUE THREAD

**Issue by jfenoli** [wowsims/wotlk#1301]
[Brunnhildar Axe] (https://www.wowhead.com/wotlk/item=41752/brunnhildar-axe "https://www.wowhead.com/wotlk/item=41752/brunnhildar-axe")

Also note that the in-game tooltip has an additional + 4 - 6 damage (no damage type listed)
This is not on the item in wowhead for some reason

**Comment by jimmyt857** [comment]
We intentionally don't include common or junk items because there isn't any purpose to adding them. Is there some need for this item?

**Comment by jfenoli** [comment]
it's really slow so I was hoping to test it with fan of knives for different numbers of targets
