### ISSUE TITLE
crit bug

### ISSUE THREAD

**Issue by tinor20** [wowsims/wotlk#1303]
On the Rogue simulator I put all the gear I have and the same spec with the same gems and enchants and it adding crit to me.  in the game on the Character info tab it shows me only having 570 crit rating.  On the rogue simulator it has me having 999 crit rating from armor.  It has my dps why off due to this.  dont know if its a bug for everyone or not

**Comment by jimmyt857** [comment]
Our displayed character stats don't match the value in game; we also include a lot of other stuff, like crit from talents and debuffs.
