### ISSUE TITLE
Missing items: Kibler's Bits

### ISSUE THREAD

**Issue by mmolignano** [wowsims/wotlk#1312]
[Kibler's Bits](https://www.wowhead.com/wotlk/item=33874/kiblers-bits) missing as an option for pet food buff in Hunter sim settings.

**Comment by jimmyt857** [comment]
Thanks for the report! I don't think this is something we want to add though, since the new WOTLK pet food is so easy to get and clearly better. It's not worth taking up UI space for an option that will very rarely get used.
