### ISSUE TITLE
Crash Report -1835199861

### ISSUE THREAD

**Issue by jdwoodall** [wowsims/wotlk#1322]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztkU8oBHEUx+f7Zuz+jNSPHMY6WHuSUvMnBy4znBwctlzkxIEcHOTGaUiRCzmxOcjJZSNRTkq0tQesGqytrU3EheSgvTG/GQ5ScuDme3i9932f3+v1e2ojI046jWAMLrAB5IB7oAzKEbmErgYODXHocHxk7h2hEqgMdEi1UuxUmUYkOTo4MTTOKrgam4Kq8Lk8qVF+t0sJSCrjW2ek3fgW46tXpBXSso+8ZASyehAgVfzYR1LPsiiifHMncBV+eEZ+fL0U6Gz+3Xw6Eeb+hYiPl2JqPkNaaU1WRXdjmxKMKXp1Uu6TWxZJ+tcnTUYYNIpjmiKquJ80j379G7Vapq6bVpvIza9d0xKuJfqWabQZvmf4uWEZluWX19DYwy3xdY+0JY/iyx41L3ikr5zTPZQnRFOorBkOdGHvAQVIiSJVBpu6w05NuHOdU59aEcra7aGTs5s+Xplpivdq7M9PPeP8xhQ3e/Qrc36i8K96ik5nWJftbgzgDZKEcEA=

RNG Seed: 4164932100

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 76 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe73e0, 0x1247360})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x7a7f180, 0x6e11500)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:93 +0x2
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).RotationActionCallback_RD(0x753e000, 0x7a7f180, 0x6e11500, 0x6e1da40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:193 +0x4
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:206
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).DoRotation(0x753e000, 0x7a7f180)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Tank DK sim isn't even released for alpha yet  :)
