### ISSUE TITLE
Crash Report 430195324

### ISSUE THREAD

**Issue by Zilthoras** [wowsims/wotlk#1323]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztUc9LFFEcn+9nhmH24cYzOjzt4DinEoQ3Mw1olx39Cxa8eBVRhDosEkhCMEgH8VDaQVbRS0gEYeDBWH/tRUEXwRbaNjCoEAeWMEghECHqzWoHb0F163P48L6f9/l+vo/vYy0WOCSGKEcR0XOiMlGN6JRQBiJQ93VOgmySFCrL+IUFnwinRLe1q1rza2OMzOzdvvsDw5bJWfNLYpyPr0H8mDIcc2ET+RUwg2+ugaV5/hVE6QMc/awAZvEnRYj9RZ018O1lOKZyVpV+hZ+sQkx+hGPsFKCpemcZ4t2i7hjVpGb8eEPdnSXnND96AxG/UJHVeuQzFbn7Ppn4qJhwvJTw4dOEv30n5Vhah9iLdaYpZaIIx7IMmc7qvXrbJLT/uIRR0yIBm8bA1LYgSH24NkE3pe/dctt9GbR7vu/50vel9KTnBp6U0g0UJZobuAckrPkK+FEM8SWGna/gxuMKZP4tamR8pdQspRoH66hmCkT7pDmfkaoPjwbDxvNnXAubZmcSlDKd50o50/qry1tFbu7BaEO2717/0MjA8B3bC+weYf3z73wY/o2UqLT1Jzmyoy3X9bvm+vKi6YPwoqOW+QmkCYM/

RNG Seed: 3836348336

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe73e0, 0x1248380})
	/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x80d6e00, 0x8107500)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:93 +0x2
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).RotationActionCallback_RD(0x8146000, 0x80d6e00, 0x8107500, 0x813ae10)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:193 +0x4
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:206
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Tank DK sim isn't even released for alpha yet  :)
