### ISSUE TITLE
Adjust the enchants to link to the spell and not the item.

### ISSUE THREAD

**Issue by zaider** [wowsims/wotlk#1330]
**Is your feature request related to a problem? Please describe.**
The enchants on the list are inconsistent on whether or not the link is to the spell of the enchant or to the item that teaches the enchant.  If the link is to the item you can't see the materials required for the enchant. 

**Describe the solution you'd like**
Adjust the enchants to link to the spells instead of the items.   
Example: 
https://www.wowhead.com/wotlk/spell=60692/enchant-chest-powerful-stats
vs
https://www.wowhead.com/wotlk/item=44489/formula-enchant-chest-powerful-stats#teaches-recipe

**Comment by avidal** [comment]
@zaider Is this still an issue? Looking at the site right now, I'm seeing consistent spell tooltips for enchants (vs the formula item tooltip).

**Comment by jarveson** [comment]
yea looks like this is fixed, or not sure exact links its referencing, looks like the enchant dropdowns are all using spell links now
