### ISSUE TITLE
DK Tank Enchants Provide Wrong Defense Values

### ISSUE THREAD

**Issue by wlfbck** [wowsims/wotlk#1332]
**Describe the bug**
"Rune of the Nerubian Carapace" and "Rune of the Stoneskin Gargoyle" seem to provide "defense rating" instead of "defense". See attached screenshots of actual vs sim. I did not check if the stamian bonus is correctly simmed, might be worth looking into as well.

**To Reproduce**
1. Equip white vendor value ingame without rune.
2. Equip white weapon in sim.
3. Compare defense and defense rating values.
4. Enchant rune both ingame and in sim.
5. Compare defense and defense rating values.
6. Notice the difference.

**Expected behavior**
Both runes should increase defense.

**Sim Links and Screenshots**
![grafik](https://user-images.githubusercontent.com/1621804/196060096-0b9016d0-39a2-416e-a8c5-617a963c804f.png)
![grafik](https://user-images.githubusercontent.com/1621804/196060102-110fb98d-9085-42e9-9eaa-313788b0eef0.png)

**Comment by JooperGH** [comment]
Thank you for catching, fixed. Keep in mind the Tank sim is super WIP, don't use it realistically.

**Comment by wlfbck** [comment]
Good to know, but so far i have been using it to "sim" where i would end up defense wise (and if i'm still crit capped).
