### ISSUE TITLE
No gear/gear options/presets load in when opening the website

### ISSUE THREAD

**Issue by leavitt1102** [wowsims/wotlk#1336]
When I open the website it will not load any class/spec's gear, preset talents, or saved sets. Also you cannot click on any gear slots to add any gear.

1. Just open the website by either typing in the website or clicking a link.

**Expected behavior**

 - OS: Windows
 - Browser: chrome and windows edge
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by jimmyt857** [comment]
#1509
