### ISSUE TITLE
Not working on phone

### ISSUE THREAD

**Issue by Nighthuntah** [wowsims/wotlk#1338]
**Describe the bug**
When trying to acces the site on phone, iphone 11. it keeps reloading the page and sometimes just crashes completly.

**To Reproduce**
1. Go to anything
2. Click on anything
3. Scroll down to anything

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: iphone 11. OS: 15.6.1
 - Browser tried with safari and opera. 
 - Version newest.

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: 15.6.1
 - Browser Safari/Opera
 - Version newest.

**Additional context**

**Comment by jimmyt857** [comment]
#1509
