### ISSUE TITLE
Death Knight - Display Army of the Dead cast under Detailed Results Timeline when "As a Major CD" is selected.

### ISSUE THREAD

**Issue by JoeyWButler** [wowsims/wotlk#1342]
**Is your feature request related to a problem? Please describe.**
Players are debating about whether or not Army of the Dead after a gargoyle snapshot is a DPS gain or loss over using it at prepull.

Currently, Army of the Dead does not appear inside the Detailed Results Timeline when the option "As a Major CD" is selected. 
 
As I understand it, Army of the Dead is used after ERW and during the window on the simulator, but seeing the cast on the timeline would be helpful.

**Describe the solution you'd like**
Show the cast of Army of the Dead under Detail Results Timeline or Log.

**Comment by rosenrusinov** [comment]
Army of the Dead channel time has always been present in the timeline when used As Major CD (And I just went and confirmed its still there and visible)
