### ISSUE TITLE
Purple Gems adding too much DPS

### ISSUE THREAD

**Issue by EdogawaHolmes** [wowsims/wotlk#1344]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Need a link to your settings and a bit more information in order to debug this.

**Comment by jimmyt857** [comment]
Closing because OP hasn't responded.
