### ISSUE TITLE
Subjugate Demon import bug

### ISSUE THREAD

**Issue by Mupki** [wowsims/wotlk#1347]
**Describe the bug**
Using WowSimsExporter WOTLK addon, it gives me an error when I have Glyph of Subjugate Demon.
The error produced is:
Import error: Error: Unknown glyph name 'Glyph of Subjugate Demon'

I believe it exists because Subjugate Demon was renamed from Enslave Demon.

If I replace Subjugate with Enslave in the import code, it Imports correctly.

**Comment by jimmyt857** [comment]
#1371
