### ISSUE TITLE
Crash Report 2073886492

### ISSUE THREAD

**Issue by Gandri11** [wowsims/wotlk#1363]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUkFIFFEYnv+fcXy+lJ7i4bWnaU9iBG/esKAX922nuq10qaOEItRhWYJKCJYoDE/SQcySyEME4aWo1HYhwpCFaJcGClYIElqWkOgU3ex/Mx46Ctatb+Cfme/7v//9M3w8w1DhNJSgAvAYoAnQAfgF2EQ8NRCgIeU2wHwirgEMOJl7XTfAL16auDZZZt2iJ7MBXIhmFWXjM2b9t2+wuobcE+0a8j7xgfgt4t2vRDKx+wxla9Ulw4vnKOvbZCDBGo6IxlOUm8SAw3vFOsmfVt0sOvbtZ40aqes9NQpRX0HZfpJa2wlzp4WyQ93+wvr+6XOPbP2yZ+tuzdbvDbvA61co320jd4jZWsEso8/3i+45b3iejvqPPzHjMZBYPs3HhA1AAEOooJBqY+ZMcq8UzHj6MG7Op9KosXG6agNFyVlMMuMJmjQHJyKltYq00lEU5UJF0CrUOox0FOpceDJSObosq3dAsgcxiuUY5WKMwWyMQ9U9VLdi7ID3A7qX4Cj3ucceziLv4i572dcCJ/sNe9J9pkx/us+gObZ016KeH02ZZv74VIKPeb2BpfvXZ3qLE5cvTF+ZLF8MdC44K9k/j8NN8zemVOqbh5mjRoZLhYM2Jz+vsrBj9h2d/G/y64y8

RNG Seed: 2823976584

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe7680, 0x124b3c0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Dot).basePeriodicOptions.func2(0x7a260e0)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:123 +0x3
github.com/wowsims/wotlk/sim/core.NewPeriodicAction.func2(0x7a260e0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:86 +0x3
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x7a260e0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:327 +0x43
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x7a260e0)
	/home/runner/work/wotlk

**Comment by TheGroxEmpire** [comment]
This seems to not be an issue anymore. Closing the issue as it has been resolved.
