### ISSUE TITLE
i cant do warrior arms sim

### ISSUE THREAD

**Issue by Ocelotchimes** [wowsims/wotlk#1364]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kcthebrewer** [comment]
My Stat Weights either don't start or they freeze with no error

**Comment by rosenrusinov** [comment]
No issue description, no steps to reproduce, no information about environment, no additional context
