### ISSUE TITLE
Missing items: [ITEMS] Mage T7.5 Pants

### ISSUE THREAD

**Issue by darcdisc** [wowsims/wotlk#1366]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=40417/valorous-frostfire-leggings

**Comment by psiven** [comment]
This item is both accessible and present in the P1 Preset. Have you tried restoring defaults?

**Comment by darcdisc** [comment]
Looks like I had an older, cached version where the T8 pants were showing up instead. Force reloading did the job.
