### ISSUE TITLE
Glyph of Subjugate Demon - Warlock - Causing import issues.

### ISSUE THREAD

**Issue by Bookofmormon1** [wowsims/wotlk#1371]
**Describe the bug**

**To Reproduce**
1. Go to https://wowsims.github.io/wotlk/warlock/
2. Click on Import
3. Use Import String {"talents":"2350002030023510253500331151-000000000000000000000000000-55000005010000000000000000","glyphs":{"major":["Glyph of Haunt","Glyph of Life Tap","Glyph of Quick Decay"],"minor":["Glyph of Unending Breath","Glyph of Subjugate Demon","Glyph of Drain Soul"]},"class":"warlock","race":"Gnome","name":"Bookofmormon","gear":{"items":[{"enchant":3820,"gems":[34220,40051],"id":39409},{"id":40680,"gems":[]},{"enchant":3810,"gems":[40051],"id":40424},{"enchant":3825,"gems":[],"id":40251},{"id":39497,"gems":[]},{"enchant":2332,"gems":[],"id":41908},{"id":40197,"gems":[]},{"id":40696,"gems":[40051,40051]},{"id":42002,"gems":[40050,41467]},{"id":39254,"gems":[]},{"id":40719,"gems":[]},{"id":39389,"gems":[]},{"id":40255,"gems":[]},{"id":40682,"gems":[]},{"enchant":3855,"gems":[],"id":37360},null,{"id":40284,"gems":[]}]},"professions":[{"name":"Enchanting","level":235},{"name":"Tailoring","level":250}],"level":80,"spec":"","realm":"Grobbulus"}
![image](https://user-images.githubusercontent.com/116230834/196821972-6969b8d3-a90c-4c7a-8ea1-a5d5c4cffefc.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser: Chrome
 - Version: [e.g. 22]

**Additional context**

**Comment by Bookofmormon1** [comment]
To add to this, I removed the glyph and now I am getting error. 
![image](https://user-images.githubusercontent.com/116230834/196822333-e2114a73-21d6-4ced-a839-f9d65067e4bc.png)

**Comment by Anipsy** [comment]
Temp fix is to rename it to "Enslave Demon" in import text.

**Comment by Bookofmormon1** [comment]
Thank you for the response. I will do that! Luckily I was able to manually
input my gear using the pre-raid Bis list.
