### ISSUE TITLE
Missing items: BOA/ Heirloom gear

### ISSUE THREAD

**Issue by shnaza** [wowsims/wotlk#1373]
Hi there,
Could we please include the BOA/ Heirloom gear, please

https://www.wowhead.com/wotlk/item=42949/polished-spaulders-of-valor#comments

**Comment by jimmyt857** [comment]
We could definitely look into adding these, but I'm hesitant to do so if we can't get the wowhead tooltips to work. According to https://www.wowhead.com/classic/tooltips we should be able to set 'lvl=80' in the data-wowhead, but this didn't work when I tested it.

**Comment by shnaza** [comment]
No Stress mate,
İ know that some BOA items at 80 out perform some pre-raid bis items.

Thank you for all the work you do.
