### ISSUE TITLE
Export all gear in bags and run simulations on all gear you own to find the best configuration.

### ISSUE THREAD

**Issue by bxyoung** [wowsims/wotlk#1379]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the export addon to export all gear in my bags. Then have it simulate all different variations of all the different gear options that are in my bags to be able to tell me "This is your best configuration based on the gear you own."

**Describe alternatives you've considered**
Only alternative is doing this manually.

**Additional context**
n/a

**Comment by jimmyt857** [comment]
#1512
