### ISSUE TITLE
Crash Report -515352624

### ISSUE THREAD

**Issue by cloudsMountians** [wowsims/wotlk#1381]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJzjkuRgMmCyYAxgSmBsYGRcwch4gZHxASPjC0ZGJxEORgUmB8YCkMQCsNwORkYhBqk3LE2MbAE5iZWpRRwcAoxS/YxcPAL/NzEpsR09xLRpBxMXi8C6E0xcnALT9jApMe8DCnAIXDjBJHHwJjNQ6vJSJi5ugVXbmCS67zApMTIAOXN3M0lsgHC4BFqXMSmxtO5gYgCqXTkJpPf4HiaJ82C9T/6DDH8MJj8uB5Gv9oLIxiUg8heY3bEP6BCgpxgDWLQmMDGMAhRQxcLBKMG0iVGbS4yDSYBRglWB0ZaBQcHRgdVDLhbEAMYvPxc3x38YYBRI6WIMNzUwNjIwMDY0MjUGEkCOobGxgamxoaGRsaGuAV6ga2RgCtRqANSGAR4xSnA03GcSuL6fSeLmfiaFX/eYNI5fYjI4fInpAyPjLEaGW4wMSneZOMFOb0hzEIR4QsRBctZMEDhpbwkRuWCvmAYG1+yN1jIpBEtw0DzuWxyoYUrDySNUMYcYAAkrn7sOjhD+D3sPxgRGAPFUedI=

RNG Seed: 934079976

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe8cc0, 0x126e3e0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/druid/feral.(*FeralDruid).checkQueueMaul(0x33ae400, 0x20a47e0)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/rotation.go:75 +0x94
github.com/wowsims/wotlk/sim/druid/feral.(*FeralDruid).OnAutoAttack(0x33ae400, 0x20a47e0, 0x33b6960)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/rotation.go:33 +0x11
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).TrySwingMH(0x3387d00, 0x20a47e0, 0x2a86a00)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:483 +0x24
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).SwingMelee(0x3387d00, 0x20a47e0, 0x2a86a00)
	/home/runner/work

**Comment by StevenWMurray** [comment]
This crash seems to appear any time a non-None Bearweaving option is selected, but Mangle is not talented into in the talent tree. The crash appears to be independent of RNG seed selected.

**Comment by jarveson** [comment]
oops, thought i fixed this, can fix the crash, no real guarantees on rotation though if you also dont have mangle/trauma selected as raid debuff (should be fine otherwise though) or try 'in front of target'
