### ISSUE TITLE
Heroes' Bonescythe Breastplate socket bonus has too much impact on DPS (10x expected amount or more)

### ISSUE THREAD

**Issue by galhast** [wowsims/wotlk#1382]
**Describe the bug**
While simming gems in my Heroes' Bonescythe Breastplate, I found that if I broke the socket bonus (+6 critical strike rating) I would lose approximately 152 DPS on my simulation. 6 critical strike rating should only have a minute effect (10 dps or so). 
I've seen this bug before with other critical strike rating set bonuses - the simulation seems to give them far too much weight.

**To Reproduce**
1. Load up a gear set using the Heroes Bonescythe Breastplate.
2. Gem the breastplate with useless stats, but match the socket bonus requirements and run the sim.
3. Remove the gems, breaking the +6 crit strike rating socket bonus, and run the sim.

**Expected behavior**
Should expect to see a relatively small ~10 dps loss.

**Actual behavior**
See 152 dps loss.

**Sim Links and Screenshots**
Current setup: https://wowsims.github.io/wotlk/rogue/#eJztUs0rRFEUf+fMNZ4XuqRcVuPtKHXnvV6N1Tz+AmUjKxIpFpOUj1JDkhRmpUjsECmFaXylsDClKOVjGKFokoWVBRbOe2NhqbBzup17Pn6/c+4992qFKkpsgRCGAeYBYgDHACmAqnwBPgyADbUQgiE3ma8UJ1g/eKvbGrqb2tVM7i3eBY3z6CGKo2vUvdE9fI2hxnjfOmo5PLqF4vwWdM/0DGoqP9lEkVjyEGFwjQhXRNiLYZIIuTwygmL/EnVGEUXL5stEPVvy6Kg43ss2YanyQhyJvUq5h0WK7MTcdjl8bBRFitAeB8D48LqrZx39tO3o5IVzgJs5FDPLQNb7Stpi/G0FdU4zgFpWz7qApkB3LYtQ33/5Kj1MBYF1QstVkTOBPpQskGFn0J9gHAUMQ6mUlilNR1uGnzZD+qVpmn5p+cvJdZdZbknjDlT14B558ghTwJ4hcxKUBCj6I2a5vcLNdl66a4FdNDnhSDxYkY4cB0uaXTkNGhsYmurtya5u6Ghs6Wxqb/UZlq9GqH/+egP2b1QJx/d/UkcGykKV3wW7wwuP39mfjFTwAzq0faA=

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.119

Reported a similar issue in this ticket: https://github.com/wowsims/wotlk/issues/870

**Comment by jimmyt857** [comment]
Most likely you are deactivating your meta gem.

Feel free to reopen this bug if that isn't the case.
