### ISSUE TITLE
Missing items: Event Rings from Hallows End

### ISSUE THREAD

**Issue by Nefaroz** [wowsims/wotlk#1383]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=49121/ring-of-ghoulish-glee
https://www.wowhead.com/wotlk/item=49123/the-horsemans-seal
https://www.wowhead.com/wotlk/item=49124/wicked-witchs-band

**Comment by psiven** [comment]
Please ctrl+F5 to force refresh the page, if they don't show up they will be listed as Phase 5 gear
