### ISSUE TITLE
Improved Unholy Presence

### ISSUE THREAD

**Issue by sam-chipp** [wowsims/wotlk#1388]
**Describe the bug**
Speccing into improved unholy increases dps by approximately 180 dps for 2h. The rotation (timeline) does not switch back to IMP UP at any point, meaning it should only be up for around 16 seconds. 10% rune cooldown reduction for 16 seconds surely does not equal to 180 dps. It seems the 10% is being applied for the entire fight length. The rotation would need to either a. switch back to UP after hero or stop calculating this effect once in blood pres.

**To Reproduce**
use the talent build here: https://wowsims.github.io/wotlk/deathknight/#eJztUj9oE2Ecvffumn45bf0sDp+ZYnCQQuByR6FOd4qDg0PAJaMKFgcHdbJOQRxKHeqYBhTpJEhEdIkaodCCZGrANAVriwiWiBU6Bpf6u7t0cHOom+/u/T7e+/3jO84tKGp6vIFbqALPgJfAMtAB+sAA7JDndZ4eIlSkZi6pmeA0cq9G7iNTvnl19vodZWs314Kr9c4Gzdo2C5nmCnv7dLN68JkFu9WkO6Z/tmg+bA+l0h/f0TQ3GXdJor0pXU/ajHPjel5yq+I4Ii3RfanYaNhDfVT33qbV8kr/rmR3nosj2XT2wnuafsN2Hf39NSU+fBPHF0tx/LEWVyzLhi9PbdcSZ0GmHVP0xqZRdirO3fiak49o/ccfuOcoGP7CNfdCDVjCaZcqK4SQQluYEY4IR4WOcFwxQhkV+3Y6Yy+cTc65lWjCypnjB24ek0fU/gEwj2Ix8D1vSh6BX/QDT2QQiAz8UmJK9L2gFASlqdJXGPW4S737jabeZb7W5ZnaOr3Fdfbh7GG0DusTrMIWs8nC6kw0XH0iOllfjNEOz6ZOJzw1k6AX+g3mLxv1z/+FB9FhTKm2Vw9lzt8g/VaXtqJzqR6EF3EFvwHdgpBi

Points in dirge produces the difference.

**Sim Links and Screenshots**
As above

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 106.0.5249.103

**Comment by jimmyt857** [comment]
This talent looks to be implemented correctly; I think this may actually be a 180 dps improvement, at least for your particular sim. When the faster CD means 1 extra rune, that's a whole extra ability cast (possibly more from multiple types of runes).
