### ISSUE TITLE
wrong jwerly

### ISSUE THREAD

**Issue by KafkaSea** [wowsims/wotlk#1389]
**Describe the bug**
[Valorous Plagueheart Gloves](https://wowhead.com/wotlk/item=40420) need blue jwerly

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Wowhead currently shows the socket as red and we get our data from them.

Closing this bug because this isn't something we can solve; report it to wowhead though!
