### ISSUE TITLE
Plush Sash of Guzbah incorrectly shows two available sockets

### ISSUE THREAD

**Issue by BreakBB** [wowsims/wotlk#1392]
**Describe the bug**
The item [Plush Sash of Guzbah](https://www.wowhead.com/wotlk/item=40696/plush-sash-of-guzbah) has one available gem socket, but is incorrectly displayed with two.

**Expected behavior**
Only one yellow socket should be available.

**Sim Links and Screenshots**
![grafik](https://user-images.githubusercontent.com/33514570/197237352-39dc6beb-56fe-4b1b-bf8f-7f390e1e9c77.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 106.0.1 (64-Bit)

**Comment by psiven** [comment]
It's a belt buckle, all the belts assume you get one
