### ISSUE TITLE
[Warrior] Strength of Arms talent only gives 3 expertise instead of 4

### ISSUE THREAD

**Issue by RobinsonFred** [wowsims/wotlk#1394]
**Describe the bug**
When Strength of Arms talent (in the Arms tree) is talented 2/2, the sim only gives 3 expertise instead of 4.

**To Reproduce**
1. Pick the Strength of Arms talent in the Arms tree
2. Place 2/2 talent points
3. Mouseover the Expertise row in the stats section
4. See that expertise from talents is only 3 (33 rating). 

**Expected behavior**
The talent tooltip shows that it should give 4 expertise when selected 2/2.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/17479798/197289250-931780b6-c9f2-4721-ac81-dfc61fd61816.png)
![image](https://user-images.githubusercontent.com/17479798/197289279-aedbec3a-17c0-4451-83f9-b808a76eb219.png)

**Comment by TheGroxEmpire** [comment]
This is definitely a UI issue as 33 expertise rating should be exactly 1% reduction or 4 expertise.

**Comment by beltsmith** [comment]
Looks like a float precision issue:
```typescript
} else if (stat == Stat.StatExpertise) {                                                                
    const val = (Math.floor(rawValue / Mechanics.EXPERTISE_PER_QUARTER_PERCENT_REDUCTION)).toFixed(0)   
    console.log(`RAW ${rawValue} EXP ${Mechanics.EXPERTISE_PER_QUARTER_PERCENT_REDUCTION} value ${val}`)
    displayStr += ` (${val})`;                                                                          
```
```RAW 32.78999999999999 EXP 8.1975 value 3```

```
> 32.78999999999999/8.1975
= 3.999999999999999
> 4 * 8.1975
= 32.79
 ```

It can be worked around by casting to a fixed point number with 2 decimals:

```
> Number((32.78999999999999).toFixed(2))
= 32.79
> Number((32.78999999999999).toFixed(2)) / 8.1975
= 4 
```

Not the best solution as it relies a number->string->number cast, a more robust fix could be having things which provide expertise rather than expertise rating being handled separately.
