### ISSUE TITLE
Crash Report 661090507

### ISSUE THREAD

**Issue by dgx** [wowsims/wotlk#1404]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjEudgMmDKYCxgbGBkXMHIeIGR8Qcj0wUmJid+BSYHoHAHWHgHI6MQg1QnaxMjW0BOYmVqEQeHAKfUQUYuAYELe5gkzt9jUmLbdphp5UkmLhaBZ3uZuHgFLgHFjwPFmdcABTkELp9gkri1lhmoYdtWoIY7QA1PdzABERe3wPlNTBJHbjMpMTJw8QnsBEpfX8usxAKUY+DiEdi8CKh02k6wUgGBk4uYJJ6tBooArYKITLrFJPECqB6k5hBQhFNg0lmgrSBJFoGuZSDy3XkQ+WYvyB0/NzNJXLvDxMUAFOnZx6TEAfQ/WwBzBIvWBCaGUYACqlg4GCWYihy5zAUYJzAyKjA6QsTtHDzBdIOjQyCEEegQCZGydAClpQpQauoApxkWAaARXYwaxgZGRkBsYGRsbGxqaGBgCGQbGhkZGhsZGxqZGuoaG5jqGhkYGz9ilOCYf5lJYO5lJokZl5kUWi4zaTRfZjJovcz0gpHlAyP7LEaGW4wMSq+YOCFWpzkIQqwWcZCcNRMETtpbQkQu2CumgcE1e6NdTAVzaqt4AhJLkjPKU4uyFYxMFYIlOGge6y0O1DCl4eQRSswxsNAqcCRWMTjwGqY9coDqeGEPAN3aiVI=

RNG Seed: 946490891

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 111 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe8c20, 0x126f3e0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Dot).basePeriodicOptions.func2(0x7a27340)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:149 +0x4
github.com/wowsims/wotlk/sim/core.NewPeriodicAction.func2(0x7a27340)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:86 +0x3
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x7a27340)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:327 +0x43
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x7a27340)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:273 +0x43
github.com

**Comment by TheGroxEmpire** [comment]
This seems to not be an issue anymore. Closing the issue as it has been resolved.
