### ISSUE TITLE
Crash Report 1945711030

### ISSUE THREAD

**Issue by necronaut1** [wowsims/wotlk#1413]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjkudgMmDKYCxgqmBsYGRcwci4gZHpAiPjC0bGH0AGE5MTvwKTA2MBYwdYcgcjoxCDVA9rEyNbQE5iZWoRB7sAp9RhRi4Bga1bmSTO32NSYjt6iOnaDiYuFoHVJ5i4eAUu7WGSOA4UZ34KFOQQ6F/GJHFrLTNQw1mgxPk7QA17djABEVCkazeTxJHbyCI7gYZeX8usxAbUDNLPI7B5EROYdw0sf3IRk8Sz1UxweQGBSbeYJF4g6WAR6N0HIruWgch350Hkm70gl0zYxSRx7Q4TFwNQ5DjQVA5gSPAGMEewaE1gYhgFKKCKhYNRgqnIictCgHECI6MjRNTPwRNMNzg6BEIYgQ6REClLB2CaYgSnKWDKmQFONiwCQDO6GDWMDYyMDIyNDIyMjY1NDQ0MDA2MDAyNjAyNjYwNjUwNdY0NTHWBCowfMUpwzL/MJDD3MpPEjMtMCu2XmTT2/GcyaL3M9IKR5QMj0yxGhluMDEp3mTghtqc5CEJsF3GQnDUTBE7aW0JELtgrpoHBNXujtUwKwRIcNI/lFgdqmNJw8ghVzCEGQMLK564DNH5/2HswJjACAI1bhzc=

RNG Seed: 2189568617

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xe8ec0, 0x1272420})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Dot).basePeriodicOptions.func2(0x6feda40)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:143 +0x4
github.com/wowsims/wotlk/sim/core.NewPeriodicAction.func2(0x6feda40)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:86 +0x3
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x6feda40)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:327 +0x43
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x6feda40)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:273 +0x43
github.com/wowsims/wotlk/sim

**Comment by TheGroxEmpire** [comment]
This seems to not be an issue anymore. Closing the issue as it has been resolved.
