### ISSUE TITLE
JC trinkets don't show EP values for gems

### ISSUE THREAD

**Issue by robertjdac** [wowsims/wotlk#1417]
Steps:
1) Go to protection warrior sim
2) Select Figurine - Monarch Crab in first trinket slot
3) Select Figurine Monarch Crab
4) Go to first gem slot tab
5) Observe there are no values for EP for any gems. 
6) Observe that TBC gems are prioritized higher in the list than WotLK gems

Expect to see EP +/- values, and WotLK gems listed above TBC gems

Windows 10 desktop PC
Firefox browser version 105.0.3

https://imgur.com/a/2yw6ckZ

**Comment by jimmyt857** [comment]
We have EPs for all trinkets hidden because trinket actives/procs can't be measured properly and therefore EP gives unintuitive results.
