### ISSUE TITLE
Displayed number for hit rating not including buffs/talents

### ISSUE THREAD

**Issue by PullyPushy** [wowsims/wotlk#1421]
With most BIS guides, the Hit Rating number given is usually the same as what you see in the in game character screen. It makes it easy to know just which number you need to reach ( excluding including talents and raid buffs. )

It makes it harder to theorycraft on the sim when the hit rating has buffs and talents included. It would be extremely useful to show a number in the sim that is relatable to the number in the in game character menu.

Thanks!

**Comment by Teebown** [comment]
The magnifying glass next to your hit rating and % gives you a detailed breakdown of sources of hit.

**Comment by Teebown** [comment]
![Screenshot_20221023_093144](https://user-images.githubusercontent.com/108202746/197397909-8980e6b5-ef8c-49ad-ac10-d649077e903e.jpg)

**Comment by PullyPushy** [comment]
ahhhhh brilliant, should have noticed that. my bad! thanks for the great sim
