### ISSUE TITLE
Option to easily toggle raid buff on/off, so you can test your sims against a dummy to check rotation

### ISSUE THREAD

**Issue by bamsillo** [wowsims/wotlk#1423]
like title says, an option to toggle the alll the buff on/off with one buttom if possible :D great work on the sim, thx for taking time to develop this tool :D

**Comment by jimmyt857** [comment]
We have to be extremely careful about adding new UI elements, there's already a ton of info on the screen and users get confused really easily.

I don't think a feature like this would get enough usage to make it worth the extra bit of complexity, there's already a very simple workaround: just click on/off all the buffs. It doesn't take that long, and you can create a saved preset with all buffs / no buffs if you want to.

**Comment by bamsillo** [comment]
oh, i didnt know you could that, i guess that is more than enough, thx for replying, i mention this option, since in raidbots.com when youre simming in retail, you could just mark raid buff on and off, but since you mention i can create profiles, is almost the same, Gg and again, thx for the develop of this tool :D
