### ISSUE TITLE
Elemental Oath not increasing damage with Clearcasting.

### ISSUE THREAD

**Issue by ambiwar** [wowsims/wotlk#1427]
**Describe the bug**
Clearcasting damage bonus from Elemental oath not implemented.

**To Reproduce**
1. Sim DPS with Elemental Oath
2. Sim DPS without Elemental Oath
3. There is no change in damage done by spells

**Expected behavior**
Spell damage should be increased 5% per rank of Elemental Oath while clearcasting is active.

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/1536
