### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by PhilGreenfly** [wowsims/wotlk#1428]
Does not find any IDs of shadow priest gear when importing using WowSimsExporter addon - 40287, 44657, 40450, 39425, 40602, 37884, 39519, 40271, 40448, 40326, 40433, 40108, 42132, 42988, 40395, 40192, 40245

**Comment by HopelessRomant1c** [comment]
Kel'Thuzad's Reach is missing

**Comment by jimmyt857** [comment]
I definitely see those items in the sim. Perhaps your page failed to properly load?

**Comment by PhilGreenfly** [comment]
Hey James, thanks for the reply. I have tried multiple times, I export my current gear using WowSimsExporter addon (current version) and insert the string into Import -> Addon window. It says that the import was successful but none of the item IDs was found. Not sure what am I doing wrong tbh.

**Comment by PhilGreenfly** [comment]
Seemed to have been a browser problem. Fixed =)

**Comment by jimmyt857** [comment]
Thanks for confirming!
