### ISSUE TITLE
Libram of Radiance incorrect value

### ISSUE THREAD

**Issue by dahun0** [wowsims/wotlk#1430]
Libram currently showing 79 crusader strike increased damage should be 98.  All databases show the wrong value for this item. It was probably changed at some point in wotlk life cycle.

![xxUcSJL](https://user-images.githubusercontent.com/31947217/197422747-96c741cc-e827-42d0-bdde-17ecc7ed8cc3.png)

**Comment by Teebown** [comment]
I don't know this for sure, but do you happen to have talents that add 25% to crusader strike?  Wowhead comments suggest this tooltip will be modified by talents and PVP gloves.

**Comment by dahun0** [comment]
ya i do

**Comment by jarveson** [comment]
in this case then its just the tooltip updating, correct value would still be 79, viewing the item on any other class will show 79
