### ISSUE TITLE
Optimize gems uses gems not appropriate for Phase 1

### ISSUE THREAD

**Issue by Rerox-WoW** [wowsims/wotlk#1431]
**Describe the bug**
The "Optimize gems" feature uses epic gems that are not currently available in the game in Phase 1.
The Sim should at least offer the option either to limit Gems to a certain phase or quality/itemlevel.

**Comment by jimmyt857** [comment]
Could you clarify which gems are being used that shouldn't be?

**Comment by jimmyt857** [comment]
Fixed now
