### ISSUE TITLE
Issue with Chest Enchants

### ISSUE THREAD

**Issue by hitgub53** [wowsims/wotlk#1438]
**Describe the bug**
Hi 
So there seems to be an issue with the rating of the chest enchants "Super Stats" (+8) and "Powerful Stats" (+10). 
First of all the latter is displayed as inferior in the enchantment menu and also seems to sim worse on average.
I know the difference for +-2 overall stats is not too big but it bothered me nonetheless.

**To Reproduce**
1. Go to '(https://wowsims.github.io/wotlk/mage/)'
2. Click on 'Chest and Choose either enchantment'
4. See error as described above

**Expected behavior**
refer to above

**Sim Links and Screenshots**
Sim with +10 enchant compared to reference with +8
![image](https://user-images.githubusercontent.com/68532271/197610620-cef80b30-d990-4e1f-9c39-123510a787ae.png)

Thanks for the tool and for dealing with everything!

Sincerely yours
Aikana - Razorfen

**Comment by jarveson** [comment]
![image](https://user-images.githubusercontent.com/536093/197898198-86f125fc-4337-4ecd-9a32-be1856343cf6.png)

Seems to be correct, unknown if other bug was recently fixed, also stats look to change as well on the page, just using w/e defaults for mage

**Comment by jimmyt857** [comment]
#1507
