### ISSUE TITLE
Focus Magic Percent Uptime bug

### ISSUE THREAD

**Issue by zwedegamer** [wowsims/wotlk#1441]
**Describe the bug**
In your wotlk-simulator, I can not take advantage of "Focus Magic Uptime" when I am not specced inte Focus Fire which is annoying. Let's say that I am playing a Mage-spec that is not using Focus Fire (like frostfire bolt spec) talent but I get the buff from another Mage. Then I should get +3% crit, with that spell cast on me. Now, when I spec into TTW Fire Mage (it gives me 3% crit if the target that I cast the buff on crits), it instead gives me +6% crit which is wrong (it should be +3%). The only way to get 6% crit through this buff is by using the buff on someone else that crits, AND the person using the buff on myself. Right now, I either get 0% if I don't have the buff (which is not always the case since people can use the spell on me even if I don't have the talent) OR 6% by talenting into it (which is not correct either, as it should be 3%)
![92e7ba35d265451edfe650c7f5ffe485](https://user-images.githubusercontent.com/116602843/197638326-04f74497-fb6c-4f13-bd2a-770de5fb8373.png)

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
![92e7ba35d265451edfe650c7f5ffe485](https://user-images.githubusercontent.com/116602843/197638297-c1cdef83-5bea-446d-b52c-bf526e387acc.png)

**Comment by PANDAxBEARS** [comment]
This is definitely a bug. Right now when you talent into Focus Magic the sim is applying a static 3% spell crit buff AND another 3% based on what's set in focus magic percent uptime. What we should be doing is:

if the Focus Magic **talent** is present, add 3% spell crit * focus magic percent uptime / 100

if the Focus Magic **buff** is applied, add 3% spell crit

There's actually a lingering todo in mage/talents.go that describes this exact problem, I'll post a PR that fixes this behavior and removes the TODO.
