### ISSUE TITLE
Rogue - Poison Procs

### ISSUE THREAD

**Issue by raal657** [wowsims/wotlk#1445]
**Describe the bug**

Poison procs for rogues is incorrect based on the patch.  In 3.1 rogue poisons changed to PPM for instant poison.  The sim appears to be using the old rules for poison procs, not 3.1.

**To Reproduce**

Easy to do is to run the sim with pre-bis with 2x Librarian cutters w/ berserking.  It's more damage than Sinisters Revenge/Webbed Death which is prebis after the poison changes in 3.1 (it was changed back in the day because blues were better than raid wepaons).

**Comment by b-r-a-n** [comment]
Thanks for the report!

Instant poison is currently implemented as PPM (https://github.com/wowsims/wotlk/blob/8a2e490f3f34caf91a1944e8467eddc0971cecb1/sim/rogue/poisons.go#L304).

I also checked the scenario you described and cannot replicate it (2x Papercutter sims about 300 dps worse for me).

It sounds like there could be some kind of poison configuration issue (e.g. deadly poison on the offhand) so double check that.

I'm going to close this issue but if you can reproduce it please reopen. You can also export your settings to help with the investigation.
