### ISSUE TITLE
ATTACK POWER is higher than the data in game

### ISSUE THREAD

**Issue by Kerwin75631591** [wowsims/wotlk#1450]
**Describe the bug**
3268 in sim
3098 in game

![D77CD049DBA2F812D9FAFAD262273EDE](https://user-images.githubusercontent.com/42667842/197683091-e686215d-d924-4523-a200-baf00c0ebe8e.jpg)
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/42667842/197683807-18f775ce-c8fd-4bf9-a868-e6bf5c38a79e.png">

**Comment by rosenrusinov** [comment]
Can you please provide a link to your sim configuration by clicking the Top Right -> Export -> Link and paste the link as a comment here @Kerwin75631591

**Comment by jimmyt857** [comment]
Closing because OP hasn't responded.
