### ISSUE TITLE
Spell haste buffs are not updated on stats sheet

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#1456]
**Describe the bug**

**To Reproduce**
1. Go to: Settingss
2. Click on: Click totem of wrath/swift retribution/imp moonkin form off/on
3. Scroll down to: -
4. See error: -

**Expected behavior**
To get 3/5/8% haste on the sheet

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/warlock/#eJzNUjFoU1EU/ef+3/D7a+prlz4zxQymCIX3/++HdMqvk+AS0KGTULBSpEMoCBocYpCKpdCsFgTBoVkE6aSJLUEMEkEoCSimwaFYzBhFipN4X353C3HwDId3zz3nPrjvOWmbBCnK4DIWkKciUAae4qdZAV6A6sA+0AMuTdhIkkKInDaC25OcShxbJcRyK4t3l1btEWEnduEI8WyD5IcvlIo13tDeS3JGxY8upcwOH+OiVyP5npum7thivUGys2Ny6hs3mgec4kblFTnjYq1KssWKxYrB9Vd2fHpuntRnxK/dyB1N6r8mWWroK9bY12Pf4ApLtHY0b+5p/r6tuV/TgTLb3h3ouljV3K1S6qwNNZZBzloYuQPexsUyGUNhNhwu//+hELchSNKyU4GTx62EM86CJfl/TEMhQ5NGIhYp67jguYFSnqd8V3l+wBT4LPi+6wbuzEzAZ0ZwCGk/eWiKz0ck20eULLVp+neL1P029TDWh7UF49HJS8yFHRipQxqNyuvhua3HGs3sXKTsZ8/fHOBj1qtR/vheIX5laSV9bfl2YfFG0guSV6U99Lv+DQ/CfzGl2Hw7zJy6l16dP615sL36VDecj7ZH4R9am4nD

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 106.0.5249.119

**Smartphone (please complete the following information):**

**Additional context**
Also im not sure how haste is counted, but I couldn't produce the same shadowbolt cast times with the haste stats I had, and temporary haste effects. But im prob having wrong formula while trying to understand it.

**Comment by TeamSpeakUser1** [comment]
I actually checked the correct formula for haste, and its only a visual issue with the stat sheet not updating, spells have the correct haste.

**Comment by jimmyt857** [comment]
This happens because those effects multiply your casting speed, like Bloodlust or PI, they don't add to your spell haste stat. So this is WAI, thanks for the report though!
