### ISSUE TITLE
Temporary buffs selection box

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#1457]
**Is your feature request related to a problem? Please describe.**
Would be great if temporary buffs could be clicked on/off ex. bloodlust/pi/actives etc.

**Describe the solution you'd like**
Temp buffs having their own selection box

**Describe alternatives you've considered**
Temp buffs having their own selection box

**Additional context**
-

**Comment by jimmyt857** [comment]
They can, just like all the other options in the 'Buffs' and 'Debuffs' sections.

**Comment by jimmyt857** [comment]
OP, can you give a bit more context on this? Otherwise will close the issue soon.
