### ISSUE TITLE
Orc Base Stats incorrect?

### ISSUE THREAD

**Issue by seen1sm** [wowsims/wotlk#1462]
**Describe the bug**

The base stats for orcs in the sim seem to be incorrect

**To Reproduce**

**Expected behavior**

Ingame Base Stats
Strength - 116
Agility - 186
Stamina - 106

Sim Base Stats
Strength - 118
Agility - 201
Stamina - 91

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Which class is this for?

**Comment by TheGroxEmpire** [comment]
This is definitely rogue with that much of a base agility.

**Comment by seen1sm** [comment]
Yeah this is for rogue

**Comment by b-r-a-n** [comment]
Looks like all races were incorrect. Fix for this coming soon.
