### ISSUE TITLE
Crash Report 794039676

### ISSUE THREAD

**Issue by zhen246** [wowsims/wotlk#1467]
Link:
https://wowsims.github.io/wotlk/raid/#eJztlk9oE0EUxmfezsbN2C1jLLjmFHOxFAqzuyzUU1L10IOHopfiqVVbEdSKWJCeYvFiQSlKBXsSr5qTELSpDfYPIdVaqWhpYqoUKgUVoiAUT77ZTZHQi4f0ZL6El/ne9zK77Pwg4Xf28yZOtl8Rwr8z/pmNUPNo38W+y2f7Y8evDl04Z4QEjU5TLsS9KbAW1yAemp+BhwXgYfHrI8S14jPgpriP4QKGmkpMsbEC1vhPLUiFGMe0UMKvYjqNnWaxiQPL2GFoCfq7OLGS1qreFD/Q33qCG6hxQ1TQjsyrVR5Xm2mNM7GUBaxjz1XNTapayaqJV1mw8iXlU373Rhbi3KCSdrMe/TptGwPSUI2GiXOAmwa1qEfIlc4O2kUjJMo4GPooPexJ15HStW3PdW0Xje260kPvuHZ7uyM9DKXtrFPLSH0CsZIDazUHsd9r0Dq7DDK/DJuUVeieCUqKtIY3ky8gb03HBi+d6bsWOzl4fqjf0EUomlW4PcWDXlK4ZWbhzaLCbUvhlvNxy2CYX6taQ7zDIy8iFKYoVUnzg2bxPgPWnMIsp7DaK8pVzPA+wuL2ZHVOiK+I45fHeDG0wZbjmW3ORn3CJqZU/fZC1fKqmsjhRV+X1OpRJlgx8RJZMwyQejfrZQ3SdmiYnI7gA2MWSK0DFGQCLDpKWyUShZRJz3HbpeMhVbYPlidt6SBomCBjnr1Om4yZDRD5DaRsqZasBkz/lxowNWCqm3YVpuD3rvbfVo2LkDYS7eEtPEJ3SHUZY4BvFBZdfagu3jZT984Y0RnTNUKq3b/yzzlehrDvUgPJfUG/JXlw4oFSIXEk6LxNHBrw9SHhpCF2yjJ2nZKbyXrskirM1WWff1HwrE6Uk52B30p00V76B0H3g5s=

RNG Seed: 0

Aura Garrote already registered!
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xbcc60, 0x7b4f360})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*auraTracker).registerAura(0x7aa3988, 0x7aa3500, {{0x1ea378, 0x7}, {0x1eba9f, 0xa}, {0xbe24, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:311 +0x3d
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:341
github.com/wowsims

**Comment by jimmyt857** [comment]
Raid sim isn't released yet; this one looks like a rogue bug though. Thanks for the report.

**Comment by zhen246** [comment]
thx jimmy~

**Comment by b-r-a-n** [comment]
Fix coming soon.
