### ISSUE TITLE
Please allow to cap weights (example hit cap, haste cap, etc.)

### ISSUE THREAD

**Issue by PoPFlashh** [wowsims/wotlk#1469]
Please allow us to stat weight hit cap (and all stats) to get a better understanding of how certain pieces of gear would sim better over others.

**Comment by Tharre** [comment]
Can you be more specific what you mean by that? You can already calculate stat weights below and above hit cap.

**Comment by PoPFlashh** [comment]
Sorry I didn't see the option to calculate stat weights below or above hit cap. Is this achieved with the with the stat weigh EP calculation? Once over hit cap with talents/buffs/gear the calculation will automatically underweight hit to a lower level.

**Comment by Tharre** [comment]
You can add/subtract hit rating under "Bonus Stats" on the Gear screen to get above/below whatever caps you want.

**Comment by Faldal** [comment]
What he means is probably the issue with stat weighs after reaching certain caps (for example 17% caster hitcap due to gear/talents/debuffs) but stat weighting still shows hit as best stat.
