### ISSUE TITLE
Stats weight outputs negative values on Intellect and MP5 - Shadow Priest

### ISSUE THREAD

**Issue by zoroperona** [wowsims/wotlk#1472]
**Describe the bug**
I chose Shadow Priest P1 Preset and used stats weight feature, then negative values displayed on Intellect and MP5, which is confused for me.

**To Reproduce**
1. Chose Shadow Priest.
2. Chose P1 Preset.
3. Modify 'Settings' as the pic below.
4. Click on 'Stat Weight'.
5. Click on 'Calculate' on the popped out window.
6. See bug.

**Expected behavior**
Intellect and MP5 maybe no benefit for short duration battle, so their weights are supposed to be 0 but not be negative.
(Intellect provides spell crit, so it must be positive.)

**Sim Links and Screenshots**
Sim Settings
![image](https://user-images.githubusercontent.com/13634899/197954801-bfd063eb-89e5-4f43-92bc-335ae0c62d66.png)
Sim Result
![image](https://user-images.githubusercontent.com/13634899/197954428-7a55149e-4f18-4d4d-ac6f-11b9aa136415.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [106.0.5249.119 (64bit)]

**Comment by jimmyt857** [comment]
I recently made some updates to the EP calculation which should hopefully fix the most eggregious cases like this one. Note that it is possible to get negative values due to natural variance, but it should be a lot better now.
