### ISSUE TITLE
Hyperspeed acceleration not getting used

### ISSUE THREAD

**Issue by sadistlex** [wowsims/wotlk#1474]
**Describe the bug**
Hyperspeed acceleration hands enchant is not getting used in DK dps sim.

**To Reproduce**
1. Open DK dps sim
2. Sim with Hyperspeed acceleration enchant on hands slot
3. Look at detailed results or log
4. Hyperspeed acceleration has 0% uptime, no log entry for it either. It's not getting used.

**Expected behavior**
Hyperspeed acceleration enchant is getting used in the rotation, buff uptime is present in detailed results and casts log.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/78348729/198019692-d6866d8a-1be2-4dd8-a028-d3c803c8dc65.png)
https://wowsims.github.io/wotlk/deathknight/#eJztUj1MFEEY3fftchkHz4zEYqDx2MIQEpO53WxBYXa0orAgoaGEAmJhoVRiRYgFMQbs5CdGKmMkl/gTDCF3BLlrrgCuOCRAToyJ5CScuZLY4OyehNBZYMcrvpl57833Mj/cZSRI0T08wCjwBngHrAAloAocgUpEd0SKFDT6jGc89rRYbc+axpDouT8wMjhsOvC2LLgQb/MkN76Sm/iUp/U14o44eE88KWpZkrmK7drZReJMTL4mubhLZsPnBZLFXbPBCJHWLF4ukywYBha/IlaNvJWxXcdoFr8s6rlTqxAFo+7PnzJMTCyRrGZsk/vzY5Re+xDVw1xUf21Ejuoxyb0528x2tkl+m4u8k0vkJhmpZI/T5zyKjtj5nKwLnMFjh0HSb9zi1zW6MRCT+pV+2JDr4Ug8jue1+Rzy6gmbQmczOz4BnuKG56tAKRXc9D1T/UD5gecpX6WNoJTvp1XaD9LfIdlsmcSLMsnaD0pNlaljapPU9CZV4dSRmAHjCe6w/Xl7B5ZboUtx4sqg/pt9TbfOTEcohl0NphS2D8X4EnoZSvVK9t/f+Yk+jy6jxcK59PkXNO7qbkXfbqyPwm704w/MqI8C

**Desktop:**
 - OS: Windows 11
 - Browser: Opera
 - Version: 91

**Additional context**
Haven't checked if the problem is present only on dk sim or all of them.

**Comment by rosenrusinov** [comment]
In your export link you have selected to give a specific time to Hyperspeed Accelerators but then have not inputted any time in the box thus making them not cast at all. Either remove the major cd from the options box or give it a time if you want to test firing at specific timings (You should not do that as there is extra logic to when to use them for snapshotting buffs)

![image](https://user-images.githubusercontent.com/5707996/198024819-abadbec2-2e00-4511-b215-3e33ce92f2fa.png)

**Comment by rosenrusinov** [comment]
Oh there seems to be another problem with frost as well - reopening while i take a look

**Comment by sadistlex** [comment]
Ye i forgot to mention that problem appears if you remove it from Cooldowns aswell.
