### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by subrand0m** [wowsims/wotlk#1486]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=40247/cowl-of-innocent-delight
https://www.wowhead.com/wotlk/item=40064/thunderstorm-amulet
https://www.wowhead.com/wotlk/item=41931/hateful-gladiators-satin-mantle
https://www.wowhead.com/wotlk/item=40724/cloak-of-kea-feathers
https://www.wowhead.com/wotlk/item=37258/drakewing-raiments
https://www.wowhead.com/wotlk/item=37884/azure-cloth-bindings
https://www.wowhead.com/wotlk/item=37798/overlook-handguards
https://www.wowhead.com/wotlk/item=40696/plush-sash-of-guzbah
https://www.wowhead.com/wotlk/item=39408/leggings-of-sapphiron
https://www.wowhead.com/wotlk/item=39254/saltarello-shoes
https://www.wowhead.com/wotlk/item=39231/timeworn-silken-band
https://www.wowhead.com/wotlk/item=39389/signet-of-the-malevolent
https://www.wowhead.com/wotlk/item=40682/sundial-of-the-exiled
https://www.wowhead.com/wotlk/item=37873/mark-of-the-war-prisoner
https://www.wowhead.com/wotlk/item=37360/staff-of-draconic-combat
https://www.wowhead.com/wotlk/item=39712/gemmed-wand-of-the-nerubians

**Comment by Tharre** [comment]
These are all already available in the sim. Try clearing your cache if they don't show up for you.

**Comment by subrand0m** [comment]
https://i.imgur.com/Ng4gZZZ.png

Site does not show them as in the Database. I Legit just installed chrome to test this as I normally use Brave.

Is there something I am doing wrong? Happy to get you a mp4 video of me loading the site and doing the import then getting this.

**Comment by jimmyt857** [comment]
Oh, I can see in the background that none of the items loaded; you're probably having a different bug, where the database doesn't load properly. Unfortunately that one is a lot trickier, we still haven't figured it out.

**Comment by jimmyt857** [comment]
#1509

**Comment by dabilos** [comment]
Don't know if I can help but I am having the same issue. Tried on 3 browsers but cannot get [Sundial of the Exiled](https://www.wowhead.com/wotlk/item=40682/sundial-of-the-exiled) to be available
