### ISSUE TITLE
In game hit =! sim sheet hit (at least for rogue)

### ISSUE THREAD

**Issue by DDemirovic** [wowsims/wotlk#1490]
**Describe the bug**
There's a difference between the sheet hit in game and sim. I got 246 hit on my rogue in game while I got 295 on the sim sheet (with the same gear/gems/enchants) 

**To Reproduce**
-There are no real reproduction steps as far as I can tell, since I just "copied" my gear from in game into the sheet (I clicked on all the icons/gems/enchants by myself, there was no automation in case you may have missunderstood me).

**Expected behavior**
Expected to see 246 hit on the sim sheet, got 295 instead.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Win11
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] 106.0.5249.119 (that's what chrome tells me)

**Additional context**
Nothing to add really, except that the hit on gear shouldn't be "hid" behind the magnifying glass on the sheet (e.g. expertise on the sheet is shown like this: "Expertise: 218(26)". It may be more beneficial if hit was shown the same way (without adding talents and buff/debuffs). Right now it's: 505(19.25%) with a breakdown of: 295hit from gear, 131 talents and 79 from debuffs.

**Comment by jimmyt857** [comment]
We don't aim to show the same values that would appear on your in-game character menu; instead we show the real values, including additional things like talents which the game doesn't show.

Will leave this open a bit longer in case you have a concern beyond that, but otherwise this can be closed as WAI.
