### ISSUE TITLE
Import error: Error: Unknown glyph name 'Glyph of Subjugate Demon'

### ISSUE THREAD

**Issue by jd7901** [wowsims/wotlk#1494]
**Describe the bug**
Gives error if you have Subjugate Demon glyph

**To Reproduce**
Generate data from Exporter Addon and have Glyph of Subjugate Demon on your character.
"Import from addon" on the github page

**Expected behavior**
Be able to import data without having to edit it out

**Sim Links and Screenshots**

{"talents":"2350002031023510253500331151-000000000000000000000000000-55000005000000000000000000","glyphs":{"major":["Glyph of Quick Decay","Glyph of Haunt","Glyph of Life Tap"],"minor":["Glyph of Unending Breath","Glyph of Drain Soul","Glyph of Subjugate Demon"]},"class":"warlock","race":"Human","name":"Seedgobrrtt","gear":{"items":[{"enchant":3820,"gems":[41285,40051],"id":39496},{"id":40071,"gems":[]},{"enchant":3810,"gems":[39998],"id":40424},{"enchant":3722,"gems":[],"id":41610},{"enchant":1144,"gems":[],"id":42102},{"enchant":2332,"gems":[],"id":39252},{"enchant":3246,"gems":[39941],"id":39500},{"id":37408,"gems":[41457]},{"enchant":3872,"gems":[39998,40051],"id":40422},{"enchant":1147,"gems":[],"id":40750},{"enchant":3840,"gems":[],"id":49123},{"enchant":3840,"gems":[],"id":40719},{"id":40682,"gems":[]},{"id":37873,"gems":[]},{"enchant":3830,"gems":[],"id":40336},{"id":40698,"gems":[]},{"id":37177,"gems":[]}]},"professions":[{"name":"Enchanting","level":445},{"name":"Tailoring","level":441}],"level":80,"spec":"","realm":"Pagle"}

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Browser: Chrome

**Additional context**
The github has the glyph name set up as the old version with "Enslave Demon" but on the mouseover it says "Subjugate Demon" so idk what's up with that lol

**Comment by jimmyt857** [comment]
#1371
