### ISSUE TITLE
Non-dagger 1handers showing as upgrades for Assassination spec.

### ISSUE THREAD

**Issue by mbrostrom** [wowsims/wotlk#1500]
**Describe the bug**
Non-dagger items showing up as sim upgrades in the drop down when selecting a weapon to replace as Assassination spec in Rogue class.

**To Reproduce**
1. Go to '[...](https://wowsims.github.io/wotlk/rogue/#)'
2. Click on 'Any weapon slot, mainhand or offhand'
3. Scroll down to 'Non-daggers show as upgrades, including maces and axes, etc.'

**Expected behavior**
Maces axes swords should not show as upgrades for Assassination spec.

**Sim Links and Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise]
 - Browser [Firefox]
 - Version [106.0.2 (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
The EP calculation is just an approximation so it doesn't handle this. We have now added filters though, so you can filter out the unwanted weapon types.

**Comment by mbrostrom** [comment]
Makes sense. Thanks for filter option.
