### ISSUE TITLE
The Powerful Stats to Chest enchant (+10 stats) reports that it is worse than the +8 (and all the other) plus stats enchants to chest. It looks like it might just be set at zero.

### ISSUE THREAD

**Issue by PhantomeX42** [wowsims/wotlk#1507]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the report, looks like this is because this enchant spell ID (44489) matches the ITEM ID of a different enchant and we don't make that distinction everywhere.

**Comment by psiven** [comment]
@jimmyt857 If it helps, I compiled a list of itemid/spellid collisions:

44483	Massacre to Weapon, Superior Frost Resist to Cloak
44484	Greater Assault to Bracer, Expertise to Hand
44488	Wisdom to Cloak, Precision to Hands
44489	Powerful Stats to Chest, Defense to Shield
44492	Mighty Health to Chest, Berserking to Weapon
44494	Superior Nature Resist to Cloak, Lifeward to Weapon
