### ISSUE TITLE
Make addon available through WoWUP

### ISSUE THREAD

**Issue by Tatters654** [wowsims/wotlk#1515]
**Is your feature request related to a problem? Please describe.**
WowSims Exporter Addon is not available through wowup

**Describe the solution you'd like**
Make WowSims Exporter available through wowup

Thank you for your time.

**Comment by lologarithm** [comment]
This should be a non-issue now that wowup re-added curseforge support

**Comment by Kruhlmann** [comment]
It might still be a good idea to provide the addon through several platforms as curseforge is proprietary and as such there's no guarantee of the addon/platform being available in the future.

**Comment by generalwrex** [comment]
I will add it to WowUp as I use it myself.
