### ISSUE TITLE
Missing item: Commendation of Kael'thas

### ISSUE THREAD

**Issue by Nealliam** [wowsims/wotlk#1526]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=34473/commendation-of-kaelthas

some tanks may still be using this - my bear is

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1534
