### ISSUE TITLE
druid bear armor bug

### ISSUE THREAD

**Issue by Nealliam** [wowsims/wotlk#1527]
**Describe the bug**
Armor value for druid in bear form is incorrect. They have two talents that increase armor to cloth and leather items. this talent doesn't increase armor for any additional armor from enchants, jewelry, or on weapons. The sim is applying these talents to everything and inflating what your armor actually is.

**To Reproduce**
1. Go to https://wowsims.github.io/wotlk/feral_tank_druid/
2. remove all items, remove all raid buffs and potions etc
3. set talents to thick hide and survival of the fittest in feral
4. equip keystone great-ring to a ring slot
5. armor value should increase by 490. instead it increased by 2710

edit: actually it looks like you don't even have to have any talents set and the armor value will be wrong it might be dire bear form itself is having the issue. with no talents set armor increased by 2303.
I'm guessing you need to make sure dire bear form is excluding items worn on the:
neck, finger, trinket, two-handed, main hand, one-hand, held in offhand, and enchantments

**Expected behavior**
accurate armor value for bear

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 106.0.2 (64-bit)

**Additional context**
The talents are:
Thick hide:
https://www.wowhead.com/wotlk/spell=16929/thick-hide
https://www.wowhead.com/wotlk/spell=16930/thick-hide
https://www.wowhead.com/wotlk/spell=16931/thick-hide

and Survival of the fittest: (33854 is something else careful)
https://www.wowhead.com/wotlk/spell=33853/survival-of-the-fittest
https://www.wowhead.com/wotlk/spell=33855/survival-of-the-fittest
https://www.wowhead.com/wotlk/spell=33856/survival-of-the-fittest

dire bear form:
https://www.wowhead.com/wotlk/spell=9634/dire-bear-form

**Comment by jimmyt857** [comment]
Thanks for the report! The bear sim is not even in Alpha release yet, so significant bugs are expected. We'll keep this open until its addressed though.

**Comment by jimmyt857** [comment]
Fixed in #2138
