### ISSUE TITLE
Crash Report -1535880741

### ISSUE THREAD

**Issue by SteveSpam** [wowsims/wotlk#1530]
Link:
https://wowsims.github.io/wotlk/shadow_priest/#eJztUjFIW1EU/ef+JL4+ibyKw2um+CcRhJf/+VCnfDtl6BBah4w61MkhuNkpiIt20LXiJIi2IEhQqbZJRRSVUBpCKTXGlraDEh0UF+nU9/MR0S4OuvUMj3vPefe8y32XxxkJUvQYKWSQpRwwCSyC1oEycAQ8iTLEScFDFvNAqxEbDY8gkh7sH34xxLgIxz6CC/FjjeSn72RFtjao+I54SKy8Jx4Vrz6Q/PmNLNMnmSjvkKzmTV3we4nk55ou0MK51prElzxZMHiLqGtpUUshzRuci4vCZSzEmPY7XDatSDUoi4q3e9poz7TMauOFSp5kreZHE8UgCol6wT/P5nx2Xhts7/v5nwa7OkMWY1BIhzPhzkky/uMaXurhCJKUxbMWTszUCxDRG4EOjKNXuQnHVk5CKUfdRJftuMrViq2UnXBt11E6cvRlN9H1z+0r/IJkb0okpkskZ0sUP65Qx0mFVL1CRzBP0TwFowrDOqAHjQZzA97DoNU279HUax+7ye6AKSfbBxr4mrQXKP5csnv/4VHvLlxyu5t34nMbBLN6euD1BPlFMoU+/AW8jYP5

RNG Seed: 626185691

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xe2120, 0x11ae5e0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/priest.(*Priest).applySurgeOfLight.func1(0x506b8c0, 0x7a80990)
	/home/runner/work/wotlk/wotlk/sim/priest/talents.go:313 +0x3
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x506b8c0, 0x7a80990)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:592 +0x126
github.com/wowsims/wotlk/sim/priest.(*Priest).applySurgeOfLight.func5(0x506ba20, 0x7a80990, 0x506d000, 0x506d1c8)
	/home/runner/work/wotlk/wotlk/sim/priest/talents.go:354 +0x1a
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home

**Comment by jimmyt857** [comment]
Fixed by #1618
