### ISSUE TITLE
Seems like sim doesn't consider T7 set bonus (at least 4 piece) for balance druid.

### ISSUE THREAD

**Issue by Mtw01** [wowsims/wotlk#1537]
**Describe the bug**
When I use 4 pieces of t7 the bonus doesn't work. Four pieces give you +5% crit to Wrath and Starfire, but it doesn't seem to work, since the "Crit%" in "Detailed Results" doesn't change with 4 pieces. I was switching only gloves to compare the results of the sim. See the Sim links.

**To Reproduce**
1. Go to 'Gear'
2. Use the Sim 1 (4piece) settings via the link I provide.
3. Click "Simulate"
4. Click "Detailed results"
5. Note Crit% of Wrath and Starfire.
6. Go to 'Gear'
7. Use the Sim 2 (3piece) settings via the link I provide.
8. Click "Simulate"
9. Click "Detailed results"
10. Note Crit% of Wrath and Starfire.
11. Compare the results.
12. It's a bug.

**Expected behavior**
The Wrath and Starfire Crit% should be increased with 4 pieces of T7.

**Sim Links and Screenshots**
Sim 1 (4piece):
https://wowsims.github.io/wotlk/balance_druid/#eJztUkFIVFEU/efOODy/TTzDxcvV728KQXj/PT7Yar6uWg5EMFsJRajFR4JKED7iohECFyk4uAvChaBoC4vUqIYwqGTIoGkosBaDG0dX0mZ8/6sLd4K16/C4cM8591x479kOI06SenADBYQUAZPAIug1sAnUgb52BockAuRjB+aAS1bnbnoMmfzd/ocDw4xxdL6AzfnjVyQ+/iA3U35D1RWy03x/iewsnzb8B8On1gzJ+ESZxNR+ygifjPC5ZoSGEdr43lMSle/kwrIv8oPnJBo1uGkzZJnwg1USxfmUm9lbIXMM88RMj5XNOuOoJskLSyTmavHiX824/k7qzmpcZ5/FjuYyia3E8SdhH62RazNI5NOFlgfomiTrP05hhDFwEhRCOXaWQeCWZYW9BQzF/yBrt7HmCTCBq74nlZLaU77WnpZaeVpLX0tPaa+7W0lfyrjZhmDRT+Jf1kl8WyentEXX3lZIvq9QHS0NtJZgFY/fQgVVWO4OtSZdNBi0H/EdweXSTIyN3PUjZjN3ZTDB15x6SeHs6MiFfP+920P3B4bvOMp3bgr2z194PPgbKdHGu/PkyJ6usPes5uTyount4HiinjsESrSNng==

![4piece](https://user-images.githubusercontent.com/117014952/198877130-c5fa72ee-83c1-462b-a82a-13ca241afa35.png)
![4piece (detailed)](https://user-images.githubusercontent.com/117014952/198877136-ca8ad448-291a-4d9a-9f8f-85924f6ebd1d.png)

Sim 2 (3piece):
https://wowsims.github.io/wotlk/balance_druid/#eJztUkFIVFEU/efOODy/TTzDxcvV728KQXj/PT7Yar6uWg5EMFsJRajFR4JKED7iohECFyk4uAvChaBoC4vUqIYwqGTIoGkosBaDG0dX0mZ8/6sLd4K16/C4cM8591x479kOI06SenADBYQUAZPAIug1sAnUgb52BockAuRjB+aAS1bnbnoMmfzd/ocDw4xxdL6AzfnjVyQ+/iA3U35D1RWy03x/iewsnzb8B8On1gzJ+ESZxNR+ygifjPC5ZoSGEdr43lMSle/kwrIv8oPnJBo1uGkzZJnwg1USxfmUm9lbIXMM88RMj5XNOuOoJskLSyTmavHiX824/k7qzmpcZ5/FjuYyia3E8SdhH62RazNI5NOFlgfomiTrP05hhDFwEhRCOXaWQeCWZYW9BQzF/yBrt7HmCTCBq74nlZLaU77WnpZaeVpLX0tPaa+7W0lfyrjZhmDRT+Jf1kl8WyentEXX3lZIvq9QHS0NtJZgFY/fQgVVWO4OtSZdNBi0H/EdweXSTIyN3PUjZjN3ZTDB15x6SeHs6MiFfP+920P3B4bvOMp3bgr2z194PPgbKdHGu/PkyJ6usPes5uTyount4HiinjsESrSNng==

![3piece](https://user-images.githubusercontent.com/117014952/198877656-6f4c1b1c-1a42-4181-9378-496b18172e8f.png)
![3piece (detailed)](https://user-images.githubusercontent.com/117014952/198877662-9c9b4a41-c0aa-4e35-8448-fb2a7b05c712.png)

**Desktop:**
 - OS: Windows 10
 - Browser: chrome
 - Version 106.0.5249.121

**Additional context**
The overall gear stats doesn't rly change. Set with 4 pieces has less Spirit and a bit less of Crit, but the bonus to Wrath and Starfire is massive (+5% crit), so the problem seems to be just in a set bonus issue.

**Comment by Gashiraa** [comment]
You've got the healing head part equipped buddy.

**Comment by Mtw01** [comment]
> You've got the healing head part equipped buddy.

Gosh, you're totally right!
Sorry 😅
