### ISSUE TITLE
Crash Report -458915563

### ISSUE THREAD

**Issue by CoffeeNoodle** [wowsims/wotlk#1539]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJzj4uFgsmD0YNzAyHSBkdGJi4NRglGBSYMxglGIQeo/SxMjW0BOYmVqEQeTALvUHkYuHoHnm5mU2LYdZnq2nYmLXeDTHSYlRgYuFoG/i5m4OAQuLGeSmPqJmUtA4PQeJonzQEm2/TuY7u1g4uIW+LaYSeLIbbByPoH2ZUwS19cyK7EAjQHxTy1ikuhcA+S37ADyBQROAbU/Ww3Rfg6oXUBgPVDFC6AOttfbmYAIaOXD/yDy7SYQ2bcERL7ZC3LE3AdMEmdug1gN+yAsFoGWfUCzOBgNGAOYtCYwMYwCFFAFDBoBpgLGJC0uBSkOIJtZglmBkYPREyzbEOAQCGE4ODiA0gULUAVjF2OQgamxgbGBoamRARrQBYmbGhgYGwJJI0NjYyDf0BCMDEwNddGVI8AjRoYXjCwfGNlnMTLcYmRQusvECbE5zUEQ4lQRB8lZM0HgpL0lROSCvWIaGFyzN1rLpBAswUHzGG5xoIYpDSePUMUcYgAkrHzuOjhC+D/sPRgTGAGpW3R8

RNG Seed: 2545524992

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xe21a0, 0x11af5e0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Unit).SwingSpeed(...)
	/home/runner/work/wotlk/wotlk/sim/core/unit.go:307
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).MainhandSwingSpeed(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:452
github.com/wowsims/wotlk/sim/shaman.(*Shaman).registerFeralSpirit.func1(0x7ab9440, 0x7bac200)
	/home/runner/work/wotlk/wotlk/sim/shaman/feral_spirit.go:40 +0x6
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x7ab9440, 0x7b84000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:276 +0xe
github.com/wowsims/wotlk/sim

**Comment by lologarithm** [comment]
This is caused by having enh spec (using feral spirits) on the elemental sim. I have fixed the issue in https://github.com/wowsims/wotlk/pull/1546 so it doesnt' crash... however this is very much not ideal way to play :)
