### ISSUE TITLE
Listed Items DPS Increase Availability

### ISSUE THREAD

**Issue by sneighbours11** [wowsims/wotlk#1545]
**Is your feature request related to a problem? Please describe.**
I do not believe this is an issue currently, but instead of using EP as the item upgrade determining factor you could use actual dps +/-.

**Describe the solution you'd like**
After your equipment is selected there should be an option to run the simulation for all the different gear options which would then show the +/- dps change per items that are listed in the available options.

**Describe alternatives you've considered**
None

**Additional context**
This is similar to hitting the "Sheet DPS" button from the classic vanilla sim (https://guybrushgit.github.io/WarriorSim/)

**Comment by lologarithm** [comment]
related to https://github.com/wowsims/wotlk/issues/1545

**Comment by lologarithm** [comment]
prob closing this over our combined ticket https://github.com/wowsims/wotlk/issues/1512
