### ISSUE TITLE
Crash Report -164305260

### ISSUE THREAD

**Issue by Eluulne** [wowsims/wotlk#1547]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJzj4uFgsmD0YNzAyHSBkdGJi4NRglGBSYMxglGIQWoGaxMjW0BOYmVqEQe7ALvUXkYuAYEZu5kkzt9jUmLbdpjp3A4mLhaB17uZuHgFzuxhknh8g0mJeT9QkEPgygkmiVtrmYEa1m4FargD1PB1B9PZs0xc3AKbFjFJnLjJrMTIwMUnsBEofX0tsxILUB8D0JzLm5kkOtcwKzGDDBcQ2AyUfrIaqBsofQ5s8pFNTBIvgCazCLzdBLL+4X8QOfEkiHyzF6Ri7zImibM3mYGsNVsgLBaBln1AMzgYDRgDmLQmMDGMAhRQBQwaAaYCxiQtLgUpDiCbWYJZgZGD0RMs2xDgEAhhODg4gBIGC1AFYxdjkIGpsYGxgaGpkQEa0DU2MDIwNTA2NgSSBobGxkB1hoZgZGBqqIuuHAEeMUpw7DrCJLDnCJPE4SNMCn8uMWl8vcRk8PMS0wtGlg+MnLMYGW4xMijdZeKEuCjNQRDiBREHyVkzQeCkvSVE5IK9YhoYXLM3WsukECzBQfOYb3GghikNJ49QxRxiACSsfO46OEL4P+w9GBMYAf9kgHw=

RNG Seed: 3697954697

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xe30e0, 0x11b5640})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Unit).SwingSpeed(...)
	/home/runner/work/wotlk/wotlk/sim/core/unit.go:307
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).MainhandSwingSpeed(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:452
github.com/wowsims/wotlk/sim/shaman.(*Shaman).registerFeralSpirit.func1(0x7a4d5f0, 0x2a8e200)
	/home/runner/work/wotlk/wotlk/sim/shaman/feral_spirit.go:40 +0x6
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x7a4d5f0, 0x2a81500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:276 +0xe
github.com/wowsims/wotlk

**Comment by lologarithm** [comment]
This has been fixed already
