### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by working926** [wowsims/wotlk#1549]
[Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:](https://www.wowhead.com/wotlk/item=50355/herkuml-war-token)

(Phase 3 was selected)

**Comment by lologarithm** [comment]
Item is shown with Phase 4 tag in wowhead (and is in sim under phase 4)
