### ISSUE TITLE
exclude specific gems when optimizing gems

### ISSUE THREAD

**Issue by 0nlyDev** [wowsims/wotlk#1551]
I.e. i have JC, but i can't put storm jewel gem on each item. I would like to exclude this item and optimize the gems

**Comment by jimmyt857** [comment]
JC gems should already have the proper limitations applied. Could you be specific about which gem is the issue here? This might be a wowhead error since we scrape our data from them, so the gem is incorrectly labeled.

**Comment by jimmyt857** [comment]
Optimize gems should now work properly with phases and JC gems based on current settings.
