### ISSUE TITLE
Super Stats and Powerful Stats Possible Miscategorization 

### ISSUE THREAD

**Issue by Dbolisher** [wowsims/wotlk#1563]
**Describe the bug**
Super Stats and Powerful Stats enchants seem to be swapped in their values. +8 stats to chest is reading as a higher value. +10 stats to chest is reading at a lower value and also sims to come out with less survivability.

**To Reproduce**
1. Go to 'Pick Paladin Preset P1
2. Click on Chest Enchant
3. Scroll up to +8 stats to chest
4. See how +8 stats to chest is higher rated in value than +10
5. Run sim between both and notice it's acting as if the +8 gives more survivability.

**Expected behavior**
Sim will run better with the worse enchant.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version Unknown

**Additional context**

**Comment by Grimsbain** [comment]
I'm seeing the same issue on my Shadow Priest.
