### ISSUE TITLE
Crash Report 857949768

### ISSUE THREAD

**Issue by Babyhoof** [wowsims/wotlk#1566]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztkk1oE0EUgPPerulksM1YRdd4WXOxFJTJroF62q1eLF5SvOhFGqRS0EMIgrUgBI34c2lFkBo8VLxESi8eNJQK0kZKoNXAgkKFWtsSV72sHkQ8qG+ziTQHQVBvPoaZed/7neFxnaHEIchgDqAIUAVwATyAL4BVxBzCwR062nAYMnAVYKzuNIGwAtiJPRDzwhchnDqTPj+YZZtEJPYRuBDzLmrPlzEefjiH9yvII+LmGsaVuRLydvGUjPPLDVWI6lvUlqaUeJjUWp3MkkPlFUXPlPDZIvIO8XodtTIRlUiI9DJ5vKQY9auvR8Woi/EI2YLFt4qVNdRqkwRnS0h5aedMjD5GzZ1SqJviOpX3PSPi07tGJ6r4UPP3J9N+DwuUYKHRw0yphdCDgjd5b4LQeJS+MJxSjykDOEyfhN1jGPovLTLSxkDDCYDsEX6IhkiHLugNTPvtvuDSZ/fXz1y/fTwg++x0cPEsmlAYBppRGsJxmr1QDHW4DntMQ0rDlAnDNPeaMimTppQyaUgzQYeZMAhJM5lYBY0VHRQFB7VxB/VLDnblHZSXHXRB9aCtAPeAx3gHu7Zd/94U6GTNB3DBVVabVJqE2T4RNxaxSTyLR7nC8gMbXHzwqH1Dll08yr59Vn5ZQuQfQGsJdvfKzxLb7CUIxd9jJFBP2FuafGfhti8V60BAqtbuU3V5YRnTmLlzYWRzKn325NC5wexp3UjqRzX2z6c0b/+NLLlK+U/yyJ7uTO/vOtc/L3dr1W5EuNYPZfbISQ==

RNG Seed: 3525353026

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 64382} for 300ms, curTime = 12.919010136s
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3c0, 0x5a315f0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x5b99cb0, 0x8227500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x5b99cb0, 0x8227500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
