### ISSUE TITLE
Spell Hit not calculating properly with Mage Talents

### ISSUE THREAD

**Issue by DrunonTV** [wowsims/wotlk#1568]
**Describe the bug**
Mage Simulator is calculating 3% Hit from Talents when both Arcane Focus and Precision are maxed out. 

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
![Mage Talents with 6 Hit in Sim](https://user-images.githubusercontent.com/117326099/199631965-4a7adcb0-6386-48af-b9cc-b4addfa2ae20.PNG)

**Additional context**

**Comment by PANDAxBEARS** [comment]
I think this is working as intended as Arcane Focus only gives 3% increased hit chance to spells in the Arcane tree, not all spells. I guess you could have the UI display the hit % for each tree, but I'll defer to the maintainers if that's something we'd want to support or not.

**Comment by jimmyt857** [comment]
Yeah this is WAI, we currently don't show spell-specific bonuses in the character stats panel.
