### ISSUE TITLE
Crash Report -2059636906

### ISSUE THREAD

**Issue by Zerabrant** [wowsims/wotlk#1571]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUj1IK0EQvpk74+VE3yoWa6p4jSIImztT2HirlaKFYqOdFoqFhVipVXgqiCAKgmAKwU6QtCL+EUWRgD/RQ4PGWAhKwMYypXO5FNq9wtf5Fbsz3zf7zbI7RkhHgWMwATGALYA0QB6gAJhG7PgTRknKQlHZBahRQqtlfyHQOz48PTKpl7NgKAkGY28Z5NfPaAbOTvDqEo0gKzyhqR7solHJbg+Qn5OovlKqM3cf+WNCJSFLQipLwkYKjSp2t4P8lFKNjilGBcuRnEmoJijkt7RXqmPshvi3bWpGdfdFy+VD5HmyDLKHTKlMY0tH3vp+7a3JPa8sSZ0vsl8jjR3vo2nQCwR61QFtCppWUPnFN8xoOnCc7DacFYAwtPtsm+wq7rF22ecHfXLQl1qlN01T3jzR4GyCz7ZIGp4AIweOi9BgC8uyhRCWbTfbIiqiXhK1hB2hzY5YREXsaOQFuL7lIou7yNdcDM+62Djnoph3MQ/aB5THQXkExcxh0L/FqKz2+9XKuvi6h5TT6jNpp360iHvHSmC4n+v//bfn5E+4xFKnP+LzL/DfqicnS/9ccDphCD4BVmuDeA==

RNG Seed: 2165030534

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 64382} for 192.203656ms, curTime = 14.713319427s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3c0, 0x7ae3fb0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x7a19e60, 0x7aba000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x7a19e60, 0x7aba000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x7a19e60, 0x7aba000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
