### ISSUE TITLE
Crash Report -362215530, the wotlk sim crashes when simming the 2 handed sword Armageddon.

### ISSUE THREAD

**Issue by Kerazayah** [wowsims/wotlk#1573]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjkuVgMmDKYCxgbGBkXMHIeIGR8QYj4wtGxh+MTBeYmJyEFJgcgJIdjIwTwPI7GBmFGKT+sjQxsgXkJFamFnGwC3BK7WDkEhBYdZhJ4vw9JiW2bYeZHu1g4mIRaNzJxMUrcGkPk8RxoDjzU6Agh0DjZiaJh5uZgRq2bWWSOHkbqGHeSbAGboG5+5gkjgBFGBmAnLtAfX9uMoM4nAK9u4AGANUBtV0Eij9bjdDGKzBrG5PEKaA25j1ga7uWgcjefSDyzV4QuW4RyObpu5kkztxm4gKZd+M2xEFKbED/MwYwa01gYhgFKKCKjYNRgkmBsciOy0gAFP0aTI4QGTsHTzDd4OgQCGEEOkRCpCwdMhgrGGeAUwmbAKMCowRjF6OGsYGRkYGxkYGRsbGxgaGBqaGBkYGhkZGhsZGxoZGpoa6xgakuUIHxI0YJjvmXmQTmXmaSmHGZSaH5MpNGy2Umg9bLTC8YuT8wss9iZLjFyKD0iokTYm+agyDEXhEHyVkzQeCkvSVE5IK9YhoYXLM32sVUMKe2iicgsSQ5ozy1KFvByFQhWIKD5pHe4kANUxpOHqHEHAMLrQJHYhWDA69h2iMHqI4X9gDqJYWS

RNG Seed: 1937268185

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 47475} for 500ms, curTime = 1m52.064737978s
Stack Trace:
goroutine 88 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3c0, 0x5e3d1f0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x516bb00, 0x5e06000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x516bb00, 0x5e06000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x516bb00, 0x5e06000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
