### ISSUE TITLE
Crash Report -544866431

### ISSUE THREAD

**Issue by theodordaniel4** [wowsims/wotlk#1578]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjkuJgMmDKYCxgbGBkXMHIeIGR8QUj4w9GpgtMTE78CkwOQJkOsMwORkYhBqn/LE2MbAE5iZWpRRysApxSuxm5BAQu7GGSOH+PSYlt22GmpzuYuFgE/m5m4uIV+LmTSeLxDSYlZpAgh8DEfUwS328yAzWcBWm4A9QAlDh3lomLT6BrN5PEkdtMSix7djAxcHEL3AWq+HOTWYmRgYtT4O8uqBkCAv92MUk8Ww3UOW0nE8TUZUBTzwNNZRF4+B9kde8+EPlmL4g8sAvkjKnLmCTO3IYaATLvBpSjJAD0PG8AcwRLBcj7QH9qTWBiGAUooIqFg1GCqciay1CAcQIjoyNE1M7BE0w3ODoEQhiBDpEQKUuHAmhoAtMLiwBQcxejhrGBkZGBsZGBkbGxsYGhgamhgZGBoZGRobGRsaGRqaGusYGpLlCB8SNGCY75l5kE5l5mkphxmUmh/TKTxp7/TAatl5lmMTLcYmRQusvECbEnz0EQwhBxkJw1EwRO2ltCRC7YK6aBwTV7o7VMCsESHDSP2BYHapjScPIIVcwhBkDCyueuAzRKf9h7MCYwAgBanICm

RNG Seed: 452346631

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 47475} for 500ms, curTime = 52.382119359s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3a0, 0x7a44d60})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x7a197a0, 0x7a4c000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x7a197a0, 0x7a4c000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x7a197a0, 0x7a4c000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home

**Comment by theodordaniel4** [comment]
its caused by Sword Specialization talent from the arms tree

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
