### ISSUE TITLE
Warrior Polearm offhand incorrect sims.

### ISSUE THREAD

**Issue by Mitch3llO01** [wowsims/wotlk#1579]
**Describe the bug**
When simming a Human Fury Warrior with a polearm in the offhand, for example [Betrayer of Humanity] MH and ilvl 213 [Cryptfiend's Bite OH], the results show a demonstrably lower DPS than what is expected.  If you sim [Betrayer of Humanity] MH and [Brutal Gladiator's Decapitator] You get nearly equal DPS (20 damage higher on [Cryptfiend's Bite] in Offhand vs [Brutal Gladiator's Decapitator] in Offhand)

There is absolutely NO way that an ilvl 154 level 70 pvp weapon is going to do roughly the same DPS as an ilvl 213 level 80 Naxx 25 raid weapon.

**To Reproduce**
1. Sim fury warrior [Betrayer of Humanity] MH, ilvl 213 [Cryptfiend's Bite] OH, note the DPS
2. Sim fury warrior [Betrayer of Humanity] MH, ilvl 154 [Brutal Gladiator's Decapitator] OH, note the DPS
3. Sim fury warrior [Betrayer of Humanity] MH, ilvl 175 [De-raged Waraxe] OH, note the DPS
4. See that these are all simming close to each other in DPS.
5. Sim fury warrior [Betrayer of Humanity] MH, ilvl 200 [Colossal Skull-Clad Cleaver] OH, note the DPS as being FAR higher than any of the above 3 sims
6. Arrive at conclusion that there is no possible way an ilvl 213 weapon is simming nearly the same DPS as an ilvl 154 level 70 weapon. Pole-arms in the offhand are not simming correctly.

**Expected behavior**
Simming a level 80 ilvl 213 Naxx 25 pole-arm should sim FAR above a level 70 ilvl 154 PvP axe.
Simming a level 80 ilvl 213 Naxx 25 pole-arm should sim above, if not equal to a level 80 ilvl 200 Heroic dungeon axe. Not vastly lower DPS.

**Sim Links and Screenshots**
n/a. Run the sims mentioned above to reproduce issue.

**Desktop (please complete the following information):**
 - OS: Windows 10, latest
 - Browser: Chromium
 - Version: Version 109.0.5399.0 (Developer Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by yebber** [comment]
Polearms in your offhand do not trigger offhand swings from WW and im not even sure your character autos with it. Its not even supposed to be possible ingame to equip those weapons with titans grip. So no i do not think the sim is incorrect about polearms/staffs in offhand.

**Comment by Mitch3llO01** [comment]
I will test the WW idea right now. Your character absolutely auto's with it. I tested two seperate 5 minute auto attack only scenarios on the level 80 Heroic boss target dummy with Betrayer MH and Wraith Spear vs Colossal Skull-Clad Cleaver for offhand.

Test came up after 5 minutes of auto attacking with both as Wraith Spear out DPSing Skull-Clad when used in offhand, as expected from being higher ilvl.

To further back this theory up, Wraith Spear MH Skull-Clad OH was higher DPS than double Skull-Clad (MH/OH)

**Comment by Mitch3llO01** [comment]
It appears when a polearm is used in the offhand, Whirlwind only hits for the MH weapon. When a polearm is used in the Mainhand and axe in the offhand, it hits for both weapons.

While this will make a difference for certain (in my testing the single WW hit from Betrayer/Wraith was usually hitting for MORE than the x2 hit from Betrayer/Skull-Clad, but it was only about 10 instances of combat). This still doesn't account for the off-hand hits being higher and overall higher stat budget on a higher ilvl item in the sims. 

Combo #1: Betrayer/ilvl 213 Cryptfiend's Bite = x1 WW hit, higher autos, higher stat budget
Combo #2: Betrayer/ilvl 200 Colossal Skull-Clad Cleaver = x2 WW hit, lower autos, lower stat budget
Current sim result: Combo #2 beating Combo #1 by over 240 DPS. 
Expected result: Combo #1 being more DPS or Equal in DPS to Combo #1, not vastly lower DPS

**Comment by Mitch3llO01** [comment]
I've run another test and it seems the double whirlwind is making up the damage difference seen in the sim.

To be clear, with a Pole-arm in mainhand, and an axe/sword/mace in offhand, your whirlwinds hit **twice** in-game.
With an axe/sword/mace in mainhand with a pole-arm in offhand, your whirlwinds hit **once.**

Conclusion: Sim seems to be correct, however higher DPS/ilvl polearms should continue to be used in Mainhand over lower axe/sword/maces while the Titan's Grip bug persists.

This thread can be closed/archived.
