### ISSUE TITLE
Crash Report -810784301

### ISSUE THREAD

**Issue by k0okz** [wowsims/wotlk#1581]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUj1II0EU3vd2yW1GPMfDYkwVU4kgzM6QwsYdrRQsFBvttFAsrhArvSqIx4koWKkXEEEQBYmFoCT+pAgRSWVgQUFROEFJYWFzEK/Rmew1113hdfcxvBm+977vMTOPxFzkOAGTkALYASgDVACqgGXE7oY4Kp2Zr2WyAJ+sWNWZhUj/59GZsSkXaTS2D4TSn5vILu4wETkr4EMWiUMfT5HU05ccsnPN24Z06dERsuuMrQWHB8hKN1pQyKJepI7+0qVFzYBFPtKcTl9l7ISjdRaJ0sK29tgqoVY+7yN73A2VxrWepg+RVXSxvZIznX+8mriUN3Fv08SnUxNXj5FYel/MY8LVd47020NO2zJa//EHvjguMJzySXIZIA5dIdupemt7qksNhIcBNRymOpSZnmkzP/O1EXGoNliAVsmF4FJwIaXkHk96XHBPCE8K6Ymk1y55sl0XyHtg7kaAdD1AthZg/FuArSevyL8GWAHnGT6kwboGK3GL0bD1uGoMWzep5vR3g5LfETJlv2W8hktfZDA+yNx//sVz6j1cUqXiu/j8DcK36rtVvz+36vfACLwBAvx88w==

RNG Seed: 3136784201

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 47475} for 500ms, curTime = 44.222155294s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3a0, 0x7a49890})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x7a1b7a0, 0x7a4e000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x7a1b7a0, 0x7a4e000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x7a1b7a0, 0x7a4e000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
