### ISSUE TITLE
Crash Report 1061838572

### ISSUE THREAD

**Issue by mpuryear** [wowsims/wotlk#1585]
Link:
https://wowsims.github.io/wotlk/protection_warrior/#eJztUj1oFEEY3ff2fnZXopPDYrxqsyCESGB210O08FYrC4uAjZVooVhYBCu1OjTBQ1DSmR+U2Igo18qpMeAf5ho9PDFwIbkzEDmwuTKdztySws4idj72fcy+ffO+neHzDjoUVLyMSVaAJ0AT6AF9cBtskhWiSpwsCvhMMAltqg58daBrTDhmFShRfJS9idzElQvXL151HOEWn8MT4scq5acNBrkPbzn3gl5GTOvqiNk25YOOWX1doWzXbO3tLlE21rR3pU79eHvEw2XKmQ4DWN5e8V1/Xq3ZQWazTstzxceXDGzjc8Td15Rbz+gNic4GZU+b7NlBs3vLpt5qmLr22NSfn82GL68oF6bMakGnVvWPuKL5Js0L9glb5tXQRPasfc2cdWyG1n/8gRuuA0kfi8BTHPEOFX2PDjQ9TWramlnNvGZO0x1JNx5PClYx53MUCe5gLD6slIqViuLxWEXjqhTHURhFJa2qMCpFYRyrMDTiJqSz2KLoblHeb9GfbnH0dotq6Rd7yPSRn4c7fGmAb2U9mm0U3EHH6rtkOO29XQ7WmYrWuR1xf3Jgfs6gUT6aKs3yyE5OVKN/Rjr/fACmkt1IqTTe70rO3yC9q9PryYn0vV8+hfP4DaNUhic=

RNG Seed: 4215741894

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 64382} for 360.886788ms, curTime = 2.639113212s
Stack Trace:
goroutine 101 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3c0, 0x5d7a4d0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x5c2b170, 0x79b7500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x5c2b170, 0x79b7500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x5c2b170, 0x79b7500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9

**Comment by psiven** [comment]
Can you try a force refresh? This bug should be fixed in the latest build
