### ISSUE TITLE
Crash Report 311867490

### ISSUE THREAD

**Issue by hendleyr** [wowsims/wotlk#1586]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUk1oE0EU3vd2204GW8dSZIyXNadSKMzOGrBeMvFk8ZLiRS9ikUpBDyEI1oKwiOIPVHrypyh6EFG0JzXEGnvQgglUjK4/aEHaHkoQkZ5UEIxvsxYRPAjqzccwM+973/cezHzcZahwN+QxALgGUAOoAywDfAasIQYIW7pcNLAV8jAOcJkWwjxgp5WstByB1tz+wUNDBdYiEsnbwIWolVE+eYup1uJDvF5F7oibFeTt4hnhjwi3l0rImXheQfnptU2C4h2U1TkSlEu4QLUO8aKIcoYQ50EJLcrvEuPVpJ1yHkd5QoxNURtik/gpdV268UPMxNVplPVJm+aOTUfTFxrRfvpKtL+/HzHO3kM5O4fcIuTLLUy10wM4OWeHPQInAHrG0fofP8VoGwOJ9POFzXyjiFzgQjYu9Zv+5hlkzUB8GTA741KfGSbLjADZirxinYJuX2mtfK207/vKU2lPaeVp7fna93Ta6/VVupcI/iJIdilEcTFEeS5E93iI3eUGqmMh1sFZhrYJ2MaTvIOdXOs2VgI6WTyXGb6er2ZfP9q/LgrusNkPuIII8was1DtMxOkusya+dJl1E+ejqGb6YqSW2bC3GS8zegrzFw6PrsoNHtgzfHCosM/VaXe7ZP/cPEfN3+gSVGf+pI/a1JPP/i65+XjBmUXzXVHPfAMO+qHc

RNG Seed: 2348388268

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 47475} for 500ms, curTime = 25.219847199s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3a0, 0x7ae0560})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x7a1d9e0, 0x7a56000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x7a1d9e0, 0x7a56000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x7a1d9e0, 0x7a56000)
	/home/runner/work

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
