### ISSUE TITLE
Crash Report -725989031

### ISSUE THREAD

**Issue by Crimios** [wowsims/wotlk#1590]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUjFIHEEU3f93PdYxJhOxGK+6bCWCMDvjFTbZ0UohhYeNdrFQLFKIlaY6jEWICHYmByJaCXKVIOflFCHXHOTwdOEUjYIBxSJFSivN39uApEthurzi7+57//2/u/NY0kWJkzAFWYANgBrADcAtYA2x/1kKDSnvG0oBoM1KLjTNQWLozdjs+LTLeHNyBxjntRKKgwv0EttfsFRA5vDrXWSt/Ij4k0vw7CsiXV4sojjN22SoRoZvZKDuOmktfGUPRfkMPbDYU35A8nHe9pxqAS32hG+tUyvNoEcyH5J6vflgbuW5bRQ31G/XG8sX96J6eR/VH7tR3S9G+5c/o/h6hswi5m4HPUafnhiyR5wZ6FpC6z/+wFvHBYHTgyxYAkhBX8y+NIONa7bPZOKbjBmNpV4TxWgmChIlZg1itsdQahxOoz5Ap5ZKSa2k0lpLX6Z9qaSvlK+V9lXa79Yy3U0N+jsI92OIfCVEsRpiqnSPnfMhynchUjp/gpMD6xQs7xyb45eYMM/jde2mI/cpQiXojZla8GKigXqg8pgaFu4/P+x58xhTspXyo8z5G8T/6tW5+X3Mt8EAvIZfOOaB1g==

RNG Seed: 45421705

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 47475} for 500ms, curTime = 1m21.61425088s
Stack Trace:
goroutine 61 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc6e0, 0x75268f0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x90bfdd0, 0x7512000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x90bfdd0, 0x7512000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x90bfdd0, 0x7512000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
