### ISSUE TITLE
Crash Report -966299953

### ISSUE THREAD

**Issue by klohny** [wowsims/wotlk#1592]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmF9sU1Ucx+8593bc3a3Loe7h2gdzrVHrTJPbe20iD2ZFwGCCSYWYLCYmG25AI2xkDg19IgMMTKeExIctMSOIEgVEgTSlLS2wjdGN/WHIkI1tBJku4U8GxoTgA/5+595uHWPGGHiyv91zes75nT/N3Sff3+9UufWCstuhbHc0kuJQfV2DFqpaX1UdrpUdTHJ3EoWx7Seo2jdGPQXH2mlbG1Uk1p6gipPtgPGvxqlHHHpAFZkNJ6g6fEiEBVvBkRmBBTB7KEaVIvZzlKq7YCoRlBK2Ddytd0WPdDZGBZjeD86dB0VPAfThga2aYcbEATzjG/BNHhI9YstxPPjzFNYHoF3M2n6xTrA81/fiwhb4DgMj2BqA1o5x9GxNUY8sS7ozJFaIZbuokLdZFhG6SZnicWsKlQugyFAKoVAoIpQFUAgUh0twU1VsIl6fHtD1gN8MGLruNw3T7zfB/IZp+H0B6OiG7geXeY2o8ugQZZ+doupPE1SbHKTe3wepPjFIJ4k0RRa0ksKFa7gNlccIGQY87D+XoHz9lHJVaiSFS6oatKX1m8LVcgEj7hgS2ZKkaj8SGW2nSSCmkN27Ahxi08l+AGfXmN2V2QUbSycbSVpYckcJuwhodUBXSiKGRWwU3JcANfgShaw5bs9j7MYlqv52AA6DLpLuZEfjNpR9MQSsNYl1M0fzRj/WJ+N4cgecfA5gFGCkNwobyFQnISmP4ByLCEeIR1Flyojq0IiXvCYI2uKgY/kz7wlC5WIAT2LVKmkiL/kCumnoBlJnAGWAIXCnG6Zu+oFIv8/QAzAD8EP2zqQp23edqp1pqrVepN4uYK99hj0BeWsD3VOW1a7TVq2r2lBVC19hgfsMMjaew1gfZ+xPZKyPM3Yuy1jfLMYY67EZK2iP8VUlbDhuY9bXS1H9ztqYSd9nKJJ2AUk7mEHSupM2aekYxREnO5ywSbufQ1oTF7ybJ7gg7uPnRy3SZHbwmNWSWGMiT9z8FhF2k0olpMgyYVQlGgFp8dqCh8InZUXPFkWnLYoKCqKX6OJivs3G/cE3rQ0XBUOkggCpCqcYdvTSJvIi8Ik4Bgyfqb+CsomcIr8mIuuHHgf3GimW2zsoS3ZQtWdiNqHdIILFS+o2rAYdXFm3dlMNROYCdwIZPZrLaO+0DqY5o9Eso+n5dDA9WwfT8+lgerYOQtfa8ksrOE8jaeFpgTl6GWekE1kw90azYJ5KYDymuiMkVebRnGsR4V0XvDBJpbr4KuXaR1H7vCh2EFb1gGH6dAOCb8DPiQqADhoQhcEDwmfBdHqCsq4Jql7uz8P0f7YnChNmacVKbs7WXKL0A2FOCKbVdR9rofpwzYcNssgc7jgidhdo6EXEOk/T1ExMHeaIfQrObkQsxbsTQMjwEdHyMnYNumd2wlLwpjhqkzAyiKilYjywfpINrHdiPLDeSdp7yWwKXI2d2LqdzFL2Bc/X+hNYp+NYTyVwRg9Q1sXZOs9H90SRMAJx1FHhyBM2xyLCyhIMnMBWgYxhD+h6Xudpmun3+UwjgOlZwA9QAVp4W4CbA1wbEC1V3t9D2eEeqh6H68ENuB7chBTt9kMpGt4ClGXra3JTtCji1JGD08gMTtb/fCzOccolaYSTdDqbou3JUHjwQpqwSdqT4aJ1G5b+eIVaonUrPp3mIUbbOEZdqJWXEaPUtzMYTU3DNIORzM5D6xaf2xPHlAxRonmQ5lhEWF2maG7MyERV1IhMrNRqSyj4ttUIBoOYYUkwAyB7zlIwyK3g3mkATyZHDBo

**Comment by jimmyt857** [comment]
Thanks for the report! The raid sim isn't really supported yet though; we'll start taking issues once its released for Alpha.
