### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by 0vertime** [wowsims/wotlk#1597]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

https://www.wowhead.com/wotlk/item=38231/choker-of-forceful-redemption

**Comment by jimmyt857** [comment]
Thanks for the report! This item is below our ilvl threshold though; we exclude items below ilvl 140 to keep the download size of the website manageable.
