### ISSUE TITLE
Bonus Stats : Defense is improving chance of death

### ISSUE THREAD

**Issue by panpaningame** [wowsims/wotlk#1598]
**Describe the bug**
In Paladin Protection Sim
My conf :
https://wowsims.github.io/wotlk/protection_paladin/#eJzVVEFrE0EUzvdmWydrK9PiYYwe0j2FQnV2w0L1ktUfIAEv9WaRFkEPoQhqQYhWIYpK8CA0KOlBQagV9SDR0qBUsMlBQ5BSWrQSCOZSCOLBo2+Tehe0Bx98w5v3ve+bZeax9kFJigyN4hQyyAJ5YA4/xGPgGVADvgItoA36CcoRjjkSChpxMkhjjDW5UADunyOshW04EhmMxJ72XEVv+tz4pYkp2aOsWBW2UteXSH/4Qk7vw2UqFsm21PIi2f0qx/UHm+SI2VdkS3W3THp9QbBghonKBgu4O+R2q08vSee5FRF7j7rGdOG7cCymI+zz/jXpG0+EIxql0Oc208358IBHrGotiO4BlrpTDtd5zvtUca1r/7EU7ppV3q2UaKVjUF8kXdsIsxpnuc1QNVMmx5aWEWkxJi5iOE+R/zJOBjvlPC15RkhTHFUcsg8oxLRNspchGJJBDDCiPCj9moY6sjcvggRuIjFifGN8N+l7xri+l3TdJIfrJY074hvX84znMpVsQMvPq6RuvSX9vEnxVp0S3+pkmnVqwWpjVwH7bcUvxi88KLufdjwYmOzEaqoErCM60K23U84WRTtpdjLYLu4N9hVmw6ikDncrtdTQb7m3RJn7l6f70uPnT5+5MDF1Nu758RNa7vQ8tK8E/8ImW3n3Nz5mdDhz9E+bO5eXvdcIthWtFP8zfgH5PJm7

**To Reproduce**
1. Click "Simulate" (I took 100000 iterations)
2. Check the chance of death (mine was 1.06%)
3. Add 100 Defensive Bonus
4. Click on Simulate
5. -> The chance of death increase (mine was 1.36% with +100 def, increase of 0.3% chance)
Tried several times, same result.

**Expected behavior**
The chance of death must decrease if we add 100 defensive bonus.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 10
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] 107.0.5304.88
![2022-11-04 22_36_44-Window](https://user-images.githubusercontent.com/43447540/200078697-e2959a2d-92b9-4e81-ad03-662d746cced0.png)

**Comment by psiven** [comment]
With default settings this is to be expected as the healing model scales with your DTPS, so increasing avoidance causes them to heal less, while your ability to survive a given streak is not changing. 

Set a fixed HPS amount and they will not adapt. The model is very simplistic but keep in mind that there is some truth to the behavior.

**Comment by panpaningame** [comment]
Ah ! Thanks a lot, didn't notice that thing.
