### ISSUE TITLE
Crash Report -2044300368

### ISSUE THREAD

**Issue by Mooruk** [wowsims/wotlk#1600]
Link:
https://wowsims.github.io/wotlk/warrior/#eJzjkuJgMmDKYCxgbGBkXMHIeIGR8QUj4w9GpgtMTE78CkwOQJkOsMwORkYhBqlprE2MbAE5iZWpRRzsApxSxxm5BAQu7GGSOH+PSYnt6CGmpzuYuDgFPt9hUmIGMXkFLgElj9+DcjkEdu1ikri1lhmo6yxQ4uRtoC6gBEhOQODqNiaJI0givAJHgaqvr2WGaOYU+LsLao6AwEWg7merIWqn7QSZ3L+XSeIF0GROgZvXgcrOnWXiYhHo3QciX58HkW/2gpQd2M0kceY2iHVuG4TFIvBvJ5OSADAgeANYIpgrQEEB9LPWBCaGUYACqlg4GCWYiny5HCcwMiowajA5QsRNHDzBdIOjQyCEEegQCZGydAAlLliYLmSEaQCmJTYBoBkSTF2M6sZGBkbGBgZAwljX2MDUwBTEMTUyMDYEUsaGRkAhQ2NTw0eMPBzTLjMJzLrMJLHiMtMLRpYPjEyzGBluMTIo3WXihNic5iAIsUPEQXLWTBA4aW8JEblgr5gGBtfsjdYyKQRLcNA8jlscqGFKw8kjVDGHGAAJK5+7DtC4/WHvwZjACAAW9YZf

RNG Seed: 4229916055

Trying to cast {SpellID: 47450} but casting/channeling {SpellID: 64382} for 300ms, curTime = 22.649091846s
Stack Trace:
goroutine 10 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc6e0, 0x83cf990})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x65e0e10, 0x32f9500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func3(0x65e0e10, 0x32f9500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:141 +0x1c
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x65e0e10, 0x32f9500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:105 +0x9
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work

**Comment by jimmyt857** [comment]
Thanks for the report! Looks like this is fixed now.
