### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by Hepticlol** [wowsims/wotlk#1603]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
The Freya 10 Man Hardmode Wand
https://www.wowhead.com/wotlk/item=45294/petrified-ivy-sprig
Nice to have for Ulduarprep as it is bis for most classes, even disc priest and even for casters in ToC Patch

**Comment by lologarithm** [comment]
It is currently marked as phase 4 in wowhead. We will change once wowhead updates.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1725
