### ISSUE TITLE
Shadow Priest SIm uses Vampiric Touch when not specced into VT

### ISSUE THREAD

**Issue by beckzudian** [wowsims/wotlk#1607]
**Describe the bug**
Shadow Priest SIm uses Vampiric Touch when not specced into VT

**To Reproduce**
1. Go to (https://wowsims.github.io/wotlk/shadow_priest/#)
2. Spec into one of the meme specs that only go down to Shadowform 
3. Sim
4. Vampiric Touch shows up in the logs

**Expected behavior**
Vampiric Touch should only be used if the priest is specced into the talent

**Sim Links and Screenshots**
(https://wowsims.github.io/wotlk/shadow_priest/#eJztUTFIW1EUzbn/x768ot6GDt9M3z9JIfDyfwvtlN9OBaFIXRx10MlBSpd2Cg5F66BLhzplq1CknYoYsaVWS4yiZlAwxUEQAi2SSDu39yV26ORiNw+P++455977Hu/pXkVMhu7iIYYwQQWgiJ/Oe9AnYBeoAw+6FXwyiG0BFoC0VGea7iQ6BsZHno0+UUlOZpahmc9WyNs+oqBj/TMVy6RT/OsbBc7hEulOnhFzU0zHOp18ckDeqzOn7TIfC92YltbVJZKlu7guSrVGgSs0IfyF9B8sOoHbtDzFzZXzWYobYk2u2+xUsvqio12eXSWJOyUbPy7b2CjZikqJvK81y/daavEDBdcVDAaSQ8kp4NYcJa7wD55rBSaP7P8/Zk3KSScySjT46MNLZM0dE4UmykUmMpKHUWRCY3LZbBRaJmkoMSdblLt9DE+9qRC/q5C3UCH/e5X6flTJnFapDreBa/NIa9ZdauuR//svcIhEUKNU6z6FsfhG+2Y345751xbl/L22spvvHWthPx++JX/Qo//+oU/jy5hSKH+5YE7/pZxj0X6rqbX4/rkQD+MP3T+G0Q==)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Marking this resolved because it is now easy to remove VT from the rotation if desired, thanks to the new APL options.
