### ISSUE TITLE
Elemental T8 4pc Electrified refreshes without ticking, and doesn't accumulate damage

### ISSUE THREAD

**Issue by raethkcj** [wowsims/wotlk#1609]
**Describe the bug**
The [Elemental Shaman T8 Set Bonus](https://www.wowhead.com/wotlk/spell=64928/item-shaman-t8-elemental-4p-bonus#comments) causes the [Electrified](https://www.wowhead.com/wotlk/spell=64930/electrified#comments) debuff, which, upon landing a critical Lightning Bolt ticks for 8% of the Lightning Bolt's damage over 4 seconds. 

Currently in the sim, each LB crit is overwriting the Electrified debuff and resetting the 2 second tick timer, meaning that in a string of crits, no ticks ever happen until no critical LBs land for >= 2 seconds.

Also, the damage from sequential crits is not accumulated, so only the most recent LB crit is used to calculate the eventual tick damage.

**To Reproduce**
1. Sim with 4pT8 and at least 100% spell crit chance (link below)
2. View the Log
3. Ctrl+F "Electrified"
4. Note the timings of buff (re)applications and ticks.

**Expected behavior**
The Electrified debuff should function similarly to Mage's Ignite or Warrior's Deep Wounds.

Instead of resetting the tick interval when a new crit lands, the new crit's damage should be added to the the damage of the current debuff's remaining ticks, and spread over the next 2 ticks.

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/elemental_shaman/#eJzNUjtIA0EQvZk7k8uBsn6KTap4WARBuNwR0CpnKtFGtLGNYqoU4qfQKsbOysLGFGKnhYiFRbQIEiKiogTB74X4SdRYBAQ7BXHvTqKVCrHwLezOm7fzdthdyS1iO3TBEmQaVwCSANsAWYASQKhOBApe9IHONgxAA+eZrYmDozcanhweFV3E6SmDRMj0I9LDPMqOnTQ+J1FykfI9yrwZ1pIZJu4zkU9Z9O4MadL4oIS8lZDuMepg1MzUkfkCUiPNywKjnFRPbopI13MoO+0dHHO/uq7Ux5l7fMeuN6zMDas/MD4ztST/gDSXqzS0VvxCBXJUMOfctSmtMmnXqPS6yKzKF7xNBXKwhbIoggK9wkBN6xxyVaFJt5aRZb06n/+DKYcIBEdg0CMRj8RinqKXXReLzK8jmOssyGpAUxTFH1A11a9qAb+mqprmZ0GbogTYULRboOJGBkn2Dul2Br2vefS9HKNyeIIlEJ+ATwB3CZz8iC7r4FhEr7dbaNHdiQUTe8EOO5MNNkcsnAbVTZxyhUYnxsPR6MSYt59i1Y/4E8b1P7ERUj/49Hyrd/cNdf72KOvaYudZ/aPiKdgFMYB3jj+WcQ==

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version: 107.0.5304.91

**Additional context**
Here's a link to a player using this set bonus in original wrath:
http://wws.piechart-guild.com/uld25/sws-overall-1248905728/actor_0xf130008061004174.html

Scroll down to Damage In By Source -> Oldboltsides, and mouseover the AvCrit and AvTick tooltips for Lightning Bolt(r14) and Electrified. With a max Lightning Bolt crit of 10729, the highest Electrified tick *without* Ignite behavior would be `10729 * 8% / 2 = 429 damage` (8% spread over 2 ticks), but we can see that the actual highest Electrified tick was 1316.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1644
