### ISSUE TITLE
Missing items: Serpent-Coil Braid

### ISSUE THREAD

**Issue by hyperactivated** [wowsims/wotlk#1623]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
[Serpent-Coil Braid](https://www.wowhead.com/wotlk/item=30720/serpent-coil-braid "https://www.wowhead.com/wotlk/item=30720/serpent-coil-braid")

**Comment by jimmyt857** [comment]
Duplicate of #1399
