### ISSUE TITLE
Rogue Bleed Bug on Assassination

### ISSUE THREAD

**Issue by Chainsaber** [wowsims/wotlk#1624]
Adding a Bleed Debuff to the WotLK Rogue Sim substantially increases dps output for Assassination Rogues even though the Assassination Rogues deal no bleed damage.

**To Reproduce**
1. Go to (https://wowsims.github.io/wotlk/rogue/)
3. Click on Talents
4. Scroll down and select Assassination
5. Click on Gear
6. Scroll down and select P1 Assassination
7. Click on Settings
8. Scroll down and Uncheck both Open with Garrote and Rupture for Bleed
9. Scroll down and turn on a Bleed option under Debuffs Section
10. Run Sim
11. Click 'Use as reference' Pin under the simmed dps output
12. Turn off the Bleed option under the Debuffs Section
13. Run Sim

**Expected behavior**
There should be no difference in dps output because Assassination Rogues don't use bleed damage.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: LVL 4 (core: 91.0.4516.106)
 - 
![no bleed](https://user-images.githubusercontent.com/117615059/200216796-05e83115-8008-44ab-955f-41ad0c7d9a46.PNG)
![bleed](https://user-images.githubusercontent.com/117615059/200216825-9ff967f2-2fa3-4bbc-a5d3-94f434f5b3aa.PNG)

**Comment by vigo2** [comment]
If no Bleed Debuff is present, the sim assumes there's no external bleeding sources, and only uses Hunger for Blood if "Rupture for Bleed" (and optionally "Open with Garrote") are checked.

**Comment by b-r-a-n** [comment]
> 

As @vigo2 mentioned, this behavior is intended. I can see how it may be confusing though so I'll consider adding a warning in this case (Hunger for Blood talented but no bleed source).
