### ISSUE TITLE
Ret paladin rotation.

### ISSUE THREAD

**Issue by dwright1241** [wowsims/wotlk#1627]
**Describe the bug**

**To Reproduce**
1. Go to 'settings'
2. Mouse over judgement
4. See error - cool down time shows 10 seconds. In-game cd time is 7 seconds with 4 piece and 8 seconds without t7 4 piece.

Is this effecting sim?

**Comment by TheSorm** [comment]
No that's just the tooltip. If you look into detailed results you will see that it's handled correctly.
