### ISSUE TITLE
Edge of the Tuskarr

### ISSUE THREAD

**Issue by Leiffis** [wowsims/wotlk#1629]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=37032/edge-of-the-tuskarr

**Comment by jimmyt857** [comment]
Thanks for the report! This item is below our threshold though, so we wouldn't want to include it. We exclude low ilvl items to minimize the amount of data the site needs to load.
