### ISSUE TITLE
Crash Report 307717581

### ISSUE THREAD

**Issue by Eluulne** [wowsims/wotlk#1630]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztUjssBFEUnXvf4BmfPKJ4thpTiUTyZiebUO1QkSgWjRIJlUJ0VCIaKiVKhYZNWJ8IlsIUJBZZ4hckPoXEJxoJiYQ7O4VQKeicvNycd+89532NfI5VUAczgHsAtQYHCSaWQwsUa6HRrAHIjnW19Xb08ByRE0qCIcToCsrdC7SyFzdwZwkNXdytoFEgtldRXh+jxdYpycXBJsrTOCNBfIEEZyR4XsJUCo08kZhAuXnCLNCMQjFL5aM4s3TSaeSzP4dyaJpZzDcXYo7KN1OkpvJOxtlLoLwlZ108JPzlL9/9+Ljrx/uk35GcRJk6YcSm5wOmi8E18uCgIIYVI6j94wv66GoEdkN7hWGGOHEmmQkc6jPV/pjbGBDXdf2PoVMHDEOTijjKUXYkrL6h0lFhFVGOY1NUtuNQn21nhorYld/bP3EFki97KFY9lBsemm9pLH9Oo3pN4y3oT5A7DtopaNY55gY76nSLgiOUuKXjYz62otVBZi9a1pnBYTQcR7NZ8j9/+UH3N1z6t7xf8fkJgrtqOHdrgvlLtA5a4QNGpoDf

RNG Seed: 930870231

restartMelee used while auto swing isn't cancelled
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc760, 0x2ffd88})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).restartMelee(0x7ace208, 0x7a66f30)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:587 +0x1b
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x7a66f30)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:340 +0x14
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x7a66f30)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:267 +0x1b
github.com/wowsims/wotlk/sim/core.runSim(0x7a57600, 0x0, 0x1)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:110 +0x3b
github.com/wowsims/wotlk/sim/core.(*Simulation).runPresims(0x7a663f0,

**Comment by lologarithm** [comment]
While this shouldn't have crashed - you are using enhancement talents in the elemental simulator. This will produce less than desirable results :)

Fixed in: https://github.com/wowsims/wotlk/pull/1649
