### ISSUE TITLE
Crash Report -1297994774

### ISSUE THREAD

**Issue by Dencyl** [wowsims/wotlk#1631]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztUT9IG2EUv9+747x8rfJFHK52aHpTFYTvctygS04nhw5Cl452qHToIG51CuogCjYtRUxAI5JBkOyptlns0OCSIZZikQZR0KHQVtRs+i6ng5uDbv4+eLw/v/d7j++JJxZJUvQGo0gDq0AVOAQaoCpRmjDwWMJGAgoBU6YvKVQHNYA+rV3r3DYmYA69ffXu9ZgFKTpLEFKefCH7/IPhmIVN+l4iYcjNDRKtssH5xd/k6HuctOTHMtk7RZ3Ls+skHsgljjNchiba5DFzc/91x2ABTTyU/76SY2Y/N/WkPOPqwRpnOIzEjtbJ3voVzporh3ayQtyV/8mcfJ5Wm1vsr4TMbIHsTwWDvTVWqS+HC5yWybEsQ7UO6S/17gxp97iGcdOCTQlMkCnCs2sz6FLK7/GUz5Y95fHzXeUlXT+plOeyYet5ru/uwbb+HJCcr/FJa5RYqNGz9zVS2W06hPEXLTnE4iNN/EiVgB1ozi7FmoPTI0E8WqEjeJTLhqikeqNMNfX0qitZpMQL27rzy00Ft6GSrny7FZ2bIPqr57tBfxQ3UoMYxgWOVH6e

RNG Seed: 4141477041

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xe2180, 0x119a720})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x2052ea0, 0x6fe2a00)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:90 +0x2
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).RotationActionCallback_RD(0x33b1000, 0x2052ea0, 0x6fe2a00, 0x6fd5e60)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:196 +0x4
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:209
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report! The tank DK sim isn't released for alpha yet though, so it isn't expected to be working. Going to close this, and we'll start taking issues when the basics are ready.
