### ISSUE TITLE
Question more than a feature

### ISSUE THREAD

**Issue by Apanocles** [wowsims/wotlk#1636]
Hi,

I don't know if I'm asking this question in the right place but I didn't find another so please excuse me if I'm wrong.

First, I want to thank you for wowsims et congratulate for your beautiful job. Wowsims helps me a lot.

My question is : Are set bonuses on the calculation when we hit "simulate" ? I'm not sure because sometimes I don't really see a difference when (I think) it should have a big one.

Thanks

**Comment by lologarithm** [comment]
Yes, all sets should be included. There is a UI bug with wowheads tooltips that make the set bonuses not highlight when hovering the items. 

You should still see dmg / buffs / debuffs caused by the set bonus.

**Comment by Apanocles** [comment]
Okay thanks ! I thought so but I needed to bo sure
