### ISSUE TITLE
Adding Berserker Rage

### ISSUE THREAD

**Issue by Apanocles** [wowsims/wotlk#1638]
Is it possible to add the spell Berserker Rage (ID=18499) for the warrior please? I use it to generate more rage but I can't add it on the settings

**Comment by TheGroxEmpire** [comment]
Berserker rage is not useful for warrior dps as currently the sim doesn't have any damage taken mechanics for dps. For prot it might be partially useful, however, rage has never been an issue for prot. There's no promise, but I'll keep this as low priority suggestion for now.

**Comment by Apanocles** [comment]
Okay I understand. I used to put the two points on the talent tree to have the 20 rage points bonus. That's the way I meant "use it to generate more rage". It's still 20 rage points every 20 secs
Thanks a lot for your time and your comment !
