### ISSUE TITLE
Missing item: Edge of the Tuskarr

### ISSUE THREAD

**Issue by Leiffis** [wowsims/wotlk#1640]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

https://www.wowhead.com/wotlk/item=37032/edge-of-the-tuskarr

I would like you to reconsider this item proposal: https://github.com/wowsims/wotlk/issues/1629

This item is used by the top parsing rogue (number 1 in the world in overall damage) seen in this warcraft log: https://classic.warcraftlogs.com/reports/bvfyWCnqtgX7QFN2#boss=-3&start=311562&end=3320066&type=summary&source=27

As this is an item most rogues would like to sim to see the results, I think you should make an exception to your low ilvl rule. I know that you have made exceptions with other low level items such as https://www.wowhead.com/wotlk/item=12590/felstriker which is also used by rogues for the same exact purpose as edge of the tuskarr was used by the top parsing rogue: aoe fights.

Thanks in advance.

**Comment by lologarithm** [comment]
It doesn't look like Edge of the Tuskarr has any activate abilities on it... Can you just pick any other item that is same type and roughly the same stats?

Felstriker has a special active ability  which is why we included it but not the item you linked.

**Comment by Leiffis** [comment]
The reason for using it is because it has a very high chance of applying instant poisons since it is 2.9 speed (IP proc chance is higher the slower the weapon is) and a 1 hand weapon (so rogues can use it). I don't think there is any other weapon that is so slow AND a 1 hand weapon. So it is unique because of those qualities. It seems to be the slowest 1 hand weapon in the game that we can use.

The point is to compare the best available offhand options and there is no other weapon that is the same type, ilvl and speed. (best mainhand is titansteel spellbale https://www.wowhead.com/wotlk/item=45085/titansteel-spellblade becuase it is a very slow dagger and FoK https://www.wowhead.com/wotlk/spell=51723/fan-of-knives scales better with daggers)

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1711
