### ISSUE TITLE
Ardent Defender Cheat Death does not proc

### ISSUE THREAD

**Issue by paragonsix** [wowsims/wotlk#1641]
For the Prot Paladin sim when you look at the log and follow the health loss the first death does not proc the cheat death aspect of Ardent Defender.  I assume this would greatly impact the % chance of death stat.

**Comment by psiven** [comment]
AD is also still using TBC logic (leapfroggable DR). Thanks for the report, I meant to look at this already.

**Comment by psiven** [comment]
Fixed with #1763
