### ISSUE TITLE
SIM over multiple items in a particular slot 

### ISSUE THREAD

**Issue by chreez** [wowsims/wotlk#1655]
**Is your feature request related to a problem? Please describe.**
Feature -- It would be nice to just hit a checkbox and in bulk run a sim against every single item IN A SLOT. You can see this in many other sims and this can be generalized for every class. I saw the "bulk item sim" thread but that seemed to be a much more complicated request. This one is just to iterate over a single slot.

**Describe the solution you'd like**
I think it would make sense to have the gear selection modal a table that includes check boxes or a multiple selection. You would have a secondary button in this modal that says "SIM All" and it would iterate over each one and sim them each-- showing you the +/- from your currently "equipped gear"

**Describe alternatives you've considered**
I was considering writing a greasemonkey script to do this.. I'd rather not :( Right now I am going through and clicking each item then going back one screen and clicking SIM -- also I need to remember the history of each item ive simmed and I have to click "set reference icon" every time.

**Additional context**

Here is an example of the old mage tbc SIM: 
![https://media.discordapp.net/attachments/948414175925927979/1039813094806925392/image.png](https://media.discordapp.net/attachments/948414175925927979/1039813094806925392/image.png)

You can see how I clicked multiple items and simmed them against one another.
https://cheesehyvel.github.io/magesim-tbc2/

**Comment by jimmyt857** [comment]
Thanks! We already have an issue for this, #1512
