### ISSUE TITLE
nothing shows up on my wowsim page 

### ISSUE THREAD

**Issue by jaxxerr** [wowsims/wotlk#1656]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the 
![why](https://user-images.githubusercontent.com/117823179/200814077-0533ae96-2455-4372-86de-2c5e6480d1b9.png)
problem here.

**Comment by jimmyt857** [comment]
This is probably #1509
