### ISSUE TITLE
Shadow Priest basic rotation doesn't use mindflay

### ISSUE THREAD

**Issue by Vysci** [wowsims/wotlk#1659]
**Describe the bug**
When selecting the "basic" rotation type it doesn't use mindflay at all. It also ends up using SWD regardless if you have it selected it or not

**To Reproduce**
1. Go to 'Setting" then select "Basic" for rotation type
2. Select "Basic" for rotation type

**Expected behavior**
Use mind flay and not clip it. As well as toggle SWD on and off

**Comment by jarveson** [comment]
basic rotation was removed
