### ISSUE TITLE
Fire mage does not cast "scorch"

### ISSUE THREAD

**Issue by RisaAudr** [wowsims/wotlk#1662]
**Describe the bug**
"Scorch" is not cast according to the log when "Maintain Imp. Scorch" is enabled, for the fire mage rotation. 

**To Reproduce**
1. Go to settings/spec
2. Choose "Fire".  Checkmark "Maintain Imp. Scorch" box. 
3. Run sim.
4. See no cast of "scorch" in log nor in damage output. 

**Expected behavior**
Expect to see scorch damage, and to see no just the aura applied but a refreshing every 30 seconds of the scorch cast. 

**Sim Links and Screenshots**
N/A 

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: [version of what? my OS? my browser? or of the sim? Sim version is not publicly viewable, at least not that I could find, but might be worth adding somewhere...]

**Additional context**

**Comment by RisaAudr** [comment]
Hmm, thought of something after writing this: If I turn off the "spell crit" debuff, but tick the box, it does cast scorch in the rotation. Perhaps the checkbox for "maintain imp scorch" could be tied to disable the crit buff? 

Either way, this seems to have fixed the user error. Feel free to close or remove. Thanks for all the work on the sim! :)

**Comment by jimmyt857** [comment]
Yeah as you've discovered, this option basically means "if there is no spell crit debuff applied, use scorch to apply it". When you turn on the option in Debuffs, which represents another player providing the debuff, your mage no longer needs to cast it.
