### ISSUE TITLE
Black Magic currently proccing from Necrosis

### ISSUE THREAD

**Issue by CharWS** [wowsims/wotlk#1663]
**Describe the bug**
The Black Magic weapon enchant is currently flagged to be able to proc from hits of Necrosis (the unholy death knight talent) in the sim, this is not an effect that can proc the enchant in game. 

**To Reproduce**
1. Enchant a weapon with Black Magic
2. Talent into Necrosis
3. Run a few iterations keeping an eye on when Black Magic procs in detailed results
4. Note that Black Magic will proc from auto attacks dealing damage with Necrosis

**Expected behavior**
Black Magic should only proc from harmful spells, of which Necrosis shouldn't be flagged as one

**Sim Links and Screenshots**

<img width="952" alt="Screen Shot 2022-11-10 at 2 00 00 AM" src="https://user-images.githubusercontent.com/104176019/201022201-d8cc6507-b91e-4045-a79d-376d2fc13ba3.png">

**Comment by rosenrusinov** [comment]
Fixed in #1671
