### ISSUE TITLE
Include additional options for dealing with pre-combat actions such as ICDs and Pre-Combat Potion

### ISSUE THREAD

**Issue by CharWS** [wowsims/wotlk#1664]
**Is your feature request related to a problem? Please describe.**
There are actions and effects that happen prior to a fight that the sim currently can't handle such as having a proc with an icd. There are times when a player might intentionally want to delay an icd of a trinket prior to engaging in combat so that it becomes available at a set time after the pull. Another example is using potions prepull at various times, if one wants to be safer on specific pulls they may use a pre-pot sooner on a pull than immediately before combat begins so that they can ensure a potion goes off.

**Describe the solution you'd like**
Add a time toggle for various internal cooldowns of applicable items prior to pull.
Add a time setting for pre-pull potion such that they could be used at a specific time before combat is engaged.

**Comment by jarveson** [comment]
#3007
