### ISSUE TITLE
[DK sim] Add Defense stat and % line to stat table

### ISSUE THREAD

**Issue by Nonstopich** [wowsims/wotlk#1665]
There is no way to control defense stat in the process of changing equipment to Blood DK.

Please add the Defense stat total raiting and def% to the character stat table.

I calculate this value manually on a calculator.)

Because Blood DK is a tank and the defense stat is not needed for other specs I think the display of this Defense line can be tied to the CheckBox in the settings called "Show Threat/Tank Options" and display the Defense line only when this option is enabled.

best regards Alexander

**Comment by rosenrusinov** [comment]
I think you're using the wrong sim for dk tanks as the DK Tank sim already has the Defense Rating stat visible:
https://wowsims.github.io/wotlk/tank_deathknight/

![image](https://user-images.githubusercontent.com/5707996/201082026-e25157f7-f7cc-4ffc-ab21-7d83996c0d2b.png) 

Maybe its a good idea to have the Defense Rating converted to the Defense stat in the tooltip or somewhere else.

Leaving issue open for now

**Comment by Nonstopich** [comment]
Then my post is not a problem.)

But the problem is that there is no img-link with a tank-dk in the drop-down list on top of site.

**Comment by rosenrusinov** [comment]
The reason that there is no link in the dropdown is because the tank sim is pretty much unfinished and not even in alpha. Only sims in alpha state are enabled in the dropdown else you need the direct link
