### ISSUE TITLE
no items are shown

### ISSUE THREAD

**Issue by Eltsapo** [wowsims/wotlk#1667]
Hello. It. is the first time Im using your simulator, and the issue is that no items are shown at all, nor am i able to select an item for a slot. Shouldnt the items load by themselves? The problem occurs from both my laptop and my phone, at my phone a message appears if you stay more than 5 seconds at the page saying "A problem repeatedly occurred" and the page doesnt even load. I downloaded the addon you suggested and tried importing my gear but that doesnt work as well. 

**To Reproduce**
I just enter wowsims.github.io, click feral and no items are shown

**Expected behavior**
I guess there is an already existing set of items used or at least i am able to import my gear from in game or select an item from each slot. 

-my phone: Iphone
-my laptop: browser: safari 

Thank you for your understanding.

**Comment by lologarithm** [comment]
This is already being tracked in here https://github.com/wowsims/wotlk/issues/1509
