### ISSUE TITLE
Crash Report 23028472

### ISSUE THREAD

**Issue by Gibson2121** [wowsims/wotlk#1668]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1F6WJka2gJzEytQiDnYBNqnVjFz8AmsXM0m8lFVi23aY6dxZJi4WgcadTFw8Atv2MEk8kFViPryDiYtdYN0VJonr7EDVbVuZJLZIKrEBhUEyPAJ3lzNJHOBRYr57GMRbuIRJ4jCc920vkxIbkNl1BGTGxW1MEv8kgYzOW0wSn2SBNnXtBNn38D+IfLMXRN69CVK5CKjyrCyQcWg3mMEicPUmkxIH0KusASwJLFoTmBhGAQqoYuFglGCKEgMGOosEkwKTAbMFkwMrMMpZBJgkGLsYNQ0MTI0NjEGkqZEhkDIyMDQwNjY2NDA11AVywchY19TA6BEjD8eJp0wCx58ySRx8yvSCkekDI+csRoZbjAxKd5k4wbY1pDkIQuwVcZCcNRMETtpbQkQu2CumgcE1e6O1TArBEhw0j64WB2qY0nDyCFXMIQZAwsrnroMjhP/D3oMxgREArmpstg==

RNG Seed: 1209678854

No enchant with id: 3817
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xbc3a0, 0x6f7d8b0})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core/items.NewItem({0x91ad, 0xee9, {0x5101bc0, 0x2, 0x2}})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:268 +0x22
github.com/wowsims/wotlk/sim/core/items.NewEquipmentSet({{0x91ad, 0xee9, {0x5101bc0, 0x2, 0x2}}, {0x9c81, 0x0, {0x0, 0x0, 0x0}}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:297 +0x5
github.com/wowsims/wotlk/sim/core/items.ProtoToEquipment(0x6fc6f40)
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:304 +0x9
github.com/wowsims/wotlk/sim/core.NewCharacter(0x20a5c00, 0x0, 0x203d1e0)
	/home/runner/work/wotlk/wotlk

**Comment by b-r-a-n** [comment]
This was a temporal issue related to the client/wasm binary somehow getting out of sync.
It should be fixed now.
