### ISSUE TITLE
[Prot Paladin] Eternal earthsiege & Eternal Earthstorm Diamond meta (sbv) does not seem to be working

### ISSUE THREAD

**Issue by GNouchi** [wowsims/wotlk#1669]
SBV is the same when switching between Eternal Earthsiege/ Eternal Earthstorm (sbv) and Austere Earthsiege (armor) gem should be triggered in both cases. Purple gems are in 2nd slot in chest and multi-color nightmare gem in shoulder slot. Tried changine shoulder to a a green gem and using the purple in the belt prismatic slot to no success.

**To Reproduce**
This can be seen from the p1 preset. To emulate, just change the meta to Austere Earthsiege. You will notice the armor gem activating as the armor value increases however there is no drop in block value as would be expected if it was activated. 

**Expected behavior**
I believe the sbv meta might just not be activating at all. 

**Sim Links and Screenshots**
default settings on visiting the page with p1 presets for prot pal on landing
Done on windows desktop in chrome

**Comment by psiven** [comment]
SBV % modifiers do not currently show on the GUI. You should still see a change in Defense rating from the gem activation, and the appropriate effects on the sim.

**Comment by jimmyt857** [comment]
Closing since this is WAI.
