### ISSUE TITLE
WoW Wotlk Warrior Sim

### ISSUE THREAD

**Issue by hellrider81** [wowsims/wotlk#1673]
First of all thank you for this great simulation!!!!!

Can you also add a function for the talent Enrage in the Warrior Fury tree?
It procs only if you are receiving dmg and gives you a %dmg buff.

Thanks :-)

**Comment by jimmyt857** [comment]
Thanks for the suggestion!

We could implement the underlying functionality, but making it do anything would also require some sort of model of damage taken. I don't think the benefit provided by this would be worth giving up more screen space / making the UI more complex.
