### ISSUE TITLE
Presets for Stat Weights for multiple characters

### ISSUE THREAD

**Issue by kiler2010** [wowsims/wotlk#1680]
So it will be cool to have presets for stat weights like for gear and encounter settings

**Comment by jimmyt857** [comment]
Thanks for the suggestion! I don't think this is something we'd implement anytime soon though; stat weights are not a first-class citizen in our tool, they don't do anything other than sort the gear picker menus. I can see how this might be somewhat useful for classes which have wildly different stat weights depending on spec (e.g. mages) but the benefit would still be pretty small compared to the amount of work required to develop something like this.

**Comment by kiler2010** [comment]
Thank you for answer vm!!! I played on diff chars with same class, so it would be great for stat weight's to pin with current gear set at least...
