### ISSUE TITLE
Missing items: Girdle of the Howling Berserker

### ISSUE THREAD

**Issue by DaveOMac** [wowsims/wotlk#1681]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
[https://www.wowhead.com/wotlk/item=37785/girdle-of-the-howling-berserker](https://www.wowhead.com/wotlk/item=37785/girdle-of-the-howling-berserker)

**Comment by jimmyt857** [comment]
I think this is below our ilvl cutoff. But sometime in the next few weeks we might be able to get all those extra items included anyway.
