### ISSUE TITLE
Warrior - Maintain Hamstring

### ISSUE THREAD

**Issue by david2278** [wowsims/wotlk#1684]
**Is your feature request related to a problem? Please describe.**
I would like to sim for a moving PvP target constantly running away. For this, at the very least, maintaining hamstring is a must.

**Describe the solution you'd like**
An option to maintain hamstring like with thunderclap and demoralizing shout

**Comment by jimmyt857** [comment]
Unfortunately we don't support PVP scenarios. To get anything reasonably accurate we would need dozens of other settings, maintaining hamstring wouldn't even come close to being reasonably accurate.
