### ISSUE TITLE
Crash Report 522072987

### ISSUE THREAD

**Issue by georgemancer** [wowsims/wotlk#1686]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUk1oE0EU3vey2WzGthlFZFzasi4eSqAwu8tCBGFXj54CXnoSilSKeohF0BaEUCrUFsWqlCSIiIoUvXhRQm3jT7wEFHJoeyieCtEoEQMeWrzUt0lL8SAI6s3Hfm9n53vf92aHxywdOUochgxkAeYAngC8BKgC1AE2AKuIR7mJEgIYoJrJVs0eTIGxHh0HLX12cHRoRI9yZrwAluDFtyg+9VjaszLWisji/Nt7tCILtOzgXxZQ3O+1Iiv0FeMzJRTrPSR59RTFBkmoPpQwPl1GcbnXAoV18tdE3uq2VGIUsmguoqWR250KkrJBhl93lAl+YxXFbLelUYewpcqvlsI89TDMjcUwX3sQNq9vonhk0CL/HMWcQfvTJbQSOsrOFKTVAfVi+KfJ66j8j59iLKaDwLuA3+E0O5YDuAcHGepxAhCQECFohCghRlAJXaSiCUrDubZN0x9tvSfLAc1bkSZKMYzd25wAE5K79M3tgCnok67nuY7tua4r6ZGOtKXj2q4tpd0vpSe9fuk60l0DoTdqyAtLKD7W0MwtYV9uGWV+GeugNiFWgMNMY6r+4XGEcdalX9ln7jQKGX5zHn/BzLzDVVCszxhvH/VEsHXmvcH+Qj6Min+ovVP1D5xqxYrvzGPm9qWxjvTg+ZPDF4ZGzpiOZx4X+j8fr4ngb7hkK2/+xEemkpkjv1vcurzs7Fqwpaj7PwD4kq97

RNG Seed: 0

No enchant with id: 3817
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xbc760, 0x7a60870})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core/items.NewItem({0xa638, 0xee9, {0x7a62278, 0x2, 0x2}})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:268 +0x22
github.com/wowsims/wotlk/sim/core/items.NewEquipmentSet({{0xa638, 0xee9, {0x7a62278, 0x2, 0x2}}, {0xae73, 0x0, {0x7a62280, 0x1, 0x2}}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:297 +0x5
github.com/wowsims/wotlk/sim/core/items.ProtoToEquipment(0x7a6cbc0)
	/home/runner/work/wotlk

**Comment by jimmyt857** [comment]
That enchant ID refers to the head enchant Arcanum of Torment, but the live version of the site does not have this issue. Try refreshing your page!
