### ISSUE TITLE
Elemental Mastery haste component is not applied correctly

### ISSUE THREAD

**Issue by Shavv66** [wowsims/wotlk#1696]
**Describe the bug**
Elemental Mastery applies a 15% spell haste buff for 15s. I have seen two ways this can be applied incorrectly:

1. It does not apply at all
2. When in effect alongside Bloodlust, it lasts for the remainder of Bloodlust's duration, rather than just the remainder of its own duration

**To Reproduce**
Example 1 - Haste buff does not apply at all
1. Go to [sim link](https://wowsims.github.io/wotlk/elemental_shaman/#eJztkjFoFEEUhvd/u9mbGyM3nqCTIyfnCHIEhNldTmJ1q1UEkROblCoqCBbBTgsJksJYBRTBYJFKQRGEKCQxEQkX5RDlTKGgOYtIJIiIWkjUIs7scmI6i9j5isf/vve/N8vs8M2MetGHEWAME1vvgprAvk4GiRKVUUM/8k5hoeMC/Nrpo2dPnGFZkSlMg+fErfskPxaVPzdLDyeIZ8XXBVLuGyM7xeNpkotF5Y41bLX0iuTlbcq1tpyYNb17Xco3PQs2iqEHJK/nlWdGHc7FpymSV7oVHDO5MkPKNy67JyfmzORwMQF2MiOeGHC1m3vi3SqZ3Bq3+cOMzV9uWsPqOMlvRSNemDOWmeFPp0htYNCoef0dF4GeEXL+x5o45zMIGsAxzXcWuNGupJK5MUb7k/5gLS7jUOrdHWv02ifiGR8uYUdUibTWQSWMwiCKKkEUhpEOjNgV6VBXtI6CRUg2WSfxqE6yuUSln2+p/GOe9Pd5Wob3GZlRnOKCe2zyGfKs/VUJeX/bXUvsf/6D5LjLhre0AYsTcON8G/Sk4Plvh4pfw1Etyqbl8XhTKg7GXaPXbDSqe1LSrG4/mcTLaniHSocl++cvZyhejy2Djfq67PmbSO/qQCvem9Yr1T4cwS9YP4Jq)
2. Click on the 'Detailed Results' tab
3. Click on the 'Timeline' tab
4. Click on 'Sim 1 Iteration'
5. Scroll to around the 16s mark where it casts Elemental Mastery
6. Hover over the Lightning Bolt casts either side of the Elemental Mastery cast, and you will see they both have a cast time of 1.24s

Example 2 - Haste buff applies for the remainder of Bloodlust's duration
1. Go to [sim link](https://wowsims.github.io/wotlk/elemental_shaman/#eJzjEuZgsmD0YJzAyLiAcYf4BkamC4yMTjwcjBKMCkwajAGMEYxCDFJ3WJsY2QJyEitTizg4Bdil9jBy8Qus2sok8UZWie3oIaZ9O5i4OAU+3WFSYr4NZPIIHNvDJPFIVol5wUkQ7+l1JonJckrMIGX8AoeAclskldiAciABXoGW3UwSc4SUWIBaGbi4BN7tYpKYIqPEyADU+WMvkxIbUBXIHH6Bo0CdnbJgAZBOdoHjQIFpMlwsAo//MwHJu5tB5Ku9IPLjcpCC/5uZJL7JAhkXgXa84ACKn97FpMTNwWjAGMASwdrByKg1gYlhFKCAKjYORgGmAsYkAy41KS4gm1mCSQEYYhxMnmD5hgAHDcZAiFozBwNGC1ASYQGqY+xiVDY2NTYwMDA0NTI2MjQ2NjU0NjIyNjAEMnSNDYwMTA0MjA0fMUpw7DzCJHDgCJPEhadMCr/vMWn8usRk8PMS0wtGlg+M7LMYM7kEuFg4dp5lFOKAuQos8mw1M6oIKJ6RRPi5mDk6xWACHA5ggWV1MAEViMA5uAoth1uMDEp3mTgh3BQHQQjDz0Fy1kwQOGlvCRG5YK+YBgbX7I3WMikES3DQPOW0OFDDlIaTR6hiDjEAElY+dx0cIfwf9h6MCYwAWqOCbA==)
2. Follow steps 2-4 from example 1 to sim and view a single iteration
3. Scroll to around the 25s mark where the Elemental Mastery buff falls off
4. Hover over the lightning bolt casts on either side of the Elemental Mastery buff falling off, and you will see they all have a cast time of 1.08s
5. Scroll further to around the 43s mark to where Bloodlust falls off, and you can see the Lightning Bolt cast time remains at 1.08s all the way up to this point, after which it finally becomes the correct 1.61s

**Expected behavior**
Example 1 - After Elemental Mastery is cast, the Lightning Bolt cast time should become 1.08s for its duration
Exmaple 2 - After the Elemental Mastery buff falls off, the Lightning bolt cast time should be 1.24s for the remainder of Bloodlust

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Browser chrome
 - Version 107.0.5304.107

**Additional context**
The thing I was trying to experiment with when I discovered the issue was casting Elemental Mastery before/after Fire Elemental Totem. This is one of the differences between the two scenarios, although another difference is that one is cast during Hyperspeed Acceleration and the other is not.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1710 fixed
