### ISSUE TITLE
Mage sim

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#17]

**Comment by pilotchute** [comment]
Linking #425

**Comment by mormigil** [comment]
Most of this has now been done here https://github.com/wowsims/wotlk/pull/483

**Comment by mormigil** [comment]
Still to do
Add Mirror Images,
Add Frost Spec,
Add better automatic cooldown mgmt,
Add T10,
Add 3 target configurable fight setup for living bomb maximization,
Add several aoe setups,

**Comment by jimmyt857** [comment]
This sim is now in Alpha.
