### ISSUE TITLE
Expertise weight calculation is inaccurate (bumpy)

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#1701]
**Describe the bug**
The weight of Expertise is not properly calculated.

**To Reproduce**

1. Make sure to be under the Expertise cap.
2. Click the STAT WEIGHTS button.
3. Click the CALCULATE button.
4. Write down the computed Expertise weight.
5. Close the window.
6. Decrease the Expertise by 4.
7. Click the STAT WEIGHTS button again.
8. Click the CALCULATE button.
9. Compare the computed Expertise weight with the value written down at step 4. It is very different.
10. If the value is not significantly different, decrease the Expertise by 1 and calculate the stat weights again. Repeat until you hit the bug.

**Expected behavior**
The weight of Expertise should not change significantly when adjusting Expertise rating by just a few points.

**Sim Links and Screenshots**
I actually graphed the computed Expertise weight for 21 consecutive Expertise rating values and you can clearly see bumps up and down every 3 to 5 points:
![expertise_weight](https://user-images.githubusercontent.com/4045314/201612301-b42ccd9f-d004-44c6-aa6b-981647264d60.png)

**Additional context**
The problem is that the simulator adds a constant Expertise rating value (+10 I believe) to compute the weight. However, unlike other stats, Expertise is not purely linear, it can only be gained in -0.25% parry/dodge steps. This means that most Expertise rating points give nothing, and then one more Expertise rating point will make you reach the next -0.25% parry/dodge step and will appear as having a lot of value.

At level 80, we gain -0.25% parry/dodge every 8.1975 Expertise rating. When the simulator adds 10, there are 2 possibilities: either we were right after a -0.25% boundary and will will gain just another -0.25% parry/dodge, or we were right before a -0.25% boundary and will will gain -0.50% parry/dodge at once. This suddenly makes Expertise appear to have twice the value it was estimated to before.

**Suggested solution**
I can think of 2 ways to address this problem:

1. Change the code to ignore the 0.25% steps when computing the weight of Expertise. Claim it is purely linear, same as hit rating. For the purpose of the stat weights calculations only, or course. The rest of the simulator needs to preserve the steps, as this is how the game implements Expertise.
2. Instead of increasing the Expertise rating by 10, increase the parry/dodge reduction by 0.25% directly. Compute the resulting benefit, and divide the result by 8.1975.

**Comment by jimmyt857** [comment]
Thanks for the report! Your diagnosis is spot-on too. This will be fixed in a few minutes.
