### ISSUE TITLE
Crash Report 218385554

### ISSUE THREAD

**Issue by Sulous** [wowsims/wotlk#1702]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmn9sU9cVx9+9fo6dR9LcZhQeFmGvFms9NEvP72EJpm1xgKF07aQM1DWd1I0MAmSFhBlowX+l/BgQoLC2MH6MhQFTS8vGCihKYicBQgvhNwkkhY4fY4Smg/JjtBpCa9k59z7HduwAomVThU/ynPfuu75PSj4553y/18rqF5TWbyi35DkkqyhYMUMrKplSMqGs3GlnsqueKDlsfgNV/5nnztjRTKurqSKz5jBVsthCGF4yyG1rv00VBzsVpuqKgTB7LgzfhNkwtb2WKgo7XkPVqkFuIinZbB7cfGOQW95XSyWYewRu/XagOwMu4RtWWQr3r+TB4n+COysHum2r6/CBrzbi6zt1+NjqDyhfXNy5sAHfthoefjAPTo7CyaJBMD63kbqdTlnPLrIV24Ysp1I6EiIk7SdDFLdLU6gzAw4nHJlwUDhscDjgIHDYcyUXVW1VxOPV/bru95l+Q9d9pmH6fCaEzzANn9cPF7qh++CWeZ6oztPtlC3ZRdV3O6nW1Uo9H7VSvbOVdhH5GnGsIZmPTuTRnl9LyCkAQ1IW2QG/0TODs7XnSoLBsoog4JfpqkH8LnZQ9WMA6r3d9PAhqmSym3+jblukFmFojVD1XJ7b1snpaRMMZrEPI5xB2x9aKEB3AliaD9BFEDqFnYabbwxEHjPZ0noqZuWwYzB8FR4Ds9r5assaEEGYdLLDmiSzpRzES0fwdWc9ztoJzzyUFzuR2a4wokf1DEBPTqOXFCEp+LSSv5wQjRSIkR8EnuI/KwsCPxEjzweeFyfDA5PJNDKLVBKykJA/EjE6NABYZjBYQaVV5EkTuDNMwM80vSZg6jd1QNXQTR/8AESRXNPvQzLfaqNsTRtVV7VRbW4b9cxro/r8tm4yJaSxC1NhQXDq9AQWtyKLRyOCxZpmurmlFxYvpmZxM2exKixY3N0Li5s5i1/UCxYhtV5MwSK8GThbE+mFRSkN4V0DINSVwYwAhhaET1kQ6i/FszeLxJPmgSwHWBlAmwlAQSLkWc/g+dDw+5A+L0zgSbAaUFtnobYAUIvcTkatA1DLHFkyQxsVnFk2wQkPEpytjnGGcCVw9heLs0hqznD47jkPZ+WwSx2xnHcb195eL8ru4TjCknPenhhnh2qgGgNnpChNWXKEpG3ErahOyohq14iHfF+StIKAvXDQC5I0rgDQktkElVSRb3v9HCsECQiL5i1IapDDoLoCVH6YAawhWe83UbbpAlXfa6LamhPUsxfKa3NrAlm5krJfVZoxk42smPpLIGxMxaSZpZDJMlzvImHbY4TFVdUmTliNRVhTasKaEghr6oWwpgTC4EqstoI3dkBOVV0MscsN+Hr6JE5oihbUDTU9Cqq9SB6Xpiw5QtLPHlP6MFmlum0YrSTf41xR5MqDIBm8Gppe3YCaCFmLV0NMXQYvkDpmrvMky7m7k7K9nVQ9eSQxSaUpehjiQVO0Fjr8PmNKE/XlX+MbfIAIq5AFETbcWWxOQ4piBw2SgCgDJol6F+2rkupdFmsHjrDCJZY8653drZXMFtf17Kquhnt0VRcOC4ag2o0jaYaSIiT9aJLyC+enNvapbYAY6srXZA8ZoVp60mbpTWppTHnMd6w70VHZOnekGi8kxSSqSAdjp6/7QJd6EUyEElsvE6UoaFPAEs6janQeqNHFu1KqUU7nRqDTOTpYMR1asacBTUVYH3FoJmnPT5L6sH/n4VvuiGY26xJoissYnUKEXo70RufH22k3o9iFCUYd7PM6qr7tsk7ecsH4MlgxByDNHgaYFsuzUDilWU2KkHSL

**Comment by jimmyt857** [comment]
Thanks for the report! The raid sim is not yet functional yet though, so bugs are expected.

**Comment by Sulous** [comment]
I just sent it on the off chance it helps in some way with development lol.
Thank you all for the hard work and great sim, though!
