### ISSUE TITLE
Crash Report -261555461

### ISSUE THREAD

**Issue by Sulous** [wowsims/wotlk#1703]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmn9wE8cVx29XJ+t82PHGpXBoML2olKieauZ0F81Apq1kQjNO0864MGmcTn/ggAE3xk4FJKC/HCAlmPxqEyiQpnZJ2oamDQ0wHtuSbX4lxAHzwwYToBBKMXHK75BMGdqEvrd7siRLJp40SaeDnn3S3u7enn989N77vj319A/V3i+oV+XFJK8sXDtfL6uorphZVaM4mexuJWoBe7SNav8o8uRs3k4bGqgqs+1Rquaxx6D78XEeR+81qrrYkSjVVo6F2Uug+wrMhqm9zVRV2YEmqtWP8xBJzWdLYfDZcR75jWYqwdy9MPSLsZ4cOIVvWOUJGD9fBIv/DkZWjfU41rTgDZ9sx9eXW/C2DW9RvrgYObUOL1sDN99dBI190Fg+DvqXtFOPoshGfpmj3FH8NJWylmIR6U1SrHrcukqVHDgUOHLhoHA44HDBQeBwFkpuqjnqiddnBAwj4LcCpmH4LdPy+y0wv2mZfl8ATgzT8MOQdZJoyrFeyh7fSrVX+6je302973RTo6+b9hP5InGtJbk3z+LWG2wm5AiAIanLnYDfnQvCi/R7K8Lhqtow4JfrbkL8Th+i2rsA1Gvb6J4uquayK3+lHkesGWHojlHtRJHH0cfp6REM5rGjMc6g4zedFKA7CCw9CtDFEDqVHYPBZ8cij7nsiVYqZhWw/dB9AW4Ds3r5ak+1IYIw6fAhe5LMnuAgntmLr1tacdYWuGdXUaIhs61RRI8aOYCenEUvzSJS+G41+DQhOikRPd8M3cXf60pC3xM994XuE41JoTnkQbKQ1BHyGCG/JaL3thBgmcNgBY3Wk1st4M60AD/L8lmAacAyAFXTsPzwBogiuVbAj2S+1EPZ2h6qre6h+pIe6l3aQ41HewbIlJDGfnSFJeG581JY3IAs7osJFpu20/WdQ7B4OjOL6zmL9VHB4rYhWFzPWfyoVbAIrvV0BhbhYuBsbWwIFqUshB9rAKGhjmcEMLQhvMuG0Hgomb2FJJk0L3g5wMoE2iwAChwh93om94dmwI/0+WACd4INgNrzNmrLALXYtXTUjgJquXdUzNenhBdUzVTgRoKzNQnOEK4Uzl6xOYtl5gy7P97n4awCduZQwuddw7U3tYqwuyeJsHSftyPBWVcTRGPgjJRlKUu3iLSRTFA1hTKiOXXiJd+QJL0k5Cwd9yNJml4CaGHczWczNVJPvuoLcLQQJqAs7rvAsYEfgwgLYAVgBvCGdL3eQdmLp6j2WgfV1x6k3p0QYrd3p9BVKKndmroTvdkdtXPvB8qm1s5eUAneLMf9KlK2KUFZUmTt4JQ12ZR1ZKasI4WyjiEo60ihDM7Eait5cgf01LckMDvbhq/HDuOEjnhQXdc0KKg6y+TpWdLSLSL9YIw6gskaNRwTaR35us0WZRTZ8iJMJo+Kls8wITaC9+JREV2YyQOlgR7sJMlTtvVRtrOPaof3pjqrLEk3gn0eJD0H2f6IqZWpWvMvyck+gIQRyQYJk+88trgtQ+CDZEmAlAOTROyL51hpsS+P9QJLGO1Sw5995UCaJbMVLYMzrAvRQRnWqT2CI4h800mWozSLSN+erf5Eed/B3neMEV39QV32ksmarS0dtvaktt6Up37NHon3ynbblam/lJSTuDodj1m/4QeN6kMwEUpMwyyUpaBTAUtox5XpUlCmK7ZmVKaczheATuXOcO08SMvuBjRVUQZJQjNNh55Ly8n+WYSXXBfNfNYv0BSnCTqFID0bG4rOdzfRAUYxIxOMutiHLVT7o9tuvOSG

**Comment by jimmyt857** [comment]
Thanks for the report! The raid sim is not yet functional yet though, so bugs are expected.
