### ISSUE TITLE
Crash Report 27870284

### ISSUE THREAD

**Issue by Icemad88** [wowsims/wotlk#1713]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj0sQ1EUfuf0pW6fn1xleBoDnUQiuX0vL2HqY+pgaGIxVkQng9iYpDFZWLEYLRIREWmrRIhUNKhEk1a1iqSTn4jExrl9DDYDm2/4cn7u992bc67WzrAXQrACBy2rAOuAewBnAGXAKsCAxkCHLrBhGLwowHehxsAdHh+ZGptkwF2+LdA4LydQz1yj3324j6lt1Dz89Qr9rjyFjfyWmsfUdL3UOve5zw7nlRzq6QLJSCNlTbxKlSxVVEoVTeOlxFfs4c9JEqZqwhuyjB06Qumq8oek5PmU5NOE5J0Nybtx1Bg/ofNHBZmfxyXHNtHPGIj6sBqB7gVU/vEN027aLU7AgJeGp9oNIXcYvYpPZaiPzkG3YQohrIBpBoQwTRGwhGlQbFjCMo0eYfYIg8p0KFABnS2XkD9mUH/PYMddFrvKWRRv1/S51CeoWwIlD4q/iJ7axTNRu9l5QqvdtrQokQ72OZWzYGe0hsugsYYdQzr7883N2r/hMpM++BWfn8CZ1WDR7nfyt2AIIvABIuZ6ow==

RNG Seed: 2341009819

No enchant with id: 44877
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xb97a0, 0x6711870})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core/items.NewItem({0x9de0, 0xaf4d, {0x4bfe430, 0x2, 0x2}})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:269 +0x22
github.com/wowsims/wotlk/sim/core/items.NewEquipmentSet({{0x9de0, 0xaf4d, {0x4bfe430, 0x2, 0x2}}, {0xae75, 0x0, {0x4bfe438, 0x1, 0x2}}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:298 +0x5
github.com/wowsims/wotlk/sim/core/items.ProtoToEquipment(0x6768e80)
	/home/runner/work/wotlk/wotlk/sim/core/items/items.go:305 +0x9
github.com/wowsims/wotlk/sim/core.NewCharacter(0x67c00e0, 0x0, 0x6775980)

**Comment by jimmyt857** [comment]
Thanks for the report; this is probably caused by loading a newer version of the wasm binary file without updating the website. Try refreshing your page!
