### ISSUE TITLE
Option to remove Epic gems from the Itempool

### ISSUE THREAD

**Issue by Jungleonly1740** [wowsims/wotlk#1715]
**Is your feature request related to a problem? Please describe.**
When Using the Gem Optimization function it always picks epic gems which are not available in phase 1, turning off epic gems from the selection would be great

**Describe the solution you'd like**
Turning off Epic gems in the sim with a checkbox

**Describe alternatives you've considered**
Not really sure if there is an alternative

**Additional context**

**Comment by lologarithm** [comment]
Fixed gem phases https://github.com/wowsims/wotlk/pull/1771
