### ISSUE TITLE
Crash Report -963344480

### ISSUE THREAD

**Issue by jongoad** [wowsims/wotlk#1717]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YJzAyLiA8YjwBkamA4yMFxgZHzAyvWBkdOKQYNRgDGCMYBRikPrD0sTIFpCTWJlaxMEpwCx1m5GLX+DiBGaJN7JKbEcPMR3dycTFKfCom1mJ+SaQySNwBSj3SBbG276KWaILyLsB5PELXAbK/QDqA/JA+ngFtgGl5wgpsQAFGIDcC0D5KTJKLEdBXH6BrUBTOYHsm2DEJSTQ1sMs0S6rxAnRfxNsZjdQbJoM0C07mW6A3fIC5BaIs+51Qp3FIrCmkxlIrgSSnAJrepghLmIRmN8DEvgDdb4SNwejAXcAawJjByOj1gQmhlGAAqrYOBgFmAoYnYS4OIAsFgceDzZgGmHhYJJI7mLUNjI2MDAwNTA2NATSxrpANpBjYGBoaGxgZGxsaGBqbGhkYGxkaGxq+IhRguPzWSaB/2eZJFY+ZVJ4colJ48ElJoMf94ApkOUDI/csRoZbjAxKT5g4IVbHOUjOmgkCJ+0tISIX7BXTwOCavdFepoI5tVU8AYklyRnlqUXZCkamCsESHLSOwg+NDtQwpuHkEUrMMbDQKnAkVjE48BqmPXKA6nhhD0zqAPyFizY=

RNG Seed: 591048967

Trying to set non-zero stacks on inactive aura!
Stack Trace:
goroutine 31 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:56 +0x10
panic({0xb9b20, 0x2f4040})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).SetStacks(0x6d53a20, 0x6dbd170, 0x1)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:173 +0x3f
github.com/wowsims/wotlk/sim/core.(*Aura).AddStack(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:200
github.com/wowsims/wotlk/sim/common/wotlk.init.5.func9.1.1.2(0x6dbd170)
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/other_effects.go:348 +0x9
github.com/wowsims/wotlk/sim/core.NewPeriodicAction.func1(0x6dbd170)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:73 +0x6
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report; this is probably caused by loading a newer version of the wasm binary file without updating the website. Try refreshing your page!
