### ISSUE TITLE
Missing item: Nyn'jah's Tabi Boots

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#1721]
[Item 33222: Nyn'jah's Tabi Boots](https://www.wowhead.com/wotlk/item=33222/nynjahs-tabi-boots)

**Comment by lologarithm** [comment]
This is a very old item with no special set bonuses or actives... could you just work around by manually adding stats to represent these boots?

**Comment by jdelvare** [comment]
This is indeed an old item, but players coming from Burning Crusade (like me) could still be wearing them up to level 80 as there isn't much better to be found during WotLK leveling.
You are correct that I can work around the problem by manually adding stats, however this is definitely not as convenient, and this could get the metagem activation check wrong.

**Comment by jimmyt857** [comment]
Unfortunately we need to keep the item list trimmed to preserve website load times, and so we have an ilvl threshold. This item is very easily replaced (there are plenty of options from regular dungeons, or even pre-80 dungeons / quests) so the load time concern is considered higher priority. Sorry!
