### ISSUE TITLE
Crash Report -281832889

### ISSUE THREAD

**Issue by jpaardekooper** [wowsims/wotlk#1723]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztU0FIFFEYnu9vXd6Oyr5dOrxkjW0wEkF4M9OAnXbs1HEhgj0moQR2GCQohWDyYnkIhRAS6RTRMYOELcKopLyEGZR6SF0h9lAwUKR0qX9m10O3oLr18fhnvu/733f433vmUUGSNPXBp1OoIKAQmALug54CK0AdeEU4mRMokoaPctyEe0De6JhuGUe6fGFgdHBECImONzCz8uEeqU+dVnrpGa1VyczI27tkHZjn3zb5gL1a5z57tE1qklnclpV32dvjfewtsdAua19IzeWtFAsG0wX2bxaaNC+r30hNF6wM08cfaT6JeBuRmuCItUZEVm7vkJopWOlmR0pGW3GtJvX1TlIj4rQ7u6RuHE7SGss02Fv4SpYU0CinKi2XwZO5BvRMkfEfv2BMCEhSFMDpMuObgm4e2hnDCPorOBvflHazVfzYByZxzLNdR2vXtj3XtV3tOjZ/Peas9fY62mNT204NSoSbJN8vklpfpOL3D9T9fJX0y1WqIxWhdRbG9eZ5HPc3YFifKZOwcMjPNfSD/qHZWzGWSycaykrpyFCCdyXnCQVzV8baygMXz52/NDgyXHS84mkl/vUpR1f9vxETLr/4kxzd1xP0/25zMrxwpuY3d9RL/Bp+AuCjmXc=

RNG Seed: 761830589

SpellSchool for spell {ItemID: 47182} not set
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xb9b60, 0x324be10})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterSpell(0x89f3000, {{0x0, 0xb84e, 0x0, 0x0}, 0x0, 0x2, 0x0, 0x0, 0x0, ...})
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:190 +0x147
github.com/wowsims/wotlk/sim/common/wotlk.newCapacitorDamageEffect.func1({0x2f9390, 0x7ae0f00})
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/capacitors.go:46 +0xe
github.com/wowsims/wotlk/sim/core.(*Character).applyItemEffects(0x89f3000, {0x2f9390, 0x7ae0f00})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:171 +0xb

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/1726
