### ISSUE TITLE
Missing items: Drape of Icy Intent

### ISSUE THREAD

**Issue by mrt0mat0** [wowsims/wotlk#1728]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=45461/drape-of-icy-intent

**Comment by lologarithm** [comment]
wowhead shows its in phase 5 -- im sure this is incorrect but we won't fix it until wowhead does.
