### ISSUE TITLE
Weapon swapping

### ISSUE THREAD

**Issue by Rarius92** [wowsims/wotlk#1731]
For Unholy DK's getting the best possible gargoyle snapshot is huge, thus we use several weapons with different enchants to try to proc more buffs at the same time.

Example:
Black magic on my OH weapon, Black magic only procs of spell casts and has a very high proc chance (i estimate 33%) so on most pulls i have the black magic buff op even before i get in mele range. Once it procs, i press a macro to equip another weapon with another enchant (Berserking or Fallen Crusader)

Because I can not sim with weapon swapping it can be hard to realisticly test how big a weapon upgrade is.
(I have to sim Fallen crusader MH and black magic OH, but as seen it my example thats not realistic)

**Comment by lologarithm** [comment]
duplicate of https://github.com/wowsims/wotlk/issues/1731 closing this one so we dont have multiple of the same bug to track.
