### ISSUE TITLE
Hunter sim safari

### ISSUE THREAD

**Issue by Dopimine** [wowsims/wotlk#1736]
recently when I use safari to do sim and try to change gear it doesnt pop up in window anymore it pops up in one column that u can not scroll so you cant make any adjustments to ur gear

**Comment by Dopimine** [comment]
![Image 11-18-22 at 2 00 AM](https://user-images.githubusercontent.com/118423144/202641344-e056f941-7c46-4d4a-98db-14169b598e74.jpg)
![Image 11-18-22 at 2 00 AM](https://user-images.githubusercontent.com/118423144/202641372-5deb8abc-df5a-4075-a21c-2445dec53aa6.jpg)
One is safari one is firefox the fire fox is way it used to be on safari. The safari broswer makes the sim unusable

**Comment by Dopimine** [comment]
@jimmyt857

**Comment by Dopimine** [comment]
It was posted this morningJosh ***@***.*** from my iPhoneThis email, and any files transmitted with it, are confidential and intended for use by the addressee only. The confidential nature of the information contained in the email and/or file attachment is not waived, lost or destroyed if it is sent to other than the addressee. Use or dissemination of the information contained in the email and/or file attachment, by a recipient other than the addressee, may cause commercial damage to both/either the sender and/or addressee. If you are not the addressee of this email/file attachment contact the sender immediately and delete this email/file attachment.On Nov 17, 2022, at 20:38, James Tanner ***@***.***> wrote:﻿
Could you include a screenshot for this?

**Comment by jimmyt857** [comment]
Ok, I think this is related to a small change I made the other day to use <table> tags instead of <div> tags. I'll change it back tomorrow.
