### ISSUE TITLE
execute phases not respecting variance in sim length

### ISSUE THREAD

**Issue by spectrawl** [wowsims/wotlk#1745]
First noticed this looking through affliction warlock execute timelines and seeing some iterations have a much shorter execute than others. I thought it was just a timeline bug but further investigation shows that on, for example, a 90+-60 second fight the execute % is calculated only based on the initial 90 second timer, causing some iterations to have very short or non existent execute phases and others to have very extended executes.

Example: affliction warlock iteration of a 90+-60 sim where execute should start at 54 seconds (72 x 0.75 = 54) but instead starts at ~68 seconds (90 x 0.75 = 67.5)
![image](https://user-images.githubusercontent.com/118485391/202563745-273faaed-28d1-4f9f-92a5-e7356cccdf82.png)

**Comment by TheSorm** [comment]
https://github.com/wowsims/wotlk/blob/master/sim/core/target.go#L31
The error happens here when the executePhase20Begins, executePhase25Begins, executePhase35Begins are set based on the duration on the target fight level.
It should be set on the effective duration on the single sim level.

The same function is also responsible for not allowing 0% execution time. 
If the execution time is set to 0 it will be reset to whatever is the default.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1746
