### ISSUE TITLE
Improved Faerie Fire not affecting hit

### ISSUE THREAD

**Issue by Kwxpala** [wowsims/wotlk#1755]
**Describe the bug**
Hello. I am simming prot pala weapon enchants and I noticed that improved faerie fire does not affect hit. I have 5% hit with 8% cap which should be covered by improved faerie fire. Unfortunately I still miss 3% of time.

**To Reproduce**
1. Go to 'sim tool'
2. Click on 'sim'
3. Scroll down to 'detailed results'
4. See error missing with 5% melee hit despite having faerie fire toggled

**Expected behavior**
With 5% melee hit and 3% from improved faerie fire I wouldn't miss instead of 3% reported miss

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/118537690/202708975-2a77e61a-40b4-420f-b559-822279a4cbe8.png)
![image](https://user-images.githubusercontent.com/118537690/202709006-5bcd563b-c038-4229-89ac-43c4c88b2aaa.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Teebown** [comment]
Improved faerie fire only provides spell hit in wotlk.
