### ISSUE TITLE
Plush Sash of Guzbah

### ISSUE THREAD

**Issue by sskel232** [wowsims/wotlk#1757]
[Plush Sash of Guzbah](https://wowhead.com/wotlk/item=40696) has 1 socket not 2 as sim is showing

**Comment by sskel232** [comment]
![image](https://user-images.githubusercontent.com/5025180/202764338-deed1753-4105-41c2-a252-2d6906ce3649.png)

**Comment by PANDAxBEARS** [comment]
You can add a socket with Eternal Belt Buckle https://www.wowhead.com/wotlk/item=41611/eternal-belt-buckle

**Comment by sskel232** [comment]
ahh my bad, thanks!
