### ISSUE TITLE
DK sim freezes when using Imp UH Pres & setting Unholy for the fight presence

### ISSUE THREAD

**Issue by je-c** [wowsims/wotlk#1759]
**Describe the bug**
Death Knight DPS sim iteration freezes when using _Improved Unholy Presence_ talent and "Fight Presence = Unholy" setting.

**To Reproduce**
1. Use any Unholy build that includes _Improved Unholy Presence_
2. Go to Settings and change "Fight Presence" from Blood to Unholy
3. Start sim
4. See iteration counter stop incrementing.

**Expected behavior**
Expected the simulation to complete as normal

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 107.0.5304.107

**Additional context**
Does not occur for Unholy fight presence without _Improved Unholy Presence_ talented. Also does not occur for Blood fight presence **with** _Improved Unholy Presence talented_

**Comment by lologarithm** [comment]
Could you link a sim where this is happening? I have been running MANY sims using IUP and unholy for fight presence without any issues so far

**Comment by je-c** [comment]
Just ran this and it froze on 495/3000

https://wowsims.github.io/wotlk/deathknight/#eJzjUuJgEmAyYMpgLGBsYGRcwci4gZHxACPjBUbGF4yMPxiZLjAxOQkoMBkwOjBGANV0gNUIMUh9Y2liZAvISaxMLeJgFOCS2szIxS+w6jCTxEtZJbZth5nOnWXiYhGYuoSJi0fg7R4miQeySsw3DjNxsQv0L2OSuM4OVH1wK5PEFkklNqAwSIZLYMd+Jon5kkqMDFy8Ai+AetawKrEAZRiARuxaxARXyC/wBij5HmjPvJNQgUm3mCQ+ycJVsAg8/A8im0+CyDd7QeS78yDLNwJ1rpDiYgAKrN7PpMTPwWTAa8EYwBLBUgHym9YEJoZRgAKqWDgYJZh+Mepw8XEwSQCTQQAoBewAJwIJQYiaD/YKjFrcHP9hgLGLUVfX2MjAwBQIgcBI18gYSBoYGwO5xkaGYEEgCRQxNDY2NDV8xCjBMfcKk8Cbp0wSs64wKcy4wqQx4yqTwcyrTC8YWT4wss9iZLjFyDCLiUHpLhMn2M6GNAeo7SIOkrNmgsBJe0uIyAV7xTQwuGZvtJZJIViCg+YR2+JADVMaTh6hijnEAEhY+dx1cITwf9h7MCYwAgDi2oXv

**Comment by lologarithm** [comment]
fixed https://github.com/wowsims/wotlk/pull/1991
