### ISSUE TITLE
Gems not filted by phase/profession

### ISSUE THREAD

**Issue by mmolignano** [wowsims/wotlk#1769]
The gem menu is not properly filtered by either phase selected nor profession set in settings.

Even if phase 1 is selected, epic gems exist in the available gem menu (which aren't available until phase 3).

Even if non-JC professions are selected, JC-only gems are listed as available in the gem menu.

**Comment by lologarithm** [comment]
phases on gem updated: https://github.com/wowsims/wotlk/pull/1771
JC gems do show up in the gem selector without JC being selected still

**Comment by jimmyt857** [comment]
Fixed now.
