### ISSUE TITLE
Crash Report 934797975

### ISSUE THREAD

**Issue by EsreverWoW** [wowsims/wotlk#178]
Aura Rune of Razorice already registered!
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:45 +0x10
panic({0x8ba40, 0x8262270})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*auraTracker).registerAura(0x825a400, 0x825a000, {{0x17a100, 0x10}, {0x0, 0x0}, {0xd05f, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:276 +0x3d
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:301
github.com/wowsims/wotlk/sim/common/wotlk.init.2.func15({0x27aee0, 0x825a000})
	/home/runner/work/wotlk/wotlk/sim/common/wotlk/enchant_effects.go:396 +0x27
github.com/wowsims/wotlk/sim/core.(*Character).applyItemEffects(0x825a000, {0x27aee0, 0x825a000})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:199 +0x12
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x825a000, {0x27aee0, 0x825a000}, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:163 +0x24
github.com/wowsims/wotlk/sim/core.(*Raid).applyCharacterEffects(0x2119e60, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, 0x0}, {0x822a100, ...}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:220 +0x48
github.com/wowsims/wotlk/sim/core.(*Environment).initialize(0x823b5f0, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, 0x0}, {0x822a100, ...}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:101 +0x14
github.com/wowsims/wotlk/sim/core.NewEnvironment({{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, 0x0}, {0x822a100, 0x5, ...}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:40 +0x4
github.com/wowsims/wotlk/sim/core.ComputeStats(...)
	/home/runner/work/wotlk/wotlk/sim/core/api.go:38
main.computeStats({{}, 0x0, 0x0}, {0x200e020, 0x1, 0x1})
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:64 +0x13
syscall/js.handleEvent()
	/opt/hostedtoolcache/go/1.18.3/x64/src/syscall/js/func.go:94 +0x26

Request:
eJztkr9rFEEcxfe97+5mM3jHeIgMqY4r5AgIc7sspNMif4CdtYVgYSFW0SrYqBHMgYWnATm7gxA4EMIlJnBi4Vmd4MVgEBXBY0MSuDIIUWfzA6zF0u/Am3l83vdVo36GaiFUD8M7CC9dv3Lr6s1oTKuJV1BaDzdp+p9ZCZdf80OHalzvf2JFnr2lKui9NZo3DsqaI5F+/5Jma0nyLQf6Lhe6XB4t6jnHeh+l4ruo53zmEptLJ35cH6we12i969Bw0S07u31YPL9Ok7liX2+/oNMHK7nurue6088TBys0X5ryx8vX866y2CZ7LLTIGX8W/mSP3v/5J3Pbj2D4A5eVV5qOqKUcXAwyyAi8x6BOaTBoUdoMOmSXfEf5SmTkiFIXaYg0BW1BR6QrQU8wUTh91Dy6YFDFHM7FiU2tten5JHaapDZJ49gmtuaAtUlSs7UkrX2DiRYG1I8HNHvfWW4MWG1s0D7ZYAZ/hLGniFWo/Oj5XR7ew0X3RVUxun+2/OtkkBP9aPUosb/DLXjq+JQ8dUr9lSudqXIKNziDJtACukAGTGqDMiymcA2zQB34DbIgjRE=

**Comment by jimmyt857** [comment]
@JooperGH FYI. DK sim is still being developed though so errors are expected.

**Comment by jimmyt857** [comment]
Going to just close this because there's been tons of development lately.
