### ISSUE TITLE
Crash Report 139692096

### ISSUE THREAD

**Issue by BocaDaddy** [wowsims/wotlk#1786]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUjFoFEEU3fdv3cytJzc5QdYjC+tWISLM7nCQNN6aynLBxko8YkTQIgRBDAROGzWNASXgkSKlljYh3GkUiWDAYEyhEESP08AVBlZECDb6d+8aO0Ht/MWf/96b/2aYP7YnaBTzwBLWDt4HVoCnwCbQBnWBF4RxW8CjYcQ4jRIplBPzOqz4Uu3q5LTIy1z5IeyibLfI+ez61vNntLpCdl5+e0d+bpvLgvzIWsf1c18ytPOWnDm3pxVlh7U97uOmhIkDssvyYsk3mTAYfmD97lAf5uVuk13TAwZk8oicGy4Xy01yFoZsU75qEefbq2l+0kxz0kp3vmSP7y7D1xm5tEy+JaAQ7xuZJ+N//BIzAwISdWD8kM2Tl2ZUOGnFVDLKliAJpzaHo6FWSlWUDgJe9TGuGSgVBFqFWgeqooNQ6TDQlaADR3zdIPljg5wHO+R92qLh9hapvff8vcwE+xsYtIt2Ttw5UxK9G5yLbvWncjzahtEgw9+lfEacnYgGe9JYdLhxL4316liP2aweOZ/Fm2r4mKYWZ2cKce3yxIUrk9MXvbDinXLEvx53ci36Gzb19bU/8VGjI1Mnfndz9nj1hU7U7+hWbwI/AdqFg/8=

RNG Seed: 1738874739

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cc26e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cc26e0, 0x1d70000, 0x1dfca00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1dfca00, 0x1cc26e0, 0x1d70000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cc26e0

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
