### ISSUE TITLE
Balance druid simulate dps bug

### ISSUE THREAD

**Issue by Marcbariller** [wowsims/wotlk#1787]
**Describe the bug**
When I simulate balance druid dps I got an error "Simulation failure: runtime error: invalid memory address or nil pointer dereference 

**To Reproduce**
1. Go to balance druid
2. Click on Simulate
3. See error

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - windows
 - chrome

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
