### ISSUE TITLE
Crash Report -1891757257

### ISSUE THREAD

**Issue by wzh1986** [wowsims/wotlk#1788]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUjtIA0EQvZkcyeYUXKPFGiLEqyQQ2NwR0CqnVQqLgI2lIqayEDutRETBykIEo4WljaDxC4KIaGGhhhQqATUxAS0EDTbpdO6iop1F7HzFMPPmzdthd7UAww6IwwocN60CrAMeAmQA8oCPAN0aAwHtYEEf+FCCv6JOgjsxPDA2NMqAu/zXoDXwjUcUT626++QID/ZQ8/L9AuouO63nO9S7b9Vdr06VLqGYpSpHVQNPU69Cc6Q8cIjpIopl3xfBeYH08wHdQ3oyUEiyWULdW97D8ufMNpnMfDe5yKNYCDhEztnm9oG2KTvpbvFjMZWfF+2YLtr0VumLvirYcWUHdcZA1iXUfgjNofKPHxh30+vjCHT7NMZVqz7uTqBP8asMxeAshAxTShmNmGZEStOUkag0DcqNqIyaRliaYWkQTaLIPQi2dIf8+QzF2xkGS1lsz2dRVm7p+6kv4EmBkgMlhYp+g17n7Imk1VjdotlqSS3aOI11VplMrC3p4DJmrGGwV7A/f7wpqxYuE6fHNfH5Dap31XNjdVXrSiwO/fAOpEOH0w==

RNG Seed: 3285418115

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cb11e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cb11e0, 0x17c8a00, 0x144b400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x144b400, 0x1cb11e0, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cb11e0, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
