### ISSUE TITLE
Crash Report 2119585953

### ISSUE THREAD

**Issue by Norrev** [wowsims/wotlk#1789]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUT1LHFEUnXMzrs+Jsk9J8RRH1mkSBOHNDAta7WhlYbFgs6UpIhYpJFVMNYmCmCKYQIQs/gAbJRCFxfULPxA72UKJuApJERELYwqXNObOjinSWZjOUzzOx7unuNdKCZKkqQt9yGGEQmAK+AxaB/aAU6C3USBFGgGy0Q/MAk1Gy5n5Bons86ejz16IhETLAqyk/HFA6tx2Etsb9LNAVp28PCLnwSHTejm9TKpkx6pWFpdIXdk88pHtCo+sFihKGuRYkdR0k2OyYbD8wPl8841MysoKqfetTuJXgVarRRecT9hMdphcRqT8hVTYxuT7dZWY8myF+F0sRv9nuP5dm2Ww8bpIjiWgkTVzNS/RMUXGPf7BKyEgSdEIPNviVSlkkzkMR/dvsB6K67/AWzxOa9/T2nfdtO+7PgvX93Watee7nZ2eTnOoXe8blAhPSB6skfq6Rqnfx/Rks0R6p0SnMC9Qm4cxeXMILziEkSfDKVNd1QiHgsY4ehQ05z9F2M10x85epn2oiv2MN0epASX++0HHg7toCXe37qTnNoh31V8OemJdyfRhEH8AAat/4g==

RNG Seed: 4004017214

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 24 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1d41e40)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1d41e40)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1d41e40)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1d41e40)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
