### ISSUE TITLE
Crash Report 114344915

### ISSUE THREAD

**Issue by Bassjunkie23** [wowsims/wotlk#1790]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjtIHFEUnXNd9TkqPiXFUxhYp5KA8GaGBa12ksrCYiFFtkwKxcJCrKLV+AHRalFU3EqskiJGkhT+dg2JAe1EyEdRA1YiFiEhstjofa6BQEAstPMUB86955zivmfHBUnS1II2pNFDEZABFkAfgC3gCHhcKxAnjRAp48BLoM5qmCkdRFmq+3lfR68QEg3vYNfIiVVSJ45b9vkj5RfJrpB/9sgtmV0iu0pO8e7AcUvMolxO5EmNORyZ5HGBIwvT9Ip91XJohdS848Z+L5LFcpz38/VuLG+kkIUcuWRZHDx7T2qEg+wzwXL5hit/OXZMZvLEvDFn+DhnOPfWGL5z86kxRMtmOLBCri2gkYqlS1/gYYZ77/Ev+oWAJEU98B2bT6WQqkmjyzx/tV0pzv8CY3ia0IGvdeD5iYCJhRcEOhF4nh94zfpaNPs6wVHNsf9wCCWiHyR31kh9W6P4p21qyn4hvb5NRxA/UZmFNXr1cH64CytLlrtPFZeDqDOsLa4ehPXZGYPNZGtxspVs7LzE16T/muJPlLjzDzAc3kZLtLl+Kz03QfFW7fvho6IuJNvwDBf4j4Xd

RNG Seed: 278932349

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 21 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cd73f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1cd73f0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1cd73f0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1cd73f0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
