### ISSUE TITLE
Crash Report 1775122310

### ISSUE THREAD

**Issue by Malonarasoli** [wowsims/wotlk#1791]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUb9LHFEQ3m9uc3m+i/gUi6fcwuU1SkB4u8uBqW61srA4sLnSFBGLFJIuVpuQYHKNJhHBwz/AJmCIhXj+wh+IhSAWCZFowOoICVwSCCEpzHu3prBLYTq/YpiZb75vYIbnGAnS1IsBlDBGMTAFLIA2gAOgBvS3MuRII0LRTmAeaHM6a+4jpIv37jy4e58xgc7X4C3i5QrJz55K72zS2hLxJvHtA6nUkUlviBnDnXoqZYnrorxDsuwZye9FkosdKv19iewcF0+qJOfaFBzeLF4YzXRWuUbjGIsvyySfZ1Xqa8OibsgJzyS7JpnJcldMrtmd0/uUbHFFvWrjp1U7fvaG5A/PlPGybT6sksowaBTd0rWnwK0pcq5wAeOMQZCkMQQe5wwSxZYSRu33m3mGnf0FyujK6zDQOvSDfGiCKfww1PnQ94PQ7+kJdN6Q2g9OIVn8kcS7dZLv1yn364S6tw5J7x5SDW4dmQqcZ+ePCKIjOBVy1DE1NRrxSNSaUO1RR2XWYq9wO+kcFG6ONPC2ELyi3JBk//2hj6PLcIn3ti/F51+Q3GrwOOpL6p+FAQzjD1p7fUA=

RNG Seed: 2377436834

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x14e8840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x14e8840)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x14e8840)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x14e8840)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
