### ISSUE TITLE
Crash Report 2022300594

### ISSUE THREAD

**Issue by numbbane** [wowsims/wotlk#1792]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUU1IVFEUft9xHO9cpXcdIq4DA6+3KQThvvd4YKuZWrkccDPLRBShFoMEohA8wkhdDfgDDe5zIeImK80fKhF34sLIomBWg7QoVzIbPW+mkHZBtetbHM75vvMdzr1HOoIUGepFH4ooUQSUgVXQDnAA1IA7toBDBoVYxxKQ5uZMLfEIycL9gfGhUZFUyKxA2mr2NemvWTe5+4a2XpJMqdNP5LYcc9qhFlirZt2WWGhTG+ukZ7JsmWf6jC1Mf2RFqscbpBfTLizOn6+RXumK85R6sUZNs63m2PPk0tOmlnnaaVYmVPkVcVxuxO/P4niyGTcssaMeN9Q3Y3Jqi1whwG9qLSa6y2T9xy+YaBdQpPncq4CvpRLQcNBnF+wi7mIEaStD0prBjdAEvjGB54VB4AVceEFgQq79wOvp8U3IovH8KrSIvpB6v036wzY59c908+0hmb1DqqH9G1orSEslr4jpa875T+AYVoUs94RSja2i4Xxnc7+r+a7K0xj7uVtN5iB3fbiBo5y/TqXFhxMdhYEHgyNjQ6P3HD90+rX453eezP+NKdH+uz+ZY3q7S7d/t7nxedFCNf/DUctdAJ19hNw=

RNG Seed: 2682124188

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x15f0000)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x15f0000)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x15f0000)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x15f0000)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
