### ISSUE TITLE
Crash Report 144079836

### ISSUE THREAD

**Issue by rynoman14** [wowsims/wotlk#1794]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj1IW1EUft/J43l7tXiNHW5DFH2TCMLNewR0yqtTBoeAi6NFdHIQt3YKRRA72GJLodHB0cVS2iVVDEXsEIookTpI/IsODtJWXLLZ814mNwfd+g2Xc77zne9c7rkyKagfWSxjq30F+Az6DuwCJ6ALYFAKaPQgwAjiZJDYs1/ByU0+fzE+LaBiia+QrermC+nLDtf5sUmlIklb5b+RbFFn66RrHW7sirkm9Yuzd52srnFQZ/VyOVJLtcDEUtyFJR+rY47fJ137oEgWW+ysketwHApb1SkXZ7mTs+vI81OJ9IckD5zbCMe+KYXn751w+OJP7qwWqRoJL9dIz3dKi8tVthQCpjlnj6L3LVn/cQsvHV4sTWEwLoWyg5ask6O4lbAF6bHX6PV8Y0w65fspY3zfpNLG9zj20ibte33G7zMe0yxK1aDF4jGpP9ukb7ap67xCPScVMvUj/ln2XzQVYB3AKpDlHtKjaHZ+Imhr3OJJ8LTwMUQ5M9BgdjPdExH2M94qdQ1r8eDLmwnuwyVf3roXn7ug8VZDh8GzRl7PZDGKf/p5dlw=

RNG Seed: 4083298890

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca53f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca53f0, 0x14ca000, 0x14dc400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x14dc400, 0x1ca53f0, 0x14ca000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca53f0, 0x14ca000)
	/home/runner/work/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859

**Comment by rynoman14** [comment]
Thank you
________________________________
