### ISSUE TITLE
Crash Report -1267098844

### ISSUE THREAD

**Issue by CreamyDreamssss** [wowsims/wotlk#1795]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJT6z9LEyBaQk1iZWsTBJcAstZGRi1/gwW4miTeySmxHDzHt28HExSnw6Q6TEvMtIJNH4DFQ7pGsEvP8nUxc7AJdR5kkumSBWh4BhbdIKrEB1X8GquMSuLKJSWKOkBIjAxevwPEtTBJTZJRYzu1gYgCa9nYX0DSQwfwCD4HaFsiBtX3cATLw3R4miWkyXCwCj/8zAcn+fSDy43IQ+WovSMEZoI5fskDur70gwQXbmJQ4OBgNuANYEhi1JjAxjAIUUMXGwSjAVMDoJMTFIcDiwOPBFsAkxCDFwsEkkdzFGGFkbGBgYGpgbGgIpEFsFKALlDMFCRsC1RkZGxsamBobGoFUG5sa6qKrRgaPGCU4/p9lElj5lEni81kmhdOXmDR+3GMyeHIJmApZPjByz2JkuMXIMIuJQekuEyfYpQ1pDoIQN4s4SM6aCQIn7S0hIhfsFdPA4Jq90VomhWAJDppHdYsDNUxpOHmEKuYQAyBh5XPXwRHC/2HvwZjACAB9IH8c

RNG Seed: 2908579868

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1566840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1566840, 0x1ccca00, 0x159ec00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x159ec00, 0x1566840, 0x1ccca00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1566840, 0x1ccca00)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
