### ISSUE TITLE
Crash Report -1175419675

### ISSUE THREAD

**Issue by Petrouchkavodka** [wowsims/wotlk#1796]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUkEoRFEU/ffON9585Bmbb5pf/Cykpt7/vylW81nNwmLKxkokVhayYyUpNRsWUoaFpY1CFmIMiYUiMxbUZJgGZSFGUpMN9/s2dhZj5yxu59xz73n13lOCDNsgCstwWL8CsAa4D5AGyAM+AHQqDFRoARt6wI8CAhl5Eryx4f6xwVFWwT2BdVBqeX4H1UdN9x4dYGoLFR9/u0LdkyVazW/JK2i65/VL3V+iGtdcr5YXyCvRHi05ezX8gewlvy6TkkjekD8X/JY+/pKkVGewkheTqE5rRJ6IzAcVmc+kkOrZjlN3N5y6t+1MnlDGu0Yys+00JzdRZwxEVUzug9ZZlP7xA+NeBhxHoNOvMC7b1VFvDP1SQGaoDsSh1bSEEGHDsgwhLEsYYWGZxM2wCFtmSFghYVKbhowCqGzxBvnzKaofp9h4d44t+XMUpWv6V3IRPAmQsiAlUNJz6HMP77XrXNJsNyQWHBxH2t1OOtI09IWLiLmKjd0q+/PHm7LLkTJxfFiWnN/AvauunN3h6lIkCn3wCb9AdaA=

RNG Seed: 249387080

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca5340)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca5340, 0x1c42a00, 0x1d6f000)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1d6f000, 0x1ca5340, 0x1c42a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca5340, 0x1c42a00)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
