### ISSUE TITLE
Crash Report -1715924841

### ISSUE THREAD

**Issue by wenti6** [wowsims/wotlk#1798]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJT6x9LEyBaQk1iZWsTBKsAstZaRi1/g42YmiTeySmxHDzHd2sHExSnw6Q6TEvM+IJNH4PFuJolHshAeu8BVIK9LFqjlyBYmiS2SSmxAYZAWLoF7QDPmCCkxMnDxChwHSk6RUWIBSjIATfu4B2oav8BDoP52WbA2iIHbdjFJTJPhYhHYt4wJSPbvA5H7d4HIV3tBClbuYZLok+NiAAo0bWFS4udgNOAOYIpgSWCsYOxgZNSawMQwClBAFRsHowBTAaOTEBeHAIsDjwdbAJMQgxQLB5NEchdjhJGxgYGBqaGxsaGBgbGxgaGpgbERkG1kamBqbGSgawCSxgF0DYyAOoAKDLFIPmIU4Xh/lklg9n0mif9nmRSeXGLSOH0JmAhZPjByz2JkuMXIMIuJQektEyfYlQ1pDoIQ94o4SM6aCQIn7S0hIhfsFdPA4Jq90V6mgjm1VTwBiSXJGeWpRdkKRqYKwRIctI73D40O1DCm4eQRSswxsNAqcCRWMTjwGqY9coDqeGEPzB8A2GuEDQ==

RNG Seed: 3597894351

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c98790)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c98790, 0x1cac000, 0x1c71800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1c71800, 0x1c98790, 0x1cac000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c98790, 0x1cac000)
	/home/runner/work

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
