### ISSUE TITLE
Crash Report 89899811

### ISSUE THREAD

**Issue by Sappachino** [wowsims/wotlk#1799]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFMU1EU/edSyvMh6RMdHiQ/KX/RmJC8/3+alKlfJgaHJi4dYYAwMBAndPoaEwKLHdTExs3FRWoIA4ptDWgsW8OggQRIcCHGQTSBxkXvayXGjQE2znCTe8555yb3PpkWpMhQFiMoYJpioAi8Ar0DGsA+MHxZIE0GWUTIWw9eAL1O/5fEfSTzU2N3xm+LpEJ/GTKl6oukv7le8sMq/VwmmVD7FZIX1ZO3pPdcr6PKXJdq1Ekfuex+zHST3UxvsSLVwXPSz3o9OLJHNZdIL/R5CRYdjmhWyEtypo1IqUf8cvbfyy5VrpL+4fLAh1U7tvja1tobW79WrCHmuENriFvkvRXyhIBBoXMG14vknOM/3OXlKNI0jcCVUkAjnypg0h6+R3aL38fAPK5mTBgYE/p+Jgz9kBs/DE2G+yD0BwcDk2HR+MEetIh3SX2ukd6sUfrXDl1b2yDzcYP4m31HZwnO3N9DBNEWnBI53jZdaBHxRHSpLV2J+kpPLdZzQ22mkRuYaOFTLnhJ6VtanPlBH0SnkRKvvz+VnJOgvaub29GNdt/MjWAUfwAAUH4x

RNG Seed: 1553236800

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cd5c30)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1cd5c30)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1cd5c30)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1cd5c30)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
