### ISSUE TITLE
Hunter sim

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#18]

**Comment by jimmyt857** [comment]
#82 #83 #84 #85

**Comment by Ocisly1** [comment]
Something with hit rating seems to be way off. I just compared to 80 upgrades - same settings/gear/enchants/gems etc. but in wowsim its almost 3% more hit. Right now it is zero (after refreshing page)

**Comment by jimmyt857** [comment]
Hey thanks for the comment! Someone else mentioned this and I found the issue, should be fixed now.

**Comment by jimmyt857** [comment]
Most of the development is done on this now, hunter sim is in active Alpha mode. Still have to improve rotations and I'm sure there are more bugs, but this thread can be closed.
