### ISSUE TITLE
Crash Report 760737299

### ISSUE THREAD

**Issue by Brinq** [wowsims/wotlk#1800]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJS6zNLEyBaQk1iZWsTBIsAstZ6Ri1/g8BYmiTeySmxHDzHt28HExSKwYQsTF4/A491MEo9klZg/A8XYBSbvY5LokgWqfgQU/gFUDVQKUs0l0AoUmCOkxMjAxStwHGjUFBklFqAMA9CIBUuYJCbKKDGDFPILPAQqbIfohJj5bg+TxDQZoIX9+0DWPv4PIj8uB5Gv9oIUTADq+CYL5P7eCxL8tohJiY2D0YA7gEVrAhPDKEABVdwcjAJMCowFwFTA6CTExSHA4sDjwRbAJMQgxcLBJJHcxahtZGxgYGBqZGxoaGBgbGxgaGpgDOQYGJkamBobGeoaGOsaGAHFgaoMHzFKcMy+zyTw/iyTxP+zTApPLjFpPLjEZPDjHjBlsXxg5J7FyHCLkWEWE4PSXSZOsAsa0hwEIW4RcZCcNRMETtpbQkQu2CumgcE1e6O1TArBEhw0j8IWB2qY0nDyCFXMIQZAwsrnroMjhP/D3oMxgREAxNJ00w==

RNG Seed: 300402764

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ccb1e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ccb1e0, 0x15ec000, 0x1648e00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1648e00, 0x1ccb1e0, 0x15ec000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:427 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ccb1e0, 0x15ec000)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
