### ISSUE TITLE
Crash Report -1403842937

### ISSUE THREAD

**Issue by Mursz123** [wowsims/wotlk#1801]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUT1oU1EUft/x2VyvltwWh2tJJL6lUijc9x4BnfJ0yuAQcMlYB4ODQ3FqOz1LoeBibWvB4OAogugkNdFG/KFkKykqRqJQlyIW2q1kiefm0aGbQ7v5DQfOd77zncM5MidIkaFLKKKMSYqBBeAl6B2wAWwDV4cEcmQQoWQVeAoMOyPf3VkMlG7fmL55RwiFkReQabX0hvSfrDfw6T3trZJ0Vfya5Bm1wvRW1jvxpEkypT7XSS+dZ/VDpvdZzXSb1VI9e0X68bAHRw6qRS4uZzx3bZUcttipkX6QSSzSqs4W89zJbXZOSq2zeiXDA++v2bG/ejY2ajb+fmsFm2zdzdqN+uTdOnlSwKDklk9OYWyBnP84hBkhoEjTJIKs5FNplNJl3LKvH5SnRe8AuIfRvAkDY0Lfz4ehH3Lih6HJcx6E/vh4YPJcNH6wBS3in6S+Nkh/a1Cu+4MufmiRWW/RNtxdpKpw2nCq5HgdOtXfIq5EQ8k+Z6Nz1UcWzcLlhNkoXKj08aUQPKfcdS2O/Y1z0VG4xM2PR+LzL0huda0TXUny/UIRE/gLumx7hQ==

RNG Seed: 3048744890

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c99d90)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c99d90)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c99d90)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c99d90)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
