### ISSUE TITLE
Crash Report 480199560

### ISSUE THREAD

**Issue by froto1667** [wowsims/wotlk#1802]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUTFLW1EUft/Jq16vilfpcBP6JL5FKQj3vUegnfLaKYNDwCVjO1QcHKSbTmktVF0UBMH8AePQ0CmUaqNERYKLOCiVRiEuIi20HYq46L0+HdwcdOs3HM73nfN9wzk8yUiQomfIIIdRygOzwGfQGrADnAAvOxmSpBAiazZQBLqsRN1+j6bsyOuxN28ZE0gsgXeIX1WSPx23abNKlS/EW8TfH+TGDnTbJuZXSDYcN2YGzWL5K8m5bm1p7JM80xYtm712MbFMsuS4thYszsW7mqZxF5ZO+7dCN/5imeRHRzelCsn5J9wWMxXS9fjC1D+Lpp5+M5vbOu/c0XSvbMTJCrmMQSFr5x49nSXrP25hXB9HkKRR+A7nDBLZjhyGzcvbeSu7uAGm0ZtSga9U4HmpIPACTbwgUCnN/cDr7/dVSg+V5zcgWf6IxP4qye+rlDw/pL71XVJbu3QC+zdYAdbU9SP88ABWgSy3Ti1XQn4o7IxGj8N4YcGgln4eKTvpnqEr7KX9T5QclOzBH/ohvI+UfG3jXnLuguhWA/XwRcTP0hm8wiWYIHsj

RNG Seed: 2631754360

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x16b0a50)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x16b0a50)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x16b0a50)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x16b0a50)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
