### ISSUE TITLE
Crash Report -358715547

### ISSUE THREAD

**Issue by Butapal** [wowsims/wotlk#1803]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFIHFEQ3Td36ndzcl+xWOVWzq2CIPzd5UCrW60sLA4svNIUioWFpDKpVgmIVmeMgoeFpY1gYZF44kmiyJEiYqFEooIgWFicRUBszOytFiIEC+18xTDvvZkpZkZPCpKkqAM9yGKUfCAHrIK2gD3gAuiuF0iSgodMUIFloEFrzldNoDoz8u7D4HshJJrXoMfl7AYZl6ZVvfOdlkqk18q/f8iKHH0lPSbn2TszrUhgxOT5IRmzLaEXl3PsXXMfe5ss1MkLthcbrCgzjeln9r8k7mhMXjGdSViRoLZGlplNmpzscjKf0KPyV4E45r4FsbgexHIhqPxZIOPGZOpXxPECWbqAQiaarRpDW460VzzARyEgyaBROKbOqzKQiWcxHNy/Tn8jbu+BafSnlOso5dpOyuXAxHZdlXJt23HtdvVftDsqxa2K2x7hDIb4XSTpn5JxWKTk7j69vTkh9WOf+DfLiOahTd0dzvGOoOVJs46ptiL4Q159aDV6TfmFAKV0Z6jspVuHKjhIOyuU7DPEiz/AJ+85pvil7WeZ8xSEu+o99rpCfp3uwQD+ASa4h7E=

RNG Seed: 2914131026

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c96d10)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c96d10)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c96d10)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c96d10)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
