### ISSUE TITLE
Crash Report -1243377074

### ISSUE THREAD

**Issue by Malksss** [wowsims/wotlk#1804]
Link:
https://wowsims.github.io/wotlk/mage/#eJztkk0oRFEUx9//zGtc18g1LO5MpngrKXXnvaZYzWM1C4spG0sSKwvZsZqklA0rZVigyIYkyXfyEbNQQhbKt4WFIkqTDfeZlZ0FO//F6dz/Pfd3bvdcXsaoBgmMY7dkBpgHbQFHwDXoAajnDBKVcNGEICmE98xe+JMdLd1tXQzCF54CLxI7iyQfI5Z/b5s2l4mb4mWBeEDcrZG8jVi+mRXieSKzQHIgopO3A5KLIc7FqXaGgxYMXij2NWIuZJn6vKG3shtkmca5hhWJG43p13S99brskZZWSb5EdJvBTa/ZwaQXT9a9ODbtFaQ07M0reN/wzIlhshiDKkiazagaIuNf39Tj16OkTtQHOROmG0j4kxQ0wiYj2TqAKttRSsWijhNVynFUNKYcW+d2TMUcu1o51crWti6K3kKy0SsST4ckPw6p/P6YKq+PSWUv9V8qeIYvDeMcRpoM64Lyv3qn2t3i3C1K3VB6xFMmXptzjuIV7V86i9uzVN4o2Z8Pr8/9DUoqs/srnJ8o91YNF25dbp2NJ9CMT1cvb8w=

RNG Seed: 1468468805

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 22 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cab8c0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cab8c0, 0x1cf2000, 0x1cae000)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1cae000, 0x1cab8c0, 0x1cf2000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cab8c0, 0x1cf2000)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
