### ISSUE TITLE
Crash Report -1170598274

### ISSUE THREAD

**Issue by MagraeByzae** [wowsims/wotlk#1805]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJS6ztLEyBaQk1iZWsTBIsAstY2Ri1/g42YmiTeySmxHDzGd28HExSKwYQsTF4/A491MEo9klZg/AMXYBbqOMkl0yQJVH9nCJLFFUont3mGmxTuZuLgEluxjkpgjpMTIwMUrcBwo+VNMieXWDiYGLk6BBUuYIPr5BR4CTWuXBWsDCfAItAEFPkGN5xSYchaqkkWgfx+I/LgcRF7eA7J77gMmiW+yQO6mmyDBb4uYlFg4GA0YtSYwMYwCFFDFxsEowFTA6CTGxQNksTjweLAFMGUwCjFIsXAwSSR3MWobGRsYGJgaGBsaAmljXSAbyDEwMDQ0NjAyNjY0MDU2NDIwNjI0NjV8xCjB8fksk8D/s0wSK58yKTy5xKTx4BKTwY97wNTF/YGRdRYjwy1GhllMDEp3mTjBDmhIcxCEOEXEQXLWTBA4aW8JEblgr5gGBtfsjdYyKQRLcNA8BlscqGFKw8kjVDGHGAAJK5+7Do4Q/g97D8YERgDRuHdP

RNG Seed: 1728288296

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cad1e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cad1e0, 0x1cd4a00, 0x1448a00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1448a00, 0x1cad1e0, 0x1cd4a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cad1e0, 0x1cd4a00)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
