### ISSUE TITLE
Crash Report -162594823

### ISSUE THREAD

**Issue by Mypcilka** [wowsims/wotlk#1806]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUj1IW1EUft/xNV5fI7mKw1NM+/qWFiFw8x4P7JRnp44PumSVogh2CFKQCoXooOJiqBpocHAsnTqV+pOk9IeSTaS2VYqDIARpwUUQF3tuUgc3wXbzGw73fOd83zncey1HkCRF/XiILHKUBwrAG9B7YBOoAw86BBxSCBHpDrwCOo2eA3MKsejJ4LOhMSEkelZhJeTCBtm/km7s8wdaqZHVJo9/ktuy+46suCxybS/ptlQ4a5Xb62Qv3GLJEtMnLGFa91ny9VuylztdGFa7fMHFxV7XZDODLZZ2yI3xWVsk5CIXZ5rKSmPCNHsWe5sTTDlf0bGwqmN1TcfDsp78g7tOk5yeljU5uU6uEFCIzOyNvgIZ17iACb4cSTbl4N224gI2HESJLEb0J2i3boqzc2AOdwPle0r5aS/w/bTPSdr3VeCrNHOplKcCpTlvH7b4WiX5vUr2TpWc0jbd+7hF6ssW1WEeobUEYxdGiQz3N7U19sgPhx3NjbrC7tJLjVrmfpPZzNwZbuBbxitTbvn5RDwafPp4ZHxobNTxAueRLf73yx5Nhv/CJl/7dBUf1d+XG7hsc+Py8sX98K+inpkF/gAP+oex

RNG Seed: 2831885731

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x177c2c0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x177c2c0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x177c2c0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x177c2c0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
