### ISSUE TITLE
Crash Report 1003931115

### ISSUE THREAD

**Issue by KlancyKL** [wowsims/wotlk#1807]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj1II0EY3fdliePq4Vy0mAsJeFuJIszuEDirrFYprgjYWCqilYVcp1UQQbBRUISLFpY2wqEioiYehxYWwSCoIP7EeIXFcQriEbhCZ7OVnYV2vuLj+3nvzTDfWDFGX5DCInYbl4AfoJ9AESiBboAui0GgBR56ECGJ6JE5hnB6qG9k4BsDD0XXYDXw0haJP3E7vPeL8htk1fKHM7JDpzqt59d6Vo7boXtd1fCZPInJuJaUT0hUtETzfZ7FV9dJLERsGNYHfqk1szHb1ENDW1RyVCX63g38Sg8nAmXg+XebxFzMMvlUnnQ82PJjbsWPO5s+IbNG4l9cl/9zfnNxnWzGIOvSZi9ap8l4xzOMhvVmaRhdEYtx06tPhdMUMaImI9E/iTZXSSkTjlKOlEpJJyGVq3M3IRPKddqlapeucqVmOWUINn9J/LZA4rFAzb8PqaV0SLJyof+WeYeaLIxTGFky7HOqrR6eGfQ+Btdo8j5lv/vYT3YEnWLy82AVx0l3mZq7BXvz7Y17r+GS2d99FZ+XIHirr+deZ1BXkin04gmCwHdM

RNG Seed: 601077780

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca5290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca5290, 0x14e0a00, 0x17ab800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17ab800, 0x1ca5290, 0x14e0a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca5290, 0x14e0a00)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
