### ISSUE TITLE
Crash Report -1497760054

### ISSUE THREAD

**Issue by vlaicuro** [wowsims/wotlk#1808]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUjFIQlEU/ff6sddX6GUNL8mwP0kQvP8/Qk3+mhwahJbGInJqiLaaJJpcas0KxCmCQsrBRYnSKEIKh4agMmmIEKIgkRZ73w9BUNBQW2e4vHvuOfde3ntKL8EhCEMSCl1bAGnAA4ALgArgA8CoQoBBAEyYAA9y8L7KS+CMzE4tzMwThTq826B00KMMsppPdRYP8SqLikzTGVTc9FjQVZ/qsLg2Gi8ii/uEuiDohlDns/gsKgq92Ue24VFBEufmCbLdHvvcyKEqC4kkTEVhSvZ9mNro5R6yF5+YtZK3Jp6krPiYs2Lt3BJsVpDVLcFbi6ynUCUEuCsiT8LAKkr/+IRFJwGKczDqUQiVTXfYGUGP5JUJsuk4TOgG5zyoG5rGuWFwLcgNkXA9yIOGrg1yq/wNBrkuHEKgfVGsAiPrt0ifSsiaJfSflTFwV0Z+Xxbfz5UA6QqkBErqNba31oxFzU574W6zJ7Fm4TQ0bDMXof5oC5chfQf944z8+Tsvm7/RJXZa+JU+P4F9V2PX5oidN0JhmIR3KJN6/A==

RNG Seed: 202584911

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c976b0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c976b0, 0x1cb7500, 0x1436c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1436c00, 0x1c976b0, 0x1cb7500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c976b0, 0x1cb7500)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
