### ISSUE TITLE
Crash Report -284223733

### ISSUE THREAD

**Issue by hazx12** [wowsims/wotlk#1809]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUj1oFEEU3u/dj5Px9CaHhMnBwrqNIRCY3WUhVrtaWR7YHBZCkEhAiyMIaiBwiiKmMUUUPNIrCiIYRO5MImqQVMYISoIoXCFHtIgp9LTRmVtP0EpQO7/i8d73vvfNY2a4w0iQomEcQBkVqgLTwG3QA2AFaAH7exkcUohRMgpcBwpaXryTOYts6fjI6dFxlhUozoHnxec5ku9tN7v0kBbuEe8RW6/ITa3rdJt4d59k09bJ1BLJT7ZWX9ZMm7lZLTUSLs43SM4WXFh8h2hrq1v9blo3LZ4T7XnqCI1tXszoyQv2DyInbqyR3LLdlKnS4tKCiU8bJm7Mm/jhmlnh+V2SH21dPqsb8kyDXM6gUMqUM6cwOE3Wf/yECcYgSFIFfh/fySAxYK4rX8YYClaRuDWFPaEKfKUCzw8DHXThBYEKA8/zA29oyFehbirPb0Ky6hsSLxdJri2S8+U1DTxaJfVklVpIb2J7DYd4UZ9ysc/52gUKLNlkM+IiecdfmJl6l4lLMZc8zd7eTBVEV9PtrMOqkeVuUE/SORz3JsmuuL921WA52pswK9Huox28iPw6VWYnJ3KlkRNHxk6Ojh9z/NA5KNk//yrn4r/hUl1+/Cc+aniwsu93xZ3Lq15pxt8nWtE3pvGTPw==

RNG Seed: 1111348266

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x17d6580)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x17d6580)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x17d6580)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x17d6580)
	/home

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
