### ISSUE TITLE
Crash Report 323473881

### ISSUE THREAD

**Issue by Pallyboom** [wowsims/wotlk#1810]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUs9rE0EU3u+l2U7HxkyLyCYQWPeiFAqzuyzUU1ZPHhe85FqkpaCHUAS1IKwFMfVi0Fow9A/wJIoeNJpE/EEteCiFChZByKmIQulF6KW+SariTVBvfgOPme/HO7w30hWkSNMETqGCKqVAHbgPeg6sAVvAyREBlzRiJMaBu8CoVZzPzsNOzk1empoVQqH4ADKvbj0j53PJs1+/oPZjkkNq5wN5mU2+Dqsl1rolL2OEQbXxlJyvJY7cZvpRwbOZNj6prrKyPOrBkjl1k8V7BW+ARYu71ZrUz+fVIivXSj9ig2qFiZ2SHFA32sS1/sTUTtPUTy1j2HtIzq4x7LYMWWuTJwS0nWQr2bE6Wf/xC+Z4OIocqiJwZU7AQZKvYAYX35jt5+QBsfcduI6jkQ4DrUPfj8LQ5xP4YaijUPtB6I+P6yBikR9dOCL9SOpth5z3HXIbG3Ts5TrplXXin7aNTANFqeRBsXDY/dlf2rywxSYt7G8piDdhNcjyvtBQj0in45G+dCguNO4YrJaP95m18pHpHt6VgxZVly/PDSeT58/MXJiaPesGkXvaEf96/dtX4r/RJl199Sd99MRY9cTvmnvDS5e68X5iq1wDvgF66ZKB

RNG Seed: 1553851187

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x14e46e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x14e46e0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x14e46e0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x14e46e0)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
