### ISSUE TITLE
Crash Report 199129426

### ISSUE THREAD

**Issue by AxelLidvall** [wowsims/wotlk#1811]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFAKqk7rA0sTIFpCTWJlaxMEqwCy1mZGLX+DwFiaJN7JKbEcPMe3bwcTFKfDpDpMS8y0gk0fg8W4miUeySsyfgTx2gcn7mCS6ZIFaHgGFfwC1ANWDtHAJfFzMJDFNSImRAcjeuo1JYooMiM0p8HEP0CiQEn6Bh0A97RA9n8Fmr7oJ1CMDsYlFoH8fiHz8H0Tu3QQiX+0F2dkAdN03WSD34i6Q4J1dTEocHIwG3AEsEaxaE5gYRgEKqGLjYBRgKmB04gMGFosHsxCDFAsHk0RyF6O2kbGxgYGpobGBoYGBEZA0NTA2MjY0MDI1MDU2MtQ1MNY1ACkBKjJ8xCjBMfs+k8D7s0wS/88yKTy5xKTx4BKTwY97wGTF8oGRexYjwy1GhllMDEqvmDjBFi9IdxCEOEHEQXLWTBA4aW8JEblgr5gGBtfsjXYxFcypreIJSCxJzihPLcpWMDJVCJbgoHlUtjhQw5SGk0coMcfAQqvAkVjF4MBrmPbIAarjhT0Acit9Pg==

RNG Seed: 3908535621

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cd5290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cd5290, 0x1c1f500, 0x1cfba00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1cfba00, 0x1cd5290, 0x1c1f500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cd5290, 0x1c1f500)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
