### ISSUE TITLE
Crash Report -1608883760

### ISSUE THREAD

**Issue by JohnnyMBear** [wowsims/wotlk#1812]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztkj1II0EUx/f/ssZ1iWQMCnuSHLltPARhdpeAVlmtLCwC16S8KxSLK8RKrVYR/KjixwUuWFjaCBYWauQifuAFC8VCOdE7EIQUFrEQxMq3WZvrLLTzXzzm935vppgZPamRIEmd6EUWQ+QBOWANtAOcABWgp0lDkiRcZPwJrAAxpfVGnUA48/3baP+wFhZoXYceFQvbZNwmzPDBLi2XSW8Q95dkhi42SI+IPLvrhBnyRUTcnJOx8DFwUfGD3QPvY/eLG42iwnopZqpMCuM8+8X4M0bEHeNc3Az5s/WiyjSV4MUhL/JxXRXHReKa2/Rracuv1aI/eVQk4zHB6NWa40UyGzVIZNRs3QimgfYcKe/5L2OaBkEGDcFu0fm2DGSiWQxi5Lf/C0hXZtGWko4tpWNZKcexHAbLcWSK2Xasjg5bplhKy76GoXn/SJyXyPhTouTjX/q8d0ry8JQqUKuoL0CZeX4A272AUiDFvKKGWsMbcJsC1ex+KPz0U053BZ2T9KeBWs7S9iolvxjamz/kpPsap3jl/Vc55yUJ7qrvyu0O+CHdi694Am8pd4I=

RNG Seed: 2732611231

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
