### ISSUE TITLE
Crash Report 431181316

### ISSUE THREAD

**Issue by Klorra** [wowsims/wotlk#1814]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJQ6z9LEyBaQk1iZWsTBJcAstYqRi1/gwW4miTeySmxHDzHt28HExSnw6Q6TEvMtIJNH4NgWJolHskrMn4E8doHJ+5gkumSBjG8nmCR+yHJxCWzexiQxR0iJkYGLV+A+0JwpMkosQEMYgFI/9jIpsTCATOQXeAiUagdaAeRBTFoPNGmaDBeLQP8+JiB5YhGI3LsJRO7fBVIwAajjlyyQe3EXSHDnIiYlXg5GA+4AlgTGCsYGRkatCUwMowAFVLFxMAowFTA6CXFxCLA48HiwBTAJMUixcDBJJHcxahkZGxgYmBoaGxsaGBgbGxiaGhgbAdlGpgamxka6Bsa6BkZAYaAiw0eMEhyz7zMJvD/LJPH/LJPCk0tMGg8uMRn8uAdMVSwfGLlnMTLcYmSYxcSg9JKJE2x3Q5qDIMQVIg6Ss2aCwEl7S4jIBXvFNDC4Zm+0k6ngW00Vd0hGYkpKZmmxgpGpQrAEB80js8WBGqY0nDxCiTkcNjeaHIlVDA67AztuOEB1fLEHAPfse2g=

RNG Seed: 2357978574

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c989a0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c989a0, 0x1cac000, 0x1c71600)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1c71600, 0x1c989a0, 0x1cac000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c989a0, 0x1cac000)
	/home/runner/work

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
