### ISSUE TITLE
Crash Report 704436641

### ISSUE THREAD

**Issue by CFFMCVGIX** [wowsims/wotlk#1816]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJzjUuFgEmAyYLJg9GCMYCxgamBknMDIuIDxiPAGRqYDjIwXGBlfMDI6CXIwKjAZMDowBoBUMa5gZBRikGpkbWJkC8hJrEwt4mATYJTaxcjFLzB5D5PEG1kltqOHmPbtYOLiFPh6h0mJ+RaQySMwDSj3SFaJGSTBLrB7F5PEZDmglqlA4R9ALQtOgrXwCjTvZpKYI6TEAuQxALmTgPJTZKBcfoEfe5kkJsoosQG5IOX8Ah+uMkm0y8IF2AXWb2KSmCbDxSKwfxMTkJywE0S+2gsiPy4HKWjYwiTxSxbIvbgLJNi4m0mJm4PRgDGAJYK1g5FRawITwyhAAVUcHIwCTBJMBYxG0lxAtgQwHWSAEgEvFzfHfxhg7GJUNzUwNjIwMDY0MjU2NjQGcgyNjQ1MjQ0MjYwNdXWNDEyBkkDOI0YJjob7TALX9zNJ3NzPpPDrHpPG4UtMBscvMb1gZPnAyD6LUYZLiouPo1NMAWG+EAfUPQ63GBlmMTEo3WXihAjEOQhCGCIOkrNmgsBJe0uIyAV7xTQwuGZvtJZJIViCg+YR3OJADVMaTh6hijnEAEhY+dx1cITwf9h7MCYwAgCkVoq7

RNG Seed: 811938922

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c9ab00)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c9ab00)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c9ab00)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c9ab00)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
