### ISSUE TITLE
Crash Report 50432215

### ISSUE THREAD

**Issue by majestum** [wowsims/wotlk#1818]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFoFEEU3fdvc5kbojueEiZHTs5tEoTA3I4HprrV6gqLAy2uVEGxsAh2Wm2CEGJj4GLAwyKdgigpgiSnJkEj4bqQwmgwKgEliIIpImKjM7c5IdhYJF1e8Yf33v9/hj+f9zASpOgkSqhggCJgAguHJ0HzwBLwBvgI2gBOeww5UghtGh4AaSfzpG0IyfLVC9cvXWNMIDMD7onqM5Jfs37y1QuaaBBPia135CdWp4l3iHHjrWf9hDU6xKcVktWjseeJO8ab6vKTs9NkhQNiw9j30r5rBMfQx3WSY93bNCW+1Snu44kxUzmc/VvZLhaNMN7NXTE6QybenrVx876NX57bhGiK5I+soVHdioNPyWcMCmW30nZ8lJx97MANMxxBkgYQdPKDjCR6zbBKXgVX7BoQd26hp6BVoLTOBwUTtNJBXmtlxLzS+b6+QBWU0koF65As+kBiZY7k2znK/XpPvS+XSS0umy1zv6O9hjLPmFtGOnO/W0CaxS85EnLJXfb5YSItWkp8nms6olqnf52R7R89Ea7CqZHjr1GqKcxfDA+1krtqdy0axf5YWSoeu9zE62LwiHJnJdvzzbgZ7kaXqLGwK33+B/GszqyFp2L+s1jCefwB30SJrA==

RNG Seed: 4118249629

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x16c5550)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x16c5550)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x16c5550)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x16c5550)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
