### ISSUE TITLE
Crash Report -1537238151

### ISSUE THREAD

**Issue by edgeralenpwn** [wowsims/wotlk#1820]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJRqZm1iZAvISaxMLeJgEWCW2sjIxS8weTeTxBtZJbajh5g+72Di4hT4eodJifkWkMkj8Bgo90hWiRkkwS4weR+TRJcsUMsjoPAPoJZ9O8BauASWAGXmCCkxMnDxCtwHSk6RUWIBSjIATXu7C2oav8BDoMwCObg2doF3e5gkpslwsQg8/s8EJPv3gchXe0Hkx+UgBROAOn7JArm/wIJNW5iUODgYDbgDWCJYtSYwMYwCFFDFxsEowFTA6CTGxQNksTjweLAFMCkwCjFIsXAwSSR3MUYYGRsYGJgaGBsaAmkQGwXoAuVMQcKGhsYGRsbGhgamxoZGBsZGhsamhrroqpHBI0YJjs9nmQRWPmWS+H+WSeHHPSaNh5eYDJ5cAqZElg+M3LMYGW4xMsxiYlC6y8QJdm1DmoMgxN0iDpKzZoLASXtLiMgFe8U0MLhmb7SWSSFYgoPm0d3iQA1TGk4eoYo5xABIWPncdXCE8H/YezAmMAIA+P9/FA==

RNG Seed: 801626839

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca5290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca5290, 0x14ca000, 0x14e0c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x14e0c00, 0x1ca5290, 0x14ca000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca5290, 0x14ca000)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
