### ISSUE TITLE
Crash Report 1747776506

### ISSUE THREAD

**Issue by NewYorkStyle** [wowsims/wotlk#1821]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjEuJgsmD0YNzAyHSAkfEBI9MLRkYnDg5GCUYDxghGIQapByxNjGwBOYmVqUUcXALMUrsYufgFHuxmkngjq8R29BDTvh1MXJwCX+8wKTHfAjJ5BB4D5R7JKjF/BPLYBSbvY5LokgVqObKFSWKLpBIbUNE5oAyvwIvrTBJzhJRYgAYwALn3gdrWSUK5nAJvdwENBJnNL/AQKNMOtGwfRCe7wDqgmZ9kgYwJO5kkGuSAjP59YAaLwMflTEDy1V6QsjNAfb9kgdxfe0GCTVuYlIAeM2AMYElg0prAxDAKUEAVCwdjAaOTFJcAB6MAiwOPB1sAkwQwDWSAUgELB5NEchejlq6BgampgbGBgaGRsYGRsbGhgamxoZGBsaGhsamhLpBhDJQEihoYP2KU4Oi5yyTw/yyTxMqnTApPLjFpPLjEZPDjHjCJMX9g5J7FyHCLkWEWE4PSWyZOsAsa0hwEIW4RcZCcNRMETtpbQkQu2CumgcE1e6O9TAVzaqt4AhJLkjPKU4uyFYxMFYIlOGgdpx8aHahhTMPJI5SYY2ChVeBIrGJw4DVMe+QA1fHCvoOREQCs0n8u

RNG Seed: 2895432788

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c94840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerPyroblastSpell.func1(0x1c94840, 0x1cdee00, 0x1cdef08)
	/home/runner/work/wotlk/wotlk/sim/mage/pyroblast.go:35 +0xa
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func2(0x1c94840, 0x16c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:104 +0x6
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:402
github.com/wowsims

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
