### ISSUE TITLE
Crash Report -1907922648

### ISSUE THREAD

**Issue by Renvert** [wowsims/wotlk#1822]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztkjFIW0EYx9//M8bztHiGDqfwIL5JCsK99wjYKa9ODh0CDs2og+LQQZxqpyBCq5ODFQy4uKRLi0PADBpLq6hQRDMoCmrJoohDFSySFurdiw6lUBx062/4uO9///93cHc8zkiQok50I40hygCTwDzoE7AFnABdzQxxUgiQMg68B2JW61TtKKKpl30j/cOMCbR+BG8Si3Mkz2wnuvqZ9gvEI+JdiXij+Krlsu3UGK1OTKySPLe1+2eeZL7FiRYLoZuLXzmS0zEHlnaVc2QWjeJqiZzoZoG0S2cqOvPGDjPFcNroEckLm9eLy21yao4XzKnrc6aeLpl6njOu2W8kf9i6rYTi2yI5nEEhFUnXvsKTSbL+8wevGYMgSUPwbK6vSiLVlMageflHvIH9vgUTeJFQvqeU73oJXxfduL6vEr7rer7bof5Jh6cSOqp07C/KkCxzRGJ3meTeMsW/lKi9ckhqrUQniHxHXRbW+M3DecE+rCxZzgHVh0JmIGiubj0OWrIzho3k06qylWwbCNlJeh8o3iPZg3+AseA+pmQ2Vu5lzl2o3tXzg+BZtb9KdqMX13d/h6o=

RNG Seed: 2377769164

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x17d6840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x17d6840)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x17d6840)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x17d6840)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
