### ISSUE TITLE
Incorrectly applied rogue T7 4-piece bonus (bonescythe battlegear)

### ISSUE THREAD

**Issue by billstpor** [wowsims/wotlk#1823]
**Describe the bug**
Since yesterday I'm seeing the 5% discount on combo moves (mutilate) even though I'm not equipping 4 pieces of T7. That means the cost is always 52 instead of 55, and that's also reflected on the dps which is way too high due to the energy savings.

**To Reproduce**
Doesn't matter what I do, it happens all the time.

**Expected behavior**
The cost of mutilate when I have the glyph of mutilate but not the 4-piece T7 bonus should be 55: 60 base energy minus 5 from the glyph.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Windows 11
 - Both Chrome and Microsoft Edge
 - Chrome 107.0.5304.107 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
