### ISSUE TITLE
Crash Report -735650653

### ISSUE THREAD

**Issue by MedericGirard** [wowsims/wotlk#1824]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUk0oRFEUfufMM55n5BoW1zRT4600pe681ytW81hZTtnYSqRYTFKi1CRSNpSfMixslKwskPwMMRaKkkQkP8NikvIzG7HgvBkbO4Wdr9vpfKfzfed27lW9ClZCLUxDongWYB5wE+AA4AowBVCjKsChHCyoBzcK8BzJveAMtzV0NbUrOczhWQK1kG0vIL/3ac6dLYwvo5rHns9Rc5xR6mI3q8iTPs2RJpbLRuLIB30kSZDkhSRjy0hHLWCpE+RTbk0mA0lV2eIS8lGvBhK5Pa2Rm21cyK7JbYBkxNIZ+7lT5ONezdFPTGZDcTvevNvxcdWOGyv22D2SvfqIvq3bxfQMak4FRH5YDgyj9I8v6KbVMIxAjVtVmGy5ap1hdEseWUHeOAgB3RBCmEHDCAphGCJoCkOnXDeFaegVwqgQOpWpKZgErkxeInvYR/6+j/7bQyy/OkTxckFfS36E/BhIZyDFUNLuMC8zO9psFWVvUWKVxiZs7IaqspWDUFlzBschfQUjUz3drnBDR2NLZ1N7q183/XVc+fPX7LN+wyW6m/iJj6gMRKq/25xZXnQ8aX0qUqEPjst+rA==

RNG Seed: 1798631384

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca4840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca4840, 0x17c6000, 0x17c5c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17c5c00, 0x1ca4840, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca4840, 0x17c6000)
	/home/runner

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
