### ISSUE TITLE
MAGE SIMMING DOES NOT WORK FOR ANY SPEC ATM PLS FIX **To Reproduce** CLICK THE SIMULATE BUTTON AS MAGE DEFAULT SETTINGS WINDOWS CHROME

### ISSUE THREAD

**Issue by Reziles** [wowsims/wotlk#1825]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
