### ISSUE TITLE
Crash Report -721829317

### ISSUE THREAD

**Issue by Reziles** [wowsims/wotlk#1826]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUz9oE1Ecvu93l/P1NbXPKHKGBOJNpSK8uyPQTjk7dQwIktFSWgo6hCKIBSGKosahDlIwdMikFRcRqcWSItIOHSqlg0MRjalKB4UWEaqD8XfXOrgJ6uY3fL/v937vfe+/zAjqwyDqWDw4AzwEPQNWgSZoExiQAg56EKKEFGmkbyYuwy6eHbowMi6kMtN3IbtVc56cj1nXXnpOC3MkO9SXV+Sa6yyTaoNrraxrvuBsn6oukVPNsvg+R85OVkp1levTKReG7FJvWN/OuBabGOzyZHbPpVu95co1noEr27HR7FNypjLSUpMLxLzRjrjxKOLtexFXHkf8rRHx5Dy5XQK6s5goWadxHei9RcZ//IIJW0BRGQOO3M/KCpODdpFKGEPKSFuCnOEqjvmB1jqvA8/jGBxnzYnWnhdoPwg8nQ88Xwe+F+S9FhzxeYVUe4Wc++8p926NepprpHde88Pq3IJVQ79UPNeNw7n2T0Da0hIfHphRVDN1yIQ0xddTcVq/QnHkC16HUSPD/UQd8doro+GB3V0cCo/U7kRYLvTvtqwWjo7GeFnwG1SevjiRLA6dGx47PzJ+Jufncycd8a9fw9al8G/YVJYX/8RH9/WWT/xu5/jwKlOtcG/EZoF/zQ9ZSo2/

RNG Seed: 4129322822

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca88f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca88f0, 0x17c6000, 0x17f2c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17f2c00, 0x1ca88f0, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
