### ISSUE TITLE
Crash Report 1324304538

### ISSUE THREAD

**Issue by Clicknut** [wowsims/wotlk#1827]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUjFIAlEYvu/30PMSelnDKRXlJILw7g6hJi8nhwahpdGImhqirSaJaGgpoiVzEKJoKcIWwYyIGhyEaGgIKkuHaKlokYbqnTe1NdjWN3x873sf33v876m9Cg0hiTzOu/eAQ9ApcAnUQE9AQlWgIQwL4/ATR7AgL8KdmpmYn5pTwFzBDag+9nZEIffFGb0XSZXZU5lUL6uXKORyjErB5k+hVbZeIi3nD0ES+ljog4CtfaxZFhU3RToRqU72IHaW+1qGXeFhByek5QOipf5ldzVanNu1+blsB163SVvtVyVhfOyIKgW8I43IGkn/+IEFMRpGs0j4VYXJli/pTpFfCsoKaZMriBgm5zwmWOfcFBzjpmHq3IjpMdPQo1HDdkVGNx+hKVv3xF6qpH1VaaBxReHaFfHmnfg48is8WUg3kLIkhW7J2zo7M211ObfosQLZTRuV+LDjXMYHp1u4jhv7NDCmKX/+eEtWO1oylfO29PwGzqxGb60RZ92MJ5HGN96la04=

RNG Seed: 1211746957

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca33f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca33f0, 0x14e5500, 0x1648400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1648400, 0x1ca33f0, 0x14e5500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca33f0, 0x14e5500)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289 +0x12

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859

**Comment by Clicknut** [comment]
NP :) It has a crash report again. But onlye mage again. Den 20. nov. 2022 kl. 19.12 skrev James Tanner ***@***.***>:﻿
Closed #1827 as completed.
