### ISSUE TITLE
Crash Report -1796735590

### ISSUE THREAD

**Issue by Poulpi64** [wowsims/wotlk#1828]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUk1IVFEUft9xZrpelbmKizfCxPjahCDc9y4PdDWvVi0fuGi2EopQi0ECSwietehnEROV6DCLdrWKNkGio9EP4k5cKIkkDAgiBlqLpE2dN68WEkRQ7foWh/ud7/sOh8uRpwQp0jSAcyihTBFQAZ6BXgKrwC4wQzjbKVAgjQBhbMIToMvquZe+jkx4afjqyLjIKPQ8h8yq+wtk7+edzNtXtPiCZKv6uEVOyyY/29U0a42807LYZDsbZH/OJ1pWPWTtiHOsxXKHujFPdq3LSTGzpFQLTJ/mHFicPKqTk/mUGLPqASdvJslDbpxQy9x4lJMpVZkjrrfrcT18HNe9emyo8ay7J6XFjal5cqSARpgupa6gr0LWfxzDpBBQZFMZXl7yV9kIsyWMxQfQIdvE1x/AHZz3jfa0Nq7rG+MabTzXGO0z94zbr3+Jfk/7HNWu97PWgC2ibVIbS2S/W6LCl/d0+vUa6eU14vs8QLoKaxNWlSznA7U2t45Gg85k/+4gV52NsVIcTDqrxd7RJtaLXp3KtWuT7eHw5QtjEyPjFwueXxiyxb++g4Op4G+MiVbe/MkcPdBXPvO75ubnRdON4Htit3gL+AYwLpEd

RNG Seed: 2849104160

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c90f20)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c90f20)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c90f20)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c90f20)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
