### ISSUE TITLE
Crash Report 178967493

### ISSUE THREAD

**Issue by Quecy92** [wowsims/wotlk#1829]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUk0oRFEUfufMa9x5Rq5hcU0z4q2k1J33mmI1j9UsLKZsLEdiZSE7VpJSFihSxiyshFI2SmZMEotZTDSFyM8YFpJCUrPjPE/JzoKdb3E633fO+c7t3qsFGLZAFBZhr3oZYB1wB+AQoAB4B9CuMRDQCBZ0gQ8l+I/UUXDH+ruHegeZxl3+DdAqeSGF4iGou/d3MbOJmoe/nqPuOqPUy2+oVgzqrhdiZXwmg2IiSCNFkks0Qv12pYLfnaBI+nSVBIXoFdVnA5/Uw5/TZGh7V/Jrqox/TXr56imKuYCzT+VTGTsepOyYXLLj/ba9eSWNYrJOU0g430KdMZDlMTUOTdOo/OMbht0MOA5Au09jXLW8UXcMfYpfZSh6JqDJMKWU4ZBphqQ0TRkKS9Og3AjLsGk0S7NZGiRTU6gIgi1cIX/MoXjLYf1tHhsLeZSlS/pb6hOUJ0A5AyWBin6Bno/dI31WlXOKGqs2MW8jG2l1lMNIQ98HjiPGGtZ3Cvbnjzdm/YbLSHbvV3x+AueuOi6sNoeXIlGIwzvjuHdI

RNG Seed: 1879019412

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c994a0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c994a0, 0x15c8a00, 0x1c2b000)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1c2b000, 0x1c994a0, 0x15c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c994a0, 0x15c8a00)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
