### ISSUE TITLE
Crash Report -1402298103

### ISSUE THREAD

**Issue by R1PLI** [wowsims/wotlk#1830]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUz0sQ1EUfuf0qduHuErkadqk3iQSye17acLUx9TB0MTSkQgxGMTGJCKRWBhEogxGi0TEQFEiDE00qgNJo1SRdBA/EUlj4bw+i83A5htOznfO/b57c8+9ipdhO4RhBY7qVwHWAQ8A0gB5wCJAl8JAhRYwoRfcKMCTkyfBGRnuGxsYZQp3eLZBqeX5HVQffJrz+BATW6i4+Nslao4spdX8lnoFn+Z4LbP7C1RnfHavlheIlUhHIktXw4tUWHZrMjGJ6DVp571f1MVfdsk1UVbeUGfaVlrGlfxxF9UFryLz2QRSPN2x4t6GFffj1oITUrz7iJ7FreLkJmqMgYCIHK1onUPpH98w7mTAcQS6GmlqslkddkYwCkPgljwyQ7V/Blp1QwgRDBhGQAjDEIGgMHTK9aAIGnqbMNqETmVaFCiAypaukT+lUP1Iof8ugy35DIrSFb0x+RmqYiBlQYqhpOXQVd5/os+ss0/SYDbFFi0kQx12JR1qHizjPKSvob9HZX8+wCnzN1wmkke/4vMT2HfVnTM7bV4KhekPfwKjEXpZ

RNG Seed: 1945460305

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca6fd0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca6fd0, 0x14e3500, 0x15c0c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x15c0c00, 0x1ca6fd0, 0x14e3500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca6fd0, 0x14e3500)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
