### ISSUE TITLE
Crash Report -1316152105

### ISSUE THREAD

**Issue by DoomB0x** [wowsims/wotlk#1831]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJQ6y9LEyBaQk1iZWsTBKMAstYaRi1/gwW4miTeySmxHDzHt28HExSKwbA8TF4/AY6DwI1kl5o9AMXaB3buYJLpkgaofAYV/AFUDlS7dycTFJbBkH5PEHCElRgYuXoH7QMl1kkosQEkGLk6Bj3uYlJhBZvILPATKtEO0Ld4JMnAdUNs0GaBt/ftAdj7+DyL3bgKR+3eBFJwB6vglC+T+2gsS/LaISYmDg9GAO4AlgVFrAhPDKEABVWzAGGUqYHQS4uIQYHHg8WALYBJikGLhYJJI7mLUNjI2MDAwNTA2NATSxrpANpBjYGBoaGxgZGxsaGBqbGhkYGxkaGxq+IhRguPzWSaB/2eZJFY+ZVJ4colJ48ElJoMf94BpiuUDI/csRoZbjAyzmBiU7jJxgi1vSHMQhDhDxEFy1kwQOGlvCRG5YK+YBgbX7I3WMikES3DQPPZaHKhhSsPJI1QxhxgACSufuw6OEP4Pew/GBEYAmMBz7Q==

RNG Seed: 2723766613

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1d8f290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1d8f290, 0x1cd8000, 0x1cf4600)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1cf4600, 0x1d8f290, 0x1cd8000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1d8f290, 0x1cd8000)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
