### ISSUE TITLE
Crash Report -1520230398

### ISSUE THREAD

**Issue by Ohni-Mik** [wowsims/wotlk#1832]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUT1Iw1AYzH3G+hotfYpDKgZqRkF4SQjo1Ojk4FBwsKMOioNDcapOVQSxiwVBsLjrIjgU/C8iinZzUhBdXCzioA5ScNCX1oKDg0PdvOHj3t19N7xPizLiJKgXg0ggSWkgC2yDjoFLoAQMtDJEScBD3E9gE2hTOsrqPALxqbGZ8WnGODo2oIX5yiHpT4YZODuhwi5pQf56S2bDjaQtfFV694bZ4BtNfKVAesaQK+950vMRM/CwQ0XphHjpmvT1NlOVOUVjvJwnkxRFdr0cUm37WXYtGpKcS7Laqal8uUByZvf8+Xjkz5cNP7kpA2+GfKb3fXHugEyNQSCuJhpT6M7K6n98xyxj4KRTEnZUCzHoiIcTmETqwr96SGtmHzUggxHhOrYQjiV+QM9P4jfbdoSwHceyLcdyhe1K5jrCcoRr3UMpQX1GUw7K0teNbO8GSo4U846CFSE94bVWrXYvklvzUYz1VZXLWNdEBVcxe4uiwzr781svePVoSRdP69LzG1T/aujO66++y7FBjOITEpJ6MA==

RNG Seed: 1224713018

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x17833f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x17833f0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x17833f0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x17833f0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
