### ISSUE TITLE
Crash Report -561015199

### ISSUE THREAD

**Issue by adam-tj** [wowsims/wotlk#1833]
I tried simming balance druid

Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUktoE1EUnXMzjS/T1j6DyjM0ZTouLJXKmxkCdZXRlcuAmywtUinoIgRBLAhTFaRuDKYNGLtwWXAjClJbTYofSnel4K8IQhYSiovqStzUO9OW0p2g7jyL4dxzzz1veO9axwVJ0jSMMyjiHMZQohCoAA8wdfQRaBFYAT4AbeD0IQEFmzQCthd4oIRZIM3Tmfsd15EsXBq5OloWSYnMY1g9svqc1Nesk3zzkhpzZKXk90/kJNaYdska91pZJxE19slqg1S1j0emWf7BIyxHvm55Y4HUTNoxN+bI4PIu96d6HbMRlSk5vcCB3+KI2aekbmWZLLGl1svkDoeGfUwqz2JiyuY88Xf9ReTffELqZ5bLMBYnOEkIaBTMYsdghYz/2IPxTgFJNj8574fXb+0XpDAQ3VdPkdcmbWS6rU6xuQPcxrGc9j2tfdfL+b7rc+H6vs752vV8d2jI0zluctGCEuFnku+bpD42ya6/pYFXq6SXVqkNcwOJOk5YGT5w8rC9m58WW/91MLCkZYovDxO7yuT263nBGow6Gc46pWJhsRwc2DEdqd+LsJw/uaWs5PsvxHiX9+apNHNtvKswcvn82JXR8kXby9lnlfjna3Ez+Bsp4fLrP8nRw4OlU79rji8vrLWC7Yl2/hcHxZTe

RNG Seed: 2182646143

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c90dc0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c90dc0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c90dc0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c90dc0)
	/home/runner

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
