### ISSUE TITLE
Crash Report 259766527

### ISSUE THREAD

**Issue by Carlx94** [wowsims/wotlk#1834]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj0sQ1EUfuf0pW6fiqsMV9Mm9SaRSG7fSxOmPp06GJpYjESYDGJjEpFILAwiUQajRSJioKpEamhC/AxEg1IkBvETkTQWzuuz2AxsvuHkfOec77s391wtwLAF4rAA2dpFgGXAbYBDgCvAe4CYxkBAI1jQCT6U4D9TR8Gd6O8e6h1kwF3+ddCqeSGF4iGou3d3MLOGmoe/naPuylPq5TcbKIpB3fVaZnenKCaCTq+aF4mVSEciW1fF76kw79NVYgrRAmmnA1/Uw1/S5JopK6+pM+4obeMK/phGMRPQVD6ZQYoHG3bcXLHjVsoe2CPFe5DoUcoujq6izhjIyoTaBU1TqPzjG4bdtF4cgJhPY1y1vHF3An2KX2UoeiagyTCllJGwaYalNE0ZjkjToNyIyIhpNEuzWRpUpqFwEQSbKyB/2kfxsY+h22NsvDpGWbqk/6U+Q0USlDwoSVT0C/SUzx7ps2qcW9RZ9clZG7loq1M5jDb0lXESNZYw1CHYny9vzPoNl5Fc9ld8fgLnrdovrDaHl6Jx6IJP6Eh5hw==

RNG Seed: 4280890465

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca9290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca9290, 0x17c8a00, 0x1435400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1435400, 0x1ca9290, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca9290, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
