### ISSUE TITLE
Crash Report 1301050229

### ISSUE THREAD

**Issue by Buenos1227** [wowsims/wotlk#1835]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj0sQ1EUfuf0pb19SK8yPE2b8CZpIrl9L02Y+pg6GJpYjER0MoiNqWkkEguDSJTBaJGIGGgpEQaJRhkIQatIDOInImksnNdnsRlq8w0n5zvnfN+9uecqfobtEIVF2GtYAlgB3AHIAxQBHwC6FAYqtIIJveBFAb5zOQnO2FD/6OAIA+7wbYDi4cUMqo8Bzbm/i9l1VNz8/RI1xwWltfyWeqWA5nirsPszVCcDds/DS8TKpCORpavjD1RY8GoyMYlogbQz/m/q5q+b5JqtKG+oM2ErLWMXf9pEddavyHwqixSPMlbcWrXidtoaOCTFR4DocdoqJtdQYwxETUzug+A0Sv/4gTEnrReHocurMC6btVFnDL2ST2aoDkxCUDeEEOGQYYSEMAwRCgtDp1wPi7ChtwmjTehUpqFQCVQ2X0D+nEP1M4fNdyfYWjxBUb6m/yW/gCsF0gVIKZS0K3RXzk7EzXr7Fo1mU2rOwkGkw67kIy3xCk4j+jI296jsz5c3blbDJXGwVxWf38B+q+4rs9Pm5UgU+uAL75N5iQ==

RNG Seed: 3271404687

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca4b00)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca4b00, 0x17c4000, 0x17f2400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17f2400, 0x1ca4b00, 0x17c4000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca4b00, 0x17c4000)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
