### ISSUE TITLE
Moonkin ad mage sims dosent work 

### ISSUE THREAD

**Issue by Nhex77** [wowsims/wotlk#1836]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
