### ISSUE TITLE
Crash Report -2012012260

### ISSUE THREAD

**Issue by dvmage123** [wowsims/wotlk#1837]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJRqZG1iZAvISaxMLeJgFWCW2sjIxS9weAuTxBtZJbajh5g+7GDi4hT4dIdJifkWkMkj8Hg3k8QjWSXmj0Aeu8BVIK9LFqjlEZDxA6hl3w6wFi6BP8uZJOYIKTEycPEKHAeaN0VGiQUoyQA04sdeJiU2oP59YCM+7GGSWCAHFF51k0limgzEHhaB/n0gcsJOEPlqL4jcuwmkvAFo1i9ZIPfiLpBg0xYmJQ4ORgPuAJYERq0JTAyjAAVUsXEwCjAVMDqJcAGjXoDFgceDLYBJiEGKhYNJIrmLMcLI2MDAwNTA2NAQSIPYKEAXKGcKEjYEqjMyNjY0MDU2NAKpNjY11EVXjQweMUpw/D/LJPD5LJPEyqdMCqcvMWk8ucRk8OMeMB2yfGDknsXIcIuRYRYTg9JdJk6wWxvSHAQhrhZxkJw1EwRO2ltCRC7YK6aBwTV7o7VMCsESHDSP7BYHapjScPIIVcwhBkDCyueugyOE/8PegzGBEQBx3H5L

RNG Seed: 1674343798

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca4a50)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca4a50, 0x17c6000, 0x17c5c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17c5c00, 0x1ca4a50, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca4a50, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
