### ISSUE TITLE
Crash Report 889452849

### ISSUE THREAD

**Issue by frucade** [wowsims/wotlk#1838]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj0sQ1EUfuf0pl5fK64yXE2b1JtEIrl9L02Y+pgkliYWY0WYDCIWJjH4W0iIRBlsJBYSRNBGqMHQpDqIlFBlEBE/EYlYOE8tJgubbzg55zvn++7JvVfzq1gPzbAAqYolgBXAXYAMQB7wBqDJo4KAINaABW3gpUnfCRsCZ7S7vb+zV2Xc4VsFrYznt1HcBXTnwR4mN1Fz8Zcz1B05Sj38inqFgO54pqqETyVRjAdIUiD6lSQ0b3dK+fAWinmvzohQNI2vb6CY9uugkNvTDrnZxmX8kmQjJMsVZSX8fgfFjF9jfCKJFMcSdnxatONtwh6YJMVbgMqjLZscWkNdU0G6o6yNxaB2EpV/fMOAWwWOUeih3wBNXk3lzPI0O6PoVXxMRdExDrWGKaUMh0wzJKVpylBYmgblRliGTaNOmnXSIJqGQgUQ6twF8oc0ivc0Bq+zWJPPonw9pw/GHsEdByUHShwV/RRdnwsMdlnlxVUqrar4rI3DSEORyUSquz5xHDGWMdgq8M9fsM/6DZfBw9QPPi2/co6N4l2N7luNX4QVgw8JQXYj

RNG Seed: 888252936

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca4840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca4840, 0x17c6000, 0x17f2800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17f2800, 0x1ca4840, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca4840, 0x17c6000)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
