### ISSUE TITLE
Crash Report -420222288

### ISSUE THREAD

**Issue by frucade** [wowsims/wotlk#1839]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE78HIwKTAaMASB5xhWMjEJAxVL3WZoY2QJyEitTizjYBBiltjBy8QtM3sMk8UZWie3oIaZ9O5i4OAW+3mFSYr4FZPIITAPKPZJVYt4H5j29ziTRJQuR4xeYCpT7AdQHlANJ8wq8AErPEVJiAfIYgNxJQPkpMlAuj8BHIHeiDMQodoEPQF67LJBxHMiYJsPFIjBhJxOQPL8bRO7fBSJf7QWpPL2bSeKXLJDbABZs3M2kxM3BCPQZSwRrByOj1gQmhlGAAqo4OBgFmCSYChiNpLmAbAlgGshgFGKQ4uXi5vgPA4xdjOqmBsZGBgbGhkamxkACyDE0NjYwNTY0NDI21NU1MjAFShoYGj1ilOBouM8kcH0/k8TN/UwKv+4xaRy+xGRw/BLTC0aWD4zcsxgZbjEyzGJiULrLxAlxRJyDIIQh4iA5ayYInLS3hIhcsFdMA4Nr9kZrmRSCJThoHoktDtQwpeHkEaqYQwyAhJXPXQdHCP+HvQdjAiMAXUN9CA==

RNG Seed: 1872463595

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1c96a50)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
