### ISSUE TITLE
Crash Report -176122169

### ISSUE THREAD

**Issue by casper966** [wowsims/wotlk#1840]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUU1oE0EU3u/tdt0OlYw5jSEpcRGUQmF2l4V6SvTkccFLPBapFPQQiqAWhK0UBC9GjQFDDz0ULHjxWFuTij+U3kpBi0EUc9AgHoyIlJ58u/HiTdDe/Bhm3vu+7z2G98RRhyRpmsBpVFClGKgBi/huPgI9BbaAHnDqkIMiaZQRJS4sA1kuyf2wrsOOLk5enZpxbIlcCyIjP+2Q+lJw7ZfPqL9CYlh+e0uu2eFwRDaekOoWXDMRDshXa6TujnLJPaZ3uaS9QnyEkEttUgtZF4Y4KO+wWM+7FisGe3dbpG7nXbs/8GZknfUbhZTopG03mGjkOag9JhWPcnCrnQaW7D8gvj+3Etsy2/YKnMarCTm3Rq5woBENVYauYKxGxn/8hlnHgSRFVfhZwaNSiDIVTCNr5EgYN3Es1IGvdeB5YRB4ASdeEOiQcz/wxsd9HbKoPb8L5cTvSe6sk3qzTsW9d3T8+TbpjW3qwfoKswklbGE5Hx+aySvrvCB7sL0OjCYZ7gcaHvzpbPlw836CzdKJAbNVOnI+xeuSv0rVhWuzI9HkpXPTl6dmLhT9sHhGOfu+2/nyv+gSb774mz56Yqx68k/N6fDiRrf8q6JX+gnwFoWb

RNG Seed: 4106529115

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x158fd90)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x158fd90)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x158fd90)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x158fd90)
	/home/runner/work/wotlk/wotlk

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
