### ISSUE TITLE
Crash Report 29080088

### ISSUE THREAD

**Issue by Ralfing** [wowsims/wotlk#1841]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztkT1IW1EUx9//8JpcbxGvweEqRuJbKoJw33sEdMrTKYNDwCWjHSoODuJknYIUFCdLGsEgKC7qIIh06KCJ+IEJgoiDoqCCLiIO7RakYO81dHBz0M3/cDgfP845nMNjjAQp6kQSaQxTBpgG1kBbwBFwC/TUM8RIIUDKEFgGIlbTgT2OUGro89cvIywk0DQPXieyGyTvo05ob5sWysRtsVoiHhaFdZLXUe0clkhmWzSY02BFg5oq/CLOxd8lknMRBxavFZWfJH80O7aumDB3RvK7Di1DhsWlJidMs33dY6ZZDyktmlE3j8bebRr7Z8mQKxp4iHJLJyYL5HAGhZSd/jCK9mmy3vVMY4xBkKRheFGuTyWRqktj0Ly6ln9kj/+FKXyKx5WnlO+quO+7vvI91/e177qu73Z0eCqui8r1riFZ5orEaZHkWZFiD5fUtnNMav+YbmH/RjgP6xxWnizngmqetsgMBPXVfRqCxvysUTnRVc0cJVoHnnSS8FYp1ifZm7/xW/AaXTLl3Vfp8xJVb9V7EXRX40oiiX78A09idbs=

RNG Seed: 1956677852

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x15ef290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x15ef290)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x15ef290)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x15ef290)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
