### ISSUE TITLE
Crash Report -1665470995

### ISSUE THREAD

**Issue by Xoiqt** [wowsims/wotlk#1842]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJS6ztLEyBaQk1iZWsTBKMAstZ2Ri1/gwW4miTeySmxHDzHt28HExSnw6Q6TEvMtIJNH4DFQ7pGsEvNnII9dYPI+JokuWaCWR0DhH0AtQPUgLVwCm7cxScwRUmJk4OIVuA+UnCKjxAKUYQCa9nEP0DSQKn6Bh0CZdog2iIHrgAZOkwEy+oGMBjkg4+5mMINFYP8uJiD5ai9I2QSgvl+yQO7vvSDBpi1MShwcjAbcASwJjFoTmBhGAQqoYgNGLlMBo5MQF4cAiwOPB1sAkxCDFAsHk0RyF6OWkbGBgYGpobGxoYGBsbGBoamBsRGQbWRqYGpspGtgrGtgBBQGKjJ8xCjBMfs+k8D7s0wS/88yKTy5xKTx4BKTwY97wNTF8oGRfRYjwy1GhllMDEp3mTjBdjekOQhCXCHiIDlrJgictLeEiFywV0wDg2v2RmuZFIIlOGgeeS0O1DCl4eQRqphDDICElc9dB0cI/4e9B2MCIwBxAnbM

RNG Seed: 1154556293

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c99600)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c99600, 0x1cbaa00, 0x1585600)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1585600, 0x1c99600, 0x1cbaa00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c99600, 0x1cbaa00)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
