### ISSUE TITLE
Crash Report 523248888

### ISSUE THREAD

**Issue by Blazyxx** [wowsims/wotlk#1843]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYFRg0mB0YIxgFGIyYJS6xdLEyBaQk1iZWsTBJcAstYWRi19g8m4miTeySmxHDzF92MHExSnw6Q6TEvMtIJNH4DFQ7pGsEjNIgl1g9y4miS5ZoJZHQOEfQC37djB9BMpwCWzexiQxR0iJkYGLV+D4FiaJKTJKLEATGIBG/NjLBFYIRECdD4E62yE6IWau28ckMU2Gi0Wgfx8TkLy7GUR+XA4iX+0FKZgA1PFLFsj9tRckuHMRkxI3B6MBdwBrBGsHI6PWBCaGUYACqtg4GAWYChidRLiACUCAxYHHgy2ASYhBioWDSSK5i1Fb18DA1NTA2MDA0NDYwMjY2NDA1NjQyMDYyNDY1FAXyDAGSgJFDQyMHzFKcPTcZRL4f5ZJYuVTJoUnl5g0HlxiMvhxD5jAWD4wcs9iZLjFyDCLiUHpLRMn2PqGRAdBiENEHCRnzQSBk/aWEJEL9oppYHDN3mgvU8Gc2iqegMSS5Izy1KJsBSNThWAJDlpH6IdGB2oY03DyCCXmGFhoFTgSqxgceA3THjlAdbywByZ8ANw6gR4=

RNG Seed: 3803143129

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca7080)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca7080, 0x17c8a00, 0x1438000)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1438000, 0x1ca7080, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca7080, 0x17c8a00)
	/home/runner/work

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
