### ISSUE TITLE
Crash Report -1325474555

### ISSUE THREAD

**Issue by patrickwire** [wowsims/wotlk#1844]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJzj4rVg9GA8wMj4gJHxBSOjExsHowSjBqMQg9QtliZGtoCcxMrUIg42AUapjYxc/AKT9zBJvJFVYjt6iOnjDiYuToFPd5iUmD8DmTwC04Byj2QhPHaB3buYJCbLAbVMBQpvkVRiAwrfBspwCbTuZpKYI6TEyMDFKzAJKDlFRokFKMkANO3tLqhp/AJTgDJtsmBtt8AGHgcKTJPhYhGYsJMJSPbvA5Gv9oLIOctACrYAbfwmC+Q27AIJNu5mUgL6xoAxgEVrAhPDKEABVSwcjAJMRlxcTBygyGbiYuhiDDc1MDYyMDA2NDQ1NjY0BnIMjY0NTIF8I2NDXQO8QNfIwBSo1cDQCFPuESPDC0aWD4zssxgZbjEyzGJiULrNxAl2RkOagyDEQSIOkrNmgsBJe0uIyAV7xTQwuGZvtJpJIViCiebxWOJADVMaTh4hYI43VewBAUhYdRx2cIQKOCQwAgDnPmnY

RNG Seed: 972556147

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cce9a0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1cce9a0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1cce9a0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1cce9a0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x1cce9a0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:273

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
