### ISSUE TITLE
Crash Report 2025350530

### ISSUE THREAD

**Issue by DerWhiskey** [wowsims/wotlk#1845]
Link:
https://wowsims.github.io/wotlk/mage/#eJztkU8oRFEUxt935nnuXOQaFncmI95KSr03rylW81jNwmLKxpLEykJ2rCQ2FlJsTBazEDYkRk1E0kgKWVFTJCt/CwvJyn3eBisLdr5u9557vl/nnO7l1YyakEQG+cpFYAW0A5wAl6BroJUzSNTDRQdCZCFS0EdgpPq6BnsGWJEIRObAy0V2nuR91DT2dqmQI66Lu03ixWJijeRFVAVT2yTHowrMZ0lmw6bxlCO1OBdjmyRnQyY0Xib2lbkcNnXlaDwoMnNkBo5zXqGLBZKZGhXcrJJ8jqoGh6ukkOkjhfgdH868/XbLwzOKevGoty0vub5BJmOwSlJ6JxomSfvXFw0ZDIL60RriTOhuadJIUUiL6Ixk9zg6Yo5lWXHLsW11evEXNSpPmTHLVpzjKD/u2DGPc+J243f6s66gXaPoESVpaAVoadLMcwp+TDTc61b4s1W54fSMp4NEs585SdT1fug0EVui2nbJ/vxLR93fqDJ8kP+VOj+R/1Zt526Lf39NJNGJd80vbfQ=

RNG Seed: 1305466465

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cc1340)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cc1340, 0x1d84000, 0x1db6800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1db6800, 0x1cc1340, 0x1d84000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cc1340, 0x1d84000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289 +0x12

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
