### ISSUE TITLE
Crash Report -1596416391

### ISSUE THREAD

**Issue by Spook9** [wowsims/wotlk#1846]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkudgsmD0YJzAyLiA8YjwCkbGDYxMBxgZLzAyPmBkesHI6CTGwSjBqMCkwWjAaMHoAFQawBjBmMAoxGTAKHWBpYmRLSAnsTK1iINJgFlqFSMXu8D2XUwSb2S5OAW+3mFSYr61g4mLR2DnIyaJR7JKzPuAPHaBxi1MEl2yXPwCR4CMLZJKbEDhD0AZXoE2oN5pQkosQAEGIPc4UH6KjBLLBxCXXeDfEyYlRgagvoe7mSTaZcH6PoNNXLcPqE+Gi0Xg8X8mIDlhJ4jcvwtEvtoLUjD3AZPEN1kg99dekOCdXUxK7BxAL3UwMmpNYGIYBSigio2DUYCpgNFJgosPyGJx4PFgC2BSAEa8EIMUCweTRHIXo7aRsYGBgamBsaEhkDbWBbKBHAMDQ6C4kbGxoYGpsaERSNbY1PARowTH57NMAv/PMkmsfMqk8OQSk8aDS0wGP+4Bkxj3B0aWWYwMtxgZZjExKL1l4gQ7oSHNQRDiGBEHyVkzQeCkvSVE5IK9YhoYXLM32stUMKe2iicgsSQ5ozy1KFvByFQhWIKD1pH6odGBGsY0nDxCiTkGFloFjsQqBgdew7RHDlAdL+yBiR8Au+p+VQ==

RNG Seed: 3651229381

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x14e0840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x14e0840, 0x1de1500, 0x1434a00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1434a00, 0x14e0840, 0x1de1500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x14e0840, 0x1de1500)
	/home

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
