### ISSUE TITLE
Crash Report 288253283

### ISSUE THREAD

**Issue by Ryantra16** [wowsims/wotlk#1847]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj1IQlEUfuf4eD5fhjdxuApKvTEQ3g9CTb6cHBqEFscicmqItpoe0eSSa9JgQzQVQWFlJFFGuDU1SA7ZIlFgLYlT5/mWbGqwrW+49zvfOefjcM9VgjJMQRoKAEeAVwBtgJTMSctAFoJCpCNugJRZXlhbWpWBeSKnoATYzQny16gq3V5j9QwVH/t4RNXTIOpnzxfIW1HV06HIyz6Pkeej1FKjli61kOxkFLZXRb4TVEFQRtkdJQ/DqkgOArm9VcjNMQ6wJ3LbjalS1W3zsnIFeSlMpHCO3I4R2ar2icheLpHO932nzCbHXpTCXl8slVGVZNAgK04WUPjHANZ9tFpYoR8AqZCiUCBa/rSUQdq/KCNfzEPWMDVNS2imrtPt8AHEKZdwZJ3qDNPUtYSpG061mdDjP6u/owVCG0Y64CmC0AChiILaRF9/LDtnjbkDhqxwcdtBPTntKvfJiVwfD0njAMfnuPzne920huFi12tD8fkN3LeabVozbtxNpmEevgAWMXIU

RNG Seed: 1509626008

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c9afd0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c9afd0, 0x1caea00, 0x1568400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1568400, 0x1c9afd0, 0x1caea00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c9afd0, 0x1caea00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289 +0x12
github.com/wowsims

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
