### ISSUE TITLE
Crash Report -478375373

### ISSUE THREAD

**Issue by Luckseven84** [wowsims/wotlk#1849]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJS6xtLEyBaQk1iZWsTBKMAstY2Ri1/gwW4miTeySmxHDzHt28HExSnw9Q6TEvMtIJNH4DFQ7pGsEvNnMO/pdSaJLlmIHL/AI6DcD6A+oCaQNK/AC6D0HCElFqAAAxeXwNZtTBJTZJQYGYBGftwDNHIfWNtDoLZ2hDZ2gW27mCSmyXCxCPTvYwKS+5aByMt7QOSH3SAFZ4A6fskCub/2ggSbtjApcXAwGnAHsCQwak1gYhgFKKCKDRi3TAWMTkJcHAIsDjwebAFMQgxSLBxMEsldjFpGxgYGBqaGxsaGBgbGxgaGpgbGRkC2kamBqbGRroGxroERUBioyPARowTH7PtMAu/PMkn8P8uk8OQSk8aDS0wGP+4BExfLB0b2WYwMtxgZZjExKN1l4gTb3ZDmIAhxhYiD5KyZIHDS3hIicsFeMQ0MrtkbrWVSCJbgoHnktThQw5SGk0eoYg4xABJWPncdHCH8H/YejAmMAHmkeA0=

RNG Seed: 4029440035

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1d24840)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1d24840, 0x1d38000, 0x17c5c00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17c5c00, 0x1d24840, 0x1d38000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1d24840, 0x1d38000)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
