### ISSUE TITLE
Crash Report -1523757039

### ISSUE THREAD

**Issue by aligolrouie** [wowsims/wotlk#1860]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj8sQ0Ecft+vL3VOxSnDaVrhTY1Ecn0vTZj6mDoYmliMRJgMYmOSxtSFiEjU4s/AIhEakQiRIGIQYjBIVIOhsahIpLFwTyebgc03fLn7vt/v+13ujocZdSCJJRw3rAOboEPgEiiAikA3Z5CIwkUfgqQQ2jLT8KdGBsaHxpgpfKFZcFPkdkhzcZ94QDzskbyPWL7XXeJVInNCMhPR5uM2cS62d0jOBy0YvFac5kjOhS3zZpcMXi3eV8jy5Y+I14kT7Sw3W37teEKVuN7SbWGdcrHnDZo+8Php3+OXNa+gtEryLcINLaRzZDEGVZMy+9E2Q8Y/vmHCzyBoFN1BzoTpBpL+FAWNkMlIDmbQZjtKqXjMcWJKOY6KxZVj67UdV3HHbldOu7K1rIti95Bs8Y7E8znJj3NqebyiaOGKVDmvP45ZQk0Wxg2MLBnWLVV/zZ4cdusrp2h0m7ILHs4SnRXlMtE6/IXrhL1BLb2S/fnjTbm/kTJ5dvwrOT9B5a56bt2uyr6cSKIfn5KVaRg=

RNG Seed: 2814215258

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca14a0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1ca14a0, 0x17c8a00, 0x143b400)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x143b400, 0x1ca14a0, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1ca14a0, 0x17c8a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
