### ISSUE TITLE
Crash Report -2066885906

### ISSUE THREAD

**Issue by GregBH78** [wowsims/wotlk#1861]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFIHEEU3fdvcxk3kRslxURu5dxGEYTZXQ6S6tZUFhYHNlcFLRQLC0mlVhsJEWw8oxFyWAcbQdBC0dOQRMROLCJKVLA6k8YmetjEv7exSGdhurxi+O+9/x/Dn7EygiRpeoYuFDBMIVAElkCfgD2gArxoEMiQRoB81IEFoNFoOjfHkcwP9Y32vxJJiaYyrJSc2SD103aS259pc5WsOvnrOzmJIy4fyzn2zmwnERkP5eQ2qSubR96zXOURlqO+elk5IDXf6JgsGEzfsT+b/kNTslomNZ2utcdBF+xP2Jz/dp3UXPo2f2qTVNjMRXGtVphy/iPx+aMcueEKqUub6dRyJL5eJ8cS0MibhQcjaC+S8R9/YUwISFI0DM+2eFUK+VQBg9FHqLceid+3wCRas9r3tPZdN+v7rs/E9X2dZe75bkeHp7Nsatc7gxLhKcmDLVKHW5S5PqG2L/ukd/apAvMCiRKMIxglMpxjqouv8TJoiIsnwdPShwi7ueexspdrGajhW85bpEyPEv/8Gd8E95ES7n69l5y7IN5V93HQGfNqrgu9uAGtEn9f

RNG Seed: 3952079828

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1d30bb0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1d30bb0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1d30bb0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1d30bb0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
