### ISSUE TITLE
Crash Report -1913675453

### ISSUE THREAD

**Issue by GregBH78** [wowsims/wotlk#1862]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztUj1IHEEY3ffdeo5r5EZJMcqtXLZJEITZXQ5MdWsqC4sDm6tEC0MKC0llUq0SErDx1ETwsA5pAgEtDHoq/iB2YqEomoDVqY2N5LAx395qkS6F6fKK4Xvvfd9j+GasjCBJmrrQgwJGKASKwDfQOrAHVIAXzQIZ0giQjzrwBWgx2s7NcSTzw4Nvhl6LpERbGVZKzqyQurSd5PYGrS6R1SCvT8hJHHP5SM6yd2Y7iciolxPbpH7ZPPKJ5SqPsBz1NcnKIan5FsdkwWA6zf7H9B1NyWqZ1FS61h4HXbH/web898ukZtP3+ZOrpMJ2Lorfa4Up5z8TnxflyA0XSd3YTCcXInFsmRxLQCNvFupG0VEk4z/+wFshIEnRCDzb4lUp5FMFvIo+QpPVKG7vgQk8zWrf09p33azvuz4T1/d1lrnnu52dns6yqV3vDEqEP0kerpE6WqPMzQ96trlPemefKjCvkCjBOIZRIsM5pYb4Gv1Bc1w8DlpLcxF2c89jZS/35GUNBznvK2X6lPjnz/gueIiUcHfrQXL+BvGuek+D7phXcz0YwG+5On9j

RNG Seed: 3047890275

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1ca26e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/druid.(*Druid).registerWrathSpell.func2.1(0x1ca26e0)
	/home/runner/work/wotlk/wotlk/sim/druid/wrath.go:69 +0x33
github.com/wowsims/wotlk/sim/core.NewDelayedAction.func1(0x1ca26e0)
	/home/runner/work/wotlk/wotlk/sim/core/periodic_action.go:24 +0x4
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1ca26e0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:350 +0x15
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
Sorry about that, fixed by #1859
