### ISSUE TITLE
Crash Report 472947365

### ISSUE THREAD

**Issue by Jaklopio** [wowsims/wotlk#1865]
Link:
https://wowsims.github.io/wotlk/mage/#eJztkjFIHEEUhvd/DnvjqDieIuORBd1KBGFulwOtbrW6wuIgjaUStEohdlqJRISrbD2FpLpEQZBTQdRIirMwIIiChXAqGkgKwVNBLpWZddPYWZguP8PjvZ/HN495I95w6kEGn1Bq/gKsgr4Bh8AF6BfQLzgUOhFgEHHSSHxn07Cz74cnRsY5ZE1iGaJBPhZJXTsus3Y3STB5VyRRL5cKpK4ct+beeDGZ2yOVc0SjLK2TWm9z7dtNMkcIObNNajHuwjKgc5P/bnWZ4VgGUf1Krl2JGmPy7DOpWcfYl4Zc+UtmsrwWxt1CGI93wrhYCNt/mqEeHFN+LIbmxha5nEPXZdkQuubI+q9nmrTNPmkM/XHBJQvqM3aW4laCcVLvcujyfK11Kun7Sa19XydT2vdM7qV0yve6td+tPWObpuQlFF84J3lzQOrxgNp/HFHnxRHp6pn5UKyCWB7WKaw8WW6Zap/unhoNmqIpWoK2/Hyo/XRv5BymO0afdJL2Vqj9reL/fHkfgtegTO2XXoXzEkVvNVAO+qK6ms5gCH8Ag6NycQ==

RNG Seed: 988469297

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x15f08f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x15f08f0, 0x16c0000, 0x177ce00)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x177ce00, 0x15f08f0, 0x16c0000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x15f08f0, 0x16c0000)
	/home/runner/work/wotlk/wotlk/sim

**Comment by jimmyt857** [comment]
Thanks for the report, fixed by #1859.
