### ISSUE TITLE
Crash Report 930528023

### ISSUE THREAD

**Issue by Romulo0727** [wowsims/wotlk#1866]
Link:
https://wowsims.github.io/wotlk/mage/#eJztUj1II0EY3fdlieOqOEaLMcSgW8kdwiRLQKusViksAjaWimhlcdh5VZDjDixUUASDhZVoIWijYuIPooWFIiIWghqighwiik2689usjd0VXnevmffe9+abj5mxIoLakcICDuqXgFXQHnAKFEAPQJcloNAKF70IkUb43BxDMD3cPzo4IiAD4TVYtbKQI/XYZAcP92lnkyxTLubJqpa3bBeb7MArexUyt0VqOsrpItslTnPUS9fIn1yZD9kmK4PlDddnIu+yUr7kyQ54wVp5wpVf/k6/51Oe1GyEyeQOqUyUyUauTEz5e9sbZHfLiy1zbCJqGWwsrJMtBHRV2uzDlyky/uMDvvPlSOrFN3SFLCFNtzoVTFPICJuC1MA4vsYdrXVCO06MV6eNOQutY+w7DpOEE4t7hpOIFaHE6zHJP8eklu+p+e6MWgtnpEvX/LXMZ1RkYVzCyJJhX1Fl+fjMkFvnD9LgNmbnPBwlO3znNNkyVMZFMr5CzT1K/PP3++F+RpfM0cGn9Pkb+HfVfeV2+rqUTKEPb+SpdNE=

RNG Seed: 4192803988

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x158f290)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x158f290, 0x1516a00, 0x17ed800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17ed800, 0x158f290, 0x1516a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x158f290, 0x1516a00)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by jimmyt857** [comment]
Thanks for the report, fixed by #1859.
