### ISSUE TITLE
Crash Report -594314815

### ISSUE THREAD

**Issue by Clicknut** [wowsims/wotlk#1867]
Link:
https://wowsims.github.io/wotlk/mage/#eJztkj9IAzEYxe99PdprLBirQ1pUtJMIQnpHQaeeTh0cBBfHiujkIG46FREHJ3GzVuiiuFhEHQq1IqJDB0EcHIT6rx2Ki4ogxUHN9SY3B918ZPjlJXlf+BLWblA/EsjitHUb2AUdAxfAHagGDDEDAj2wMYYgSYQL+gK8I9Pjc5OzBrgnvAEW4C/7FPGendBrnpjOa0Vifl4pUMTjGqU9Yj7+kSdxEGKMrxZIZIIRaIoPFedCDgd4vahSrvOkBmvm92plqaNhOCk+njsikQ0pqHySSHUqqLqg88yWU+ax6GxbUefeOpimjPdNFWhANiXRu0Lav75pXrWG0wyGgszguh1IeEcoqIV1g8TEMnpNS0oZi1pWVErLktGYtEzFZkzGLLNPWn3SVLbaFH2AMNZviT+dk/g8p67qJfXcXZKs36gfpD/Dl4Z2DS1NWqRM/kbt1JTd4t6izQ6l1xyV4gOucxHvnmroKm7uUNeoMP788Rbt30hJlU5/Jecncns1XLYH3Xk9nkASX8HSbfQ=

RNG Seed: 387057758

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1c9f1e0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1c9f1e0, 0x17c6a00, 0x1438800)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1438800, 0x1c9f1e0, 0x17c6a00)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1c9f1e0, 0x17c6a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289 +0x12

**Comment by jimmyt857** [comment]
Fixed in #1859, thanks for the report!
