### ISSUE TITLE
Crash Report 2082041798

### ISSUE THREAD

**Issue by Ouotentote** [wowsims/wotlk#1869]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjkuFgsmD0YFzAeER4BSPjBkamA4yMFxgZHzAyvWBkdOLiYJRg1GB0YIxgFGIyYJR6xNLEyBaQk1iZWsTBJMAstYaRi1/g42YmiTeySmxfDzFd3MHExSKwbA8TF4/AsS1MEvdklZg/A8XYBSbvY5L4KAtU/WwRk8QWSSU2oDBINZfAr8VMEtOElBgZgOyt25gk1kmC2DwCP/YyKbFN3cG0D6iKX+Ao0LQOoCVA3kewgdc2MUl8kgXa9vg/yM7+fSDy7XUQ+WovSMHcB0wS30AKNt0ECTZtYVLi4GA04A5gSWDUmsDEMApQQBUbB6MAUwGjkxAXhwCLA48HWwCTEIMUCweTRHIXY4SRsYGBgamhsbGhgYGxsYGhqYGxEZBtZGpgamxkoGsAksYBdA2MgDqACgyxSD5iZHjByPKBkX0WI8MtRoZZTAxKd5k4wS5qSHMQhLhNxEFy1kwQOGlvCRG5YK+YBgbX7I3WMikES3DQPEpbHKhhSsPJI1QxhxgACSufuw6OEP4Pew/GBEYA9htyUQ==

RNG Seed: 522411193

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 16 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xdf020, 0x1122690})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x0, 0x1cab3f0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:494 +0x2
github.com/wowsims/wotlk/sim/mage.(*Mage).registerMirrorImageCD.func1(0x1cab3f0, 0x1d9a000, 0x1dcc600)
	/home/runner/work/wotlk/wotlk/sim/mage/mirror_image.go:36 +0x8
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1dcc600, 0x1cab3f0, 0x1d9a000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x1cab3f0, 0x1d9a000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:289

**Comment by Watcher7** [comment]
Your browser might have a cached version of the site from before this bug was fixed. Try using ctrl while clicking the refresh button.

**Comment by jimmyt857** [comment]
Yep this was fixed in #1859. Thanks for reporting!
