### ISSUE TITLE
Miscalculating melee hit

### ISSUE THREAD

**Issue by msinger92** [wowsims/wotlk#1873]
**Describe the bug**

The melee hit on this gear setup adds up to 215, but the site is showing 313. 

**To Reproduce**
![hit](https://user-images.githubusercontent.com/118706363/202961203-464e487a-ec63-4ef4-9704-a9df8c9d3359.PNG)

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
That panel also shows hit from talents/consumes/debuffs. If you mouse over the magnifying glass you can see a breakdown. If you think there is still a problem, could you include a link to your settings?

**Comment by msinger92** [comment]
I was forgetting the Nerves of Cold Steel talent. Big dumb. Ty!
