### ISSUE TITLE
Wow shadow priest sim

### ISSUE THREAD

**Issue by Dopimine** [wowsims/wotlk#1875]
When using the sims on safari to fire fox. There is a large difference in the result. For the hunter it’s about 600 dps for shadow priest it almost 2k. 

I have trouble shooted this all I can I made sure everything was same. I reuploaded the sim import and rechecked. 

the sims last week were exactly the same result minus the margin of error. 

Could you please advise. I have sent a lot of people to the sims. I would hate to be proven wrong that they are the best for upgrade choices. 

I know apple products and browsers are not main stream but with wow being optimized for the new Mac chips, a lot of people are starting to play on Mac. 

thanks for your time

**Comment by psiven** [comment]
This sounds like you haven't cleared your cache from yesterday morning's bug. Ctrl F5 should do the trick.

**Comment by Dopimine** [comment]
@psiven i have cleared the cache clear all website date reload reimported there is still a huge difference between the two browsers

**Comment by Dopimine** [comment]
![Image 11-21-22 at 2 38 PM](https://user-images.githubusercontent.com/118423144/203144372-0c025be7-903f-4b2e-b7d2-ce98217d3248.jpg)
![Image 11-21-22 at 2 39 PM](https://user-images.githubusercontent.com/118423144/203144379-3388adfb-9e18-4fd1-979c-2dfa3027748a.jpg)

**Comment by Dopimine** [comment]
@psiven  FIXED It wasnt the cache for some reason the json export that I was using from safari to firefox to equalize them was not setting thing properly. So I did a json export from safari to firefox and it fixed it
