### ISSUE TITLE
Idol of the Crying Wind is not affecting sim damage

### ISSUE THREAD

**Issue by JosiahParry** [wowsims/wotlk#1879]
**Describe the bug**

Idol of the Crying Wind (ICW) increases IS spell power by 374. In the sim damage from IS is unchanged when using ICW compared to Shooting Star

**To Reproduce**

1. Go to balance druid sim
2. choose a preset
3. run sim and inspect insect swarm damage
4. apply ICW and rerun sim compare IS damage

**Expected behavior**

It is expected that IS damage would increase when using ICW

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by brandonBartosek** [comment]
Looks like this issue should be resolved by #1885
