### ISSUE TITLE
Mage trinket EP(+/-) values doesnt rank properly

### ISSUE THREAD

**Issue by Clicknut** [wowsims/wotlk#1880]
**Describe the bug**

**To Reproduce**
1. Go to 'mage'
2. Click on a 'Trinket'
4. See error: Mage trinket EP(+/-) values doesnt rank properly

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Trinket EP is weird because most of the power is in procs/effects that can't be directly measure. So instead we don't show an EP and sort by ilvl.

**Comment by Clicknut** [comment]
♥️Den 22. nov. 2022 kl. 15.10 skrev James Tanner ***@***.***>:﻿
Trinket EP is weird because most of the power is in procs/effects that can't be directly measure. So instead we don't show an EP and sort by ilvl.
