### ISSUE TITLE
Suggestion: Social Links (GitHub, Discord, Patreon)

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/wotlk#1896]
# Overview
Links to the Discord server, GitHub repo, and Patreon could help increase engagement and support, and are pretty standard parts of open-source projects. Let's advertise them! 😄 

### Homepage

Links could be added below the various class sim links as seen below. It's important to provide a larger margin between the two to provide separation.

<img width="1728" alt="Screen Shot 2022-11-22 at 9 25 54 AM" src="https://user-images.githubusercontent.com/12898988/203339074-2315ec38-1fce-41c9-a3c5-c616401c4143.png">

## Sim UI
This one would be a bit harder to fit into the UI, but I think we can do it. There's a couple of different ways you could approach it.

**Option 1**
There's already a Patreon link in the right-hand top toolbar, so it's a perfect place to include them! We'd want to provide a little bit of separation from the more functional buttons with a small divider.

<img width="1728" alt="Screen Shot 2022-11-22 at 9 34 52 AM" src="https://user-images.githubusercontent.com/12898988/203341509-e125faff-f118-4f7b-ad8a-29e304eed086.png">

**Option 2**
We could add links in a separate footer element that's accessible via scrolling. This would give us the most room to work and is probably most commonly used. It would enable us to include the logo/homepage link and other content as well.

<img width="1728" alt="Screen Shot 2022-11-22 at 9 42 18 AM" src="https://user-images.githubusercontent.com/12898988/203342927-cc6085b9-04e2-4ecf-9452-73b6446c670b.png">

**Option 3**
Socials could be fit in below the left-hand stats table. The problem with this approach is that many specs have significantly larger stat tables that affect them, and already have shrunken font sizes to deal with spacing issues.

<img width="1728" alt="Screen Shot 2022-11-22 at 9 29 45 AM" src="https://user-images.githubusercontent.com/12898988/203340043-12596682-e703-49a2-b607-e484490e18ff.png">

**Comment by lologarithm** [comment]
My vote would be the homepage probably just to keep as much space as possible in the sim for sim stuff. Header bar with patreon link would be second best imo
