### ISSUE TITLE
UI: WoWSims v3.0

### ISSUE THREAD

**Issue by kayla-glick** [wowsims/wotlk#1899]
Documenting the v3.0 UI discussions from the Discord server.

# Overview
`@Nord` on the Discord server put together some amazing mockups for a revamped UI featuring cleaner, more-modern styling. This issue is documenting the conversation and can be used to divide up the work.

From `@Nord`
> WoWSims 3.0. Revamped an old concept but I took the existing structure and worked on that to make it more feasible rather than a big overhaul. I've been wanting to make an updated visual for quite some time now. Not by request but just for the passion of making.
>
> It consists of many subtle changes that gives a bigger impact. Working with more marginals of the elements so the content gets more room. Bigger changes are more suggestions of dividing sections of DPS and Stat Weights in the left columns and moving the stats to the right together with the gear. And a re-design of the headers. Making the Import and Export more visual and not as hidden as now with the Addon is a big feature of the WoWSims. Note that not every single detail is correct because its not necessary for a concept.

# WIP Mockups
![image](https://user-images.githubusercontent.com/12898988/203389113-f6dcebf0-c90a-4033-9ec3-bc1e8d848f0f.png)
![image](https://user-images.githubusercontent.com/12898988/203389135-5bb39fd2-e788-491a-9cf5-e47fd318971d.png)
![image](https://user-images.githubusercontent.com/12898988/203389149-ac35cd8a-a839-4ab9-a767-c6b6f0f778c4.png)

# Additional Discussion Points

> @Pokpoong
> Love it! Some initial thoughts:
>
> 1. Really like the header navigation changes. These are also easy enough that I might be able to get them done in the next few weeks.
>
> 2. Gear Stats isn't a good label for the stats section because it includes all stat sources, not just from Gear.
>
> 3. Moving the stats out of the left-side panel will make it not visible while in the other tabs, specifically Settings and Talents. It's important that it still be visible while viewing those tabs because stats can change depending on buffs/consumes/talents/etc and being able to watch the stats change when various settings are toggled is a very helpful sanity check to improve trust in the sim.
>
> 4. We have enough problems with EP already so we'd rather not make it more prominent. 🙂 
>
> @lologarithm
> big agree with making stats visible from all input tabs because they come together (gear+consumes+talents) to make the stats

> @Lucenia
> What do y'all think about putting sigil below off-hand and adding a bit of separation between Wrists and Weapon+Offhand+Sigil? Keeps it a little closer to the in-game UI. I've gotten tripped up a couple of times because of where sigil is
>
> @Pokpoong
> Not specifically against this but again, on smaller screens (even typical laptops) we already have a vertical scrollbar. If you can do this and pair it with some better size adaptations to avoid having scrollbars then sure
>
> @lologarithm
> I think having some visual separation for the weapons/ranged slot would be good

**Comment by jarveson** [comment]
this looks to be all set now?
