### ISSUE TITLE
Errors in console when changing items

### ISSUE THREAD

**Issue by lologarithm** [wowsims/wotlk#1903]
Open link, click on helm, get exception.

Uncaught TypeError: t.getAttribute(...) is null
    s gear_picker.ts:797
    removeTabs gear_picker.ts:797
    m gear_picker.ts:569
    b gear_picker.ts:573
    addTab gear_picker.ts:522
    setData gear_picker.ts:267
    Ls gear_picker.ts:255
    t gear_picker.ts:123

http://wowsims.github.io/wotlk/elemental_shaman/#eJztUj1IHEEU3vd2vZsblJsckowHC+tqIYHA7C4LhhQ3SWUgxQWbK/0hVhYhXaxEbHJVLD1SWKVSsbCQMxiRC+EiMZeACv4VgmCh4RAEMY1vd7GwS6GdH8Pje2++72MYHhcMe6EPZmDp0QJgA+BFKwMJDvaAhhLkjPxUywSkiqOD79+8YxmRzs8Cz4raF5Qntpv6toa7S8gz4nwPXXOFaFocVFEe2rxVHG2jLNuuGSmyYo0sF2SZqSMd3iYml1F+yrkWdQbn4i/Z5jtcMCjttEppG3Fak2wfbCLfiZzZ3BIrn5Hqr+WoNuP6tRop1ynvMlL+JnLMaL5OMYyBgqJVann8EY173MBYioHAtzD0jHt5TtyU6NB3MRTwMlaMF3UJXidU617aicG4WR3StBoWWaAMXSoMfKW80A98zw9CL/D9QHlEnigVqtBXgXcIki3WUDSOUK7W0Pl3gD2Xf1D93MRjsJqQrkAXz3KTbTzMseR1juaCW6zxw7yedOsdMCpouPuYiQcDw/pBctWuOyrTEeqFp8mkUegcibFV8OfQ6ZfszjdgUt9Gyni9dis5/4Pkr17t6+dJf1HogwG4AsA/d5k=

**Comment by jimmyt857** [comment]
This error doesn't reproduce for me

**Comment by jimmyt857** [comment]
My recent change #1930 fixed this.
