### ISSUE TITLE
Changing Gear/Gems Cumulative Lag

### ISSUE THREAD

**Issue by blooblahguy** [wowsims/wotlk#1910]
**Describe the bug**
Changing gems or gear slowly adds more and more lag into the sim. Switching gear or gems goes from a near instant interact to something that take 5 seconds or more,

**To Reproduce**
1. Go to any sim gear set
2. Click on each item and swap gems multiple times, go to the next item and repeat. Or swap items multiple times.
3. Every change adds more and more lag to the interaction. By the time you reach the last piece changing gems takes 5+ seconds (i'm on a 5950x, I assume this is much worse for lower end cpus)

**Expected behavior**
The time it takes to change gear/gems remains consistent.

**Desktop (please complete the following information):**
 - OS: PC
 - Browser: Chrome, happens with both localhost and wowsims.github.io
 - Version 0.1.5

**Additional context**
Refreshing the browser resets the issue, and gem/gear go back to being a near instant interaction.

**Comment by kayla-glick** [comment]
At a quick glance I wonder if this is because of event handlers being added and not properly cleaned up?
