### ISSUE TITLE
Missing items: Blade of Unquenched thirst SIM for enhance shaman

### ISSUE THREAD

**Issue by dragonlordx** [wowsims/wotlk#1927]
[Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:](https://www.wowhead.com/wotlk/item=31193/blade-of-unquenched-thirst)
was very popular in the private server scene past naxxramas for a fast speed alternative that dealt 100% dmg with your spellpower, would like to see how it does in a sim, been trying it abit in t7 and been getting varied results between 70-200 dps from the proc alone. would be awesome if you could add it =)

**Comment by jimmyt857** [comment]
We had an implementation for this in the TBC sim, and the proc rate was 2%: https://github.com/wowsims/tbc/blob/master/sim/common/melee_items.go#L768

That's definitely not enough to get 200 dps out of it even with a specialized build. Do you have a WCL log, and some data on the proc rate?

**Comment by dragonlordx** [comment]
https://classic.warcraftlogs.com/reports/jg3LyGrxNXtYzDbF#type=damage-done&source=8&fight=28
https://classic.warcraftlogs.com/reports/jg3LyGrxNXtYzDbF#type=damage-done&source=8&fight=36
https://classic.warcraftlogs.com/reports/jg3LyGrxNXtYzDbF#type=summary&source=8&fight=40

these were the only old logs i could find
I was in shit gear when I used this dagger because I had no other weapons will do another raid next week with it equipped to see how much dps it does now =) as you can see the dps is very varied if u dont get an average proc rate. 2% is accurate with the testing I did with it before. currently hitting a dummy to confirm will send screenshots soon

**Comment by dragonlordx** [comment]
https://gyazo.com/7f401654933e09e0d6cda4c5d8c67ca4
proc rate still 2%
