### ISSUE TITLE
Tempo for The Cooldown

### ISSUE THREAD

**Issue by AnitaSinha** [wowsims/wotlk#1931]
the tempo is not taken into account for the cooldown times of the spells...

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Hey thanks for the report, the description is pretty vague though. Could you clarify what the ask is here?

**Comment by AnitaSinha** [comment]
> Hey thanks for the report, the description is pretty vague though. Could you clarify what the ask is here?

mind blast has a cd time of 8sec, due to my tempo rating the cd is currently reduced to 5.5sec which is not taken into account according to the timeline, it is only cast again after 8sec.

**Comment by jimmyt857** [comment]
Could you provide a settings link to show the issue? Export --> Link

**Comment by jimmyt857** [comment]
Ah, there's no bug here, this is just the rotation logic. The sim doesn't cast MB immediately off cooldown because its a DPS loss. If you look closely, you'll see that the time between casts is still often < 8s.
