### ISSUE TITLE
Warrior Tier 7 set bonus not activating 

### ISSUE THREAD

**Issue by fearnotbaby** [wowsims/wotlk#1934]
**Describe the bug**
Using the downloaded sim tool I could not get the warrior Tier 7 set bonus to function. In the live web tool they function as normal this is only a bug for the downloaded sim files. Screen shot below

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 0.1.5

![Screenshot (7)](https://user-images.githubusercontent.com/96964204/204059218-f5d6315c-ca17-40c1-960d-1d792fb63f43.png)

**Comment by jimmyt857** [comment]
Downloaded sim does not have the latest updates; I believe @TheGroxEmpire fixed this in an earlier PR. We'll update the download again sometime in the next week or two, thanks for the report!

**Comment by fearnotbaby** [comment]
ok that would be great! the downloaded sim is just so much faster and all around smoother to run
