### ISSUE TITLE
Simulation iteration issue

### ISSUE THREAD

**Issue by strider209** [wowsims/wotlk#1941]
**Describe the bug**
When I attempt to run the simulation after setting up all my gear, it will only go through 1 iteration (using Firefox). I can only rerun it if I refresh the page. If I don't refresh and try to run it again it just thinks and never provides any results. I have set it to run 3000 iterations but it simply won't do more than 1.

**To Reproduce**
1. Go to the website and enter all your gear/spec/etc.
2. Click on SIMULATE

**Expected behavior**
It used to run through all 3000 iterations and return a good number with which to judge whether or not an item is an upgrade.

**Sim Links and Screenshots**
I've attached a screenshot that shows an unusually high dps number after going through only 1 iteration.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 107

**Smartphone (please complete the following information):**

**Additional context**
I've tried running this in Microsoft Edge and it works. However, if there is any kind of update or fix for Firefox I would prefer to continue using it since that is my browser of choice. It was working in Firefox up until about a week ago.
![Sim Error](https://user-images.githubusercontent.com/16285774/204067963-eba0b8d1-240c-459d-aa62-4551108fa85c.png)

**Comment by lologarithm** [comment]
Hi @strider209 could you give me a link to your setup? I use only firefox for all dev work and it works for me on both desktop and mobile firefox.

**Comment by lologarithm** [comment]
You could also see if there was an exception in your console (if you know how to do that)

**Comment by strider209** [comment]
Not sure how to do that, but it's working now. I don't know if a recent
firefox update fixed it but I tried it a few days later and didn't have any
issues. Thanks though!
