### ISSUE TITLE
Marksman hunter talent Rapid Killing bugged

### ISSUE THREAD

**Issue by Brotherbert** [wowsims/wotlk#1945]
**Expected behavior**
Taking points in the Marksman Hunter talent Rapid Killing should increase DPS when fight times are set between arouund 210-330 seconds

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.]
Points in Rapid Killing:(https://wowsims.github.io/wotlk/hunter/#eJztU89rE0EU3vc2TWaXSsYgZRs2ut1LQ6Eyu8NC42XXeukx4MWjRSqCIqEI1YJQi0Lx1IOWGAR7EXoRPIhYMSjowYrRECH+Qqht2kZaMaJ/gG93q+hNUG9+8A2z3/u5jze6yZCjwCEo4iE4DCWcAbwJWAdoAwz3MLAwDwGchhmAeYAFgDJiRsmud01Dsnhi9MzYOEtxzL4FPc3vt9H4kLOTtx9i9Q7qGq+toq2G127+9T0ayzlb3aSvNK9voHHZtJNki4Uqhd7qjYTQfwe/sY7Ghd12gsyKnuHnV9G4ZNpabK9GMZ8p+09Chi+T06ecrW1GwrNa6HSP6s6ZPxJrfKG13ZPGZ7+3l+DvXodncwP1FL9Lab7kdIWu0y00yqadZiggmlEimsTALCr/8QsmGQOOBpZg34R+YATyyGBnZAmuBcOWjqyLmCJqREbUiSoRieBUroRY9AsywguflmwvLeeebA+dQEuojqhlgAegPgZ4BdAX1+34hdrTEFv+Rej3hDsoHE8Kz5GOK4VwpCulkJ6QDmmDniBIdwUMNv8c+fU1NBZbaL1sYP5JA0WzgW1IdECrgPIGlAoq9kfU4kIng/h3lF1Bb9zskl+IlbrfdzRC03erWLp6drK7OHrqyLGJsfHjlutZBw32rzemcy74G2mmlh79SR4xNFDa/7vO0fCm5laC7Yi2Ty/rG1WUp8k=)

No talent points in Rapid Killing:
https://wowsims.github.io/wotlk/hunter/#eJztU89rE1EQ3plNk7dLJc8g5TVsdLuXhkLl7S4LjZdd66XHgBePFqkIioQiVAtCLQrFUw9aYhDsRehF8CBixaCgBytGQ4T4C6G2aRtpxYj+Ac7uVtGboN784Hu8Nz++mR1mdYMhR4lDUMRDcBhKOAN4E7AO0AYY7mFgYh4COA0zAPMACwBlxIySXe+ahmTxxOiZsXGW4ph9C3qa32+j+JCzkrcfYvUO6hqvraKlhtdu/vU9iuWcpW7SK83rGyguG1aSfLGhSqm3eiNDGL+D31hHcWG3lSC3omf4+VUUlwxLi/3VKOczqf9kyPBlCvqUs7TNyPCsFgbdo7pzxg9hjS+0tnvS+Oz39hL83evwbG6gnuJ3SeZLTlfoOt1CUTasNEMJ0YwS0SQGZlH5j18wyRhwFFiCfRP6gRHII4OdkSe4FgybOrIuYoqoERlRJ6pEJIJduRJi0S+4EV74tGR7aTn3ZHvoBFpCdUQtAzwA9THAK4C+uG7HL9SehtjyL0K/J51BaXuu9GzXlq6Utuu4rnQ9SU/PHvQkwXVWQLD558ivr6FYbKH5soH5Jw2UzQa2IdEBrQLKG1AqqFgfUYsLnQziz1F2Bb1xs0t+IbbU/b6jEZq+U8XS1bOT3cXRU0eOTYyNHzcdzzwo2L/emM654G/ITC09+hMdOTRQ2v+7wdHwpuZWgu2Mtk9/1jdSLKfH

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 107

**Comment by jimmyt857** [comment]
Thanks for the report, but next time try poking around before assuming a bug. If you go to Detailed Results --> Timeline, its obvious why this is happening: the 2nd cast of Readiness is used to reset Rapid Fire, rather than waiting for Rapid Fire to refresh normally and then use Readiness to get a double usage.
