### ISSUE TITLE
Crash Report 283625784

### ISSUE THREAD

**Issue by sainth0rse** [wowsims/wotlk#1950]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztVM9rE0EY3fe5JtOxpaOnaWjKungokcDsjgEFYVf/goCXHlukItRDLIK0IEShUBS0B6lpFK+WnvxFjaFCIR7MQc0h7UE8SEFJ0WBuFj3Y2U1b8CaoN9/hm5nvve99w8ww/CgjQcMYQYFmgUXgIagCrAKvgAbQArZADaI5wmnhkEJoxKMoxuJDVmpm/zUk8hfGpsYnWVLw1DPwfrFUI7mZdhPLNXrzmniP2HpP7r6VCvFe0V4h+SHdXSVFtUryW9qUfDLppwNu4n6dIoaLR8skZ4ZcWLxPtAx5e9C1axWyjMV6lfaE/eKLIb+m9xJJcdN4zg9yW9x4TiZuPoniajWKn99Gggdme0spM/nxmORiyuRvGUfGSPXl7RE7M0fWf/yC6QSDpFF8x0k+VAIYFPK42CU7wVQ8ztbCSvwm5MFdwkHmAPu5C1xHVnlZ7Svl65zSx3xfaeX5Wimltac8nfOyZmV4rXImbECyu00Sd5ok2x/JKTVpuLRGamGNWrA7SJZhvYNVJsttU0/cszgR7nQ/Eg6UFyLUgxPdTCM4fC7GeuC/oMK9K9O9+bFLZ89fHp+ccPycc0ayf333navh37Ap1l/+iY86nimc+l1xfHjF+Y1wp6IVmJ9iGxJfk0Y=

RNG Seed: 3234345748

you can't unh sub without ERW in the opener...yet
Stack Trace:
goroutine 63 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbb100, 0x2c2d60})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).SetupRotations(0x1498b40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:163 +0x98
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Reset(0x1498b40, 0x1581ef0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:300 +0x20
github.com/wowsims/wotlk/sim/core.(*Character).reset(0x17e6a80, 0x1581ef0, {0x2c7d10, 0x1498b40})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:359 +0xf

**Comment by enhancedgore** [comment]
the error message says "you can't unh sub without ERW in the opener...yet"
because there's no code for non ERW opener for frost sub unholy yet.
