### ISSUE TITLE
Owlkin Frenzy

### ISSUE THREAD

**Issue by biogopher** [wowsims/wotlk#1952]
**Describe the bug**
Owlkin Frenzy does not show in the buffs under any setting or iteration

**To Reproduce**
1. Go to 'Talents'
2. Click on 'Owlikin Frenzy and run the simulation for any number of iterations'
3. Scroll down to 'Detailed Results/buffs'

**Expected behavior**
Owlkin Frenzy should proc at some point during Thadius/Lotheb/KT, My character Skahn in westfall has it procing 6/3/1 time(s) respectively due to aoe damage taken during those fights

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jarveson** [comment]
`Owlkin Frenzy Uptime` in settings was added for balance
