### ISSUE TITLE
Crash Report -1323761819

### ISSUE THREAD

**Issue by simonizeshow** [wowsims/wotlk#1956]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJzjUuJgEmAyYMpgLGBsYGRcwci4gZHxACPjBUbGF4yMPxiZLjAxOQkoMBkwOjBGANV0gNUIMUj9ZWliZAvISaxMLQKawCW1iZGLX+DZdSaJl7JKbNsOM507y8TFIvB3MxMXj8DbPUwSD2SVmPfsYOJiF7i8m0niuyxINVD4B1D1vJNMIBlegS6gTKucEguQxwDkzgZyp8hAuTwC13YxgdUCEdCUZ7uYJN7LAoVnbWOSmCYDMZxF4OVmENm9E0T2LQGRr8+DlF8CmrVCCshYvQfMYBH4c4ZJiZ+DyYDXgjGAJYKlAuQ1rQlMDKMABVSxcDBKMP1iNOUSn8HIKABMBh6MAYyJYDmHfocd4MQgIQhR/MFegVGLm+M/DDB2MeoYGOoaGxkYGBmbGhibGhkZGBsYGhkbGBgYGxsaGBqb6gI5QGljA1Mg8YhRgmP2FSaB6VeYJN4+ZVKYcYVJY8ZVJoOZV5leMLJ8YGSfxchwi5FhFhOD0hUmToidcQ6S1SLr3B9WLbG3hIhcsFdMA4Nr9kZrmRSCJThoHq8tDtQwpeHkEaqYQwyAhJXPXQdHCP+HvQdjAiMAhpyD+w==

RNG Seed: 599767374

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xe0160, 0x1132320})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).applyRime.func1(0x1f83340, 0x1f5c0b0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_frost.go:130 +0x3
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0x1f83340, 0x1f5c0b0)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:592 +0x126
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).newObliterateHitSpell.func1(0x1f5c0b0, 0x1787500, 0x17c5400)
	/home/runner/work/wotlk/wotlk/sim/deathknight/obliterate.go:63 +0x66
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x17c5400,

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1987
