### ISSUE TITLE
Feature Request: SV Hunter Lock and Load Usage

### ISSUE THREAD

**Issue by JustAeion** [wowsims/wotlk#1961]
Is it possible to have a toggle button in the settings for hunters that when 'Lock and Load' procs from survival tree, it would then use rank 4 - rank 3 - rank 4 Explosive Shots? 

As I can see on the detailed results - timeline, it only uses Explosive Shot - GCD filler shots - Explosive Shot - GCD filler shots - Explosive Shot.

You could name it 434 rotation. I'd like to see the difference in DPS between the normal LNL usage and 434 rotation. Thanks!

**Comment by jimmyt857** [comment]
This already exists, its the `Allow ES Downrank` option in Settings --> Rotation.
