### ISSUE TITLE
[Feature Request] Delay debuff uptimes

### ISSUE THREAD

**Issue by MikaB07** [wowsims/wotlk#1964]
My raid isnt the perfect at getting the debuffs up fast (95% or lower in some cases)

Would it be possible to add a time (like the buffs) in which you can specify the delay the debuffs come up.

Considering the fact that debuff uptime is 100% in the sim currently.

Im curious as to how much dps loss it is in different uses cases etc.

**Comment by jimmyt857** [comment]
This is now doable using the raid sim + APL. Exposing specific options in the individual sims for every debuff would unfortunately add too much clutter to the UI for a niche benefit.
