### ISSUE TITLE
Eternal Earthsiege/Earthstorm Diamond not granting bonus block value for tank sims

### ISSUE THREAD

**Issue by Winfrieda** [wowsims/wotlk#1966]
**Describe the bug**
In the paladin and warrior protection sims the 5% block value increas of eternal meta gems is not applied at all. I confirmed in both sims by changing the default austere gem to eternal and confirmed that the conditions are met by checking increase in defense rating in the character stats in the lower left.

**To Reproduce**
1. Start protection warrior in P1 balance preset or paladin in preraid set.
2. Note that warrior is equipped with austere meta (Stamina and 2% Armor) and Paladin with eternal meta (def and 5% block value)
3. Check character stats before meta change.
4. Change warrior meta to eternal to see defense increase but not block value.
5. Change paladin meta to austere to see defense decrease, block value stay the same but armor and Stamina increase.

**Expected behavior**
Block value should be properly increased by 5%.

**Sim Links and Screenshots**
Since presets are used, this should be fine without screeshots, as it is easily reproducible.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version 107

**Comment by psiven** [comment]
This is a display issue, no modifiers apply to the stats shown on the sheet but the effects are present in the sim.

**Comment by Winfrieda** [comment]
You're right. I didn't check the results. Thanks for the quick reply. Case can be closed if you like, or maybe the display issue could be fixed and tracked here. I don't mind since i know now.

**Comment by jimmyt857** [comment]
With some recent core changes we can now surface pseudostats in the UI. Fixed the visual bug!
