### ISSUE TITLE
Level 80 Nightelf warrior base stats wrong - Reason unknown

### ISSUE THREAD

**Issue by Winfrieda** [wowsims/wotlk#1967]
**Describe the bug**
Using a night elf warrior at level 80 with identical gear on wowsims is not showing the same base stats. Notably block value is far off, but also Armor and HP is off, as well as Dodge. Dodge could be off by calculating avoidance according to TBC and not reworked night elf racial, which is now 2% enemy miss chance.

**To Reproduce**
1. Open this 80 upgrades link. This warrios stats match the live server perfectly, screens attached: https://eightyupgrades.com/set/w48JkrPq9bLfg9uMD5BtCg
2. Click three dots on the upper right of the character display (above gloves)
3. Click on export
4. Import into wowsims protection warrior sim and check if all raidbuffs are deactivated, talents on standard preset and race set to night elf
5. Note that stats are different between 80upgrades and wowsims.

**Expected behavior**
Stats should be the same as 80upgrades, since 80upgrades matches live server perfectly. See screens below and matching stats between live and 80upgrades, but disparity of both and wowsims.

**Sim Links and Screenshots**
![Winnfrieda_live](https://user-images.githubusercontent.com/119366386/204401018-ec02f77b-9029-4d25-b90a-05e18a18da35.png)
![Winnfrieda_live_melee_stats](https://user-images.githubusercontent.com/119366386/204401041-59de60a4-1598-4fa3-ad11-d36769bcfd5b.png)
![Winnfrieda_80up](https://user-images.githubusercontent.com/119366386/204401064-b02957dc-6fb0-4004-afa2-76c2c7cf0537.png)
![Winnfrieda_wowsims](https://user-images.githubusercontent.com/119366386/204401073-ee32969d-932b-4f5a-9cfc-6ef7c764745e.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 107

**Comment by Winfrieda** [comment]
Additional screenshot of 80upgrades with melee stats visible

![Winnfrieda_80up_melee_stats](https://user-images.githubusercontent.com/119366386/204401629-5cbf6133-6865-4ce5-86f2-43d01ad8fc30.png)

**Comment by Winfrieda** [comment]
Forgot 80upgrades link, Edited the first post.

**Comment by jimmyt857** [comment]
Unlike 80U, we don't try to match the in-game character stats panel. There is a rough correspondence, but it omits certain things because of Blizzard implementation quirks, and we have a few quirks of our own which don't always match Blizzard's. If you think a specific effect is not being accounted for in the sim then please do let us know, but otherwise this is a known difference.

**Comment by jimmyt857** [comment]
Closing since this is WAI. Thanks for the report!
