### ISSUE TITLE
Frigid Dreadplate talent causes sever DPS decrease. 

### ISSUE THREAD

**Issue by Kalabast** [wowsims/wotlk#1974]
When adding 1 or more talent points in to the Frigid Dreadplate talent DPS drops significantly 

**To Reproduce**
1. Remove a talent from any part of the tree
2. Hit "Simulate" Noted DPS at 4.9k
3. Add talent to Frigid Dreadplate
4. Hit "Simulate" DPS now sims at 1.2k

**Expected behavior**
Since Frigid Dreadplate has no impact on DPS output I would assume it would have no impact on simulated DPS

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 107.0

**Additional context**
Attempting to simulate and test tanking DPS

**Comment by hillerstorm** [comment]
![image](https://user-images.githubusercontent.com/779488/204594945-c632db4f-2248-4698-a9cf-a820decbf2a6.png)
🤔 why does it even care about how many points you have in FD?

**Comment by Kalabast** [comment]
![image](https://user-images.githubusercontent.com/119438135/204599546-9edd1985-2d97-4005-83f4-4a5ea8eff6d9.png)

Lol no idea...
