### ISSUE TITLE
No stamina to spellpower for demonology warlocks

### ISSUE THREAD

**Issue by hjelp200121** [wowsims/wotlk#1978]
**Describe the bug**
Using the "Calculate stat weights" as a demonology warlock gives a weight of 1 stamina = 0.00 +- 0.00 DPS EP, however due to the talent "[Demonic Knowledge](https://www.wowhead.com/wotlk/spell=35693/demonic-knowledge)" 1 stamina ~ 0.14 spellpower. 

The lack of value for stamina in the weights calculation seems to imply that the conversion of stamina to caster spellpower is completely skipped in the simulation, or that there is a simple bug in the weights output.

**To Reproduce**
Go to warlock simulation and choose any demonology spec and simulate weights

**Expected behavior**
1 stamina ~ 0.14 spellpower. 

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/warlock/

**Desktop**
Browser chrome

**Comment by lologarithm** [comment]
Found the issue, we were applying extra SP from pet stm but it wasn't dynamically updating and so the 'bonus stats' that the EP system uses wasn't added to stm before the SP bonus was added. 

I am working on a fix now.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1983
