### ISSUE TITLE
Initialisation issues

### ISSUE THREAD

**Issue by Glandaaalf** [wowsims/wotlk#198]
The dps-meter is always going up when launching a sim
If things were perfectly randomized, we could see it sometimes go up, go down, be stable...

This is a hint that there are probably some initialization issues in the sim.

**Comment by Watcher7** [comment]
Is this just a "simple" DPS meter behavior thing? The detailed damage graph shows spikes and dips just fine.

https://i.imgur.com/ldhTyGk.png

**Comment by Glandaaalf** [comment]
I'm not talking about dps vs Time like in your graphs, but dps (average) vs Iterations. Hence why you can't see it in your runs.

**Comment by Glandaaalf** [comment]
More on this issue (my discord comment):

Ok so I was meddling with the rollover function, trying to figure out how to properly rollover the spell haste modifier. I added some increasing crit bonus when rollover was called to see whether at least the crit that was already taken into account. And after quite a few tests, trying to make sense of what was displayed, it dawned on me. Some spell variables (and at least the dot crit) is not properly re-initialized. Why do I think that? Well check these couple of screenshots:

On one hand, I have a near 100% crit rating on corruption, which is what I would expect with my hacked in crit rating.
However, on the second screen, you can see the results of 1 iteration. And I'm sure it's always the first iteration. You can see it doesn't crit nearly that frequently!

I pretty sure we have some variables in the dot program that need to be reinitialized properly.

https://cdn.discordapp.com/attachments/891807022973087825/1001856162808991864/unknown.png
https://cdn.discordapp.com/attachments/891807022973087825/1001856163186483330/unknown.png

**Comment by jimmyt857** [comment]
This should now be fixed by #1335
