### ISSUE TITLE
Crash Report 373307061

### ISSUE THREAD

**Issue by sanguinerarogue** [wowsims/wotlk#1984]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmn9wE8cVx29XJ+u82HjjEDg02L24KVGYaOYkoSlk0rEAt+P+SMcD08Kk0w4KGOwEbOpAUvRPCYECBgJNQgpOKJTQSQYoTHDGtS3ZgpgUzM/UBpsf5UcoJqQQfpRpS5kW+t7uyZKQTBkmNJ2gJ5+8t3u3Z0uffft9b5f9/mnW/hC7qc4lOSXjjR9UVVRPm22UfFfL5sy5lbA8frab6p8WFGU1tNH9+yhT+b/rKcvhn0WofqqgyBZppMzBO8NU/0cBXg3V1+DqX7dTbMnltdAyv7BIhTMFTt+E09eHWKc5vKuZimvhB3o520z1SwVQXddA9TeGyM5V/mk9vi9uwvdX1uP7+QN4eQf09a4TChsjoqDyf+2lRXkaNXNHkDJ1gvozspCQYcupkrEkCynXyXA2UKOcBEgpKSNBUR1YFmgkJF9x6g/I6y4XG2RYP+1mzEgtcbt9XtMc7vObYF6312eaPnjBqc/r8UOT6YGyx+fxQaXnNNG11Qcpv9AD3+dBaqw8SF0rD1Fz1SF6jqiXiaOOKEeJUgcsZAi8n+z/kUCFLbQDg2U11TONsuC04OTKKo1w1dmMDM5vofpfgKr1bXTNGgSgLYwMLoTqJYVFtl2CwaOAw4ohcPXLLZJBuLQLWhg/CDjVFhYRBHAeNL4OPO5CAPP4AWj65ZCiLDiVvSyF9ovI4G8tBldJ7lrxfWMTPnbNYSo6ly1n1uFtq+Dhewug8BEUFhVC/cuttEjTVDO3zDbBloEwxULKbuJnboM8Jk631QScBqNaFhwaHNlwUDhscDjgIHDYgU2q22qJy43E+T0+JM7j8/o8wJvP5/EChG4/nJhe0wNNPgTweBflS7ZT/b0eapzroK5POqjZ09ELYPYDU4R1FQP8Foz1WXOJ9lSwIvhM8NmgwPB3aVxhNr/2JyqdVA6f2yL9ofRknTEWb8T9IbYwvrpV+ENgkfHjEeEMSa8nhK6wtzx+vhs9YW+Fgy9rQRoBq7pI3BleCsed4TZ44r4CGEZA5H7LC6IPnEjvzguOCCSfDw+kuyrV7vS6L95C/eGbpTpdS8gMMoeQ70xiPxosm84VG6qLjB5icWezuKQWiyqyOPZxqzXWolplR7r6UhJj9xFA1296gGD4AWABY6+J8AK0QLEXXacnxu084Hbx9rTcLiLMyfpriwYacf+cr8m/f0CAcaZqS/55a83ZjbZYjaKwr7I87cbfbYkd8OTP6BFxGz+ylSZ3xDevS6iRoyZfYfOd7AQoiewxwZlGSc2sysmaxolzC46dVZHesYNEJ42dzSlaAsZODj8mx45NColDDQlCInHsZPOlzVZXSQOn6yb2Xd8s3fh+ISXk6FnaGhs3Kt/WjM/cER89+xpgIMLoAQWR8dopFlK2kqFMR+mg2w3iIt9QFGNUwF5a+GNFmTgKIEfnnccn6yAWHnP7QRYg1sA5eGRw2eCjTRANPg9g73ED/HAFuGrk/Q9RytefofqHUWrUHaKuncB7W0eKUNgKMiF73A+N0llVM8trNAenznoErCkO2Jr2XsCwmMPDFmAtjUnO+US3JRTaaYtg7GizZKzlVsZyeIcUCqKLPL44LDFrkZg5eE/E8s+1TXHOLrTg+/EjMcKuImEOvh2KK4eAOADIRmQwS2ch5YkX2ahS4qJSigbWBEajOrBb/jXbUgnM8s7oZ4mnbhVaU/FIn7DOYsDRBFS

**Comment by sanguinerarogue** [comment]
Crash occured when adding an imported ret paladin JSON

**Comment by jimmyt857** [comment]
Unfortunately this issue doesn't seem to be reproducible. Going to close,, but feel free to reopen if it occurs again.
