### ISSUE TITLE
Improper Item Levels

### ISSUE THREAD

**Issue by GrooveGrindGore** [wowsims/wotlk#1986]
There are phase 2 items that are labeled as 232 item level that should be item level 226 and are given inflated stat weights. The ones that I've found are Proto-hide Leggings, Flamestalker Boots, Belt of the Twilight Assassin, Footpads of Silence, and Savior's Slippers. There may be more but these are the ones I've seen. Appreciate the sim as it's been very helpful in gearing decisions.

**Comment by Watcher7** [comment]
Blizzard has stated that they're changing item levels of Phase 2 equipment.

https://www.wowhead.com/wotlk/news/wowhead-wrath-classic-database-updated-item-levels-330095

226 -> 232 for Phase 2 25nm gear seems consistent with Blizzard's intent.

Our gear picker uses Wowhead as a data source, Wowhead harvests data from the game.

https://www.wowhead.com/wotlk/item=45141/proto-hide-leggings

That means 232 item level Proto-hide Leggings are consistent with at least what Wowhead has found in-game.

**Comment by hillerstorm** [comment]
Linking them ingame on the PTR gives the 232-stats aswell, NAB

**Comment by GrooveGrindGore** [comment]
Understood. Thanks for the feedback.
