### ISSUE TITLE
Warlock sim, rings have enchants, although there is no enchanting as a profession trained and gives error after each attempt to change

### ISSUE THREAD

**Issue by ViktorYakov** [wowsims/wotlk#1990]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lologarithm** [comment]
Try opening the settings menu (gear in upper right) and "Restore Defaults".  
You should be able to remove the enchants by clicking on the item, going to enchant page, and clicking 'remove' in the upper left.

If this doesn't fix it, can you click Export->link in the upper right and paste in the URL you are using so I can debug?
