### ISSUE TITLE
There is no pictures on items 

### ISSUE THREAD

**Issue by zukalinda** [wowsims/wotlk#1995]
There is no pictures on items.

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lologarithm** [comment]
We have had a ton of reports of disabling anti-virus or giving exception to the site fixing issues, you should try those first. You can also try the downloadable version https://github.com/wowsims/wotlk/releases here, which many have found resolves some of those issues
