### ISSUE TITLE
penance cannot crit when target is hostile and penance using incorrect Damage values

### ISSUE THREAD

**Issue by beckzudian** [wowsims/wotlk#2000]
**Describe the bug**

**To Reproduce**
spec Priest into penance (51 point discipline talent) 
run sim
observe penance damage (target is harmful)

**Expected behavior**
Penance should crit more than 0% 

**Sim Links and Screenshots**

Add any other context about the problem here.](https://wowsims.github.io/wotlk/smite_priest/#eJztUjFoE2EUvu/1Eq9nJH+jw2/IwXlTEIT/7jhQEHJ10cEh4NJJWqGSQTCIgy0UioiWdmgFhxocgoMUB+kgUhKpIh0aAlozqIiDFISAEtJKQZx8f87FTVA33/Dufe/73sfdu2eftEiQohhnMIYqzQJLwDJQx8bBFWAV9BzYBLaAd8BHoMsKwjJhk3DKsSDhUhEKx6E9yuwyjgqq4OGcqdv5nnkd6fKlianJK1ZKpPKPYWfF7lOSXxwvvfeC6i2yh8XeB/KG1tfIzogF5rYdb0gTGfHpLcn5nygrHjZIfuM5VmrxAdFl+l7OMxkZDG/y7J2CZ+5omBE7DG8XEuN9os/olsNFj4tdxzbF4jpxftXU+VlD535TK9tNkt+14PWgWX9CXtbiryynxlLjuIY54OgSGf/jl5guWBCQ5PIVVOwV2FVeFZ/U3OCq7kPwKuEiZ+TTEhY/51FUkQoDFfqhCpWK/CAMfRUw9IPIPxYwG/maCbYhrdU2iQdtko/a5H7uULHXIfWyQ12YfeyvwXgPo0aG16Xh5H3OxyNJcSg+XLuro1U6kXS2SkcuDuJNKVij6sLMtH328sTVyuQFN4jcc9L657/3Rvw3XGZbG3/iEy+OTI3+rjhZ3elGPBoO4mvpB7INir8=)

**Comment by jimmyt857** [comment]
Fixed now, thanks!
