### ISSUE TITLE
Elemental Shaman: Flametongue Weapon

### ISSUE THREAD

**Issue by DrChakalu** [wowsims/wotlk#2002]
**Is your feature request related to a problem? Please describe.**
There is no way to verify if you have the buff or not.

**Describe the solution you'd like**
A button in the Fight Settings tab in the player section. Would be nice if it takes the right values for talented or not.

**Describe alternatives you've considered**
Two buttons or a dropp down list in the player / gear tab.

**Comment by lologarithm** [comment]
Currently the sim assumes that you always have Flametongue imbue and correctly accounts for talents. You can verify this by removing talent points from 'Elemental Weapons' and see your total SP go down. We could add a UI to show that its always selected but felt like a waste of UI space

**Comment by DrChakalu** [comment]
Thank you very much for the clarification. I tried to find it in the beginning of the log but couldn´t make any guess if I have the buff or not.

**Comment by lologarithm** [comment]
Yea, we don't 'cast' the spell at all, we just add the bonus spell power before the fight starts (based on talents etc)
