### ISSUE TITLE
"Only Sunderer" option for Warrior sims

### ISSUE THREAD

**Issue by jeffkaminski** [wowsims/wotlk#2009]
Currently there a few options for Sunder Armor in warrior sims, but as far as I can tell none of them account for if I am the only warrior in the raid and solely responsible for all sunders (this is actually my current situation).

Would definitely appreciate this option!

**Comment by jeffkaminski** [comment]
> Hey @jeffkaminski! If you right click the `Major Ar` debuff it should tell the Sim to apply and maintain sunder armor
> 
> <img alt="image" width="1411" src="https://user-images.githubusercontent.com/12898988/205341459-2f97da5e-b697-4791-bb97-38507922ecc4.png">
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/12898988/205341722-0314d10a-8cf4-4682-b173-e99fda80b3c3.png">
> 
> <img alt="image" width="525" src="https://user-images.githubusercontent.com/12898988/205341761-2c007c32-17da-4a8e-95a4-e6bfa162fe76.png">

Hey, thanks for the quick reply!

So, I am aware of this option. I do have this enabled (see screenshot 1 below)

This option does apply and maintain the Sunder Armor debuff. However in the Log of the Sim, it still assumes that there is another warrior in the raid who is applying sunders alongside me to get the stacks up to 5 after the boss pull.
(In screenshot 2, you can see that I only cast Sunder Armor 2 times, but it does reach 5 stacks.)

So I was wondering if there was an option that would cause the Sim to only have myself applying all stacks of Sunder Armor.

Maybe I am missing something or not understanding. If so let me know!

![image](https://user-images.githubusercontent.com/38301759/205356382-5d946141-9260-4a9f-aa13-80f02b749a98.png)

![image](https://user-images.githubusercontent.com/38301759/205357128-61ee8f0e-cc02-4592-a38a-ce3b94e38ee0.png)

**Comment by jimmyt857** [comment]
@jeffkaminski the option shown in your screenshot is the option for YOUR sunder, and it is set correctly. But you also need to disable the Sunder option in the Debuffs panel, which is for debuffs applied by other raid members (this is described by the tooltip for the Debuffs section). You need to turn off the Sunder Armor option in that section.

**Comment by jeffkaminski** [comment]
@jimmyt857 ahh I knew there had to be something I was missing. Thank you very much!
