### ISSUE TITLE
Cancelaura toggle for specified buffs

### ISSUE THREAD

**Issue by Algelius** [wowsims/wotlk#2029]
**Is your feature request related to a problem? Please describe.**
Shadowmourne has a notoriously awkward effect where you benefit from doing a cancelaura for the Chaos Bane buff, as it prevents generating stacks of soul fragments and triggering its attack while active. Currently there is no option to simulate including cancelaura for buffs as they are applied. 

**Describe the solution you'd like**
A toggle to cancel a buff, and the option to set whether it should be canceled immediately upon receiving the buff, or at a specified delay. Preferably for any potential buff your current talents/gear/class/consumables could apply. Perhaps using a similar interface as the cooldowns section under settings.

**Describe alternatives you've considered**
The scenario is rather specific to Shadowmourne, so it might not have much use outside of the Chaos Bane buff. Meaning it could just be made into a unique toggle for that buff alone. However, I believe it would be beneficial to have the option for any buff, to allow for experimentation.

**Additional context**
The reason for canceling the Chaos Bane buff is due to it supposedly not being powerful enough (270 strength for 10sec upon reaching 10 stacks of Soul Fragments and triggering the attack that shares the Chaos Bane name) to justify not generating new Soul Fragments (30 strength per active stack, up to 10) and thus preventing triggering more attacks.

**Comment by jimmyt857** [comment]
This is niche enough that it should probably only be allowed once we have APL-like rotation support. The suggestion of making it a Shadowmourne-specific option (only shown when Shadowmourne is equipped) is also a possibility.

**Comment by vigo2** [comment]
From playing around with the sim, cancelling the buff is a DPS loss, anyhow. That's _after_ changing the proc rate from 50% to ~75%, making it proc on the 10th, not the 11th Soul Fragment, and on a Fury Warrior (rebuilding stacks in ~8 seconds, a lot faster than Paladins or DKs). Chaos Bane's direct damage is rather low, and can't make up for the additional average strength the Chaos Bane aura grants (~60 strength in this case).

**Comment by jimmyt857** [comment]
Cancel aura is a valid action in APL now, so this is doable.
