### ISSUE TITLE
Human Race Paladin Retribution BUG，The simulator should not have more strength points than the game

### ISSUE THREAD

**Issue by xjc520** [wowsims/wotlk#2031]
**Describe the bug**
The human paladin does not wear any equipment. Without BUFF, it is 173 points of strength
BUT，The simulator has 199 strength points without any BUFF and equipment
![QQ截图20221204135807](https://user-images.githubusercontent.com/12624782/205476907-51b525c0-4b18-40d0-9af2-0e8f598222b7.jpg)
![QQ截图20221204135831](https://user-images.githubusercontent.com/12624782/205476921-059d1c3f-386d-4789-96cd-65bb5819b348.jpg)

**Expected behavior**
Human strength are 173 default not 199

**Sim Links and Screenshots**
![QQ截图20221204135807](https://user-images.githubusercontent.com/12624782/205476907-51b525c0-4b18-40d0-9af2-0e8f598222b7.jpg)

![QQ截图20221204135831](https://user-images.githubusercontent.com/12624782/205476921-059d1c3f-386d-4789-96cd-65bb5819b348.jpg)

**Comment by Watcher7** [comment]
Paladins do indeed have 173 base strength in the sim.
It's likely that you have https://www.wowhead.com/wotlk/spell=20266/divine-strength enabled.
173 + (15% of 173) = ~199

**Comment by xjc520** [comment]
![1](https://user-images.githubusercontent.com/12624782/205508796-1508ef4c-05e9-4001-804a-3a5792d3a7ce.jpg)
![2](https://user-images.githubusercontent.com/12624782/205508799-e3da547f-2db2-4ff2-9a48-f25559340a54.jpg)
![3](https://user-images.githubusercontent.com/12624782/205508801-9887b5c1-fdbd-4293-b624-1d6dd4fd9ff3.jpg)
![4](https://user-images.githubusercontent.com/12624782/205508805-7fbeedac-7e98-45d5-8f0d-0528593a1b2c.jpg)
![5](https://user-images.githubusercontent.com/12624782/205508809-21d0625d-f57e-4192-9b23-dd9183e49fee.jpg)
![6](https://user-images.githubusercontent.com/12624782/205508811-50f89e46-b743-4696-9f60-96fd19053b59.jpg)


basic strength are 155 like img1 not 155+(1.15*155)
