### ISSUE TITLE
[Feature Request]: Stat Weights export Pawn string

### ISSUE THREAD

**Issue by alphabitnz** [wowsims/wotlk#2032]
Huge QoL increase if you could give stat weights the ability to export a pawn import string, as currently users have to copy/paste every stat's weight/EP individually.

Raidbots does this nicely for Retail stat weights.
For what it's worth, note Pawn applies rounding for any stat weights longer than 14 decimal places (it will handle a 16 decimal place number accordingly)

Pawn formatting would be as follows:
```
( Pawn: v1: "Name of Export eg Name/Class/Spec": Class=Warlock, CritRating=0.58194056287938, HasteRating=1.1758460253786, Spirit=0.63049250601454, Intellect=0.2628343412496, Stamina=0.13791351044553, HitRating=0.20066514102071, SpellPower=1 )
```

**Comment by jimmyt857** [comment]
This already exists under Export --> Pawn EP.
