### ISSUE TITLE
Trueshot Aura not applied in hunter simulator

### ISSUE THREAD

**Issue by klippx** [wowsims/wotlk#2033]
**Describe the bug**
It seems Trueshot Aura is not applied in hunter simulator

**To Reproduce**
1. Go to [simulator](https://wowsims.github.io/wotlk/hunter/#) and select MM1 P1 Preset
2. Click on simulate, get about 7593 +- 200. (Use e.g. 10k simulations)
3. Remove something (e.g. silencing shot) from talents,
4. Click on simulate, get about 7495+- 200.
5. Remove trueshot aura from talents,
6. Click on simulate, get about 7496 +- 200 (again).

**Expected behavior**
Should make a difference if a talent that boost attack power by 10% is used. This should equivalent to a good 300-400 AP, at least. Not by a measly 1dps difference. 

If there is a bug here, that could explain why this talent it is not part of the recommended build for MM.

**Comment by jimmyt857** [comment]
I'll need a link to your settings if you want this to be debugged. However, you probably already have the same buff being provided by 'another raid member' in the Buffs section.

**Comment by klippx** [comment]
I use the default settings. And it seems you are right.
