### ISSUE TITLE
RetPal Glyph of seal

### ISSUE THREAD

**Issue by CheeseCoffee** [wowsims/wotlk#2035]
Glyph of Seal of Rightousness is not working how it works in game.
without any glyph for example and with sanctified retribution aura (+3% to damage) it hits for 550 damage.
with glyph it should hit for 605 damage. Accurate formula is:
base_speed * (0.022 * ap + 0.044 * spd) * (1 + seals_of_the_pure) * (1 + glyph_seal)

your sim hits for 600 damage, I suppose your formula is:
base_speed * (0.022 * ap + 0.044 * spd) * (1 + seals_of_the_pure + glyph_seal)

**Comment by Watcher7** [comment]
Thanks, I'll look into this.

**Comment by Watcher7** [comment]
After some brief testing I've determined you're correct, this should be fixed in https://github.com/wowsims/wotlk/pull/2041

**Comment by CheeseCoffee** [comment]
👍
