### ISSUE TITLE
Human Paladin basic strength are 151 not 173

### ISSUE THREAD

**Issue by xjc520** [wowsims/wotlk#2036]
![1](https://user-images.githubusercontent.com/12624782/205509105-acc67251-c509-47c0-90f7-fcc2e005c7a0.jpg)
![2](https://user-images.githubusercontent.com/12624782/205509109-446f3bab-0bc8-4c5c-b448-f1d5214f68a8.jpg)
![3](https://user-images.githubusercontent.com/12624782/205509112-e9deb616-43e9-416b-98f2-88083e8927a2.jpg)
![4](https://user-images.githubusercontent.com/12624782/205509115-ee9e02af-69fb-4434-bebc-5b602a4ca2db.jpg)
![5](https://user-images.githubusercontent.com/12624782/205509116-2772c420-1bdd-4232-b578-ecabe798bc05.jpg)
![6](https://user-images.githubusercontent.com/12624782/205509118-f814f9f0-b83f-4cec-890a-01ab58537f20.jpg)

basic are 151 strength 
not 
151+151*0.15(tatent)=173

**Comment by Watcher7** [comment]
Hm, interesting, you seem to be correct-- interestingly I recall having someone testing this during BETA classic and getting 173

https://www.wowhead.com/wotlk/gear-planner/paladin/human/BgFQAAA

Wowhead seems to have the same bad value, so maybe I'm not crazy?

Regardless, I'll resolve this shortly.

Thank you for the report.

**Comment by Watcher7** [comment]
This should be fixed in https://github.com/wowsims/wotlk/pull/2041
