### ISSUE TITLE
Moonkin - Player Latency not working

### ISSUE THREAD

**Issue by nlautner10** [wowsims/wotlk#2053]
**Describe the bug**
Varying values do not affect rotation. It is effectively a boolean switch triggered by either a positive or negative value (only way to affect DPS is to change from positive to negative value or vice versa). Technically impossible to react with a negative time lol but that's beside the point.
This current version is better than what was before, it at least recognizes a guaranteed 1 spell offset from eclipse proc.

**To Reproduce**
Ensure seed is set to anything other than 0
Changing latency to 1. Sim. Change to any other positive value, try 15000. Sim. Same results. If it took me 15s to realize eclipse proc'd, I shouldn't be reacting the way as explained in the timeline for casts.
Changing to a negative value will alter results, all negative values hold same result.

**Expected behavior**
Player reaction to eclipse buff should make the sim think a buff does NOT exist if it has been active for less than the current latency value. 

**Desktop (please complete the following information):**
OS: Win
Browser: Chrome
Version: Unsure how to find

**Additional context**
I can only assume "moonkin.LunarEclipseProcAura.Duration" isn't what it seems from looking at the code. Possibly changing line 82 (and equivalent for solar) to..
lunarIsActive = (sim.CurrentTime - moonkin.LunarEclipseProcAura.startTime) > playerLatency
Would prove more accurate?

**Comment by jarveson** [comment]
should be set now, the parameter was 'nanoseconds', its now the amount of 'milliseconds'
