### ISSUE TITLE
Lighting Reflexes 10% haste not being calculated in stats

### ISSUE THREAD

**Issue by jakess009** [wowsims/wotlk#2062]
When testing the rogue sim talenting 3/3 in lighting reflexes the stats block is not reflecting that extra haste. If the Sim uses that stat block then it may be calculating incorrectly.

**Comment by jimmyt857** [comment]
Thanks for the report! This talent is correctly implemented, the code is here: https://github.com/wowsims/wotlk/blob/master/sim/rogue/talents.go#L20

Lightning Reflexes increases melee attack speed, but does so the same way Bloodlust does, without actually granting +Haste rating. So not showing up in the stats is working as intended!
