### ISSUE TITLE
Crash Report 1795348903

### ISSUE THREAD

**Issue by MattZeeX** [wowsims/wotlk#2079]
Link:
https://wowsims.github.io/wotlk/raid/#eJztUjlIA0EUnflZk80QcRSLSdCwbqVCYHaXLbTJamVhERDBUkEEQRTEyko8QMVC8IBEsJBYiYXGE4x4NQqipBAU0ggeqIV2NoJ/s1jYWWjngwfz/v/z5jEzjDSSelCVMhIZKxqmoUR/34CW6Ojp6OzuVYErkW3KSvjKMYinSt2fPobkLjCFP2SBhfh4FsRUVPe5tQDfXQcxV4GL+wyIjTBjfHEfxGRUp4QV81GcnY3qCs4SFuTDGdB9tzuA5tebID7Cuh87rlGIL2+BmK/wbEN85hzEReXXIUdLrsIEzxdujpesW0ymQbyV42JhD8REFOsj+6CrqiKLE0qbUjsN5B/fMEjOqM1iGq0pyIN+J6IxUP1IFRlEAtKHDCApsgi/CAjfJK2OSVtK27BsU0rDMi3DsBCGaZlGzEYhTWlgy7qlQs1fAZ86BLF2B9pjDqofciDvcvBIlVcaSNFgaVcBV/EdSm8oSQHR8xAshHJanVIvbbkTTiVdnMbrvMplvOpro7kKWotQ//yRR53fcBk6PfkVn5/Au6vmvNPg6fd4E22nn//BceA=

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:47 +0x10
panic({0xe1a20, 0x1153640})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).registerTricksOfTheTradeSpell(0x1faea80)
	/home/runner/work/wotlk/wotlk/sim/rogue/tricks_of_the_trade.go:19 +0x2e
github.com/wowsims/wotlk/sim/rogue.(*Rogue).Initialize(0x1faea80)
	/home/runner/work/wotlk/wotlk/sim/rogue/rogue.go:167 +0x34
github.com/wowsims/wotlk/sim/core.(*Environment).initialize(0x1eb71e0, 0x1c11180, 0x1d3fe40)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:111 +0x26
github.com/wowsims/wotlk/sim/core.NewEnvironment(0x1c11180, 0x1d3fe40)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:41 +0x4
github.com

**Comment by MattZeeX** [comment]
Ok the issue here is probably the rogue setting is to use tricks on cooldown, and the rogue's tricks under the raid settings is unassigned cause I removed a guy

**Comment by lologarithm** [comment]
Ok, I closed the other 3 you reported
