### ISSUE TITLE
Mjolnir Runestone Proc is Incorrect

### ISSUE THREAD

**Issue by DegausserW** [wowsims/wotlk#2093]
**Describe the bug**
Mjolnir Runestone has the correct tooltip in the sim (751 ArP), but the proc is still the old pre-buff amount of Armor Pen (665).

**To Reproduce**
Run sim with Mjolnir Runestone equipped
Go to Log tab
Search for Mjolnir Runestone to find proc
See that the proc amount is only 665, not 751

**Expected behavior**
Mjolnir Runestone's proc in the log should be the same as the listed proc on the tooltip. 751 instead of 665.

**Sim Links and Screenshots**
[(https://wowsims.github.io/wotlk/warrior/#eJztk01oE0EUgPNe1nR26JohB1lDIusiWArCZLeBFMRMPOnJiJf2IlaJFPQQgtBaEKK2oF5aQQsG8ecW6MGb5mBBbEUKRgMLHjzFNqQpHgyeSi86u5OA9iSoNx+Pnfe+t2/ezOMNPUSQYwZOwCQUsQywAFAFqAG8AmgAdAC2AY/HCVjIIQMCxmAabgE8kYrQBIzJ7PizyA2I5C9PXC2UyB6mxzeBRtnbDppbSTvyfAVf1pDqrL6BdnhFmoPsjYw1k3bYD0RZYxPN+wk7Ir2dALyW4e1kAN7XkRpsqYXm3AFba9cwJN1VGb+XsLUd342y+Q7a+qM1VEpjrLmB5tekrct8pXSAzS+juZiQx6i2UBXW2betnqmxLx+Cb9sv/06m11V5dcBdQGfdzyrRNmT/jLw2pgVdGV7A0H/5RWYMAgxNtKAIcr5Kp+hR5k9ZToWPiZPBWs6J04qMi3FljAo5k3LaZNZTUGhExEJxQ+87DIbgDhx2ueNwl6cc1z3i8jQfcTnnaYlScnFTjkQpN51aB5NUPWQVD83HHlo3PRya9ZDPedgBrQsDFThP43Qvub3P+t4XiJH+TSijGmkvhfuECJ+wu3X8iURpmMye2wVeGH2QEJ8gVMGQ3cLeLc6K/ZUHvqxlRxVpZA9eDORj1lnG4sNrM4P5iSsXJqcKpUuWk7bOmORfz1n3uvgb25QLq3+yD88MF3O/+3PQvPLiuuhldLLyPf4Ak/Cxaw==)]

![Mjolnir Runestone](https://user-images.githubusercontent.com/120121151/206501914-01c29bbb-e149-4b53-be9d-f3f52b4ab0fe.PNG)
![Mjol Proc](https://user-images.githubusercontent.com/120121151/206501930-d700b4d5-f4c6-4928-8b5c-49967c5565aa.PNG)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by lologarithm** [comment]
Probably worth checking all ulduar trinkets
