### ISSUE TITLE
starfall bug

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#2094]
**Describe the bug**
Starfall isnt' losing damage if no natures reach but using glyph of focus when you put over 15 on range

**To Reproduce**
1. change range with glyph of focus

**Expected behavior**
Should be losing starfall damage when outside of its range

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/balance_druid/#eJztUj1IW1EUft9JjDfPllwz3QYj6UVQSoX73iOgS/Ps5NAh4OLYDnVyEKe2U1qkVSdBEczk6FKoOLRVaGxpaV1aEbQ0oBIT0KGDUBHp0p73nopjB7v5cbmc77vnj3Ou3SFIkqEe9GMQI1QCpoB5jHe+Aq0C68ABcLdVIEcGPoqBFxaANIdkZpueIVEcfvD44ahISGQ2Yafk2zqpn1md+PSB3r0hOylXaqRjgXlNHh2Q2svqWDVkyzVS0+069otZWn7juBOhk+wZHbtFPmdtNq3Jsmwpaw1SM226OXq1uNRSgy76p+Qh53/Btc+FWpCgLRSqYTOv6xSVT8qd/dO+4rKyHNxf62Q3y/f7pI6zTBcbgfh0hbQUMCjGB5segQc0Dtya4paucBFPhIAkRSNwtZ2K7C4eG/+rL0hbmet2i/hzBkyiM28813ieY/J8eUwcz2PbcYzndHe7Jm+MZxx3D0r8qJAs7ZL6XqHc7x3q+rxBprxJ/DMPES/Dmjjdxm2/CqtMlt6mZCiUhvzW6OmOf6M8F2Ct0Bsp64WbQyG2Cu5Lyg0o8d+3OuZfRpbS2sdLyfMviGZ1b9vvi/hJoR/38RfyXJH1

**Desktop (please complete the following information):**
 windows11

**Smartphone (please complete the following information):**

**Additional context**
Could be me misunderstanding the range

**Comment by jimmyt857** [comment]
The range option is your distance from the target, but it's only used to calculate travel time. We do any other checks based on range, so that glyph and talent don't affect the DPS. Thanks for the report though!
