### ISSUE TITLE
Missing some hit rating while testing Affliction Warlock BIS for Ulduar

### ISSUE THREAD

**Issue by jakewillms17** [wowsims/wotlk#2108]
**Describe the bug**
Here is the JSON string I am working off of. 

{
  "settings": {
    "iterations": 25000,
    "phase": 2,
    "fixedRngSeed": "4245393343",
    "showDamageMetrics": true,
    "language": "en",
    "faction": "Alliance",
    "filters": {
      "oneHandedWeapons": true
    }
  },
  "raidBuffs": {
    "giftOfTheWild": "TristateEffectImproved",
    "powerWordFortitude": "TristateEffectImproved",
    "strengthOfEarthTotem": "TristateEffectImproved",
    "arcaneBrilliance": true,
    "divineSpirit": true,
    "trueshotAura": true,
    "leaderOfThePack": "TristateEffectImproved",
    "icyTalons": true,
    "totemOfWrath": true,
    "moonkinAura": "TristateEffectImproved",
    "wrathOfAirTotem": true,
    "sanctifiedRetribution": true,
    "bloodlust": true
  },
  "debuffs": {
    "judgementOfWisdom": true,
    "faerieFire": "TristateEffectImproved",
    "curseOfElements": true,
    "ebonPlaguebringer": true,
    "earthAndMoon": true,
    "heartOfTheCrusader": true,
    "totemOfWrath": true,
    "shadowMastery": true,
    "bloodFrenzy": true,
    "sunderArmor": true
  },
  "partyBuffs": {
    "heroicPresence": true
  },
  "player": {
    "name": "Player",
    "race": "RaceGnome",
    "class": "ClassWarlock",
    "equipment": {
      "items": [
        {
          "id": 45497,
          "enchant": 3820,
          "gems": [
            41285,
            45883
          ]
        },
        {
          "id": 45133,
          "gems": [
            40051
          ]
        },
        {
          "id": 46068,
          "enchant": 3810,
          "gems": [
            39998,
            40051
          ]
        },
        {
          "id": 45618,
          "enchant": 3722,
          "gems": [
            40026
          ]
        },
        {
          "id": 46137,
          "enchant": 1144,
          "gems": [
            39998,
            40051
          ]
        },
        {
          "id": 45446,
          "enchant": 2332,
          "gems": [
            39998,
            0
          ]
        },
        {
          "id": 45665,
          "enchant": 3604,
          "gems": [
            39998,
            39998,
            0
          ]
        },
        {
          "id": 45619,
          "enchant": 3599,
          "gems": [
            40051,
            40051,
            39998
          ]
        },
        {
          "id": 46139,
          "enchant": 3719,
          "gems": [
            39998,
            39998
          ]
        },
        {
          "id": 45135,
          "enchant": 3606,
          "gems": [
            39998,
            40051
          ]
        },
        {
          "id": 45495,
          "gems": [
            39998
          ]
        },
        {
          "id": 46046,
          "gems": [
            39998
          ]
        },
        {
          "id": 45518
        },
        {
          "id": 45466
        },
        {
          "id": 45620,
          "enchant": 3834,
          "gems": [
            40026
          ]
        },
        {
          "id": 45617
        },
        {
          "id": 45294,
          "gems": [
            39998
          ]
        }
      ]
    },
    "consumes": {
      "flask": "FlaskOfTheFrostWyrm",
      "food": "FoodFishFeast",
      "petFood": "PetFoodSpicedMammothTreats",
      "defaultPotion": "PotionOfSpeed",
      "prepopPotion": "PotionOfWildMagic",
      "defaultConjured": "ConjuredFlameCap",
      "thermalSapper": true,
      "explosiveDecoy": true,
      "fillerExplosive": "ExplosiveSaroniteBomb"
    },
    "bonusStats": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "buffs": {
      "blessingOfKings": true,
      "blessingOfWisdom": "TristateEffectImproved",
      "blessingOfMight": "TristateEffectImproved",
      "vampiricTouch": true
    },
    "talentsString": "2350022001023510253510331151--55000005",
    "glyphs": {
      "major1": 50077,
      "major2": 45785,
      "major3": 45779,
      "minor1": 43394,
      "minor2": 43390,
      "minor3": 43393
    },
    "profession1": "Engineering",
    "profession2": "Tailoring",
    "cooldowns": {},
    "distanceFromTarget": 40,
    "healingModel": {},
    "database": {},
    "warlock": {
      "rotation": {
        "preset": "Automatic",
        "curse": "Agony",
        "primarySpell": "ShadowBolt",
        "secondaryDot": "UnstableAffliction",
        "corruption": true,
        "detonateSeed": true,
        "specSpell": "Haunt"
      },
      "talents": {},
      "options": {
        "armor": "FelArmor",
        "summon": "Felhunter",
        "weaponImbue": "GrandSpellstone"
      }
    }
  },
  "encounter": {
    "duration": 180,
    "durationVariation": 30,
    "executeProportion20": 0.2,
    "executeProportion25": 0.25,
    "executeProportion35": 0.35,
    "targets": [
      {
        "level": 83,
        "mobType": "MobTypeDemon",
        "stats": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          320,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          10643,
          0,
          0,
          0,
          54,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "minBaseDamage": 10000,
        "swingSpeed": 2,
        "parryHaste": true
      }
    ]
  },
  "epWeights": [
    0,
    0,
    0,
    0.25476723603243057,
    0.5251524130291553,
    1,
    0,
    0.04265203445935122,
    0.5699980916406838,
    0.6966198468604334,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ]
}

**To Reproduce**
1. Add up hit rating manually from each tooltip. 
neck (52) + chest (78) + wep (44) + off had (58) + wand (33) 

**Expected behavior**
should = 265 but it is only getting you 258

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Here is a link to the same gearset on eightyupgrades that shows the correct amount of hit rating: 
https://eightyupgrades.com/set/bc5XvLDVPPYgvLBUCd6J4p

**Comment by jarveson** [comment]
db updated to match wowhead tooltips
