### ISSUE TITLE
Standard deviation of stat weights looks wrong

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#2127]
**Describe the bug**
When asking the simulator to compute stat weights, standard deviation is displayed after each actual stat weight. These numbers look quite suspicious to me and I'm reasonably sure they are incorrect.

I made two tests. First test is on my feral druid. Standard deviations reported look like this:

Strength: +/- 1.79
Agility: +/- 1.79
Attack Power: +/- 1.79
Melee Hit : +/- 0.00
Melee Crit: +/- 1.79
Melee Haste: +/- 1.80
Armor Pen: +/- 1.79
Expertise: +/- 0.00

Both Melee Hit and Expertise are over cap on my simulation, which explains the lack of deviation for them. All other stats have 1.79 or 1.80, which is suspect. Also this number is simply too high to start with, it even exceeds the weight of some stats. For example, AP weight is reported as 1.00 +/- 1.79, which means it could be reasonably anywhere within range -0.79 to +2.79. Negative values are simply non-sense to start with, so this can't be correct.

Second test is on my rogue. Standard deviations reported look like this:

Strength: +/- 1.01
Agility: +/- 1.01
Spell Hit: +/- 0.00
Spell Crit: +/- 1.01
Attack Power: +/- 1.01
Melee Hit : +/- 1.01
Melee Crit: +/- 1.01
Melee Haste: +/- 1.01
Armor Pen: +/- 1.01
Expertise: +/- 1.24

This time, value 1.01 is reported almost everywhere, which is pretty suspicious. And it is still way too high. I would expect the standard deviation to be a small percentage of the stat weights, like the standard deviation of the simulated DPS itself (typically around 3% of the DPS value).

**To Reproduce**
1. Click on the Stat Weights button.
2. Click on the CALCULATE button.
3. Wait for the simulations to be over.
4. Look at the standard deviations displayed.

**Expected behavior**
I would expect standard deviation to be small, and vary a bit from one stat to the next. For example, I would expect Haste rating or Critical rating to incur more noise and thus have higher standard deviation, compared to AP or Strength which should have almost none, as they only change the damage in a way that does not depend on RNG or affect timings.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.3
 - Browser: Firefox 
 - Version 102.5.0esr

**Additional context**
I'm not sure what exactly standard deviation is supposed to represent in the context of stat weights. How are you computing it?

**Comment by jdelvare** [comment]
I took a look at the code. I'm sorry to say I don't think the way the stat weight standard deviation is computed makes sense. Which easily explains why the numbers are way off.

As I read the code, you are computing the standard deviation on the DPS value over 3000 runs with stats unchanged, then you are computing the standard deviation on the DPS value over 1500 runs with one stat decremented. You combine these 2 numbers together using a formula that I can't make any sense of. Square root of the sum of the squared value of the standard deviation of the DPS of both series? Why? What is this quantity supposed to represent?

This is mathematically wrong. The number you obtain has nothing to do with the standard deviation of the stat change in question, it is solely related to the variation of the DPS itself over the 3000 baseline iterations and the 1500 iterations with one stat decreased.

If you really want to display the standard deviation of stat weights, you have to compute it in a way that is mathematically correct:

1. Run your 3000 baseline iterations.
2. For each baseline iteration, do an iteration with the modified stat (ideally using the same RNG seed) and store the DPS difference (1:1 comparison with the corresponding baseline iteration). You'll end up with an array of 3000 values (half negative, half positive, given the current strategy).
3. Compute the standard deviation over this array. That will give you the actual standard deviation for the stat change in question.
4. Repeat steps 2 and 3 for each stat.

That being said, I would question the value of displaying the standard deviation for stat weights. It does make sense to compute and display the standard deviation of the simulated DPS because we do expect variation there, it is clearly visible in the DPS histogram, and there are a number of factors which will affect the variation range and thus the standard deviation (for example, increasing the weapon damage range will increase the variation range, while increasing the hit rating under cap will decrease the variation range).

On the other hand, do we expect significant variation when changing one stat by a small amount? I don't think so. So I'm not sure these numbers are worth computing in the first place, and it might be better to simply drop the whole code for simplicity.

**Comment by jimmyt857** [comment]
Hey thanks for the report! And an ever bigger thanks for actually looking at the code, most people don't get that far. A few clarifications:

1. Assuming the default 3000 iterations, both the baseline and the modified sim run for 1500 iterations. This is because we do 2 modified sims: one with +X, and one with -X.
2. The confusing formula you noted is how the standard deviation of a difference between two distributions is calculated: https://stats.stackexchange.com/a/186545. Your suggested strategy might still be better though.
3. We do hold RNG constant, and our RNG seed for each iteration is `initialSeed+iterationNumber` so we are using the same RNG seed for all corresponding iterations in base vs modified.

I'm planning to make another pass at stat weights soon because there are other issues with it, so I might attempt your suggestion and see how it goes. The justification for including standard deviation is to give the user some sense of whether they need to increase the # of iterations, although I'm not sure we actually accomplish that today.

If you have any other suggestions, please feel free to offer them!

**Comment by jimmyt857** [comment]
Tried out your suggestion and it does work way better. Thanks! Feel free to open another issue if you see something else wrong.

**Comment by jdelvare** [comment]
Thanks for the detailed answer and the quick resolution.

Answers on Stackexchange are usually of high quality and this one was no exception. The formula mentioned for the combined variance of two series of data is correct: contrary to the popular belief, when doing a difference between two series of data which each have some variance, variances do not magically cancel each other but instead tend to add up.

However this only holds if the series are independent from each other. In the case of stat weights we are actually trying our best to make them dependent, by using the same random seed. This is why comparing the individual iterations and computing the standard deviation on these 1:1 comparisons gives more accurate results than the general formula.

Speaking of this, I have another idea that could possibly make stat weight estimation even more reliable. I'll create a separate ticket for it, as the bug reported here is already solved.
