### ISSUE TITLE
Make stats weight computations even more reliable

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#2147]
**Is your feature request related to a problem? Please describe.**
This is a follow-up of issue #2127. The bug reported there is fixed now, thanks, but it made me think of another implementation change that could possibly improve the reliability of stat weight computations.

**Describe the solution you'd like**
After commit 4c0e4fa0c5338bf7033a9a8d57202221e27f69f8 ("Fix EP stdevs") the standard deviation reported for stat weights makes sense. One thing which stands out of the numbers now is that we really have two different kinds of stats (as observed on feral druid and combat rogue, may be different for other classes):

- Strength, Attack Power and Armor Pen have no standard deviation at all. The reason is that we use the same random seed when evaluating the stat change as we used when computing the baseline value, and these 3 stats only change the damage made by each attack. They do not change the timings, nor the chances to proc a trinket or talent or gain a combo point. So just having the same initial random seed is sufficient for the whole simulation to be exactly the same sequence of events, with just the damage values changing a little bit. Therefore evaluating these 3 stats (for these 2 classes) is very reliable. Actually, you could compute the theoretical weights instead of simulating them and you'd get exactly the same results.
- Agility, Melee Hit (under cap), Melee Crit, Melee Haste and Expertise (under cap) do have a standard deviation. The reason is that they do change either the chance to miss or deliver a critical hit (which it turn can have an effect on the acquisition of combo points, or trigger talent or trinket effects) or the swing timer and GCD duration. These changes, no matter how small, mean that at some point during the stat weight test simulation, the course of events will start diverging from the baseline simulation. A consequence of that is that our calls to the RNG, even though they will return the same numbers as during the baseline simulation, may use the results to make different decisions. For example, an increase in Melee Haste value means we will do more white attacks during the fight. For each white attack, we "consume" a RNG call to decide what happens based on the attack table. Meanwhile, yellow attacks are still energy-bound and thus not faster, so we will reach a point where a RNG result that was originally used to determine the outcome of a yellow attack, will instead be used to determine the outcome of a white attack. And all following RNG calls will be shifted by one. This is where the deviation comes from.

If we want to have a more accurate estimation of the weight of these stats which do affect the timeline of events, we need a smarter way to preserve RNG results between the baseline simulation and the stat weight test simulation. It is not sufficient that the same sequence of random numbers is returned, we also need to use these numbers for the same purpose. So we would need to save the actual results of all RNG calls together with the use that was made of them (decide the outcome of a white hit, decide the outcome of a Shred, decide the outcome of a Rip, decide whether a trinket procs, etc.) and read from these predefined random number tables during the stat weight test simulation instead of calling the RNG. This would minimize the effects of random for the purpose of estimating the effect of the changed stat.

Important note: for this to work, you really must save the raw number generated by the RNG, **not** the outcome, as the same number could have a different outcome after changing the stat (specifically for all the stats which change the attack table).

This is a pretty big implementation change, only affecting the stat weights (and not even all of them) and probably only to a small degree. This is in no way a priority, and might simply be considered too much work or complexity for the expected benefit, but I thought I would still mention it in case you would like to explore this idea.

**Comment by Tharre** [comment]
>  It is not sufficient that the same sequence of random numbers is returned, we also need to use these numbers for the same purpose.

This is (mostly?) at least in theory already done, i.e. if you want a random number that is used to determine if the molten core talent procs you call `sim.RandomFloat("Molten Core")`, and that will return the same array of numbers regardless of other calls done for instance to determine trinket procs.

I'm assuming that's also how all the attack table stuff works, though even if it doesn't that would be fairly straightforward to fix.

**Comment by jdelvare** [comment]
Oh, very nice then. Now I feel ashamed I did not read the code more in depth before posting my feature request. I wrongly assumed this wasn't implemented yet because you still set a common random seed for all simulation runs, which I don't think should be needed if you use pre-filled random number tables (but I may simply be missing an implementation detail).

Anyway, if this is already implemented then perfect, thank you :-)

**Comment by jimmyt857** [comment]
Looks like @Tharre beat me to the response, but he got it right. Since this thread is named sufficiently generically, I'll offer an alternative issue which I still want to address and I'm curious if you have any thoughts.

The problem is that stat weight computation makes the assumption of a smooth weight slope. When we add +20 Hit Rating or -20 Hit Rating, each point is supposed to contribute roughly the same amount of damage so that when we divide by that +/-20 later, we get an average. However, in reality there are many stats which have soft and/or hard caps, sometimes multiple different caps for a single stat.

Personally I believe we should always try to return the 'instantaneous' slope value, i.e. what we'd get with infinite iterations and +/-0.00001. To accomplish that we already have the beginnings of a solution here: https://github.com/wowsims/wotlk/blob/master/sim/core/statweight.go#L239. The idea is that when close to a cap, instead of doing both positive and negative mods, only use the direction which does NOT cross a cap threshold. This preserves the assumption of smoothness.

The reason this is still a problem is that there are a surprisingly large number of caps and many of them are tricky to identify, either because 1) many caps are different than what we would infer by looking at character stats alone, due to dynamic effects from talents / buffs / etc, and 2) some caps are extremely subtle, such as increased haste reaching a breakpoint allowing an additional cast to fit into a rotation cycle.

**Comment by jdelvare** [comment]
Thanks for sharing the implementation details with me. I did not expect that to be possible, because the low-level programming languages I'm used to only allow one RNG instance per thread. Good to know that modern high-level languages offer more possibilities in this respect.

**Comment by jdelvare** [comment]
Here are my thoughts about caps (and the current stat weights computation), feel free to pick what you like and throw away the rest. I apologize in advance for the long comment.

I did notice the handling of hit caps for the stat weights computation. As far as I can see there are 2 different cases being handled, with 3 different outcomes possible (correct me if I read the code wrong):

1. The baseline hit is under cap but hit would go over cap after adding the stat mod. We are far enough away from the cap that we can trim the stat mod (to a minimum of half the original stat mod) to make baseline + stat mod stay under cap.
2. The baseline hit is under cap, hit would go over cap after adding the stat mod, and we are too close to the cap to trim the stat mod. We basically skip the statModsHigh simulations and instead run the statModsLow simulations twice.
3. The baseline hit is already over cap, adding the hit stat mod will obviously be over cap as well, subtracting the hit stat mod may or may not be over cap. We "only use the direction facing away from the (...) cap" according to the comment.

(As a side note,  this raises performance concerns. For case 2, we run the same simulations twice, so we could cut the simulation time in half with the exact same results. For case 3, we discard half of the simulations we have done, so it would have been faster to just not run them in the first place. But one could argue that going over cap is a corner case situation that isn't worth optimizing.)

Note that I believe the implementation of case 3 is actually broken. The comment implies that we should discard the statModsHigh simulations (because they are over cap) but as I read the code, we actually discard the statModsLow simulations. This is confirmed by experimenting with the online simulator: if I set the Spell Hit of my rogue to 17.01% and compute the stat weights, Spell Hit is reported at 0.00 EP, which corresponds to an over cap situation. statModsLow would be under cap and should return a non-zero EP.

My opinion is that caps should not be considered during stat weight computations. Stat weights have limitations, any player using a simulator should be fully aware of that, and caps are one of the factors that can make certain stat weights irrelevant. You try to mitigate that limitation by making the code smarter, and I understand the intent, however I don't think you are actually doing users a favor by doing that.

1. As detailed above, you have kind of a hidden decision tree to deal with the caps. Users who have not read the code have no idea that this is happening. Slightly different baseline stats could cause different paths to be taken in the decision tree, leading to a different logic being used. These different paths in the tree are not guaranteed to give continuous results at the transition points. This means that the user can see unexplained jitter in the results. When this happens, users tend to lose confidence in the tool.
2. Hiding the fact that we are close to a cap may cause the user to discover it the hard way later. I would personally prefer to know early that I'm very close to being capped, to make better decisions when rolling on gear or getting my gems cut.
3. You only deal with a limited number of caps. As you rightfully explained, there are many more soft and hard caps. The user has no way to know (again, short of reading the source code on a regular basis) which caps are being "mitigated" during stat weights calculation and which ones aren't.

If I'm right about the suspected implementation bug above, the fact that nobody noticed in over 3 months (I think the bug was introduced by commit b0fadb9777e582be5d2a6072989949af317af48bso on September 1st, 2022) would be a good hint that this feature is not really needed.

So I'd rather keep the code simple (best way to avoid nasty bugs, by the way) and instead warn the user about the limitations of the stat weights calculation. Specifically I would suggest the following:

1. Print a short explanation when opening the stat weights, about how stat weights are only valid at the point where they are calculated, and will change as soon as you cross a cap.
2. Detect when caps are being crossed, but instead of trying to mitigate that, simply report it to the user. For example color the number in red and add a hover text explaining that the stat is (or will soon be) over cap and thus the calculated weight should not be trusted.
3. I also think it would make sense to let the user know how much is added / subtracted to perform the test. It used to be +/- 10, that was changed to +/- 20 recently with no rationale given. The user doesn't know the value. It might even make sense to let the user change that value.

Now, about how to deal with the caps. I think they are a different topic from stat weights and should thus be tackled completely separately. Stat weights are only valid at a given point and should only be used to make quick decisions and get a general idea of the relative value of pieces of gear. Dealing with caps requires a much broader view and long term planing.

What I envision is a separate feature, opening its own view (like we have for stat weights), that would focus on only one stat at a time. The user would give the range over which the stat should be tested, and a step. Everything else would be taken from the current simulation settings. After running all the simulations we would draw the evolution of the average DPS for the requested stat values. Discontinuities or inflection points in the graph would let the user identify cap points. Running the tool again with a smaller step value around the detected cap would allow refining the cap value. It would be the user's duty to then figure out what is causing that cap. Does that make sense?

**Comment by jimmyt857** [comment]
Thanks for the detailed response! It definitely makes sense. What I've decided to do for now is to take your suggestion of removing the cap logic, and we'll see if anyone reports issues. However, I'm keeping the autodetection for over hard caps, as removing it would definitely result in lots of bug reports from people saying 'I'm over cap but EP shows positive values!'
