### ISSUE TITLE
Warlock JSON imports failing

### ISSUE THREAD

**Issue by Lol420FunnyNumber** [wowsims/wotlk#2160]
**Describe the bug**
When attempting to import a json file to the warlock sim, it fails without a displayed error. An error is displayed within the dev console though.

Error Message:

Uncaught (in promise) Error: Unable to parse message proto.UnitStats from JSON array.

**To Reproduce**
Attempt to upload the attached JSON file via the import feature.

**Expected behavior**
The items import.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/warlock/)
![jserror](https://user-images.githubusercontent.com/50419340/207747442-aaea6f09-4aae-401e-9b50-9e944e75d66a.png)

**Comment by Lol420FunnyNumber** [comment]
Assuming this PR is causing the issues https://github.com/wowsims/wotlk/pull/2156

@jimmyt857

**Comment by jimmyt857** [comment]
If you're seeing this issue, its probably because you saved the JSON export from before that change. You can fix this error by finding the `bonusStats` array within the JSON text and deleting it.

Newly-exported JSON data should also be fine.

**Comment by jimmyt857** [comment]
Going to mark this closed but feel free to reopen if you have more issues with JSON imports.
