### ISSUE TITLE
Crash Report -1696889646

### ISSUE THREAD

**Issue by crx-au** [wowsims/wotlk#2177]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE78HIwKTAaMDowBjAWMKxgZhRik5rA2MbIF5CRWphZxMApwSO1l5OIXeLqbSeKNrBLb0UNMn3cwcXEKfL3DpMR8C8jkEXgBlHskq8S8D8x7ep1JoksWIscv8AjI+8GhxAaUAwnwCrTtYpKYI6TEAhRgAHLPbGGSmCKjxHLvMJDLI/BxD5PERBmIUfwCz4AGL5ADa/4INrsNKDANKH0OyGMROL8bRPbvA5Gv9oLIj8uZuNgFVgIN6ZfjYgAKNG1hUuLiYDRgtGAMYI1gXcQEVDaDiWEUYAVCCoRUVHEAkwSTBFMBY5YEMD5YJICpRwMUvEzAhMMGlAOKdDGqGxmbGhgYGBkYAwljU0MDI1OQgLGxoaGpoa6uKUjSwMDU8BGjBMfcdmaBm0+ZJC4/ZVJousyk8e8Sk0HjZaYXjCwfGNlnMTJ0QmPL0uEWI8MsJgalp0ycYIGGNAdBiJSIg+SsmSBw0t4SInLBXjENDK7ZG21lUgiW4NCiday3OFDDlIaTR6hiDikAEmY+dx0cIfwf9h6MCYxBWHNKtcg694dVLfZc1xcX2HIdt/d4WAUSsYfIfrCHqTv8VSOm/9Bb+28g6usD+zeBO+RaX7+0RzdvqALCOQUAoaCWXQ==

RNG Seed: 0

No enchant with id: 3820
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:47 +0x10
panic({0xbd4a0, 0x1771670})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.NewItem({0x9de5, 0xeec, {0x1773218, 0x2, 0x2}})
	/home/runner/work/wotlk/wotlk/sim/core/database.go:211 +0x22
github.com/wowsims/wotlk/sim/core.NewEquipmentSet({{0x9de5, 0xeec, {0x1773218, 0x2, 0x2}}, {0xae75, 0x0, {0x1773220, 0x1, 0x2}}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/database.go:240 +0x5
github.com/wowsims/wotlk/sim/core.ProtoToEquipment(0x17fc440)
	/home/runner/work/wotlk/wotlk/sim/core/database.go:247 +0x9
github.com/wowsims/wotlk

**Comment by crx-au** [comment]
Crash occurred after page load when clicking to select my gear set named "Current".

Sorry if this isn't helpful!

**Comment by jimmyt857** [comment]
It sounds like you might have some weird outdated data in that saved set. Try overwriting it (even if its with the same gear) and that will probably fix the issue.

**Comment by crx-au** [comment]
> It sounds like you might have some weird outdated data in that saved set. Try overwriting it (even if its with the same gear) and that will probably fix the issue.

This solved it, thank you! :)
