### ISSUE TITLE
Warrior shield wall is still using the tbc talent bonus to determine length

### ISSUE THREAD

**Issue by mpuryear** [wowsims/wotlk#2182]
**Background**
Warrior shield wall is now baseline 12s. T7 4p increases this to 15s. The talent referenced in the following line now reduces the cooldown instead of increasing the duration. 

**Culprit**
https://github.com/wowsims/wotlk/blob/293bc26c2dc865f5f49b1253997419137bf6a18a/sim/warrior/shield_wall.go#L15

**Comment by psiven** [comment]
Fixed #2211
