### ISSUE TITLE
Warrior shield wall currently on the GCD / Shield wall sometimes failing to activate entirely

### ISSUE THREAD

**Issue by mpuryear** [wowsims/wotlk#2183]
**Background**
Warrior's shield wall got removed from the gcd when wotlk came out. Utilizing the prot war sim I noticed shield wall, last stand, and trinket usage was being delayed when the CD timing option was set to 0. 
![image](https://user-images.githubusercontent.com/17075809/208076487-bb0a7ea0-3e32-468d-be30-2b46793d803f.png)

![image](https://user-images.githubusercontent.com/17075809/208076422-5bda32b4-f3c8-43ad-9046-46a45722781b.png)

**Likely culprit for shield wall**
https://github.com/wowsims/wotlk/blob/da31e3c108f01405f6d24a96e62f5bb61a485301/sim/warrior/shield_wall.go#L40-L49

**Comment by psiven** [comment]
Gcd should be fixed. I think there are still some issues with the hp% auto fire behavior conflicting with set timings so more evidence on this would be welcome.

**Comment by TheGroxEmpire** [comment]
Closing the issue as it seems to be fixed.
