### ISSUE TITLE
Unable to Import JSON.txt

### ISSUE THREAD

**Issue by drewpop24** [wowsims/wotlk#2200]
The 'IMPORT' button doesn't work and the window will sit idle.  The only thing that has worked was restarting my computer.  Still then, was only able to import one JSON.txt then it quit working again.

1. Hover over 'IMPORT' on top bar
2. Click on JSON
3. Paste in JSON.txt from Notepad
4. Click 'IMPORT' bottom right corner
5. Nothing happens

Normally, clicking 'IMPORT' would exit from the JSON Import window and refresh the sim page

 - Windows 10 Home
 - FireFox / Chrome
 - 107.0.1 / 107.0.5304.122
 - Have tried both browsers with the same issue

I have tried refreshing the browser window, exiting FireFox/Chrome completely, and also updating to the newest browser versions.  Have also tried importing using the "UPLOAD FROM FILE" function with same issue.

**Comment by jimmyt857** [comment]
I'm not sure exactly what this issue is without seeing your input. Feel free to reopen if the above change doesn't fix it.
