### ISSUE TITLE
HP inconsistencies

### ISSUE THREAD

**Issue by psiven** [wowsims/wotlk#2213]
**Describe the bug**
Tracking reports of health pools inconsistent with in-game observations. Total HP should exactly match ingame values with a given set of buffs.

**How You Can Contribute**
Please include the following evidence:
- Screenshot (still/vod) showing your max HP and active buffs; or raw numbers that you got while knowing what your buffs and gear were. WCL is often not good enough to trace your buff state. 
- Exported link of your sim session wearing the same gear set (addon will facilitate this) and using the same buffs
- Max HP you have in that gear set while Unbuffed (ideally)

**Comment by jarveson** [comment]
Should be set from #3578 , base health was wrong almost everywhere
