### ISSUE TITLE
Ability to swap weapon

### ISSUE THREAD

**Issue by DoktorVanHelsing** [wowsims/wotlk#2221]
It will be nice to have option to swap weapon in the middle of sim boss fight.

I am playing as warlock and from my perspective is worth to start fight with wand, weapon and off-hand which have a lot of crit to put corruption with big crit % stat. After putting corruption I should change to normal weapon set. Due to corruption skill specification it will stay with big crit% until I recast it.

What I think that option should have:
- ability to choose with which wand, weapon and off-hand I will start fight
- ability to custom spell rotation before and after swap
- ability to choose after how much time roattion will be made ot choose to auto swap after end of custom rotation
- ability to make more than 1 swap

**Comment by jarveson** [comment]
related draft pr is in works #2241 for weapon swaps, also related issue #1281 but for dk

Tagging this one for 'warlock' for now, since each class rotation may have to be updated a bit to handle this specifically

**Comment by rosenrusinov** [comment]
Unholy DK has been updated to use the new Item Swap functionality (albeit to almost no dps increase after the nerfs to gargoyle)
Fixes #1281
