### ISSUE TITLE
Mind Flay ticks trigger Judgement of Wisdom

### ISSUE THREAD

**Issue by jvyth** [wowsims/wotlk#2239]
**Describe the bug**
Mind Flay ticks are incorrectly triggering Judgement of Wisdom mana returns, resulting in way too much mana being returned to the priest.

**To Reproduce**
1. Run any Shadow priest sim config with Judgement of Wisdom active under **Settings**.
2. Click **Log**, 
3. CTRL+f search for "Judgement of Wisdom". Look for an instance where Mind Flay is the trigger.

**Expected behavior**
Mind Flay ticks should not trigger Judgement of Wisdom.

**Sim Links and Screenshots**
Example sim [link](https://wowsims.github.io/wotlk/shadow_priest/#eJztU01oE0EU3veyjdNJYoY9yBi7uCwIsVC62WWhnrJ68hRCvfQg0iiVgh5CEaoFoYr4U9EelFJDwehF1IMFIdSkxhLqQSIVclGKXgItAWsJSqH0orPZRFTUIupB8Dt8zLzv+97bhTdUJ8iwB/bDIJyEUYBJgCxkd04DzgG8AqgB7AsS4GCAI1x9oEiRW/6z4E8eT50aGCJ+1hbJAQ2z97PIV1Td/7SExRmk7WztNeq+RXEMsstCq6q6r9i4Lb1EPqZ6WpjdyyNfJ7pfaK5M2cMc8ilFB4mG2HkRvN6hyx9mUBIt3+XRaxJmCwXkF9TPsS1sVVgnOqjMxoso+EXB5Sd5l+sF11AWiQ1VXDceu8VsDvUQASOQlPva+uEiwG0UwiRK//FdKNpmjpEAAYYc0zAN0LuDhoiPwfaGNHfYEYtDhA4aRGEMdhm2YZmGFevqskzbMC3DjpmCY4bgmO2eLDtWBU7ulJE9KCN/tITa2wpGVyporFawBnIdAhm4CpRTmZy5ggprfofjjTzq0AjdSi5t0z62AArxLMShutCeJ77UmvmEl+9POZSJRbmWx1Yq4VBNzFq+71P417/ezEiHnEWQMijpC9jeqpglTE+dHgkmUyeODA4PDB3TTFs7wEnn3961c86f6DL6bP53+hg9nem9vxra0xg8UXWayVq896dvM3PDxd347oPjpbXobNyr1uPf+oaLNyPdb+Z/qP+r2PxtfgJxKqcG).

Example of incorrect trigger in Log:
```
[3.86] [Player (#1)] [Target 1] {SpellID: 48156, Tag: 2} [DEBUG] MAP: 755.7, RAP: 755.7, SP: 3429.0, BaseDamage:1390.8, AfterAttackerMods:1746.3, AfterTargetMods:1973.3, AfterResistances:1776.0, AfterOutcome:1776.0, AfterPostOutcome:1776.0
[3.86] [Player (#1)] Mind Flay (2 Tick) Hit Target 1 for 1775.99. (1775.99 Threat)
[3.86] [Target 1] Aura refreshed: Misery.
[3.86] [Player (#1)] Gained 2.8 Mana from Judgement of Wisdom. (20608.2 --> 20611.0)
[3.86] [Player (#1)] Shadow Weaving stacks: 3 --> 4.
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux / Windows 10
 - Browser: Firefox

**Comment by dbyena** [comment]
JoW is definitely giving more mana than it should, but I do not think it's related to MF proccing it. It looks like JoW is just proccing  a lot. Also, why do you think MF ticks cannot proc JoW?

**Comment by jvyth** [comment]
It's a conclusion I've arrived at by looking at WCL. Comparing JoW proc timings to MF ticks and other spell cast timings, JoW procs line up with spells landing rather than MF ticks. For example, compare timestamps [procs](https://classic.warcraftlogs.com/reports/k6RfabPDV7xrJ3KC#fight=4&type=resources&source=16&spell=100&ability=20268&view=events) to [casts](https://classic.warcraftlogs.com/reports/k6RfabPDV7xrJ3KC#fight=4&type=casts&source=16&view=events) vs. [mf ticks](https://classic.warcraftlogs.com/reports/k6RfabPDV7xrJ3KC#fight=4&type=damage-done&source=16&view=events&ability=58381). If MF ticks could trigger JoW I think, shouldn't they account for most of the procs? It's by far the most frequent hitting ability. Unless it would, for some reason, have an innately lower chance of procing.

**Comment by jvyth** [comment]
User glucera#5830 on Discord suggests a 4 sec icd on JoW procs for spells being the reason for why the behavior is observed in logs:

> 4 second icd on spells JoW needs to be in sim, melee has no icd its why shadowfiend + pets can proc it more, any spells casted within the 4 second window of icd are ineligible to proc it including mind flay the initial application + damage ticks will not proc it extending portions of no JoW past 4 second icd. also spell batching / queueing happens and can multi proc if situations happen where you queue a mindflay after a hard cast MB-> flay (if in an eligible window you will get multiple JoW ticks in succession)

So MF ticks not being able to trigger JoW could be functionally right, but maybe not technically?

**Comment by lime-green** [comment]
JOW was fixed here https://github.com/wowsims/wotlk/pull/3119 so that initial application can proc JoW but the ticks cannot
