### ISSUE TITLE
Crash Report 1498002440

### ISSUE THREAD

**Issue by Orangejulius420** [wowsims/wotlk#2274]
Link:
https://wowsims.github.io/wotlk/shadow_priest/#eJztUz1oFFEQ3m/ux836k+dxxTN4sm51CoG3uxxoIW+1MYXFES1SWGhhKovDzlRnylgkhYUeFhItgkgQjaeYyxGCKYIg4YoEggoGDsNFZFGCh43O3pLKaBCSQvArhvn55mOYN8+yTRKk6AT6MIASlYEx4DFoFlgE1oAz3SZsUghQRAkTQMboGU8NI128evn6lWtmQqR6HsHqFj+ekPyUc9LzcxS+IKtLbLwlJ7HC7j5xs0ZyNeck6hztESPzJL/luOXhS5JtbmHSV65Y4mmV5N2MA8PaL1pTJG8ddpIsZrBEe4acNPfHEiEL3jvCTpUlvuSspHg+TWxH65FtzUS2Ph0xJ5j5JiIsVaPk8BQ5pgmFYmogNU5MvE3Gf2yJjL0dY4hXKUhSCf0HLDITfBtpPhfkMYILBeX7Svmu7/ueKrhe5Lq+57pewe31PC66igm/oHeL3CZWIc1ak8Rsk+SD12SvNyj/uUGq1aA1JEPsrcBYgVEhw2lSV2fG8mBwMJ42Gxyq3ImwoE/GmUV9dLCDJe09I/u8NI/v8jmEN4KdkCkvvNoRnb9BvLNz74LTcdzWfbiE/j9+oWMXR+c28jWdnTz7YSj7XsfZUG/Wl++XTlnL67pTnvyo49f4rn+n969h+y/0E8Npk9w=

RNG Seed: 1600364213

runtime error: index out of range [0] with length 0
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0x16b320, 0x145a8d0})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Raid).ProcReplenishment(0x1466140, 0x2051d90, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/buffs.go:1172 +0x5c
github.com/wowsims/wotlk/sim/priest.(*Priest).registerMindBlastSpell.func1(0x2051d90, 0x17e4000, 0x143a800)
	/home/runner/work/wotlk/wotlk/sim/priest/mind_blast.go:65 +0x42
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x143a800, 0x2051d90, 0x17e4000)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:423 +0x23

**Comment by dbyena** [comment]
Should be fixed with https://github.com/wowsims/wotlk/pull/2277
