### ISSUE TITLE
Mage Simulator - Crit Rating from gear overstated

### ISSUE THREAD

**Issue by Jedanas** [wowsims/wotlk#2286]
**Describe the bug**
After selecting gear out, I noticed the crit rating is overstated on gear values by 372. I had navigated from other gear outs so it could be a value not resetting when selecting a new phase/gear list.  

**To Reproduce**
1. Go to mage simulator. 
2. Create new gear set. Select gear. 
3. Navigate to P1 BIS  gear. Toy with gear. 
4. Navigate to Preraid BIS gear. Toy with gear. 
5. See error

**Expected behavior**
I expected the crit values to match what I see in game from gear. 

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

Sim gear out values: 
![image](https://user-images.githubusercontent.com/121972542/210626942-56c1dac7-86c6-4818-a2b8-ba46da2e4836.png)
In game gear out values: 
![image](https://user-images.githubusercontent.com/121972542/210627018-6ca19e37-d619-4868-a731-6dfaa58e296c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 108.0.1462.54

**Comment by jimmyt857** [comment]
Thanks for the report! This is likely just a visual bug due to a quirk in how we handle crit internally, we currently convert int --> crit rating (and for mages, spirit too) before it gets recorded for that stat. Going to leave this issue open a reminder to address this.

**Comment by jarveson** [comment]
Likely fixed from #3578 now. without an actual link to what gear is used the one below has 22.8%
Biggest issue here is probly that the ingame screenshot does not have buffs nor molten armor on, yet the wowsims screenshot does. fwiw templated ptr 80 matches w/ brilliance and both with and without molten armor

If its not fixed still, a link to wowsim setup is borderline mandatory here

https://wowsims.github.io/wotlk/mage/#eJzjYrJgdGIQYpC6wNrEyBaQk1iZWsTBJcAstZORi1/gwW4miTeySmxHDzHt28HExSnw9Q6TEvMtIJNH4DFQ7pGsEvMHII9doOsok0SXLFDLI6DwD6AWoHqQDJfAkn1MEnOElBgZuHgF7gMlp8gosQAlGYBG/NjLpMQGVAUykF/gIVCyHaGTR+DsLiaJaTIQG1gEHv8Hkf37QOTH5SDy1V6QzWeA2n7JArm/9oIEvy1iUmJYxPSViesAE8MooAgIGZCqo4rBSZ5LpJFx1kwQOGnfyWgMBoftpdglkpUYNNYwdTFqGxkbGBiYGhgbGgJpY10gG8gxMDAEigPVGhqYGhsaAQUMjU0NHzFKcHw+yyTw/yyTxMqnTApPLjFpPLjEZPDjHtMLRpYPjOyzGBkOMTGcYDrB2AmNb0uHW4wMs5gYlLqZOcECDWkOghApEQdJmMssISIX7BXTwOCavdFtJoVgCVYtGqcbjU4HahjTcPIIAXOCqWIPOQAStnvfOzhC+D/sExiD8ObIHXKtrwN33LN/WCWyzv3hLXuI6Ad7ruuLC2y5ttsHgRXcsO8/9FUjpv+RPUhVlcg7e5p7ZZAB0nNkFFTHB6LDCgDv0pzG
