### ISSUE TITLE
Metagem is calculated even if the requirements are not met

### ISSUE THREAD

**Issue by milkisbad** [wowsims/wotlk#2296]
**Describe the bug**
Metagem is calculated even if the requirements are not met

**To Reproduce**
1. Go to https://wowsims.github.io/wotlk/hunter/#eJztU01oE0EU3u9t0mwGJWMR2YakTfcUhMJuQ8AIZdZ6MAcPVS8e60FPHkJPbU8qFEo9CSoxl4o/4EkEsTS2hYo9GLFYUki0NFKFQMWCEVFyq2+zehAVCcSbH/vezuyb73tvZ96IqEGSbDqEERpFjqZBD0BrwDYwLA0kKAkX47gH5AndWnQ3eAldI+fPTJwd85jRhxARWVwk833c6pp7SrMlEmHZ3CRL94Z75ALHtuKWvjRPIiTXF8i8FmPKmyqZTabwIi+yV248JnOq1wrwTBNC1ph2NWZBY4nyHJlXYr5ERF5miY/M5Fll19Os89LrMRGQM0ViX1j0/M6S52uvvQUrzPgcFxoPn/AwH7MiBtk6/3PgdGAc08AtWiWRJ+0/fotuu13GpGFAkkk5HJ4QR7NIkoF9rYg76w4nBBlBthBbmM1gE2w6G7HBKdzwUFSZVAvrilvP5obrix5gD25KPavngWXoz4BXQL+ft6Eyqy887KgkZpBM286AbadTdtoZSNuM1KD38jT5q+M4HHL4eQfTuFsnefMlmXfqlKiWKfm8THalTNsINBAqQNuAViDN2qRwK9XymNvjl1lSGT/7muo/10JFDT6ixCnTOPiPm6px0e2EzIXSSkd02oG/Z8dr7hF/3lRZjOLkTxfRP/3g99q2lL/fn1SHSnB/ZB4S1du5oa+qb+rDifneL23qNzpVz1/x60XMvp3cf/9Yj/snxjf2PqNB
2. Click on simulate > save as reference
3. click on helmet > meta gem > unequip
5. Click on simulate 
6. See error

**Expected behavior**
the simulations should be the same (1st doesn't meet the requirements for metagem and 2nd doesn't have metagem)

**Sim Links and Screenshots**
sim numbers for my simulation (-197.43 dps)
![image](https://user-images.githubusercontent.com/53466794/210958412-078f71d2-b8b9-4d99-96a4-7d2c5cf2bd9d.png)
![image](https://user-images.githubusercontent.com/53466794/210958438-e410a7c1-4477-4566-b4a6-5d72efa00ddc.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome
 - Version 108.0.5359.125

**Comment by jarveson** [comment]
the gear in ur link includes a nightmare tear, so metagem is active, remove the nightmare tear then retest with/without meta
