### ISSUE TITLE
Crash Report -898618713

### ISSUE THREAD

**Issue by ezizet777** [wowsims/wotlk#2300]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE6iHIwKTBqMBowWjA6MASBVjCsYGYUYpE6zNjGyBeQkVqYWcbALcEk9YeTiF9j5mEnijawS29FDTPt2MHFxCux+yKTEvPsZExePwI4XTBKPZJWYF5wE8TY9YZKYLAfhAfUB5X5wKLEBNX0G6uMVaAMaNEdIiQUowMAlIPAQqHqKjBI7kAsWERLYDBSZKKPE+RmsA2SZkMAGoKZ2WSVOoJlAsVs7QCaff8AkMU0GbjKnwL3nQBdBHLf9MZAJUsYicO4xiJz1GOS0LUCjf8lCFLEIbHwCUvruIUSXkggHOCwCWCJYE5gqGIEh1sHIuIjpLBPXDCaGUYAVCBmQqqOKg4NRgEmCqYDxFyMbFwMwuTF0MaoZGZsaGBgZGRgYGgCZQMIURBobGxqaGurqmgIlgcD0EaMEx9x2ZoGbT5kkLj9lUmi6zKTx7xKTQeNlpheMLB8Y2WcxMnRC48rF4RYjwywmBqXHTJxggYY0B0GIlJ2D5KyZIHDS3hIicsFeMQ0MrtkbbWZSCJZg0qJ1nJc4UMOUhpNHCJjjTRV7kAEkzDoOOzhCBRwSGIPw5pLSL9nn29PP2u+zLLF0t3xoDxH9YA+TX/zrYzZz4nP7hWetQ1aYPrZ//W/J0a2xb+1xmTfUAOm5BACMeacn

RNG Seed: 4245393343

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0x16b800, 0x145b110})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).registerScourgeStrikeSpell(0x21bc000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/scourge_strike.go:69 +0x6a
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).Initialize(0x21bc000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/deathknight.go:262 +0x9
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Initialize(0x1755800)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:181 +0x4

**Comment by rosenrusinov** [comment]
The link has a corrupted configuration with what looks like warlock setup on the dk sim
