### ISSUE TITLE
Affliction Warlock, Drain Soul.

### ISSUE THREAD

**Issue by Rhae23** [wowsims/wotlk#2301]
**Describe the bug**
When simming as an affliction warlock and looking at the damage breakdown, I'm seeing it getting in more ticks of "drain soul" on the timeline than are being accounted for on the damage breakdown.

**To Reproduce**
1. Sim as an affliction warlock (sample pool was 240s)
2. Click on "results" and look at Drain soul
3. Hits vs Cast were exactly the same, so I went to the timeline and checked it out.

**Expected behavior**
There should be more ticks being accounted for, and I think the damage being shown as the "dps" for the breakdown is incorrect.

**Sim Links and Screenshots**
(https://wowsims.github.io/wotlk/warlock/#eJzjUuRgEmAyYLJg9GCMYCxgamBkXMD4hXkDI9MBRsYLjIwvGBmdBDkYJRgVGA0YHUBKGFcwMgoxSC1jbWJkC8hJrEwt4mAX4JDayMjFL/B0N5PEG1kltqOHmD7vYOLiFPh6h0mJ+RaQySPw7hGTxCNZJeZ9YN7T60wSXbIQOX6B50B9P4D6gHIgaV6BF0DpOUJKLEAeA5D7Gqh3igyUyynwcQ8TxBx2gQ97mCTaZYGMd0DGNBkuFoHzu5mAZP8+EPkBzN6/C6TyDNCOX7JA7rVtIMGmLUxKPBxAT1kwBrBEsCYwLWI6y8Q1g4lhFGAFQgak6qji4mAUYJJgAqWZLCkuPiCPBZiOmDRAgc4ETEJsEJEuRnUjY1MDAwMjA2MgYWxqaGBkChIwNjY0NDXU1TUFSRoYmBo+YpTgmNvOLHDzKZPE5adMCk2XmTT+XWIyaLzM9IKR5QMj9yxGhk5oDFo63GJkmMXEoPSViRMs4FDgIAiREnGQnDUTBE7aW0JELtgrpoHBNXujo0wFc2qreAISS5IzylOLshWMTBWCJTi0aJw0PjQ6UMOYhpNHKDHHwEKrwJFUTeBAbJj2yAGq84V9ByNjENbcVC2yzv1hVYs9LPwfVoEEbtlDZD/Yw9Qd/qoR03/orf2SAluu64sfQOkX9ujmDVVAem4CAGEKnzc=)

![drain soul 1](https://user-images.githubusercontent.com/122127891/211106857-8a782817-935a-4c41-89db-485270fbdc6c.png)

![drain soul 2](https://user-images.githubusercontent.com/122127891/211106884-dbf9782a-1a52-4e56-8b62-6536d11cf6c6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by Tharre** [comment]
This was fixed in #2777.
