### ISSUE TITLE
Blood DPS issues

### ISSUE THREAD

**Issue by Saltyc0der** [wowsims/wotlk#2318]
1) No presence is shown being active under buffs on results (Not active at all?)
2) Blood Gorged's ArP part isn't being added to the stats panel (but it is active as far as i can tell from sim log)
3) Sim sometimes prioring HS over refreshing diseases (I can get this reliably happen when I set sim length over 140)
4) Sim is only recasting diseases for first DRW, all other DRW casts don't recast diseases

**Comment by rosenrusinov** [comment]
Fixed in #2379
