### ISSUE TITLE
Crash Report 749069167

### ISSUE THREAD

**Issue by Witzug** [wowsims/wotlk#2334]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUz9oE1EYv+/zbO9OS54hyBmaEm8qhcDLnQUd5J0udnCIdengYAfFwaF00rrUYkFcgiiSBkQ0CsVBXJQoDqVxKdiaIbEgaBtrakoFgyAGUet37zVOFluIm7+Dx/f7vt/3h3ffsxwDGXI8A0MwCjAJ8BBgCqAIUANoABYRD7M4cvBhgDSXpSasRZe3j0Fb6uzg+VPDRjuzogtghViuhvZKzGl7XMBCHi2TXVtCZ9szMneyexRbjCkWYsUPaH8lJbGqdNyicEM5AkUHW3iP9niXoxPTiN6m+PXOdRpiTyromEobyMNsbhHtTzHHrErH3KysSSVudP6uabK3zXF0Nl0JztVleb4MBrxKHe5Hm+MGbDLaVKefohMykHfsh5Q+oJ8L7uEOUpMMav/xR4T5VjNGdANs/AautZuWkhauD1IwKEN+2s8DRO1dSlkXcejZYaw1AVcgkfBczvd5vZzgJlyPc48+op6b7KUQT5Kd9JIeOZPvwDZulpB9rNKGlDCeKWF3pox8oow10OvQngXtNWhZ1JwqmrLn1LC/3j3i78lOBJgRB5SnKPaelngl3EcYP24bPf94MeoX/VaUGZ153pI6W4G6s6Nv/EOKN0QfnIR++ZgKX7pPpKdNfz43dNCaXxKbran+x4pQ+eUN8uoi3zW+eiz/U/RLoyZU3g9xN2iXq4nIgyOVkcjnDftekIJLm56rVQjz2RcBDF9N+v2vE/wCUQvRog==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:47 +0x10
panic({0xee680, 0x12e7f60})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.NewDeathknight({{0x0, 0x0, 0x0, {0x2000e40, 0xb}, 0x50, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/deathknight.go:369 +0xa
github.com/wowsims/wotlk/sim/deathknight/dps.NewDpsDeathknight({{0x0, 0x0, 0x0, {0x2000e40, 0xb}, 0x50, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...)

**Comment by rosenrusinov** [comment]
Can't reproduce so could have been recently fixed. @Witzug please re-open this issue if you still encounter the same error
