### ISSUE TITLE
Deathknight Talent Bug - Frost Sub UH w/ 1pt in Epidemic

### ISSUE THREAD

**Issue by Zixt1** [wowsims/wotlk#2337]
**Describe the bug**
I wanted to figure out how much putting points into the Unholy Talent: Pale Horse would cost DPS.  For About Phase 1 bis gear in Frost UH talent set up, my dps was around 8k.  Moving a few points around and having Unholy:Epidemic 1/2 results in the dps dropping to ~2k.

I'm no rocket surgeon but that doesn't add up.

Trying several different talent builds, Epidemic 0/2 and 2/2 works fine, it seems to only be related to 1/2.

**To Reproduce**
1. Starting with the Frost-sub unholy build, Run Sim Dps around 8k +/-
2. Take talent point out of Blood: Subversion
3. Add that talent to Unholy: Morbidity
4. Pull point out of Unholy:Epidemic and put it into Unholy:Pale horse.  At this point the talents have Epidemic: 1/2, Morbidity 1/3 and Pale Horse 1/2
5. Run Sim, dps was like ~2k a 75% reduction.

Take a talent point out of anything and raise Epidemic to 2/2 and it goes back up to ~8k.

**Expected behavior**
I'd expect the dps to change a little but not be reduced by 75% that much.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Browser: Chrome
 - Version: 108.0.5359.125 64-bit

**Smartphone (please complete the following information):**
N/A

**Additional context**
Trying further combinations of talents it looks like it's caused by having Epidemic 1/2 , both 0/2 and 2/2 work with no issue.

**Comment by lime-green** [comment]
It doesn't really make much sense to have only 1 talent point in epidemic since it can't do the Sub UH rotation because disease timings won't work with only 3s longer duration. It could fallback to normal sub blood but that might be even more misleading

**Comment by rosenrusinov** [comment]
@lime-green @Zixt1 can we consider this issue resolved and close it?
