### ISSUE TITLE
Comparing different items in the same slot

### ISSUE THREAD

**Issue by cyanophage** [wowsims/wotlk#2377]
**Is your feature request related to a problem? Please describe.**
Currently if I want to try out several different items in a slot I have to manually swap them around and record the dps values to decide which one is best. In another sim that was used a lot during TBC there was a feature where you could easily compare all items in a slot. 

**Describe the solution you'd like**
Maybe there could be a separate UI, or maybe it could be included in the item selection pop up, but it would be great if there was a compare button. It would run the sim for each item in the slot and give a dps value saying if it is more or less than the current item in that slot. 

**Describe alternatives you've considered**
Maybe there could be buttons to click next to the current "favourite" star that says "compare". When you have selected at least one item to compare then a big red button appears at the top of that window that lets you compare the dps of all the different items you have selected

**Additional context**
The Warlock TBC sim I'm referring to was here https://kristoferhh.github.io/WarlockSimulatorTBC/

**Comment by lologarithm** [comment]
We have a ticket open to track all this https://github.com/wowsims/wotlk/issues/1512

I will close this ticket but it will now be linked in the other one so we can ensure this info is included in there!
