### ISSUE TITLE
Fireball spec gaining a buff from a talent that is not taken

### ISSUE THREAD

**Issue by bazmage** [wowsims/wotlk#2398]
**Describe the bug**
On the mage sim if you select ttw/fireball spec it is gaining clear casting procs which is normal but these procs are giving the talent arcane potency which makes your next spell have 30% increased crit chance. This talent is in deep arcane and this fireball spec doesnt not have access to it yet the sim still shows getting it every time clear casting activates.

**To Reproduce**
1. Go to mage sim select the fireball spec talents and then sim
2. Click on results tab and then on buffs
3. Scroll down to see arcane potency buff is there from a talent you cant get in this spec

**Expected behavior**
not to see this buff as you cant get it

**Sim Links and Screenshots**
no need to link you recreate just by selecting fire talents including clear casting but not arcane potency

**Desktop (please complete the following information):**
 - OS: windows
 - chrome
 - latest

**Comment by jimmyt857** [comment]
Thanks for the report! This is just a visual bug, although the aura is being applied it isn't providing any crit bonus. Will be fixed soon though.
