### ISSUE TITLE
tooltip for bloodfury inaccurate

### ISSUE THREAD

**Issue by wuchonah** [wowsims/wotlk#2399]
![tooltipbloodfury](https://user-images.githubusercontent.com/122655846/212445851-67bdf0b1-11cc-48d7-b143-e348d2da7998.PNG)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
The tooltips come directly from wowhead, and wowhead only shows the level 1 version of this tooltip: https://www.wowhead.com/wotlk/spell=33697/blood-fury

So unfortunately there isn't anything we can do here.  :(
