### ISSUE TITLE
Valorous Deathbringer is bugged for Warlocks

### ISSUE THREAD

**Issue by DoktorVanHelsing** [wowsims/wotlk#2431]
I added [Valorous Deathbringer Gloves](https://wowhead.com/wotlk/item=45419) to gloves slot, [Valorous Deathbringer Leggings](https://wowhead.com/wotlk/item=45420) to legs slot and simulator didn't  see any of it as a part of set :P.
![image](https://user-images.githubusercontent.com/26298714/213612546-12b03ce8-07b4-4db3-b323-0b182305082f.png)

**Comment by ELANIMALX** [comment]
yea lots of things is not simming right

**Comment by Tharre** [comment]
This is a purely visual issue, the set bonus still gets correctly applied for the actual damage calculation.

**Comment by jimmyt857** [comment]
Yeah this is a visual-only bug with wowhead's tooltips, unfortunately there's nothing we can do here. You could try bothering them about it on their discord.
