### ISSUE TITLE
WARLOCK IMPROVE LEECH

### ISSUE THREAD

**Issue by ELANIMALX** [wowsims/wotlk#2436]
**Describe the bug**
How does improve leech increase dps exactly? if anything it does less...also phase 2 tier 9 should include in the sims .it feels like it ain't siming right 
**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tharre** [comment]
More mana = less taps = more damage, seems pretty straightforward, no?

2pT9 seems to work fine, 23% pet crit with, 13% crit without or what's the issue there?: https://wowsims.github.io/wotlk/warlock/#eJzjUuRgEmAyYLJg9GCMYCxgamBkXMD4hXkDI9MBRsYLjIwvGBmdBDkYJRgVGA0YHUBKGFcwMgoxSJ1lbWJkC8hJrEwt4mAX4JC6w8jFL7DzMZPEG1kltqOHmHY/Y+LiFDj7gEmJ+fMOJqDcl+dMEo+Acvt2MH0ECvAIbHrCJNElq8R8Cyy98wWTxA8OsPTi50xcvAJtQLPmCCmxAAUYuDgEtn5lUmJiYOASEtgM1DdRRokTaCwQ7QPr3vyVSWKBHFg3ROD8AyaJaTJgAZD1nALbHzNBrOIUuPccyAQpYxE49xhEznoMcs8WoLm/ZGEyG5+AlL57CHG/EhcH0P8WjAEsEayLmM4ycc0AumUUYANCBqTqqAIGrgCTBBMocWVJcPEBeSzABMekAQpyJik2CL+LUd3I2NTAwMDIwBhIGJsaGhiZggSMjQ0NTQ11dU1BkgYGpoaPGCU45rYzC9x8yiRx+SmTQtNlJo1/l5gMGi8zvWBk+cDIPYuRoRMaf5YOtxgZZjExKH1l4gQLNKQ5CEKk9BwkZ80EgZP2lhCRC/aKaWBwzd7oKFPBnNoqnoDEkuSM8tSibAUjU4VgCQ4tGieMD40O1DCm4eQRSswxsNAqcCRVEzgQG6Y9coDqfGHfwcgYhDUvVYusc39Y1WIPC/+HVSCBW/YQ2Q/2MHWHv2rE9B96a7+kwJbr+uIHUPqFPbp5QxWQnpcAVJmw4g==

**Comment by ELANIMALX** [comment]
yea but shadow priest doesn't provide that ?? and plus u need to life tap for glyph??

**Comment by ELANIMALX** [comment]
Something is not quite right here ...shadow priest already provide mana to the raid so u shouldn't run leech talent .it seems pretty straighfoward no??

**Comment by Tharre** [comment]
> Something is not quite right here ...shadow priest already provide mana to the raid so u shouldn't run leech talent .it seems pretty straighfoward no??

Read the talent text again. There 2 effects, one that immediately restores mana to you and your demon, and then the replenishment effect that can also be provided by a shadow priest. So even if you have replenishment from some other source you'll gain more mana and thus dps by having improved soul leech.

**Comment by ELANIMALX** [comment]
I don't think it should sim that much ..I can think of other theorycrafting beside having mana back....anyway good talk....just trying to be straightfoward..
