### ISSUE TITLE
Crash Report 987644418

### ISSUE THREAD

**Issue by jhohm** [wowsims/wotlk#2437]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCDVBtrEyNbQE5iZWoRB7sAm9R6Ri5+gaPPmCReyiqxbTvMdO4sExeLwMbdTFw8Atv2MEk8kFVi/rqDiYtdYNcuJompMkDh20DhH1BhXoGr25gkWuWUWIA8BiB3A1ByigyUyylwZBcTRCG/wLoXTBLvgZZ82cH0BWzgt4dMEtNkgLZ17QTZOWsPiHyzF0Qe2AVSsH83k8RZWSBj0TYwg0Xg4G4mJV6gdxkDWBJYKkC+WsQEdPAMJoZRgBUIGZCqo4qFg1GCKUqMi0+ARYJJg8mA2YLJgdWDVYpFACjexahhYGBqbGQAJA1NdA2MTI2ADANTAwNjUwNDAyMjY0OgjIGhkanhI0YejkNPmQSOP2WSOPaU6QUjywdGxlmMDLcYGWYxMSg9ZeIE29eQ5iAIsVnEQXLWTBA4aW8JEblgr5gGBtfsjbYyKQRLcGjROqpbHKhhSsPJI1QxhxQACTOfuw6OEP4Pew/GBMYgcPaw5bq+uMD2k/3hrxox/Yf+2hNrZrXIOveHVVvs3wTukGt9fRGHvg/2EPO/2cu3vgaq/GoP0iWy7rs9iHR/+MoeaCnQ5vdE20svIGQAdnAruwMk5TE7ENIBAHKfoMk=

RNG Seed: 3289755114

Rotation is empty
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xc8960, 0x31bb60})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x1570000, 0x2083970)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:473 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1570000, 0x2083970)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:26 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x2083970)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x2083970)
	/home/runner/work/wotlk/wotlk/sim

**Comment by catszeid** [comment]
If you clear the cache, it should run without issue. New merge added rotation related code that is causing that.

**Comment by catszeid** [comment]
Closing the issue. Open a new issue if this persists so it can be investigated further
