### ISSUE TITLE
Crash Report 1486025123

### ISSUE THREAD

**Issue by polocabbit** [wowsims/wotlk#2442]
Link:
https://wowsims.github.io/wotlk/rogue/#eJztmE1IFGEYx+d5dnadHRRft2Bnl93Yhg4iBDOzSS4E79SpwIMFgXgyaMNDh8WbniQySugQVNgeCoRCwkPRum1ZK30JCq5LHwt9LIiQGZqYFGwG0TuzHQvZN729P4aXZz7+/5f5zW3UoIIG9kAKBwBGAXIARYAlgEMkhm1gQyek4Lx7KyCFB71nwNdx+kRfslfxEl84A2ojuTCO2ueo7ss+w4Ucqn5S+YC6Z5KN9ST7CLX5qO65fgPVOnIpj9qVCIucY5FMSPct3kd2qCrZeIDa4C4dJLWB3GGZyxFdLuRQYm3PH7K2DdbWSDLszi8WY23VwjFWeDWiyuRiHtk6dMtZy2+ddeWx88BIFrXZKBueTriDTNITqMvsnb0jOIvqMEqCvxIwak30ywpo2BVkH0rWMIbN2OaxcRgOhGUCGgxBi2G0xi3DZGurZbITZ47vNSw2OIdhxE12xbIscwHqlZk5JO/nUJv6iEsgr0FdGqR3IKVR0r/v8Vf33Gc3VYeddih9zWGaJqpXinT3KZcStcYxdlRTWrb7a5+1t6TGePJfPd3BHQdrzVSdtZftP8kKPQzdILxthvAmvPEivPEhvPEhvPEhvPEhvPEhvPEhvPEhvPEhvPEhvPEhvPGxdd6OuX8Mb7r/mb7SmeX2vhepH7TW7pPH++8trxb/kVuj+48k3ni+vab5u6XkeuITnRqY7Fksl+h0x21/V2Gd9iZHgyudAbvWfbebgNFcKaTHXoXsBvPll59Bn71Z4jefGhdT

RNG Seed: 3532051829

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xeeb00, 0x1340fa0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).setupAssassinationRotation(0x210a000, 0x151d4a0)
	/home/runner/work/wotlk/wotlk/sim/rogue/assassination_rotation.go:292 +0x104
github.com/wowsims/wotlk/sim/rogue.(*Rogue).setPriorityItems(0x210a000, 0x151d4a0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:268 +0x10
github.com/wowsims/wotlk/sim/rogue.(*Rogue).Reset(0x210a000, 0x151d4a0)
	/home/runner

**Comment by catszeid** [comment]
Clear your cache for the site and it will run.

**Comment by polocabbit** [comment]
Clearing cache didn't seem to solve the issue. Running a specific talent set seems to be the cause of the issue. Here's an export link

https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCDVCNrEyNbQE5iZWoRB6sAm9QGRi5+gc17mCReyiqxbTvM9GgHExenwI87TErM+4FMHoFtQLkHskrM8+YzcbELXN7NJDFVBqhlPVB4i6QSG1ARSB2XwK+dTBKtckqMDED2XaDkFBkQm1PgyC6gUb+ASvgFtgCF/wH1AI2CmDZ1G5PENBkuFoHefUxAsmsniLx7E0S+2QtSMPcBk8QxHi42gXVJEh9FgMIHdzMpsQD9y7qI6SwT1wwmhlGAFQgZkKqjioWDUYIpShwYTywSTApMGkwWzA5MMxhtpFgEGCUYuxi1DAxMjY0MDIGkqZEhkANiG+saGAEZIGRgYGwIFDEyMjJ8xMjDceo8k8Dt88Doe8r0gpHlAyP7LEaGW4wMs5gYlO5KcELsNHEQhDBEHCRnzQSBk/aWEJEL9oppYHDN3mgrk0KgBIcWrWO7xYEqxhgcpMicBHFhR1L1QMLM564DVOcPew/GBMbRcCMERsNtNNzIBaPhRh4YDTfywGi4kQdGw408MBpu5IHRcCMPUC/cgsA9w6Xg/sRH+1OvfSqPFvy0J9XslNCqza/fXcCh74O9uaflVeYvV+z3bbyW+snyuf2xhv0Zz+5esz8ZsIoz6twn+6LUFeJvIoQcSLWX1kDIQOPHuVlrLks68BpeevtbnM2BkA4AMSDqFA==

**Comment by catszeid** [comment]
I will take a look at that. Thanks for letting me know it wasn't just old settings
