### ISSUE TITLE
Crash Report -1156536728

### ISSUE THREAD

**Issue by Zappzarrap** [wowsims/wotlk#2446]
Link:
https://wowsims.github.io/wotlk/rogue/#eJztU01oE1EQzsxuNttnxDUEug1G455CQXjZsBIPZVcveox6EfFgkZZCewhFUCNCKgREEA9FqUEU6kVQqtAYk9oYbBTpIVoRlApCLVSiLTQKUSgIzr7oTbHFn5PDY+Yx3/vmm/fH2lXk2AcpzABcBygCzADUAXYFIpgABw5ACo7DGQEGPKGq9zQoyYHuEz2DapumhO4C26CNT6L+LmwohSo+KSKTtaESMr9WoPRc2JBWKOfTnt9D/cImWn2L0vkOQ6H0CK1j2koJ9ZthAzxsvXabwKrfkAnxUIlPZTSUShFpEDNP4DLpVItIg+DxCdTLfkOqCNXcpOvP3Xf9Utn1r2dd5Qop18I0GS2IiaxdmUNjHW3cm5QPy7S3UawhG0HPf/uhBfhaGWlZBR0PttOlyVHkUgId7x4vPbGQrBFwFqKcW3GTkzfj27hpmdyKcYvzuMVj3DTjMUJ4zLRi8+BXpxZQe7yA+uxTrIPcAF8OtjOFyWqpBiK+vSExL5PUOwMiFPpF9v2w5EZteAJFvPoAX4Enhx6jiW2izUyvs7HVcNDpyF1ybdre0crM2Ft7hb2wzUeYunwq7U92Hz3Sd6xnsD9iWpH9utr5l59MY8j5E2Uy0w9/pw5PdKZ2rpUkDjFzcd75xqzb9M32iV/WxV5eS3V9tKvN6KHzU1/s1ZY8GRzb/Sadt5f2FjdnF5/9hNewW/f4wd6SXaSVTdtlBcc+299xEiXl5VXr/isLcNFw1ue0diA5v2J8BcHOtNw=

RNG Seed: 2898040951

Rotation is empty
Stack Trace:
goroutine 61 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xc8960, 0x31bb98})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x1572000, 0x16a5c30)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:473 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1572000, 0x16a5c30)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:26 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x16a5c30)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk/sim

**Comment by catszeid** [comment]
Clear the site cache and it should run without issues
