### ISSUE TITLE
Crash Report 539169931

### ISSUE THREAD

**Issue by Zappzarrap** [wowsims/wotlk#2447]
Link:
https://wowsims.github.io/wotlk/rogue/#eJztU01oE1EQ3pndJNtnxDUEug1G455CQXjZsBIPZVcveox6EfFgkZZCewhFUCNCKgREEA9FqUEU6kVQqtAYk9q02CjSQ7QiKBWEtlCJttAoRKEgOPuiN8UWf04Oj5nHfPPNz/thrSpy7IEUZgBuAhQBZgBqAHsCEUyAA4cgBSfhnAADUqjiOQveZF/nqa5+tUXzhu4D26SNjqP+Lmx4CxV8WkSmaAMlZH6tQO65sCGvks+nvXiA+qUtFH2H3Pk2w0vuIYpj2moJ9dthAyS2UbtLYMVvKIRIlOJTGQ3vZBFpETNP4ArVqRSRFsGjY6iX/YY8Karmxl19YcLVy2VXv5l1Kw8XUK+GaTMxLzaKdm0OjQ00uCepHFVotmGsIhtC6b/8UAJ8vYy0ooKOh1vp0pQocjmBjmefh55YSNFQh/MQ5dyKm5y0Gd/BTcvkVoxbnMctHuOmGY8RwmOmFVsAvzq1iNqTRdRnn2ENlDr4crCTeZmilqog7NtbMvMwWb3XJ0yhV3jfD8qu1QbHUNjrD/E1SDmUjAa2iDYz3c7mZsNBpy13xZVpe1fTM2Nv7xby0jYfY+rqmbQ/2Xn8WM+Jrv7eiGlFDupq+19+MvUB50+kyUw/+p08PNGe2r1ekjjEzOUF5xuzZtM3OyB+WQd7dSPV8dGuNKJHLk59sdea8nRwZO98Om8v7y9uzS49/wmvbjfv8YO9LbtEkQ3bZQVHPtvfcSpKlVfWXPdfSYCLhrM+pzmB7PyK8RVyl7UB

RNG Seed: 1331799954

Rotation is empty
Stack Trace:
goroutine 51 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xc8960, 0x31bb98})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x15c0000, 0x144b080)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:473 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x15c0000, 0x144b080)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:26 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x144b080)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk

**Comment by catszeid** [comment]
Clear your cache storage, and the reenter the gear and settings. The settings you are using are outdated and causing the error
