### ISSUE TITLE
Feature Request: Adjustable Honor Among Thieves

### ISSUE THREAD

**Issue by catszeid** [wowsims/wotlk#2453]
**Is your feature request related to a problem? Please describe.**
Honor Among Thieves (HAT) is currently implemented at a set rate and cannot be adjust to match realistic conditions.

**Describe the solution you'd like**
The user interface should have an option under settings to allow the adjustment of Honor Among Thieves activation rate.

**Describe alternatives you've considered**
Full integration with the raid sim would allow for an accurate representation of the talent, which would replace a regularly occurring activation. This would require a check for triggering each time any player in the rogue's party has a critical hit with a damaging or healing ability.

**Additional context**
-Honor Among Thieves cannot trigger more than once per second.
-Any Dot that can Crit will give Combo Points
-All pet Abilites will not give Combo Points

**Comment by vigo2** [comment]
Done in https://github.com/wowsims/wotlk/pull/2789.
