### ISSUE TITLE
Bug: Glyph of Backstab effect does not stop after the 3rd hit

### ISSUE THREAD

**Issue by catszeid** [wowsims/wotlk#2454]
**Describe the bug**
Glyph of Backstab should only add time to a Rupture Dot up to 3 times. Current implementation allows for addition of time past the 3rd hit.

**To Reproduce**
1. Simulate with a dagger in main hand and Subtlety preset talents selected
2. Click on Results -> Timeline
3. Count the number of ticks a Rupture deals when 4 or more backstab occur during a single Rupture
4. The number of damage ticks is greater than Combo Points + 3 + Maximum Glyph of Backstab procs (3)

**Expected behavior**
Any Backstab hit after the 3rd while the same Rupture is active does not extend the Dot

**Comment by vigo2** [comment]
Fixed in https://github.com/wowsims/wotlk/pull/2818.
