### ISSUE TITLE
Hunter mixed T8 10man/25man 4set

### ISSUE THREAD

**Issue by dimitarkalevski** [wowsims/wotlk#2456]
**Describe the bug**
It seems that when you have 2 pieces 10man T8 hunter tier (gloves legs) and 2 pieces 25 man (helm chest) the 4 set is not active, at least not visually as both are just shown as 2 set when hovering on them

**Comment by jimmyt857** [comment]
This is a visual bug with the wowhead tooltips, the sim correctly recognizes the 4-piece bonus. You can see this by checking Results --> Buffs and seeing the 4pc buff active.
