### ISSUE TITLE
UI Suggestions regarding Stat Weights display

### ISSUE THREAD

**Issue by Saltyc0der** [wowsims/wotlk#2462]
Move "Optimize gems" behind the experimental checkbox and move the current "Copy to Current EP" to "Optimize gems" location. It would be more intuitive from UX perspective

More often than not optimize gems results are awful and in my opinion the current location is pretty bad place for it. I've accidentally clicked it multiple times when meaning to click on the "Copy to Current EP"

**Comment by kayla-glick** [comment]
Hey there @Saltyc0der 👋 I just got done reworking the Stat Weights modal and put "Optimize Gems" behind the experimental checkbox, so let me know what you think
