### ISSUE TITLE
incorrect conflag dmg when molten core talent is picked

### ISSUE THREAD

**Issue by dandacan** [wowsims/wotlk#2464]
**Describe the bug**
incorrect conflag dmg when molten core talent is picked, its abnormally high (~1.5x)

**To Reproduce**
1. Have both the conflag talent and molten core selected in the warlock talent sheet
2. Sim
3. See incorrect damage on the conflag section.

**Expected behavior**
correct numbers lol

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/19211904/214073119-ab88b2aa-9635-44b5-a4c5-d860a5372ad9.png)
![image](https://user-images.githubusercontent.com/19211904/214073339-ab6aa0ee-ac8d-476f-9c28-b32068114959.png)
![image](https://cdn.discordapp.com/attachments/679009960180580362/1067099656972161095/abc.PNG)

**Desktop (please complete the following information):**
 - OS: window 11
 - Browser: Firefox
 - Version 109.0

**Additional context**
n/a

**Comment by Tharre** [comment]
Link your sim setup.

**Comment by dandacan** [comment]
im sorry lol was busy raiding [here](https://wowsims.github.io/wotlk/warlock/#eJzjYnBi0mAUYpCaytrEyBaQk1iZWsTBIsAhtYWRi1/g6W4miTeySmxHDzF93sHExSnw9Q6TEvMtIJNH4AVQ7pGsEvOCk0xc7AJXgbwuWaCW50DGDw4lNqDwPqA6XoG2XUwSc4SUWIA8BiD3CVB+naQSC1CeAWjg211AA0EK+QV2AGXagZYBeSAb2AXe7WGS+M3BxSLQv48JSJ7fDSJf7QWR+3eBFJwB6vglC+Re3AUSXLCNSYlhEdNZJq4ZTAyjACsQMiBVRxVDlgQXnwCzBJMCowajAaMFowOTFBsHowCjBGMXo7augbGxoYGBsYGhobGpkaGRgbGugSmQNAKShgZGQDlTQwNjU6C04SNGCY5rp5kEbj5lkrh6mkmh6TKTxr9LTAaNl5leMLJ/YOSexcjQCY05S4dbjAyzmBiUvjFxggUayhwEIVIiDpKzZoLASXtLiMgFe8U0MLhmb3SMqeB5A1MVl2NOemJOfp6CkalCsASLFo1TxIdGB2oY03DyCCXmbDj/qdmRVE3gMGw488kBqvODvQdjByNjENZsZAwGh+2/acT0H/p6w75aZJ37w6on9jCtqKpf2EMi6qG9Ldf1xQW2r+zRzRuqgPRsBADv/ZKq) it is
