### ISSUE TITLE
WARLOCK SPELL HIT IS NOT CORRECT ..IS GIVING 2 PERCENT SPELL HIT FOR NO REASON ..PLEASE FIX THIS

### ISSUE THREAD

**Issue by ELANIMALX** [wowsims/wotlk#2465]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tharre** [comment]
You need to at the very least provide a link to the issue, I can't fix something that I can't reproduce.

**Comment by Tharre** [comment]
Closing since it's not at all clear what the issue is and OP is unresponsive.
