### ISSUE TITLE
Valorous and Conqueror's Deathbringer don't provide set bonus.

### ISSUE THREAD

**Issue by Juicepants** [wowsims/wotlk#2475]
**Describe the bug**

**To Reproduce**
Equip Valorous Deathbringer Robe and Conqueror's Deathbringer Hood in the WOTLK Warlock simulator and the set bonus does not show up as enabled.

**Expected behavior**
One should received the 2 piece set bonus for the Deathbringer Set.

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/warlock/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE7CHIwKTAaMFowOjAEgNYwrGBmFGKQmsTYxsgXkJFamFnGwCHBILWHk4hfY84JJ4o2sEtvRQ0y3djBxsQg0P2Xi4hHY+5xJ4pGsEvNnoBi7wO5dTBKT5YCq3z5ikvjBocS2bwfTR6AMl8Dth0wSc4SUGBm4eAWe7GaSmCKjxAI0h4GLU+DjHiYl5ltg/duAqtplQQygQdNkgLb07wPZtfMBiNy/C0S+2gtSeQZoxi9ZILcBLLhgG5MSFwcjyC8BrBGsi5jOMnHNYGIYBViBkAGpOqo4OBgFmCSYChizJLj4gGxmCUYFRg1ggDswSrEB+awSjF2MarpGBsZAZGxgaGBsamBoZApkGZsagQhDXVNTAxAwNXrEKMFx8ymTwNx2Zonbp5kUmi4zafy7xGTQeJkJmCo/MLLMYmTohEaepcMtRoZZTAxKT5k4wQINaQ6CECkRB8lZM0HgpL0lROSCvWIaGFyzN9rKpBAswaFF40TwodGBGsY0nDxCFXNIAZAw87nr4Ajh/7D3YExgDMKacapF1rk/rGqx57q+uMCW67i9x8MqkIg9RPaDPUzd4a8aMf2H3tp/A1FfH9i/Cdwh1/r6pT26eUMVkJ5xAFfrjzY=

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 109.0.5414.75 (Official Build) (64-bit)

**Additional context**
I love you and thank you for your hard work.

**Comment by lologarithm** [comment]
It is implemented in the sim, the UI just isn't correctly showing it because wowhead separated the two set names. You can validate by swapping out the set item and putting in the same stats manually and you can see that immolate damage drops.
