### ISSUE TITLE
Warlock Conqueror's Deathbringer Robe

### ISSUE THREAD

**Issue by skiyoshii** [wowsims/wotlk#2489]
**Describe the bug**
Warlock 2pc is not showing active when combining Conqueror's Deathbringer Robe and Valorous Deathbringer Shoulderpads

**To Reproduce**
Add Conqueror's Deathbringer Robe and Valorous Deathbringer Shoulderpads
Check 2pc active on either piece.
Shows Conqueror's Deathbringer Garb on Robe and Deathbringer Garb on shoulders

**Expected behavior**
Show 2pc active

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
Chrome  109.0.5414.75 
![deathrbingerError](https://user-images.githubusercontent.com/63738829/214771858-c52f4d7a-5965-4aaa-8431-926bc4de26a5.png)

**Comment by Tharre** [comment]
This is a visual bug with wowhead tooltips, there's nothing we can do about it, see also #2431.
