### ISSUE TITLE
Warlock: Combining the 10m t8 set pieces is not applying the set bonuses

### ISSUE THREAD

**Issue by SteelShield** [wowsims/wotlk#2490]
I have Valorous Deathbringer hood and Conqueror's Deathbringer Robe Equipped. Mousing over one of the items shows that the set bonus is not active. It may be possible that it is just displayed incorrectly, but the sims seem to reflect that the set bonus is not applied. Switching to Valorous Deathbringer Robe did not apply the set bonus either. Only after have both 25m pieces equipped did the set bonus apply.

**Comment by Tharre** [comment]
This is a visual bug with wowhead tooltips, there's nothing we can do about it, see also #2431.
