### ISSUE TITLE
The Valorous Deathbringer Hood does not count as set item

### ISSUE THREAD

**Issue by Lestat888** [wowsims/wotlk#2510]
**Describe the bug**
The Valorous Deathbringer Hood does not count as set item in the set bonus. However, the Conqueror Deathbringer Hood does count as a set item.

**To Reproduce**
1. Go to warlock simulation;
2. Select the "Valorous Deathbringer Hood" head piece;
3. Notice that it doesn't count to the set bonus.

**Expected behavior**
When equipped, the Valorous Deathbringer Hood counts as a set item towards the set bonus, just like its Conqueror version.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/warlock/#eJztU0toE1EUnXvzm4xKn6HIMzRhnFUQCi8TBtqFzNSNWUa76cJNF1aQoIM742b8UXVTQRENutGNKym4MCalSv1RrBorWKwKJihOsZZYSRFB8c403WgRgroQPIs35557z2GYuU9RZWQosAeyMAA2OgCnAEYBbwFUAVyArR0yqCjAghzYcAUgJsWrocMQzuUHD+zaL0eYHL8OSgebqyOfT2jhuxM4W0IlypovUQt4dC1zK8jrCS0wTlWEVcrITyfJcsNF/pksJH+izjrmziC/ENOCJEhUviHbma5WGWUfx1qBEdYYQz6cILJA5GwXkVfXkDtJIiPjPgmym2Wks1Hx5qco6UuCyidl79UWapT0qISaIoNY0wO50EDoEj5E5RxK/7EqYqJdR0GWgSFHG/ZsoB0IcFAhBd4mxcPUCXE4Cf3iF+gWIqOLTEak0xlDF7pBjIhOR7rbMPwZ42dbHbh8cTjAnr9F/uIBqt+mMeU8RfF1Gl0INCBYBOlE6z/3WrMgFVHSljDqC86QtX651WltLJ73MGn2LitVc9OQj2emfg/tdw4WlL787sH8vr2qbqj9PLj5L+9P45D1J2KcyTu/kzP6ePFIX7sm/xs6U4tWy9kws3AcYMeql+5g59VttcJRU5m5bG9R7pvZWsFTzBXrytztZmrnyMQHc8l7NF+b89tLyWPv58wf8/5VtH/pvgOfHanS)

**Desktop (please complete the following information):**
- Windows 10
- Chrome last version

**Comment by Tharre** [comment]
This is a visual bug with wowhead tooltips, there's nothing we can do about it, see also #2431.
