### ISSUE TITLE
A way to simulate combat like Hodir with additional critical damage percentage buff.

### ISSUE THREAD

**Issue by zsz1992418** [wowsims/wotlk#2542]
As title described.
We already have ability to simulate additional combat-specific buffer by adding additional stat like haste/crit but not for crit damage.
This can be helpful to sim best gear for Hodir combat.

**Comment by kayla-glick** [comment]
Hey @zsz1992418! We already have an issue in the backlog for this https://github.com/wowsims/wotlk/issues/2164 so I'm going to close out this one for now so that we can keep things organized
