### ISSUE TITLE
Crash Report 117399862

### ISSUE THREAD

**Issue by Nessik88** [wowsims/wotlk#2543]
Link:
https://wowsims.github.io/wotlk/warlock/#eJztUz1LA0EQ3Zl8r0rWIHiGRHQrEQKXOw60SrSyNn/AKoi/QKy0EUmjgogGi2BpJQhqFD8QLYIoIUrEaCGRg2CTCAoiRNy9K5VAIHa+Ypg3b+ftsMzSkBcYDMEYTMI0ZODNsQ14CpAHqACMkgAOQXDL5XUxb/AQqJ+Zh6gcdHP3xRm+7iP1sfdH5I6SSNtZRWjlMHccW8y8QyUVtjU/y1ZQ+Qhzt9BkH2XVMiobAQ6EdrA9Ia6EuFOIRFiePKFt4mfXwjLTa7XZd8yLwmqIO6SJky1lZVw8lvHkQMaXI6QeVhfmn2FBi7uyuGwiJ5t4hXQNyT9+RUBttmPGI3dnAWCKUhJ0C+JSIAUJtQEiqqprqq6r0ahuRKOaITLd0DTJIoZhnTF+tpVB8d6byG5NVB4usa9ewIG5G1S/ClgBZw3a0kBKQNJI+DP6rOlmk/FOe86ueE96XSIXG7Yr+Vh/0kIxpu1gX0JxDf7xYtTm4q2wmc2dt8SnGdhvdlSNj9j8IzYB4/9fqQGa/0rfbBx/yQ==

RNG Seed: 1524713699

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 12 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xef060, 0x1348080})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0x17de000, 0x2015080)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:558 +0x1e7
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0x17de000, 0x2015080)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:284 +0x16
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x2015080)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:384 +0xe
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x2015080)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:355 +0x1f
github.com

**Comment by avidal** [comment]
I'm just now getting into contributing to the project, but when I attempt to replay your scenario the immediate issue I see is that the rotation options in the settings tab have a few missing options (ie, only corruption is selected, no other rotation spells, and there's no curse selected).

Did you change anything in the settings panel? Or did you just open the warlock sim and select/import your gear and hit Simulate?
