### ISSUE TITLE
DRW not casted as blood

### ISSUE THREAD

**Issue by codyhertz** [wowsims/wotlk#2554]
Currently DRW is not cast while talented as blood.

**Comment by rosenrusinov** [comment]
Can you provide an export link to your setup as from what I can see the sim is casting DRW when talented

![image](https://user-images.githubusercontent.com/5707996/216148968-68291130-1347-42e0-9d61-fe6a629bb736.png)

**Comment by rosenrusinov** [comment]
Closing this due to no more information. @codyhertz you can re-open it if you want to provide more information
