### ISSUE TITLE
[BUG FIX] Death Knight DPS: Blood without Dancing Rune Weapon large inaccuracy

### ISSUE THREAD

**Issue by NuptupTDOW** [wowsims/wotlk#2560]
**Describe the bug**
When using the DK DPS sim and choosing blood dps, if you remove Dancing Rune Weapon talent for any reason (for example, to take the Unholy Blight talent instead), the damage for the spec drops drastically below expected loss/gain brought from Dancing Rune Weapon. I expect a drop by removing the talent of course, but the drop goes from 4,047 in full Phase 1 preset down to 1,237 which is clearly incorrect. I am unaware of how much lower Unholy Blight (with dark death glyph instead of DRW glyph) is, but that's why I was trying to sim for it and how I came across this result.

**To Reproduce**
1. Go to 'https://wowsims.github.io/wotlk/deathknight/'
2. Click on 'Blood DPS' in the talent choices (Gear irrelevant, but I used full Phase 1 Blood)
3. Run a sim and note it is roughly 4k (4,047 in my current example)
4. Remove Dancing Rune Weapon talent and glyph (you can leave nothing in their place or select something else such as Unholy Blight and Dark Death glyph)
5. Run another sim with no other changes and note a drastic and unrealistic drop in damage down to roughly 1.2k (1,237 in my current example)
6. See error

**Expected behavior**
In my in-game testing, I am pulling less burst damage with the lack of DRW, but my constant throughput is still decent when talking about off-meta dps specs, and it results in a much more relaxed playstyle. I would assume a loss of maybe 5-15% dps, not nearly 70%.

**Additional context**
I looked at the results tab and it pretty much only auto attacks, tosses engineering bombs and casts Army of the Dead, nothing else at all. So, I went digging through the rotation logic for Blood in the DK sim folder and it seems as though the entire rotation is dependent on having taken DRW, so it's absence is likely causing a back-end logic issue with the sim, causing it's rotation to be completely non-functional, leaving it sitting on runes and runic power while it tries to activate a spell it doesn't possess.

**Comment by rosenrusinov** [comment]
I'll add support for this even trough it makes no sense. 
People thinking that 1 talent point that gives them 600dps is a bad spent point is beyond me
