### ISSUE TITLE
Crash Report -1835164239

### ISSUE THREAD

**Issue by badmilk27540** [wowsims/wotlk#2565]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1GzWJka2gJzEytQiDkYBNqmNjFz8Apv3MEm8lFVi23aY6dxZJi4WgRWPmbh4BLYBhR/IKjF/38HExS4wcR+TxFQZoPBtoPAWSSXm/UBhLoFFQOFWOSVGBi5egd5HTBJTZJRYgDIMXJwCrx8zQVTxC7y+ziTxHmgDkAcS4BHYvItJYpoMRJpFoGsniOzdByLf7AWR73eD7Ny/m0niowiQsWgbmMEicHA3kxIH0MOsASwJLIuYgK6dwcQwCrACIQNSdVSxcDBKMEWJA2OMRYIJmHyYHZg8WGcw2kixCAAluhg1DAxMjY0MgKShia6BkakRkGFgamBgbGpgaGBkZGwIlDEwNDI1fMTIw3HoKZPA8adMEnfOM71gZPnAyDiLUZyLlYuZY1s2FxsXC8e1w4xg+tVk5luMDLOYGJS+MnGC3dGQ5iAIcZGIg+SsmSBw0t4SInLBXjENDK7ZGx1lKphTW8UTkFiSnFGeWpStYGSqECzBoUXjNPGh0YEaxjScPEKJOQYWWgWOpGoCB2LDtEcOUJ0v7IFFQxA4G90uLTz1beVb+xQbpk3X5/+0J9XoTx7zF8y6dglDn292Xees76/sFZSnfGhi+2rv8eIJ+42HH+3DwuPW2k/4Yr9A7+nqpb8/kGwfvYCQAav/xP/lbwQd3lzVMfqpw+BASAcAyKeqhA==

RNG Seed: 193680588

Rotation is empty
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xc8de0, 0x31d010})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x20f8000, 0x2268210)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:472 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x20f8000, 0x2268210)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x2268210)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk/sim

**Comment by catszeid** [comment]
Tested the setup linked and could not replicate the issue.
