### ISSUE TITLE
Shadow Priest T8 4 set incorrect link

### ISSUE THREAD

**Issue by DKong27** [wowsims/wotlk#2569]
When simming a Shadow Priest that has the T8 4 set bonus (https://www.wowhead.com/wotlk/spell=64907/devious-mind), the buff does not display correctly in the Results - Buffs screen. It displays with placeholder icon and no name, presumably because it is linking to item=64907 instead of spell=64907. It seems like the effect is actually working and its just a display issue on the Results screen, but I can't be sure.

**Comment by CyberQuackGames** [comment]
Should be fixed in next update. Thanks for report.
