### ISSUE TITLE
[BUG] Raid Sim freezing when closing individual character's settings window

### ISSUE THREAD

**Issue by NuptupTDOW** [wowsims/wotlk#2570]
**Describe the bug**
While using the Raid Sim, if you add a class/spec to the raid, then click the edit button and change anything, you have to refresh the page to continue editing the raid sim settings.

**To Reproduce**
1. Go to (https://wowsims.github.io/wotlk/raid/)
2. Restore Defaults
3. Add (I think) any spec to the raid groups
4. Click the edit button to enter that character's individual set-up window
5. Change any piece of gear, gem, enchant, talent, glyph or really just anything at all without using a preset
6. Press the "X" to close the pop-up window and return to character edit pop-up window, or just click on the area outside said window to return to the raid sim
7. Both options will result in a darkened view of the Raid Sim page that is unable to be interacted with until you reload the page

**Expected behavior**
Upon closing a pop-up window after making a change, you should be able to return to the previous wind(s) without the UI freezing and waiting for a reload to fix it.

**Additional context**
Any changes you make during this process DO persist ad work, you just have to reload between every single one.

**Comment by NuptupTDOW** [comment]
Also, Somewhat related, the individual character edit window's "X" to close it seems to only really be clickable in the absolute bottom right corner. The item select screen and whatnot seem fine, but the one to close a character and return to the Raid Sim page is seemingly only a handful of pixels at the bottom right corner of the "X" icon.

**Comment by kayla-glick** [comment]
Gonna take a look at this one
