### ISSUE TITLE
Base stats for undead priest are wrong (probably all races)

### ISSUE THREAD

**Issue by kaquinones** [wowsims/wotlk#2572]
**Describe the bug**
Base stats doesn't match with in-game base stats

**Sim Links and Screenshots**
These are the base stats for a priest with no talents or gear or buffs in wowsims ->
![image](https://user-images.githubusercontent.com/17010647/216506209-03989a52-bc75-466c-b14d-b8904fe7f8c8.png)

These are the base stats of a priest with no talents or gear or buffs ->
![image](https://user-images.githubusercontent.com/17010647/216506538-69237ed0-c201-44cb-92b9-0bf177940459.png)

**Additional context**
Suggested solution
![image](https://user-images.githubusercontent.com/17010647/216506072-5aa6ea5c-b176-4ed0-9c5b-68f5fc75ffd2.png)

**Comment by CyberQuackGames** [comment]
Thanks @kaquinones for the report. I've updated Undead / Troll here since I have those values. I'll need screens for other races to make those adjustments.
