### ISSUE TITLE
Unable to equip gems

### ISSUE THREAD

**Issue by busabuzz** [wowsims/wotlk#2576]
**Describe the bug**
Since yesterday I'm unable to equip gems on items. In some cases you are able but the gem page shows up at the bottom of the item selection page, which is probably some UI rework but it's pretty bad. If I want to select gems for more items and click the gem tab the application doesn't display any gem menu.

**To Reproduce**
1. Go to rogue simulator
2. Click on an item in the character screen
3. Click on the gem tab
4. The gem window either concats to the item selection window or does not show up at all.

**Expected behavior**
The gem selection window to replace the item selection window.

**Sim Links and Screenshots**
[Note the gem menu button is active (selected)](https://ibb.co/68L46j9)

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.0.1
 - Browser chrome
 - Version: 109.0.5414.119 (Official Build) (x86_64)

**Comment by Saltyc0der** [comment]
can confirm. switching enchants etc. works fine for 1 item after refresh but after u try to mess with other items, it breaks.
