### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#2578]
**Describe the bug**
Im missing all Off hand items from warlock sim, no filters on. They are there on spriest sim

**To Reproduce**
1. Off hand
2. click to change
3. 
4. >See error<

**Expected behavior**
To have a list of offhands to change to

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/110721034/216586533-f97c59f8-c7cd-4250-90a4-66f59b156545.png)

**Desktop (please complete the following information):**
 - OS: win10
 -Chrome

**Additional context**

**Comment by kayla-glick** [comment]
Hey @TeamSpeakUser1 would you mind sharing a link to your sim? Export > Link > Copy

**Comment by jimmyt857** [comment]
Probably just have it filtered out. Check the filter settings using the `Filters` button (it's visible in your screenshot). Going to close this but if that doesn't resolve the issue, feel free to repopen.
