### ISSUE TITLE
Wrong item level on an item "Delirium's Touch"

### ISSUE THREAD

**Issue by Make98** [wowsims/wotlk#2582]
[Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
](https://www.wowhead.com/wotlk/item=45494/deliriums-touch) 
Shows up as 245 ilvl, as in 10man hardmode weapon. It is not 10man hardmode drop from mimiron, it is 25man hardmode weapon from mimiron and the real ilvl is supposed to be 252 (stats are also wrong, not just the ilvl)

**Comment by rosenrusinov** [comment]
Wowheads API still returns the item as 245 but now it returns it with its new stats so atleast that is fixed. I'll keep this issue open unitl they fix the iLvl

**Comment by catszeid** [comment]
The issue with iLvl and source are now fixed.
