### ISSUE TITLE
Crash Report -610469546

### ISSUE THREAD

**Issue by Sourborn** [wowsims/wotlk#2593]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztk01oE0EUx/c9N+1mbckYcliXpMQ9lUJhkiWggszqRY+xXop4sAeLBw/Fk9ZLWixIPOQi2uZQofXQkyhCWTWiWA8GbJtD0oIn22DcUmuDUIzfzuyoB7XYQrz5291h3pv3n/dm961uaUiQ4mkYgAzAFMAtgEcAJQAPoAFYQjxE4kjBgV4ec8mPCSvmx8AwtKTP9J0/dVYLEN18CHqIjC+jsRKzWqZncG4W9SB5X0NrR8FFvY2sFdB4EZNWK7ldQ+NdjEuue2g0uGTOxfEi6u0kex+NkQ5LXXBR4abHZVeilloQZoi8qaIV5HN5c8drvr7O9Vws9G0kP43G1ajMo5LsXTFe9sfakhhX50X+a1U0pkxuzr8Sztw9tEIa0va9kFZ71XPinBPIjzCKyn/+SJhuVzGoamDgB9ivR3nT8YY6Amno85ecnOMCPBV9h6a5S8bXWRy6dmpffwAUsnCc0lQqQRMp27Ypv5NJmqD8sSmn26Yp/+Ik6a90cym1f3P/ZBkMbe0lkoky76Ayxscq2JkrIx2toAdqHVrzoDwHJY+KVcWgX2Km3/lebMTZnR8TFNk+6SmxPf0+Cyx5B+PHjEDXP+6m+pDTjG0yxSdN2Wc7yHf2YN05KO0GOwk9/v83s9F5Ivc46CxODhzQF6tsqzvKr7HCpL6yia7O3I6R1aPuF9bjTzwmdZ/ZDZFu0mORm4eXBiNvN817wQ+4uOW6mkWYzj4TaI6s9NNfK/gGJ7jPGQ==

RNG Seed: 170515947

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xf0940, 0x135b920})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:482
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).RotationActionCallback_HS(0x210a000, 0x15dfce0, 0x1617900, 0x20ff350)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:66 +0xd
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk

**Comment by rosenrusinov** [comment]
You're trying to use the DPS DK sim for a Tank spec. I would suggest to you that you run your Tank simulations in the DK Tank sim.
