### ISSUE TITLE
Crash Report 1380341452

### ISSUE THREAD

**Issue by badgorath** [wowsims/wotlk#2603]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjYnBiEGKQ6mVtYmQLyEmsTC3iYBXgkNrOyMUvcO8Bk8QbWSW2o4eYbu1g4uIU+HqHSYkZxOQReLGbSeKRrBLzPiCPXeAqkNclC9Sy4yGTxA8OJTagMEiGS+A2UGCOkBIjAxevwOtHTBLrJJVYgDIMQNP2P2CC6OcXmPGMSWKBHFwbu8ApoLYFkkBG21MmiQY5IOP8bjCDReDPQyYgueoZSNkZoOAvWSC36RFIcME2JiWGRUxnmbhmMDGMAqxAyIBUHVUMWUJcfByMAswSjAqMGowGjA6MUgxdjGq6RgbGQGRsYGhgbGpgaGQKZBmbGoEIQ11TUwMQMDV6xCjBcfMpk8DcdmaJ26eZFJouM2n8u8Rk0HiZ6QUj8wdG7lmMDJ3Q6LJ0uMXIMIuJQekxEydYoCHNQRAiJeIgOWsmCJy0t4SIXLBXTAODa/ZGm5kUgiVYtWgc7R8aHahhTMPJI1QxhxQACbO97x0cIfwf9gmMQVgzSrXIOveHVS32XNcXF9hyHbf3eFgFErGHyH6wh6k7/FUjpv/QW/tvIOrrA/s3gTvkWl+/tEc3b6gC0jMKAO0yi8A=

RNG Seed: 617226597

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xf0c20, 0x1360920})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0x14e4000, 0x1448790)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:389 +0xd2
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0x14e4000, 0x1448790)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:284 +0x16
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x1448790)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:384 +0xe
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x1448790)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:363

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/2833
