### ISSUE TITLE
Destruction Warlock Simulation is not accurate what-so-ever

### ISSUE THREAD

**Issue by warzhead65** [wowsims/wotlk#2608]
Currently, the sim for Destruction talents is about 2k lower than self buff, no raid buffs, damage on the training dummies. I Pull on average 5.1k dps over a 2.5 minute fight on the dummy. 

Either there is isn't a big enough pool of players to pull data from or the sim was abandoned at the beginning of the expansion for affliction since every warlock is mostly in that spec.

With the release of Ulduar, the destruction spec fills a role for cc and actually outputs between B and A tier dps. At least I do.

Please fix the destruction simulator so warlocks who are actually using the spec can see where their dps should be.

![Warheadzz Destro](https://user-images.githubusercontent.com/124622611/217059995-7662a982-db77-4b0f-b93a-dadabaf7e229.PNG)

**Comment by Tharre** [comment]
> Currently, the sim for Destruction talents is about 2k lower than self buff, no raid buffs, damage on the training dummies. I Pull on average 5.1k dps over a 2.5 minute fight on the dummy.

P1 bis destro set sims for about 5.1k dps as well, you probably have something setup wrong. Link your setup.

Also saying 'X is inaccurate' is useless without very specific information about what is actually inaccurate. We can't fix bugs if we don't know what the bugs are.

**Comment by Tharre** [comment]
Closing because it's unclear what the actual issue is, and no response from OP.
