### ISSUE TITLE
Non-Ferocity Pet Talent Ability Usage Missing

### ISSUE THREAD

**Issue by Twosiders** [wowsims/wotlk#2613]
**Describe the bug**
Some abilities such as Wolverine Bite and Roar of Recovery never seem to be used by the selected Cunning pet, with the necessary talents picked. This results in lower than actual DPS when non-ferocity pets are selected.

**To Reproduce**
1. Go to Hunter Sim
2. Click on Talents, Select Pet, Select for instance a Cunning Pet such as a Dragonhawk.
3. Unlearn some talents so you can learn Roar of Recovery for instance or Wolverine bite
4. Start a sim
5. Check the combat log of the sim
6. Search for "wolverine" or "recovery" and you won't find these abilities used at all.

**Expected behavior**
I would expect Wolverine Bite to be used constantly, though I am not sure if it's a DPS increase.
Roar of Recovery should be used for instance the first time the Aspect of The Viper would be turned on, at the user setting of 20% mana or whatever.

**Sim Links and Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version: -

**Comment by jimmyt857** [comment]
It does use Wolverine Bite, but there's a different issue with the icon not loading properly so the row is not easily noticeable (the icon is simply blank). I'll look into fixing this.

**Comment by Twosiders** [comment]
@jimmyt857 Thanks for the reply.
I ran another simulation this time with a spider pet with Wolverine Bite learned and I still can't see it in the simulation log.
[spider_cunning_wolverine_bite.txt](https://github.com/wowsims/wotlk/files/10678678/spider_cunning_wolverine_bite.txt)
Uploading the log here.

**Comment by Twosiders** [comment]
Here's the link to the build, I'm not sure if it contains the pet talent selections as well but it might make things easier for you.

`https://wowsims.github.io/wotlk/hunter/#eJztVE1oE0EU3vfy082gdCz+TMKmpntahMJuQqARyqwFMQcPUS8e9WDx4CH01PYUlUrpyYBKzEWxCJ6KiNoE6x/2UrG2RGhRLLRiJGLFCCoFe+ibrB6KigTizY/9Zmffm3nfm5k3y6I6cLDAhh44BlnIAZwHuAk4D1AD6Nuh3DFyZ8g5CnADoIDYgT0Q+R44A8HMqeNDJwZ05BiZANbOH9ZQvI+awbtPcGUSmZ+vV5Ft4R/foliOmj5la+P5ByguGjR6cgrF7bAZJPPzWWSMz91CMdJpgsa28hI5Lximn5wahTj7DkXe8EK080ek84l08iU8V1Ix18ooLhkkWJxSsmNl1a7eV+3SSzVg+h6KL1GmUfcxdQuGyXVUyz7qH1TLpsVdQ0qigNp//BYddrMzhnVVPoJKZ+8Q258GC3XY1vC4V9y+GEM9QGwjhog6kRF9RCSCU7ysUJapRAMvZAYiNhXbrshOalXZous7iVkcVMdXAOjydOsyNftMYVVaMAZW0na6bTuZsJNOd9ImJOLqpWKSNe4ol0PPGxD61Tnk41UU16sYW6yg9bSC9kIFa+CvQ6gI2ivQiqiZrzHUkMr1u2EvzRmZ8tTnZVd/AwsyfgdjR4S+5x8XVf2024owuZnplsRpBt6eHVxy93nfazJNP6LDmy6id/qBH7ktS2+/P8sWpeD+VO5li+PZ3m9y98iHQ6XOr03Gr7cqn7/i14uYXhnePnEg7P5pxgb4haJ9`

**Comment by jimmyt857** [comment]
It's in the log too, but the same issue is present where the name is blanked out. Try searching for the spell ID (53508) instead of the name and you'll see some of the debug log statements.

Here it is in the results tab:
![image](https://user-images.githubusercontent.com/1822327/217402240-a2ebc363-0d77-43d6-8942-9a620b56863a.png)
