### ISSUE TITLE
Crash Report 924856324

### ISSUE THREAD

**Issue by Skedekriger** [wowsims/wotlk#2634]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1HWWJka2gJzEytQiDlYBNqlALmaBvXZcDEBqtiKQ2C4NJH7yc7EJNEkqMTIA6U/iIBqk4LwGkFgUyMUicP8YI5DZwskFkfgpACROaAAlJp5iVOICuoc1gCWCJYFlEdNZJq4ZTAyjACsQMiBVRxULB6MEU5QKlxQHkwCLBBMwhpkdmDxYZzCGrmC02cDovYNRQ4pNgEmCUUGoizHUADfQNTAyNTIwwSWJBzxiZOG4c57pBSPLB0b2WYwMtxgZZjExKD1m4gQ7sSHNQRDiWBEHyVkzQeCkvSVE5IK9YhoYXLM32sykECzBqkXj1PGh0YEaxjScPEIVc0gBkDDb+97BEcL/YZ/AGATOT7Zc1xcX2H6yP/xVI6b/0F97Yk2sFlnn/rBqi/2bwB1yra8v4tD3wR5i/jd7+dbXQJVf7UG6RNZ9tweR7g9f2QMtBdr8nmh76QWEDMAObmV3gKQ7ZgdCOgAIRoMB

RNG Seed: 1977117120

Rotation is empty
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xca500, 0x321ea8})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x1af0000, 0x19bc370)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:469 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1af0000, 0x19bc370)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x19bc370)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x19bc370)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:150 +0x7
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x19bc370)
	/home/runner/work/wotlk

**Comment by catszeid** [comment]
Tested the setup linked and could not replicate.
