### ISSUE TITLE
Import all relevant gear from bags via addon and add to separate window

### ISSUE THREAD

**Issue by Paulie-K** [wowsims/wotlk#2638]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When importing character from in-game addon, also import all relevant items from bags and put them to separate window below/when hovering over item slot, so we can click on them and it "equips" them in simulator instead of searching for them and adding enchants/gems. Do not forget to include already equipped items (and highlight them) in this new window so we can easily switch back to equipped item.

Also, add settings to ingame addon what items to select, by default select all usable epics+legendaries
- Gear type: Cloth/Leather/Mail/Plate/Weapons/Trinkets/All 
- Gear rarity: Legendary/Epic/Rare/Uncommon/Common
- Item level range

**Comment by jimmyt857** [comment]
This is being tracked in #1512
