### ISSUE TITLE
Missing items: Love is in the Air Eventboss 226 Necks

### ISSUE THREAD

**Issue by Rerox-WoW** [wowsims/wotlk#2653]
The 226 Necks of the Love is in the Air Eventboss are missing, since they are not the same as the 232 Badge Necks.
https://www.wowhead.com/wotlk/item=51806/shard-of-pirouetting-happiness
https://www.wowhead.com/wotlk/item=51808/choker-of-the-pure-heart
https://www.wowhead.com/wotlk/item=51807/sweet-perfume-broach
https://www.wowhead.com/wotlk/item=51804/winking-eye-of-love
https://www.wowhead.com/wotlk/item=51805/heartbreak-charm

**Comment by Saltyc0der** [comment]
#2647
