### ISSUE TITLE
Crash Report -946194802

### ISSUE THREAD

**Issue by dimkasta** [wowsims/wotlk#2658]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU0FoE0EU3f+bptux0jHkMIZU0sVDCAQmuwb0ILP1osdYr16CtAh6CEWQRoQoisVLELSmqVI0IqLgIQeJWgStggUbhSYGPaUtLRuqGAoFUavO7tqbxRbrzXf48/f/997/7M6S1jBkAPYpPiXwrvUseBPHk4N9A2obJYEikE5asJA1ujTvgwksTyHx0K/zSDro0CyyepfWslBC0kanHyO7EpTsMcn+LNmybHcIHS0iq/k1UMhWao0juxzUPOUSKtKiUUd2KehadNIPsvnJVZYdz9tPkA0H5cDrc/bYYt2O0+N2XHxtE5ZmkN0NyGTlIbI7AVnPPkJNuYlyzRwq//Fb+PhGFWnlC/SQYA5ARQomHIAEJJ2OmTVLAC8BAt3tLtdvbnOTpghBZIv6YxVwEaI8FjV0znUjzo1dus4NHtMNzrlhxHjMiMei8kn2DR6XYRaYOlpBerWC7OM8hnIVDOeqyEeqaAE0wZOHncRLPOqNC+icC/da7JOOPUWCRHFyeV3eg5JHRVtGd8NM/+qGfnN7fsTGpNjjVt6I7n4Hb4X+AlPXTqc7EskTR46e7Bs4FtLjoUNMjfzji9U8Y26GTWby+d/48N2RVM9GRc5LzAzPmr+UlhgC6HX+xYnl8OHss3azVkjtJbU5sV5L9/s0hKuvrqFritKO84sHS99Fr5NYwtWtiFv2uIIl/Pf3z6T9S2vOPeUQzq17r82Cj0+9sqGa7qbf/rjBT7VJxGs=

RNG Seed: 4087912899

runtime error: index out of range [-1]
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0x171c40, 0x1868c00})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(0x18dfef0, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:318 +0x23
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x18dfef0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:366 +0x39
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x18dfef0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:267 +0x1b
github.com/wowsims/wotlk

**Comment by rosenrusinov** [comment]
Using your link I don't get the crash. Can you try Restoring defaults (top right cogwheel icon then Restore Defaults) and setup and run it again?
