### ISSUE TITLE
Missing items: T5 Rift Stalker Set [TBC]

### ISSUE THREAD

**Issue by klingo** [wowsims/wotlk#2659]
Although the "TBC" filter checkbox has been ticket, I don't seem to find the Hunter T5 Rift Stalker Set Items.
Obviously I know that these items are not relevant in any WotLK group/raid encounter, but for soloing content, 2pT5 is incredibly strong and it can be very helpful to be able to sim which two pieces causes the least DPS loss.

_Currently I can only do this with a workaround: Export my gear as JSON, replace the itemId with the one from T5 Set, copy, and then import as JSON again._

Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
- [Rift Stalker Helm](https://www.wowhead.com/wotlk/item=30141/rift-stalker-helm)
- [Rift Stalker Mantle](https://www.wowhead.com/wotlk/item=30143/rift-stalker-mantle)
- [Rift Stalker Hauberk](https://www.wowhead.com/wotlk/item=30139/rift-stalker-hauberk)
- [Rift Stalker Leggings](https://www.wowhead.com/wotlk/item=30142/rift-stalker-leggings)
- [Rift Stalker Gauntlets](https://www.wowhead.com/wotlk/item=30140/rift-stalker-gauntlets)

**Comment by jimmyt857** [comment]
Unfortunately, re-implementing all the old item effects/bonuses for WOTLK would be just too much work for us, we're already struggling to keep up with the main sim features. Sorry!

As you've discovered with your workaround, older items are loaded into the sim when important via JSON or Addon importers. However, the set bonuses aren't implemented so you're only getting the stats.
