### ISSUE TITLE
I would like to test if using Ghostly Strike is a DPS upgrade. Is there any way to force to use it in rotation?

### ISSUE THREAD

**Issue by ginosaji92** [wowsims/wotlk#2662]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by catszeid** [comment]
Ghostly Strike is implemented as a spell, but not used in any rotation. At this time there is no way to make the sim use Ghostly Strike in the rotation. 

With regards to damage and effectiveness the math I have done shows it as inefficient when compared to Hemorrhage or Backstab when running a full sub spec. Note that it does not benefit from the talents in Subtlety that increase damage done or decrease cost of specific abilities.

**Comment by ginosaji92** [comment]
Hi. Im combat and use slow MH weapon. There is a build for algalon only and in wowhead simonize said that you can use ghostly on CD If you have a slow MH weapon. I would like to test it. If you already know that is not a dps increase thats enough for me

**Comment by catszeid** [comment]
I have added in Ghostly Strike as an option for subtlety rotations. Feel free to compare it versus without using it!
