### ISSUE TITLE
Ironsoul bug

### ISSUE THREAD

**Issue by youmi94** [wowsims/wotlk#2663]
2h Weapon Ironsoul gives expertise on sim whereas it shouldn't

**To Reproduce**
1. Go to 'death knight dps window'
2. Click on 'main hand'
3. Scroll down to 'Ironsoul'
4. See error 'Compare exxpertise rating before and after equiping Ironsoul'

Ironsoul should only give crit and armor pen stats, not expertise

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.]
(https://wowsims.github.io/wotlk/deathknight/#eJzjUuJgEmAyYMpgLGBsYGRcwci4gZHxACPjBUbGF4yMPxiZLjAxOQkoMBkwOjBGANV0MDIuYGQUYrJglPrM0sTIFpCTWJlaxMEqwCWVxMUAhfwC818wSfyQVWKbd5Jpzw4moBC7QOczJiVGEKMBwuAQWPKCSYmJASQ0axtYiEVg13MmIPn6CYi8vAfMPg8iHz0EGcKgxMvBZMAbwBLBUgFyySKms0xcM4BGjAJsQMiAVB1VnByMEkwZXMAo/sVoyiXJwSgAjHcPxgDGRLC8Q7/DDnDakJLghOiIdBCEMD7YKzBqMRgwdjFqGRkbmBoaGZgaGxgYGBsbGBsZGxoAxQwMjU0NdXWBLCMjA6ASoOQjRgmO50+ZBDZfY5J4+5RJYcYVJo0ZV5kMZl5lesHI8oGRfRYjBxco5oH4FiPDLCYGpTdMUJvzHCRnzQSBk/aWEJEL9oppYHDN3ugoU8Gc2iqegMSS5Izy1KJsBSNThWAJDi0ap5YPjQ7UMKbh5BFKzDGw0CpwJFUTOBAbpj1ygOp8YQ/MYUHgDPa0RVhU/y+bg6ix/tRnBl/tSTU67HIC1yaT4/YPW284/llwHk3/Bzj/oIZJwS2nH/bie59arNR6bm/z6/+BeYf/20/7pW59jO8/TntZjhXKHC+cQ7K7KAVCBnKZlfYFqcoOxOoAAJv8kqI=)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version last

**Comment by Tharre** [comment]
It gives expertise because you've selected human as you race and they get mace specialization, which gives 3 expertise. That's not a bug.
