### ISSUE TITLE
Crash Report 533188086

### ISSUE THREAD

**Issue by maddiGG** [wowsims/wotlk#2664]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU09IFGEUn/cadXZK/Fr28DWsss1JJOHbmRYqiG/qUsfNLh465CHp0EE6lV7WSIgue0lbNyjLDtIhgiAGW0GyQxtZS+0mRId0cx2RcBGCJfv3zXx6S1LYbv0YHvPmvd/v/WbmfbqpIUGG56EPUgATAI8ApgEKAB5ADbCAeJzEkIED3aLnWtATVoyXDVegMXmh5/K5i5pKdCMHegsZKyNdbjUbn8zg61nUQ6T2Ec1dORf1PWRsAemnVpk1kXdPkQ5HBeWOh7QmKLfzKC69mUxXkA61meqii4pI74r6jaip5vw0RFKVDUHBFIKrkik101NIR6K6SiaXUMSVz0GsBPGNb2FdSD8wNi28nUc6YYhiehLNFg1Z8yFIqt3qJf8l76Hwn0HlP/6IMNspo1/VgOI3OKJHxcaJbToJSegJSk7acQFe+EuHhrFX9ld5DDp2a782AQyuwwFmddoWY5adYPZBy2I2i1s2Y8y24yxuJzpFIso2S4iwAFS7VURys4j0yyLGMkVsz5SQjZbQA7UKTVlQPoCSRcUsYygYmup1NsZHnH3ZUR95flg+KfD9vQHec+sxxk7Tho5/vB/VQaceMqn887ro7ATym02tOsdkXuNnoSs4UTNf28+kn4WcufG+o/pcmW9XUf6NZS75pS14Ve62Da2ccn/yruDG45L3g9/3x417PPLwxHx/ZG3LuQNBw9Vt+6oXwmz2lQ/NkU6//9XBbzdTxGk=

RNG Seed: 2257907422

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 43 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xf2020, 0x1380980})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:482
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_Frost_FS_HB(0x2028480, 0x224edc0, 0x1a14f00, 0x1ba89f0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:172 +0x14
github.com/wowsims/wotlk/sim/deathknight

**Comment by Saltyc0der** [comment]
Crash is caused by not having Howling Blast talented, since frost sim assumes you will always have it talented. Weird non meta specs arent supported.
