### ISSUE TITLE
Not properly calculating hit for an arms warrior.

### ISSUE THREAD

**Issue by mwilds44** [wowsims/wotlk#2668]
**Describe the bug**
I am simming an arms warrior (it was probably happening to fury as well) and manually added the hit rating to show it is not adding correctly.

**To Reproduce**
1. Go to https://wowsims.github.io/wotlk/warrior/#eJztUzFoFEEU3f9vs9lbDm48UkyOXDy3OoXA7KwpUuhOtFALIdFCAym0MFhYhFSa6hQOxcJYqMSDKEYLKxtBDklEkkiIcHiwmKBV9AheCJgDiRyo6MxOwCYhBM7OV+zOvjf//cfsHydtI8OLMAx5gKcAFYAaQAOwgngkmUUhlRuRUgJIGelb1jWw+i6dv3JhxG4l8fRbcJJkvoZ0NeNaL2ZxqoSOSX6uoJMgbyS9nHFjK5JLksoXpHc7XEvu0MSMlBuZiFBVCTLxCmmh042VI3lOynfk/rKWk+RrFd24XC5qIkWWq0jXMxG36dFKxqaR3uuQEd5X0YmTD0uo/Uyy9k49X79UVt9klvLf1oYU5ifRteVZWH2xs+YkltEZR+M/tkSK7bZi1LSB4shJ5yiB2wBZyGGvVg6LE9E73yv6NTMgBvSiR6i5vKwmU47gI9DsQZG2iHSgeBPO+Ixz5nOP+77PvG7GGGce557PfY93e10+U9yW6JKF/jbaZ6D2wxDJRIh0PMTs1G/MFUJk10OsAdbBLILxEYwiGm4V4zr/kNijA7aJ9uJ9hYWgRzOVYN9QhMWAP8fsadpy4B8PV/2qaIZNfmGuKT67gT6z6XWxOSCN4Byciq7j7EZucGymRewtrPWXOn8Fze1bD45/Gm17dmw1+K7abBgialP4Eaiv3CAI/Q9NsZ2D3CwrHjQ5185Isf1RxHbxZPiQs/Q4IXaq+AO0Jbzm
2. Manually calculate the hit value on the gear
3. See the incorrect value on the stat sheet on the left column

**Expected behavior**
This is just not adding that stat correctly, I'm not sure if there is anything else broken

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser OperaGX
 - Version 4

**Comment by Saltyc0der** [comment]
? looks correct to me?
49
75
40
83
4 (socket bonus)
---
251

**Comment by catszeid** [comment]
Manually counting the Hit Rating it matches the gear
Shoulder: 49 Hit Rating
Weapon: 75 Hit Rating
Hands: 40 Hit Rating + Socket Bonus(+4 Hit Rating)
Trinket: 83 Hit Rating

The sum of all values above is 251. Likewise the Melee Hit total shown is 251. When counting the socket bonus on the gloves may have been missed.
