### ISSUE TITLE
Curse of Weakness always enabled in simulation

### ISSUE THREAD

**Issue by DenysTsi** [wowsims/wotlk#2670]
**Describe the bug**
When simulating Feral Rotation, the Sorcerer spell Curse of Weakness is always selected.
Unfortunately, you can't deselect it in the settings like you can all other spells/buffs/debuffs.
Furthermore, this is not displayed in the settings either, but after a simulation in the log/timeline.

**To Reproduce**
1. Just simulate Feral DPS

**Expected behavior**
Option to deselect this spell.

**Sim Links and Screenshots**
https://puu.sh/JzvJI/241cca909c.PNG
https://puu.sh/JzvJL/aa2b4cf1a4.PNG

Kind regards,
Endecs

**Comment by Saltyc0der** [comment]
![image](https://user-images.githubusercontent.com/81025536/219700437-c59a2e01-a27f-4c52-bf64-41c952d5b16e.png)
You can disable it from there.

**Comment by DenysTsi** [comment]
Oh wow, my bad! Thanks.
