### ISSUE TITLE
Crash Report -801522683

### ISSUE THREAD

**Issue by 13dayoder** [wowsims/wotlk#2677]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRidhBSYLRgfGCMYCRqBUB1hWCCgkNYu1iZEtICexMrWIg1WATWo9Ixe/wNoXTBIvZZXYth1mOneWiYtF4P4UZi4egYsPmSQeyCoxf9/BxMUuMHEfk8RUGaDq1UDVP4Cq9+9gAiIuLoFFQJlWOSVGBi5egQ17mCSmyCixAPUwcHEKtD5jUmIGqeIXmPaMSeI9Qhu7wKsHTBLTZIC2zdoDsvPqYxD5Zi+IvHsTpGD/biaJs7JAxqJtYAaLQP8jJiVeoJ9ZA1giWCpA/lrEBHTwDCaGUYAVCBmQqqOKnYNRgmkBI2OUNJewAIsEkwKTBpMFswOTB2sC4wxGGykWAaB8F6OGgYGpsZEBkDQ00TUwMjUCMgxMDQyMTQ0MTY2MjA2BUgaGRqaGjxglOA49ZRK4fJ5J4uZ5JoUPl5g0vlxiMvh0iekFI8sHRs5ZjAy3GBlmMTEoPWbiBLuhIc1BEOIaEQfJWTNB4KS9JUTkgr1iGhhcszfazKQQLMGqRePo/9DoQA1jGk4eoYo5pABImO197+AI4f+wT2AMAmeYfnCofrQ/PXHv/lDnv/akmjzptgeDSuA1HPo+2F8w0S7xW/DT3pvz0sv6vZ/tvyXzyfX++W1/dp5QoeGMLyTbRy8gZKCxNneV9HFRh0Ml2e1rdZkdCOkAAHHgoII=

RNG Seed: 1301750651

Rotation is empty
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xcb3e0, 0x323b78})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x1932000, 0x201fd90)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:469 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1932000, 0x201fd90)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x201fd90)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:45 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x201fd90)

**Comment by catszeid** [comment]
I suspect that the issue is tied to not having the Combat Potency talents and that causing it to fail to find the rotation. I will look into making it possible to run Combat without taking Combat Potency.

**Comment by 13dayoder** [comment]
Oh I'm dumb. Thank you!
