### ISSUE TITLE
Enhance Shaman Setting Option

### ISSUE THREAD

**Issue by Vancopland** [wowsims/wotlk#2680]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was wondering if we could get a deranked Wind Fury on the Enhance Shaman Sim!!!

**Describe alternatives you've considered**
Non

**Additional context**
I was meme simming and I was wondering if running a deranked Wind Fury would be a dps gain or not much like deranked Flametongue is for Spell Hance!

**Comment by jimmyt857** [comment]
There is no reason to ever downrank WF imbue. If you want to use 2x WF then use max rank on both hands. :)

**Comment by Vancopland** [comment]
yea i just hit up the Shaman discord and they said the exact same thing. I thought maybe it acted like FT with its internal cd
