### ISSUE TITLE
Mage: Haste is over-weighted with Spellweave Robe

### ISSUE THREAD

**Issue by ogoine** [wowsims/wotlk#2689]
**Describe the bug**
When Spellweave Robe is equipped, the value of Spell Haste seems to be greatly exaggerated. This effect disappears if any other robe is equipped, including those with similar stats

**To Reproduce**
1. Load the settings linked below, with Spellweave Robe equipped
2. Simulate weights and observe that Spell Haste is weighted at 1.43
3. Equip a similar robe like Heigan's Putrid Vestments
4. Simulate weights again and observe that Spell Haste is weighted at 0.70

**Expected behavior**
This can't possibly be valid. It doesn't make sense why Haste would suddenly double in value with that particular robe equipped. I've tried various other robes, and various other encounter durations, and even tried it with a raid (level 83) encounter, and still this robe seems to trigger an overestimation of Spell Haste no matter what. Spell Haste's weight should be near 0.6  with this robe equipped.

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/mage/#eJzj4rZgXMHI+ICR8QUjoxOTA6MQg9QCtiZGtoCcxMrUIg5OAWapuYxc/AKHtzBJvJFVYjt6iGnfDiYuFoEXe5m4eAQe72aSuCerxAwSYxfoOsokMVkOyPh2gkliiyQXl8Cf5UwSc4SUGBm4eAW2LGKSmCKjxHJrBxMDF6fAr0VMSsy3wPruAVW1ywIZ23YxSUyTAUpOOQuU/Ai2aN8yEDkHTL7aC1L+YTGTRJ8cFwNQYOE0JiVODkYD7gC+DkbGRUxnmbhmMDGMAqxAyIBUHVWsHIwNwIRhxCXRyDhrJgictO9kNAaDw/YSjAqMUmIcTAaMEslK3Bz/YYBRYw1TF6O2kbGBgYGpkbGhoYGBsbGBoamBMZBjYGRqYGpsZKhrYKxrYAQUB6oyfMQowTH7PpPA+7NMEv/PMik8ucSk8eASk8GPe0wvGFk+MDLOYqziEuBi4dh5llGIA+I4GQewyLPVzEgi/FzMHF1xaAI7EtEEuuEqRCACk2ECDYFgUwUWtDAh9HRCk5Slwy1GhllMDEpfmTghIn4OgjBzJGHhYwkRuWCvmAYG1+yNjjIVzKmt4glILEnOKE8tylYwMlUIkuDQonFa/dDoQA1jGk4eocQcAwutAkdSNYEDsWHaIweozhf2wPwdhDd7mzPUnZikess+ef9KVZ72y/YQ0Q/28qIKp1smd9qvqHDasy95qv0+mRs71zDdt39YJbLO/eEje3L8NBgB6dkbAIuxq5M=

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 110.0.5481.77 (Official Build) (64-bit)

**Comment by Saltyc0der** [comment]
It's not that this specific item causes the value of haste to skyrocket. Sim seems to value haste very highly at 391+ haste. equip some other item and then add bonus haste
