### ISSUE TITLE
Warlock 225 tier pieces are not counting toward the set bonus

### ISSUE THREAD

**Issue by Igrac813** [wowsims/wotlk#2690]
**Describe the bug**
Only the 232 items are counting toward the set bonus for Warlocks
The 225 items dont become yellow or "active"

**To Reproduce**
1. Go to Warlock
2. Equip any combo of 225 and 232 tier items and see what it shows as equipped

**Expected behavior**
225 tier items should still count toward the set bonus

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.]
(https://wowsims.github.io/wotlk/warlock/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE78HIwKTAaMDowBjAWMKxgZhRikjrE2MbIF5CRWphZxsAhwSG1l5OIXOLGFSeKNrBLb0UNM+3YwcXEKfL3DpMR8C8jkEXixm0nikawSM0iCXeAqkNclC9Sy8wWTxA+gFqDwZ6AMl8Dth0wSc4SUGBm4eAVeP2KSmCKjxAKUZACa9u8JE0Q/v8AboEw7RBvEwFNAbdNkuFgETj9mApL9+0Dkq70gcv8ukI59z5gk+uSU2G5BdDAAJRZsY1Li4mA0YLRgDGCNYF3EdJaJawYTwyjACoQMSNVRxcHBKMAkwVTAmCUGTAEsEsBUpAEKbiYpNqAMkN/FGGxkbGpgYGBkYAwkjE0NDYxMQQLGxoaGpoa6BriBrqkpmAZqQQePGAU4bj5lEpjbzixx+SmTwt9LTC8YWT4wcs9iZOiExq+lwy1GhllMDEqPmTjBAg1pDoIQKREHyVkzQeCkvSVE5IK9YhoYXLM32sykECzBqkXjdPKh0YEaxjScPEIVc0gBkDDb+97BEcL/YZ/AGIQ1Z1WLrHN/WNViz3V9cYEt13F7j4dVIBF7iOwHe5i6w181YvoPvbX/BqK+PrB/E7hDrvX1S3t084YqID1nAQCiKpvH)

For instance in this link you can see a combo of T7 ilvl gear showing the set bonus. 200 head and 213 shoulders
However, the hands and legs which are 225 down count toward the T8 set bonus but the 232 chest does

**Desktop (please complete the following information):**
Firefox Windows 11

**Comment by Saltyc0der** [comment]
It's just a visual bug.

**Comment by Tharre** [comment]
This is a visual bug with wowhead tooltips, there's nothing we can do about it, see also #2431.
