### ISSUE TITLE
Feral tank sim using wrong armor values for Ring/Cloak EP calcs

### ISSUE THREAD

**Issue by strykermyst** [wowsims/wotlk#2701]
**Describe the bug**
EP values for Rings/Cloaks is using the armor stat weight (~3.57) vs the bonus armor stat weight (~.58).  I don't see a bonus armor stat weight option when looking at Stat Weights, so might be a missing variable that's specific to bear druids.  I noticed this when comparing recommended upgrades as compared to 80-upgrades recommendations.  This might also be happening to druid weapons as well.  

**To Reproduce**
1. Go to Feral Tank Build 
2. Click on P1 boss tanking gearset
3. Run sim with defaults
4. Click stat weights
5. Note armor stat weight
6. Click Ring 'gate keeper'
7. Note EP is 2478
8. Note armor is providing 1600 of that total weight (using leather-armor stat weight values)

**Expected behavior**
Armor stat weight should only be providing ~0.58 value (as per 80-upgrades phase 2 values).  This would significantly reduce the perceived value of armor on rings/cloak/weapons.  This was a nerf in Wrath as compared to TBC feral druid.  

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/feral_tank_druid/)

**Desktop (please complete the following information):**
 - OS: [win-10]
 - Browser [Edge]
 - Version [110.0.1587.49]

**Additional context**
Thanks for the great sim!

**Comment by jarveson** [comment]
fixed with #3016
