### ISSUE TITLE
Tiny Abomination in a Jar 

### ISSUE THREAD

**Issue by huhsupomgosh** [wowsims/wotlk#2702]
**Describe the bug**

**To Reproduce**
1. Go to the retribution simulator
2. Equip some ret gear, Tiny Abomination in a Jar in the trinket slot and Shadowmourne in the weapon slot.
3. Simulate the DPS and record the DPS number
4. Unequip tiny abomination in a jar, add 85 hit rating to both melee and spell 
5. Rerun the simulator, again record the DPS number
6. The difference in DPS should be ~3.5% more than the initial number

**Expected behavior**
The above result is a close approximation to the damage output from manifested anger, but does not account for the total dps increase. Whenever manifest anger triggers and applies the melee attack for 50% weapon damage seal damage is also applied on top of this for retribution paladins (This seal damage from Vengeance/Corruption also has a chance of granting a mote of anger) Ticks from Seal of Vengeance/Corruption also have a chance of granting motes. Additionally, when Shadowmourne is equipped Manifest Anger will also grant a soul fragment. It might also be worth looking at the bonus effects this trinket has on rogues and shaman as Manifest Anger applies the rogues poisons (though the poisons do not have a chance of generating motes) and can proc effects like windfury for a Shaman

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem. N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A
 - OS: [e.g. iOS8.1] N/A
 - Browser [e.g. stock browser, safari] N/A
 - Version [e.g. 22] N/A

**Additional context**
Add any other context about the problem here. N/A

**Comment by huhsupomgosh** [comment]
After looking through the log it looks as though seal damage is applied after a Manifest Anger proc, however I do not see any mote procs on the seal ticks applied from the manifest anger proc.

**Comment by vigo2** [comment]
All seal damage spells have an empty proc mask, currently, so they don't proc anything. Tiny's proc aura (https://www.wowhead.com/wotlk/spell=71545/anger-capacitor) procs only on melee (ProcTypeMask 0x20), but might be special cased for paladins.
If you have something quotable (e.g. EJ's paladin forum) on whether "Tiny" should proc on seals, this could be updated, but I'll close this a not-a-bug for now.

**Comment by huhsupomgosh** [comment]
Ret paladins are very bizarre due to their hybrid nature.

Here are some quotable resources from January 2010 which list the sources of mote procs on a paladin.

https://www.mmo-champion.com/threads/688878-Tiny-Abomination-in-a-Jar-test-results-w-pic - "TAJ requires you to be standing right on top of the target of the proc (less than 2 yds). While running tests, I found that many of our abilities can proc a mote. Judgement, DS, CS, auto, and seal damage can all grant a mote."

"TAiaJ is proc'd by: Judgement, Crusader Strike, Divine Storm, Seal of Corruption, application of Righteous Vengeance, refreshment of Righteous Vengeance, Auto Attack, Seal of Righteousness, and Seal of Command (non-cleave portion). Every seal can grant a mote. I didn't list SoL, SoW, or SoJ because they really don't matter here."

https://www.wowhead.com/wotlk/item=50351/tiny-abomination-in-a-jar#comments - 

"For the people still wanting more info for retribution:

This trinket has a 50% chance to proc from:

Melee hits
yellow attacks
Seal of vengeance dmg
Refreshing Righteous Vengeance (dot)
Holy Vengeance (dot) not sure."

"Clearly best-in-slot trinket for retribution paladins. This is about 3.5% to 4% of your overall damage. Procs off seals, so you get tons of motes."

https://www.mmo-champion.com/threads/688692-Tiny-Abomination-in-a-Jar-bad-good-or-great - "The motes can build from their seal (every hit), the dot that gets applied (every hit), judgements, etc."

Additionally here is an EJ paladin forum post from August of 2010 which explains how seals application works and how while the seal itself is not considered a melee attack the hidden strike mechanism that applies it is.

http://web.archive.org/web/20100807233345/http://elitistjerks.com/f47/t49865-paladin_retribution_pve/#Glyphs__Gems__Consumables__Enchants__Professions

**Comment by huhsupomgosh** [comment]
https://wowpedia.fandom.com/wiki/Seal_of_Vengeance

Here is a description of the patch 3.2 change which outlines the hidden strike mechanic
