### ISSUE TITLE
Crash Report 179481775

### ISSUE THREAD

**Issue by xstormrage** [wowsims/wotlk#2709]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjYnBiEGKQ6mVtYmQLyEmsTC3iYBTgkNrKyMUv8HQ3k8QbWSW2o4eYbu1g4uIU+HqHSYkZxGQXOPqQSeKRLJBxFaioSxaoeucLJokfQNUfdzDtAyrhFXhxnUlijpASC5DHAOQ+ASpcJwnlcgp83AM0C6SQX2A3UGc7UOc+iE52gXd7mCQ+gQyfsJNJokEOyDj9GMxgEfjzkAlI7t8FUnYGaOIvWSC36RFIsGkLkxLDIqazTFwzmBhGAVYgZECqjiqGLBEuHgEWCUYFJg1GA0YLJikWDkYJxi5GNV0jA2MgMjYwNDA2NTA0MgWyjE2NQIShrqmpAQiYGj1ilOC4+ZRJYG47s8Tt00wKTZeZNP5dYjJovMz0gpHlAyP7LEaGTmiEWTrcYmSYxcSg9JiJEyzQkOYgCJEScZCcNRMETtpbQkQu2CumgcE1e6PNTArBEqxaNI74D40O1DCm4eQRqphDCoCE2d73Do4Q/g/7BMYgrFmlWmSd+8OqFnuu64sLbLmO23s8rAKJ2ENkP9jD1B3+qhHTf+it/TcQ9fWB/ZvAHXKtr1/ao5s3VAHpWQUA69WL7g==

RNG Seed: 1037508576

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 21 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xf6d40, 0x13db360})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0x19bc000, 0x20fea50)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:389 +0xd8
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0x19bc000, 0x20fea50)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:284 +0x16
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x20fea50)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:388 +0x10
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(0x20fea50, 0x7fffffffffffffff)
	/home/runner/work

**Comment by lologarithm** [comment]
duplicate https://github.com/wowsims/wotlk/issues/2709
