### ISSUE TITLE
Crash Report 1265673751

### ISSUE THREAD

**Issue by xstormrage** [wowsims/wotlk#2710]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjYnBiEGKQ6mNtYmQLyEmsTC3iYBTgkNrKyMUv8HQ3k8QbWSW2o4eYbu1g4uIU+HqHSYkZxGQXOPqQSeKRLJBxFaioSxaoeucLJokfQNUfdzDtAyrhFXhxnUlijpASC5DHAOQ+ASpcJwnlcgp83AM0C6SQX2A3UGc7UOc+iE52gXd7mCQ+gQyfsJNJokEOyDj9GMxgEfjzkAlI7t8FUnYGaOIvWSC36RFIsGkLkxLDIqazTFwzmBhGAVYgZECqjiqGLBEuHgEWCUYFJg1GA0YLJikWDkYJxi5GdQMjXSMDYyAyNjA0MDY1MDQyBbKMTY1AhKGuqakBCJg+YpTguPmUSWBuO7PE7dNMCk2XmTT+XWIyaLzM9IKR5QMj+yxGhk5ojFk63GJkmMXEoPSYiRMs0JDmIAiREnGQnDUTBE7aW0JELtgrpoHBNXujzUwKwRKsWjSO+Q+NDtQwpuHkEaqYQwqAhNne9w6OEP4P+wTGIKx5pVpknfvDqhZ7ruuLC2y5jtt7PKwCidhDZD/Yw9Qd/qoR03/orf03EPX1gf2bwB1yra9f2qObN1QB6XkFAMnEjCA=

RNG Seed: 92481627

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 25 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xf6d40, 0x13db360})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0x203a000, 0x197f290)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:389 +0xd8
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0x203a000, 0x197f290)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:284 +0x16
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x197f290)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:388 +0x10
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(0x197f290, 0x7fffffffffffffff)
	/home/runner/work/wotlk

**Comment by lologarithm** [comment]
Looks like this is because the warlock code assumes that if you have demonic pact you are using it. Since this particular link has no demon summoned (despite being demo spec) the code tries to access DemonicPact values which are null.

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/2833
