### ISSUE TITLE
Presence of Mind casted illegally

### ISSUE THREAD

**Issue by KevinTyrrell** [wowsims/wotlk#2712]
In the sim, Presence of Mind is casted while Arcane Power is active. This is impossible on the Classic-WOTLK client. Arcane Power cannot be activated while Presence of Mind is active and Presence of Mind cannot be activated while Arcane Power is active.

Solution: Grant priority either between Arcane Power or Presence of Mind depending on the scenario. This may constitute a togglable option whether or not to give Arcane Power priority over Presence of Mind. In other words, Presence of Mind is always waited to be casted after Arcane Power ends, assuming the user is affected by Arcane Power when Presence of Mind becomes off cooldown).

![image](https://user-images.githubusercontent.com/12791400/221086527-7441b0e6-11f5-46e6-b4df-dfbfe0ce4816.png)

**Comment by lologarithm** [comment]
fixed https://github.com/wowsims/wotlk/pull/2832
