### ISSUE TITLE
Raid Sim does not use Rampage buff of fury Warrior

### ISSUE THREAD

**Issue by barcmoehm** [wowsims/wotlk#2715]
**Describe the bug**
Adding a fury warrior to the roster does not grant the +5% Meele Crit buff. The buff section does not show Rampage.

**To Reproduce**
1. Go to Raid Sim
2. Add a fury warrior to the roster.
3. Scroll down to buffs
4. Meele Crit shows 0

**Expected behavior**
Meele Crit in the Buff section should go to 1. Rampage should be added to the raid buffs.

**Sim Links and Screenshots**
![grafik](https://user-images.githubusercontent.com/26359410/221182756-4d5bf606-3259-4b92-ad4c-6d585a7736fd.png)

**Browser:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 110.0

**Additional context**
I did not check if the buff is correctly applied in the damage calculations so it could well be a visual bug only.

**Comment by rosenrusinov** [comment]
The default warrior from the template does not have the talent Rampage. If you want to provide it you have to edit the warrior entry and select the rampage talent.
