### ISSUE TITLE
Righteous Fury

### ISSUE THREAD

**Issue by konaresco** [wowsims/wotlk#2716]
**Is your feature request related to a problem? Please describe.**
I can't see Righteous Fury buff in simulation settings or results for Protection Paladin mode. Not sure if it's already calculated into sim as default or not.

**Describe the solution you'd like**
Adding Righteous Fury to simulation settings or if it's already there - adding visual confirmation and taking into consideration Improved Righteous Fury talent when calculating simulation outcome.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jarveson** [comment]
yeap, was implemented correct before as far as i can tell, i refactored it into a buff tho so its a least listed now for better or worse with #3045
