### ISSUE TITLE
Crash Report 1261951667

### ISSUE THREAD

**Issue by simbaledo** [wowsims/wotlk#2733]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzj4uNg0mBMYKxgbGBkXMHI6MSjwOQA5E0A84QYpGayNjGyBeQkVqYWcXAKsEntY+TiF9h2hknipawS27bDTF92MHFxCkw9y6TEvB/I5BGYvIhJ4oEshMcusO4Kk8RUGaCWtq1MEj+AWoDC584ycfEKTOhlkmiVU2IBCjAAuR1A+SkySixfQFxOgTuXmWBG9CxjkngvCzS5v49JYpoMRJhTYBLMShaBrmUg8s1eEHn3JkjPbaC1Z2WBjNV7wAxOgRu3gcqBhitxcDAZsEawVDAuYgK6YwYTwyjACoQMSNVRxcLBKMEUpcQlIcAiwaTAZMHswOTBOoMxdAWjzQZG7x2MGlJsAkAVCkJdjKoGBqbGBsaGQNLUyBDIMTIwNDA2NgayDHUNjEyBNBA9YuThOPGUSeD4UyaJg0+ZXjCyfGDknMXIcIuRYRYTg9InJk6wxQ1pDoIQJ4g4SM6aCQIn7S0hIhfsFdPA4Jq90SGmgjm1VZwBiSXJGeWpRdkKwRIcWjROAR8aHahhTMPJI5SYY2ChVeBIqiZwCDZMe+QA1fnCvoORMQgp03ywv/nYS/fRop/2JBvdwBv2c+tlHPo+2CexXJsy785n+7yls2+/mvrRnv2ropaA+2d7zbuTpmrPemt/n9XnXC3PZ5LtpTUQMtjoMf/dSkEJB76/ERy7klgcCOkAAJXKo1E=

RNG Seed: 256313388

Unexpected cast failure
Stack Trace:
goroutine 122 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xcf540, 0x3333e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x18e6000, 0x2008840)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:498 +0x71
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x18e6000, 0x2008840)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x2008840)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:44 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x2008840)
	/home

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
