### ISSUE TITLE
Crash Report 321073737

### ISSUE THREAD

**Issue by Jesperson** [wowsims/wotlk#2736]
Link:
http://localhost:3333/wotlk/deathknight/#eJztU01oE0EU3veSppu1JWPIYV0SiXsqhcpkl4AKMqsXPcZ66cGDPVg8eCietF6iKIiXHKwljaBoFMSDCIJEUSitBwO2RkgseNDG+LOlSIMiBPHv7U4qHiy2EG9+O8zOe9/33ryZfauZKjLkeBhGIQtwA+A2wBRABcAFaAFWEHezJHJwYIg0Z31NVDHqXacglDkyfPzQURWYZjwDLcKKLuqLCTN0dwbnZlELs/MNNAMPSqj1sOvELSRWrPE3qF+ISyvCLhPXorhLZaSh9bJXRE/1mEGiFTKvED8eb5sRdq+OZpjWcmhRNreA+nLidx/lpBQTcTPUdnSzl1QLKFqQTdeR5qV3/vzU0356j/pN45fWE+XuoxlRkfdug0xgKHDMO/lVpEPlUfmPPyLK1xsxFlRBxy+wQ4tTG1KL7YUMDPuUk3NKAI+9TkTD2Cj1TZGE/g3qjxUAh3OwNWWn0tzi6QHbSnPvIVjc5qkBy+b0tj2XbXHLIn/qNejqxSqyiSrqH95iMl/FvnwN+WQNXQg2obsAygtQCqiYDQz722ZHnHYBMWdTYdJDWWyXnorYMuLjubDuYHK/3tX/jzukedLpRJps+VFH8qwH8s4eLju7pN0SB2HQ/6dmPvcdyE2Hnfni6E5tviHWmlF+jUUh42urxDVFafOZpX2l72LQX7hCxn0T17ztiq6I3dpTH4t9XHXfE77g9Jrr6hSifPaJB9WRlX79awU/AePlzWs=

RNG Seed: 2813466299

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 868 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x9e
panic({0xe98ac0, 0x360e990})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).uhDeathCoilCheck(0xc000aa0000?, 0xc000aa4630?)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_unholy_helper.go:301 +0x44
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_UnholyDndRotation(0xc000aa0000, 0xc000aa4630, 0xc0009ae000, 0xb5a32f?)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps

**Comment by rosenrusinov** [comment]
Unsuported build 17/26/28 and no plans to support atm
