### ISSUE TITLE
Option to weight hit as crit for item comparison

### ISSUE THREAD

**Issue by diadatan** [wowsims/wotlk#2747]
the upgrade rankings on gear appears to use an unsituational weighting for hit as superior to other secondary stats, causing gear with hit almost always score higher than gear without hit. in situations where reaching hit cap is accomplished regardless of choice in the specific slot, inaccurate gear rankings are being provided. replacing the score of hit with the score of crit will allow better item comparison.

**Comment by Tharre** [comment]
You can set the EP value of hit to the same value that crit has, but I don't understand how that is supposed to solve anything.

**Comment by diadatan** [comment]
What prompted this suggestion is me plugging in my gear and checking
upgrades and it ranks loop of the agile below darkstone ring, even though
this is incorrect. The reason is due to the weighting of hit and the
comparison not knowing you arent necessarily giving up hit when you switch
out a hit item for a non hit item.

**Comment by diadatan** [comment]
Anyway, thank you, i hadnt found that function.

**Comment by jarveson** [comment]
Solution here would be as you found, using the 'stat weights window' and changing them as you see fit or recalc ep's for given gear
