### ISSUE TITLE
Faster swing timer on OH weapon causes more unrelated spell casts

### ISSUE THREAD

**Issue by lime-green** [wowsims/wotlk#2749]
**Describe the bug**
By simming with a furious gladiator's Longblade then simming again with a furious gladiator's Swiftblade then comparing the number of spell casts done in the rotation, you can see the swiftblade consistently has more casts of spells like DnD, death coil, etc. They have the exact same stats other than damage and speed.

**To Reproduce**
1. https://wowsims.github.io/wotlk/deathknight/#eJzjUuJgEmAyYMpgLGBsYGRcwci4gZHxACPjBUbGF4yMPxiZLjAxOQkoMBkwOjBGANV0gNUIMVkwSj1ibWJkC8hJrEwt4mAX4JK6ycjFL7DgMZPES1kltm2HmV7uYOLiFLjxnEmJeQ+QySOw9AWTxANZGG/KEyaJ71Aev8B8oNwPoL55J5mAiItX4D5QulVOiQUozcDFJbASaO4UGSVGBqDanQ+ZlDiBqpY9YwJpFhI494BJ4r2sEifQRqDANYiBQP3TZJTY9oDFgA659xjqEBaBQw9B5MonIPL1eZBjJgKtXyEFc1rvcwSPReAY0Dp+DiYDXgvGAJYIlgpQGCxiOsvENYOJYRRgBUIGpOqoYuFglGD6xWjCJcbBKABMbB6MAYw7GBlPgJIi0wdGRikpQYjKD/YKjFrcHP9hgNGAsYtRV9fYyMDAxNjUAAiMdI2MDQyMgRDINTYyNAVKGRgC2YbGhsZAQcNHjBIcc68wCbx5CkwjV5gUZlxh0phxlclg5lWmF4wsHxjZZzEy3GJkmMXEoPSJiRNsa0OZA9R+EQfJWTNB4KS9JUTkgr1iGhhcszc6xFQwp7aKMyCxJDmjPLUoWyFYgkOLxgnlQ6MDNYxpOHmEEnMMLLQKHEnVBA7BhmmPHKA6X9gDM1cQOG9JKrQtrbZjc+jWv6BzwvanPbFGii0O/j4x64a9M/MEp4xHy+0ld8kt0PhxFk3/B/tc1ni1nVO+2q9UjzM8uvOv/bIX3nnKDb/t00TXcH/6xelAyJ63W79zn/01j2h3UQsIGSTpxtxWKZZx4HOM32t3QtCBkA4AZULPuA==
2. Sim
3. In another tab, use the same setup but replace the OH longblade with a swiftblade
4. Compare casts, almost every spell has casts increased (dnd, plague strike,  blood strike, death coil, ...). Even the number of MH auto-attack casts are increased consistently

**Expected behavior**
Number of casts should not increase when switching OH

**Comment by rosenrusinov** [comment]
Any clue from the timeline?

**Comment by lime-green** [comment]
@rosenrusinov no it's very subtle, it can be 0.1-0.5 more casts. Also, I noticed the same effect with fury warriors having increased Bloodthirst and Whirlwind procs

**Comment by rosenrusinov** [comment]
One thing that can cause this is that we invoke ai methods on attacks as well iirc and that would mean faster weapons faster ai reactions which would explain this @lime-green

**Comment by lime-green** [comment]
@rosenrusinov interesting, and the last piece: how does the faster AI reactions cause more casts?

**Comment by lime-green** [comment]
@rosenrusinov hmmm I don't know, as far as I can tell the patchwerk 25 AI does nothing for dps sims, since the AI current target is nil, so no AI auto attacks or spells are cast

**Comment by lime-green** [comment]
Actually, even without trinket this can still happen
