### ISSUE TITLE
Exact Sims for Rogue don't line up. 

### ISSUE THREAD

**Issue by InformativeGit** [wowsims/wotlk#2751]
**Describe the bug**

**To Reproduce**
1. Go to '...' https://wowsims.github.io/wotlk/rogue/
2. Click on '....' N/A
3. Scroll down to '....'  N/A
4. See error  N/A

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Brave 
 - Version [e.g. 22] (Updated as of 3/8/2023
![GearCapture](https://user-images.githubusercontent.com/127291910/223659999-2aeb1a9b-3f5b-47bb-aa3f-b6bd925abd4d.PNG)
![Gear2Capture](https://user-images.githubusercontent.com/127291910/223660032-9fd1e849-9fc8-4902-9f30-fc92f47d6e42.PNG)

**Smartphone (please complete the following information):**

**Additional context**
Both of these pictures are from the site that include the same gear/spec/talents/rotation/debuffs etc. I have checked this multiple times and the sims get both the same numbers every time that are substantially apart. I noticed the stats were off however I checked the added stats and all other anomalies and there were none to be found.  Thanks for taking the time to put the effort into improving the site, and best of luck.

**Comment by vigo2** [comment]
As mentioned above, the stats differ between these screenshots: the first shows 385 strength and 1618 agility, the second 385 + 99 = 484 strength and 1618 - 99 = 1519 agility. 99 agility equal an additional ~54.7 crit rating, so the DPS delta is expected.
