### ISSUE TITLE
Rogue and Warrior Major Debuff for X Seconds Setting

### ISSUE THREAD

**Issue by where-fore** [wowsims/wotlk#2754]
**Is your feature request related to a problem? Please describe.**
Some fights have a short add phase but a long main phase, such as XT's heart phase, which generally incentivizes maintaining Sunder Armor on the main phase and Expose Armor on the short phase. The simulator currently cannot handle this use case. Is it better for the Rogue to glyph Expose? As either spec? Which spec is better at exposing for 30s mid fight? 60s? 20s? How do all of these values compare to a Warrior sundering in those same timeframes?

These questions are mostly answered through opportunity costs, which rely on the rest of your settings, so it seems like a job for the sim.

**Describe the solution you'd like**
An "Advanced" option in the dropdown for maintain/never armor debuff, with further options for amount of time to expose, and potentially time into the fight the expose phase happens.

**Describe alternatives you've considered**
The "Cast Once" option for maintaining expose. Unfortunately it will only cast it once, as the name implies, which does not help you figure out if you should glyph or not glyph, and is not indicative of longer phase durations.

**Comment by jimmyt857** [comment]
Our answer to most questions like this is to use the raid sim. Adding UI options hurts everyone that doesn't use them, so the tradeoff isn't there in this case.
