### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by Hoefert** [wowsims/wotlk#2763]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

https://www.wowhead.com/wotlk/item=49906/hellfrozen-bonegrinders

**Comment by where-fore** [comment]
I see them under Phase 5, as expected, given they are a rep reward from the Ashen Verdict in ICC, in the Warrior sim. Did you have an issue in another sim class? Were you expecting them in a different phase?
![image](https://user-images.githubusercontent.com/108002636/224519002-483fbd77-6310-47d4-a578-b3d49b114d3f.png)
