### ISSUE TITLE
Crash Report 2008050824

### ISSUE THREAD

**Issue by kvnXcls** [wowsims/wotlk#2795]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1FTWJka2gJzEytQiDlYBNqktjFz8AmtfMEm8lFVi23aYafszJi4WgT9Pmbh4BLbtYZJ4IKvEPG8+Exe7QMdTJonTHEDVq4GqfwBV79/B9HUHExeXwKJ9TBJrZJUYGYDsvmdMEl/BbE6B3qdMSsxAVUA9r68zSbwH6gEaBTKNX+DPYyaJT0CBc2eZQCpYBHr3gchZe0Dk3Zsg8v1ukLWLtjFJnJUFMg7tBjNYBA7uZlJiAfqZcRHTWSauGUwMowArEDIgVUcVCwejBFOUKpeAAJMEkwIwWVmwOLB4sFYwSgkCRRgVRAz+wwBjF6OmgYGpsYGxoYGJsamRIZBjZGBoYGwMFDA11AVywchY19TA6BEjD8eJp0wCx4Fp6OBTpheMHB8Y2WcxMgDT6i1GhllMDEqfmDjBTmhIcxCEOEbEQXLWTBA4aW8JEblgr5gGBtfsjQ4xFcypreIMSCxJzihPLcpWCJbg0KJxWvjQ6EANYxpOHqHEHAMLrQJHUjWBQ7Bh2iMHqM4X9sASIQicfWy5ri8usP1kf/irRkz/ob/2xBpZLbLO/WHVFvs3gTvkWl9fxKHvgz3E/G/28q2vgSq/2oN0iaz7bg8i3R++sgdaCrT5PdH20gsIGYAd3MruAEmGzA6EdAAAeTi0Eg==

RNG Seed: 4055935786

Character `Player (#1)` did not perform any actions. Either this is a bug or agent should use 'WaitUntil' or 'WaitForMana' to explicitly wait.
	If character has no action to perform use 'DoNothing'.
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xcf9c0, 0x1a53080})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x18cdb80)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:392 +0x23
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(0x18cdb80, 0x7fffffffffffffff)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:355 +0x15

**Comment by vigo2** [comment]
Fixed in https://github.com/wowsims/wotlk/pull/2818. Combining "Open with Garrote" with "In Front of Target" caused this, because of Garrote's ExtraCastCondition. This is now simply handled in the rotation code (ignoring "Open with Garrote")
