### ISSUE TITLE
Rogue: Unable to change which poison goes on which hand

### ISSUE THREAD

**Issue by petaren** [wowsims/wotlk#2797]
**Describe the bug**
Rogue: Unable to change which poison goes on which hand. The drop-down menu frequently disappears when you move your cursor away from the icon. Even if you are successful and manage to click on a new poison, it doesn't register and change it.

**To Reproduce**
1. Select Rogue as your class
2. Click the Settings tab
3. Under player, mouse over one of the poisons (a drop-down menu of alternative poisons appear)
4. Select a different poison

**Expected behavior**
The new poison is selected

**Sim Links and Screenshots**
Firefox behavior:

https://user-images.githubusercontent.com/3486895/226199684-b867be59-00a9-4090-ac79-a608cb9d07b5.mp4

Safari behavior:

https://user-images.githubusercontent.com/3486895/226199752-6683e78d-51a9-4be3-9651-bc55609d5b2b.mp4

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser Safari 16.3 & Firefox 111.0

**Additional context**
It used to work just a few days ago in Safari. The dropdown has always been fiddly, but at least I could change the poisons. I've tried restarting my browsers with no success.

**Comment by catszeid** [comment]
In order for the poisons to be changed from the default generated by the application, you must check the Configure poisons manually box.
