### ISSUE TITLE
Crash Report -1958186221

### ISSUE THREAD

**Issue by sneekzx** [wowsims/wotlk#2800]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1CzWJka2gJzEytQiDnYBNqkzjFz8AiufM0m8lFVi23aYaf8OJi4WgRWPmbh4BC4+ZJJ4IKvEPG8+E1DRBaCiqTJKbEAVIEX8AqtfMElskQQLfAUKcAlsecAk0SqnxMjAxSuwBig5RUaJBSjJADRq82MmsMJzZ0E61wEl3wPtAxoMMerPYyaJaUCzgeaALOMUmABUzwxxy9XHIPLuTRD57CETF7vA/t1MEmdlgYxrD8AMToF1zyDKlbiAYcEawBLBksCyiAlo1wwmhlGAFQgZkKqjioWDUYIpShEYnUwKwCRnweLA4sEqJSgAFFUQMfgPA4xdjNwGBqbGRgZA0sj4EaMEx+XzTAI3zzNJHHrKpPDhEpPGl0tMBp8uMb1gZPnAyD6LkeEWI8MsJgalx0ycYJsa0hwEIXaKOEjOmgkCJ+0tISIX7BXTwOCavdFmJoVgCVYtGkfyh0YHahjTcPIIVcwhBUDCbO97B0cI/4d9AmMQOFvYcl1fXGD7yf7wV42Y/kN/7Yk1sVpknfvDqi32bwJ3yLW+vohD3wd7iPnf7OVbXwNVfrUH6RJZ990eRLo/fGUPtBRo83ui7aUXEDIAO7iV3QGS7pgdCOkAAFkfthE=

RNG Seed: 1051430707

Rotation is empty
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xcfa20, 0x3340c8})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).rotation(0x1966000, 0x18cd4a0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:468 +0x84
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1966000, 0x18cd4a0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:25 +0x26
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x18cd4a0)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:44 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x18cd4a0)
	/home/runner/work/wotlk/wotlk/sim

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
