### ISSUE TITLE
Crash Report -1868309074

### ISSUE THREAD

**Issue by adamthom-amzn** [wowsims/wotlk#2814]
Probably a build you have no interest in supporting: was goofing around at what a scourge strike/imp icy talons build would look like

Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EU3vcak901acaosIZU4xZBA4XZXQL1tOsPKJ6CXuqxSkugHtooVgvVVBClIqVgSxrSH4qHHj1J1NYK/SMHNUJTSoogaUMiRhsQsebkbFIKgmCK9ebb3Tfv7/v2zfBGlHkkSDEI7RAGmAB4AvAKIAmQB9gATCKeJF6kYEATq7kPMAbg4twru+6ANXCl+WZLiBeI6J4H0UlGMih9rJOtT2fwzWsUBbKcQ7mmFEfRTsZY7kOdXDPJPBvpf4nSgIdBYiy8wSAjCWSv6CC9L1C6e1C2sDqOucMs/8iz6TrJl1WUBWYvxdEkcpJRll9n+JlyjAW+r6I06NkKWMiDZ6b+tGbqwlTZfmsWfs2hNOGWrZMVKo4l+p6j7OCROgKWJssNc7PjyPYRQe6//FZcdLuILoEHCYMim6ISKOJ+HghIbLjOQgDi5bkrArgloVJ90dhTMYq6F3wchV5QqNagqVT1U79CqapSjSoNqkbZqml+tqgK01QztcIeqmRA4ocXkRSyKH3OojeyiEcjKaRDKcyDpQi2KPCiOQDsSwMXRU4uYKWBcKtxIDpkSkI/XukkqR9uLcuSrs5he6y7yx5ovnY52NkSavOqfu8Fiff944Ep9hg7QRNOzP4ND230tZ/YLqh8iOHBjLGJzOvskp0v37FA7vT76Yc2gzrsx0Jt3/RqKTs9pb3jo1mdvNt97ur1OT05f+TQY1ib/rWquMXXs0+oTS/80NOZ2tsr98A4NXVrvf4MZ/zpP42zHZ6FjljVfe2UuGjfQH+q+1K9US3iJzQeul0=

RNG Seed: 1129975051

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf7360, 0x13e0e90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).uhDeathCoilCheck(0x2042800, 0x1bdd6b0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_unholy_helper.go:358 +0x18
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_UnholyDndRotation(0x2042800, 0x1bdd6b0, 0x2338000, 0x202ad50)
	/home/runner/work/wotlk/wotlk

**Comment by rosenrusinov** [comment]
Should be working now without a crash
