### ISSUE TITLE
Add Training Dummy as the encounter NPC

### ISSUE THREAD

**Issue by dimkasta** [wowsims/wotlk#2822]
**Is your feature request related to a problem? Please describe.**
Many times, we sim and then try to work on our rotation on a training dummy, with results having bigger or smaller deviations. 

**Describe the solution you'd like**
The idea is to add a training dummy preset for the encounter, so that we can get a more precise idea of what is going on when trying to work on our rotation and find pain areas.

**Describe alternatives you've considered**
I tried doing it with a custom, but I am not sure what proper settings are for a dummy

**Additional context**
In the same concept, it might help having a predefined buff preset for "self-buffed"

**Comment by Tharre** [comment]
The default encounter setting is equivalent to the (boss level) target dummy, minus any of the bugs specific to target dummies that nobody sane is going to try and reproduce.

Unless there's something I'm missing?

**Comment by Tharre** [comment]
Actually there is one difference, you need to set the execute percentages to 0.

**Comment by dimkasta** [comment]
Is there a way to revert to the default after you have selected and saved for example Patchwerk?

**Comment by Tharre** [comment]
Not sure what exactly you're referring to, but you can either select one of the NPC presets again, or reset everything to default with gear icon on the top right -> restore defaults (this will not delete any saved sets).
