### ISSUE TITLE
i dont see sim fire mag. Please add this bield to sim.

### ISSUE THREAD

**Issue by Apokalepsiz** [wowsims/wotlk#2827]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

**Comment by lologarithm** [comment]
Could you please link the item again? We should have all items already. It is possible its in a different phase than you currently have selected in the item UI

**Comment by vigo2** [comment]
Fire mage is supported, you just have to choose the rotation.
