### ISSUE TITLE
Crash Report -2024092309

### ISSUE THREAD

**Issue by juni0338** [wowsims/wotlk#2835]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1C7WJka2gJzEytQiDmYBNqkXjFz8AmtfMEm8lFVi23aYaf8OJi5OgZ/PmJSYQUx+gb0PmSQeAOWAPJAAu8AKoMBUGS4hgYWPmSR+yCpxft3BdO4sWJJXYPUTJolWOSUWoBgDkLsGaPAUGSWWwyCukEA/kNsvo8QJMQukQ0jgAdCU97LIYvwCf4Bi02TgdnIKPHgOdQ+nwKeXUCaLwLOHIPLacyYuHoE1QC1nZZWYgTYBea+eIXjsAk1AR82QUeIChhNrAEsESwLLIqazTFwzmBhGAVYgZECqjioWDkYJpihVLgEOJgEmCSYFYJK0YHFg8WCVEgTyGRVEDP7DAGMXo7iBgamxgTGQ1AViMDLWNTUwesTIw3HiKZPA8adMEgefMr1gZPnAyD6LkeEWI8MsJgalx0ycYNsa0hwEIfaKOEjOmgkCJ+0tISIX7BXTwOCavdFmJoVgCVYtGkf0h0YHahjTcPIIVcwhBUDCbO97B0cI/4d9AmMQOGvYcl1fXGD7yf7wV42Y/kN/7Yk1sVpknfvDqi32bwJ3yLW+vohD3wd7iPnf7OVbXwNVfrUH6RJZ990eRLo/fGUPtBRo83ui7aUXEDIAO7iV3QGS7pgdCOkAAN8sv2w=

RNG Seed: 1105866867

Rotation is empty
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xcfca0, 0x3361c8})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1968880, 0x185d080, 0x1938000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_generic.go:271 +0x8f
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnEnergyGain(0x1938000, 0x185d080)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:35 +0xe
github.com/wowsims/wotlk/sim/core.(*Unit).EnableEnergyBar.func1(0x185d080)
	/home/runner/work/wotlk/wotlk/sim/core/energy.go:44 +0x12
github.com/wowsims/wotlk/sim/core.(*energyBar).newTickAction.func1(0x185d080)

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
