### ISSUE TITLE
Sim is off by 1k dps compared to gameplay tests on a dummy

### ISSUE THREAD

**Issue by guywolfus** [wowsims/wotlk#2850]
**Describe the bug**
Testing my dps on a dummy produces very different results than what the sim suggests.

**To Reproduce**
Run the sim vs. test that gearset+setup on a dummy I guess? haha
I've been practicing unbuffed (except self applicable buffs) on a dummy and got very different results.
My character is indeed a dwarf, enchanting + tailoring, gear set is matching as well as the hit/crit/haste stats.
Only using Inner Fire and spirit buff on self, not using potions or any active cooldowns (no shadowfiend either).

**Expected behavior**
Details plugin on a dummy says I'm doing around 4.8k dps, however the sim shows around 3.8k which is a massive difference.

**Sim Links and Screenshots**
`https://wowsims.github.io/wotlk/shadow_priest/#eJzjYjFg8mB04pRgVGAqYFzByCjEIDWDtYmRLSAnsTK1iINZgFXqACMXv8CdF0wSb2SV2I4eYtq3g4mLU+DtMyYl5nNAJo/AVaDcI1klZpAEu8DV3UwSXbJALTeAwj84lNiAwiAZXoG2XUwSc4SUWIA8BiD3MlB+naQSywcQl1/g62MmJc5bYLUQgz7sYZJYIAeU+feYSeIT0O5bMJmdD5gkGuSAjN9PwAwWgb2bmIDkq70g2dtA2V+yQO7uByDBiU+ZlBgWMZ1l4prBxDAKsAIhA1J1VAGTS5AoFy8whTBKgkUOJDlIsQgwKjB2MaoamBoYGxkYG+rqGhuZGhgZG5gaGgFJQ6CosaGpIZBlbGr4iFGCY/lpJoH1p5kkdj5lUnh9iUnjzSUmg3eXmF4wcn9gZJ7FyMHFxMUAwrcYGWYxMSh9YOIE29WQ5iAIcYeJg+SsmSBw0t4SInLBXjENDK7ZGx1gKphTW8UZkFiSnFGeWpStEKxF40TwodGBGsY0nDxCiTkGFloFjqRqAodfw7RHDlCdL+w7GBmD8OYbzZj+Q1819tiLrHN/WCVyzx4i+sEeJn99cYEt1/XX9mDpdc/tIRHzyx6XeUMNkJ5vAD6Clts=`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 111.0.5563.65 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not applicable.

**Additional context**
None.

**Comment by vigo2** [comment]
It'd be helpful to log your dummy gameplay tests (don't forget to switch on "Advanced Logging"), and post the upload link here.
