### ISSUE TITLE
100dps decrease when I remove 1 haste rating (not % but rating!)

### ISSUE THREAD

**Issue by rextrix** [wowsims/wotlk#2851]
**Describe the bug**
As subject says, very small variance in stats (1) results in huge performance difference. Obviously this is not expected and is only visible in certain fight lengths. Strangely it is seen when the fight is longer, despite that logically haste is more beneficial in short fights due to OOM scenarios.

**To Reproduce**
1) Use this setup:
https://wowsims.github.io/wotlk/mage/#eJzjUudgsmB0YPJgnMDIeIPpC/MKRsYNjEwHGBlPMDJeAAoxMj5gZHrByOgkxMEowajApMFowAjUwBjAGMEoxAJiS11jbWJkC8hJrEwt4mAVYJY6x8jFL7DxBZPEG1kltqOHmPbtYOLiFHj7jEmJGcTkEdgGlHskC+M9vc4k0QXk3QLy+AU2AeV+APUB5UDSvAIvgNJzhJRYgDwGLgGBh0+YJKbIKLEDVX8GifALfH3MpMR5C6x8H9iIrUAj2iFGQMz895hJYpqMEhtEEReLwM4HIPL3ExB57jGI3PQYpHAiUGGfHFghSCcDUOI40HQODqCnA1giWBYxnWXimsHEMAqwAiEDUnVUCXIwCjAVMFYwNjAydoCSHqOTOpd8JUT2g30jI4T1wL4TyrpgL8EoxcLBJJHSxahlZGxgYGAKJA0NDIyBpKmBsZGxobGRqYGpsZGugbGuAVAOpMjwEaMEx+z7TALvzzJJ/D/LpPDkEpPGg0tMBj/uARM3ywdG7lmMDJ3QiLVzuMXIMIuJQekVEydYoCHNQXLWTBA4aW8Jc4ZiGhhcszc6zFTwraaK1zs1Rz0ko7QqMUXByFQhWIJDi9YppcWBGqY0nDxCiTkHjNSLHEnVBA7FA+J3HBwhocjkEIQ3Z+2Qa30duOOe/cMqkXXuD2/ZQ0Q/2HNdX1xgy7XdPgis4IZ9/6GvGjH9j+xBqqpE3tmT66nBBkjPWQBpFLY3

2) Simulate results and save as reference

3) Manually add "-1" haste rating and re-sim.

4) You will see around 100 dps loss decrease.

**Expected behavior**
Expectation is dps to differ by 1-5 (usually around 1) when you adjust Haste by 1. Note that with this setup the bug is only visible in 180secs fight. When you move to 120secs fight the bug is gone.

**Sim Links and Screenshots**
Sim link is in the steps to reproduce.
![Capture](https://user-images.githubusercontent.com/129693159/229377859-341f186c-cd95-497f-bc95-ea4d1025b7f5.PNG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge and Firefox
 - Version both at latest

**Comment by lime-green** [comment]
@rextrix it's because that 1 additional haste manages to get another arcane blast cast at the 180 fixed duration. Do not use 180 +/- 0, use something with variance such as 180 +/- 5

**Comment by rextrix** [comment]
Thats correct. I tested and confirmed. I definitely did not expect that to be the case. Thanks for the very quick response!
