### ISSUE TITLE
Demonic pact is wrong in old saved settings

### ISSUE THREAD

**Issue by Sadoed** [wowsims/wotlk#2852]
**Description**
When i use my saved buf settings from The March Demonic pact gives 5000 spd instead 500spd in new metric system. So simulation is wrong. And its hard to find the bug.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Saved settings' from The March or some later date. It has to be set Demonic Pact in big value
3. Simulate and see +1...5k error dps.

**Expected behavior**
Old settings must follow the new metric system of Demonic Pact.

**Sim Links and Screenshots**
Here is screenshot of bug
![bug_demonic_pact](https://user-images.githubusercontent.com/40039290/229379359-33948757-0b79-4754-8725-bad5b9e61d50.jpg)

**Desktop**
 - OS: [Win 10]
 - Browser [chrome]
 - Chrome Version [111.0.5563.147 (64 bit)]

**Additional context**
Here is the screen of true behaviour 
![true_demonic_pact](https://user-images.githubusercontent.com/40039290/229379373-dc9643a6-234e-489e-a9b1-f875b144d396.jpg)

**Comment by lime-green** [comment]
Fixed in https://github.com/wowsims/wotlk/pull/2886
