### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by Nepert** [wowsims/wotlk#2855]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/spell=55628/socket-bracer
https://www.wowhead.com/wotlk/spell=55641/socket-gloves
Hi these are not really items but they are missing from the enchant list.

**Comment by ncberman** [comment]
Set one of your professions to Blacksmithing and the extra sockets will be added
