### ISSUE TITLE
Crash Report -977721445

### ISSUE THREAD

**Issue by Xabi787** [wowsims/wotlk#2858]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztUz9oE1EYv+/LJV4ONK+Hw2tIy3nTKVTe3RHQQe7ilDHo0sWhoNUhaHHSTtEiqIsOKppJRaQiBXGQDGql1UqhqbGgg1NqYxIRMXSQIh383l0rIh0sqZs/jnvf+32/7w/vfU+3NWBog4B9kIcTMAIlgKsA4wAVgBcANYA2wArgwZ0amKGuAIOkuxiKDCX9NX4eEoXi0NljpzWNQXoR9BR720b+uc9KPJnGqQrqSVZdQismzRR7toi8Tj7aRUSthfx6JiR+EGGwO0vIV/qsZKSQou1soon8Qr+lfqqgQtt5KnAtY6lTcptiV9r4u9xgdUrxjVI8rWD0kWiVuBtUZ41IsnqLmrrflOZ4g0zJquxLU/4fNGTIRAN5lXqlqvNV1BVyXHqOFtNQxArqoHpGnhcdxV0k701U/mNDGGKzEaM7aDCBw22IZvIx2HqGx02w4YCimLkgnu8/oihBTnp76QbSGjvKQfovw+6BrPBc4Tqe67mucITIeo4jPE94jsg6zoArsqQQjvsRuDYziewe3fOrSTTL79B+vYBiegHboHZgWxk0PaGrWvNh7AMoZVSs75gMOywNBz1Rr3uD3vItiVl/f8TU/F3DId777gyOtEo4queKx4eKp06abtY8zNU9/3hYOueCrUhTmn3ZTZ5Hb5bHcpsNCs+wNLccrEV2/Lx8YofCF+aFiK031U1zG6DjV+ckVn+t6/X+XLe2bvcwRDRwIvjbiJ/tqbsq

RNG Seed: 2495880957

Trying to cast {SpellID: 16857} but GCD on cooldown for 1s, curTime = -1s
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xd0960, 0x2052ea0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x2013d90, 0x1abaf00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x2013d90, 0x1abaf00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:156 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncInit.func1(0x2013d90, 0x1abaf00)

**Comment by jarveson** [comment]
fixed. sim didnt like both prepop zerk/ omen
