### ISSUE TITLE
Crash Report -1935022104

### ISSUE THREAD

**Issue by spyhunt3d-cyber** [wowsims/wotlk#2859]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztVEtoE0EY3v/vNp0M1I6rlDGkYd2DpkJhdpccPMTdeOrBQ1EQDypRtIh4CD1VT1EoWC8KPtDcrB4U6UFBKQVtSX2QQ2staEUUojUx6qHFBxYN6OxOexA8WIg3v8P8+3/f/5jn0naCAn3IQg7yANcApgFqAFvXEDAln4P+gD8ZSoYWG4qcgEjPkX1HD/YRwiBWAtrGntSQv++wIncmsDiCVGf1Ckr67mvkZUlLLqBb2M0q8vNxarDLc8gXO6yoUgKxlQ1LcSBh6d9HUJPulKx5Lm7pxcCNsoEqWk1BoMHKMnleJV8vhcltrC65C/GwleRk/Jm5pXidVcrB+PFxMI6PBtHDb5FPyonJVlOTSDUpDN5Dq1Vuhd6j79L7g/UOoZQuovYff4QhVppxjBDgmIVD9BZsoDGCvNmEtKaZGb+5O7FH055n8pCQOx8j7AAHE5JwCjq7UsJ1hGO7jus4whYi5drSd4Vri5RtdzkiJSOE7bwBTh6OIbsqD/fBGJqFp5h8NINiYgZroC9ASwGyNEl1Ur3RZJhqSlv80OR3Kju+X1n/sE9jdBUZbDd/LgMMspxDubwwZ0fRYL8vcK//ArQCalYFo6pur79aSWv9dYVLAUreZsVMe+t7QzzznNto7uBk0z++bAvH/UaUyZfuN6TOSqD2bNsrP6P8Ra9b/rG2hw+Uzl7JpekPT9lvXqN6qnrvvHT48cHr3H26+DX5xVOn9mmpT90Lw2Y/N6xvo2CIcMIvN/p/m/ELv128YQ==

RNG Seed: 1754296876

Trying to cast {SpellID: 16857} but GCD on cooldown for 1s, curTime = -1s
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xd0960, 0x181d1c0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x18ca160, 0x1a10f00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x18ca160, 0x1a10f00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:156 +0x4
github.com/wowsims/wotlk/sim

**Comment by jarveson** [comment]
fixed. sim didnt like both prepop zerk/ omen
