### ISSUE TITLE
Shadow Priest DPS is off

### ISSUE THREAD

**Issue by CMMauddib** [wowsims/wotlk#2861]
**Describe the bug**
Sim says my Spriest should be doing over 17k DPS!

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/117476694/229880092-e51509d5-441d-48e3-abb2-f2aa41208f47.png)

Windows 12 PC

**Comment by where-fore** [comment]
I'm guessing this is related to #2852, your demonic pact is set to give you thousands of spell power.

**Comment by Tharre** [comment]
The meaning of Demonic Pact changed, change it to the amount of SP you want from it and your DPS will be fixed.

**Comment by CMMauddib** [comment]
I changed the Demonic Pact from 5k to 500, and I’m still getting high dps.

***@***.***


It seems to me that a LOT of the buffs are adding too much (playing with the buffs a bit).


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Tharre** [comment]
Link your setup, but I don't think there's any issue there. All the buffs seem to add the appropriate amount of values on the shadow priest sim.

**Comment by CMMauddib** [comment]
I got it figured out (egg on face!). I had it set to Hodir with the extra buffs up.  My bad!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
