### ISSUE TITLE
IDK fire mage sim seems broken

### ISSUE THREAD

**Issue by NicholasIzosimov** [wowsims/wotlk#2864]
**Describe the bug**
So, when simming mage in about 4.7k gs i get 13k dps (nice) idk checked settings and everyhting but cant find the issue. Does not do it for any other class.

**To Reproduce**
Ig check my sim export? are you getting the same result (13.1k dps)

**Expected behavior**
Last time i simmed before it bugged it was at around 8.2k dps

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
Sim Export:
https://wowsims.github.io/wotlk/mage/#eJzjkudgsmD0YJzAyHiD6YjwCkbGDYxMBxgZLzAyPmBkesHI6CTBwSjBqMCkwWjAaMHoAFQawBjBmMCYwSjEZMAodZG1iZEtICexMrWIg1OAWeoQIxe/wMYXTBJvZJXYjh5i2reDiYtT4O0zJiXmz0Amj8DOR0wSj2QhPHaBrY+ZJLpkgVo2AbVskVRiu7WDCSTDJXD7IZPEHCElRgYuAYG7z5kkpsgosQMNAyIGoPKvj5mUOG+BuSAb+AW2AvUvkFNiA/JugQX+AU2eJgM2EKSCReD3ExD56hGI3L8LzN4LcsJ1oMJvskDuppsgwYlPmZS4OBgNuANYIlgTGBcxnWXimsHEMAqwAiEDUnVU8XEwCjBliKxgFCkApjVGJz0uMQ7GRsZZM0HgpH0nozEYHLaXEuFgkkhW4ub4DwOMGmuYuhi1jYwNDAxMDYwNDYG0sS6QDeQYGBgCxYEaDQ1MjQ2NgAKGxqaGjxglOD6fZRL4f5ZJYuVTJoUnl5g0HlxiMvhxD5i2WT4wcs9iZOiExq6lwy1GhllMDEqfmDjBAg1pDoIQKREHSZj7LCEiF+wV08Dgmr3RIaaCObVVnAGJJckZ5alF2QrBEhxaNE4zHxodqGFMw8kjlJhjYKFV4EiqJnAINkx75ADV+cK+g5ExCG822yHX+jpwxz37h1Ui69wf3rKHiH6w57q+uMCWa7t9EFjBDfv+Q181Yvof2YNUVYm8syfHT4MRkJ7NAKJvvTM=

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version idk

**Additional context**

**Comment by Tharre** [comment]
The meaning of Demonic Pact changed, change it to the amount of SP you want from it, in this case 250, and your DPS will be normal again.

**Comment by NicholasIzosimov** [comment]
Oooh ty!
