### ISSUE TITLE
Set sim to level 70 for prepatch

### ISSUE THREAD

**Issue by Undertoe** [wowsims/wotlk#287]
**Is your feature request related to a problem? Please describe.**
Have an option simply to set the max level to 70 instead of 80 to allow prepatch simulations

**Describe the solution you'd like**
Basically just a spot in settings that would allow us to change the max level between 70 and 80.  This would also require us to update talents & run only 2 greater glyphs.

**Additional context**
This is simply to enable the ability to do prepatch sims.

**Comment by jimmyt857** [comment]
Hey thanks for the suggestion, unfortunately this is a lot more complicated than it would seem. We'd have to update every ability, core constants (e.g. rating conversions), update all the old item effects / consumes, huge pieces of the UI, and a lot more. Basically, it would just be a ton of work and isn't something we're able to commit to.
