### ISSUE TITLE
Crash Report 1051486647

### ISSUE THREAD

**Issue by Felson36** [wowsims/wotlk#2878]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1BbWJka2gJzEytQiDlYBNqnLjFz8AmtfMEm8lFVi23aY6dxZJi5OgR93mJSYD+9g4uIRWA+UeyAL4bELdDxlkpgqA9SyGij8A6hl/w4mIOLiFVj7jEmiVU6JBchj4BIQuP2cSWKKjBI7RJ6BS0igH6ijX0aJEyIC0sQvsA4o9h5hCrvAt4dMEtNkgIzefUwS/2WBjFl7wAwWgbs3mYDkm70gR3U+ZpI4Kwtz4qtnEB7ICBaBtldMSlzAIGENYIlgSWBZxAT00QwmhlGAFQgZkKqjioWDUYIpSgkYfSwKwJRnweTA6sEKTHtS/AJACYP/MMDYxahpYGBqbGBsaGBibGpkCOQYGRgaGBsDBUwNdYFcMDLWNTUwesTIw3HiKZPApfNMEgefMr1gZPnAyDyLkeEWI8MsJgalp0ycYMsb0hwEIc4QcZCcNRMETtpbQkQu2CumgcE1e6OtTArBEhxaNI73D40O1DCm4eQRqphDCoCEmc9dB0cI/4e9B2MCYxA4r9hyXV9cYPvJ/vBXjZj+Q3/tiTWzWmSd+8OqLfZvAnfItb6+iEPfB3uI+d/s5VtfA1V+tQfpEln33R5Euj98ZQ+0FGjze6LtpRcQMgA7uJXdAZLymB0I6QAAzbm5Nw==

RNG Seed: 3837438148

Unexpected cast failure
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xd71a0, 0x355170})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1b8aa80, 0x201b3f0, 0x2028000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_generic.go:300 +0x7c
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnGCDReady(0x2028000, 0x201b3f0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:46 +0xd
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x201b3f0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:388 +0x10
github.com/wowsims/wotlk/sim

**Comment by zku** [comment]
The panic happens because the rogue sim wants to cast Envenom without having Deadly Poison on the target. The extra check here fails due to the dot aura being inactive:

```
		ExtraCastCondition: func(sim *core.Simulation, target *core.Unit) bool {
			return rogue.ComboPoints() > 0 && rogue.DeadlyPoison.Dot(target).IsActive()
		},
```

Guess the question then is why the rotation attempts to cast Envenom without having the debuff up.

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
