### ISSUE TITLE
Crash Report -554925008

### ISSUE THREAD

**Issue by witccvgd** [wowsims/wotlk#2887]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1E3WJka2gJzEytQiDlYBNqlnjFz8AlsmMEu8lFVi23aYad58Ji5OgZPdzErMICaPwDag3ANZGO9uN7PEVBkl5js7mbiEBB4AeT9klTg37WS69p8JJMYrsGUVs0SrnBILUIwByN0M1D5FBsrlF5jcwwxWDkFAga1A+fdAq4G8O2CB9UAzp8kosd2BCHAKPOpkhtjHKbBhFZTJIjCphxlIrlzFDHTUxh5mibNAJ27dCXLivW4Ej1NgLdBCEFOJFxhKjAEsESwVoMBYxHSWiWsGE8MowAqEDEjVUcXCwSjBFKXKJSDAJMGkAEyRFiwOLB6sCYxSggJAGQURg/8wwNjFqGlgYGpsYGxoYGxsamQI5BgZgthAAVNDXSAXjIx1TQ2MHjFKcJx4yiRw+TyTxMGnTAofLjFpfLzEZPDpEtMLRpYPjOyzGBluMTLMYmJQ+szECXbLgSIHQYirRBwkZ80EgZP2lhCRC/aKaWBwzd7oMFPB8wamKnbHnPTEnPw8hWAJFi0ap4kPjQ7UMKbh5BFKzNlw/lOzI6mawAHYcOaTA1TnB3sPUE4KAmckW67riwtsP9kf/qoR03/orz2xhlaLrHN/WLXF/k3gDrnW1xdx6PtgDzH/m71862ugyq/2IF0i677bg0j3h6/sgZYCbX5PtL30AkIGYAe3sjtA0iGzAyEdAKrAy4w=

RNG Seed: 3319272429

Unexpected cast failure
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xd7860, 0x356f68})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1b8e200, 0x1ba7ef0, 0x1b74000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_generic.go:300 +0x7c
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1b8e200, 0x1ba7ef0, 0x1b74000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_generic.go:297 +0x53
github.com/wowsims/wotlk/sim/rogue.(*rotation_generic).run(0x1b8e200, 0x1ba7ef0, 0x1b74000)
	/home/runner/work/wotlk/wotlk/sim/rogue

**Comment by witccvgd** [comment]
Changed a few items, switched the name of my saved gearset and ran simulate and it crashed

**Comment by vigo2** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/2901
