### ISSUE TITLE
Crash Report 1238967129

### ISSUE THREAD

**Issue by vic6string** [wowsims/wotlk#2891]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EU3ve6rZvVkjHmsC5NiXsqhcrsDgE9yKxe9BjrpQcPerB48FA8ab3E0kLxoBeRNCCizaEnEQuSg0JoRS1YDZK04ClpaNlSoaEgDf7V2ZmKF4stxJvfZd/P9977Zuat6RhIkOJlGIIMwBTAE4AiQAkgAGgClhBPkSRS8GFAcMYlJ6bZr9tHoCN95eL1S1cNIKZdBDNKpqtorSacjmez+G4eTZ18XUbzABlfQquacNqeF9DcRz4I0mZCsB8EaDUFW4TDTCcprqA11u3owtOE+1Dk73ZtuxGSWUHVIkryIrP+uzJKNuto3euSgQU5ZKaG1lZCGE+r0tDJ7XwoaO29lCCyU7YwNpShk1c1dKIG0s5jkNYH9GvhQR+hOEMWtf/4I2J0rxXDugEWfgHXPCS2TmzUGUhDAeBNuG9o2wcVrcGT0Lvf2PoFoHALjvYxj9IUS1FKPY8y6vZ5jIovc0WIeW5KpJlLqesy12NLYBn3y0g+LYvFKGMyW8aebAXpRAUD0BvQlgPtI2g51Jw6RuTYzKC/LSDuH85NhJjjx1WkxI8MSixwbxqT56z23n+8GI2bfivaZOZetqTPXqDu7MW6f1L5TX4B+uWvNPu55/ydmYi/ODl0wlys8912VK+xylV9ZYe6Bi90j62dLfzg/dIIuKr7zvPhuMmAxx+frg3HN3ace0MSRnetq1WI0fm3IQxfKf32VwU/AfiFxj0=

RNG Seed: 2058380093

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0x1013e0, 0x1472b00})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*SnapshotManager).ActivateMajorCooldowns(0x0, 0x1b8ac60)
	/home/runner/work/wotlk/wotlk/sim/core/spell_snapshot.go:72 +0x2
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_Haste_Snapshot(0x207f0e0, 0x1b8ac60, 0x19b1900, 0x1afef90)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_unholy.go:384 +0x4
github.com/wowsims/wotlk/sim

**Comment by lime-green** [comment]
was fixed in https://github.com/wowsims/wotlk/commit/fb4a9a702c17234ac1a25b047d2ab29c9fcd502d
