### ISSUE TITLE
Balance druid sims, T8 resto set pieces showing higher DPS than Balance tier set.........

### ISSUE THREAD

**Issue by Ifartstarz** [wowsims/wotlk#2896]
Like I said in title, its showing Resto tier set as DPS increase over Balance tier set pieces.

**Comment by lime-green** [comment]
@Ifartstarz are you actually running the sim or just looking at EP values? Those are not an accurate measurement of DPS and only are used for ordering items in the menu

**Comment by Ifartstarz** [comment]
> @Ifartstarz are you actually running the sim or just looking at EP values? Those are not an accurate measurement of DPS and only are used for ordering items in the menu

When I click on an item slot, its showing the resto gear higher

**Comment by lime-green** [comment]
@Ifartstarz you shouldn’t rely on the item ordering since that won’t take into account item set bonuses and other stuff. The most accurate way to compare gear is to press the simulate button with different items worn
