### ISSUE TITLE
Retribution Paladin - Showing wrong DPS numbers

### ISSUE THREAD

**Issue by GawainXL** [wowsims/wotlk#2904]
When I simmed my gear in March, I was around 8.5-8.9k DPS. I simmed it again today, with the same gear and now it shows 11k+ DPS. I checked the settings, but even if they changed, no way you'd gain this much. I've checked my P1 gear I had during Naxx and even that shows 8.8k DPS. Is there something that changed in April to the sim? Even on my mage there is a 600 dps difference when comparing it to the magesim from cheesehyvel

**Comment by lime-green** [comment]
@GawainXL do you have a link? You can share it via Export -> Link -> Copy

**Comment by where-fore** [comment]
Are you intending to sim against 3 targets?

**Comment by GawainXL** [comment]
ffs Thanks forpointing that out. I dunno why that happened, I never select the settings until today. Well looks like it's solved and the only issue is me :D
