### ISSUE TITLE
Nerves of Cold Steel adding Spell Hit?

### ISSUE THREAD

**Issue by dotcomrie** [wowsims/wotlk#2922]
**Description**
It appears that Nerves of Cold Steel is adding Spell hit. Does Nerves actually give spell hit? In game it does not show this for me with the WA that I am using.

**To Reproduce**

Set talents to UH (or frost) spec with 3/3 points in Nerves of Cold steel. Then observe the +3% more spell hit from talents as show in the screenshot.

**Expected behavior**
I would expect the Spell hit +3% to only count on melee swings like the tooltip reads.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/deathknight/#eJzjYnBiEGKQ2sTaxMgWkJNYmVrEwSrAJbWLkYtfYPMDJomXskps2w4zvdzBxMUi8PspExePwNIXTBIPZJWY9wDF2AXaHjFJfJcFqp4PFP4BVD3vJBMQcXEJXHjIJNEqp8TIwMUrsBAoOUVGiQWoh4GLU+DlAyYlZpAqIYFzQEveyypxAm1Y9ozpGtBMfoHvj5kkpskosQFV7wFb/PoJiPwFJl+fB5GX94AsvwS0YoUUgsEicOwhkxLDIqazTFwzmBhGAVYgZECqjiqGX4xmXGIcTAKMDowejAGMOxgZTzAyXmBk+sDIKCUjCFH1wV6CUYFRi5vjPwwwGjB2MerqGhsZGJgYmxoAgZGukbGBgTEQArnGRoamQCkDQyDb0NjQGCho+IhRgmPuFSaBN0+BaeAKk8KMK0waM64yGcy8yvSCkeUDI/ssRoZbjAyzmBiUHjNxgu1tSHOAukDEQXLWTBA4aW8JEblgr5gGBtfsjTYzKQRLsGrROGF8aHSghjENJ49QxRxSACTM9r53cITwf9gnMAaBs9Lhrxox/Yc4Ha4vLrDluv7YnlgTIbHx0h6i/yoOfR/sd8i1vg7c8c8+CMx4YQ/R99d+Cci6xS/sRda5P6wS+YTT3mqwghai3UUtIGRw9gwIcDhAXPqHoAsACa+5Yg==)

**Desktop (please complete the following information):**
 - OS: Windows 11  22621.1555
- Browser: Google Chrome Version 112.0.5615.49 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

![BuggedSpellHit](https://user-images.githubusercontent.com/69738942/231692103-d25dac29-e004-4f4a-a619-5a05bbfb7e04.png)

**Comment by rosenrusinov** [comment]
You are looking at the spell hit added from Virulence (uh talent tree)

**Comment by dotcomrie** [comment]
Yes I was. =)  I forgot all about Virulence. Thank you for seeing this (hopefully before many others) and closing it to save my noob ass the embarrassment.
