### ISSUE TITLE
Tiny Abomination in a Jar inaccurately modeled for retribution compared with original wrath implementation

### ISSUE THREAD

**Issue by huhsupomgosh** [wowsims/wotlk#2925]
Describe the bug
Currently Motes from Tiny abomination in a jar are only granted to Retribution Paladins on successful Crusader Strike, Divine Storm, and Auto Attacks. 

To Reproduce

    Go to the retribution simulator
    Equip some ret gear, Tiny Abomination in a Jar in the trinket slot and Shadowmourne in the weapon slot.
    Simulate the DPS and record the DPS number
    Unequip tiny abomination in a jar, add 85 hit rating to both melee and spell
    Rerun the simulator, again record the DPS number
    The difference in DPS should be ~3.5% more than the initial number
    Open the log and you will notice that motes are only granted after a successful crusader strike divine storm or auto attack

**Expected behavior**
Additionally motes should also trigger from application or refreshing of Seal of Vengeance and Righteous Vengeance debuffs. This is because of a hidden strike mechanism. "In patch 3.2, application of the debuff is treated as a melee attack. That is to say, it is not applied to the target automatically every time your melee swing lands—instead, when your melee swing lands, a separate melee attack is made to see if the debuff is successfully applied to the target." This remained in effect for all of WotLK. https://wowpedia.fandom.com/wiki/Seal_of_Vengeance

To clarify the DoT ticks from Seal of Vengeance/Corruption do not grant motes, only the application of the seal on the target. on an auto attack made with Seal of Vengeance/Corruption a mote can be granted for both the auto attack as well as the application of the seal onto the target, and when Righteous Vengeance is applied or refreshed following critical strikes made judgement, crusader strike or divine storm this should also trigger a mote. Righteous vengeance DoT ticks will not trigger motes. 

Here is a summary of the valid sources in original wrath that would trigger motes on a retribution paladin

Auto attack
Holy Vengeance/Corruption stack application/refresh
Righteous Vengeance application/refresh
Crusader Strike
Divine Storm

Additionally the debuff application/refresh from judgement might also trigger mote procs however I am still researching this. 

If you want to wait until there is more data available from blizzard before making code changes I completely understand, but I feel that at the bear minimum you should add a warning banner to the retribution simulator when Tiny Abomination in Jar is equipped that lets people know this and that the dps may not be accurate based on Blizzards implementation. Many people treat the SIM data as gospel truth which is a real testament to hard work you all have put in to make this simulator so accurate and reliable. Many guilds and raid groups are already using the SIM data from future phases to justify loot distribution in the current phase.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I was unable to reopen https://github.com/wowsims/wotlk/issues/2702 which contains additional context, and since it has been a couple weeks since this issue has been addressed I opened a new bug report.

Here is a list of the sources I used to compile this data:

https://www.mmo-champion.com/threads/688878-Tiny-Abomination-in-a-Jar-test-results-w-pic - "TAJ requires you to be standing right on top of the target of the proc (less than 2 yds). While running tests, I found that many of our abilities can proc a mote. Judgement, DS, CS, auto, and seal damage can all grant a mote."

"TAiaJ is proc'd by: Judgement, Crusader Strike, Divine Storm, Seal of Corruption, application of Righteous Vengeance, refreshment of Righteous Vengeance, Auto Attack, Seal of Righteousness, and Seal of Command (non-cleave portion). Every seal can grant a mote. I didn't list SoL, SoW, or SoJ because they really don't matter here."

Additionally here is an EJ paladin forum post from August of 2010 which explains how seals application works and how while the seal itself is not considered a melee attack the hidden strike mechanism that applies it is.

http://web.archive.org/web/20100807233345/http://elitistjerks.com/f47/t49865-paladin_retribution_pve/#Glyphs__Gems__Consumables__Enchants__Professions

https://wowpedia.fandom.com/wiki/Seal_of_Vengeance "In patch 3.2, the application of the debuff is treated as a melee attack. That is to say, it is not applied to the target automatically every time your melee swing lands—instead, when your melee swing lands, a separate melee attack is made to see if the debuff is successfully applied to the target. This separate attack can miss, be dodged, or be parried just like a regular melee special can.

Furthermore, in patch 3.2, if the target already has a 5-stack of Seal of Vengeance debuffs, each subsequent melee swing or special attack made while this seal is in effect will inflict 33% of the attacker's Weapon Damage as Holy damage to the target (twice this amount if the melee swing crits). This extra holy damage cannot miss, be dodged, or be parried."

https://wowwiki-archive.fandom.com/wiki/Righteous_Vengeance_(removed_retribution_talent)

**Comment by huhsupomgosh** [comment]
I'll keep digging for information and see if I can find any definitive proof of whether the judgement debuff triggered the hidden strike mechanic

**Comment by vigo2** [comment]
To test things out, I've added "phantom procs" for Righteous Vengeance and SoV applications:

```
13529 -    0 procs  0.0% (Proxy +85 Spell/Melee Hit)
14018 - 12.2 procs +3.6% (Sim)
14188 - 16.3 procs +4.8% (+Righteous Vengeance)
14316 - 19.7 procs +5.8% (+SoV Autos)
14447 - 22.9 procs +6.8% (+SoV Crusader Strike + Divine Storm; not in WotLK)
```

That's using the "P5 Preset (Placeholder)" preset. If you trust the "+3.5%" number, the sim is _already_ overshooting (since about 1k DPS is from Hand of Reckoning). TAiaJ might be undervalued, but I'd simply wait until it's available for testing. If it's actually beating Deathbringer's Will: great, one less contender ;)

**Comment by huhsupomgosh** [comment]
Based on the calculations there 

(22.9 (procs) * 3310.5 (Average Hit From Manifest Anger )) / 180  (length of the encounter in seconds) = 421 dps from manifest anger 

421 Manifest Anger dps / 14447 total dps = 2.9%. That seems reasonable to me, and close to the percentage of damage manifest anger made up of total dps. TAiaJ accounted for between 800 and 1200 dps for a ret paladin in original wrath depending on whether you had the regular or heroic version of the trinket and that lines up with the phantom sim.

If you want to wait to until the trinket is available to make changes, that seems pretty reasonable to me. It might be worth adding a banner or warning for retribution paladins when the trinket is selected until then.

**Comment by huhsupomgosh** [comment]
I found this blogpost from May of 2010 that gives a pretty detailed TAiaJ dps breakdown, unfortunately his links to the actual logs are gone.

http://modals-logic.blogspot.com/2010/05/how-good-is-tiny-abomination-in-jar.html

He noted 37 Manifest Anger procs over a 214 second encounter.

**Comment by vigo2** [comment]
If both RV and SoV applications proc TAiaJ, you arrive at 19.7 procs, or ~2.4% of total DPS (~2.6% w/o Hand of Reckoning). The 22.9 procs scenario assumes SoV is applied from CS and DS, which is a classic addition. However, "The difference in DPS should be ~3.5% more than the initial number" seems to be about _total_ DPS added by TAiaJ, not about Manifest Anger DPS only.

I've read through EJ's Retribution Paladin thread, and there's nothing really conclusive to be found. The Rogue thread (which the current modelling is based on) has both "pre-" and "post-nerf" numbers, since initially, TAiaJ procced from spell damage as well. It's unclear how this has affected Paladins, however.

With regard to SoV phantom procs, https://web.archive.org/web/20100507223304/http://elitistjerks.com/f76/t68951-retribution_updated_3_3_a/ states: _A "hidden strike" which uses melee combat mechanics occurs. If it lands it refreshes/stacks SoV DoT. Only white swings can trigger a refresh or stack. (This hidden strike mechanic can also proc things like berserking..)_
From my testing in classic, SoV applications don't trigger melee based enchants or auras at all, so I think it's rather unlikely we'll see extra TAiaJ procs come testing, but that's just my guess.

Finally, I don't think a warning is necessary, since for almost all classes, TAiaJ is the worst trinket option available, typically beaten by those a tier below. The heroic version doesn't even live up to its item budget, it seems, since all other heroic versions have both improved procs _and_ better static stats (~12-13% more).

**Comment by huhsupomgosh** [comment]
"I've read through EJ's Retribution Paladin thread, and there's nothing really conclusive to be found." Yeah this is one of the problems I encountered back in original wrath when I was theory crafting. It was really difficult to find reliable and accurate information. I had to dig deep. 

""The difference in DPS should be ~3.5% more than the initial number" seems to be about total DPS added by TAiaJ, not about Manifest Anger DPS only." I can say that once I did obtain TAiaJ and was able to physically test it myself (post hotfix which removed sources like berserking as a trigger) Manifest Anger alone would account for between 3.2% and 3.7% of my total dps output. With 2.5% being the lowest and 4.3% being the highest I ever saw. This blogpost from May 7th 2010 (5 months after ICC was released and post hotfix) gives a decent breakdown of TAiaJ: http://modals-logic.blogspot.com/2010/05/how-good-is-tiny-abomination-in-jar.html 

The user saw 101016 in a 214 second encounter on Festergut which is equal to 472 dps from Manifest Anger. Recount reported 12698.9 total dps on the fight. 472 / 12698.9 = 3.7% and then seal damage would be added on top of that. 

"From my testing in classic, SoV applications don't trigger melee based enchants or auras at all, so I think it's rather unlikely we'll see extra TAiaJ procs come testing, but that's just my guess." Yeah you could be right, Blizzard has certainly made changes to the way things work in classic so retributions interaction with TAiaJ could be completely different than it was originally, we'll have to wait and see.

**Comment by Watcher7** [comment]
I've re-added the phantom strike behavior in [2446676](https://github.com/wowsims/wotlk/pull/2970)
With an empty proc mask for the phantom strike (basically current behavior) until the proc-from-procs behavior is hashed out.

**Comment by vigo2** [comment]
Updated the numbers from above with better gear, a bug fixed, and adding SoV hits (seal damage):
```
 DPS  --  MA --    # -- setup
13902 --   0 --  0.0 -- 85 hit only
14398 -- 222 -- 12.4 -- baseline (81.6 auto, 21.6 jov, 30.5 ds, 40.4 cs, 5.2 how)
14555 -- 294 -- 16.3 -- +rv applications (~55.5 rv)
14787 -- 399 -- 22.1 -- +sov applications, auto-only
14987 -- 490 -- 27.2 -- +sov applications, ds + cs
15434 -- 692 -- 38.4 -- +sov hits
```
As for how TAJ most likely worked, I've found this: https://discord.com/channels/891730968493305867/932806215682105475/1101611428227588127.

**Comment by lime-green** [comment]
This was fixed in https://github.com/wowsims/wotlk/pull/3129
