### ISSUE TITLE
Blood knight tank high damage rotation options

### ISSUE THREAD

**Issue by Bigwilleh** [wowsims/wotlk#2928]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Allow priorities for the following:
-Prepull army of the dead
-Raise dead offensive usage
-Heart strike priority for death runes (from death rune mastery)
-Dancing Rune Weapon usage
-Dancing Rune Weapon RP priority
-Dancing Rune Weapon cast priorities (fresh diseases, no changes to current rotation, deploy with full death runes, etc)

**Describe alternatives you've considered**
I've kind-of guesstimated it by running parallel runeblade sims and blood tank sims, and doing some math to change out ability usage in each of the results, but this is cumbersome and difficult to use accurately since it does not replicate the runeblade's duplication of rune strike.

**Additional context**
There are those of us playing old fashioned blood knight rather than whatever it is the private server guys did to replace squishy enhances. Since enhancements aren't likely to go out of style in classic, and since people are starting to discover the strength of old fashioned blood knight in general purpose tanking (aoe threat actually exists in the old variant), it would be neat to be able to sim it properly.

**Comment by rosenrusinov** [comment]
This is now possible with the new APL rotations and I have added a preset for a more dps oriented rotation
