### ISSUE TITLE
Parallel offensive and defensive stat weight columns for tank simulations

### ISSUE THREAD

**Issue by Bigwilleh** [wowsims/wotlk#2929]
**Is your feature request related to a problem? Please describe.**
It is a moderate nuisance having to re-browse item selections after alternating between offensive and defensive stats while simming tank, and setting up a combined weight set manually is relatively meaningless since offensive and defensive weights use totally different and unrelated scales (not to mention a combined result does not indicate the strength in each end of the measured scale).

**Describe the solution you'd like**
Capacity to set up two parallel stat weight columns with individual sorting capability.

**Describe alternatives you've considered**
Manually described combined stat weights, but this is a guesstimatey and uninformative approximation at best

**Additional context**
I prefer to optimize a balance of high firepower while retaining adequate survivability. It would be really nice to be able to efficiently simulate out empirically chosen gear sets for this.

**Comment by merijn** [comment]
> is relatively meaningless since offensive and defensive weights use totally different and unrelated scales

Unrelated to your actual suggestion, but I do have an open PR addressing this problem. It lets you pick the EP normalisation manually, so you can normalise mitigation and offense to the same reference stat (I've been using agility, as it has decent impact on DPS and on survivability, which seems to work fairly well), resulting in offensive and defensive EP that are "in the same scale" and lets you compute semi-reasonable threat:mitigation skews.
