### ISSUE TITLE
Missing Item: Collar of DIssolution

### ISSUE THREAD

**Issue by Undertoe** [wowsims/wotlk#295]
**Describe the bug**
https://www.wowhead.com/wotlk/item=39146/collar-of-dissolution
Item is missing from neck.

**Comment by lologarithm** [comment]
Looks like a couple items are missing. I will try to regenerate all items again. Thanks for the report!

**Comment by lologarithm** [comment]
fixed https://github.com/wowsims/wotlk/pull/317
