### ISSUE TITLE
Missing: Enchant Chest - Powerful Stats

### ISSUE THREAD

**Issue by Undertoe** [wowsims/wotlk#296]
**Describe the bug**
https://www.wowhead.com/wotlk/spell=60692/enchant-chest-powerful-stats
https://www.wowhead.com/item=44489/formula-enchant-chest-powerful-stats - added 3.0.2 so available on launch.

**Comment by lologarithm** [comment]
This is weird, it is in our enchant list but doesn't show up in the UI. I will debug this some more.

**Comment by lologarithm** [comment]
It is a conflicting ID between an item ID enchant and spell ID enchant

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/357
