### ISSUE TITLE
Incinerate doesn't get selected as filler on warlock sim

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#2962]
Selecting Incinerate in warlock sims rotation section doesn't actually do anything, the sim still uses shadowbolt as filler and only uses incinerate on MC procs..

Select Incinerate > check results > shadowbolt spam

Should swap to use Incinerate as filler instead of shadowbolt

**Comment by Tharre** [comment]
Fixed by #2963.
