### ISSUE TITLE
Resilience not calculated to Defense rating

### ISSUE THREAD

**Issue by silverselo** [wowsims/wotlk#2964]
**Describe the bug**
Resilience ins't counted towards the Defense Rating.

**To Reproduce**
1. Select Greater Inscription of the Gladiator for Shoulder enchant
2. look at the Defense Rating
3. see Resilience not being calculated

**Expected behavior**
Resilience should be counted towards the DefenseRating.

**Sim Links and Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

 - same behaivor on the website
 - Version v0.1.24 (Desktop App)

**Additional context**

**Comment by jarveson** [comment]
resilience doesnt count towards defense rating, 
it only lowers chance to be crit from pve mobs, this is accounted for here: https://github.com/wowsims/wotlk/blob/a7ae80460b1da5f752c430ca8d68bcd96c3775bd/sim/core/spell_outcome.go#L609
