### ISSUE TITLE
Yellow and orange gem EP values seem incorrect

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#2975]
**Describe the bug**
The EP value of yellow and orange gems does not match my computations.

**To Reproduce**
I'm using the Feral Druid simulator. I need to choose which gem to put in a socket. The tooltip at the top of the EP column in the Gem selection frame says: These values are computed using stat weights which can be edited using the "Stat Weights" button.

If I click on the Stat Weight button, the weight values which are currently set read:

Strength: 2.38
Agility: 2.60
Attack Power: 1.00
Melee Hit: 2.34
Melee Crit: 2.15
Melee Haste: 1.62
Armor Pen: 2.31
Expertise: 2.51

The EP values displayed for the red, orange and yellow epic gems relevant to the feral druid are:

Delicate Scarlet Ruby (+16 agility): **42**
Precise Scarlet Ruby (+16 expertise): **40**
Bold Scarlet Ruby (+16 strength): **38**
Fractured Scarlet Ruby (+16 armor pen. rating): **37**
Bright Scarlet Ruby (+32 attack power): **32**

Glinting Monarch Topaz (+8 agility, +8 hit rating): **48**
Accurate Monarch Topaz (+8 expertise rating, +8 hit rating): **47**
Deadly Monarch Topaz (+8 agility, +8 critical rating): **46**
Etched Monarch Topaz (+8 strength, +8 hit rating): **46**
Inscribed Monarch Topaz (+8 strength, +8 critical rating): **44**
Pristine Monarch Topaz (+16 attack power, +8 hit rating): **43**
Deft Monarch Topaz (+8 agility, +8 haste rating): **42**
Wicked Monarch Topaz (+16 attack power, +8 critical rating): **41**

Rigid Autumns' Glow (+16 hit rating): **45**
Smooth Autumn's Glow (+16 critical rating): **42**
Quick Autumn's Glow (+16 haste rating): **34**

**Expected behavior**
If I multiply the gem stats by the configured weights, I get the following results:

Delicate Scarlet Ruby (+16 agility): 16 * 2.60 = 41.60, rounded to **42**
Precise Scarlet Ruby (+16 expertise): 16 * 2.51 = 40.16, rounded to **40**
Bold Scarlet Ruby (+16 strength): 16 * 2.38 = 38.08, rounded to **38**
Fractured Scarlet Ruby (+16 armor pen. rating): 16 * 2.31 = 36.96, rounded to **37**
Bright Scarlet Ruby (+32 attack power): 32 * 1.00 = 32?00, rounded to **32**

Glinting Monarch Topaz (+8 agility, +8 hit rating): 8 * 2.60 + 8 * 2.34 = 39.52, rounded to **40**
Accurate Monarch Topaz (+8 expertise rating, +8 hit rating): 8 * 2.51 + 8 * 2.34 = 38.80, rounded to **39**
Deadly Monarch Topaz (+8 agility, +8 critical rating): 8 * 2.60 + 8 * 2.15 = 38.00, rounded to **38**
Etched Monarch Topaz (+8 strength, +8 hit rating): 8 * 2.38 + 8 * 2.34 = 37.76, rounded to **38**
Inscribed Monarch Topaz (+8 strength, +8 critical rating): 8 * 2.38 + 8 * 2.15 = 36.24, rounded to **36**
Pristine Monarch Topaz (+16 attack power, +8 hit rating): 16 * 1.00 + 8 * 2.34 = 34.72, rounded to **35**
Deft Monarch Topaz (+8 agility, +8 haste rating): 8 * 2.60 + 8 * 1.62 = 33.76, rounded to **34**
Wicked Monarch Topaz (+16 attack power, +8 critical rating): 16 * 1.00 + 8 * 2.15 = 33.20, rounded to **33**

Rigid Autumns' Glow (+16 hit rating): 16 * 2.34 = 37.44, rounded to **37**
Smooth Autumn's Glow (+16 critical rating): 16 * 2.15 = 34.40, rounded to **34**
Quick Autumn's Glow (+16 haste rating): 16 * 1.62 = 25.92, rounded to **26**

As you can see, the displayed EP for the red gems all match my computations, however the displayed EP for orange and yellow gems *do not* match the computations.

**Desktop:**
 - OS: openSUSE Leap 15.4 (Linux)
 - Browser: Firefox 102.10.0esr (64 bits)

**Comment by lime-green** [comment]
@jdelvare is there a socket bonus fulfilled by a yellow gem in which case you'd need to add the EP provided by the bonus to your orange and yellow computations

**Comment by jdelvare** [comment]
Oh my, I'm an idiot. I never realized that the socket bonus was directly taken into account in the displayed gem EP. I didn't expect that because set bonuses aren't taken into account that way. But I do understand that socket bonuses are trivial to convert to EP using weights while in most cases set bonuses can only be evaluated by running simulations, so the different behavior makes perfect sense.

Maybe it would help to add this information to the EP tooltip for the gem selection?

The gem socket I was testing was indeed a yellow socket which was giving +8 AP as a bonus. This totally explains the difference in EP for all orange and yellow gems (the difference between my computations and the displayed value is always exactly +8). Sorry for wasting your time, and thank you very much for your quick answer.
