### ISSUE TITLE
Draenei doesnt give you 1% hit, neither the race option and or the debuff in the options tab

### ISSUE THREAD

**Issue by Zitronenhaze** [wowsims/wotlk#2978]
Only tested it in the Shadow Priest part of the sim.

Worked until the recent update tho.

Thanks for all the hard work :)

**Comment by Zitronenhaze** [comment]
https://wowsims.github.io/wotlk/shadow_priest/#eJzjUuVgEmCyYPRgzGAsYGpgZJzAyPiA6QfrBkamA4yMN4AcRsYXjIxOfByMEowajAaMDowBjBGMQkAtUifYmhjZAnISK1OLgIawSj1k5OIXuPOCSeKNrBLb0UNMu58xcXEKvH3GpMT8eQcTF4/AVaDcI1kl5n1g3qYnTBJdQN4tII9f4AZQ7geHEhtQDiTNK9D2mElijpASC5DHwCUg8BCoeoqMEjtEnoFLSGAzUGSijBInRGQf2JRbQFPaZcGmfAQLnH/AJDFNBi7AKbD9MRPESk6Be8+ZIG5hETj3GETOegxy1xagub9kYTIbn4CUvnsIUarEwQEMgwCWCNZFTF+ZuA4wMYwCioCQAak6qoQ5GAWYJJgKGCsYgem1A5xkgyS5eDmYBRglIWo8HaSAESXAqABMsl2MqgamBsZGBsaGurrGRqbGRsYGBoZGQBJIGBkbmoJYxqaGjxglOJafZhJYf5pJYu9TJoXXl5g03lxiMnh3iekFI8sHRu5ZjEFcAlwsHDvPMgpxQOz5YA8WebaaGU2ksZcJJsLAwCXFxcfRKabwHwaQ9N9iZJjFxKDUzcwJFmhIcxCESKk4SM6aCQIn7S0hIhfsFdPA4Jq90W0mhWAJJi1ap78SB2qY0nDyCAFzvKliDzkAErYdhx0coQIOCYxBeHP27akMLdtLTtr/Ufj8RfjgPXuI6Af7ONW1F/9cOrgfpi6Y25PlctJre/Op0h7dbY/taeeHwQlIz9kAUyq59g==

**Comment by where-fore** [comment]
If you mouse over the Spell Hit field, you'll see 26 rating = 1% contributed from buffs, and if you change to another race and turn the Heroic Presence buff off, your hit drops by 1%. Running sims as Blood Elf and Draenei see the Draenei with 1% lower miss than the Blood Elf sim. Everything seems in order to me, not sure where your issue is.
Maybe the horde races shouldn't be able to benefit from the Heroic Presence buff, that would be less confusing.

**Comment by Zitronenhaze** [comment]
No it is definitly bugged,
if you add hit manually to my sim, the dps will go up, even tho i got 16% hit.
Tested it multiple times, aswell as other ppl from the shadow discord.

**Comment by Tharre** [comment]
> No it is definitly bugged, if you add hit manually to my sim, the dps will go up, even tho i got 16% hit. Tested it multiple times, aswell as other ppl from the shadow discord. @where-fore

The set you linked has 9% hit on gear, you gain 3% from talents, 3% from debuffs and 1% from heroic presence. That's 9+3+3+1 = 16% hit in total, 1% short of the hit cap of 17%. That's why adding hit beyond that makes dps go up.

Nothing bugged about that.
