### ISSUE TITLE
Demonic Empowerment only trigger once during fight.

### ISSUE THREAD

**Issue by yizhou1992** [wowsims/wotlk#2994]
**Describe the bug**
I found that demonic empowerment only trigger once no matter the length of the fight.

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tharre** [comment]
To be clear the issue here is not that it's only casted once per fight, but that it's only casted once every 3 minutes.
