### ISSUE TITLE
Rogue T8 2PC bonus issue

### ISSUE THREAD

**Issue by thegreatestqb** [wowsims/wotlk#3018]
**Rogue T8 2PC ENERGY RETURN ISSUE** 
THE SIM IS UNDER REPORTING THE ENERGY RETURN VS. DEADLY POSION CASTS 

**To Reproduce**
1. Go to '[...](https://wowsims.github.io/wotlk/rogue/)'
2. Click on 'SIMULATE' (WITH ATLEAST 2P T8 AND DEADLY POSION ON)
3. Scroll down to 'RESULTS TAB SCROLL TO BOTTOM TO SEE HOW MANY DEADLY POSION CASTS, THE NUMBER SHOULD BE EQUIVALANT TO THE RESOURCESS TAB "ENERGIZE" ENERGY RETURN GAIN' (DEADLY POSION EACH TIME DEALS DAMAGE PER WOW LOGS IS EQUIVALANT BY CAST TO THE ENERGY GAIN FROM THE 2PC T8 SET BONUS.
4. See error- CURRENTLY THE WOTLK SIMULATOR IS UNDER REPORTING THE ENERGY RETURN BY MORE THAN 58% GIVING A INCORRECT DPS OUTPUT WITH THE 2PC EQUIPED.

**Expected behavior**
CORRECT THE 2PC T8 ROGUE ENERGIZE SET BONUS ENERGY RETURNS TO BE EQUIVALANT TO THE DEADLY POSION CASTS PER SIM

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]- WINDOWS 11
 - Browser [e.g. chrome, safari] - CHROME
 - Version [e.g. 22]- Version 112.0.5615.138 (Official Build) (64-bit)

**Smartphone (please complete the following information):**- NA 

**Additional context**

**Comment by catszeid** [comment]
The 2PC T8 set bonus is working as intended and to the same behavior as the game. The set bonus has the text of _"Your Deadly Poison causes you to gain 1 energy each time it deals damage."_ The application of Deadly Poison does not cause damage from Deadly Poison. Rather, it is the damage over time effect that is applied to the target and ticks every 3s that counts for the set bonus. Deadly Poison does have the effect of triggering the poison on the other weapon, BUT any damage from that poison is not counted as coming from Deadly Poison and does not trigger the set bonus. 

To sum what I put above: The set bonus is working as intended and is true to the game client. The only damage that Deadly Poison causes is the tick every 3s from debuff applied, not any poison triggered at 5 stacks.

**Comment by where-fore** [comment]
If you wanted proof from Warcraft Logs of this behaviour, see this links of an Assassination rogue:
[36 Damaging ticks](https://classic.warcraftlogs.com/reports/a:wxjRK87QbycvDN6A#fight=26&type=damage-done&source=678)
[36 Energize ticks](https://classic.warcraftlogs.com/reports/a:wxjRK87QbycvDN6A#fight=26&type=resources&source=678&spell=103)
[171 Applications of Deadly Poison](https://classic.warcraftlogs.com/reports/a:wxjRK87QbycvDN6A#fight=26&type=auras&spells=debuffs&hostility=1&target=678)
