### ISSUE TITLE
Enhance sim: TypeError a is undefined

### ISSUE THREAD

**Issue by Surveillant0** [wowsims/wotlk#3019]
**Describe the bug**
When simming 300s enhance sims for p4 and p5:

About half the time I get an error "TypeError: a is undefined". 

**To Reproduce**
1. Go to my links below.
2. Click on simulate.
3. See error about half the time

**Expected behavior**
1. error should not occur, sim should complete

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE9IFFEYn++9cXd2WPU1SEybmg5RIhSzDlt6qHl5qugw1MXqkP2loGLxkkWgRpF/OoRY0dZBEtS2MDtkWQoLbsUG0p4kK9Sk0E6uYCRe7JuZNcIOIWmnvuH3eL/f+77vvXn8eHKhRHQohZ1gkUoIk1qAMfJO7AYSA0gCTAKUByRQoYAUAYcKCAOmtAJ0AjwDUITADe8l8FinD58/XiV5mTfwCeRsFr1O1a95mqdngPT0EtnHxpuoRmM49bNOXBvLW2BPo1T9jsxOU1jdNarO5mk+ZEPzxM7IZD2YcSVfE1ETkD7A8pbcNM1mL6JU87UnyGgvwRGF+7g+hVujYNdns1vY82au5om5go91Ywm1k31spCF9LJH1N1Ac+6IUD9WFJYPpQ/nZ41+YyCKNVMu0L80SK8RqqAe4R74ROUaE//FXoehLrbjgl4ARlaAd0ZTNcBnkallGjaJfQQcGgc0ykSiCIEQEIDIQHkQmwoeQEVkIryzopMzpzGv4DmcS7uC73M32cwvtf8pVr/KqLHTGw8/EcUbbBAlIEmFQQItII2zUQ4Zu6HqoZJOhh/AzbKLrQQMnRjBoBHHUQ8Fx8EvP44T1xYk6ECeTIKbAG4HtMpNFaSIFiuRuncMXKdz6TTnEZY+rvAchQgStifqclVgVX7XQZk3kth0J0/1LIWkWnnBiyCz5QAr2qVLxCvs4VceXo01tIr4sfVYi3Lvtn0o7SJg1K2Gv80J8dG5/2rzTmtGyLjxrLlQkDq5Plu+Z+8mVLcUbLo7PmIsaC9HmkVRZx7RZWl/ceGb+1aL1lHlseFJuOztnhobFyvyTX8xRiD1683rGrBl8sjVn9bT5sqv9SHJtBl+Jv/4Xoei7rbdDgbsK39ZWeu6oJfA/VRxY8pvyA+hU1DE=

https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnNm3J29rHobJKZNTYcoEYpZhy19qJl8quhhqBerh+yXgorFlywCLYr8CQqRfrYeJEFNxOrBJSthwa3YQNqnJStKxNCeXMFIfLGzMxphDyFpT53hu9zznTnfPfdy7mXFMupQDjvBxmoIYz3ACL6THgPGAJIAEwCVARlUKMISsKAKwkC/tAF0ATwFUITAHe9l8NinD58/XiN7uTcwBiyXd98U1a8Fmic6iNF+ZD4+2ixqYkcCmZ93UWykQBNj/Rkv3iyq3+e9XN5DsZlMXj+m5pBl8zkKXy3UJAoLjPPn5Lbma15yoxlG4X3E3MjXfC7jqjwklUlXxSVuXxfVW/maJ+YSPt6zUA5V1jg/lXhfo0jjAI1+3kspQ1RX1KnyyS+exCNNopadOTdbqpJqoQHgAX5DFkPhv/2VKfpSMy74ZeCoInUk9WULXAFWyxhxIrUs6MAhsJmhLBKQIBGAkEXwELIJPgIj5BC8TNCxwlG26qwdziTcae1yF9tv2XQDTrnsNasmhzqjZwydzmgfx4AsI4cisQSbYKMeMnRD10Nlmww9RJ+RcXQ9aNDECAaNII16KDgKfvlZHPmLOKqDcZwAKQ3eCGxnnEnyeBoU2V06z1rEWPZvzCGLeVzmPQgRFLRm0edEYjXWqgWZNZG7GUuY7i6FpFl8wrGUWfYBi/apcukK93H6krUcMvWJ+LLorIS5ZzswOd9BwoxZDXudF+Kjc/pT5r22rNZ14RlzISNxcH2ycs/sT1/ZUrrh4ui0uUhY6G75lK7onDLLG0qbzsy9WhRPm8eGJ1j72VkzNCxVF578Yn6G2KM3r6fNuqG+rXmrp8yXvR1HkmuzrJXY9b8wRd9tv00F7ivWtvbyc0dtwfpTxoElvyk/AG8G1KU=

**Desktop (please complete the following information):**
 - OS: Windows 11 and EndeavourOS (Arch Linux)
 - Browser: Firefox
 - Version 112

**Additional context**
According to Watcher7 and some sim people who are much smarter than me (I'm just learning programming) have pointed this out.

Watcher7: "That's not a Go error, looks like it's frontend error originating at https://github.com/wowsims/wotlk/blob/master/ui/core/proto_utils/logs_parser.ts#L829 

looks like when it attempts to look up how many times https://www.wowhead.com/wotlk/spell=58643/strength-of-earth-totem is cast in the logs it gets an empty value

not sure what the root cause of that is though"

`{
    "raw": "[298.18] [Player (#1)] Casting {SpellID: 58643} (Cost = 413.224, Cast Time = 1s, Effective Time = 1s)",
    "logIndex": 13068,
    "timestamp": 298.18,
    "source": {
        "name": "Player",
        "ownerName": "",
        "index": 0,
        "isTarget": false,
        "isPet": false
    },
    "target": null,
    "actionId": {
        "itemId": 0,
        "spellId": 58643,
        "otherId": 0,
        "tag": 0,
        "baseName": "Strength of Earth Totem",
        "name": "Strength of Earth Totem",
        "iconUrl": "https://wow.zamimg.com/images/wow/icons/large/spell_nature_earthbindtotem.jpg"
    },
    "threat": 0,
    "activeAuras": [],
    "manaCost": 413.224,
    "castTime": 1,
    "effectiveTime": 1
}`

" seems to be the offender, given that cast is happening at 298.18 maybe it's somehow not completing?"

This is all the context I have at the moment.

**Comment by MaxxSrini** [comment]
I replicated the error using the above links.

**Comment by zku** [comment]
Not sure whether the root cause is just a parser bug or if something is wrong with the sim itself, but what happens is:

Towards the end of the sim, spell 58643 Strength of Earth Totem starts but does not end (i.e. there is a abilityCastsBegan for it, but no corresponding abilityCastsCompleted). The parser code tries to access the corresponding completed event anyway and fails with this error as a result.

The question now is: is this an issue in the sim (i.e. there should be a completed event?) or does the parser have wrong assumptions? Given the comment here, I'd think this is expected but just not handled properly by the parser:

```
				// Assume cast completed log is the same index because they always come in pairs.
				// Only exception is final pair, where there might be a cast began without a cast completed.
				const ccLog = abilityCastsCompleted[cbIdx] || null;
				const nextCcLog = abilityCastsCompleted[cbIdx + 1] || null;
```

When there is no completed cast, accessing this undefined var leads to the error. Probably just needs a more strict check?
