### ISSUE TITLE
Swapping "Chance on" trinkets changes the DPS

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#3020]
**Describe the bug**
First of all: I'm not sure if this is a bug in the simulator, a side effect of the RNG implementation, or a game mechanism I'm not aware of.

Swapping "Change on" trinkets results in a different DPS for the same RNG seed.

**To Reproduce**
Run a simulation with RNG seed 42, Mjolnir Runsetone in trinket slot 1 and Darkmoon Card: Greatness (Agility) in trinket slot 2. Average DPS is 8293.07.
Run a simulation with RNG seed 42, Darkmoon Card: Greatness (Agility) in trinket slot 1 and Mjolnir Runsetone in trinket slot 2. Average DPS is 8299.63.

**Expected behavior**
I expected the outcome of the simulations to be the same when the trinkets are the same, independently of which of the 2 trinkets is in the first slot and which is in the second slot.

I can reproduce the behavior with any 2 trinkets which have a "Chance on"-style proc.

Is this caused by RNG number series being attached to the trinket slots, rather than to the trinket themselves? That's what I suspect.

Or does the game actually process trinket proc chances in sequence so the slot order matters? I'd be surprised, as for all I know trinket ICDs are fully independent from each other.

Or is this actually a bug in the simulator?

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.4 (x86_64)
 - Browser: Firefox 102.10.0esr (64 bits)

**Additional context**
My initial test was with my feral druid, but I can reproduce the behavior on my combat rogue and on my arms warrior.

**Comment by lologarithm** [comment]
We use a single random generator for each sim seeded with the seed + iteration#. If you change the order of the sims it is likely that the sim will change because they could swap the order they activate in. If you increase the iterations a bunch does the DPS converge?

**Comment by jdelvare** [comment]
Yes, if increasing the number of iterations, the DPS values appear to converge:
3000 iterations, DPS difference is 6.56.
30000 iterations, DPS difference is 1.11.
100000 iterations, DPS difference is 1.23.
300000 iterations, DPS difference is 0.22.
1000000 iterations, DPS difference is 0.27.
We can't reasonably expect reaching 0, considering that the DPS value is given +/- 249 DPS (I assume this is standard deviation) in the first place.

I asked because I was wondering if maybe there was a game implementation detail which would cause the trinket order to actually matter. However if the same RNG generator is used for both trinket, then this easily explains why the numbers differ. I wasn't sure if that was the case, as I learned from a discussion in a previous ticket that the simulator actually used dedicated RNG instances for many things, precisely to limit the effects of random when using a fixed RNG seed.

The only thing which still makes me wonder, is that even though the DPS difference diminishes as the number of iterations increases, it's always the same trinket order which has the higher average DPS value. But maybe this is just random and not relevant.
