### ISSUE TITLE
[Elemental Shaman] Several Shaman totems being hardcasted

### ISSUE THREAD

**Issue by raethkcj** [wowsims/wotlk#3025]
**Describe the bug**
If you select HST instead of MST or no water totem, it takes up the first GCD in the sim, rather than being assumed to be "predropped" like other totems. This GCD can easily occur inside several major cooldowns, causing a large apparent DPS loss.

Additionally, if you extend the fight beyond 5 minutes, your starting totems are refreshed invidvidually, rather than in a single GCD like they would be with Call of the Elements.

**To Reproduce**
1. Go to https://wowsims.github.io/wotlk/elemental_shaman/#eJzjkuRgsmD0YJzAyPiAaQLzBkamA4yMFxgZXzAyOvFwMEowKjBpMAYwRjAKMUhNYmtiZAvISaxMLeJgF2CXesLIxS/Q+JJJ4o2sEtvRQ0wfdjBxcQq8fcakxPwZyOQRaAbKPZJVYt4H5u16yCTRBeXxC/x7wSTxA6gPyAMJ8ApMecwkMUdIiQXIY+ASEHj4hEliiowSO0SegUtIYANQpF9GiRMiAjGlCWhDJ8SU22CBh0BTpsnABTgF7j1ngljJKbD9MZTJInDuMYjcvwvkrjVAc3/BXTkPaMALDpi607uYlHg5GA0YA1giWCsYOxgZFzF9ZeI6wMQwCigCQgak6qhi42AUYCpgTNLiUpHiArKZJZgUmAwYOZg8wfINAQ4ajIEQtSIOFoxSTByMXYzKxqbGBgYGhqZGxkaGxsamhsZGRsYGhkCGroGBKRAaGBs+YpTg2HOESeDCUyaJA0eYFH7fY9L4dYnJ4OxVpheMLB8YuWcxCnEJAFPDrMdMQhwQG/QcbjEyzGJiUOpm5oRYn+YgCJGScZCcNRMETtpbQkQu2CumgcE1e6PbTArBEqxaNE5BHxodqGFMw8kjVDGHFgAStnvfOzhC+D/sExiD8ObNjrRsj0yJM/aooh/s0dWdsN3Qrff9iX1omrHBxthPGPLDHZCeN6NI1gEA+JWewQ==
2. Use seed `2564654986` (might not be necessary)
3. Check Results -> Timeline, or Log tab
4. See Healing Stream totem being cast

![image](https://user-images.githubusercontent.com/7716908/236058460-66462a4d-89b4-40d4-b741-6ab4c0ccb208.png)
![image](https://user-images.githubusercontent.com/7716908/236059098-0ca258cc-135b-4b59-8c7d-f17cae630484.png)

**Expected behavior**
Healing Stream Totem should be "predropped" before the fight, like other totems.

**Comment by raethkcj** [comment]
Even after the fix, for fights longer than 5 minutes, the water totem gets refreshed on a separate GCD from the others, for both Mana and Healing Stream:

![image](https://user-images.githubusercontent.com/7716908/236116216-40b4343b-7499-4142-99ea-856c9b87f93b.png)


https://wowsims.github.io/wotlk/elemental_shaman/#eJzjkuRgsmD0YJzAyPiAaQLzBkamA4yMFxgZXzAyOvFwMEowKjBpMAYwRjAKMUhNYmtiZAvISaxMLeJgF2CXesLIxS/Q+JJJ4o2sEtvRQ0wfdjBxcQq8fcakxPwZyOQRaAbKPZJVYt4H5u16yCTRBeXxC/x7wSTxA6gPyAMJ8ApMecwkMUdIiQXIY+ASEHj4hEliiowSO0SegUtIYANQpF9GiRMiAjGlCWhDJ8SU22CBh0BTpsnABTgF7j1ngljJKbD9MZTJInDuMYjcvwvkrjVAc3/BXTkPaMALDpi607uYlHg5GA0YA1giWCsYOxgZFzF9ZeI6wMQwCigCQgak6qhi42AUYCpgTNLiUpHiArKZJZgUgDHDweQJlm8IcNBgDISoFXGwYJRi4mDsYlQ2NjU2MDAwNDUyNjI0NjY1NDYyMjYwBDJ0DQxMgdDA2PARowTHniNMAheeMkkcOMKk8Psek8avS0wGZ68yvWBk+cDIPYtRiEsAmBpmPWYS4oDYoOdwi5FhFhODUjczJ8T6MgdBiJSMg+SsmSBw0t4SInLBXjENDK7ZG91mUgiWYNWicQr60OhADWMaTh6hijm0AJCw3fvewRHC/2GfwBiEN292pGV7ZEqcsUcV/WCPru6E7YZuve9P7EPTjA02xn7CkB/ugPS8GUWyDgAny57Q

**Comment by lologarithm** [comment]
using your link i see 
![image](https://user-images.githubusercontent.com/577261/236694604-a3c5475e-2cb6-4558-8dd0-ae5516f4d46a.png)

**Comment by raethkcj** [comment]
Seems to be somewhat random, here's seed 1840242651:
![image](https://user-images.githubusercontent.com/7716908/236696020-27d144ab-50a0-4f5d-9c06-fc0e662221a6.png)

**Comment by raethkcj** [comment]
Oh, I see, it's going OOM, maybe not a real issue
