### ISSUE TITLE
Crash Report 1911883504

### ISSUE THREAD

**Issue by XWingMitch0** [wowsims/wotlk#3043]
Link:
https://wowsims.github.io/wotlk/raid/#eJztXH9wVNW933P27rK5BHLMoO+yz6TbrZWU1525u5udEWfey6LWwTfjTJ7YFjvzZoyIJa+Q+BLwaf8pRi2FvnlYqxZpJWhRQUVbayVAQoSgwAsJYEKQoJCwmx88UEJDqk1tfd/v95y7e3c3BFyXPzrdk7ube8659+7d5PP5/j5Xf3Mt04+W6n9xNTDnzVXLPG7BvP1MLxKHh7lxusTvfquN727ieoHoiHG/E3eLREs/N/pgDnpy4NAQN566lgbGYaBYPBfjxqcl/gJ5BB40TWwZ5MZjpX5toIk7oNsJH/DktX5tN3aLxJphbj+8WPTBJc7BJZqbuNzgoM9g7Gn4HDVQIPqG4KZeHMTdTXHYxVFNnBnE954hPGVLnBsdcK/wqZ0dXHfAxKqd3O/2cHNapfY8H+P629yRb1+qFZtf9IwfOt5gYf3rghkuHytj/+xwrIhGXfNmPs6K1jLnvzsc0bkrWOkLLBwOV3h1nQMw7zWYj61m3whEysMhMxQMh8KhkBk0zUg4GDLNsBkOmpFgMBAywxHoBUOnmOF5t5WLjQCBd1q5b90RXrb3PW62vceHmTbCpqxjjl7mWAf46wX86zctqa2913dnVc0PPC6hezuQBpsApS+W+t0b23hjI8JsC9JgH8CsULwMc/9davWaYsQBZw/1XgQ4u+EMPEkXW/u4sbrUzxD3LyHugQb7JO7PwfUKYF9ugPt1cLcfl9jHisRG4NeGmX63GigQjdZdaOJ/TuH7YB++v0OQ/xDu5GVv4miE/Pt93O/xaAB55wJnHvQ5admAvoEX6poHcOzVirnHuZrNBvhGgqFgBIBOGEZEwyscCJsR+oEWCgfgMITzRwNcrO/mxhPd3Le2m5et6ebmM0cScC646j5qPRVNjPUy7nMjuN91NzDP/OV1D1Q/ULUEiMS9cYT2y/GEhD+alPAtBN8LUsJTLyneoXc2RbzDAGxbB+3i/QziWohHYyTep8D8UZuEb9zP5WaT8PIq8qOa+6WEl6dZYr2Fdv9wWu1q4sNjlpyXEn60hE5pIbhPEQ0wtPZaQDw32Q0sL+Zz1LJB/I3L9bnzWBm/ivrRxuhNPpDmLnhNgVcBvDzwQgnvhBeHFwuuewbbtoo5YWpdFV7Tw8VXvNfAOyiLqHOecy1jbzPnPsbeZ+yr8rNGKuZ0HMB2tqIM9MSsgAmsAo1gBgPEonAIf+EFQWOA+oDJYDgYRFptOMjFrwe4sXGA+46+x8v+F7RET6aWGAUtUSC1xC2V80lJHEcm/TppK6GNUSB+HlO2SKF4YVgyqTnBpE9KEgZMkWgcJia51+/nsAGNTsYljaCH2uI5ZSU1Sw5t6+dkEYHJ00xM7OzLtJIa42lW0gnrdpTBpKykg0kOHQAqbvImTkGV8S58VBFaSUigBdqD7CeM5XmUk5YNj8bZV3Tdw6LsEOMjjHmvkoQC1PvYbCCPCZCfHUK8hwDeBHRAPJhEMAY4jwQDAdgDgwn1ihlG1A+BMvldDzdAqZAyWXskRZlYqH8L1Ifr1rra+mWE+PiVQnxz00URDwd+McQnnAEb+C2/AHFfKH42TEaSumfsbfJax63Znof+FWrZQb9KvxkE/vPsOqUymFIVqDLcNnWiwWt6lM1j/ynPHal4iH7

**Comment by zku** [comment]
Unfortunately we cannot reproduce this bug because the crash handler truncated the output. We have now updated the crash handler to include the relevant information for future crashes. Please open a new issue if you encounter something wrong in the raid sim.
