### ISSUE TITLE
Crash Report 1546324837

### ISSUE THREAD

**Issue by Machigatta** [wowsims/wotlk#3048]
https://wowsims.github.io/wotlk/raid/#eJztl11sFFUUx+fend2dnVJ62RSdbrbNMj7YNGkyO+Mm4oMdE33wrUpieBSxJE1qa6APxqdaYrTV+EVRbIwFw4NfFB9MWgoqSkkghVq7AqGbQHdbtqtoqakIVCOeO3d2K/gV65i4zvl373TOOXPv3N38zsw56js7iXqqVv0+2E0i97W1PNbS3rmpTaEsHJslahV76iuqfVOrh45+RheGqRph3+apHvgYTlex7RDL1RatkSzVel2riv1coNpVmAcWd1SyvhmqvRHVZbAklbHsLNX64npYxCU1yj4Az4txPSI8YpVuuEOPWCXjOLKwyqvxkiPCzs2524mwoRn3VGbjM/z4yQjf1/uw7lJpl2/CAgWleN3YCNVDCjFI8+q36GWqHqYS6h8pavzdGU9Kj9SriZiiEBbQAgmikPsdf1ez/YA4sW2bxGSIk15ym5GyTMNIpkzLTJpWKmmZpmUk4aTRMFJGyjSsZI5oyoejlE1coNrhUZr48RytX5qkxslTtEDkBRLuJ9IUkfoBO8QesfdCiD1i70Mh9oi9D4XYI/Y+VHlhH5Wwr0X2vVJ5sY/YI/aeCLFH7H0oxB6x96EQe8Tehyov7LGvRfa9U3mxj9gj9p4IsUfsfSjEHrH3oRB7xN6HKi/ssa9F9r1TebGP2CP2ngixR+x9KMQesfehEHvE3ocqL+yhr32hTu0PdRO1eWtHZ8vmztaOdiXIIrGzHP7TAPHXgN/eI/SYg9g+jtgxB6QzEHu+rmgNA1Y743rgjEPppAs/xHhYZUPTkBt1OuHk74dL++r0sAhKMDkN0ZfjYqkqdhYmz8PkXQeocOydo9ruGj00MEDhA7sY4LsYzjuIZ/kxP82PR+f4Trph+ROAe87Z1w6Avwd2ySeG2Rdwo11xvYrJWtCobA5sDDxBniUE0fdEK0H/XbJetWL1KlUoDAIjCCMMIwRDgRGAIcOIwFDXiXl32zGaoL2kwUwZhmEZhmk1WobZCLkBiWA6XiNppswkBJNJC1KF58SeNGVZyInX0jTxdJrWP5OmxqHrpZyIrNni6HTTMCFThCZC/MWAyYHJ4YH+n8nxJVRNFQ+2bOvs2LrJyQ5eN6V5dlwriLrpwBG3UNnOucw43P1UEHXTwTy3BoHJK2AtOjy/l6fayageWry5bsrwdKhkV2DuYI0uL3Izws5P02LFtVS4qVbaPytSo1QrDc5ScRu3bFp0aqDzTq3UP8Nz4NM5Xiv9qkzKOJeMTGOZ5K1Wkg4j9BZ1tSrqJDlBGUksV0WccCh/rEZON4AOWKesJHiSQDyYZsqBfB9URZ8D5ENQFV2b/MNmYA9/5t/bum1z6+Ntre0tSoAFYxlO9WVg7KKgmsN7QzcwnqNatlRnc6p31BXZ/O7GbkBlU/CwHawVz/yJGQfpUitQxX6AXOF9wKViH3AiV2JbOHJzpT5AFP9L+VIf8FKh1AcsHCwSvtwHCKS7c/zS+ay4VFcE3RuDyLcnWgnfr9CH1DsVEr1DrVDkNcJr2mAorsG4EXYNiRvENRaaYjENOodohXK9KOK+D6rtXnI7zw3eGlj8hQBvAd4yQOvgJEYjbyMM/jaweI68PUbZ7jGqHbpAExchR+YhR8Ynf5Mj+OhHrUj/6Uc/NMSrVKn49+cWC94lNUg6VaphrI09qt6qriW/Jx6QZZnCBwSHIP8H4gH4fjL/krIsBWU5GHC+sRtYVpE6/blAxDnp2mK7uV9t1/S/znW8ab3wTDStKxZrZoYmNmjBhn8Z2/oe24tluo6P/sU6Gzy5z0okftuPLtn3CPtq08PkF2dm+VU=

Active aura during reset: HealingStreamHot-23
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd8da0, 0x3e00260})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0x2924900, 0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:121 +0x1e
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0x28004c8, 0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:462 +0xa
github.com/wowsims/wotlk/sim/core.(*Unit).reset(0x2800000, 0x4cf4000, {0x368370, 0x4756400})
	/home/runner/work/wotlk/wotlk/sim/core/unit.go:433 +0x11
github.com/wowsims/wotlk/sim/core.(*Character).reset(0x2800000, 0x4cf4000, {0x368370, 0x4756400})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:456 +0x4
github.com/wowsims/wotlk/sim/core.(*Party).reset(0x18b4900, 0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:75 +0x10
github.com/wowsims/wotlk/sim/core.(*Raid).reset(0x2962000, 0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:419 +0x1b
github.com/wowsims/wotlk/sim/core.(*Environment).reset(0x5f58000, 0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:212 +0x6
github.com/wowsims/wotlk/sim/core.(*Simulation).reset(0x4cf4000)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:257 +0x29...

**Comment by lologarithm** [comment]
duplicate https://github.com/wowsims/wotlk/issues/3052
