### ISSUE TITLE
Crash Report -1804266233

### ISSUE THREAD

**Issue by Glippmeister** [wowsims/wotlk#3052]
Active aura during reset: HealingStreamHot-12
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd8da0, 0x5e45bc0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0x2352f00, 0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:121 +0x1e
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0x281e4c8, 0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:462 +0xa
github.com/wowsims/wotlk/sim/core.(*Unit).reset(0x281e000, 0x3d7db80, {0x368210, 0x4ef4960})
	/home/runner/work/wotlk/wotlk/sim/core/unit.go:433 +0x11
github.com/wowsims/wotlk/sim/core.(*Character).reset(0x281e000, 0x3d7db80, {0x368210, 0x4ef4960})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:456 +0x4
github.com/wowsims/wotlk/sim/core.(*Party).reset(0x18b46c0, 0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:75 +0x10
github.com/wowsims/wotlk/sim/core.(*Raid).reset(0x1874f00, 0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:419 +0x1b
github.com/wowsims/wotlk/sim/core.(*Environment).reset(0x196a0f0, 0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:212 +0x6
github.com/wowsims/wotlk/sim/core.(*Simulation).reset(0x3d7db80)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:257 +0x29...
	
	
https://wowsims.github.io/wotlk/raid/#eJztm3twVFWex3NO3/Tj0iFHinUuPcBme2fXjGWqbneTKpg/Jq1jzbpbO1ssTFmOf9lKDzAbEzY8apiqqeEhTxUUkQk4QERUZBQl4ZF3IAEMhBBDIGgQ6HRIJxKE8FIIDszv9zunH4mUU5ttq1y3D3RzH+eeSyqf3+9+f4+rn1vN9Dvj9IH0Rcz+6MzZcwJF+TPt6UJzHWF6pjjXy40L49zWrQ28uILrmjjWyXWnOBzmxgvj3ZaBcq7bxDLYe3UszD4Ds2/CbJh6E87oYm+IGyvHu1maniHOwsm1491aezlP00eJy13ceHms2wFz4ch6WDxThGDKJbj+pjxgE5fg+nVjdYd4P8LdlvX0P1gVxu++FvyO0P/mdoQbR8e5LS3luMhu2CvJdFsby/m5cpz0SYi77XbNzJhsecKyhd/g+j6elhr/qzHK/J9e8bu0I8yn52SxH9PuviK/K0vndit87PBxwIfDxwIfG3wYfNJd3LCsZNk5Zq5p5np8uV7T9Pi8Po/HB8Pj9Xk9ObmwY3pND5zyhZlhP9POxQv7ubGzm2f1HufZPce52X2c9zKtn9k2MMd9v6bRnlfOWAfjWdYNQGOxFeB/fGZ+4NlgQcDOhc1Vj/BfBPo+Axz3NPA+ImlbF+J2tJobIcAtTPBXVnKjyQ6z/6Lgh6l9BH9JLTeWKPhvwsnNY9xaH8LvEK91Ac57I4jrEVjtMlwGpoTW5BTvV3HjlM1tefcwLv98BTfujoONLztpwylKmzjdRNrjxRqc9Ucwpls4a3GYNjSxtBZm2bnJJmsp5JMyhoP8GjZPn6Hrdia4wbKYyQRzPaQoR9q1KOnKEjKUJejwGYmWkM1MyyRazP8H/8O0Mett/7/K9Sf5J7Mn2Ex5dJnfpQO6zLBksWy+kj1g5vpMn+nJ9eb4zAloQT4PfHvRdkw0IQ8d8ISZ095wgIvqA8BxNxiKrZ9ZNrC0DpaGpnEOngu2KQ1bZ80pLLJrQnftRMsoi1tGhCxjBTniEqDvNlhGNVnGUtj7chzM3qwsA6Yea0bL2BizDF28A+huGYPbDrEAvXw1efGtvdIs3opwudoaWO0qkl3fiTf8rCxKv3wWyKfANlf05s914x6cPNTJ3ZlgCBkTwRSe0H7LljOWsoikjOFYxACboN+PnPrZY2wyAy/cyNhHjPcz5nLdJ2f152WxB0fY70YH2M1KlpPjAx8/wQcgm6Y3x+sDoOEPcu314JMBUMfHA/BNVBv2jSe4uAgYrDvBs4pP8Ozik9xcfxIIt/YzLU74YnD+tkdnzCwoCBSR8ClDwrc3xAhvJ8IjNQhZa6n0/e0E2fJu5fvPnuLGrjFua0M5zR5M+AIg98Y43M4Ul8DxO+SsBuL85YjkvFpemSm+7ELOaSk0Fk28WIvfG6rjvF9qwZvfKuPG9XF6Ghy4W4EKh5z9Uym4kzOGA/e/TdcD9usWcd0yRh7qzcvSstkjhnLzFuXmuRI52pSH1BlrwgPBmiCBBh1/DLz9U0yKoh8B+bmmB6QR/AUlBMx7TVRFPnLxXrQDT1QQPQeC6Pn9QwRR+iAruAV+3jH12cLCX+cXFk0DO3C4atEOartkALCrgTeSHfylG+3gOjC9FQKAxlgAsDkTZh9Xnr4xKmY21VIAQNI8Q1yFebtBBTVKFdQGwtyCkGeKa2Gp/EHUNJIZ3IT7lowhWSSFTmkEv+vI+S+kECASwnvvgUfRpvGwsRKuWDEelv1ov4wVyCSsIPpTCig5YzgmUfQL/WeCvcQYqhIpYNJ+qgTMgof9/ymP/Mr/K7kxyT+DzWK/ZQsYPqdfZ/LoBL/LKmAFA3UNPgbA+4P89+Wg/weZA9GBF9UMbIMV4CNBPgG2tXGxoY0bxW08a3Ebz36ujZtL2oB9nsj+qDS9c6y+HAzA+nggf1pRIdBvda1i4Lrf6+VurRpp1cRXAL5DtB5EZskSdpxAwj+AA+SsyRJ2AdLk9F8Mw5WteKVNvNhNB+1iBywHFMIyH4AqsUiDkp59yWH8/pyi2udp+ytSOCuW43craH5Qd2Y6SpinUjwnZwyH5yd/oKPM5gafqPk1l4OE/WjzJXDJPzZJcntQpHg9xKSHXDL45hyTYlggMwc0OGruxm4uPgT9sL87FpxGffFm1NyPBvNnzgvOs1tEuusd9MSfgm+9CC7yYD3vIHDOrLUAfzU93AiDIqkl/pZcAH+Lmvtj5Ylhai0pkj6IH/80SsLZA6JjB2lum6iTxILvBhf8+ni3tVZeYRMLSYlgDAobC9DFtlTRhia2kzOuKaUcDSy2ajzpkKuUaQG5Njn9ifQUpEkZw4F0ihPFhstqR68L2vmfgDwfekgU0bnoPUEtoA81USjkgmbwKI/5dhMX7zdxo6KbZ/WBWrgIauESqoURg6LCNZgw+Y/gM0WFs2ZgtlB31TBg8Q3wb8inVMy3SSkc3C1jwjPE1OlGblxJjAnbpe7NEPsipJi1CPrMDPE6nG9wKuerdLOcK2Xy5vA9dHN/fMFonCj96r7KeK6kBQxmuws2XgmrEHF1ZSpE/JbG8ELEgP6zYvgVsB+pdAhLSA5aVbrEplTxSAwk/1te2583n/5d3uCHkPKb48l/9lLwCPoZBUUuxJXgtb0mCQs4jG47ahSvQSD5xxPc+Lz7GwPJRRhITp0BXrtoNtnEDnTbYBNGG3B5u563EpeljagjSsIq1aGJ4yGuDAJDSJhUTQ67oi6ePhxkDQ7xWehreZJqeZlTlMJlNc7o2hL/yp64ERzviiYMyQiOd6aM4Nse328jGKxdXkUjmBKcE5g2s4CyKQfRCI72xrIp1QnPhgNhmU0Zki88okxBMZ0ZfTbEDzRJe4gfWA1PHofckwc29QyyC/l8qIlfoonzXaS1Kbhs6YzmETPFu3CzZpl5xNgUdc35Y6n8SrLH9z6/MjTGXPZDvV9bxLQphYWzyTIWomRaWwWSqaKBbyIOyxvx+709+F0L7toumjplyGgXJ2Nbe9WWU3zZA1cfLeeXyYA6OknKa2JBFS7wksyb7CIxRL5/S4fkeSvd4GgllohQrfMU00kZw2G6lNv1NJeGMSX4Y3TAJihyk0qdmM/Ayif4ZA/EjSZShxgid2v2c/EqcPfe0ELn4LxeJcSS6b+cURQMUl2zDr3xLRVJAnany1GMfI51l2skHz4Nx8NJkA9h9IhfwPzmUW4rTL5G0mRxLJbMQBiNtWPd2mkpTc6hNKkljzsAl60YRwHlaTpwuwur+bEDNnEhrALLdytUYNlP5H7VSbFCiBsDGH+2QtjZa0cdE4oSOzJFbFLGcIit5PfrI3WI84XF0LI4JuaAXyZAT/xjDhbjcynLgXoCvWQu1R09GHACvFJMvHeAi5Zubuw9wLNuAbwDAG+zEhMJYeYuTEr/+9zZc+bnz31mPjnNfQjw+TjA0m9Wh5DdGsXuUZkKkXLCKU53UahJhzPRjRrn7OQ15YGuXkqGWC/LAwphea4qLBGOTb6lqjPqAAAbwksGIuoSTZz7hBJ5FGoeBXAvjIaNq+cVwQtrUz43ueM74XMHPev1a+hzH88PFGEvSbqrFJG9AZT1SWSrIlFkbeIg0NiJPg6e9jIxckUlRmrlUz1DLK0kYLUOmRi5KHHVaqW/rYv722twpmR8LOWXKe6oGorK6METvzSuC6QiWP8WZa3hFl9gbX0Tud8Pu6JpvJGpNF6SxrC6R/jj+kQ7GzVBH2HXVBjn9cOOXe0I3LGpnTTcYbFoz+UyGFybGPH9gzw32k/dITIjiDV01LY+Kp17yUPneCHmw+SgpH5bExclTdyoVjnBS0D9MZUTTKD+TaT+F4WBOTPsVsFc25H63jj1ksA7FPe9GUbqoznrV2pV3Hchjn4r6YwzobjO6FHcH5Y1laURlbbeDpAvkxcdpuXqsQkFfe0FqhKupvL5su4o8zbRVEW6AoJQqqavq0q55OSO4bC+nd8HLjlDT+R1JcsGb4ydfR6AMYd6PkhEAKq5tIUUe6L9HlvOc3GkjhtvnOdZG07y7Abg9MPjQzMUEIl9OE5/CRPYUwLz5wUKVMdfJfJ6uDqWp2iIdfw5RA8m624QXS/Xql7XaLvfdVn608WNTmrxI1gjYSmKj8le1yuq17WunJ8t52/0oHPuDcf6/sKxvj9Qx6q4KLs+VsZ6/DTxeh3e/2YZ9rrCxnm43SEnHL8SSnX6JXf8f+n0G5y5u4oF8EcD058NzKD2DzKIj6qHJO6+Igd+vDoxcRezifp44i7e6LfPKW2ipVraRGJFJ5KQsTukMtnHZMeHTbxVS83fmigljf3JqVjGXGayL1fhrM9D1AZlE+1VtAHPmFTrR9LH96f1YzD0XwD0I56c/V/B/PxZgfx8GWNuQfJXVEnyD9aTf46mrBfVJDZ/7zihYswjWPnsll1PsvM7+ihof1t2fjdIvb6zjEfNJlKJwGNT4duyZCMfORsT8tKrtsbrlu/Ux/r9Dr2Zykcne3zv89GDwS/FHpNfFk6fnh+cbdeE1bWXoN8dc/ey625nFUK/R7n7gVjX6xrU60t3S3evevR00X8o7u5fVBJoALl3Yg8USiBaIlPsUi89NDerPsG+Q1L8DJAJrHwr3hi1Y0v0RR+bCIGhtNhh483ztAGh6pZUY1Tyx3enMWpwiPkCFhefDD4dnBYMQpDJXX9GaHeGY9DWED7lPYhU1ykJ7SmCdmdEaZQapdvroxplVVe8VfsFmLWOHLdTLI5IYmuI2LWqT/u6fLvHJlZewNd0hvRnRzrj/vpup/LXNtEKGqV4rHTZE1M6PVljOJj+ZK7+8GOgR2SexL/Z/0hWQi3dod5G0xOUO/NsWI+jIm+Sj0ZbnssE0v/eRe8xZDO/5TFLMWP7mKWRsY9ZNM3Snzep+SiOi3nYg/UA4J0D6sQHAgUVuXyVzYe5R2kI9GIDmoBhL2nhYksLNyogkj0FPvwI+PD2e0WyV36od2CO/MlgfqBgWhEVFi3YiwVWEW8XvJaQetnTK3Pk1wa3C5bG2wWPxbKOfxql0owZokxlX65JFbMsEss67u6N5V86BmUdYQ8znQlVntW1qspTShKnrjKaIz+Gsr19T2LucURK2iRtDMdOHnlIH72QSfIP561gEv2GPNdoOzeecSemabLfBW3+IDWM5KIKwb4RfBkHRYnpRZWO4OeYRDtgT90k57i43MyNu8086zwQHgLCb579Wp/haYDb+Uiw6OlgwTMzggW/KwSpYnFVDeFbphYXE98Vqgb0GoWQu7uG8L2tQqUW+xJKmLsU3K0JcLfG4C6RPbHbKhLhfqdCwV0RUnDfCSu4L9IzYDudLYW7rMbeWIe41ClXTdGd5PF/l+4d6Lr/Ze7MguC8YFEQXLddCprqoZ3ed+jVg94qIKhnbzRlTtWiCpVxOdugSvPI9TrV5l3cE23zHlQnqoJrlsLyS2Q53yn+LIuaFlgE3XJpPG1eR4mWC6RnPq5SRaLVZVFHrWPafGKq2zt5Yzgw/2Y0/K4tBvV6mwy7vkW6gc19OV6q8VCfN8SO3lzq8/ZSS19OrtQbuSQ4PgHNvXGZxTjdxLMWtfHsOwDswq9nSz4AYPWfBwrmBGbPf7rwaSKW3k04GxpCbBe9Kd+0K/HdhMOl5IydCC25VKVBqtQrM334ykyHzJjfUBlzWbq8FuNW1TfllUc6VYLwTkKl50LsFUlNbAzh9wAdKdmT4jX5Y1i83g8MaMArR14nciJWQ2If8NLrvdiAalIN0ostqdiG6gFiY8jKt3uXWQRga7R1D0F2cMjYjAm+qYVz86cXFk57NlBAzB68h5d1iBufKhfpFIs6E8E9WaVUBHrbm/YYuxmi99Qglbw3sTafiRC7HR33IFgV5KXnBTlh6aD7nCkbKpQ3DBHKVLY81Znyv9/W+G7ybEmM+ZwgJ9Wfb94T6T9JezDNneZax/Qf6H/H7jXwhKZpHP7CgK90/AcGnoCfTsMfUdPS0jUt3UI/rzoRH1HmvnYi7W+dcPdwxx9+Uz3nlVm/93tP86ypRvqD3zLC2Sv8yVhmweEDf2OdqUm5z3CGLCLWXFZFxLSbeU+xvwL+gpBD

**Comment by zku** [comment]
I can reproduce the error with the provided raid composition.

* The error is related to the resto shaman's `HealingStreamHot` per stack trace.
* Removing the resto shaman from the raid makes the sim run correctly.

With the above observations, there is likely a bug in the resto shaman rotation or in the raid interaction with a resto shaman. Keeping the resto shaman in the raid but editing the rotation (via the settings) to remove the use of the healing stream totem also makes the sim run correctly.

**Comment by zku** [comment]
I suspect the issue is here: https://github.com/wowsims/wotlk/commit/b51aa543cbfd8a1c4e9b8b456825eb5a9d33b9d6. Since that change, the totem is being cast during the shaman's Reset() call, which would explain why the auras are applied to other characters (and thus active) during reset, hence the panic.
