### ISSUE TITLE
Faction filter for Gear. 

### ISSUE THREAD

**Issue by NillaWarbane** [wowsims/wotlk#3055]
**Is your feature request related to a problem? Please describe.**
No would just be a quality of life improvement 

**Describe the solution you'd like**
An option that allows you to filter Trial of the Grand Crusader by faction. could also be automatically applied when you select race

**Describe alternatives you've considered**
NA

**Additional context**
Na.

**Comment by lologarithm** [comment]
Already exists, go to the 'filters' in the item selection menu to choose your faction.
