### ISSUE TITLE
Hit from Socket Bonus not active

### ISSUE THREAD

**Issue by rwlumino** [wowsims/wotlk#3062]
**Describe the bug**
I was noticing a difference between the ingame hit value and the value in wowsims, and I think I have tracked it down to the +4 hit socket bonus from Seed of Budding Carnage not being included in the Sim. 

**To Reproduce**
1. [Import this set](https://wowsims.github.io/wotlk/feral_druid/#eJztU89rE0EUnvcySTeLpdMQZIxJXNdLLRRmdwnooezES3usehFBqKA9eSg9aU9RCPjjqoI52h7aQwN6kL1oJPEHOSTUglb0UpsQIj00IEIVBWd3+wdYmnryOzz4vve+eW9n5+mHNRR4CqZhFgoASwCrAF2AM8MaGChD9XaQSJBUN3oLYlPXLt+4OqdpDFJN0IfYuy7yrxkz9qyGy3XU4+xHB81I1UP9EGuo3EYmZAPsSQf5g7SylDeR7yiLqvctg2xFZYpZkzY9JIo2le1+2qRVnw6xby004zUPFVVRT7CNFvLtTKCFsir6pbSHaTNWDYU4W2rvjkFZpeXH5bYftzp+9UobeUNN8NPDZgN1ohJ3XqA5qG6DTtEL9Lr/0Y/xO+ovkfzHvpAQe3XMUw04PoUT+lENedSAERgnxMjL6GT2EiEf8/6zzKYou8LhLpwcy+UcW9iWYzu2LSwhco6loiMcS+Qsa8wWTk4xy94Err2pIFtUf/91BY3Sexx5u4aitoZdoD0YKAH5BKSExLwXiQejFGbkcDhUUh4pPfJRd0+Hyqp7fCbAB9f+jMZ5Hh094NfSuyn7cUyh/qov5xwEwrt9vi3zId9xp+FcsIdOgIg8Vtw662Ujsr99e26yPPFlPknl+sLsuL4OclKx8sRvd9GnC0QGbYv97vvvsLuHBSH/1nFxz5v7B03Boyw=)
2. Note the Melee Hit value is 258 (7.87%) (horde with no Heroic Presence active, however ingame value with the same items / gems is 262 (7.99%). 

**Expected behavior**
Hit value ingame and in sim should be the same, and it should take into count socket bonuses.

**Sim Links and Screenshots**
[Sim Link](https://wowsims.github.io/wotlk/feral_druid/#eJztU89rE0EUnvcySTeLpdMQZIxJXNdLLRRmdwnooezES3usehFBqKA9eSg9aU9RCPjjqoI52h7aQwN6kL1oJPEHOSTUglb0UpsQIj00IEIVBWd3+wdYmnryOzz4vve+eW9n5+mHNRR4CqZhFgoASwCrAF2AM8MaGChD9XaQSJBUN3oLYlPXLt+4OqdpDFJN0IfYuy7yrxkz9qyGy3XU4+xHB81I1UP9EGuo3EYmZAPsSQf5g7SylDeR7yiLqvctg2xFZYpZkzY9JIo2le1+2qRVnw6xby004zUPFVVRT7CNFvLtTKCFsir6pbSHaTNWDYU4W2rvjkFZpeXH5bYftzp+9UobeUNN8NPDZgN1ohJ3XqA5qG6DTtEL9Lr/0Y/xO+ovkfzHvpAQe3XMUw04PoUT+lENedSAERgnxMjL6GT2EiEf8/6zzKYou8LhLpwcy+UcW9iWYzu2LSwhco6loiMcS+Qsa8wWTk4xy94Err2pIFtUf/91BY3Sexx5u4aitoZdoD0YKAH5BKSExLwXiQejFGbkcDhUUh4pPfJRd0+Hyqp7fCbAB9f+jMZ5Hh094NfSuyn7cUyh/qov5xwEwrt9vi3zId9xp+FcsIdOgIg8Vtw662Ujsr99e26yPPFlPknl+sLsuL4OclKx8sRvd9GnC0QGbYv97vvvsLuHBSH/1nFxz5v7B03Boyw=
)

![image](https://user-images.githubusercontent.com/12403081/236953818-11313cd7-62e9-474b-b2e7-fc801f760bae.png)
vs ingame screenshot:

![image](https://user-images.githubusercontent.com/12403081/236953856-60c9f14e-b2e2-4537-8af4-dc5d8b52bc5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.139

**Comment by rwlumino** [comment]
My mistake, I had selected the wrong chest in WowSims by accident, which also had a hit difference of 4.

**Comment by where-fore** [comment]
If it's any easier, there's an addon available to let you import from game directly into the sim, to avoid small errors like this. In the sim go to Import -> Addon, and you can take the link to a curseforge page for the addon.
