### ISSUE TITLE
Survivalist Stamina bonus works wrong and Hunter vs Wild doesnt work properly because of it.

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#307]
**Describe the bug**
If u put points into Survivalist u get 2 % stamina per point while the max is 10%. You can see in the stat showcase on the left side that your Health increases indeed but not your stamina. The talent increases your stamina not your health. Because of that Hunter vs Wild doesnt count the bonus stamina from Survivalist.

**To Reproduce**
1. Put 1 point in Survivalist.
2. Check your Stamina.
3. Put 1 point in Hunter vs Wild 
4. Compare the Rap u get to your stamina.

**Expected behavior**
How it should work is that you get 10% more Stamina from Survivalist and Hunter vs Wild gives you 10% Rap and also you and your pet 10% Ap per point, based on the Stamina u have. 

**Sim Links and Screenshots**
0 Points in Survivalist : https://gyazo.com/6572a6f77f80cbc4014dfc89de369f63
5 Points in Survivalist : https://gyazo.com/5254b778959874eef5b12addb44cfb3d
0 Points in Hunter vs Wild : https://gyazo.com/c998f5876b52ba9f585328b4b165a910
1 Point in Hunter vs Wild : https://gyazo.com/d4198a0d1f89d6d17014bec5701831a4

**Desktop:**
 - Windows 11 64 bit
 - Chrome

**Comment by jimmyt857** [comment]
Nice catch, thanks! This was leftover behavior from the TBC sim which didn't get properly updated. Will have a fix out in a few minutes.
