### ISSUE TITLE
Killshot glyphe bugged or Survival APL wrong

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#310]
**Describe the bug**
Basically if i change one of my glyphs to killshot it doesnt effect the amount of killshot casted at all. This means that either glyphe is not working or the APL is super scuffed for survival.

**To Reproduce**
1. Sim without killshot
2. Check amount casted
3. Sim with kill
4. Check amount casted

**Expected behavior**
The amount of kill shots casted should go up and effect the dps.

**Sim Links and Screenshots**
Bad to see but this is with Kill shot glyphe : https://gyazo.com/00eb9d882b54614b5774086274d74851
This is without : https://gyazo.com/4698c6b16383384dced914fac926de59

**Desktop (please complete the following information):**
Windows 11
Chrome

**Question:**
Is it possible to see the APL somewhere for survival?

**Comment by jimmyt857** [comment]
Ah looks like I accidentally used the Aimed shot glyph instead of the kill shot glyph: https://github.com/wowsims/wotlk/blob/master/sim/hunter/kill_shot.go#L30

I'm out now but will fix later tonight.
