### ISSUE TITLE
Crash Report 1334020122

### ISSUE THREAD

**Issue by StephanDoktor** [wowsims/wotlk#3125]
Link:
https://wowsims.github.io/wotlk/shadow_priest/#eJzjUuZgFGA0YLJg9GDMYCxgbGBkfMAksoKRcQMj4wFGxguMjC8YGZ34ORgVmDQYHRgjgEqAkkJA9VLvWZsY2QJyEitTizhYBVilDjNy8QvcecEk8UZWie3oIabdz5i4WASanzJx8QhcfMQk8UhWiXnfDiYudoHWV0wSXbJA1TeAqrdIKrEBhUEyXAK3HzJJTBNSYmQAsm8C2eskQWx+ga+PmZQ4b4FVgRTyC9wC6uyUhevkF/j3mEniE1AAoghoyYcHTBINckC7fz0DMSB2swi82gsi9+8CKVkO1NMnx8XAxSnw7iETWIUSCwejAeMipq9MXAeYGKgKJByoa97gB0IGpOqo4gIlRwnGDK4CxiBxLl4OFgEmSYiUn4MUG0hSg7GLMcTA1MDYyMDY0AAL0MUmCJMzNjI1MDI2MDU0ApKGBkDS0BTEMjY1fMTI8IKR+wMj8yxGHi4mYKqA4kNMDLcYGWYxMShNYOYEO6UhzUEQ4igRB8lZM0HgpL0lROSCvWIaGFyzN3rAVMXqkZ+SWaQQLMGqRe30hAY+NDpQw5iGk0coMUdA92edIzXcgQ1AgjjrhYOjMRgwOwThzaeaMf2HvmrssRdZ5/6wSuSePUT0gz1M/vriAluu66/twdLrnttDIu6XPS7zhisgPZ9GkawDADRjm+I=

RNG Seed: 2238330339

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1916c0, 0x1868000})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/priest/shadow.(*ShadowPriest).chooseSpellIdeal(0x1bc97c0, 0x1bdd810)
	/home/runner/work/wotlk/wotlk/sim/priest/shadow/rotation.go:647 +0x3d4
github.com/wowsims/wotlk/sim/priest/shadow.(*ShadowPriest).chooseSpellAOE(0x1bc97c0, 0x1bdd810)
	/home/runner/work/wotlk/wotlk/sim/priest/shadow/rotation.go:99 +0x15
github.com/wowsims/wotlk/sim/priest/shadow.(*ShadowPriest).tryUseGCD(0x1bc97c0, 0x1bdd810)
	/home/runner/work/wotlk/wotlk/sim/priest/shadow...

**Comment by lime-green** [comment]
No longer looks like an issue
