### ISSUE TITLE
Item tooltips mouse hover area too large

### ISSUE THREAD

**Issue by Thsteal** [wowsims/wotlk#314]
**Describe the bug**
When you hover your mouse over an item it should show a tooltip, however if you hover your mouse nowhere near a item it still shows a tooltip.

**To Reproduce**
Go to website https://wowsims.github.io/wotlk/shadow_priest/
Hover mouse in the middle of the screen
Mouse should have item tooltip show up

**Expected behavior**
Mouse should only open a tooltip when hovered over an item and not when anywhere else on the screen

**Desktop (please complete the following information):**
Windows
Chrome

**Comment by lologarithm** [comment]
Ah, the area for a tooltip extends from the item text to the center between the gear columns. Maybe we can find some CSS to make the text area smaller (and not hoverable)

**Comment by lologarithm** [comment]
fixed in https://github.com/wowsims/wotlk/pull/339
