### ISSUE TITLE
(Warlock) 4piece set 

### ISSUE THREAD

**Issue by phreeze83** [wowsims/wotlk#3142]
**Describe the bug**
I have 3 pieces T7.5 (conquerors) and 1 piece T7.0 (valorous)  equipped and the set is not "yellowed" or recognized. Unsure if it's taken into calculation or not

http://localhost:3333/wotlk/warlock/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE78HIwKTAaMDowBjAWMKxgZhRik2tmaGNkCchIrU4s42AU4pE4zcvEL7HnBJPFGVont6CGmzzuYuFgE/j1l4uIR2AEUfiSrxLwPKMYusHcXk0SXLFD1TqDwD6BqoDBINa/Ai+tMEnOElFiAAgxA7utHTBJTZKBcIYGvj5kk+mWUOG/tYNoHRkAjLj1nklggBzeCR2A1UNE0GSVmoCIuToEJL5ggtnIKfHwIZbII3HkAIvfvAhkwEaj+F9ANQPUgLQxAieOPmZS4OBgNGC0YA1gjWBcxfWXiOsDEMAooAkIGpOqo4uBgFGCSYCpgzBIDxiyLBDANaoCihUmKDSgD5HcxBhsYGeAEugYGxkYGxsYGhobGpkYGRqZAFogBJAx1TU3BakwxtT1iFOCY284scPMpk8Tt00wK/y4xvWBk+cDIPYuR4RATQyc0KVg63GJkmMXEoNTNzAkWaEhzEIRIiThIzpoJAiftLSEiF+wV08Dgmr3RbSaFYAlWLRonqQ+NDtQwpuHkEaqYQwsACdu97x0cIfwf9gmMQXgz6163wxf+nr5oX1y3a6uN3EN7iOgHe5h8wA4jkXvqh+xnmmv43Zz5wL4vOOPn19LH9rjMG66A9MwaRbIOAAJEo98=

Chrome Version 114.0.5735.90 (Official Build) (64-bit)
on win10pro 22h2

**Comment by Tharre** [comment]
This is a visual bug with wowhead tooltips, there's nothing we can do about it, see also #2431.
