### ISSUE TITLE
Raging Deathbringer

### ISSUE THREAD

**Issue by ToilettHD** [wowsims/wotlk#3144]
**Describe the bug**
Sim isnt accounting for the proc of the weapon for enhance

**To Reproduce**
equip deathbringer and sim xD

**Expected behavior**
proc the damage

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 0.1.32

**Comment by jimmyt857** [comment]
Duplicate of #3252
