### ISSUE TITLE
Export provides no info about my glyphs (ruRU locale)

### ISSUE THREAD

**Issue by RENgOLD** [wowsims/wotlk#3148]
Export provides no info about my glyphs:
![image](https://github.com/wowsims/wotlk/assets/1100128/b47deba6-9c49-4600-af32-29ed6fb3635f)
ruRU locale

**Comment by zku** [comment]
The new version of the addon should fix this issue. Could you give that a shot by updating from 2.3 to this one: https://www.curseforge.com/wow/addons/wowsimsexporter/files/4559245? (Or just update the AddOn via CurseForge client etc.)

**Comment by RENgOLD** [comment]
I'm sorry, my CurseForge app didn't detect Wosim WowSims Exporter for some reason. Latest version works fine, thanks.
