### ISSUE TITLE
Sim treats Vanish Cooldown as 3 Minutes, even when Elusiveness talent is taken

### ISSUE THREAD

**Issue by yeldnil0** [wowsims/wotlk#3150]
I decided to test some potential talent changes for different fights to see potential dps loss, and I noticed that Vanish was still being used every 3 minutes instead of every 2 minutes, despite having the lowered cooldown from the Elusiveness talent. The only real changes to regular sims is that I was using the normal 51 talent points in Assassination and the first 8 points in Combat, but having 12 points in Subtlety to make use of Elusiveness. Ideally this helps make use of the Orc Racial Ability, which has a 2 minute cooldown, to line these up for a greater benefit.

Upon further inspection of the Timeline feature, it seems that the Hyperspeed Accelerators Glove enchantment from Engineering is only getting 2 uses in 4 minutes, despite having a 1 minute cooldown.

I cannot tell if the simulations are truly taking this into account or if the issue lies strictly in the Timeline feature, but it seems that I am getting a nearly 0 dps change in a 3 minute sim when using 2/2 Elusive and 0/2 Elusive and not putting the point back into anything else. This should result in more damage because of an increased number of uses.

A 3 minute Sim used the Hyperspeed Accelerators 3 times, but a 4 minute Sim used them only 2 times. This may be caused the AI trying to "save" the Hyperspeed Accelerators for the next Vanish use, even though it will be off of cooldown before that point twice over. 
3 Minute Simulation:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCDVBtbEyNbQE5iZWoRB7sAm9R7Ri5+gdc/mCReyiqxbTvMtGknExenwMlPTErM24BMHoG3QLkHsjDers9MElNlIDx+gZdAuR9AfUBNIH0CAp8+MUm0yimxQwQYuHgFXgGVTJFRYpk3H8gVEngCVNAvo8R5ZycTUASIgGJ7gGLvZZU4r/0HaboDNvkqUGyajBLbnZ1QF10GuQjCXPEEymQRePEJRK58AnLaDqCWs0CH3gE79CkKbzHQ2TNkwDwlLmBwsQawRLAksCxi+srEdYCJYRRQBIQMSNVRxcLBKMEUpcMlLsCkwARMrgZMFiwOLB6sCYzARAxMrFKCAkwSjAoiBv9hgLGLUcvAwNTYwNjQwMTY1MgQyDEyMDQwNgYKmBrqArkGBsa6pgZGQFGjR4w8HCeeMglcPs8kcfAp0wtGlg+M7LMYGQ4xMdxiZJjFxKDUzcwJdkpDmoMgxFEiDpKzZoLASXtLiMgFe8U0MLhmb3SbSSFYglWLxqlFo9OBGsY0nDxCwJxgqthDDoCE7d73Do4Q/g/7BMYgcD605bq+uMD2k/3hrxox/Yf+2hNrYrXIOveHVVvs3wTukGt9fRGHvg/2EPO/2cu3vgaq/GoP0iWy7rs9iHR/+MoeaCnQ5vdE2zvYgJAB2GOt7A6QdMzsQEhHFDTnfiDazwAe2srI
4 Minute Simulation:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCDVBtbEyNbQE5iZWoRB7sAm9R7Ri5+gdc/mCReyiqxbTvMtGknExenwMlPTErM24BMHoG3QLkHsjDers9MElNlIDx+gZdAuR9AfUBNIH0CAp8+MUm0yimxQwQYuHgFXgGVTJFRYpk3H8gVEngCVNAvo8R5ZycTUASIgGJ7gGLvZZU4r/0HaboDNvkqUGyajBLbnZ1QF10GuQjCXPEEymQRePEJRK58AnLaDqCWs0CH3gE79CkKbzHQ2TNkwDwlLmBwsQawRLAksCxi+srEdYCJYRRQBIQMSNVRxcLBKMEUpcMlLsCkwARMrgZMFiwOLB6sCYzARAxMrFKCAkwSjAoiBv9hgLGLUcvAwNTYwNjQwMTY1MgQyDEyMDQwNgYKmBrqArkGBsa6pgZGQFGjR4w8HCeeMglcPs8kcfAp0wtGlg+M7LMYGQ4xMdxiZJjFxKDUzcwJcUuegyCEIeIgOWsmCJy0t4SIXLBXTAODa/ZGt5kUgiVYtWicWjQ6HahhTMPJIwTMCaaKPeQASNjufe/gCOH/sE9gDALnQ1uu64sLbD/ZH/6qEdN/6K89sSZWi6xzf1i1xf5N4A651tcXcej7YA8x/5u9fOtroMqv9iBdIuu+24NI94ev7IGWAm1+T7S9gw0IGYA91sruAEnHzA6EdERBc+4Hov0MAKCsylA=

**Comment by catszeid** [comment]
You are correct that the cooldown for Overkill is not accounting for the Elusiveness talent. Overkill was missed when the talent was implemented. Hyperspeed Accelerators do have the correct cooldown of 60 seconds. The reduced usage may be tied to rotation code, but more investigation would be required.
