### ISSUE TITLE
Hunter tier9 2piece Bug

### ISSUE THREAD

**Issue by Enthraxx** [wowsims/wotlk#3151]
We've done some testing in regards to tier9's  2Set Bonus. It would appear there are couple of bugs present in the sim.
The sim is not applying the following correctly to Serpent Sting:
Crit damage Multipliers:
- Mortal shots (marksman talent)

Crit % Multipliers:
- Lethal Shots (marksman talent)
- Master Tactician (survival talent)

Serpent sting crits are also able to proc Expose Weakness (survival talent)

**Comment by jimmyt857** [comment]
Fixed this a few days ago. Thanks for reporting!
