### ISSUE TITLE
Demonic Pact does not update stat value for Elemental Shamans

### ISSUE THREAD

**Issue by Liimpo** [wowsims/wotlk#3157]
**Describe the bug**
Demonic Pact under Raid buffs does not affect Elemental Shamans spell dmg stat

**To Reproduce**
1. Click on Raid Buffs -> Demonic Pact -> Choose any number
2. Look under stats 
3. See that the value at *spell dmg* does not update

**Expected behavior**
When I've been doing some demonic pact research all other classes have had their spell dmg stat updated reactively when one ups the counter after choosing Demonic Pact as a raid buff.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Firefox]
 - Version [113]

**Comment by lime-green** [comment]
@Liimpo I recommend doing: Click cogwheel > "Restore defaults" when you see strange issues like this. Spell Damage does update when changing DP for ele sham
