### ISSUE TITLE
Crash Report -975295738

### ISSUE THREAD

**Issue by VernonWB** [wowsims/wotlk#3171]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjUuBgEmAyYLJg9GCMYCxgamBknMDIuIGR6QAj4wVGxheMjE6iHIwKTBqMBowWjA6MASBVjCsYGYWAWqRWsTUxsgXkJFamFnGwCHBI3WPk4hfY84JJ4o2sEtvRQ0y3djBxcQq8fcakxPwZyOQR2AGU+yerxLwPzPv4kkmiC8gDKeMX2AmU+wHUB5QDKeYVeHGdSWKOkBILUICBS0Dg7nMmiXWSSuxALliEX+DrYyYlzltg7j6wEbuBRiyQU2K7BTGCX+DfYyaJT7JggX1gt3x8yASxnVNgwgsmiNUsArMeg8g/D0GOWga05pcsxMEsAtcfgpS+ewjxgZIIBzgcAlgiWBOYKhiBodXByLiI6SsT1wEmhlFAERAyIFVHFQcHowCTBFMBY5YEFx+QzSIBS6pMUmwQfhdjsJGxqYGBgZGBMZAwNjU0MDIFCRgbGxqaGuoa4Aa6pqZgGqgFHTxiFOG4+ZRJ4PJTJom57cwK/y4xafy9xPSCke0DI/csRoZDTAyd0ATh4nCLkWEWE4PSVGZOsEBDmoMgRMrOQXLWTBA4aW8JEblgr5gGBtfsjZ4yFbzpZ6pic88vys3PVgiWYNOicSLT6HSghjENJ48QMCcYn7zDjtlpjtRwBzYACeewxw5QG37YB+HNvMsattlI+12wP8n6Jo/n3AN7iOgHe5j89+0Wp2quLbX/reizOMf2kf2KoIYtW72e2eMyb7gC0jNvFMk6AD5UuIA=

RNG Seed: 3956865004

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 21 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x103700, 0x14aa280})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x20c0e70, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x20c0e70, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x20c0e70, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go...

**Comment by Tharre** [comment]
Not a warlock issue, seems like the "ToGC 25/Gormok" NPC is casting something invalid. Same issue as in #3174 and #3175.

**Comment by psiven** [comment]
Should be fixed by #3191
