### ISSUE TITLE
Crash Report 390474003

### ISSUE THREAD

**Issue by KeslerQQ** [wowsims/wotlk#3175]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE1EQ3pku281q6DMEWUNS4p5CIfCStaIHeauXeqwtSBEvHiyCPw09abwUsaCCFKGVNuIPVqG9iCfJwUNoRQz4k0PSWg/SmGoTKhiEYhD/ZncTvFjbYvXkt8tj5s18M9/bnacZKjLkeAwSMAAwAXAfIAOQAygD1ABziPtYGDlY0EM5F5wcnxS4rJwDpfPEkTNH+9VmpgXmQGtht0qoV0KG8mAaK2nUPOzlIhpND8nczO6WUZ8PNbzhBdRHgq7Xwm5SrEa8G1mkV/OyzDvUB1sNmcKSprFJqjscNECi3Dkq6aEsCtlkH3s+j/qHkOGpOBszTsFPRLgaNJR6koe9LtWFyGyqaK+TC/a69MIWc4XaTwQa0vKLPz2ZPS6i4VWRe3dBj3zaPv9tXEYtg9J//BF8fL2MpKyCjp9hp7aVhpYGcj90QhrgiT2uWAUIBLe4mVWhQxjaNqnfGwAOlyAaNeOc7zDbOSEejZucm/SQa8Zj7RTiMbJjZsykzdgb0NXreWSpPM1SHsOjeYyMFpCPFbAMchWaUyBNofQKpBRKxkiTx+19yqqL8FvbUmM2smK3u5MT23sdzIj4W0y8H8Kk0tHXf7LveLhbV9r+8kxFLlobUWYg+2iVOt2/i1vpa717N0LHr+B+54Mlq96hJrqcuzq9HDk8NOWxZscTe7TZklhrPff/VYTLL6zAq4p06+DSgfQ30eUYZeHyvoo7drvxsvDf6ygm/R9X7HvWSTi/Zl3/Gj7+7KkN1XJP9GVVpYfWfbt/AKnZ1q0=

RNG Seed: 854433475

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x103720, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x20acdc0, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x20acdc0, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x20acdc0, 0x0)
...

**Comment by psiven** [comment]
Should be fixed by #3191
