### ISSUE TITLE
Crash Report 574228833

### ISSUE THREAD

**Issue by takurainc** [wowsims/wotlk#3178]
Link:
https://wowsims.github.io/wotlk/retribution_paladin/#eJztVE9IFGEUn/d2mJ0ZNL+WPYyisg1BSxTM7iDYQb7Ji9JpWyEkOughO1S4eLLtIqHQn8N2aIMMyuqil+gUe7DwTwQL7iZLVHgoN5U2DBJR8tChN/OtG4ZUkh2CfvO94Xvv937vezPzfaPbKobBwmZohxh2QhcksB8GAK4DzOMbeRTgEWAGYAJglkKAJYDWAyowMCDkSqEZHFcMnZBwVSMAnghIFJDqniuXQImd675wuo9Ecl0R9Bo2soDGxwZTeTyN+RzqGsstoOkbzyBxT4pozBNHnhuoYmlKTtcLOsDukbfRYGqCdmPV7N0iGkONpkyepDM2SCk36k2/4CWqmSqhqd3JohhUJT+PxuctVWrYXapys76ysMZGF8tNaeztZn8yG1t078svXMkMrZT73qtExFIezWoVreqY3AX9cBngPq6jPoHSf/wRAtZOFck9KhhI+zEB3pY+dkbvVtd8bM1XKxJKPCSHodXQUQUyH5lChmR+Mjl+qMxsRuXy3L9dvB3c41OHhu8q7Lea6IoctppoRO2o1RSJWrZtR2wrGrHtKE3syHsw1GuTyAYn0SiOV4VKBQx/KKC1VKBDJq+AfxikKZTmQBpGyUz7NK/pgR5nr2g/6NQO33KR5UdEZJbv6/HwikeXMPEphUmlrbfvfO/ZUIehHPzLmzB8xdmNMgPZZ7+o0/Ez3snc7jm6G31sB/GeTyw45RU2eNw73C366weJFtkJPmwrJoOrfDPf9jBd8S96CS+5+G5jXOjmuIgP8kzj0PLxzFO+ddWVip+aWg+fSq1yT6Z/4XFPUOK5GRdff9D9OwhY4kkanN9VnNzx7+AbQM7aTg==

RNG Seed: 519286779

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1037a0, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x1b8d290, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x1b8d290, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims...

**Comment by psiven** [comment]
Should be fixed by #3191
