### ISSUE TITLE
Crash Report -1965116965

### ISSUE THREAD

**Issue by iinduc** [wowsims/wotlk#3181]
Link:
https://wowsims.github.io/wotlk/mage/#eJztU01oE0EU3vcS1s200DEEWUNS6pwWRZnNErAHmbWXeqwtiIgXEXNRaejNnGpB2vSSiwpGD6IgiiIqqItCKVEPPRTaHlQClvy0WrCUigRCFersT25SCbbgwe8wO/P9vHksb0hCw8NwDCq4AfcBngBOA8wBVABXAPqIBjoYYMNJiCKH+Jg6BurAhTOXzo1oSEPxeSBd9OkK6qtJpr4r4ZSDJELH68hC7raTvpBaLclCrz8jIbT8BfXJJANFpp5JpSlTZcdLSbGC+q2oK1L6SRqvJtiuKU907Q1ZM+J7XXsXfS7zt7uZGhCd9GEd9esJFpImEqY/ltxOvlWDTsK0WHfXn1XXek+W30i2lPlXrnUtsLKIBhwGwhMAd7CBZBqV//grRHm7iZyqAcUs9B0iezS4DMUbLmZEHiwPb0Q8pqF+lnVomy2A8Qgn4UDK4pynuWWa8msdlHt54NyUvAyaPG2ZKUmYVtqsga59n0W6OYv6g2XsWVpAo7KAvLkoZz+8Dh1FUEqo5IMB6LXLoBRRYddCEY8Yzdi7fSlm72212Oszc2JfxsN7kVrG7GoBc2r/8MjF4fM9Q7q6f4eHysjb21FmdObtH+oMbaXbzs3M0e3o43fw//OJuh3c0BSDWz5Wp/vK1+POoqjmYo/7q2Xhs+uCfLibPUJeikHP8FEUSg3jdKEmXFcutiZ2qv9/Fe0/1lNtJ34B7VW8Cw==

RNG Seed: 950168375

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 44 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1037a0, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x210f810, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x210f810, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x210f810, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:156 ...

**Comment by psiven** [comment]
Should be fixed by #3191 although mage sim currently having an unrelated issue
