### ISSUE TITLE
Crash Report -301026136

### ISSUE THREAD

**Issue by Coldensjo** [wowsims/wotlk#3182]
Link:
https://wowsims.github.io/wotlk/warlock/#eJzjUuRgEmAyYLJg9GCMYCxgamBkfMB0g2UDI9MBRsYLjIwvGBmd+DkYFZgMGB1AChhXMDIKMUi1sjUxsgXkJFamFnGwC3BIPWbk4hdY+5VJ4o2sEtvRQ0xHdzJxcQq8+cSkxHwbyOQR2AiUeyQL4+3/zCTRBeRtBPKEBJ59YpL4waHECdQElAaJ8Qr8BYrNEVJiAfIYgNytQO1TZKBcfoHdQINByjdClPMLbAbKL5BTYtsINgIocA+of5oM0C0QFZwCjZ+hbuEU2P4YyAS5kEXg3GMQOesxyFH7gFp+QR3FKbDgO1z9u4cQppIQB6MBowVjAEsEawUjMKQ6GBkXMX1l4jrAxDAKKAJCBqTqqOLgYBRgkmAqYMyS4OIDslkkgKlUAxRBTFJsEH4Xo7qRsamBgYGRgTGQMDY1NDAyBQkYGxsamhrq6pqCJA0MTA0fMUpwzG1nFrj5lEni8lMmhabLTBr/LjEZNF5mesHI8oGRexYjwyEmhk5oRFs63GJkmMXEoDSVmRMscCDJQRAipeIgOWsmCJy0t4SIXLBXTAODa/ZGT5kK3vQzVbG55xfl5mcrBEuwadE48Wh0OlDDmIaTRwiYE4xP3mHH7DRHargDG4CEc9hjB6gNP+yDsGbKapF17g+rWuy5ri8usOU6bu/xsAokYg+R/WAPU3f4q0ZM/6G39t9A1NcH9m8Cd8i1vn5pj27ecAekZ8ooknUAAMoutJY=

RNG Seed: 571162898

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 27 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1037a0, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x1908f20, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x1908f20, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x1908f20, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:156 ...

**Comment by psiven** [comment]
Should be fixed by #3191
