### ISSUE TITLE
Crash Report -2133490982

### ISSUE THREAD

**Issue by Francoporto** [wowsims/wotlk#3183]
Link:
https://wowsims.github.io/wotlk/hunter/#eJztVE1oE1EQ3plNNpuH0Gepsg1pm+7FIBResgSMUHath+ZYLYh4qgdzUWnoRc2pFAvqQT1Eiemh4g/04t9FIhgM6sGIYqnQVkVsTVNSGmi0Vnp0ko2I+EcwPenHzuP9fN/M7DDvMY+KHAXugD4cgBieArwNOAlQBOjZogIHH/rBguNwHmACIInYTGTPLWUElL4jB08cGlIVjp4ssCb+oIjaUpuu3H2E4zlkDv4uIbNN/NM8anNtupxJI3PxO4uoXfASO0PsdWITdZZOGD+bR220XQeJcX6S5gmv7iINfRJz87E82i6aeIJcrNjKUtVn4T5qF71Emliokdz841Jt6uDLi5Xx7auK9sYCaquktR0zidQjtJX06kxFAVQHx37HFVxDlkXpP/4KzaJeRVyllkMNY7DzGNsdAT+qsLl6Yo1bPT6GqpPMReYmU8kYmUyGZBBIXargnhk2qnhpegT1d4dnK41AfSxH5CRAFuQnALMAnXbUshl+/qyCkumHM7AtJIJdQoQMEQoYgaAhRMAIGoYwKkva6woJghF8D5p6+QXy6wXUrhXQNzOF/qdTKKansAiOMrhSID1E6TVIKZT0Vae7Gmw4atl/JLVYrXa+OTNs70yandEqps1gAWOlcxhXegeHjg4e9vVryvYN7kj/aasRboZzj//gp/9351Z6LLqrEXn8DHad9+WtWoR1M/gGqbbOf6O2Gwq7tpmVb7UdgL3fvaP2pXRa9mrOtLv/g9mgBKyvcbvZzNVY92ezY3R5T7p9rU7/5Ubl0zD8+I5G5uMtN3tbrV8pDtT98n4BSuy8Bg==

RNG Seed: 3028160555

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1037a0, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x2259290, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x2259290, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim...

**Comment by psiven** [comment]
Should be fixed by #3191
