### ISSUE TITLE
Crash Report 2052179279

### ISSUE THREAD

**Issue by Rimlfrost** [wowsims/wotlk#3187]
Link:
https://wowsims.github.io/wotlk/retribution_paladin/#eJztVF1IVEEU3nPmtnt3KnZa9uEqrmz3IS5RcHcvgj3I3HpReghTCAkJfMiCChefansRU8gf2B76NYioh8ogIyq2l/CnFylNJFYxBDWsjYJENA0CG2d2pSIqyR6CvjtnZs535jsz997DUFsHC4qhDMqxCg5DHI9DA8BFgAkM3QS4C5gC6AYYEgxABmCXoQMDAyJS50IVxOEqgFgbxGLIn/Q2grf8aM2Jg/X6OqblvwQaYANniPE2bHof9mHXI6R+9qCTmGRQTDew0SQxJsIm6ZLeeBsxFrJegD0VukWhE156CelGdr+TGM2FpiYID2WssZ0YZwtMn8gkmQBraCemX7kqxaBI8UGlUMQ9keJ8wQrhZx/bxFmey+lUC1Fba6yrhYj+huiDbOQUMQbCpv9KP6pGPSJ2oZWYPh1tOA1wDeeRdqPnP/4IQXu1isT6XDWKqt19iNboc4TNkTwVzfCIZomKpaiDMBTmFUaEacJ8FduyLGQjWnb0fcVhji+TtZ6PBmmFLXaReKJ2bLtdJFrMidlFUdt2HCfq2LGo48TExIlOgaGPp5E19aCR7MFIZhitN8NoTw9jBrQZ8HWARRnV9PZPENTVoQ+4knl9m+SYPS4VJdeLnjHwdKDHPEf8kncT7ia1osDN67i0jH6+QzFDfHOtRJrHpjH+PokJb2ld/bG6I5FKw7v1L9eq1eKuRZqG/ie/yFP5s7ibuly7cy3O8SOo77zvlZvdYZFXyDughI5cj5dobuhO6WQiNMtz6x2JvhX/pFzwgqv/dosr3RhXfBNPFTa/25t6zL/ddYZXJ3vnreolLofkLJcyusArpCDDB54t4/N3un8HQVu9Sdj9XcX+Vd8aXwDVD9bO

RNG Seed: 3871959026

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x1037a0, 0x14aa2e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x2161600, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x21
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x2161600, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com...

**Comment by psiven** [comment]
Should be fixed by #3191
