### ISSUE TITLE
Balance Druid - Improved Insect Swarm incorrectly applied

### ISSUE THREAD

**Issue by Entex** [wowsims/wotlk#3189]
**Describe the bug**
When using manual rotation and Insect Swarm Usage = Unused the Improved Insect Swarm talent affects the DPS simulated.

**To Reproduce**
Set rotation to manual & insect swarm usage to unused. Check difference between with and without improved insect swarm.

**Expected behavior**
Improved Insect Swarm benefits should only be applied on targets affected by insect swarm.

**Sim Links and Screenshots**
With Improved Insect Swarm: 
https://wowsims.github.io/wotlk/balance_druid/#eJztU0FoE0EU3f+zxtmputNFZQ2JxEVoEAqzswT0UHb11GO0lyIe9GBPPQRveoqFYtMe9CCCwZNevCjNRfQgKalFe1BKqZYaCFIPVltoSRsM9aAz2dSDRaXaXsR3GOa9//6fz8wfepQgQ47HoRt6IYs5gBsA73AtMgo4BjAFsABwqp1AEjkEkFEuuA9gabGh6ABEM/0XLl+8RAiD2AxQkz1soL2UcKITZaw8QWqwpRo6EbXdw4oyNp9wInNNVlpFe1iyomQmG5WxhsyTTAl72WIN7TuWo8tUTdIHMn4z7uhFRU02K6saE02vslvss7RfSzhG8btmsqrUbsVlL6FgsKurrV4MVv3Q2urs1Xu11mtId7MvMmU9IenLmhIfraHTRoBDRu/VhwDuYh3pGGr/8Vew+FYzrhACDG3MgjhATTWzKTmP3WoeX0AMqTYMHWmXC+F5rkjLxeOecD2Ppz3ucs/t7BQ8zbnHuZgHm8yUkFVKaM+VMLlexdT4NPLn07gA+gq0FSBOY3QfyR9Mft0AWCRsZH9QRi3fmgARvAWtgJozEjGaQq4vaN/wHSrcVpj0T4TKlH+kr4k3vqhgssfedWyHJymVD7ajTG7y2W/q9GzLOX+C8G6fLgcnQ97wz8OZX/7RwcXTjw8PVvzxeurc9fJrP1RX/B99XXT2Xrbrkx++4sdN8X8dW/+jZ1sZm+/yZ/gGRiGu5g==

Without Improved Insect Swarm:
https://wowsims.github.io/wotlk/balance_druid/#eJztUzFoFEEU3f9vPWcn6k4WlfW4k3MRcgiB2VkOtAi7WqU8TRPEQgtTpTjstDoDwVxSaCGCh5U2NkquES3kwsWgKZQQoiEeHBILowkkXHJ4xEJnbi8WBpVo0oiv2Jn3/vt/PzN/6FGCDDkeh27ohSzmAG4AvMO1yCjgGMAUwALAqXYCSeQQQEa54D6ApcWGogMQzfRfuHzxEiEMYjNATfawgfZSwolOlLHyBKnBlmroRNR2DyvK2HzCicw1WWkV7WHJipKZbFTGGjJPMiXsZYs1tO9Yji5TNUkfyPjNuKMXFTXZrKxqTDS9ym6xz9J+LeEYxe+ayapSuxWXvYSCwa6utnoxWPVDa6uzV+/Vt15Dupt9kSnrCUlf1pT4aA2dNgIcMnqvPgRwF+tIx1D7j7+CxbeacYUQYGhjFsQBaqqZTcl57Fbz+AJiSLVh6Ei7XAjPc0Xa8zjnnnDlmva4yz23s1PwtNQ4F/Ngk5kSskoJ7bkSJtermBqfRv58GhdAX4G2AsRpjO4j+YPJrxsAi4SN7A/KqOVbEyCCt6AVUHNGIkZTyPUF7Ru+Q4XbCpP+iVCZ8o/0NfHGFxVM9ti7ju3wJKXywXaUyU0++02dnm35z58gPNuny8HJkDf883Dml290cPH048ODFX+8njp3vfzaD9UV/0dfF529l+365Ie3+HFT/F/H1t/o2VbG5rP8Gb4BN4yu4g==

**Additional context**
All Hail The Owl God.

**Comment by zku** [comment]
https://www.wowhead.com/wotlk/spell=57851/improved-insect-swarm

```
Increases your damage done by your Wrath spell to targets afflicted by your Insect Swarm by 3%, and increases the critical strike chance of your Starfire spell by 3% on targets afflicted by your Moonfire spell.
```

Specifically this part here: **increases the critical strike chance of your Starfire spell by 3% on targets afflicted by your Moonfire spell** could explain why it increases the DPS. If you look at the results pane, you can see that the sim with the talent has a slightly higher crit chance on Starfire.

Do you think this could explain the difference, or do you still suspect a bug?

**Comment by Entex** [comment]
Prob correct then
