### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by swolltitan** [wowsims/wotlk#3197]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=54801/icebound-cloak
https://www.wowhead.com/wotlk/item=54802/the-frost-lords-war-cloak
https://www.wowhead.com/wotlk/item=54803/the-frost-lords-battle-shroud
https://www.wowhead.com/wotlk/item=54804/shroud-of-winters-chill
https://www.wowhead.com/wotlk/item=54805/cloak-of-the-frigid-winds
https://www.wowhead.com/wotlk/item=54806/frostscythe-of-lord-ahune

**Comment by rosenrusinov** [comment]
Items are listed under Phase 5 (Due to Wowhead filtering them in that phase)

**Comment by where-fore** [comment]
We have the power to change this! All of the above items have been edited on Wowhead and changes should go live soon enough - thanks to Simonize.
