### ISSUE TITLE
Crash Report -1384740065

### ISSUE THREAD

**Issue by Rerox-WoW** [wowsims/wotlk#3203]
Link:
http://localhost:3333/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1Gq2Jka2gJzEytQiDmYBNqn7jFz8AiufM0m8lFVi23aYadNOJi5OgZ/PmJSYQUwegYsPmSQeyCox3wXy2AVWAHlTZYBaVr9gkvgB1AJUBJLhFVj9hEmiVU6JBchjAHLXAOWnyCixbAJxhQT6gdx+GSXOefOZIAgo9uAxk8R7WSVOoA6gqmv/mYDG/gGKTZMBGwtxyYTHUJdwCjx4DmWyCKx8AiKvPQc5cA1Qy1mgA7c/A/FePYPwtoHVNT1hUuIHBg9rAEsESwJLBSgcFjF9ZeI6wMQwCigCQgak6qhi4WCUYIpS5RIQYJJgUgAmWgsWBxYP1gRGKUGgCKOCiMF/GGDsYgw1MDA1NjA2NDAxNjUyBHKMDAwNjI2BAqaGukAuGBkbYAJdUwMjLMIQ8IhRguPgUyaBE0+ZJC6fZ1L4cIlJ49MlJoPPl5heMLJ8YGSfxchwiInhFiPDLCYGpanMnGCnN6Q5CEI8IeIgOWsmCJy0t4SIXLBXTAODa/ZGT5kK3vQzVbG55xfl5mcrBEuwadE4pWl0OlDDmIaTRwiYE4xP3mHH7DRHargDG4CEc9hjB6gNP+yDwDm4EBwPH+1Z3abc2NHMgM99WMGmbmlHXqbr9thlP9i36xSvLBH/Zf+8lHNOrexPe/dM4wf8C3/ZP/zvUdXc/BGHvqEDhAzslhpMen6Fw+HAlxO3ds1nciCkIwqa5z8Q7XcAfinNIQ==

RNG Seed: 919764461

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 381 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x9e
panic({0x17c3b40, 0x3f03760})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0xc00058ca50, 0x13a01a5?)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:213 +0x113
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0xc000cefd08?, 0x140ef6f?)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0xb0
github.com/wowsims/wotlk/sim...

**Comment by vigo2** [comment]
This doesn't repro on today's live build (https://wowsims.github.io/), so it's most likely been fixed. Which binary release was used here, if that info is still available?

Tentatively closing, if you can repro with a current release build feel free to reopen.
