### ISSUE TITLE
Alliance version of the premade bis gear for simulations

### ISSUE THREAD

**Issue by Habste** [wowsims/wotlk#3204]
Hello, it's such a minimal thing I know, but it would be great if you could add the alliance version of the premade bis gearsets for Togc. They have completely different names, so it's a bit confusing when looking what boss drops each item. Thank you

**Comment by lologarithm** [comment]
which class? some classes already do have separate versions for each faction

**Comment by jarveson** [comment]
it'd be up to each class maintainer to add, in some cases may not just be a 1:1 swap of gear over, and other cases would cause more for each spec type. also phase presets are really just that, a preset to help out and should not be considered a 'bis list'
