### ISSUE TITLE
Crash Report 1204729735

### ISSUE THREAD

**Issue by acuD1** [wowsims/wotlk#321]
Aura with 0 duration
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:54 +0x10
panic({0x99ca0, 0x2a8ad8})
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0xb7d8480, 0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:455 +0xe8
github.com/wowsims/wotlk/sim/rogue.(*Rogue).registerDeadlyPoisonSpell.func2(0xb7a1560, 0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/rogue/poisons.go:72 +0xc
github.com/wowsims/wotlk/sim/core.NewDot.func1(0xb7a1560, 0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:147 +0x1f
github.com/wowsims/wotlk/sim/core.(*Aura).Activate(0xb7a1560, 0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:518 +0xd6
github.com/wowsims/wotlk/sim/core.(*Dot).Apply(0xb773ab0, 0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/dot.go:70 +0x23
github.com/wowsims/wotlk/sim/rogue.(*Rogue).registerDeadlyPoisonSpell.func1(0x24a7880, 0xb7a1440, 0xb7f5550)
	/home/runner/work/wotlk/wotlk/sim/rogue/poisons.go:52 +0x6a
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalize(0xb7f5550, 0x24a7880, 0xb7a1440)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:250 +0xa8
github.com/wowsims/wotlk/sim/core.ApplyEffectFuncDirectDamage.func1(0x24a7880, 0xb790600, 0xb7a1440)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:312 +0x1e
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0xb7a1440, 0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:288 +0x1b
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:263 +0x12
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func3(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:294 +0x49
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:118 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:267
github.com/wowsims/wotlk/sim/rogue.(*Rogue).applyDeadlyPoison.func2(0xb7d5d40, 0x24a7880, 0xb7d8240, 0xb7d6a50)
	/home/runner/work/wotlk/wotlk/sim/rogue/poisons.go:130 +0x1b
github.com/wowsims/wotlk/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:669
github.com/wowsims/wotlk/sim/core.(*SpellEffect).finalize(0xb7d6a50, 0x24a7880, 0xb7d8240)
	/home/runner/work/wotlk/wotlk/sim/core/spell_effect.go:252 +0xf2
github.com/wowsims/wotlk/sim/core.ApplyEffectFuncDirectDamage.func2(0x24a7880, 0xb790600, 0xb7d8240)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:323 +0x26
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0xb7d8240, 0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:288 +0x1b
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:263 +0x12
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func3(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:294 +0x49
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func1(0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:118 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:267
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).TrySwingOH(0xb7cadd8, 0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:496 +0x2b
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).SwingMelee(0xb7cadd8, 0x24a7880, 0xb790600)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:444 +0x3
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).resetAutoSwing.func1(0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:352 +0x6
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:292 +0x14
github.com/wowsims/wotlk/sim/core.(*Simulation).run(0x24a7880)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:230 +0x19
github.com/wowsims/wotlk/sim/core.runSim({{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, 0x0}, 0xb7738f0, 0xb773a40, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:108 +0x35
github.com/wowsims/wotlk/sim/core.(*Simulation).runPresims(0x24a77a0, {{{}, {}, {}, 0x24810a8}, 0x0, {0x0, 0x0, 0x0}, 0xb773340, ...})
	/home/runner/work/wotlk/wotlk/sim/core/presim.go:93 +0x2f
github.com/wowsims/wotlk/sim/core.runSim({{{}, {}, {}, 0x24810a8}, 0x0, {0x0, 0x0, 0x0}, 0xb773340, 0xb773490, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:79 +0xb
github.com/wowsims/wotlk/sim/core.RunSim({{{}, {}, {}, 0x24810a8}, 0x0, {0x0, 0x0, 0x0}, 0xb773340, 0xb773490, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:40 +0x2
created by github.com/wowsims/wotlk/sim/core.RunRaidSimAsync
	/home/runner/work/wotlk/wotlk/sim/core/api.go:74 +0xa

Link:
https://wowsims.github.io/wotlk/rogue/#eJztUjFIQlEUfff+h/6eJa9oeDn9/iRB8PzyhyZ/rS1CW5MNOTVEtNQkTSZRQ0u1VCYaidEURTQZqA1FBIEiEUnhGDS0FPT+t73FoaEzXM65nHvO8B4L6igxjvOYAmgDTDABBqYBDgEGSKhFV8AXn5tZml3QgftCR8A4Lx2guH1E03daxq1zZJS/FJD18c0sioraa18XwHR+v4eiUdIU22iogyayAC/WUVTrmglEif0cis+OYPw6iya9OUOi/Gt5FK9FVGxVXX40gfn5+x26RsozebdxPefO46xrulT23RO38qnQYZRXVFwv14xAmEmI0wQdqSL5R1ewTHUQOB1kugAOYTA09VNIBsJS2lFLenNUWrYl7YhSMmrLiG1ZUSUUs+zIM5A20Dfw7wBpADEzWo8XnEo6/Z2KQWdoZ9tFLTac9PAQs1poTAn8sw+56HQjJVW7+iVnsis9Lsa8mS474z8LJwHfsjVfSA==

RNG Seed: 99362016

**Comment by acuD1** [comment]
Just had this crash, dunno if i had to submit it. By default your website is triggering this ;)

**Comment by jimmyt857** [comment]
This should be fixed now. Thanks!
