### ISSUE TITLE
Use Starfire checkbox doesn't work

### ISSUE THREAD

**Issue by ovu-github** [wowsims/wotlk#3230]
**Describe the bug**
Moonkins have a Use Starfire checkbox. When I uncheck the box, I would expect the timeline to show no Starfires, but it does.

**Expected behavior**
A timeline consisting of just Wrath

**Comment by lologarithm** [comment]
looking into the rotation code there is a bunch of edge cases not handling the flag which is causing the spell to still cast. If you like you could check out the new rotation tab, click on the 'basic apl' saved rotation and then you can modify it however you like.

**Comment by jarveson** [comment]
Theres a base apl for moonkin now, editing that would be preferred vs trying to capture exact usecase of the 'use starfire' box
