### ISSUE TITLE
Perdition only allows one gem instead of two

### ISSUE THREAD

**Issue by BreakBB** [wowsims/wotlk#3237]
**Describe the bug**

**To Reproduce**
1. Select Warlock
2. As Weapon choose [Perdition](https://www.wowhead.com/wotlk/item=48045/perdition)
3. Add a gem to the first socket
4. Try to add a gem to the second socket
5. Error: The gem in the first socket is removed

**Expected behavior**
The staff should allow two gems to be set.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 114.0.2

**Additional context**

**Comment by where-fore** [comment]
On a restore-default Warlock I can correctly socket two gems into Peridition - check that you are not accidentally socketing in Stormjewels - which are similar stats to the new Phase 3 gems, but are unique equipped.

**Comment by BreakBB** [comment]
Haha, you are absolutely right @where-fore - Thanks 🤦🏻
