### ISSUE TITLE
Missing items: Handwraps of Surrendered Hope

### ISSUE THREAD

**Issue by supernicky22** [wowsims/wotlk#3258]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=47230/handwraps-of-surrendered-hope

I think it's better than my current ones,  but the item level is lower, so please, let me sim it :). Thanks!

**Comment by Tharre** [comment]
They are already in the sim, check if you don't have Phase 3 selected or you have some filter active.

**Comment by supernicky22** [comment]
I am sorry! I mistook them for wrists, but they are hands, and yes, they are allready there. Thank you and have a nice day!
