### ISSUE TITLE
Bugged death knight 232 tier set bonuses

### ISSUE THREAD

**Issue by CharWS** [wowsims/wotlk#3305]
**Describe the bug**
The 232 ilvl tier 9 items with the suffix "of Conquest" do not have their set bonuses linked to them. 

**To Reproduce**
1. Equip enough pieces of "of conquest" tier 9 gear to achieve a set bonus with a noted effect
2. run the sim
3. note that the effect is absent from the sim

**Expected behavior**
Equipping "of conquest" 232 ilvl tier 9 sets should activate their set bonuses.

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/deathknight/#eJztVVtIFFEY3v+fcZs5ansaraaD2jZFyIJ1ZpeNLsRsvQS9dPElood6MCIiJF+6vFhodI8oygwKKsIKNIKojYKyehASlvBCBV2tViRaNGu72pmd2dVCycp66mcY/u/7L+c/3znMEENBihzXQDlUAtQBXAC4ARADiAMkAWOI86kfOURgmcjZkcrRPKyPbAPv4nWrNpVtUFRKWAcQH33/EfXOQsN7pxHvRZGo9Fk3GpLt5tAPIvak0JCON9noWg/q713ko70ilhR1bX1oE7n0cQfq1UWG3BBFj4DvRPxQgSHfs6GP3hFdVeGLRyQQjXZ2o/6m0FBvRvHMy9TSPnpCtDhcYHgbnCQxwDvMIJVeSk8m03i3/T7bYSf1iE51zJCckrqefiTT6Fs0fAry3JmwWF4mb7TFOIm9SG6g57/9kWn8Vys2ywro+BFMQhRxN2OACQA2eYwTTVh+CGQrfWkDDvPcwsgumBoM8TDnPFwSCop3KMxD4WCQh7gpApyHQiY3Q2HzGejKsRakR1pQf/0C/TUtWFzTivxoK8ZBTsCoWvA0YkImlCjMS2Rl5wfU5JIgr8gwtc02YwrG5zJb90iaVDIjQ9CDV1EQZgUZ7WYkv6KGvB+/PC99h6PNYGNNZjjbox0CdgC0fUC8i8rL1pdt0JykT82SRphCvMrW7ZIfXL9qgP+o4UffqYz1oOslu9JeVR8O2cHJuP8cv2N1No7kGOJsgnb0cr2UmYoxfUDkjIj0TzmFGUQPjFNkTVmbrhNRIpvTwhWOoHslbSzLI+pJcAfLaDYIbUs1CG0rOpfNIaY2fUCIGMxP1Ivg9iN5gTFKlqaeSxMMF3oyJzbYDF0pCTKCTWITydhAnuiRtQtRAda/p/ROcthAzdLI0XgCG09yjewfV3lVLT0ATy16jN2SmrrQlasj7q3Pj0yoPWpbkzXLYWLWpNUpa7OCD9FfqmcF/vLHqnhnZCTaVDbd/kmf0hFZ53fM0fb6m4j7SUlaK2Fp6jdwq7d4xf5GNdJ+qnwuaX9uDbejc2qdllPfOkRdwrpSVN215MpXa2nKiVtO3RfrtL3cqbiVX7/g6eb87iHX3ZJKqBr2XP/aNN581zYl4uzo808nXe7+OBLD3tM3AIxDUQ== equipped are 4 pieces of "of conquest" death knight tier, notably blood plague does not crit, changing to 4 pieces of "of triumph" suffix ilvl 245 or 258 tier 9 gear the set bonus is active

**Additional context**
at least boomkin, hunter, and ret paladin "of conquest" tier set bonuses appear to function just fine so potentially isolated to just the death knight tier, but didn't check every class and spec

**Comment by rosenrusinov** [comment]
Wowhead has a tooltip in the 232 horde set
![image](https://github.com/wowsims/wotlk/assets/5707996/d025b43d-f686-4c55-907a-5a7f5eac5094)

The alliance version of 232 is properly working.
