### ISSUE TITLE
differences between app and web

### ISSUE THREAD

**Issue by Ulidan** [wowsims/wotlk#3325]
For druid tank sims, the windows app reports 26% chance of death VS 1% on web.
App:
![image](https://github.com/wowsims/wotlk/assets/24996389/267d7e64-d676-4aae-8cea-8786d321b5ee)
Web:
![image](https://github.com/wowsims/wotlk/assets/24996389/9df2a13f-abd1-4d89-9622-339f71dc889c)

This is WoW Wrath classic

**Comment by Tharre** [comment]
That's expected, the app only gets releases every week (on mondays) and thus can have different results. Check again after the new version releases tomorrow.

**Comment by Ulidan** [comment]
v0.1.38 resolved the issue
