### ISSUE TITLE
Missing items: Suffering's End, Suffering'

### ISSUE THREAD

**Issue by sara-en** [wowsims/wotlk#3335]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

**Comment by lologarithm** [comment]
Suffering's End is in the sim - did you try changing the phase dropdown to 3?

**Comment by sara-en** [comment]
I am in phase 3 for enhance shaman. I have used the search function and read the list and cannot find it.

**Comment by lologarithm** [comment]
It is main hand only, and requires that the "1H" box be checked at the top. Did you check both those things?

**Comment by lologarithm** [comment]
![image](https://github.com/wowsims/wotlk/assets/577261/972aba09-e227-4346-8280-a78f7f148cea)
