### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by lovelaxo** [wowsims/wotlk#334]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item: 

Phase 5 items:

Charred Twilight Scale HC: https://www.wowhead.com/wotlk/item=54588/charred-twilight-scale
Charred Twilight Scale NM: https://www.wowhead.com/wotlk/item=54572/charred-twilight-scale

Bracers of the Fiery Night HC: https://www.wowhead.com/wotlk/item=54582/bracers-of-fiery-night
Bracers of the Fiery Night NM: https://www.wowhead.com/wotlk/item=53486/bracers-of-fiery-night

Cloak of Burning Dusk HC: https://www.wowhead.com/wotlk/item=54583/cloak-of-burning-dusk
Cloak of Burning Dusk NM: https://www.wowhead.com/wotlk/item=53489/cloak-of-burning-dusk

Phase 5 healer items:

Ring of Phased Regeneration HC: https://www.wowhead.com/wotlk/item=54585/ring-of-phased-regeneration
Ring of Phased Regeneration NM: https://www.wowhead.com/wotlk/item=53490/ring-of-phased-regeneration

Glowing Twilight Scale HC: https://www.wowhead.com/wotlk/item=54589/glowing-twilight-scale
Glowing Twilight Scale NM: https://www.wowhead.com/wotlk/item=54573/glowing-twilight-scale

**Comment by lologarithm** [comment]
oops! I guessed a max item ID when scraping for items. I stopped at item like 52200, I will run it up to 60k to see what else I can find

**Comment by lologarithm** [comment]
added those https://github.com/wowsims/wotlk/pull/338
