### ISSUE TITLE
Soulfrost spell power seems to not clear on weapon swap option

### ISSUE THREAD

**Issue by OttoBoyWonder** [wowsims/wotlk#3344]
**Describe the bug**

**To Reproduce**
1. On warlock sim, enable the weapon swap option
2. Add a weapon to the weapon swap and add soulfrost enchant to it
3. Run the sim
4. Save to reference
5. Review sim numbers
6. Change the weapon swap enchant to mighty spell power
7. Run the sim

**Expected behavior**
The difference between soulfrost and mighty spell power should not be so high in terms of sim. Perhaps the shadow spell power is 'sticking' after the weapon swap.

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/warlock/#eJztU0FoE0EU3f+zbjerJWMIOIa2xL0YhcIky0J7kN16McdoL6V46cEKEjR40niJVdFWUA8iNKhIvXhRGhE1VLFES+lBWwxEqpemsRixaohERVCc2SQ9SFGL9SJ+htn57/339/PnjxZQkSDDDohAD8QxCXAOYBRwHGAGoASw3aNCABnYEIU4XAPwSv4zygAo0Vjf4T0H1Sai+vOgecitKtLFVl2ZyOJEBjU3eTyHuusFP64jDzg339rwbr5EOsQ9EeYhmRLSz6qupDMo6GbytYL0oleXOSBxd4xrz7fUXQ8Zq6Du5sq0szhwn/NX2pb0HjI9h/RCyxIgk9NFUc6dIi8n7QCpotifFEUxlz8g/cKLmXWY/G0R+q5Qq1xvVoFBVO5ZcwhOAYxgFbVxlP7bH5mXrVSRUFUgSDEO+wxtCz/LlM9kkN9NB0ahdwO/9OufkJZ9unIvg3z5ZTJZRL9SCx2CzWHDZIyFmcE3wwyxsCkAwwiFzFB7uylIxszQPFD10kkXmV1AmlvAwEAOg9+eIjuawxLIZVibAimL0mB9Bjrt5yClUNJHXG4HSPbb62uUz96YGhY2ZXXWkBlrU79jeStcwfirJCaaumJ7+2IH9ge6qbz1Lw9WcNBejTTJqUe/yNP9M350unKsazXqWM6cRgd87+1hqPU+Y9X/VbYisGvZx3vEd2NHIXHc0p5djW/TJq1IISEQq6FrxD2sBnefzb61PopPdc5a3Hm37cSb19aP+f51W/nj7a0ryr/dq+/A471+

Link to sim above

**Comment by Tharre** [comment]
Your assessment is correct, we use a bit of a hack of adding bonus SP to the spells themselves for school-specific SP since they are so rare in wrath, and that does not get reset when you swap weapons.
