### ISSUE TITLE
set effects for t9 doesn't seem to be accounted for during sim

### ISSUE THREAD

**Issue by ccchaoche** [wowsims/wotlk#3346]
**Describe the bug**
T9 set have this unique characteristics that each faction gets their unique gear. For instance, for warlock T9 shoulder, Alliance version is called "Kel'Thuzad's Shoulderpads of Triumph" and Horde version is called "Gul'dan's Shoulderpads of Triumph". They have same stats but are different item. Therefore if Alliance and Horde gear are wore together, they do not form the set bonus. Therefore, if we run a sim with 3 Horde piece and 1 Alliance piece, the dps should be significantly less compare to a sim with 4 horde piece, reflecting the fact that former is missing 4 piece set bonus. This is not the case right now and both sim from above result in exact same dps.

Two possible reason could explain this:
a. internally, the sim counted Horde and Alliance piece as same item and incorrectly gave the set bonus while siming
b. set bonus was not accounted for during simulation

I do not know which one but judging by siming seems to be way off and T9 set has been given lower then expected sim result, I suspect it's b.

**Sim Links and Screenshots**
Example of horde 4 set bonus (https://wowsims.github.io/wotlk/warlock/#eJzj0uRgFGDUYLRg9GAMYMxgrGBsYGR8wPSCfQUj4wZGpgOMjBcYGW8wMr5gZHQSBimVYFRgMmB0YIxgLGAEqhFikNrM1sTIFpCTWJlaBFTAIXWXkYtfYM9XJok3skpsRw8xHd3JxMUpcPYBkxLzbSCTR2AjUO6RLIw3+w+TRBeQtxHIExJ49olJ4geHEidQE1AaJMYlcOcjk8QcISVGBi5egd1AvVNklFiAMgxAa359Y1LihCgEqeUX2AuUXyCnxLYRrB8ocP4Bk8Q0GbDARrBD7j2HOoRTYMILJoi9LALnHoPIWY9BbljynUmiTw7mBpBSBqDidw8h+pREOBgNgOEVwBLBmsAKDq8ORsZFTF+ZuA4wMYwCioCQAak6qthAqbKAMUuCiw/IYgGlTw1QBDFJsUH4XYzBRsamBgZGRgaGQNLY1NDAyBQkYGxsaGhqqGuAG+iamoJpoBZ08IhRguPmUyaBy0+ZJOa2Myv8vcSk0XSZyeDfJaYXjCwfGLlnMXJwsXGxcDxbzXyIiaETmjQsHW4xMsxiYlCaxcwJFjhQ5CAIkRJxkIQwHthbGoPBY3vFs2dA4I290Sumgjm1VZwBiSXJGeWpRdkKwRIcWjROcBqdDtQwpuHkEQLmBOOTN7DQKnCkhjuwAUsQ0SD00AFqwwt7YGYOwpqXq0XWuT+sarHnur64wJbruL3HwyqQiD1E9oM9TN3hrxox/Yfe2n8DUV8f2L8J3CHX+vqlPbp5wx2QnpejSNYBABg0wJQ=)

Example of horde 3 set and shoulder alliance piece that still gives the same dps sim:
https://wowsims.github.io/wotlk/warlock/#eJzj0uRgFGDUYLRg9GAMYMxgrGBsYGR8wPSCfQUj4wZGpgOMjBcYGW8wMr5gZHQSBimVYFRgMmB0YIxgLGAEqhFikNrM1sTIFpCTWJlaBFTAIXWXkYtfYM9XJok3skpsRw8xHd3JxMUpcPYBkxLzbSCTR2ADUO6RLIw3+w+TRBeQtxHIExJ49olJ4geHEidQE1AaJMYlcOcjk8QcISVGBi5egd1AvVNklFiAMgxAa359Y1LihCgEqeUX2AuUXyCnxLYRrB8ocP4Bk8Q0GbDARrBD7j2HOoRTYMILJoi9LALnHoPIWY9BbljynUmiTw7mBpBSBqDidw8h+pREOBgNgOEVwBLBmsAKDq8ORsZFTF+ZuA4wMYwCioCQAak6qthAqbKAMUuCiw/IYgGlTw1QBDFJsUH4XYzBRsamBgZGRgaGQNLY1NDAyBQkYGxsaGhqqGuAG+iamoJpoBZ08IhRguPmUyaBy0+ZJOa2Myv8vcSk0XSZyeDfJaYXjCwfGLlnMXJwsXGxcDxbzXyIiaETmjQsHW4xMsxiYlCaxcwJFjhQ5CAIkRJxkIQwHthbGoPBY3vFs2dA4I290Sumgjm1VZwBiSXJGeWpRdkKwRIcWjROcBqdDtQwpuHkEQLmBOOTN7DQKnCkhjuwAUsQ0SD00AFqwwt7YGYOwpqXq0XWuT+sarHnur64wJbruL3HwyqQiD1E9oM9TN3hrxox/Yfe2n8DUV8f2L8J3CHX+vqlPbp5wx2QnpejSNYBABHpwJM=

**Comment by Tharre** [comment]
The T9 set bonus is working correctly, we just treat both alliance and horde set pieces as part of the same set, so it's a).
