### ISSUE TITLE
Talisman of resurgence not working in sims

### ISSUE THREAD

**Issue by fulldru** [wowsims/wotlk#3347]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tharre** [comment]
What isn't working about it? Seems correct to me.
