### ISSUE TITLE
Black background and numbers on Talents are to large

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#335]
**Is your feature request related to a problem? Please describe.**
Basically people told me that its hard to see which talent is below this big black background and numbers.

**Describe the solution you'd like**
I guess just make it smaller

**Comment by jimmyt857** [comment]
Could you supply a screenshot to make it clear what you're referring to?

**Comment by romanhallo** [comment]
https://gyazo.com/9f02eab0f7af5536f84d613d587b24f8 
See u almost cant see the picture of the talent

**Comment by jimmyt857** [comment]
Hmm I'm going to need a bit more info, as this looks fine on the live site:
![ele_shaman](https://user-images.githubusercontent.com/1822327/181301070-990376e5-2b44-44ff-8b7c-7d127a152cd9.png)

We haven't had anyone else mention this so it's probably a strange browser / screen size that you're using.

**Comment by lologarithm** [comment]
I think they mean that the numbers are covering the icon and larger than in wowheads talent selector.
![Screenshot from 2022-07-27 10-46-45](https://user-images.githubusercontent.com/577261/181303866-f3d8242d-a042-44da-bd7e-37a11f034af3.png)

**Comment by lologarithm** [comment]
we could maybe move the number down to the right a tiny bit

**Comment by romanhallo** [comment]
Would be really nice :)

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/348

Here is new screenshot:
![Screenshot from 2022-07-27 18-43-36](https://user-images.githubusercontent.com/577261/181396362-8f468b19-3afd-4d69-9f1f-f8ada752e5b9.png)
t
