### ISSUE TITLE
Settings->Other has "Starting Overkill Duration" even though Combat Spec (Doesn't skill Overkill) is selected

### ISSUE THREAD

**Issue by i1Spook** [wowsims/wotlk#3354]
**Describe the bug**
Not sure if it's a bug or simply a mistake. "Starting Overkill duration" is available and is set to 20 seconds by default, which obviously makes sense. But that option is still there even when the Overkill Talent is not selected at all. I have tested it with multiple sims and it does not change the outcome whether 0s or 20s are selected so it's not technically impacting the sim but it does generate confusion.

**To Reproduce**
1. Use Rogue Sim with Assassination as starting point.
2. Switch talents/ gear to Combat (effectively deselecting Overkill) I use Saved Settings to switch between specs.
3. Under Settings -> Other "Starting Overkill duration" is still present.

**Expected behavior**
Whenever I deselect a talent in the "Talents" tab, its parameters or variables shouldn't show up in the "Settings" tab.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 114.0.5735.201 (Official Build) (64-Bit)

**Smartphone (please complete the following information):**
Not used

**Additional context**
I hope this isn't a frivolous bug report, if so, I'm sorry.

**Comment by catszeid** [comment]
The "Starting Overkill duration" rotation option is used for the Overkill and Master of Subtlety talents. Adjusting the option to only show when used is a reasonable enhancement. Thanks for noticing!
