### ISSUE TITLE
Crash Report -392948888

### ISSUE THREAD

**Issue by BenACooper** [wowsims/wotlk#3356]
Link:
http://localhost:3333/wotlk/hunter/#eJztVE1IFGEYnved2e3br10cB7PPj1W3oWgRjJkdFlKQmbrk0fLWyYI8dZC8lCcRhLKDRFm2BYpdgiCkQ+RBEOugUSoS/vQDplmKkVtpGITbNzvrT1SUtd16Du9878/zvN/ffJQTVNHA/VCFNVCHZwG7AUcA5gAOhghEMAoOnIabAJrEL5Am8FedPHbmxCkiq8iHgOaoA00ymy/U/XfvY3cPUkX9Mos0qE4sIZsq1OUnIpajjrxB1hbW/aLCDWjq8jtkK4V6QAT6vVhInV5E1lykK8KThLu6guxSWFd6XTeoXptB1hrW5e60YNNnZIuiqyC7gaDalER2Oez1U9QPS66dnXLtwmvXvph0aQlR9XGD5upeFF3bBXEshTohaIDYC6ULl5H2ofQffwXN2CqjgRBQkWEdlFfQQG465nQ43BD3tJjnCwviRsqVcjtAH8gDABMAuzxu0i57/MjFWzsKLbA3bsRKDSNuWXHTMGOWYZhWzLJMK25YphE3S+OGgBWbBkY6h1HtGkbW8woj46MYfTiKxtgozoGSBJoAqR9bsROAhqifKxRZriaXmvXaTr6D5pbkEJ+G5RLfRn1UNo36crFuvo/u1nQa0rfTwB3wU4UkWjBdK2t4fL12D8+kfsS4MiOvqa8xrAxDpDTKSXo89FzWGM+nQZ1SEnMj86vIM1+Nc7YpcyuFnFC/+43AusJkx4ZaIoXr43YxDhLIeG2bMtdT+BSkBEr6eTmQ3vzGWsc7LSnPKUhcdTFol3mREXtXbRpjduwZRqqZr+Qf/1vRc042ZBoHH/xCpzorff4E3t72LjoHPH/FroEj37xaVho+x/OmbO9U3ttZmoCz1reCjt+oq/hkFzcvHL5XtLxF/WS25pM1fP9qVb5syLt9qMD5GeNohvH7a/kK5VvQLg==

RNG Seed: 1535496062

Trying to cast {SpellID: 49067} but is still on cooldown for 9.375836867s, curTime = 43.419641479s
Stack Trace:
goroutine 573 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x9e
panic({0xb99f20, 0xc0006ba920})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncCooldown.func1(0xc00049fd90, 0xc00049fd90?)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:233 +0x119
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
guessing this was fixed, as link does not error on simulate
