### ISSUE TITLE
Fetish of Volatile Power doesn't apply stacks as in game.

### ISSUE THREAD

**Issue by ClayProof** [wowsims/wotlk#3362]
**Describe the bug**
[Fetish of Volatile Power](https://wowhead.com/wotlk/item=48018) does not gain it's stacks correctly as it triggers of spell hit not casts in game. 

**To Reproduce**
![image](https://github.com/wowsims/wotlk/assets/140325108/610a6122-a945-447f-80ab-1c453a9ecb6d)
As shows here it is currently only applying stacks on casts, In this case at each Starfire. 

**Expected behavior**
An easy way to verify the actual behavior in game is with Starfall as every star's damage as well as the splash seem to count as a separate instance, so the trinket usually gets to the full 8 stacks a lot faster (2 per star hit with the normal damage and the splash). It does not seem to apply with dot ticks.

**Comment by lime-green** [comment]
@ClayProof looking at some logs the proc is very strange, proccing 3 times off 1 starfire:
<img width="544" alt="image" src="https://github.com/wowsims/wotlk/assets/9436142/82ac8716-2d19-4219-80f4-51c0e158642a">
<img width="521" alt="image" src="https://github.com/wowsims/wotlk/assets/9436142/5d8114a7-e9aa-4bf7-906f-739278c2a05e">
<img width="580" alt="image" src="https://github.com/wowsims/wotlk/assets/9436142/f49579b5-9098-4a0c-81ee-f309d06de027">

and yea, proccing twice from a single starfall:
<img width="433" alt="image" src="https://github.com/wowsims/wotlk/assets/9436142/c71e9ae5-ed21-4e14-af58-849333150c2e">
<img width="408" alt="image" src="https://github.com/wowsims/wotlk/assets/9436142/4927605e-0563-47a1-b3d1-99e98d6c018d">

@ClayProof do you have any idea why it would be proccing three times on a starfire? I'm not very familiar with boomkins but it looks like this trinket should be proccing a lot more than it is currently

**Comment by lime-green** [comment]
OK I figured it out, it can can proc 3 times on starfire: once from starfire itself, once from the re-application of moonfire via the glpyh and once from the application of earth and moon

**Comment by ClayProof** [comment]
I think that is correct. Not the biggest deal as the trinket is behind in
power level. But for folks catching up seeing the correct Sim values might
matter.

Den lör 9 sep. 2023 06:45Josh ***@***.***> skrev:
