### ISSUE TITLE
Surplus Limb adds about 200SP to base spell power for ele shaman

### ISSUE THREAD

**Issue by BRBCoffeeDebuff** [wowsims/wotlk#337]
**Describe the bug**
Adding Surplus Limb adds Surplus spell power

**To Reproduce**
1. Go to 'Ele Shaman sim
2. Scroll over Spell DMG magnifying glass
3. See base spell power
4. Click on 'off hand'
5. Select Surplus Limb
6. Look again at Spell DMG magnifying glass. 
7. Enjoy 210 extra Spellpower!

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lologarithm** [comment]
Good catch! It thought that Surplus Limb was an offhand weapon and was applying flametongue weapon to it. I should probably just disable offhand weapons at all if you don't have the talent.

Fixed in: https://github.com/wowsims/wotlk/pull/339
