### ISSUE TITLE
rogue talent not affects in right way

### ISSUE THREAD

**Issue by joexi** [wowsims/wotlk#3372]
**Describe the bug**
rogue talent named mace specialization does not affect off-hand weapon wen you equip a mace in main-hand and a sword in off-hand,but in game it will affects melee or skills both hands

**Comment by joexi** [comment]
i have fix this issue with pr #3402 ,any one can approval it?

**Comment by catszeid** [comment]
Issue is fixed with [commit here](https://github.com/wowsims/wotlk/commit/0fecdbfa644a3bc6329a1b20a0e131d597171f9d).
