### ISSUE TITLE
Simulation Set Diffs... 1 Piece Diffs & Priority Upgrade Pathway Generation

### ISSUE THREAD

**Issue by loquerion** [wowsims/wotlk#3403]
**Is your feature request related to a problem? Please describe.**
No, net new.

**Describe the solution you'd like**
I would like to be able to choose 2 sets of gear for my character, and ask the tool to "Diff them", item by item, presenting a list prioritized by which items give the best DPS increase.

**Describe alternatives you've considered**
At present, I am manually changing each item in the base list, running the sim, writing the result down, resetting to the saved base spec, and changing the next item.

**Additional context**
Extending on from this, it would be interesting to work out the best 1,2,3, or 4 stage upgrade paths (to include the potential for set bonus' etc).

**Comment by kayla-glick** [comment]
Hey @loquerion 👋 this can already be accomplished with wowsims using the experimental "Batch Sim" feature.

You can enable experimental features from the cogwheel in the header.

<img width="279" alt="image" src="https://github.com/wowsims/wotlk/assets/12898988/0ac1ba0d-ec5e-494f-8d3f-15c4e3898b5f">

<img width="825" alt="image" src="https://github.com/wowsims/wotlk/assets/12898988/7b30d20f-8461-4cec-9e16-4da0ccce7938">

You should then see the in-development "Batch" tab where you can import from bags using the wowsims exporter addon, from favorited items, by adding all items in a gear slot using the "Add to batch sim" button, or by searching items by clicking "Add item" in the batch sim tab.

You can then sim a batch of items, see the DPS value of each batch, and get recommendations.

<img width="1728" alt="image" src="https://github.com/wowsims/wotlk/assets/12898988/8808dc84-af04-4118-bf5d-afae5a7f9891">

**Comment by loquerion** [comment]
Thanks Kyla,

You and the team are truly Titans amongst Murlocs :)

Loquerion
