### ISSUE TITLE
Bonus stats are displayed in a confusing way

### ISSUE THREAD

**Issue by jdelvare** [wowsims/wotlk#3408]
**Describe the bug**
When adding a stat bonus, the displayed summary for that stat is confusing.

**To Reproduce**
1. Hover a stat value in the bottom left hand side Stats panel, for example Agility.
2. Write down the itemization displayed by the tooltip.
3. Add a bonus value of 20 to that stat.
4. Hover the new stat value and write down the new itemization.

**Expected behavior**
I would expect the Base value to stay the same, but it changes.

**Sim Links and Screenshots**
![agility](https://github.com/wowsims/wotlk/assets/4045314/13fe1f05-c5f6-4d8a-a2d6-ba9bf36e9f76)
![agility_bonus](https://github.com/wowsims/wotlk/assets/4045314/48c31a1d-5e07-406f-a24b-2efab1087bcd)

**Additional context**
I can think of a variety of ways stat values could be displayed when a bonus is applied. For example, the Bonus could be displayed separately (as is the case in the current implementation), the Buffs value would be adjusted accordingly (as is also the case in the current implementation) and the Gear and Base values would stay unchanged (which would differ from the current implementation). Or the bonus could be merged into Gear and Buffs directly, colored in green or red to highlight the presence of a positive or negative bonus, respectively, Base would stay unchanged, and no extra Bonus line would be displayed.

Either way, the Base value should never be affected by the bonus. Right now if I add 20 to Agility, the actual effect is:
* -20 to Base
* +20 to Gear
* +2 to Buffs (from BoK)
* +20 to Bonus

While the total (+22) is correct, the itemization is utterly confusing.

**Comment by jarveson** [comment]
k got a fix for this. internally, as you kinda saw, internally the 'bonus stat' gets added into gear, and on display was incorrectly getting removed from base. Changed it here so display removes the bonus from gear instead of bonus

**Comment by jdelvare** [comment]
Looks much better, thank you!
