### ISSUE TITLE
Boneshield Tanking Adjustments

### ISSUE THREAD

**Issue by NuptupTDOW** [wowsims/wotlk#3410]
**Is your feature request related to a problem? Please describe.**
I would like a few adjustments to be made for Bone Shield in the tank sim. Currently, the sim doesn't prioritize maintaining bone shield, and uses it reactively to dropping below your "use cooldowns" threshold. Also, the sim doesn't account for the option to pre-cast Bone Shield 1 minute before the pull so you can immediately gain 3/4 more stacks as soon as your first set falls off. 

**Describe the solution you'd like**
I would like to have the sim treat Bone Shield as a buff that is psuedo-mandatory for the dk to maintain, or at least have the option in rotation or settings to treat it as such instead of as a cooldown to use reactively. Secondly, an option to enable pre-pull Bone Shield would be ideal so that you can start with 4 stacks, then immediately have another 4 stacks ready to go once those are depleted.

**Comment by rosenrusinov** [comment]
You can do all that with the APL. 

We are no longer maintaining legacy rotation and ritatuons are now a community effort.
