### ISSUE TITLE
Shadow Priest Twisted Faith Not Adding Spell Power Based on Spirit

### ISSUE THREAD

**Issue by CMamms** [wowsims/wotlk#342]
**Describe the bug**
5/5 in Twisted Faith in the Shadow Priest talent tree should yield 20% of Spirit = Spell Power. This does not seem to be calculated visually or actually in my tests.

**To Reproduce**
1. Build a Shadow Priest loadout, ensuring 5/5 Twisted Faith is taken.
2. Ensure Glyph of Shadow isn't taken as it has a similar effect (10s duration rather than passive) and is working as intended
4. Run the sim and take note of the DPS
5. Add x spirit manually (I did 1000)
6. Run the sim again

DPS will come out to the same depending on iterations, but with 200 expected additional spell power the DPS should be noticeably higher

**Expected behavior**
Ideally the SPELL DMG visual display would reflect how much additional spell power you are getting from Twisted Faith. Perhaps as "Base" similar to the Totem of Wrath for Elemental Shamans or Talents since Twisted Faith is a talent.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 103.0.5060.134 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by lologarithm** [comment]
good call!
fixed in https://github.com/wowsims/wotlk/pull/347
