### ISSUE TITLE
Runestrike no longer executed for Tank DK sim

### ISSUE THREAD

**Issue by Juliean** [wowsims/wotlk#3467]
**Describe the bug**
The ability "runestrike" is no longer being executed when running a DK-tank sim, both noticable by looking at it missing in the "results" tab as well as generally way less DPS than before. This must have happened in the last few days/weeks, as with the new APL-options, runestrike initially worked as intended. While I have a manual APL-setup, it still happens even with the legacy or default-APL variants.

**To Reproduce**
1. Open the link I provided below of my sim
2. Click on "Simulate"
3. Open the "Results" tab
4. See runestrike missing

**Expected behavior**
Runestrike should be executed as part of the rotation normally

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/tank_deathknight/#eJztVVtoVEcYPv9/Nuuc30smk6gnY3Z7el5MFyKzu6xVaTlbX/oaLUIpfZGihNqHVAulgcIqXlqhpJTWy9LW0pYQfYhFEROKoOmFGgxNIaa0D1KzuG6T1garsOKDzrnssqEtKLFv/uy5zHf5///MDLO0miFHGxT2QC8UAAYBvgI4DzABUAGoAk4gFhA2OhxscEBBHnzpO4F02Nfhb4BVgA2GMOQA7YF492tb39q2kxEneQWomQ9W0B5IuvEvv8HyCJLFZ26ia17Qr0v4Cc2VEq5ZDkaXbqL9UUc4Erx6A+1qwrW0shz8aCkvacXBpBvTmEGcnyyh/WHSXRRKDF1sUuducAg+ph035mVp5t9r7FCHGx8fiTo6VsKwqsXPzEXNxfhsObj/6FumtOWA/ogwDRmaGLmFLunZa1JWt/mi+TneRjqPxuNYUAj1sI6+xQxsdKCHBoH2IKOYA50gjYPwlFK5nMqkc9msUvrKprNpPfTvuXRXNpNTSmW6tCgzDTb78xryTyfRPj2FzpFJ7OyfRHX0MlYgNgdWEVoorhf9u+vYsj2IKW8U3499BkCtxKTmWHEc3UXURGZXblcdrM7WwHQd5J+MNIBtkfLAHXSZX6Qrq3ZRgoTktIy9u8K5Vwuom8Ry2Uq6Kd/319emjJ7ClitoiUvEMj5ydihk7o6bQkq7gRnQjK7Fdu83HRDPyA2k5BpanmplMcFerXl1LYK18+CBOhx+8numSMhV1JJqZnFhjoHhw4RPq4Deew8FyfpEiHVyLaVEJ4kU1/KmDxAZhunSjVhUIh20uDdosZZl4m8UjkzW1DOADBrVV0766qTsiBRBS8GspbNhT9f3mXU+Ni9DyP9Swga+wZ8J+cOjpmiXK2mpu5isUxAtZ21Z9ZH4KySsLX4cO5dvifZovj18VjwnXkTDLZpWMC5sr0na8u3Fo35c9NaHyIT3ZG2nZWaw9+O3+6zurW+80vPmtp07nBdslvqfD5u53flHkaZw8duF5FHrUr3PPYo+/i2CmS4cms5HFSqe/mPbHJzjT+yb3TScvOxlgyh5oWDOW2jJ4aSfeMh7/Vn6+Yvea94fm3zkJ+9qX9vQ81fHvM2B4Ic6/195ws1y3Js//v0f+nALlb3+0dudL/dPL7j/Bw2hxi/5wfIP6njpoU/++wuzMjM=

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 116.0.2
 
**Additional context**

**Comment by rosenrusinov** [comment]
It seems there were some changes in the tank targetsl. Can you try restoring your defaults and then selecting your tank target again? This fixed it for me.

**Comment by rosenrusinov** [comment]
Yes, restoring defaults fixed the same setting for me. Closing issue
