### ISSUE TITLE
Expertise calculation is wrong.

### ISSUE THREAD

**Issue by aLanaMaunz** [wowsims/wotlk#3471]
Expertise calculation is wrong:
213 EXP is shown as 6.50% - which is wrong. 214 EXP is 6.50% - 213 EXP is, thanks to wows atk table rounding logic, only 6.25%.

**Comment by Tharre** [comment]
This is no longer true, Blizzard patched the expertise calculation to not round down to discrete expertise values anymore.

**Comment by aLanaMaunz** [comment]
its shown ingame as 6.25% - so ingame tooltip is wrong?

**Comment by lime-green** [comment]
@aLanaMaunz  Yes the in-game tooltip is wrong. Technically you have 6.496% expertise (`213/32.79=6.496`)

**Comment by aLanaMaunz** [comment]
thanks - sorry.
