### ISSUE TITLE
Death Knight Tank Sim Master of Ghouls Rotation Issue

### ISSUE THREAD

**Issue by NuptupTDOW** [wowsims/wotlk#3478]
**Describe the bug**
When Master of Ghouls is talented, the new version of Raise Dead is not selectable under the Cast sub-menu in the rotation creator.

**To Reproduce**
1. Go to DK Tank Sim
2. Talent into Master of Ghouls in the Unholy Tree
3. Notice that the "Raise Dead" in the rotation tab towards the bottom for the Blood threat rotation has a hazard icon
4. Click the spell and look for the new version granted by Master of Ghouls and see it is not there

**Expected behavior**
Permanent pet version of Raise Dead should be selectable when Master of Ghouls is talented.

**Comment by rosenrusinov** [comment]
Permanent pet version is summoned automatically before combat and is not required to be casted as a spell.
