### ISSUE TITLE
Favorite gear/gem sorting is broken.

### ISSUE THREAD

**Issue by cfedey** [wowsims/wotlk#3481]
**Describe the bug**
Gear and gem sorting is broken for favorite items.

**To Reproduce**
1. Go to Gear tab.
2. Click on any gear slot.
3a. If you have favorites already, notice that the sorting is still the default sorting, when the favorited items should be at the top of the list instead.
3b. If you have no favorites, favorite an item and notice that (sometimes?) it does get sent to the top of the list as it should, but after favoriting a second item the sorting gets reset to default again. 

**Expected behavior**
Every favorited item should be pushed to the top of the item list. Favorited items should be sorted as default while still being above non-favorited items, and non-favorited items should be sorted as default below favorited items. This is how it used to be a few days ago, at least.

**Sim Links and Screenshots**
It still happens even after resetting to default settings, so no specific link is necessary, but I was using the warrior sim (https://wowsims.github.io/wotlk/warrior/#). I did try it on the druid sim just to make sure it wasn't unique to one sim and it does happen there too.

![image](https://github.com/wowsims/wotlk/assets/103959912/c7b7371f-d754-462f-97e0-b9bc9f2f70a2) This image shows the list after favoriting just 1 item. The item goes to the top of the list even though with default sorting it would be second in the list. This is the correct sorting.

![image](https://github.com/wowsims/wotlk/assets/103959912/8b116b83-956e-4979-9ab3-a518f478beff) This image shows the list after favoriting another item. The list goes back to default sorting as if there were no favorited items, but the items still show as favorited.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 116.0.2
 
 - OS: Windows 10
 - Browser: Chrome
 - Version: 115.0.5790.173

**Additional context**
[Here](https://wowsims.github.io/wotlk/warrior/#eJztVV1oHFUU3nNmM7lz2HRvxpDOjqSOg+g2Gpjd6RYi6N70pS2+tBZKWvoQBUuhLV2yLzFPQRK0Ik2h9KFR1FYfAoItgliDSEnbh9C/YCBKn6JRSUihMZISjBrPndntD42W4vathz177/2+c8799sy9s5QTmIUAO6EL9kEJe6AP4B3AYYAzgOMAPwDMAMwDLvESsQ9hU8ZDBVugE0ocCUcBPuYPwhSgnXAv0Vtgbjvw2ptvdIt6abnzQGl55A90Zlt88+IoTq4gWfLYNPrG1StIKXmUuakW3zj9tV598Cc6l4RvXONVWr7H3BLnMXc6Ar5bQGdgnW9ejQFb9v+OzvmUb8URcdDgDFaBL2OAy9xsuZ2Vlr9xmeXm24Alh3/GWIElF2Yr06Sc+zX6vqZTJjnlyt1SLk/fA1jywgJGuv0GgUHDtmSn0aP7cwoXkc5h4rH9L7ODh83otQQ46OnT2V2m16U+qR52xOTLams09nWo7TGyS+2KJ+2KLwJULgKchBjdoPhKjIBDKIA9yW6w17Gb7PXnANwGK665U0nw4F3IhkE+yIc59jDXFgaFoBAGAQ8BY7lCmMtH80LuJ3DERxMohybQGZ5Ab3Y8le2fwOCbFZwBnAdrCL4FcmmNONzsrVQNbBFrE4rWkiH6u2wZA46KhqkuRWkmVpqqkYkEOZQUJ9/GVUJ1ja8aqsQLMeEdUCT5FhwbwUoRHcqI+PuWUS3bpOhJSmtkFXWhckzPHMXPkBrJdLlzTqNfT3VktOXK1ERit8nVLk4aviCetYXtd9Dl5btQ+3kB7nOUuY7NNkq+mmJuAV0iDtjIbT1Y5nmEadZ+1n2GZOsaYdr4YsLlEoRh2ZX39bDX7aFX7K3ktDaLpG2NYEWNG0ncUCjfy7CiO8wTX8B9BfPrKRUJ0f3RMoXeXLec6t266DFVu2Bn3LVknQLNj41AlMWjzroOiSFM+MeN+EhNlVRjtdWZoRPaxortMTJefHpvZJPF/C9YujGIvebmQ90HD+33djhm6yN+9WQPq1qU6Ru78IA6O/6LV2ff39tRCx2rWdznndOqssNS8dXolX5+MbtncLROPTUwt/3sur+Ktd11vrjlx96mzzfPFm/pbRYTKtpmYLmoV9k9oOKnnlT/VoGDOePDGuuqndnB+uinZNSnpZfo+09S6kEZux/6T+AfJeY8Nw==)'s my settings just in case it helps. I used Chrome to test it on default settings. Let me know if you need any more info.

**Comment by kayla-glick** [comment]
Hey @cfedey thanks for reporting this! I have a PR up to fix the issue so it should be resolved in a bit 🙏

**Comment by cfedey** [comment]
Looks good to me. Thanks very much.
