### ISSUE TITLE
Crash Report 1453678083

### ISSUE THREAD

**Issue by nezrim** [wowsims/wotlk#3533]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztU01oE0EU3vdmUzZjY6ahyBoSiYtgEAqTXQJ6KLt66jHqpYiIHvTkIQhC9VSFqvkBK4jQIAgq4kHEHgSLlJS0RXsrxd+mBOlB4g+Yg4XSi77ppBcFIdhexI9heN/3vTfz2H3D91goUOJ+GIBByOMwwCjAB/zOngBOAcwDNAEO9ViQQgkB5FQWPASIGfEHXZehK3f21IXT5yxLQHwJeFQsjjL7a9Lpmq3h+ATysLhfZg5TYbdYIm856bDnHxWbKTG7SOwdeVHRIG+V6ihTCRFRJ/t2zDGJGYqSfzPhmOOKxsRTcm8knDBRvUi7Umb21eS6NqtPiYoSabcS1M5Eu51mqd1OWDQKTN9uikcFRvsk7d3iMZWsJXWSKe6UlTNWZE7EAgk5czA0BNcA7uIK8ik0/uOvEJOdVly0LBBoYx7cOO9V05umyRxQk/kSzlNCEEduFGFvNiNdV3oZN+t5GY+CjOd5WU9mKOzrc2VWSiLuMtjWqyqKehXt91VMrTUwPb2A8sUCNsFswbYKJHicb7cKO1I/NgAxS3fTG9QwyiPcVJc6Ic44uIX2VLjBIhgVNJwSC2vlRNCzUbazMqYw5x/Qyry/+8w63vhuHVNH7dC+LZ6u1qVgM44ZnpvZlHO2AvrbTn4LDmq+6p+EI398tyNfDj/bNVL3p1fSx6/XXvtabfm/5vXzt/fy/Z99/Rc//eb/6+j83R7ruOInkyuqHw==

RNG Seed: 4286387242

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x114ce0, 0x163bde0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/druid/balance.(*BalanceDruid).rotation(0x20b7200, 0x211e160)
	/home/runner/work/wotlk/wotlk/sim/druid/balance/rotation.go:75 +0xc9
github.com/wowsims/wotlk/sim/druid/balance.(*BalanceDruid).tryUseGCD(0x20b7200, 0x211e160)
	/home/runner/work/wotlk/wotlk/sim/druid/balance/rotation.go:17 +0x2
github.com/wowsims/wotlk/sim/druid/balance.(*BalanceDruid).OnGCDReady(0x20b7200,...

**Comment by jarveson** [comment]
#3539 should fix it once build bots deploy
