### ISSUE TITLE
Sigil of Hanged Man Proc not in Unholy Rotation

### ISSUE THREAD

**Issue by ryancraigdavis** [wowsims/wotlk#3550]
**Describe the bug**
Currently while the Hanged Man sigil and proc are in the sims, the legacy UH rotation does not utilize it. If you equip the Hanged Man sigil (while specced into Scourge Strike), scourge strike is not used (much less efficiently)

**To Reproduce**
Equip the "Sigil of the Hanged Man" with the Scourge Strike talent and select the UH Legacy build in "Rotation"

**Expected behavior**
Scourge strike would be used, ideally every 15 seconds to keep stacks of the buff

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EU3veyxuxiyRhyWENT4p5CITCbtaAHmdWLHmN7KeJBDxYPHoonrZcgFrQevKi0ERWsSLxYL0oEhdIqGFAIIWlBQe0PklBLQqQYin9vdlPwUhq1evJjWd437++bmTe6GUCGHE/AIKQBsgAPACYBCgAVgCZgAXE/iyEHB/op5oIbE1IiV/3nwJ86eezM8VMBYHpkDvQgW15Foxo1/Y+msfgYdY3NN9D0SXMbq5HvfdT0TbjsySc0PrdYkC2Rr0l5N/NIn97B3i2iMdxlquRWiH4k/5VOUy1KGmTPqapGrrsfUOaHWLWBRi1qajPf5ULRrXmLSlzrNP20MOFqebimRWNvF8iUnVRWacj/vUUpKkuispE1iT8zlV0f8ZnBAPKO3ZBS+9XT8iRu4wrqk6j8xx8hxH81Y0gNgIGrsEs3aHzBoOE8CCnIAbyQo4t1gIix3Yutixh0Kxz2tXKdEUgk7CTntt3DCclE0uaWzW1O1E5aPRYtWmRbtmXbROfBCNwoIcuUaKBKGBstYXy0jHysjBVQ67A1A8oUKq9ByaBiXvJpbpv0gNMSEHZ2ZMYk8mKPt1IQOwdczIjkG4z1GVu6//IUxS86m1EmnX+2QZ2+TenzO/DO9mnNaV10UxyFXvd9Tq/Ej1ye0pzZ8cG9+uyCaLeid2tV4eWX18mri1zX8NKh3DfR6xoV4eV9FXdku/GKCN8/MDcUbqzb96wbcL5tXf8aIf7qpUTA8Xb0ZUOlh1svut72nn4A35/OoQ==
![Screenshot from 2023-08-22 23-43-39](https://github.com/wowsims/wotlk/assets/7506851/08a2eb03-8c70-4124-b4db-8786cb90b625)

**Additional context**
Not only should Scourge Strike be used, but it should be used every 15 seconds to keep up the buff.

**Comment by rosenrusinov** [comment]
Legacy rotations as the name implies are now legacy. They won't receive any more support from me (i created all the legacy rotations for unholy dk). We now have APL which is much better for working with rotations and there are already presets for SS based rotations that work with the sigil.
