### ISSUE TITLE
Deathknight/Unholy: Glyph of Disease doesn't reapply CF/EP

### ISSUE THREAD

**Issue by Skurrio** [wowsims/wotlk#3553]
**Describe the bug**
GoD doesn't reapply CF/EP

**To Reproduce**
1. Put 43 Points into Unholy to unlock EP 3/3
2. Activate Glyph of Disease. 
3. Disable Settings Debuffs Spell Damage: EP
4. Use APL Rotation with "Not DoT Active Frost Fever > Cast Icy Touch" "Not DoT Active Blood Plague > Cast Plague Strike" "None > Cast Pestilence"
5. Simulate
6. Results > Timeline. Scroll down. 
7. Ebon Plaguebringer runs out at 22.19, FF and BP are not running out.

**Expected behavior**
Ebon Plaguebringer should be reapplied by GoD.

**Sim Links and Screenshots**
(https://wowsims.github.io/wotlk/deathknight/#eJzjYnBiEGKQWsnWxMgWkJNYmVrEwS7AJXWbkYtf4MMEZomXskps2w4zbd3JxMUpsHUVsxLzJSCTR+ATUO6BrBLzVjBvz2cmie9QHr/AO6DcD6A+IA8kwCvwuJtZolVOieX8TiYGLgGBz0DuFBkldog8A1DHnm5mJc5LYO56sBEfgUa8BxoBFLv2HySwaRWzxDQZuJmcAq09ULdwCtyZBWWyCOzuZAaS+1YxcwkJXG9mllghpcS58iQTBHExAOVmdzErMSxi+srEdYCJYRRQBIQMSNVRxfCLUZtLgoNJgFGC0YHRgzGAcQcj4wlGxguMTB8YGaX4BSHqPtgrMGoxGDB2Mcrp6hoZGwCRsYGpgYGxkaGpEZACQhBpYPyIUYJj7hUmgbdPmSRmXWFSmHGFSWPGVSaDmVeZXjCyfGBkn8XIcIjJdQEjo5CElBgXjxIXF4cRGxcLx/Z1zFIg+vdZZiEpKQkkmWVAGQ4uNo7GNmYFRiEuKQ6wulm9zLcYGWYxMSjNZeYEu7EhzQHqWhEHyVkzQeCkvSVE5IK9YhoYXLM3estUMKe2iicgsSQ5ozy1KFvByFQhWIJDi8bp70OjAzWMaTh5hBJzDCy0Chyp4Q5sABzYDdMeOUBteGHfwcgYBM7azn1nBRtSOBwcZk0Q+yH5zZ5YI5NYPkfuOHnV/rvQ1OXXQi7adwZU2HnMv4qm/wOcf7Dm7Pbvm3/Z10+Rt3WcweYw/43632gODocTAk4zL5T+INrewQaEDC4obrywT1DOgVgdUSQXBgAYSb3F)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.57.53

**Additional context**
Not being able to reapply CF/EP in the Sim makes it impossible to properly sim GoD for UH, since without CF/EP applied by the DK, the Shadow Damage of SS will be lowered.

**Comment by rosenrusinov** [comment]
You can enable an external application of CF/EP while we fix this. You can do that from the debuffs section (you will find CF/EP in the spell damage category)
![image](https://github.com/wowsims/wotlk/assets/5707996/7c968ef5-c300-4206-8940-9a056de880af)

I'll still fix it to properly reapply with pestilence anyway
