### ISSUE TITLE
Crash Report -1455767490

### ISSUE THREAD

**Issue by Fisper** [wowsims/wotlk#3557]
Link:
http://localhost:3333/wotlk/mage/#eJztVF1IFFEUnnNmXe9czb3OloyTG7tTxLIhze66YL7M5lM/BJIv0UtYKFE9LBpEQmC9lPYUlOFisdRL9SAqQQhBi+SD0W7qQ0WSrD+JlYWsCSmE3ZnRiAxDUuihj5m593znO9+cGe69tIRgOeyDDH4R7wF0AiYBBgAygFMAlZSAAn6IwhGQBfUWuQTOqjM152vricREdQSoi12fQ2Xaozn7erGvB6nEUhnUxGE+zWc3eW7Mo4l9VvRkFpUWHnXxyMVaee6rWdeDpngT+5ZFpV3WHJwQKGOjE6h0FGu5PHxtMi72KouaxMMu6+LEDW5xmVsM2xYuNsItEsWWZ5fVy6NxtN8usYuzS2052FzWfKbHzaZu86YWPMuZVNaUfh61pZqTgA5VOXdwDmkShf/4K8j6WisaJQIMY3xZQuVWmk+gDezE/qiaR5A5lGOa4G+FFtgVCus6v8PhoK7r4VJdj0R0TgUtjk8i4WDIJMKR4BgoZDaFbDGFyv136J0YQn9mCPW3Q+aan4G8OAi9mMAEgLxT3UFZoIA4ZawQVCd1UIw0qIwWkOYi7+IyQC5SN/+q0xsqBLlEVVfy5kg6OkXLXZUVKnWDSSWGkeZ1A6FOc+oFS3f1Bcq71VK6XfbRfI1SEjLZZKdICwMukiPjAUHNpTlUDIZsY56St6jun0x/+PgIqB7qDhQSh1UnxdFMfUzbkvk0ytu4xG7Zllgtl9nOXCdTlVjzwTQ2L+2IsugbEOIoaNdEySKa6qLF8TYT/cYeWzNg+OosvDRCHzDWfqFRqqo5e+Lkudr6095qhQQ2eHv5m6PrYdPU//QPPtWr5fXyQGzvevTxO1h/ukkejS69Ycq4AnB41ZPrwUH3/N1Pg0bylHsydui9YbMzxrPJh48XxONG6rmJ6RXjRn3Cv4q1n1xH11zxHaqm6uw=

RNG Seed: 326234110

simulation failed: Active aura during reset: Reign of the Dead H
Stack Trace:
goroutine 4653 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x9e
panic({0xfe5800, 0xc000611e20})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0xc0006a6630?, 0x27d64eaffff?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:123 +0xea
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0xc000b284d0, 0x27d653bdb00?)
	/home/runner...

**Comment by lologarithm** [comment]
This isn't reproducing in the current main branch. Try downloading newer version of the sim and see if this is fixed.
