### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by Tekesh7** [wowsims/wotlk#3562]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=45608/branns-signet-ring
https://www.wowhead.com/wotlk/item=46322/branns-sealing-ring

**Comment by Tekesh7** [comment]
Cant find them on rogue sim anymore.

**Comment by rosenrusinov** [comment]
![image](https://github.com/wowsims/wotlk/assets/5707996/cc3cd1ff-4666-4524-b54d-434facdd6c09)

Both items are there, check your filters its probably something on your end. If you still don't see them try Restore Defautls from the settings menu
