### ISSUE TITLE
Dynamic weoapn change during sim

### ISSUE THREAD

**Issue by Kebaber87** [wowsims/wotlk#3566]
Problem is we follow, we think as Arms Warrior, would bladestorm make more dps when we have two slow one hand weapons equipped. A
unfortunatley we cannot change the weapons during the sim.

**Describe the solution you'd like**
Now my idea would be, make a solution like the "time planning" of the cooldowns.
But let us say by 50 secons take this weapon with this entchant, and by 56 seconds tak this weapon with this entchant.
Please make the mainhand and the offhand as two different fields.

**Describe alternatives you've considered**
We can make a sim for 18 seconds with 2x one handweapon and a 18 secon sim with one two hand weapon.
And the calculate manually, problem, we can only see its better or worse, but we cannot see how it works in a 120 seconds fight, with the weapon change.

maybee you can make the two empty field for main and offhand , with toe popup from the weapon.

![Git HUB proposal](https://github.com/wowsims/wotlk/assets/143223350/cd7c1f79-eb29-45c3-a7ed-e4c8b0d35d7a)
![Git HUB proposal window for opening](https://github.com/wowsims/wotlk/assets/143223350/19f74024-e9e4-4461-9f21-cb98f4e66ad5)

**Comment by jimmyt857** [comment]
The way we would support this is by adding a weapon swap action to the APL.

I'm not sure if there will be time to do so before the end of wrath, though.
