### ISSUE TITLE
Crash Report 92748964

### ISSUE THREAD

**Issue by F-Joubert** [wowsims/wotlk#3571]
Link:
http://localhost:3333/wotlk/warlock/#eJztU0FoE1EQ3Zm/DbtrJd/1soZE44JYhOJPloX2UHf1VPQS7KVUBBXswXoonqpe0gpqmhwqqGiwttYeesjBYgULFkpoDgXB0oJYA4VEq6GIDYgQRMRJNj0qBOtFHJZh5r15s8P/87WwghwFtkEndEM/xgFGAJ4AzgMsAZQAju1WgEMYBbgQq9bAFIBOgsCUbwh8sYtnL5+/pMhcCRRA8/OxEWZ8Cpm+XBZzs6ipfDLFTDZNYTOfIK4YMtlqLVtIMmO4nvn5I+IqiumjyjwBO/n4HWY80E2ZAInSh8TfDtZTnT8j8a2gqdI/pmsfYddTzBjfa6qU5bwufp4k7G6QxvGKVL6WoHHytbCUrE8m87kEI58h38wzJPkW2mLGUoxKvyc9lakrIKANYnJ30wDQYd0EmMCvqM2j9N/+yHTRqOKKQpuJBvbDhQ7Nolg2aE9bqheEnbSrPfvoNke/oPGSbvPFLOoyf7OJAZV/LqDJHn/EgM8TDcPBqGULIaLCImfZERG1q4BlRSJ2pLXVrpJC2JEiGMroDcZX19FYWcfw0Aq2/FhGMbiCJZDLsCMNUhalRH0b2t23IKVRMt+hWgPive4ujzri7knfr9qi0+4hS87+3pq9dqJPMdxlNB2693e3qjzobkeb+OLCtvRpxLwzm9t0j3p5xTkDJ3/7DvuwMnO645VzKj5z7tqHguOhZWeL7/KfmDwAy87hq88zA++LTnZNO57f2HB+1e9ftcbfYU/Dip8F96vU

RNG Seed: 3949520332

No item with id: 47517
Stack Trace:
goroutine 180 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x9e
panic({0x1812020, 0xc0005d23e0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.NewItem({_, _, {_, _, _}})
	/home/runner/work/wotlk/wotlk/sim/core/database.go:199 +0x4d4
github.com/wowsims/wotlk/sim/core.toItem(...)
	/home/runner/work/wotlk/wotlk/sim/core/item_swaps.go:271
github.com/wowsims/wotlk/sim/core.getItems(_)
	/home/runner/work/wotlk/wotlk/sim/core/item_swaps.go:258 +0xb6
github.com/wowsims/wotlk/sim...

**Comment by Tharre** [comment]
No idea what caused this, but that item is definitely in the sim and I can't reproduce the issue.

Possibly just a old version?
