### ISSUE TITLE
WOTLK Shadow Priest Simulator

### ISSUE THREAD

**Issue by Belicicily** [wowsims/wotlk#3579]
**Describe the bug**
Shadow Priest Simulator no longer allows me to select or change offhand equipped in my simulation model.

**To Reproduce**

**Expected behavior**
Should show offhand options for simulation.  Works for me on other classes, and used to work for me on shadow priest.

**Sim Links and Screenshots**
I took a picture of my screen with my phone so you can see what I am getting

**Desktop (please complete the following information):**

 - Browser: Chrome
 - 
 **Smartphone (please complete the following information):**

**Additional context**
![image0 (8)](https://github.com/wowsims/wotlk/assets/143662776/890ced13-b964-4b0f-a545-82581597cfe6)
![image0 (8)](https://github.com/wowsims/wotlk/assets/143662776/5106e84b-b61f-4db4-8588-d8b4561eef26)

**Comment by Tharre** [comment]
You have active filters, disable them and you'll see offhand options again.

**Comment by Belicicily** [comment]
I turned off any filters..   I had alliance only...  still can't see options.  
Are there other filters?
    On Wednesday, August 30, 2023 at 04:30:06 PM PDT, Tharre ***@***.***> wrote:  
 
 


You have active filters, disable them and you'll see offhand options again.

**Comment by Tharre** [comment]
Go to your mainhand and make sure `1h` is selected.

**Comment by Belicicily** [comment]
Perfect.... I had 2 H selected.   What a potato I am.
Thanks Much!    On Wednesday, August 30, 2023 at 04:58:17 PM PDT, Tharre ***@***.***> wrote:  
 
 


Go to your mainhand and make sure 1h is selected.
