### ISSUE TITLE
Suggest Gems - Meta gem activation not prioritized

### ISSUE THREAD

**Issue by Kood650** [wowsims/wotlk#3583]
**Describe the bug**
Suggest gems is not prioritizing having the meta gem activated.
ex: in a set with only yellow and red gem slots nightmare tear will not be selected.
If a set has a blue gem slot nightmare tear is selected.

**To Reproduce**
1. Go to ['set link'](https://wowsims.github.io/wotlk/feral_druid/#eJzjkuRgMmCyYExgLGBqYGRcwch4gZHxASPjC0ZGJ0EORgUmB8YCxg5GxgVgOSGgSqm/rE2MbAE5iZWpRRwcAoxStxm5+AW6epklXsoqsW07zLTyJBMXp8C7KcxKzHt3MnHxCHQA5R7IKjGDJHgEFv5hkpgqA+HxC/QA5X4A9W3dyQRSzCuw+gmTRKucEguQx8AlIHBgKrPEFBkldiB3K0iEX2BzH7MSJ4QLRECBTqAR7xFG8AtMAOqZJgMWAKngFHjUCXULp8CeqVAmi8DuTmYguRxICgm8BGo5K6vEuRVuLgNQbkYXsxI7MHxYgCGziOkrE9cBJoZRQBEQMiBVRxULB6ME0yZGHS4VDiYJVgVGDUZbBoYGBwdWD7kZjMyxDAw3HAsYGxjlljKePXPGVopFIEWBsYtRU9fU1NjIwMjQ2MjYyMjA0MDA1NgQSBobGBsamBoa6hoZGJsCeYZGjxglOL6c5RFYAkx5R/czKcy6yqRx/BKTweFLTC8YWT4wss9iZFLgP8TEcIuRYRYTg9JcZk6wwxrSHAQhThRxkJw1EwRO2ltCRC7YK6aBwTV7o7dMBXNqq3gCEkuSM8pTi7IVjEwVgiU4tGicmD40OlDDmIaTRygxx8BCq8CRGu7ABsCB3TDtkQPUhhf2wJIqCJxPd61ozyhhZ3YoKniVlCPH7EBdiz/Yl1memBW16ae9y7KqnZGr/9jPaNFfFKn71/4RW+KVtYYsDjfiL20X/PLPnrr20g8IGZSdAQEDB2J1RJGcswFyfLii)
2. Click on 'Suggest Gems'
3. Check that meta gem is not activated (no blue gems)
4. Replace any gem with nightmare tear resulting in a significant dmg increase (+- 300 dps).

**Expected behavior**
Meta gem provides a big dmg increase so it should be prioritized having it activated. Some math is necessary to check which slot color slot should be used but feelscraft says it should be a yellow one (hit and exp caps in some sets might make this not true).
Either way, using a red slot or yellow slot should increase overall dmg (citation needed).

**Desktop (please complete the following information):**
 - OS: WINDOWS
 - Browser CHROME
 - Version: cba

**Additional context**
Related to this issue. - https://github.com/wowsims/wotlk/issues/3257

**Comment by BorniPL** [comment]
The functionality is not ready for Phase 4 yet - that's for sure. 

Do you know what hit/expertise/arpen/crit cap are we going for in P4?
I don't.

**Comment by Kood650** [comment]
This doesn't seem to be related to hit/exp/arp caps of phases. If you look at this set with only phase 3 gear it still does not take into account meta gem activation, [set link](https://wowsims.github.io/wotlk/feral_druid/#eJztU89rE0EYne/LJt1dWjoNOYwxiXHxUMXC7C4BPYSdemmPUS8iCBW0Jw/Fk/a0FQoigheVmpPaCh60FLVSD/7AKhpoIMTYgqcYtY30kAg15KDg7G7/AIPRk49hmPfezHyPYT59p4ocD0AOx2ACXIC7ACWAKkAd4NCACmkU0rjpG0sAURJvhS9AJHfm5PnTZ9UIhXgJ9H76ro3sa9KIPF7G2hPUNVppoBFalMteWpJeNWmEKj679QPZtUTgRWm5haydNDTpLfpD76P315HdSxqK1IhOaUFuuZoweqS54Cn99EodDW3Bp3LoPfRyDVkjKZ0vDWTXE0akEjgafdbCoLBGqxty6akK3Vz35tUNL8/UN2TF7XREqo+20OiTj6LklGPKObgIcBu/o/4CyX/8EaK80xOTigoMH8B+fY+KFFg4DYOQJcQVIjyamgHlBCFvh11I3YHiyko2rtBTabgEe4cyGdvilmlbtmVxk/OMbcrZ5rbJM6Y5ZHE7I5lp1YCpW8VeOvcZ2evnmM6/x8E3ZeTLZayD0gQ1D+Qlkg9A8kiMT6j5sdxxMRAEjIkd+RseCs7BQCk5u8d9rDrWQ0wfZeF9M3/35zSnRDeucQuvunJPJwje7GlDDAe87YzBEb/XbB8hsWt68/BSKtTlZE0nNj/ycTKmiLXZiay+BmJUsvmRn86cR2eJ8MtOd7vuv8N2r7lc/O6J4x135y/M+an9), if you put a nightmare tear in any gem socket you will see a dmg increase.
Anyway, there now seems to be a warning about the meta gem being disabled (maybe there was one already and I was blind) so thanks!

**Comment by BorniPL** [comment]
I didn't read the code, but I can safely assume that it tries to fit it in the blue socket and in this gearset you lack one (it doesn't consider prismatic socket as a blue one).

**Comment by jarveson** [comment]
this looks fixed at some point, linked set will suggest one with nightmare tear
