### ISSUE TITLE
Feature: Export all from the Bags to a JSON (File) - Problem: Don't work in a private server the addon (import)

### ISSUE THREAD

**Issue by supermavster** [wowsims/wotlk#3592]
**Is your feature request related to a problem? Please describe.**
On private servers of WoW LK (3.3.5a) when using the addon, it doesn't work when pasting the generated JSON into the page; From here a question arose: Why not also export everything that I have in the suitcase, because I have much more equipment there that would allow me to improve my statistics by using the appropriate equipment that I have in the suitcase and not equipped.

**Describe the solution you'd like**
Export all the objects contained in the suitcases (bags) of the character in JSON format AND that it works when pasting the JSON generated in the page.

**Describes alternatives you've considered**
It can also be saved as a file in the WTF folder for private servers (3.3.5a)

**Additional context**
If they test private servers, NOT Official ones with version 3.3.5a, the addon works, but the page does not carry out any process when importing this information.

**Comment by jarveson** [comment]
Private servers arent supported, theres api differences in the addon and prolly its dependencies which would make supporting both a pain

Also the sim itself is targetting current live 3.4 wrath, which may or may not match the various mechanics of a 3.3.5 server, which makes the sim much less useful and would need potentially *more* workarounds to match private or legacy behavior
