### ISSUE TITLE
Crash Report 639492543

### ISSUE THREAD

**Issue by Netrido** [wowsims/wotlk#3616]
Link:
https://wowsims.github.io/wotlk/mage/#eJztVF1IFFEUnnNm2maOltebxXh1S0ck21id3W3pl3bzyaRC6kWCoIjqpYfIh6iHsCiioqcMcomQHsIiQn3TCET0QSLLorAi8adfklqV6OehuvOjBYUg6VMdZnfO+X7OuXtn51K+jqugAgawT2sEaAJsB7gPMAD4BqCcdDChBJJQDVwR34zjEKjav+vwnoM6MVW8BcpidR/RHAlaga4O7GpFMlhjGi31mUwz2UXJDQUt9YlbdZ5VzTN+lcUaRtH8LH3Nra5vHns3huYlbmnSqhBjJyR/M9eaK8lbrySSxUY+oGXIstm9JHBBtj/ljG7FPhd4mUZzzAOa3ZH9r9GsXTyxnJOjXuWINZYadr5bhh3m8jiaX4OezmANn3AifT8oU9nLkjthQ5VWre2EK/gRqR2V//FXwe3pOo5k6sDwANQ6f1QozyNZ14PHbUyKDB0ZmrstpeQGnoHl0Zhty08sFrFtOxa27XjcllDExWQSj0WiDhCLR4YgRx+/i+z7XTSvvcSCOw+w5MUD+QaoachIgdKB42oDAC0kXQRI0282qZZBc2lOOFq6qoYWUEBohGa2D0ZKV9ZMant78BeY5wtBLDRfn8OxUnEEhPGaiaZ8i9hE5TxJ2aEsXeO4VRHSSGosXkymWERGC0glu31anUhvyNQRe+1ccdTrx863IQ+KPJdW/0yvFaupjIf9ZnrDM6SMFtAp4KQFQAtC2dJqXEeHPXsPhb9mJ+dlIkxFvJAyLSI96qDtTb8tJhL1fpykeKWooPV83a/TRMh0BrS5wECjJowU+ps29XBN4BqFLxFBV6a5A33vux50ZV96kEdEGRWHinxBXguaOvCfM4Tfvde3SCsnMfncTvvv+IrkU1BSqFjnVMMFavcmsz0qJ5mbqneiO7HaQ+4nCve68TgRfY4F20w9NMtnRfpYciba1HZ3zkif2Qhvbzc9T27w6s+JCtgJW6c8h3eMHdq87PxQ4mFdxtEn/YMJD00naq7OX7rvUcdk/ef7vxPTP4e3T9vxA4nR83Q=

RNG Seed: 1841160049

Trying to cast {SpellID: 42833} but GCD on cooldown for 51.354417ms, curTime = -1.7s
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xed780, 0x1bd8ec0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x1bdfd90, 0x1b88800)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f...

**Comment by Tharre** [comment]
That's not a bug, your APL is just trying to cast while you're still in GCD. Just adjust your prepull actions.
