### ISSUE TITLE
Demonic Pact not behaving according to latest changes

### ISSUE THREAD

**Issue by Tornaattor-i** [wowsims/wotlk#3619]
**Describe the bug**
Usually don't write these so apologies if I missed something.
According to the latest patch notes, Demonic Pact (DP) now has a 1 second cooldown (down from 5).
From what I've been able to tell by testing on the PTR - DP will refresh with 1s intervals as long as the warlock's spell power (SP) is same or higher compared to the value when DP was previously cast.
This does not seem to be reflected in the simulator.

**To Reproduce**
1. Use the sim-tool with a gear-set that provides many changes to SP (i.e. Dislodged Foreign Object)
2. Check the log report for positive (or unchanged) dynamic stat changes to spell power between two pet crits with more than 1s between them and observe no new DP has been calculated.

**Expected behavior**
DP should renew with 1s intervals when pet crits, if the warlock's SP has stayed the same or increased.

**Sim Links and Screenshots**
![image](https://github.com/wowsims/wotlk/assets/144148014/9f5077f2-5352-432a-9136-b2b4cd9cb00d)
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version [version of  chrome? v116.0.5845.97]

**Comment by Tornaattor-i** [comment]
Seed I guess is this: 2144856508
Link: 
https://wowsims.github.io/wotlk/warlock/#eJzjUuZgEmAyYLJg9GCMYCxgamBknMDIuIKRcQMj0wFGxguMjC8YGZ1EORgVmDQYDRgtGB0YA0AKQUqEGKTesTUxsgXkJFamFnGwC3BIPWbk4heYP4FZ4o2sEtvRQ0xHdzJxcQo86mZWYr4NZPIILALKPZKF8Y50M0t0QXn8AguBcj84lNg27mQCCfAK/ANKzxFSYgGawsAlIPAcyJ0io8QO5G4EifALbAUazAnhbgQbsQBoxAI5oNUQI/gFunuYJabJgAU2gt3yAuQWiLPudUKdxSKwppMZSO4FkjwCa4BafgEdBVF/aSozjPkHpPXmTiYlfg5wUASwRrBWMHYwMi5i+srEdYCJYRRQBIQMSNVRxcHBKMAkwVTAmCUGjDlmCUYFRlAydWCUYgPKsEowdjGq6hoZGAORsYGhgbGpgaGRKZBlbGpkBCQMdU1NDUDA9BGjBMfNp0wCc9uZJW6fZlJousyk8e8Sk0HjZaYXjCwfGLlnMRZwSXCxcCxsZxISQHHEgXgHsEznR2wyCkCZZ6uZhSSgYg4Qyh9KJ4D1CmztZIbp/bAfpvcQE0MnNFFZOtxiZJjFxKDUzcwJkU5yEIRI2TlIzpoJAiftLSEiF+wV08Dgmr3RbSaFYAkmLVonzhIHapjScPIIAXO8qWIPOQASth2HHRyhAg4JjEF4sz3Xsf9qkl1n7e/nlzyZ5/LQHiL6wR4m/2t2tXBdw2d79tVaVRXfHtsfbBfYus4AIT9SAOnZPopkHQAxrrBx

The above screenshot is from another seed (I guess), but I redid it from the same simulation I copied seed + link from:
![image](https://github.com/wowsims/wotlk/assets/144148014/1b388620-c61b-4b73-bc6d-bd06c0257b11)

**Comment by Tharre** [comment]
You don't have the 'New DP behaviour' checkbox toggled, so it's still using the old one.
