### ISSUE TITLE
Alchemy Bonus from Mixology Not Applied for Elixirs

### ISSUE THREAD

**Issue by havocedge** [wowsims/wotlk#3621]
**Describe the bug**
Selecting Alchemy as a profession for the Tank sims does not seem to apply the Mixology bonus for  Guardian Elixirs. 

**To Reproduce**
1. Go to 'Settings'
2. Select Elixir of Protection
3. Select Alchemy as a profession
4. Observe the Stats only change by the amounts shown in the tooltips for the Elixir. 

**Expected behavior**
The stat bonuses should be slightly higher than the tooltips show due to the Mixology bonus from Alchemy. For instance the armor from Elixir of Protection should be 1080 not 800.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 115.0.5790.173

**Comment by lime-green** [comment]
None of the elixirs don't have the mixology bonus. I'll update the elixir of protection to get the mixology bonus and if you need any others you'll need to compile a list of the bonuses

**Comment by havocedge** [comment]
Ok thanks. It looked like Guru's Elixir was providing the correct bonus and that is the only other one I really use.
