### ISSUE TITLE
Can't Sim Bug Website

### ISSUE THREAD

**Issue by al-mualla** [wowsims/wotlk#3627]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by al-mualla** [comment]
Have a Look Below,,,

[https://i.imgur.com/aRm5vcw.png]

**Comment by al-mualla** [comment]
https://i.imgur.com/aRm5vcw.png

**Comment by jarveson** [comment]
open the github issue by clicking 'Ok' in the popup in your screenshot. The link and stacktrace is necessary
