### ISSUE TITLE
Crash Report 281226458

### ISSUE THREAD

**Issue by Lyfebloomz** [wowsims/wotlk#3629]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVV1oFFcU3nN2Npk5+dmbq9H1ksU4JiIL0TszLmi1mVUQg1AI+lD1qX3Qpz6I8aWCkAixJk+lLaJLwdInQdu6CkICEv9CG9A0kcRqAqHGYvMgdLGKYX2od2Z2lk2WCkF9KT0Plznf+c53zpl7mKEWHRlK3AwdsA8OYzfAlwC/4wPtEuB1gDGAOYAdDTo0o4QMdHosOA/AI6K39gRUdX726ecHj+g6AzEBFGc/zmPiadKsGr6J0wNIBnv6DM2o91jLcio2mzSjOd8bfISJ/mQQi7NLKjav8lTMC9ex0WeY+JabmgpHlPuDin/TZGo5z42z35SqMTyADwI6Zy8V/YukaShPwQ99zSGFnW4qaRqs528Mqhts5s9iWxobfeydWXVWs1cqpZBUbu4PD7z6HM0aHSR0avu0UwDf4wuk6xj5397KuFxqxjFdB4YJPAx2I8W9nV2v9rHD28dfQCBF+uHjtCVt23EsK60ORzq25TgyrXzpWG3yjdZmy7SUjpR2ZWwWEvrDIWQTQ5iYHsLm7CSu//keylv3cA60PNRkoYkE1et9K5r/CQ24HjS+PHMT78S+A6BG0kUVafrwCc00qJpibc6GdFcJvl/AImyXwezrwRC2ytl3C+UwXydaiKXq9RjHDyIegTDdJVhFU01C+Lwox91FntXlC/5aQE4iqHnuBnJLbKRWsZZWpJYrtjEIXuBiX1TEKEpgk3HZQ/SJn7RwKL5aJGkZb6B4qq7YiM+VPmH8XJRnRDtt4jbVmkS67acXkFamGhU9qKCffIXFtiwyvoqWQR6Xu+JDcri1SMHrsaTQq+hhj4FAb5nALrGTtoot1MrXLkw7Gaaly+pWvCvbF3pyIcptIWkdbykn/8sgdniPfJVYSXW8ZvFg44WKUNiyuubgznj9wplLA+0WHdTOt1GdqZKzpV7Ca8MFs22iZZehYitKlfwmFuiU+iuuhkfrK37+7MwURLIYMR+j4QPdhzIN4dKvyp71bMTdEiBj7ppDvt137SvYvDcRS515v5/RfE/mXch0j9x+JzpLseCdXfsrsz3w591PYM8bfzyyO3d0w55J9/j+FwNT/ZNugObdxbw1PfnRbYlHbvvMR/m9d+cq4v91W/qP58CSM14DQ6E1KQ==

RNG Seed: 820621498

Trying to cast {SpellID: 48470} but GCD on cooldown for 159.503242ms, curTime = -2.5s
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xef040, 0x181d440})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk...

**Comment by jarveson** [comment]
gcd before haste is 1.5s, ur prepull actions are only 1 sec apart, the error is correct, you cant gotw at that time
