### ISSUE TITLE
Best gear in bags

### ISSUE THREAD

**Issue by Vizier01** [wowsims/wotlk#3633]
Similar to raidbots for retail, it would be extremely useful for average users to be able to import all the gear in their bags and preferably their bank and sim all those items at once to see what set is currently their best. This feature is especially useful because of the flood of items we get early on when gearing a character and we are not always in BiS. Takes the guess work out of these situations and a lot of people like myself would be willing to pay a sub for this feature.

**Comment by jarveson** [comment]
#1512 this is half supported through addon and 'experimental' setting
