### ISSUE TITLE
Crash Report 1700986903 - Active aura detected

### ISSUE THREAD

**Issue by 1337LutZ** [wowsims/wotlk#3649]
This error only happens when I Batch sim combinations and have Reign equipped on my Gear set. Doesn't always occur.

Link:
http://localhost:3333/wotlk/mage/#eJztVEtIFVEYnv+f8XrmeM1zR4Px4PUxbS43pJk7CRrETG56rEw3Ei2MylULyVWuJGqhEhZE4KWF1KYgwtpki8BECQnNXFh4SbqXnlh6wQcWQZ150KJFZSm06F+c83+Pc/5/DmcOrSJYDwfgIsBLXJFvAAwBjgBMCwz4DqAxSkCHBLjQBK2gKSbUA39UeBYiTaeOnTl5miCTeQZoCbu0ivqHuBEZH8Xx+0hV9vENGnJGpFF2QWi5uCGP++jhMuq9At0RSGMDedTX44YqNGH2uGKWFY6rmqEIJAnYI5ZfrghhlL1fQyMSektYnxAHK30i4xNja6hfqfjuUNn827ARha2seOOXrDdO5b1mzi2h/jlsTWWza6FVZYvZIDUIAbOoSWlVruEq0hGU/sdfhWZudEWXSoBhh7ib0FhOxY0cgEA46HKVoH7ckBK3sBd2pmzTNOtM27LEbNeKXICUaQnetoVWZ1spU8x2nZUDnSxPIrv5GvWvk1j9YgYTj2fQfDUjrr2Sh6I0SKM4CYMANEYjXKGox4xCWkDlWqtTUzjukbQKzimbw2Iqk4kTPEKFaXenN5OFKdS281Kq3gUPDmbQp/ueoLaL19IdWg2NGpSSlMeODMk0liwhBRoekrhfw0oF+whJq+JxWpqMEcWX1TSGBXzDJ1HIbyO5LTT82AblxM+fTmFPeHkb3DmQ0igZfbLqE93tbiyQytzy9IAXE05DwEw7Ne1+zDqpDFa36AXJLf4JEj3uZmzTPTH2i31aNqXOn0Rwtg+W3H0BXnfaoPmnz8tw5fmFw8PzTrar7Pb+7JwTsHmHPrvesZfec5p9w3Onf3Q1cbQ/53iurrJFZ8s/5R+LjT8vR8IV+d8+q28K2s2M

RNG Seed: 148740233
Running: 0.1.45 - Local

```simulation failed: Active aura during reset: Reign of the Unliving
Stack Trace:
goroutine 15439 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x9e
panic({0xbb6500, 0xc005208d90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0xc0071c6e70?, 0x66?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:123 +0xea
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0xc007fbc4d8, 0x39?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:485 +0xfc
github.com/wowsims...
```

![image](https://github.com/wowsims/wotlk/assets/1216787/3cb62148-1448-446d-ae85-01d7170462b4)

**Comment by vigo2** [comment]
Cannot repro on current master (91e5988bac7d2e90a32e92c86abc6603089ce697), using Go 1.21 on ARM64.

**Comment by 1337LutZ** [comment]
> Cannot repro on current master ([91e5988](https://github.com/wowsims/wotlk/commit/91e5988bac7d2e90a32e92c86abc6603089ce697)), using Go 1.21 on ARM64.

Any way I can test master myself without having to set up a local env? :D

**Comment by 1337LutZ** [comment]
Managed to install it through Docker, will try to reproduce :)

**Comment by 1337LutZ** [comment]
Closing, tried 20+x couldn't reproduce in current master
