### ISSUE TITLE
Error of sims needing target, but the advanced option button to add targets cannot be found in usual spot

### ISSUE THREAD

**Issue by CogSims** [wowsims/wotlk#3654]
Was messing with phase 4 sims for ret paladin, set up an undead cleave sim with 4 targets, all set at patchwerk, the sim ran fine, i went to change it back to mess with different scenarios, and could not remove the added targets, the when i refreshed the page, i could not run the sim with a popup error of "Error: Encounter has no targets! Try adding some targets first.", went to add targets back, and the green advanced options button is no longer there to edit the fight scenarios, and none of the pre built options seem to have targets either

**Comment by rosenrusinov** [comment]
You can fix this with Restore Defaults (from the top right coghweel button).

Its an error with removing targets where they look like you're not removing them (haven't looked into why) and you end up removing them all and then it bugs the UI with 0 targets.
