### ISSUE TITLE
Crash Report -128497917

### ISSUE THREAD

**Issue by CreamyDreamssss** [wowsims/wotlk#3657]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVUtoFGkQnqruyXZXTPLn12j7M8HYRlcGov1wwGd6FMQgLIR4UU+7Bz15EONFYWEUzO4kObi+0EGIiAdB8YmHKOIz7AobXxh3N2p2dUFyEJyLIOPB/fs1TDK4ENa9LFsM3VNffVX1Vf9FN7VqyNDCpdABG2E75gD2A/yBv6oXAG8CPAQYB1jTqEELWpCFTp8FpwF4Qryo3Qs1ndu+2bVlh6YxEM+BGtjofsV402zWDN3Gi4NIOjvVr5iK/3caey5jr5pj726fYvRK75n0GtiYjL2XeTLmA3XsxGHFOM5NVQIJ6T6T8UOpyOXsikz+IWXqQ4N47XXQibOefsX4rtnUpRf+ZNk+iR1JSTmDkZzxvkiOzsbySthdZU+K/vV6XpG6zsmUUqRSZQP9irwe61XMWg0s6FQ3qt8DnMR3SDcx8b/9I+PWVDN2axowNHA7OE3U4O/uQrmXHf5e/gQCKdELX2Zcy7Ec17Yzrmu7luvY8i5B23LttjbHyliWdJxXYGi535H9cgON325gS2EEF955jNaPj3EcaougFiBFguq1/MyWj7EB10IhM7K38efkCQBqIk3UkKoN7VVNnb6gZJu7KNNdhp+WMIKdCpgdvBrDdiV7uFQJ8wWilVi6XktyXJ7wCYSZbsGqRKWECHgKx/URz+4OCj4oIScR9hy4hdwWi2m+mEcz0zMkW78KfuBsXhFJUggc0i/5iPbkvBoPxeeIZprOG6khXRcJCbhWQHg0oPCsaKcl3KFpJpHmBOklpFnpJkkPO2g9HzCSZZN+QKmAfC73xCpyuT2pgq+xXGGfpMcawwL7KgqsE2tphVhG8/m8iWk9cVqmom/Vs3KCQq/PKNwRFi3grZXkTwzixOfIZ4tZVMdrJw/2qFQViiXLYw7PjNdPnLk80HrRQe18JdWZMrlQ1hIfG06YbQlNvwRVW1HuFIiYUKesL1oNn5aPXmdOdhQSBUyYf6IeALmt2cZ46WcXjvl2z1sWIg+9uVsDe+o5l7Flg5FMH/13X4vFPdnPUSZ37+5nqTMVC5/Z9bfZ1aH/3vsauv72Q2LlLu5c1DXifbvp3eBo74gXokVvMm/unuL9lcZLr33sq+KG4fGq+H/dpv4h2TzljL8AphAnjw==

RNG Seed: 1907897288

Trying to cast {SpellID: 48470} but GCD on cooldown for 14.79848ms, curTime = -2.5s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xef760, 0x1bda1a0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim...

**Comment by lime-green** [comment]
@CreamyDreamssss this is an issue with the APL, it's casting things and not giving room for haste differences in gear. If you change the Gift of the wild cast to be at -2s and wrath to be -0.5s it gives much more room for error and is more realistic
