### ISSUE TITLE
Is the Pet Talent Wildhunt broken?

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#366]
**Describe the bug**
Basically i checked the dps from my pet and my overall dps with and without the pet talent wildhunt and apparently the talent is not working. 

**To Reproduce**
1. Go to the pet talent wild hunt
2. Sim with points check dps
3. Sim without points check dps

**Expected behavior**
Normaly your pet should deal way more dps because of the ap it gets

**Sim Links and Screenshots**
This is with wild hunt: https://gyazo.com/b5404aabcd3bbb4008f8aeba9370356b and this is without https://gyazo.com/b550f630f662a66cb24e2f59d8779580 as u can see the dps almost doesnt change.

**Desktop (please complete the following information):**
 Windows 11
 Chrome

**Comment by jimmyt857** [comment]
It's implemented but it looks like I forgot some parenthesis, making it give 0.15 flat AP per point instead of 15% of hunter AP  😄
