### ISSUE TITLE
BIG problem with conversion of Agi and ap=rap is bugged on some Items, also % AP Buffs (Trueshot Aura for example) and Flat AP Buffs (Blessing of Might, Warri shout) dont work for RAP.

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#367]
**Describe the bug**
Basically 1 Agility should give 1 AP and 1 RAP but apparently the ap part doesnt work properly. Boots of the Neverending Path have 51 agility and 122 AP. If i unequip them i lose only 134 ap (thats because of the 10% ap buff), which means it does not include agility as 1 AP. Also i found out that some items are just bugged and dont give their AP as RAP. The 10% ap Buff like Trueshot doesnt work for RAP, it only increases AP. Blessing of might also gives only AP no RAP on your Char.

**To Reproduce**
If u want to check the AGI conversion just watch AP and RAP and use an agi gem.
If you want to check the 10% AP Buff then use an AP gem and check the AP and RAP u get ( RAP increases the same as the AP gem, but your Char AP gets higher than the AP gem because of 10 % increased AP)
If u want to check the AP = RAP Bug on some items, then use the items i listed below.

**Expected behavior**

1 Agi should give 1 AP and 1 RAP, 
all AP Buffs should give RAP unless they explicitly say MEELE Ap, 
all AP Items should give the proper amount of RAP.

**Sim Links and Screenshots**
https://gyazo.com/b67629adff63a3e5b768aec3f1766626 This is without neck, my attackpower is 3588
https://gyazo.com/55d2d0a862db240e88328d8144d0f879 This is with neck, my attackpower is 3709
Difference is 121 AP and the Neck has 110 AP (10% AP buff is exactly the difference), also the neck has 42 agility which simply didnt increase your AP (but it should). 
Also some AP Items dont increase your RAP, only your AP. Some examples are : Favor of the Dragon Queen ( its the neck i used in the link above, u can check my RAP when i equipped it), Frosted Adriot Guards, Journey's End and so on. I checked AP Gems and AP enchants and they increased your RAP, so they are working properly or rather i didnt find one that is not working, maybe you guys have to check them also.
Last problem i found is that 10% AP Raid buffs( like Trueshot aura) do not increase your RAP, but they should. Maybe some other AP % increases do not increase your RAP too, like Fine the Weakness or something? Though the Flat AP Stat from Blessing of Might gives only AP no RAP, thats why i think there could be other AP % or AP Flat Buffs which are not working properly.

**Desktop (please complete the following information):**
  Windows 11
  Chrome

**Comment by jimmyt857** [comment]
Thanks for the report, I think #369 should fix this. Feel free to re-open if its still not fixed.
