### ISSUE TITLE
Upgraded Dwarven Hand Cannon has wrong stats

### ISSUE THREAD

**Issue by kvnXcls** [wowsims/wotlk#3679]
This heirloom item popped up very high in my bis ranged items, which naturally made me suspicious, and the stats displayed are way higher than the in game item actually provides. It only gives 29 crit, 13 res and 33 ap.

**Comment by jarveson** [comment]
k wowhead hasnt fixed this yet so overrode stats in #3923, tooltip will still be wrong but stats will be right
