### ISSUE TITLE
Crash Report -1364123849

### ISSUE THREAD

**Issue by balhk** [wowsims/wotlk#3680]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVV1oFFcU3nN2Np09Mdmbq9Hxkmgc4w8L0flxQatmtoIYAoVgXmyf9KE+9UGMLxaEjeBPfBIVaRdB8UmwoIl/qBR/2qCCaVVMmuahjW6xeVBcImJYH+q9MzvLJotCUF/E8zAz9zvf+e535h5mqFlHhhauhDbYBNswA3AQYBSHtbOA1wHuAYwBrKvToQktSEOHYsEpAB4Rg9W7oarj+y07v9uu6wzEQ6AEuzCBxtNGs6r/Jg5fRoqzgVE0o+pxBjsic48bzWivvxr5D43D84Jcgp2VuQlZJ3MqXcNGX6BxjJuaTEfk8qLMH2kwtV61TLBn42jGh31uv6Rz9mocjX2NZjyo7/U1H+XQONrga159gqSx/KhydCknHakqjfXl1DWbU37O/4tGoehOYwPj6tp9Fc1qHSzo0DZp+wFO4kuk6xj5HO8V3JpuxQ+6DgwN3AZOPSXUzC6V89im5vE2CKTIAViSci3HclzbTrmu7VquY8u7BG3LtVtaHCtlWXLhPAZDz/yD7M9raPx1DZuyg7j01wdo3XqAY1CdBy0LDSSoVu+Z3fR/GMD1wMis9E28GzsBQPWkiyrS9P7dmhmnLyjW4i5LdZXgoQIWYacMZoevhLBdzh4olMN8sWgmlqzVYxy/jCgCYapLsApTDUL4vCjH9iLP7vIF/yggJxHsefwGclssp0ViIc1OzpLs+BVQiZ97oiJGUQKH4n0K0R+e0cKm+HzRSDN5HSWSNUUjPtfyCfePR3latNIK7tAMk0h3/PIC0pxkvaQHO+h7X2PRlk3xQ9EySHG5J9aSy+0pCspjSWGPpIceA4E9ZQIbxHpaLVbRIr5wctnesCxVtm/Fu3J8oSeno9wRFi3mzeXktzTihOfI54o5VMOrpzZ2v1CRCi3LYw7OjNdO7rnUULtoo1a+hmpMWZwteQmPDSf1toJm9kHFVJR28k1M0in5K46GovUUP2dOegQiWYyYOYz7QGZrui4c+rnZn1Tc8VYFyD1vwVY/hjznHDZ1GrHkjx/3s5jvTn8Imcyd3z6IznQieGe/PE9/FawnvM2w8Z0/EivTu2PZxkFv1zcvL48cGPQCNO9N5S3ozv++xnjktf79db5zYKwi/6nH9H8k30674g3ecSuT

RNG Seed: 376308751

Trying to cast {SpellID: 48470} but GCD on cooldown for 141.222105ms, curTime = -2.5s
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xef880, 0x1a26f00})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim...

**Comment by al-mualla** [comment]
Hello, had similar issue and fixed it.
 Try this Go to setting  website  chrome
**>Privacy
>Clear Browsing History
Check Mark on -->  "Cache & Cookie"**,  as for rest is up to you.

Enjoy,

**Comment by lime-green** [comment]
@balhk you'll have to modify your APL to be more forgiving of haste breakpoints. Right now, the timing is too tight for the pre-pull actions and the spell is not available. This isn't a bug with the sim
