### ISSUE TITLE
Crash Report 114798708

### ISSUE THREAD

**Issue by sneaker102** [wowsims/wotlk#3689]
Link:
https://wowsims.github.io/wotlk/mage/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1ErWJka2gJzEytQiDkYBZqntjFz8AsePMklcllVi23aYaf8OJi4WgWWvmLh4BC4BhS/KKjEvusHExS7w6ASTxA5JoOqNQOEfQNVXdjIBEReXwMdjTBKtckqMDFy8AsuA7EWSSizPdjIxAI14cYxJie3wDiYgAurcBtTZK6fEtmkn07X/IBveAlXv5VFi3roTZOunLyCy/SSIfAtmzzgJsrnpFJPEWVkgowPImCwLFL90mkmJC+ht1gCWCJYElkVMX5m4DjAxjAKKgJABqTqqWDgYJZicWLgYpBi6GDUNDEyNDYwNDUyMTY0MgRwjA0MDY2OggKmhLpALRsa6pgZGjxh5OE48ZRI4/pRJ4uBTpheMLB8Y2WcxMhxiYjjBdILxFiPDLCYGpW5mTrAtDWkOghD7RBwkZ80EgZP2lhCRC/aKaWBwzd7oNpNCsASrFo0TgkanAzWMaTh5hIA5wVSxhxwACdu97x0cIfwf9gmMQeAsZst1fXGB7Sf7w181YvoP/bUn1sRqkXXuD6u22L8J3CHX+voiDn0f7CHmf7OXb30NVPnVHqRLZN13exDp/vCVPdBSoM3vibZ3sAEhA7DHWtkdIOmY2YGQjihopvxAtJ8BySenDQ==

RNG Seed: 0

runtime error: index out of range [4] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x1bd8a0, 0x18681b0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/mage.(*Mage).ApplyTalents(0x24a8000)
	/home/runner/work/wotlk/wotlk/sim/mage/talents.go:33 +0x8b
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x24a8000, {0x3b3778, 0x24a8000}, 0x24a4000, 0x2492880, 0x1beec80)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:262 +0x16
github.com/wowsims/wotlk/sim/core.(*Raid).applyCharacterEffects(0x1aef8c0, 0x1beeb80)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:343 +0x4f
github.com/wowsims/wotlk/sim...

**Comment by al-mualla** [comment]
Hello, had similar issue and fixed it.
 Try this Go to setting  website  chrome
**>Privacy
>Clear Browsing History
Check Mark on -->  "Cache & Cookie"**,  as for rest is up to you.

Enjoy,
