### ISSUE TITLE
Blade Warden Enchant

### ISSUE THREAD

**Issue by al-mualla** [wowsims/wotlk#3694]
**Missing Blade Warden Enchant**  
Not Found

**To Reproduce**
--- Not Found ---

**Sim Links and Screenshots**
--- Not Found ---

**Desktop (please complete the following information):**
 - Browser

**Additional context**
Scroll of Enchant Weapon - Blood Draining
Use: Permanently enchants your weapon to sometimes grant Blood Reserve when striking an enemy or inflicting damage with bleed attacks. When you fall below 35% health, Blood Reserve restores 360 to 440 health. Lasts 20 sec and stacks up to 5 times.

Manythanks,

**Comment by jarveson** [comment]
duplicate #2714
