### ISSUE TITLE
Bonus Stat haste does not provide spell haste

### ISSUE THREAD

**Issue by Undertoe** [wowsims/wotlk#370]
**Describe the bug**
Adding 100 haste does not provide spell haste.

**To Reproduce**
1. Add 100 haste in the "bonus stats" tab
2. Note: "haste" has gone up by 100, "Spell Haste" has not.

**Expected behavior**
Spell Haste should go up with melee haste.

**Comment by Undertoe** [comment]
More weird is messing with the haste values "does" appear to be changing the ret rotation, which means GCD on spells (Judgement, conc, exo) are going down in some way, so it almost seems like it may be a character sheet issue? not sure

**Comment by lologarithm** [comment]
its probably only updating melee haste, ill see if i can correct that

**Comment by lologarithm** [comment]
Ya, that stat is actually just melee haste. I can update the names to more accurately reflect the stat that is being impacted.  I don't think we want to make it automatically update spell haste when given melee haste as I see value in being able to set them separately.

**Comment by Undertoe** [comment]
We don't have a way currently to modify "spell haste" can we get that added?

![image](https://user-images.githubusercontent.com/3249986/181859345-1db495c3-b26a-4f67-add9-e4ad10c45448.png)

**Comment by Undertoe** [comment]
Also: 

It looks like to me something is still modifying spell haste.  WIth the ret rotation there are 0 things that should change with melee haste, however at certain breakpoints there are more spells on GCD (conc / exo ) that are cast as this stat goes up: 

Below is with a gear with 390 haste baseline, and +200 bonus on the "melee haste" increase
![image](https://user-images.githubusercontent.com/3249986/181859515-e54852a1-e136-43e5-9369-19c554c7e45b.png)

And below is the baseline gear without the +200 bonus haste
![image](https://user-images.githubusercontent.com/3249986/181859657-ac1dc9a4-6698-4c6b-89a4-3bf9a46236a0.png)

+1 consecrations can only happen if there are more GCDs available, so it appears this is definitely modifying the spell haste even if its not appearing on the character sheet.

**Comment by lologarithm** [comment]
Could it be a mana issue  -- with more melee haste you get more mana back and so can cast more?

As far as adding spell haste to your EPs ... we can try it if it helps increase damage it should be there

**Comment by Undertoe** [comment]
Mana is never dropping below 75% on our sim so no its not a mana thing either.  It can only be that theres more GCDs.

The issue is that we're trying to also correct the rotation where you should be delaying hitting some buttons if others are coming up because doing so would be a dps loss.  Currently with the base line setup, you **Lose** 15 dps by adding 25 haste, because this hits a weird breakpoint where a higher prio button (CS / DS / Judge) is being dropped because the prio system hits a consecration (much less damage) instead.  We were trying to correct for this (which is intended behavior) but that's how I was lead to this bug.

**Comment by Undertoe** [comment]
Its either adding spell haste OR melee haste is also modifying the GCD for spells which is probably not intended.  One of the two are the only things I can see happening.

**Comment by lologarithm** [comment]
closing this for now as we solved the first issue and have moved the discussion to the discord channel
