### ISSUE TITLE
Crash Report 867621506

### ISSUE THREAD

**Issue by Laxdra22** [wowsims/wotlk#3713]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVl9oHGUQv/n27rI3bZLNl/Sy+bjE64JNXE3Y2/XMXUX2jNa2inKmqMU3RfNQLZXei/ZBDl9q4oMGi8W0KgaJVQvWA7FqgzFGMcXGs61FrRy2qTUEA0cwJI2CfvvvLkmPSrC+iHNwO/Ob+c3ONzO7dxgRSQK2wAsAP5GFwCGAI0BGAPIAUwBdVAQZokSDBKR4VBq2A/Wx2ZpnIJh+/KGnHt0tVklVrABYK315ici/NivBz0fJ9x8SDEkzF4kivMfVtdJx7jvf7Fk/zhK5z7Vqpa+5b4HzuGUB1dK+SSIfpIqfWz5uTnD/vojiP2uZtdKRC0QJObEO/yvu3+vwv7CBc5z/UqQEhKQPJt1CQlLhF1f1SxOT1vfcrFXR4QtEXizV9x2vb0pUhLN2XO43olSLoEHavz3wJDwLMEjmCI4Q3//yj4Rqq2XsCYogkSfg4Q3YIJKtNpZNp+51lFSK1YjAkMcIMonyifVBtxE3NE2LxXVDjxlGPGbouqHFuNKuaXH+0YyYVkHaK4GOnAdZzP9MpJExIh8bI9HFk6Tt0kmi/V4gU+AvwpoB8I2ScVEWMIwiC6Jf3D8hKIgiBtuNjs54poSfyXq43hHXyvh8CY91aEaGmuwWvI62oqTWiEFKNvqsKCScUT8IEtaIveHon54Auwyh1/O+tGILjaxMoWdQHIQACpzAnAvVmYat9FrPMfQ0NqmNnBQaIG7RjJeGfl5bhjkRdBO7DZO0E0ODYMVcfEfARmUd1ucuLw/r1Fq3hCrk9BtjGeZy6AKwOcBTQPPg3X4ijJ8BGwEM5azU0icfEU+dHi6pB4dKqvVcu+rhtwVPPVZWZ4qlgFwpVjz9rt9Dh3tLsW+V1TfKaoGrYbVBBBoadW7UK1idQEhio7qujBc/Jk6fY5re7A739b3E0aT3eZoq5hySptk9eDvtwrXW5HPe0W1Lt2j548LKzsV0zYPudCFdc5rJo+lGlkCFRpfk+CYr2AsQsAl2YUamizoeyRurtjNDH2D34V10qzdPvpDLl2DeW4KOJF8hqkpuThdLZLBaWeOxn/tW8Naabmab8GaaRFkNc4q4wy1rCbFSshWJ+JXGmWE/E45LepGvBVPl5WsaQt4UvqZOU6wYegNTMUpbvIzWMKwWBspdvcltIXfRJtaI1dQ7iNR/wh6ndaVtbANGKPNcr31Klhy5FMlheg1rxnq1zj2UW5Mez3ivANrCIvap/UtP3en4T2eFH8A3QHxKvxBy3nM9qTrnddiQahp42ZJxM+kgeXN9jy1nTP0c2RPcvGv3zl2PRbfJQfVf/r1q601djTTZ8bG/ybPtSv7U0QM9t16NOiqJ0+P7J1PuHRbM7iv+D0g80v1K9vmCuRwtmnfM7z86NXzKbOhf1A8tvmkeIDtO6HdPm30zrxb/GJo2K2f778rq/wc8uGrGX++QeNU=

RNG Seed: 1861977350

Trying to cast {SpellID: 49271} but GCD on cooldown for 33.173003ms, curTime = -1.03s
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24...

**Comment by jarveson** [comment]
#3838
