### ISSUE TITLE
Crash Report -1312668247

### ISSUE THREAD

**Issue by Maver1cc** [wowsims/wotlk#3716]
Link:
https://wowsims.github.io/wotlk/mage/#eJztVVtIFFEYnv+fcZs53o5Hi+nooo5ItrE6u9uSVrSbTyYWYi8SBEVkLz1E+9DlIbSX0ggCrVAiooewkFBfIiESyQcJTY2uonipCJSQFcF6qTMXTUgESZ/qh939v8t/2ZmdsyRbxWIogxsA4/heaQVoB+wGGBQY8CtAKVNBhxw0oRiiUAnVcAyYxOe1y+CpPH38wsmzqkZlPgYklTbNoz7jNTy9Pdj7FIlGZ+JoyCMiTaK3hTbpNeReGz2fQ71BoA6BGP0SR33Ba2hCE2aLS6bTgrvDDEUQkoCNorwpy1A6LJhK34nGlr3DsafSm0K/IkaP2C0EMSbqb2WJXRyHRp9MoTNdo3Vz7loKnY9b7wNT1lJ3xVI/vItKf9yyfptAe0sjWQUTKpVq5TxcBbiP80i6UfoffxXMXGvFxSQVKJ6BWuuHCqWZROBmcLQDUZ6oIkX9hCEVtGED7AiGTFO8QqGAaZohv2mGw6agAjYnknAoELSIUDgwCRnqXD/Sn/2oP/yMOS+HseDTsHgClFlIbAGpB+OyLpPNROUeoqiP22VDI5tIgj9YWBwj6cTDFYJ6mksGCnfFlrxDA7iMZlmcE+pLURMYlkuWgWA4ttiUHeIVpJRFSZovVVUYVklcFBI5FM4nOt9CtE4QTvqsXl5M20RqmZ12tjno9KONXci8PNOW5ZXlPbyEFDG/20y9N4IksRNU4rHSHCDpvjRRqj1CS732Crm7s5WzIu4neSyXJBmEqEGL7W7/Y5lA0PlyQmLlvIzsY3uXT+M+3RrQZRPjrQrXWtC9aKsPVzjullg299o2xR7o1k4PoG37PoAswItIvi/PNWR2oq4C+z2Du92H3BJRyghfum/17iO+M/oRpBaUjOuyZhO1NdE0R8qIbm1ptqIvUuIwg5HcGjveRoKjmHNYV30bfFTM1kXXo01t34t16bMR4VzbitHofgcvRMrEP1HVqsfw0fi5g9sbJyOvmxIvfRibiDjsbCT2IGXbqTc9S3jlz38n1n4MH1lzxS+3FvKd

RNG Seed: 2168950346

Trying to cast {SpellID: 42833} but GCD on cooldown for 51.354417ms, curTime = -1.7s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xf3080, 0x1a6fcd0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x2629080, 0x1bf7000)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f...

**Comment by lime-green** [comment]
In your APL you are casting fireball at -1.7s which does not work because you do not have enough haste on your gear. You can change that to be -1.6s and it will resolve the issue
