### ISSUE TITLE
Crash Report -437901464

### ISSUE THREAD

**Issue by Calynu** [wowsims/wotlk#3727]
Link:
https://wowsims.github.io/wotlk/shadow_priest/#eJztVU1oE0EU3vd2EydrmoyByjY0EFeEUohsdg3U066ePIb2YPVkK5VCPYQiqPWS+oOmqVBBigZBEMGIRQ3iTyrFUFqkxkPJQbCFIIHaoKUpglBE1MlugpcihKTgId/hMe97733z5jHDiAGCFLvgCIRhECIYBZgAuAXwCaO2p4CvADIAi8wHLAIcbiUggR8V6AKDlfRCBJIAHs77wn4R7OHTfecHhpmizZsH0U1fTvDSmk+2z8/ifBpFB70/zst8ii2dNM1iBZ/ML5veXJyXxiqem75msU0i21lmmWihyyx8xyMLzONESleZe7Nd3sFEU2XGTZ/HedlhuSlTYppJXC1vbUm4aXyclybbTSJl9lKMV3px0HyMt7YW6FSMZ3aGWSd9zEp++Kwkgd4d51nqz7iVKrcQUCAs9Arn4BrAPfyOYga5JuqCR6m1YsRFgOKgmAQxAuz2dreJLYSn2GaFjxlewhLADx0wBvuUkKKpihYMBDQ1pKiaEgqqzAYZqwVDQbbSQsECSORBFumTLErpFfR/zWHHWg6V9Rx7AsIG7EyAIVJRIKPX0UMqfRiiV3SR2G7/7yqgGiNW9udH/F9mFrkl4BLIyUvEYXKZfmOXFd1vtCVul7GgH7SYRX3PKRMfdHUdI6tRHHGG+86cHDw7MDzkV0P+Hol0bvPt2xg1GiETXZirR0fp6owcakQfW8GcdnSyYFR2KOrsZavLyMZra463bliXeaZUHe+mfqI53YZhq+l2//NTKvUffXfp17T+jWiRyytLusVu6Bf22pPvp3JvPrpuODhXTr+SeGjvyX/Rh1qfZQ+8LenbdYL/FbV/SsdrrvgDC6jXrA==

RNG Seed: 1830263522

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0x118340, 0x1664da0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:533
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncSimple.func1(0x211da20, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:257 +0x6c
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	...

**Comment by lime-green** [comment]
This will be fixed in the pending build
