### ISSUE TITLE
Crash Report 889354717

### ISSUE THREAD

**Issue by Andros161** [wowsims/wotlk#3728]
Link:
https://wowsims.github.io/wotlk/mage/#eJztVE9IFGEUn/dmdv3203J23ODzwy2dLsuGNLuTkEHM6iXpZHqR6CL9uywlCUF7kkLSOnh2sbDdS1HIIkF2E+mykKt5yDIQ3YoC+7O4LRod7JvZ6RJhSQodeof3vfd7v/dnHt98tI7gYWiDJfwi3wXIAE4CzAIsAb4HaKUEGIQgBl2goQF8zXsVvO3x7itnLxGfKvMRoJXq7RKyD0EdJYlWqMUC6mAbd0qucT+NbC0oeKOCt17mVar5IrIRzXVuichYrVthfkC2E6vU1/0yux7UZcmB8ylkq0GqqNlBWehvaRT64YatPxZQEFIDMsvZhPGXNlgUZQgBA9qVLk8KS0gnRf3/8jeiGVvNSHgJqNgDrdUUCXAfQXZal0IP8AYciJqGYTQZphkRp9kobOEYRkTgpimMJjMStQGzKZIHRorTqG5MI7v3FuvfzGFoaQ6N9UVxTZUkSFP4FJhM/dTLFYrMr1dQD5UbI72awvGIpNVxTtUF3EVlkj3DvVSQDvXaJ1nJobaH11DfONju6Ct04JszqB3kjXS/1kCrdEpJ1EYnM6JHuJp4NDwucadHJFquI0LaPh6kNWE/UZywL4luA4fwVTRyxgjvdgk/j0E5cexnORx072pzbAGkJEp6SvY5QN/lmL8cCsRqk8O2ZK3mMjJrNZxz5LkVXcWed32YqGiJn++OX7xQ38mU8A7/AKHB2HaU6cs++U2dzs3imZnVay3bMcevxFl0feBzbBjKu39sub0KVht0bPrITOztXzkxsWgtJwJjx5YXrB95dD7dc5Q+sjocwgtraKoUOjWUt2xWIvDJ2qlv+Vdl64/MSTej8Me7+g73tLOc

RNG Seed: 813743572

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0x118340, 0x1664da0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:533
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncSimple.func1(0x221ce70, 0x0)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:257 +0x6c
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work...

**Comment by lime-green** [comment]
Was just fixed (might need to clear your cache)
