### ISSUE TITLE
Crash Report 1189515849

### ISSUE THREAD

**Issue by Boc4arik** [wowsims/wotlk#3730]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVU9sFGUU3/dmun7zytLpJ22nH1tpBxBcs8s3MzsKouxKNBISkwYu6EkPcvJArBdNTBYS0LZE8U+IbExIjAejB0XjoRACIo1wQCtpEYupignpwcQ9SELWg37fzOyy3UZDI16ML7ubeb/33u/9vjdvZ2gNQxslboRtsAv2YAXgEMCPeNn8GPA0wBTAPMDWbgaDKKEMwzoL3gfgKfFaZh+kh599+oVnnmPMBjEH1GXPHjKcXwbc9OQZPDaBZNnvHTRcQ18us79XsasDDe/suOGMKe+K8rrsORW7oepUTAMZ+4oKv8NdUwEp7ar4W9nE5fZnKvp61rUmJ/DEtagTtw8cNJyXB1xLefFH0Y4r7HBWyZlI5MyPJ3Ise27UiLub9slRQ/1O1zTNZUX96l2tNCkVOzJmuJ0MJAybu8xXAN7F60inMfW//SPjcqkVLzIGNjq4B/we6tLbu15t5ja9medAqJs1BuvCQPrSDzw/DAIvkIHvBYFUoCcDL5/3ZSilcvyr4LDKD2h/ewqd707hYHUG139xEeWXF3EeOmtgViFLgpaz0d7BPxoGnMVCVpTP4G9px6AeYiJNJrtUR9eiO6gjXyx4I9SXwJP7TLeTVCAfFOT94Qj1xgH7zePoEjFK5/2CvImzC/WFeF8LHhN5BemHI/xusYbs3HLWwfGBlE4hDEeEvUgwibjh0c+RZ4Vo1GxPanzZ0MlXiQG6k3dTVy6TsHaQQRAnfHPUiBNy3cyIyq0qRoE6Rglf15F7YgOtza1OElZ+gg4DnuSpAwjrg+ZlUsrLYgsVuU/L9Kl9jU7XkfpyPUqCdRw0cOB3jLV6HllvGC2Qzr0Vhv2LGfa3MDwmHqXNYhOt5aupN7diYedoBmFL42iCxs0Jen5EdO1Dgz8kNpPHN7Qm/8VJio2c6Y/Mxj7wR8RW2sjvu6XyNhGhbLL0iz7K8M72Uelht4UaM1D3g+fFvTTEV7VNMVmF7ckqFJsjC0VA9/B1lNFLWW3K1dMzlFxcML1is0skYEFJU9tK0d/ezm/WJUusE8/hYZhS39Hk8euXZyFVxZT7M1oRUNld7m78SfurR7SdL22KkanS0O7ILpX8T3Fwp9ORe/vffYzX9pZvB03l/NnbwrMUi2d28tfyw7F/o/QU7PjbF5+sHHu+sGOm9NIT1ydmx2ZKMVortecN7a199aDzU2nL3OO1nRfmF8X/67b0F9+TS674E5fAPa8=

RNG Seed: 2418565734

Trying to cast {SpellID: 65861} but GCD on cooldown for 40.746619ms, curTime = -3.075s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeaaa0, 0x1a6ebe0})
	/opt/hostedtoolcache/go/1.18.10...

**Comment by jarveson** [comment]
in rotation tab, change to auto or reselect 'basic p3 apl'
