### ISSUE TITLE
Crash Report -789595042

### ISSUE THREAD

**Issue by Restomagus** [wowsims/wotlk#3732]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVV1oHFUU3nPvZjN7zM/NTbqZXDZxHbGJow2zs65JKrJrtNYqSmxRi2+K5qFaKt0n+yBrfZBNim2pWkzrXyzBVkENKok1GOMqREhY7c+DhVAblRAsBEpJqEK9M3dmNz+lEqwv4mV35+z3nfPdc849M4NRjbTDfbAP4CxZKHsf4GMgowAFgBmATq6BDjFiQTukpVcXbAUeEPmq3RDqevaJ55/eqYVZufgFsJrt3kf13xuN0Ldj5J1xgmF2ZA816IVhIrmePVQ/J7lPhon8YAXL91L9QJNBR106K0MXFP2dBCrZZUkf5kbwzDAJyL8vSv7VqBGUugHk7NNXqL43aoQlK+WdzarZS9IlpyTOuJq9csvXo0boggLC7PNemY4y3zsmTSeRIJucdn6P5qhMavo1ql9qVEwFG5I5zGgqJMj6eqihaWBBV3BrWT+5SHCUBP5f/2hxa7URu0IaMPIcPLkW6zSyycWyXemHlZFOiyoNBEofqpOYPKweuNFKJmzLiifthB1P2En5tRNWPJGMr7OspJ20rET8HOja8TxhhV+JPponsT+mSMulH4k1cYrMQHAOyvsgMEbGNZ1iBDURwqB2cJIaiBqG1iVa25KZIn466+N2a9Iq4fNFPN5qJTI8Je7Em3kzMrNKC3GyPuB4IZERtf3AsErLRWKX/QViBcJvkYU2YxOPLpewM6j1QxlSGSDUhdvCwmZ+k08MvIANZr0MCvcRL2khU8OgzC0jlAffIO7GDt6G4X5wfH77gGK9sQZrB1emhzVmtZdCOcrw2+IZ4cXwBRAXAU8AL4C//WQEvwExChgedKTZV18Q35wdKZqHB4qmc4965ofHqG9+WTLPzxUdBou+2smPgj46kiv6Hi2ZR0rmlDQjZp0GPDymNspRpxMIHVhvrinhc8eJ6nPcshu9w333ZaIs9pmUKReqSN4lHsJ7eCdWOCc/6Jfu/rOdsML3dHnn4rblQ/d7kG2pZkpvvl60o8FjizR+yFJ3AMrcADexRKaTK4b5x2ptz/DHxCP4AN/kn6ccyKVDMO8PQWuHHCFuMk/Tw9ozWGlc50f3nqL+WPONYgPewTtQNyMyRNvmpbUo8Epiy4TklSdFwr0nFMUOyLEQpr50TMMomyLHVDXF8eG3ChNjvMlXdA7DaWFZqau3ey2UFG8Q9VjJ/ULY/gn3OJ0rbxFrMcqFT739NVlUctFTwvx60Yi1Zo1XlJeTncz4jwDeJKJu1cHFVbcp/mSW/gSBPhIw9tOwenB1p2vU860u3dD3hrPGUx0KKaRu6HbX6ZT9M9kV2rhj5/Ydz8S26CHzX34BteTS10ImO57/G50tV+PTQ4e677oWeVxpqR4/Op32dlhIbb7qi739qc1vZvdOpZaic6l75w8OzYyc8PCzqUNk24T94Gyq5/xbc38OzKZWKv231+pf7I+vOuIvfe9mow==

RNG Seed: 1266063973

Trying to cast {SpellID: 49271} but GCD on cooldown for 23.914729ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 ...

**Comment by jarveson** [comment]
#3838
