### ISSUE TITLE
Gift of the Wild gives wrong amount of stats.

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#374]
**Describe the bug**
I made a small programm to check the charakter stats and i realised that u guys miss read Gift of the Wild. Instead of 37 on all attributes u gave 54 (Which is the resistance). The 40% increase on Gift of the Wild works right.

**Desktop (please complete the following information):** 
Windows 11
Chroma

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/380
