### ISSUE TITLE
Crash Report 1967023867

### ISSUE THREAD

**Issue by Boc4arik** [wowsims/wotlk#3752]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVU9oHGUU3/dmss68ZLuTzyaZfE3SZNraurLbb2Z2tLXaXYvFUhBCe6me9GBPHorxoiBsC60mKVJaKXYRCuJBVNAoHlIo/WOD7aE1lqbGKNFWkBwE92ChrAf9vvmz3WxQGqwX8cEO8977vd/7fW/eztBaAy0UuAl2wB7YhxWAIwA/4qz+CeBZgGmABYBtnQYMooAyDCsUvA/AUvxo5gCkh198/pUXXjIMC/gNoKw1d0Szf+l30lPncWISybTeO6w5mrrtsL6XuZv9iXdhXLOPDTjarPSy1rzM3ZZ1MqcCGes7mX6HObr0UsqV+bf6HH1CuVnr83HNMacmVQ/FxqxDhzX79X7HlN5URJG1xmXseJ/UEoE6rAXJWRlIBMyPRp4C69ZHo5q8npZXZs1K3JsDzWQpmTsxpjntBggY1vfobwC8i7eQzmLqf/tHxsRyK141DLDQxn3gdVFWLfAGuZw71HJeBC4f1hisD3zhCdd3vcD3XV/4nuv7IvBdV/huPu+JQAhfuN5NsI3KD2h9cwbtb8/gYHUGN3xxFcWXV3EB9BpoVegjTiuM0e7BPxIDZkRCVpbP429pW6MuMniadON6HR2T7qO2fLHgjlBPHJ46oDvtJBN5vyAeCUaoO0pYx06hQ2RQOu8VxJ24cbm+ON7TFI+I3ILwghH2AF9LVm6F0cbw0ZSCEAYj3FoimHjU8OQ5ZH2cJzU74xpPJDrZat5P97NOyuYyMWsbaQQR4OuTWgTIdRpaWG5WMUzUMQR8VUfm8o20LrcmBqz6FG0DWIyTB+DmB43buJSV+VYqMo861Kk9Fb1WR+rJdUkJ5ilQgUO/Y6TVdck8qjWFFPZuGA4uZTjYxPAU305b+GZax9ZQd27l4s7hDIKmxuEEtTsTdL2Q6OcPNfY430Iu29gM/ouTFBPMtY/1ZB/Yk3wbbWIP31V5i4hANFh6eQ9lWHvrqNSwW1LJDOTzYHn+EA2x1S1TjFdhZ7wKxcbIAu7Tg2w9ZdRSVhty1fQ0KRcXTa/Y6BIKWFTS0LaK97a28xp18RIr4EU8DtPyNxq/fr3yHKSqmHJ+QjMMVPaWO5M/aW/1hLJLpc1RZLo0tDe06yXvMxzcbbfl3v53X+O1/eV7QVO5dOGe8CzHopmd/rX8ROTfLj0Hu/72wycqEy8Xds2UXnvm1uTc2EwpitZKrbih/bUrj9k3Slvnn67tvrywJP9ft+V/+J5ddsWfDjQ+MA==

RNG Seed: 238388295

Trying to cast {SpellID: 65861} but GCD on cooldown for 5.910157ms, curTime = -3.075s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeaa40, 0x1a7cc30})
	/opt...

**Comment by jarveson** [comment]
in rotation, select auto or reselect 'basic p3 apl'
