### ISSUE TITLE
Crash Report 80929542

### ISSUE THREAD

**Issue by goomies** [wowsims/wotlk#3756]
Link:
https://wowsims.github.io/wotlk/protection_warrior/#eJztU01oE0EYzXzZbJKh4jQEWUMS4yJSLNXJrjkolFkFEW+1xYsH0YM9KagnjZdqldp4UbAFIxha60EPVnqQVChUW6QRCYWt/bF4SIOpP2hia9qAVp3dpRWRoLb15mNgv7/3vsfuDoY6tFu8gtA4QjuBII/NN+c4j8S6Y0fOHD3lchK37znCa0k+B9LbgCx2DcDoN8ACWXgFuIJ8mgIpG5DtiQRgJ4nxrM3Pp4s8KPHpmyno7gW8huizIMWCsjDdCzaezvD+Nb8sTCV56iH5LEhX/bKbp/ykk8AlUp0gfeASS4USH2r3y2LaHOIOenKA3aQ7B7I9mTMKX3oMS4lxkEXux2A5yUwGpGcBwxuntwY5YfgRJ/CmbL+EUCcUAfeD7T9WBA/9W0bUdhdhLLgQAR+EUAxtVSOUqioNKyqlNEwjClWUsMJjpUapoRFVjYQVZTs1EVGmkORq14F06SB16BBq0aHqgg60WYfXyF5AQhy5KxtNjLLHAJIwBEMoidAL5HUfMJDo0yotL6CFxDjY5Mt2t5k3NS52vNr6+HUDKbbDqgyzjYuqyiSEGiTHln/8+1S1aqsh05Qa/I1Ow6rsWQ6sd9uX13ZZeYkdRvXmxcxEvff2Zkrs0MN9FVAtatnbNwZD92HFTs8astER9mB2YeT0mzlmfeX3bNvLTeK5tklm7S0wPHbrRC2eZ+V0PM39Tzv2PFnqn6w1GFjbcPHd/mSwyKpb1k2k54uMm+eRoH3l2zaHHcv2b9oZGyjr5xd/9Pj05zsf66U/3niwzFUusJ+fP/AdXwjS/A==

RNG Seed: 3010524255

Custom Rotation is empty
Stack Trace:
goroutine 23 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeaa40, 0x3a2290})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/common.(*CustomRotation).Cast(0x0, 0x2219ce0)
	/home/runner/work/wotlk/wotlk/sim/common/custom_rotation.go:124 +0x19
github.com/wowsims/wotlk/sim/warrior/protection.(*ProtectionWarrior).doRotation(0x210ff20, 0x2219ce0)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/rotation.go:20 +0x5
github.com/wowsims/wotlk/sim/warrior...

**Comment by jarveson** [comment]
be sure to select auto in rotation tab, or select an apl
