### ISSUE TITLE
Crash Report -2071963544

### ISSUE THREAD

**Issue by Fisper** [wowsims/wotlk#3759]
Link:
http://localhost:3333/wotlk/mage/#eJztVE9IFFEYn++bdX3zNPf5NBknN9ZJZNmQZndbMA/O5Kk6SV6iDiGlBHUQDSohMC+ldYn+4SKxBEFBiHqJTokkJbSbeTBIklUrJEVkTagu9mZGJSoMSaFDH8y89/1+v+/3vvnzHi0hWAkHII2f5QcAvYADACMAacAZgBpKQIUgWHAEuKQlSDt4a8/UX2hoJgqTtQmgPnZzCdU5v+4dGsShJ0gVNpdBXR4X01x2R3BTfl0ecrKni6h2iqxPZJx9zKD6xa8rghNiG9vGZgXWzXWPACSR3hDlPcW6p89OfeyNMLblfa7cx24J/rJYetyxEMCEqE8Ui15chcIeT6O7usIuLa605WFLGfuemrabuiua+uZfZZIZWzo/6Up1LwEDarPu4RLSAZT+x18FNzZa0aoQYNgkfkuo2UFzCXSBSxy0tByCzKMe16XgbeiE3ZGoYYgrGg0bhhGtMIxYzBBQ2MHEJBYNR2wgGgtPgUoWk8iWk6g+/ICB96MYTI+i8W7U/ucXICcO0iAmMAHAy7UyykJ5xMuxStK81EMx1qIxmkc6igLLqwG8SCv8WWe0VEm8RNN+xe2R9PTKjrvGVar0gw0lxpHm9AOhXnsaAEd39RXyPVoF3cVLaa5OKYnY6ECvTPNDPpLF8ZCkZdMsKocjrrGg+Hat4AfTNZ9SApqfFoTyicepU+JoU7MpV/I1hXynkLgtuxKn5b2us9BxqhFn/jqFL/Bkx8qmKLPeghRHSY/LigO0NVr5LlVtFce77Bg297nIiFna6MSYGfmETd0XW5Xa+rMnTp1raD4dqFNJaIu3WrDD2gybtuFnf/CpW483KkNN+zejj9+F86bb+KS1ssKMeQXg8LqnmFl4P/t6ZdosLL/2qP38rOmiC+ax5zPVkz1jZvKlHXNro/sJ582teoR/NTZ+ih3dcMV3k2roTg==

RNG Seed: 3545442471

simulation failed: Active aura during reset: Reign of the Dead H
Stack Trace:
goroutine 5216 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x9e
panic({0x8b9320, 0xc007ba2e20})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0xc0085d0840?, 0xc011affbf8?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:124 +0xea
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0xc0042fe4e0, 0x1b?)
...

**Comment by jarveson** [comment]
this one looks to be fixed i think, or live sim with that link doesnt seem to have the error, worse case can wait till next build monday if its broken locally

**Comment by Fisper** [comment]
I'm not sure what all details you can see about this in the live link.  This happened when I added a number of items and tried to do a batch simulation.  When I deleted a few of the items then it would become intermittent or go away completely.
