### ISSUE TITLE
Crash Report -671190779

### ISSUE THREAD

**Issue by joexi** [wowsims/wotlk#3760]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVUto1GAQ3pnN1mRqu39/rcafLtZYHyy0JllXfDarIBZBKHpRT3rQkwexXhSEVajankRFdBEETxUFrYqgINZHUQ8+WtqqPfgE7aHQFRXqetA/yWbZdlEo6kWcQ5L55ptvZvIPCdWpyNDExdAEG2EnpgGOALzGYeUSYBfAU4AhgFVVKtSiCSlodlnQAcBDoqv8AJQ179i6Z9sutYyB6AOKsvOjqA/HjLLuO/jiOpLGOrJohN3HyaxDxt7GAq/rE+rt0uuUXpSdk7FRmSc9F6hggyOon+aGIr2QdC/I+PGavBtlwyNoaN0e16VzNpBF/VDM0DoLWJR9lRInamQvPqCx1o/o19PYyw/5R4U9fude+7JIk9h7KZOLSff5iAte+4xGuQomNCsblcMAZ/ELUheG/ttvGTcnmrFXVYGhjjvBrqaou7Pz5T42ufv4AARSqB3mJROmbdoJy0omElbCTNiWvEvQMhNWfb1tJk1TOvZb0NX0K2TPbqH+4hbWZvpx/t1eNO/34hCUZ0HJQA0JqlTbptV+Dwy46jcyNXUHr0b0MFWTKspIUQdychNpEkXq7YZFLQHMjt0IYKshWYDVR7limM8VdcTilWqE49KQSyBMtghWUrxGCI8X5rg2z7NaPMEnOeQk/JpnbiO3xAKaI2bTtPhUydZugBu40BYWEQoT2KRddhG176LipXcfUPhMEaMpvIqi8Yp8Ix7X9Ag9Z8I8JRppIbdpskGk2l56Dml6vFrS/QrqwW+Yb8si7Wi4CHK53BErKMGtcQpujwWFVkkPevQFWosE1ojVtEwsoTl89ti0g0FasqhuybuyPaH358PcFibN5XXF5J8MYgfnyGeI6VTBy8cP1pMrCQUty2P2z4xXjp25MNBa0USNfDlVGDI5U+glODYcM9tCmnIZSraiUMlrYoxOob/8ari0B2i35b9cdmoQQhkMGe9Q84D09lRVsN8zMqdce+gs8ZGnzqztng049hWs3aBH4if/7hcwuz/1J2TSD+/9EZ2JmP/Obo6kVvr+qLMF1v/yn2GmO3c3rO939m36cn2wvd/x0awznjdrf/bxcv2N0/hyXXbDo6GS+L9uE/9nbJ5wxg9S/yjg

RNG Seed: 2839379937

Trying to cast {SpellID: 48461} but GCD on cooldown for 37.107473ms, curTime = -1.5s
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeaa80, 0x1a7cd70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
select auto in rotation tab, or select 'basic p3 apl'
