### ISSUE TITLE
Crash Report 298647054

### ISSUE THREAD

**Issue by Jamzc** [wowsims/wotlk#3761]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVm1oHGUQvpm9XPamTbp5k142L5d4LmjiasLermeSiuwZrbWKElPU4j9F86NaKr0/2h9yCqKJiAbFalqVBon1A7QBoa0GY4xC1IbY1oIKwV60jaGBQw1Jo1Tf/bpL0lAJ1j/i3HE7+8w8s/O1e0txGVvgZnge4Ac8E94P8D7gEMA4wBRAG5NBhQQa0AJp4dUOW4GFeK78CYi0P3Tvow/slEuVUv4V0Drl8Z9RPVOrRT4bxu8PIUWVmVOoSY66VvnyLKq5Wk06IM5KlSenUe2uFZRzU6jOC4qAHb8yJfcrqnuZFhZAiEh5+TSqL8Y1CAnf2UnUop8fwgPuVwAnc6juq3PJHnBuEtWX4lrEc6KwMp1z0pg4LdL41gVm8i486KT07ByqC4WUfvkR1SlZGAd+Q61MBgPaw1tLHoGnAfpwFmkIQ//LPxJmrJaxKyKDgg/DfQ1UJeNmF8u2p+/wlHSaK8IOnMSvpGJCzKwbOoyUZRlGMmVaZtKyUknLNC0jKZRGw0iJj2EljRWkcSXQkxyo8vhPqAyNoHp4BBNnj2LDwlE0fp/AKQjnYU0vhIZxVFYlipHMIxSWd49JGpFMkUarqTmVKeAnsgFuNqWMIj5XwJNNhpVhNr+OrmD1pOjlcoThhpDjRSgYlX2gULncFUv8GQjw8xB2pQy8nupYfHkIM0NyH5SQJAjcOzCTG1TPLgsM/Y9RjV4tSNFe9JPmIjUKi9wy3PNgG/kN1MqaKdoHjs+pdySq1tZT5cD56VGFvs5PoZQE/epkhvscNg98FugYsHEILj8Wo0+BDwFFB5zQyseHMVCdG9dX9/YX1LHJgvru21KgflRUnbveVwcKvvLx98IBOthV8H2rqL5RVCeEGtOrZGDRYe9CXZLTCYJWqtbXF/H8h+j1OWmYtf5w9z2FnqZ8IMKUcq9I1s5vpxtZG611Jj8QlO6emQ5t/AtpeeeSphFAt/iQaXjNFN5sA28hjSUWxfg6K7kLUOIS3MSsTBvzLEowVmN7ht3N76Rb2eZgnmIhly7BXLAETa1ihZiu+DF9rCVDZdqagP3MN1Kw1mwT30jXslZS9ZigyNv8tBYRVwq2LJA4shS33HvCMykviLXgurp0TaMkmiLW1GuK48Ou4jolWF0Q0RmG08KSYlev8VsoTKyGV1MZCwpReo6443SOrIFfTnHGA9Prn+CikgueAmaX8Fqq1Cv8ovyczFQmeASwOh53qw4vrrrZsx/PSt9BqBdDWo8U9Z50nekK74FYla7pfcWRUbvVQ8btSztdOWGbJ3FXZNOOndt3PJjYokb0f/kfq6ErfTHCZEdH/ibOlgvZ0wf3dF5/MfJYSbwe3zWZ9q8wb3dc8E2g5f6OV7PPTdhL0bx909zug1ODx+yqngVz/8Kb9h7cdsS8bdrunnkt/0f/tL1ytP+urP5N4J5VM/4CJDByxg==

RNG Seed: 2200337850

Trying to cast {SpellID: 49271} but GCD on cooldown for 69.81715ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6...

**Comment by jarveson** [comment]
#3838
