### ISSUE TITLE
Crash Report 1376681561

### ISSUE THREAD

**Issue by Jamzc** [wowsims/wotlk#3762]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVm1oHGUQvpm9XPamTbp5k142L5d4LmjiasLermdyFdkzWmsVJaaoxX+K5ke1VHp/tD/kFEQTEQ2K1bQqDZLWD9AGhLYajDEKURtiWwsqBHvRNoYGghqSRlHf/bpL0lAJ1j/i3HE7+8w8s/O1e0txGVvgZnge4Hs8Gz4A8B7gIMAYwCRAK5NBhQQa0AIZ4dUGW4GFeL78CYi0PXTvow/slEuVUv4l0Drl8Z9QPVurRT4dwu8OI0WV6dOoSY66VvniHKr5Wk06KM5KlSenUO2qFZQ/JlGdFxQBO35lSv4XVPcyLSyAEJHy8hlUX4xrEBK+sxOoRT87jAfdrwBO5VHdV+eSPeBkTlJfiruA8KOwMpV30hg/I9L4xgWmZ1x4wEnp2TlUFwop/fwDqpOyMPb/ilqZDAa0hbeWPAJPA/TiLNIghv6XfyTMWC1jV0QGBR+G+xqoSsbNLpZry9zhKZkMV4QdOIlfScWEmFkXtBspyzKMZMq0zKRlpZKWaVpGUiiNhpESH8NKGitI40qgJ3lQ5bEfURkcRvXIMCbOHcOGhWNo/DaOkxCegTU9EBrCEVmVKEYyj1BY3j0qaUQyRRqtpuZUtoCLDfVxsyllFPG5Ap5sMqwss/l1dAWrJ0UvlyMMN4QcL0LBqOwFhcrlzljiz0CAn4ewK2Xg9VTH4stDmFmSe6GEJEHg3oGZ3KB6dllg6HuMavRqQYr2oJ80F6lRWOSW5Z4H28hvoDRrpmgvOD6n35aoWltPlf3np0cV+jo/hVIS9KuTWe5z2DzwWaDjwMYguPxojD4BPggU7XdCKx8dwUB1blxf3dtXUEcnCuo7b0mB+mFRde56X+0v+Mon3g0H6EBnwffNovpGUR0XakyvkoFFh7wLdUpOJwjSVK2vL+IzH6DX56Rh1vrD3fcUepryvghTyr0iWRu/nW5krbTWmXx/ULp7Zjq0sc+l5Z1LmkYA3eJDpuE1U3izDbyFNJZYFOOrnOQuQIlLcBOzsq3MsyjBWI3tWXY3v5NuZZuDeYqFXLoEc8ESNKXFCjFd8WP6WEuWyrQ1AfuZr6VgrdkmvpGuZWlS9ZigyNv8tBYRVwq2LJA4shS33HvCMykviLXgurp0TaMkmiLW1GuK48Ou4jolWF0Q0RmG08KSYlev8VsoTKyGV1MZCwpRuo+643SOrIFfTnHGA9PrH+OikgueAmaX8Fqq1Cv8ovyczFQ2eASwOh53qw4vrrrZs5/ISd9CqAdDWrcU9Z50HZkK74FYlanpecWRETvtIWP2pR2unLTNU7grsmnHzu07HkxsUSP6v/yP1dCZuRhhciPDfxNny4XsmUN7Oq6/GHmsJF6P75rI+FeYt9sv+CbQcn/7q7nnxu2l6Ix909zuQ5MDx+2q7gXzwMJ+ew9uO2reNmV3Tb8283vflL1ytP+urP5N4J5VM/4CuYByPA==

RNG Seed: 1384471831

Trying to cast {SpellID: 49271} but GCD on cooldown for 93.641042ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 ...

**Comment by jarveson** [comment]
#3838
