### ISSUE TITLE
Crash Report -623838473

### ISSUE THREAD

**Issue by MALItchfield** [wowsims/wotlk#3766]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVUtoFEEQ3aqZjbMVk520n4xNonFNVBaiPTMu+M2sghgEIehFPenBnDyI8aIgJIJichBREQ2CKAiC4ieCkIAkfoKKGD/4V4IakBwEl2gwrAft+S2bLApBvYjFMHRVvXr9arrooWoNdRS4EOphPWzDZoCDAG/xi3IJsAfgIcAgwIoyDapQQBoaXBScBWAR3l+8B4oatm7euWW7punAXwDF9QsjaHysTBT13sAXnUgx/eMQJhR3OVHvkLn3laH3ZgiNtsCL65dkbkTWXe5E+VCJ3ifTJ1hClV5Euldl/khF4Mb155I15mNdONO/Svip6V6stxNfepzvBtA4WuFx9npaWj4HWuTyq1y6pareN+C+h4fckjOf0TgwPScjIhNXv2CiWAMBDep6dT/AaRxG6sHIf/stY2K8Fbs0DXQ0cBtY5RR353aunMl6dybvAFcJdWiDOSlTWJZtm2ZKvmxhW6Zti5T0hW3W1loiJYQthPUeDO1JN+qvu9F42Y1V2X6ce/MxituPcRDUDBS3QwVxKtVap1Z9Dw2Y5kuZnL6B96KGQlNI40Wkar171ESMJlC01p6XasqFn2UxCFt5Yf1wVxg289H3s/lhNptXk54s1aIMF0dcAGGqiesFmio493AKw9UBzmzyCB9kkRH39zx5HZnJ51MNn0VTk5MlOtYFbuJ8q8KjpBBYFOtwI9qTi2rYFJvBK2kSK6N4siQQ4mGFB3h0UmFpXkcLmEUTE0Sa5ZVnkcqTUyTc30Hb9w0DWSbFDil5IRfLHL6MbGaOYXA15hj2Snio0SfYm0ewiq+kJXwR1bBZo8v2hWWpvH0LvpXlEX04pzCLC5rNqvPBP2nECs+RTePlVMKKxzb2KFuQCiXLY/bPjJWO7jnX0GpeT3VsKZUkZHF7Tkt4bDiqtwU0qQMKpiK3kydiFE9OXzAaLuwOHoXW4E6z0q8g0o6RxADGvEBzY7osnPtp7cddu+ss8iMPnZmNnj1zrCtYtc6IJo/93bsx05L+EzTNd2/9EZ7xmP/Nrn1KL/f9EWcTrP3l30Q0X94xb+1TZ/eG4c5XbU8dP5pxxuJmtmT6lhrvnLr+NZl19wcL8v+6jf9vsnHcFT8A+kEuuA==

RNG Seed: 1501600847

Trying to cast {SpellID: 48470} but GCD on cooldown for 176.4957ms, curTime = -2.5s
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeac40, 0x2445f00})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
select auto in rotation tab, or reselect 'basic p3 apl'
