### ISSUE TITLE
Crash Report 1517118543

### ISSUE THREAD

**Issue by lengyang1995** [wowsims/wotlk#3767]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVU1o1FAQ3pnN1mRqu69Pq/HRxTbWHxZak6wr/jarIBZBKHpRD6IHPXkQ60VBqELV9iQqoosgeKooaFUEBbH+FOtBrdJW7cFf0B4KXVGhrgd9STbLtotCUS/iHJLMN998M5M3JFSrIkMTF0EjbICd2AJwBOA1DiuXALsAegGGAFZWqFCNJqSgyWVBBwAPia7SA1DStGPrnm271BIGog8oys6Poj4cM0q67+CL60ga68igEXYfJ7MOGXsbC7yuT6i3S69TelF2TsZGZZ70XKCMDY6gfpobivRC0r0g48ercm6UDY+goXV7XJfO2UAG9UMxQ+vMY1H2VUqcqJK9+IDGWj+iX09jLz/kHhX26J177csgTWLvpUw2Jt3nIy547TMapSqY0KRsUA4DnMUvSF0Y+m+/ZdycaMZeVQWGOu4Eu5Ki7s7Ok/vY6O5jDwikUDvMTSZM27QTlpVMJKyEmbAteZegZSasujrbTJqmdOy3oKstr5A9u4X6i1tYne7HeXefonn/KQ5BaQaUNFSRoHK1bVr198CAq34jU1N38GpED1MlqaKEFHUgKzeRJlGkzq5f2BzA7NiNALbqk3lYfZgthPkcUUssXq5GOC4JuQTCZLNgRcWrhPB4YY5rcjyr2RN8nEVOwq955jZyS8yn2WIWTYtPlWztBriBC21hEaEwgU3aZRdR+y4qXnr3AYXPFDGawisoGi/LNeJxTY/w5EyYp0QDLeA2TTaIVNtLzyJNj1dKul9BPfgNc21ZpB0NF0AulztiOSW4NU7B7TGv0CrpQY++QGuBwGqxipaKxTSbzxqbdjBISxbULXpXtif0/nyY28KkOby2kPyTQezgHPkMMZ3KeOn4wZ5ki0JBy/KY/TPj5WNnzg+0RjRSA19GZYZMTud7CY4Nx8y2gKZchqKtyFfymhijk+8vtxourQftttyXy04NQiiNIeMdaj6yOVUR7PeM9CnXHjiLfaTXqdnu2YBjX8Hq9XokfvLvfgEz+1N/Qqblwb0/ojMR89/ZzZHUCt8fdbbAul/+M8yWzt316/qdfRu/XB9s73d8NOOM59Xszzxapr9xGl6uzax/OFQU/9dt4v+MTRPO+AG3MShY

RNG Seed: 587472730

Trying to cast {SpellID: 48461} but GCD on cooldown for 37.107473ms, curTime = -1.5s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xeac40, 0x1a7dca0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
select auto in rotation tab or 'basic p3 apl'
