### ISSUE TITLE
Base Stats for RAP and MAP are Wrong

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#377]
**Describe the bug**
Checked it with my small program and realised that apparently u guys still have the base RAP and MAP values for lvl 70 (120 map and 130 rap). The right Values for lvl 80 are 140 map and 150 rap.

**Desktop (please complete the following information):**
Windows 11
Chrome

**Comment by lologarithm** [comment]
We have a lot of base stats that haven't been updated yet.  which class are you referring to?

**Comment by romanhallo** [comment]
Hunter Orc

**Comment by romanhallo** [comment]
Would be nice to have atleast 1 race with updated base stats to search for more bugs and a reference sim.

**Comment by jimmyt857** [comment]
Thanks for pointing all of these out. If you aren't already in our discord btw you should join!

https://discord.gg/jJMPr9JWwx
