### ISSUE TITLE
Crash Report 464087751

### ISSUE THREAD

**Issue by KongenDunark** [wowsims/wotlk#3770]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVl1oHFUU3nNnszt72iSTm3QzuWziOmATRxNmZ1yzW5FZo7VWUdYUtfimaB6qpdJ90T7I6osmIhoUi2mtNEisP2C7IFRtcI3xIZbE1f6ALQRN1YbQwBJbNkZB7/ztJulSCdYX8eyy893v/NxzzzkzOxgRSQLuglcBfiAX/IcADgPJAxQAZgF6qAgyRIkGCUhxqzRsB+pj83XPQyD95CPPPL5bDEpB9j1gvTT5G5EvtCqBr8bI2U8IhqQDJaIIRzhcLx3nuplWb3XmPJEH+Moyq5e+4bpF7sd1lrpWmvmVyPup4ucrH19Ocf3rEcV/1lrWS2MLRAk5tpY5lY4vEPlgm82N21++w8U8kd+IODuEpOnzxIPPeTn5pc8/tX7ni5b9yyUiL7n5BaWFn4g8K3Jl7iJRakXQIO3fXvM0vAgwTC4RzBPf//KPhGpr9dgTEEEiT8GjG7FJJFttLptO3e+AVIrVicCQ2wgyifKODUCvETc0TYvFdUOPGUY8Zui6ocU46NS0OP9oRkyrIp3VSEdmQBYLPxPp2DiR8+Mk+vs06Vj6jmiTp8gs+Iuwbgh8Y2RClAUMo8gC6Bf3TgkKooiBTqOrO54p86ezHq93xbUKXyrzsS7NyFCT3YrX03aU1DoxQMkmn2WFhHs0DoOEdWJ/OPqnJ8AuY+gNvC7t2EYjq0PoGRSHoQYF7sCcC9WZhu30Ok8x8iy2qM3cKTRE3KQZTw39PLcMcyzoZnY7Jmk3hobBsvnlAwGblQ3YmLs8PWxQ690Ugsjdb4plmOtDF4FdAjwBtADe9lNh/BJYHjCUs0Lbd6wL50bLcP9IGU6dK8MP3xc8eKwCrbvdhbmyrXjyI7/HjvaXbd+rwHcqcJrDsNokAg2NORv1C1YlEJLYrG6o8MXPiFPnmKa3us09+AJxkPQxDxNkziFpmt2Hd9AeXG91Pucd3V7pllvha2F15WK65lF3u5SuOcXk1nQTS6BCo8tifJsV7AGosR3sxIxMD3U0ktdWbWeGPsQewHvoVq+ffCBXDkHJG4KuJB8hqkpuTJdLZLBWWed5v3RK8MaabmGb8RaaRFkNcxdxh5vWMsdqwVYF4lcaZ4Z9Tzgq6TU+FkyVV45pCHlR+Jg6RbFs6I1MxSht8yJazbBKWFOp6s1uCbmKtrBmrKXeQaTBSbud1pV2sI0YocxTvf0FWXbksiWn6TWsFRvVBvdQbk56POM9Amgbi9in9i8/dbejP5kVzoBviPiUQSHkPOf6Ug3O47Ap1TL0piUTZtJhCua1fbacNvUfyZ7All27d+56IrpNDqj/8v9VR3/qaoTJToz/TZxtV9Knju7ru+1q5FFNnBo/eC7l7rBo9l7xPSDxWO9b2VemzZVs0byztPfo7OgJs2lwST+09K65j+yY1O+dMwfmDxT/GJkzq0f778ra3wMeXrPHX2eRdyk=

RNG Seed: 1455170873

Trying to cast {SpellID: 49271} but GCD on cooldown for 55.100583ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6...

**Comment by jarveson** [comment]
#3838
