### ISSUE TITLE
Enhancing Totem Buff in your Settings has a wrong multiplier.

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#379]
**Describe the bug**
The Enhancing Totem Talent should increase the Strengh Earth Totem Buff by 15% but apparently its 20%.

**Sim Links and Screenshots**
With the 20% increase on Strengh of Earth : https://gyazo.com/2dae1e777f5cd384aaf16e09b4dd545f
and without: https://gyazo.com/f5358ba5c38250408edd99893fd6a2c8

**Desktop (please complete the following information):**
Windows 11
Chrome

**Comment by lologarithm** [comment]
fixed: https://github.com/wowsims/wotlk/pull/381
