### ISSUE TITLE
Crash Report -204916919

### ISSUE THREAD

**Issue by Sinner3112** [wowsims/wotlk#3793]
Link:
https://wowsims.github.io/wotlk/mage/#eJztVUtsTGEUvufca/z3tNq/f5Hrr6G9jWCS0XmYqEfM6KoapKlNI5EQwcZCdOGxkGHjFYnEI5RFIyKISNUKIU2jiy7UK4Q2FW3qkRCpQZRI+P97r6pHJA1WnMXcc77HOefeO/MPTWZYCdWwD+AR3rdOATQDtgLcVDXgM4AqwcCBUoxBJWSgFuphBQhDnqDtEKpdt3Lz6g3M5qbsByrkR9+i8yLshtrbsP0iks1f5NA1u1Wazw8rri/smue9quspOq/CPif4kxw6g8y1lUkBTR1IY3j2HTqHhGspwFDlMWU/N8G1zuuykF/oR9fuHpIX8oOK36FG+5gCHqqeOb3LRfRH7nuGTnaSa2r9aP7mja7I4gOXUX1+7NWSq8rzIdjR5k3vguVt/rLXT90xDGJQa9Vbm2AnwHF8i9SKxv/4rRCxkTq25DPguB6y+usKVSWk6iPgcwszMo8hR2eVa0w7i7uhPpGMxWKpWDIZV1edfxNRxaU0HFe6ZFIlqWQ8oYFkKh79Xj08+oCz04+Rf7qOzuvrWNp/W/1grAHIawSjDXOmY9I4YjJEFjvXbLo2jaZR0cSMygYqppC0CJ2iAIzPmNUwpL3VicNgMVFK4pECNkpgjaEFhKmGL03FErmIqkSGiiKFzBJYZ0hlJDOZmkKOHE92Cyglv7LL/JKeVakW++08ccLvx/dfQhGWJR5t/pyeK2dThYgGzVhTN1JeCzAK6bQUqDhSpKz2GdTsnhsog511LipklMpFGeW7RCyh0dbmH5aJJ/ybU5SokdU0X8wbPk1GHD3gkgc8OmVJuxGDh/br4ZbEOYaYLMOezPIGBt7nnejJ3neiiMsKmhIpDwQlLegwEF9nyKD7rcCirILk0HvbFZwFMzNdYDSi4e41bQ/IrskU+dTYzITGIzo60rN95Ga6bI0X99KJHixd6rDIXz5TBrZl/kSbbMe1P9Lnb4T/bBf1ZBb49WC6Wv1x1f3yvF6e27h4+v6+9J0DeVsfPOxN++hAuuFkwdS1d9uG6p9f/50Y+Xm9bMSOz34i+1Q=

RNG Seed: 3108723454

Trying to cast {SpellID: 42833} but GCD on cooldown for 31.024602ms, curTime = -1.7s
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xe8f60, 0x1a7cfe0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFunc.func1(0x1a276b0, 0x225a000)
	/home/runner/work/wotlk/wotlk/sim...

**Comment by jarveson** [comment]
reselect an apl in rotation tab, or switch to auto in the dropdown
