### ISSUE TITLE
Crash Report -291219043

### ISSUE THREAD

**Issue by LEEJI89** [wowsims/wotlk#3794]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVV1oFFcU3nNmNs6c/OzNNdH1krVxEkUWojN3XKitzWwLxSAUQvJQ9Ukf6pMPYnxREBLBn/gkKtIuBUufCv0zFgoKJVYNVcRWg3+JIGrABlRcosGwCnpnZmfZZFEI6ot4HoY53/nOOd+Ze7hDrQYwtPFj6IC1sAV7AQ4A3MYb+jHAUwCXAMYBvqg3oBltyEKnz4KfAHhM7KvZBVWdmzdu/2arYTAQI0AJ9tsUJh+krKqh03jzBJLJHt5DS/Nfa9iAit1NWdpI4OWeY/LQQksbUF6CHVOxKZWnPB+oZfcnMPk9t3SVGlPuryp+uMnSB3w3wa5PoGUOBVyfztlTRd+bskzlhbAiDSrsSJNVpUqEWvoeY9jdZLf+L77qLDfmPycnkOawZyqlkFLxH54WZevszydoVRtgQ6e+Vt8H8CNOIp3C2Ad7I+P2bDN2GP6yJnELyEZKGMhwqVrKDn8pz4FAiu2HrzPSkdJ2HSfjuo5ru9JxXTujfIW12a+1NmlnbNu1HVkZuwsNxs1BZCODmLwyiM3/DOPSM8M4DtV50HPQRILqjP55zS8iA26Eohuyp/FCPKlRIxmiinRjaJdumTSH4m3uskxPCb5WwCIsy2B26GQEO+Xsi4VymC8RrcTSdUac4ycxn0CY6RGsQlOTEAFP47imyHN6goL/FZCTCHse/Ru5I5bTYtFC89INim2eBD/wS78m4qQRSDKP+4hx5Xc9Gop/JFI0l9dTIl1bFBJw7YBw+ajGs6KdVnBJNRaRIYP0AtL8dKOihx2MPc+wKMsh86BWBvlc7onPyOXOjAq+xlKF3YoeaQwL7C4rsFp8SZ+KlbSYt0xP2xOlZcr6VnwrGRS697PGpbBpCW8tJ79iEBmdI18g5lMtr5452OVCRSiSrI45PDNeN33m0kBrRAe181VUa6nkXElLdGw4bbYVNPc4VGxFqVMgYlqdkr7iavi0cyj7i5efzI5CLIcxawzNAOjdlK2P1n5B7jvfznsrQ+SSt2hTYNc8+Qc2dyfj6W/f7SWa78u+jTK958++lTqzsfCb/fUo+3noT3kboOu1vx27d2Dbsq6r3s51kydG91/1QjTvzeQt6sv/uyp5x2u/9VW+++J4Rfx9t9n/dtbPOuMlAbk2Nw==

RNG Seed: 193596111

Trying to cast {SpellID: 48470} but GCD on cooldown for 145.961155ms, curTime = -2.5s
Stack Trace:
goroutine 55 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xe8f60, 0x1b3a9d0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims...

**Comment by jarveson** [comment]
select 'auto' in rotation tab, or reselect 'basic p3 apl'
