### ISSUE TITLE
Dwarf Mace spec

### ISSUE THREAD

**Issue by Leninaomega** [wowsims/wotlk#3795]
**Describe the bug**
Expertise does not change when putting a mace in main hand for dwarf warrior. 

**To Reproduce**
1. Go to warrior sim.
2. Add Glorenzelg mainhand (which is bis MH except for SM). 114 expertise in my currect set. 
3. Add Cryptmaker mainhand (which is good option for warrior) 41 expertise for the same set. 
4. I have cryptmaker OH. Wanted to sim to see if i can get a optional bis because of the mace specialization.

**Expected behavior**
Should receive more expertise due to the passive. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

Its both for the live verison in browser and my perhaps out of date downloaded.

**Comment by lime-green** [comment]
@Leninaomega it's still being applied to your OH, just won't show in character stats unless you have two maces equipped since it wouldn't apply to your main hand
