### ISSUE TITLE
Crash Report 803038428

### ISSUE THREAD

**Issue by fredTM** [wowsims/wotlk#3800]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVE9IFGEUn/dmXT+f2Y6T1jhq2JQkGyszsy1pIbt5ik6mhyQk6pCnAmkv1UkFK+tQkARZINQl6JL9kVwITZM0iFQsSy/lQewfmVnJFtU3M7tJbhlWXqLHMHzv93u/3/v4vplHaxhKqGMRbIFKqMFagJMAT3BavAzYCdAPMAFQms4gD3UIQZlVBRcBZEFtpnpwl+3dfXDPfsYkUO8CeaTrM6i8zNXcPV042o6UIr0aR018xJce6dN7VMYsrh35Q8nS2TpR+ZDLmatcNcOZ1nbkD6VJY29ROSdrLu4h8LSN8005mqvVSj3S8BRqKT12bavtfI3zRxx9jw1Ep1A5nWO3arW3UfeBb8NauqSbn633p6fWuyNi7WPkDSrRXJ4O22DbNGppDHQoc1UmHYCjAOfxHVInCv/jj0LWF6o4xBhIqGANmG4SVCThGGwP6IZp6n7DCPj9hl/364bfbwZ4bvoNnz5v+Ew9oFsKM5Ebgwz2uAOloQ5Uhjswr3sQC+4M4gS4JiGlGYQubHIpImUSU938KzkV4R8hJVOSzygMhGmZA7N7UdQ4SKLPCMv56mryeNNYkowbBZWDBAFVoqWscXnel3iATKpj2XIL5Ux1WWk697kfRf5P2U76vnC8hA20iN/WPfUueadaReVqGW2Si0n1KrxTagSYLHD68Ed09IYepmxvFnN9zzHiJsb6wiJK93qYKONWIVZvhm3/8Uvi4vgHwvETlIvVDeST11HqlVkl5XjVuWb2SVtmztYGoj+QNiRKGxKl/ILktWo+ZctZtEQjYqaFDkX5lIigO9YuBskr1ExKjeDsPuLN43fA3XqxFxpjs8EMjYDQjIJ2XEyxgdrqULpDZYSyms9Y0RcsdpD+4KpqOx4GzVHMq1CSvIs8YwoaQ3/Dprbv9i98Kv5Kn98J52xvvg5tdvKZ4C4on3d6N7zYdmNlw2iw+11B1YmuB0EHnQzOrSuh4Qs1Jc+Dzi0+S+D/9Vj49N4RUySe5c/iK3QyAik=

RNG Seed: 2718898477

Trying to cast {ItemID: 40212} but is still on cooldown for 59.5s, curTime = -1s
Stack Trace:
goroutine 45 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xe0f20, 0x3932880})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func3(0x3304370, 0x3263800)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:212...

**Comment by jarveson** [comment]
select auto in rotation tab or reselect 'basic p3 apl'
