### ISSUE TITLE
Crash Report -1821528783

### ISSUE THREAD

**Issue by ArbatosPakelis** [wowsims/wotlk#3801]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVVtMHGUU3vPPsjt7BDr8UBj+7OJ2jIKjJbMzrkCNmRWt9RINaaM2vmmUh2pT033RPphNXxR8qERjI62aEoP1kqibmLRSUqTUBBMI2suDTYhSRUIgbtQGpCZ65rYLlNQQ64vxTDJzzncuc27zD8Zl1gr3wasA37G58FGAT4ANAUwAzAC0cxlUSDIDWiFDVh2wE3hIHKncD5GOZ5944em9clSJignADcqp35k6l9Aip4fZheMMY8r8NNMkhy1Xhkg3ldCkT0mKKt2nmbqQIJcTBC+SC8GOpkKZ+pWph7kWJilE4iDpX49r4QuOyJW5n5l6IK7FRlxzulOIk2TS5YX40gUuk9EbcS0yMO3GLFcmf2JqrsHLJKqM75dIwrAyX2B0P/m5A04XmLqUIPGXHxww/xvTKmQwoCO8s+x5eBmgj11iOMRC/9M/Im6s12NfRAaFPQdPcgyJShkEkiypLEnT6YYbjLRlGUYqbVpmyrLSKcs0LSNFzGbDSNNlWKkpUOWBEaZM/MjUoRGWvDzJmpa+YcbYOTYD4QJIvRAaZqOyKmEtyiKCYfnguKQhyhjZbDW3pLNF/HwuwM3mtFHCF4p4qtmwstwWd+LNvBEVvVKOcLYl5FghI4/qPlCwUu6qTf4ZEIgrEH4LFdqIDTy+OoSZRbkPylAiB+E9uCkMbOQ3Bor+F7FeryOnWC/zkxaUGoYpt6zwLPhWcTe28RaM9YFjM/2hhHXaRqzOX5keVukb/BSiSO63pbLC9+GLIC4BngFOB4D/+vFaPAViCDCWd0K7H5jPzg4W2cP9RXb8YpH96AMpYE+UWOdD9dl80VY++3E4QAe7irbvl9h3S+wksbV6jQw8Nuy9qEtyOoHQhnX6xhJeGGBen1OGmfCHe+Ql5nHKZxQmKrwieYd4GO/h7VjuTD4flO5KpuM28ZW0unMp0wigB3zINLxmkjXfIlpR48llMb7OSe4ClLkObmJWtp17GiUYq7E7yx8Tj+CD/P5gnrSQK5dgIViC5jZaIa4rfkwfa81ihXZd4P3KOSlYa75NbMU7eBuqei25yLv8tJY5rhVsVSB68rSw3G/CUymv0VoIXV25pjGkptCaek1xbPitQsckbwgiOsNwWlhW6urtfgtJxetFHVbwoBClZ8wdp/PkTeImjHMRqN75gi0ruWhJML9eJLBar/KL8nMy09ngCOANIu5WHV5edYunP5uTvoVQLwtpPVLMPcFynZkq7yyrydT3vunQqN3mIRP2pk6Xztvm92xfZNuevbv3PJPcoUb0f/ln09SVuRZhcqMjfxNnx9X0mWOHOu+6FnmsRV6PH72Y8d+waG+/6k+89antb+UOTNor0YJ978LBYzODZ+yaniXz6NJ79iG2a8x8aNbunn+78Ef/rL12tP8urf8n/vi6Pf4C7Hxn6g==

RNG Seed: 3635072837

Trying to cast {SpellID: 49271} but GCD on cooldown for 13.67993ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com...

**Comment by jarveson** [comment]
#3838
