### ISSUE TITLE
Crash Report 1133059357

### ISSUE THREAD

**Issue by TakgunaGit** [wowsims/wotlk#3811]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVUto1FAUnXuTqZlb20mfVuOj1TpWKQOtL4kjfptREIsgFF34WelCVy7EulEQquCnrkRFdBAEFT8oaP3SirR+inXhr1ixCqIW1IXgLFTquNCXZDJOOygUdSNehjD33HPPOy/vJqFqDXUUOAMaYDmsx2aAPQAv8b16HrAT4CHAO4D5ZRpUoYAkNLosOAXAQry/eBsUNa5bvWnNBq1IB34HKKofH0DjfWWsqOsmPm1Diuin0hhTnsu/I/WTsva6Mqb0yWyEfrkfjX3jZcsJCQ/IltY27JKVEv3qZzQOs5gqgZBMj8n6/opsGtVPS8GI1G71fhLoSaOx80d/VP/yAY0DFdKDz4joL95mPah620v3ej/tXjvaXR99sj1TKdNrXunKR4wVayCgUV2u7gI4ip+QOjH0P34rmBhux2ZNAx0NXA9WOUXdMa2RI9jgjmA3cKTQbliWMIVl2bZpJuTFFrZl2rZIyFzYZq34ZdRaIiGELYRVWHsNhtbXgfrzDjQed2DVnR6sudWDItWL8mlIg5qCCuJUqrWMqfoWBDDNNz46eRMvhQ2FyknjRaRqTzJyYmkEhWutuulNAazvaw9gsy6Rg7V7mXyYTeHVpMdLtTDDWSGXQJho4nrB4hWcezyF4aIsz2zyBB9kkBH31zxyA5nJp9JkPonGxEdLdqQd3MLZFoWHSSGwKHLBRbTH51SvvWubyibwShrFyigaL8ka8bjCIzw6orAkr6dpzKKRMSLN8tozSGPj5ZLur6Dt+IpZWyZF9ip5kMtlDp9LNjOHKLgecwrbJT3w6AtszxNYyBfQbD6TJrNJg9t2BG2JvHUL7pXlCb05ozCLC5rCqvPJP9mIFZwjG8fHUgkrHrqxR5mCUmBZHrN/Zqx08J5zG1rEG6iezaGSmGxO5bwEx4aD9jaNRl2AgqnIreSZGKST85cdDZfWjVZL9k1nJZ9BKIWhWD9GPKB5bbIsmO9xqUNu3HVm+shDZ+JaL5441kWsWmqE4wf/7hszvTX5J2Sa797+IzrDCf+eXf+QnOfnA84qWPLLb4xobt1Yt6TX2bLiU9uz3b2Oj6adobyJW9P35xivnPoXi9NL770rqP/rMfxvzMphd3wHsHgtQQ==

RNG Seed: 4070006666

Trying to cast {SpellID: 48461} but GCD on cooldown for 40.337893ms, curTime = -1.5s
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xe0f20, 0x2a7f140})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
select auto in rotation tab or reselect 'basic p3 apl' instead

**Comment by TakgunaGit** [comment]
I did actually figure that out afterwards, thanks for getting back to me though, I really appreciate using the sim tool, y’all rock!Take care,JonSent from my iPhoneOn Oct 7, 2023, at 14:56, Jake ***@***.***> wrote:﻿
select auto in rotation tab or reselect 'basic p3 apl' instead
