### ISSUE TITLE
Crash Report -1877435489

### ISSUE THREAD

**Issue by Vigoto1337** [wowsims/wotlk#3813]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVV1oHFUU3nNnsrl7mp/JTbqZXHbjOmKTDjbMzrgmW5FZo9VWUdaKWHwQFfWhKIj7pA+y+lLTIlosFuMfBom/VBMoWG3IGmOlYmK0P4iBpSRaQ2hwqY2JUdA7f7tJWoRg+yJelp3vfud8Z84958wMtlDSBVvhBYBT5Iz8EZACwATADEB3DQUVEqQdsrADWIgP1z0D4ewj9z/x0OO0WqnmRcB6Zex3op6Ja+EvRsjkIYIRZe400SQH1ihT54g6FdekAXc3/CtRF/xdvfKN0C0K3ZFDrq5W2TdN1ANxTRbmkNiOC/u+mCZPOtt6Zek3okUEHnB/gvha2HcJvdgdcYlTZ4n6UswlBtxEij8T72YR5cCPPpSV3mnnf/6sk9FzC0RdEhkV3Py+FwFmqJe7rAyeI9o6CgZk5R1VzwL0kXmCBRL6f/2rxYy1Kp4MU1DIY/DABmyiZJvL5bOZOzyQyfA6ChyFj6RKCdGv3XCFkbJMw0imTMtMmlYqaZmmZSQF2GQYKSNlGlZyClR6eJQoEz8RtTBKEn8USfvSd8QYO0FmQC4B7YXQCPmSqhJGkfIwynT/uKQhUgxvsjo6U7kyfzIf8GZHyqjwC2U+2WFYOWbz63Aja0NFr6NhRjaHHC8kQtHYBwrW0Z5o4q9gAT+PYRt5G7ay2OoAZg5pH1ShJNy5d2EmN7CNXRkY+p/CFr1ZiCK9xE+Zi8RQFpnluOfBtvAbMM06MdIHjs/p9yVs1tZj4+D5yWGDXu+nUI1CfnUyx30NWwQ+D3gM2AQEtx+P4ufAC4CRQSe0MvwJCeDsUBm+2l+G49Nl+MF7UgAPV+BcqewwWPalxz+UA3aop+z7bgW+VYFFAaN6EwUWGfFu1CM5lUBIY7O+vsKXPiVenZOGGfdb++Yu4iHloAhTzb1Dsiy/HW9k3Vjj9H0wOLq7Mx3ZxFfS6solTSOgbvEp0/CKKbzZZt6FGkssi/FtXnIHoMoVuIlZuW7mWZSgrcajOXY3vwtvZduCfopxXDkEC8EQdKTFCDFd8WP6XFcOa7V1gXrPCSkYanYz34LXsjSqelRI6E4/rWXCCwVbFUhcWYpb7hPhmZQXxVhwXV05phEURRFj6hXF8WFXcR0TrDWI6DTDKWFVparX+CUUJtbCm7GWBQdR9o657XSurJ1vwBjjgemNz8iyI5c9Bc0u43Fs1Bv8Q/k5malc8AJgrTzmnlpefupOz348L/0AoV4S0vZIEe+ldm+mwQNNmZbel5111E57zIR9+cPuOmmbkyRxp0r1S/zZKT2duRhh8kdHL0qcS7G82g79krne2y/a98H2f/ygdz24/bX880V7JVuyb1rY//HM0DG7ae+S+c7S2/YrZOeYedusvXvu9dKf/bP2haP9d9faP+j3rFnxN3DtaeU=

RNG Seed: 2141937160

Trying to cast {SpellID: 49271} but GCD on cooldown for 11.867026ms, curTime = -1.03s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6...

**Comment by jarveson** [comment]
#3838
