### ISSUE TITLE
Crash Report -54924185

### ISSUE THREAD

**Issue by Gearlan** [wowsims/wotlk#3821]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVl1MHFUU3ntn2Jk9/A2XAsOVxe2qpY6WzM66AhpdRFv/oiE1xsYnNepDo6bpPumDoRp/oA+20aSRKioxraaktCQkQG1FgkZQNmChEZs0taUNadqIjYYWm+i5OzO7O9utCbH1wXgeds79znfOPefcvWcGqlXaSB4g2wg5Ts/K+wgdJmSSkHlCWopUopMQXU1ayQbCfHyu/DXib33h6Zef26wqmsJnCZRq316k+tlg2P/1CJ0dpBDQzp2mYWk/qkXad2g7EbRXinZgiOodQXT5BuEL6IKwsBRrU+ep/gELy0cHqQ+XSbTvrXaWpdq+ORoOjA7S2YEUvVT7Hu3tGf9SrXeO6ucRODQgSJjDlkUnh4C2JNLBSCBr07+K386TIrVDuOVS0E206yTV51WX1/cbDReqxCSt8oaCtwnppr9TGKa+/+UfCTOX6/GKXyUa3USeYeDjJSrhgGtJpyE8mw5ygxmLWqYZiVlRK2JFY5GoZUXNCCprTDNmxiwzGjlBdPWLUapNnqL68CgN/XGMrl76gZoTM3SeyAuksJP4RugbJboElaByP8jqjqQUBlDBvyZa3xBLpPEjbS5u1cfMDL6YxiP1ZjTB4vwuuJnVgWaUqH5G7/AJFlD0KO8mGpSo7ZWhP10h/DKE3YKF1kEtq8kNYSVA7SYFIKEDtx/M4ibUsZtcw65XodqoQqdAJ3WS5pgayJhbgtsMtpbfC02sAQLdRHBO75GgKlwB5X2XpwdlRqmTggLoflskwR0fdljhkwrsVdgexd0+WQldCt+pwJuUvY63ry+1wZc/Sq768UxaTWbQUxfT6lhGndkmu2p/b1qdzqjjE2l1CtUqo0IUPiIAbeEAtZsWMaHSWJExXPqZij4AiXkdPm2X0g4ew+dXMuy/kqEny7CK3ZjdBsGTWWDIBRxeIpsneuThIZCPl8yNl8wfT3TXw0MgH28slzeWnyfOxcNDIB9PHJqHh0A+3nQubzo/b3wih4dAPt5ULm8qL0+cn4eXdaAeXk8uryeL10tYD3GZ7w1RLxOBNNPtXl/6D368X4ZN/KV/95pYQWduffIWtTWtHwtUuH1/WSt/FO5jLVAkhlqfe6tTK0u4TY5LuUMhYpku9JADWaY9J5DNqnhFS7nYvE3SJB4AJMRM88UEe4I/Dg+zB905hIPUO7wW3eFV34SjjxmaWpDawcEaE1AcLnS9t9qXRDix+/lauJM1gW5Uoou60W/vnuWYL1hOIHyyGI+mZrlt0t7F8+WG7h2vqYJwvNoVCw67lRsQYrVuRNFp0Z+CTMtud/qDJnYdzvsqKGZuKdr2idS/RjyZgcZVUMO4a/zoK5pVdpqLMLueB6HcKHMKc/KyYgn39cVqeU2qcjm78gbbPt0m/UR8ndQX3ioFUm/f4c3NZfZ7+O7m6s73hYzFm2xkMr7y+ZQciVtHaegxXTWu8QfSwpbmqxGmbWz0qsS5FmL39uAvzffY6wvxp8j6v/30bHx2/Ydt7xyLe9GF+LrFHQPzBw/HV2xfsj5b2h3fSTdOWI+ciXec61q4tOtMPH+0/64s/9PzyWV7/AXfn97I

RNG Seed: 2192743532

Trying to cast {SpellID: 49271} but GCD on cooldown for 79.259056ms, curTime = -1.03s
Stack...

**Comment by jarveson** [comment]
#3838
