### ISSUE TITLE
Crash Report -202008085

### ISSUE THREAD

**Issue by benspoze** [wowsims/wotlk#3822]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVV1MHFUU3nNmWWaPBYYLheFmwXWMBUdLZmdcgRozK9rWajTYRm180ygP1aam+6J9MBtflPpQSRsbaf0jButPYruJSSmiiNhII4jSNv4kxJZICSkpMTYgNeqdv12gpIZYX4x3JjPnfud8Z87fzFBMxka4G14G+AnPhw8BHAbsAxgBmARoZjKoEEcDGiElrFpgK7AQ/6T4eYi0PPXos0/slAuVQv49UIny5W+onq/WIl/044/dSFFlegI1yRFXKSeE7my1JvVMOLtjZ1DdW+PpSpSvhW5O8N4cRHFSkbJvHNWDTAsf78aQ2M5OoLovpoWFMiTM91xALXqkG71TAF8Jfpvgi91xF7h0AdVXYi5wxA1k7JwfSFjp/cO5fnrMuQ6PO8GMnkN1vjoI9LtfUJ2UA+vsr6gVyWBAS3hrwTPwIkAnXkTqw9D/6x8tZqyUsSsig4JPw2NrqFzGTS6WaUk94AmpFC+WgZOwkVSMi47thuuNpGUZRiJpWmbCspIJyzQtIyGEtYaRFIdhJc6CKvcMoDLyM6p9Axi/NIZ189+iMXQKJyE8A4UdEOrHQVmVqIJkHqGwvH9Y0ohkiqy16huS6Rx+OhPgZn3SyOOzOTxRb1hpZvPb6UZWS4peLEcYrgs5VoSCUdYJChXLbRXxP4MF/DKE3SQSraUaFlvqwkyT3AkFJAkC927M5AbVshsCRddzVKVXClK0A/2guQiNwiK2NPcs2Hp+JzWxBop2gmMz8b5EldpqKsteHh6V6iV+CIUk6Lck0tznsDngF4FGgY1A8PjhCvoceB9QNOu4dt9DX5zqzYkHu3Ki84r64gfvSYH4cV6cnskZZHO28skPwwHa25azfTcvvp0Xx4RYoZfLwKL93oPaJKcSBE1Uqa/O4zM96NU5YZjVfnPfegE9SflIuCnkXpKshd9Pd7FmWuV0Phuk7u5MhzZyQlpauYRpBNA9PmQaXjGFNVvHG0lj8QU+vslI7gAUuAQ3MCvdzDyNErTV2J5mD/MH6V62KeinGMjFQzAbDEF9kxghpiu+Tx9rTFORdk3AfumUFIw128jX022siVS9QlDkbX5YC4jLOVviSNxZklvuO+GplL1iLLiuLh7TKImiiDH1iuLYsJu5TnFWE3h0muGUsCBf1Vv9EgoVq+KVVMSCRJT2Ibedzp3V8TUUYzxQvfEZLkg5Zylgdi2vpjK91E/Kj8lMpoNPAKvhMTfr8MKsGzz9yYz0A4Q6MKS1S1Hvw9WaKvW+b+Wpqo5XnTVoN3nIiH1dq7tO2+YZ3BXZuGPn9h1PxreoEf1f/gHVtaWuhpvM4MDf+NlyJX3q6IHWO65GHMstr8YPjaf8J8zZm6/4Y298fPNrmT1j9mJ0xt4wu//oZO+oXd4+bx6af8c+gNuGzPum7N3Tr8/83jVlL+/tv7tW/mN/ZMWMvwAo1W5f

RNG Seed: 533527055

Trying to cast {SpellID: 49271} but GCD on cooldown for 59.331633ms, curTime = -1.03s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6...

**Comment by jarveson** [comment]
#3838
