### ISSUE TITLE
Protection Warrior - Stat weights calculation broken

### ISSUE THREAD

**Issue by mmikleusevic** [wowsims/wotlk#3824]
**Describe the bug**
When trying to calculate new stat weights for my prot warrior, nothing happens

**To Reproduce**
1. Go to Stat Weights
2. Click on Calculate
3. Nothing happens

**Expected behavior**
You get new stats weights

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/protection_warrior/#eJzjYnBisGIQYpD6z9rEyBaQk1iZWsTBKsApdYiRi1/g4yMmiVeySmxLDjOd38HExSJw7iETF4/AF6DwY1kl5hNAMXaBfc+ZJE5zAFV/AAov5Fdim7GT6dwOkLrfn5kkuuQg6ngEup4xSSySVGIGmcQp0PiMSYl5xzMmoL5JQIl3QFuAEr93gAQufGOSWCCpxPZsJxNIBYvAJjC5/yGIPPocRDY+Ahn5FKjwPIcS87X/IN7tr0wSnVDrWARWf2FSYq1g7GBkXMT0lYnrABPDKKAICBmQqqOKYRUjBxeDFIsCkwNjF2O4sYGRgZGxARADCUyga2xkamAAlDIFUYZA2tjQyMDUwNDY1FAXmwYoeMQowbHiMpPArMtMEtMuMyns+c+k0XyZyeDlBZ4XjEwfGDlnMTIcYmKSYNzByHiLUYQzFATm73UQhLiSyUGBbRYTg1I3MyeY35AGkxFxkJw1EwRO2ltCRC7YK6aBwTV7o9tMCsESrFo0TlganQ7UMKbh5BEC5gRTxR5yACRs9753cITwf9gnMAaNZlkqANKzbBQOHR/sUWkEAADuSIuy

https://imgur.com/a/cXVmfyK

**Desktop - Browser
Happens on both platforms

**Comment by vandervan** [comment]
Duplicates https://github.com/wowsims/wotlk/issues/3990
