### ISSUE TITLE
Crash Report 1232200095

### ISSUE THREAD

**Issue by Krowerx** [wowsims/wotlk#3829]
Link:
https://wowsims.github.io/wotlk/balance_druid/#eJztVV1oFFcU3nNmNt49McnkanS8bGwco8hC4p07bqmtZrYFaRCEoA9Vn9qH+tQHaXxRENaAYvIg/lHapVToU6EtrdEKEYp/DdUHfyJGqqI2Fto8CN0WJWEV9M7MzrLJohDUF/GwLPd85zvfOWfuYYbaGVoo8R3oho2wFfMA+wH+xPvmz4CnAa4AjAN80MygDSXkoCdgwXcAPCEe1PdBXc9nn2z/9HPGLBB/ADVZv0yifb/VqRs+i7eGkFLWNxPoGMP6ONsa1LF7rY5xK/SG/kd7oOxx67b2JludlPaiHzVYlzT2NXdM7SW0e0KnH0475tHA5VbfBNoH0nGGBnX145rSr6trLyo5kjfsL9JRkZR15x+Mj/+N6WOQZFqPx4L/gxOBwI9adN9Cp66smNCBEw/QqWcgocfcaO4F+BYfIp3GxBt7IeNyphk7GAMLbdwKqoWagr1dpneyO9jJ8yD0ZQ3AR1lXKiU9V2U9z/Wkp1zPk1lPuspzO+RzrUPJrJQBtTZ2D2yWv4vWjVNoXzuFbYVRXHbuKsrfr+I4mEWoL0CaBDWy/nltT2IDzqLG5+bO4vGkbVALMVFHJrteQidFsyjZoTrf7o1h69DJGHY7sxWYXSxVw3ypaCcr08iSHN9NBATCbK+waoqnhQh5Bse1ZZ7bGwpeLiEnEdU8cga5K5bTErGY5mXmanbqJASBH/oNkSSDQFFqMEDYtZ/MMH24z+RviVaaw5upKdNQbiTkypAwcsTgOdFFK7ii2Q4RU2F6CWl+pkXTowpszyMst+VS6qBRBQVc7ovV5HF3mkLQY0Vht6bHPUYCu6sEPhRr6D2xkpbwxVPT9sRp2aq6Nc9KhUJ/f29wJSQt5e3V5GcMouJ75AvEfGrg9dMHGynVhOKW9TVHd8Ybp85cGWit6KYuvooaHJ1cqPQSXxtOmW0FzRmEmq2oVAqbmKJT6a+8GgHtPKr+8ptO5W5CooAJ5y9MhUB+S6453u8Fha8Cu+CvjJAr/qItoV331TFs22AnM1++2jdmcVfuZcjkL/z2UnRmYtEz+/Xf3PuRP+l/DOuf+42R+aPbOteP+js3PRy6OTDqR2jRn85btKt4aZU95nfdWVfccHG8Jv6628y/MZtnnPEU84YzIA==

RNG Seed: 1123943458

Trying to cast {SpellID: 48461} but GCD on cooldown for 56.163483ms, curTime = -1.5s
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0xe1540, 0x2a70280})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims...

**Comment by lologarithm** [comment]
change your APL to not try to cast when a spell is on CD :)
