### ISSUE TITLE
Mage Sim hit calculation seems to be off? It was perfectly fine until I switched some new pieces in and now something's wrong.

### ISSUE THREAD

**Issue by bobstaman** [wowsims/wotlk#3831]
I'm using the Mage Sim https://wowsims.github.io/wotlk/mage/ without any issues until recently. Had a gear upgrade, put in the heroic Reign and heroic tier gloves and now the hit calculation seems to be incorrect. I've tried switching out other gear pieces with it, checked the settings, the enchants, gems, and for some reason the calculation is incorrect. I've never had this issue before, any time I've used the Mage Sim it's always shown the correct % but after this gear change, it's wrong. On my character I'm at 401 hit but on the Sim it has me at 480. Even after calculating it all out, each item individually... the hit is still wrong lol. Any idea why this is?

**Comment by lime-green** [comment]
@bobstaman wowsims includes the 3% spell hit debuff which amounts to 79 hit
