### ISSUE TITLE
Crash Report -531952872

### ISSUE THREAD

**Issue by wkelongws** [wowsims/wotlk#3833]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVl9oHGUQv/n2crc3NsnmS5psPi7xumATVxP29jxzV5E9o7VWUc4UtfimaB6qpdJ70T7I4YtefdBgsXit/4LEWgvagNDWBs80ClETz7QGsRDaRmoIKYRgTHoE4rf/7pJrqATrizi37M7+Zn7zzTczu7cYFEkMHoA3AS6QGe8RgM+B5ADyAFMAnVQEGUJEgxgkuFcSdgL1sPmqV8CXfP6pl57dK/olP7sIWC2NXCXyTJPi+2aQnD9JMCDNzBFFyHF1g/Q9t11qUoTj1l12icgLTbatWvqR2xY574Nh8i0HKqUDk0Q+TBXv+DLxoCQtzxH5QFDxcy4/PJxR+JMogfPW7XErxA88RMYOwQ8OXOCct4OKj6+Qs3IpXOa52GlN/O6k5ZXm58zzV6fMpI79RuRCMcVfeIAp0aZ4pf4/iFIpggZJ786KF+E1gF4yTzBHPP/LPxKqrZexzyeCRF6ApzdjnUi2W1g6mXjUVhIJViUCQ+4jyCTEO7YfurRoRIto4aiulUlbRIvynxYJm+dwJML9wmHr0KLhtnL3klwCWTw1RKTTQ0Q+M0RCV8dI69IY0fJjZAq8s+DPgmeQDIuygPUoMh96xYOjgoIooq8t0t4RTRXx8bSL6+1RrYQvFPFwuxZJUYPdjbfSFpTUKtFHyRaP6YWEM2p7QcIqMVMfWnYF2DUIvY3XpQWbabA8hJ5CsRcqUOAEZl+ozjRsobe4hr6XsVFt4KRAljhJM54aenluKWZ70K3sXozTDgz0gulz+VMBG5SNWNt/bXpYo1Y7KfiR0+8Ip5jDoYvA5gHPAs2Du/xoPZ4BlgMM9JuhrQfWUacHiurhvqI6OllUjx0VXPV0Sb0yW3ToL/qK5z7zuuhApuj7SUn9qKROcLVerROBBgbthTKCWQmEODaoG0v47JfErnNY05uc5n74KrE16Qsexs/sTdIkewTvo524wex8v7t16043afnvhPLKhXXNhR50IF2zi8m96RYWQ4WGVsT4KS1YA1BhEazEIqlOalskt63a7hR9gj2GD9Htbj/5QK4eggV3CNrjfISoKjkxHSyWwkrlJpf9+s+CO9Z0G9uKd9E4ymo9p4i7nLRWENcKVhaIX2mURaxnwjZJb/GxYKq8ekwDyIvCx9QuiulDb2cqhmizG9FshlnCilJV73RKyE20kTVgJXU3IvWMWO00r7SVbcYgZa7p/a/Jii0XPTlMb2ZNWKvWOJtyctKjKfcVQJtZ0Nq1d+WuO2z7ubTwK3iyxKP0CAH7PdedqLFfh3WJxuw7pgwbcRvJG5u6LRk39Itkn2/bnr279zwX2iH71H/5/6o1k7gRYdLDQ38TZ8f17IkTh7rvuRF5rCV2jR+fTDgrLBpd1/0OiD3T9W76jQljNTpr3L9w8MTUwFmjrqegHyl8bBwiu0b0h6eN/Vfem13qmzbWjvbflfV/Bzy5bsZfO817hw==

RNG Seed: 1371925393

Trying to cast {SpellID: 49271} but GCD on cooldown for 348.558014ms, curTime = -1.03s
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug...

**Comment by jarveson** [comment]
#3838
