### ISSUE TITLE
Pet scaling is wrong

### ISSUE THREAD

**Issue by romanhallo** [wowsims/wotlk#384]
**Describe the bug**
I think that somewhere in your code is a wrong number because the Pet does wayyyyy to much damage. Maybe its even ignoring armor? i dont know.

**Sim Links and Screenshots**
https://gyazo.com/b7ded4499dfcd0da6eaebaa2713b2b19 I think that if your pet does more than 60 % of overall damage, even if its bm, cant be right.
https://gyazo.com/ea8518e9a61e63342f56885d05fa87d5 Thats how it looks for MM, still way to high pet damage, 30% overall.

**Desktop (please complete the following information):**
Windows 11
Chrome

**Comment by jimmyt857** [comment]
When I run the sim the pet isn't doing even half that much damage. I'll need a settings link to see what you're doing.

**Comment by romanhallo** [comment]
https://gyazo.com/d2600a9a7d73f2351c13854e895767f7 https://gyazo.com/b66f0c928149e09b90bdd7189663503b
