### ISSUE TITLE
Dual Wielding hard hit cap still have misses at 27%

### ISSUE THREAD

**Issue by d0ntee** [wowsims/wotlk#3840]
So as it says in the title, melee hard hit cap is 27%
8% default and 19% penalty. I simmed my enhancement shaman and got to 27% hit, expected to see 0% misses but it said i had 0.3% misses on autoattacks. Eventually i increased it by 1% and checked the results:

27% hit has 0.29% to 0.36% misses
28% hit has 0.2% misses
29% hit has 0.07% misses
30% hit has 0% misses

I'm pretty sure that it's not how it supposed to work. Maybe it's a problem only with enhancement sim, didn't check other classes, but in my opinion it can misslead DPS simulations and do not provide fair data. 

Build #1 (~27% hit)
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE9IFGEUn/dm3J39WPNrkZg2NR2iZKGYddnSQ83kqaLDUBerQ/ZPCioWL1kIWhT5JyJEjTYPkqAmUlkkbSFIWrGGtSfJyjRDspMrGIkXezujEnYISTv1Zn4f78/3ft+bx5uPZcmoQS7sAhMLIYTlACP4TnoA2A0QAxgHyPfKoEAmZoMBBRAC2tII0ArwBMAjeFudl8Bhnj5y/kSx7ORO72dgKbzthqh8S1cdnT3YGUHm4g/rRFVMqG7eSrGRdFXssqyhalH5MWel8HaKTSfyIjgwiyyZ99WJypUMVSKHwDh/Rrtr01Qn7e5KeFJ4x3VRdTVHkd4hi+IuUUzYFDbnzWuiUp+mOuwcqqW9WrTPc/HRyjlV4o8qRVpbaHXzy5TSv1Bi/S+WxMNVopqcaJopFUglUAFwB78j60bhv/yVeLSlZlxwy8BRQRpHGsoaqAVWysG7haEsEpAgEYCQRHAQkgkuAiOsIjiZoGGexWaUGTstJdRi7LYPOGCYNPKnbO9VoziNpuFLnT0NwxH0uHkDWW/I6ohgCXhTZaQ/BbIxh1FlYkLXoAo2acGAFtC0YM7mgBakJ5AwNM0fICXg9wf8tGpB/yi45Z5e5E97UXk9huMgxcEZhh2MM0n+GgePbJeVaizyGOZvnsMGc9ie5yi8ByGMglotuqxgeZGxep5pbfhWQqK63QQhpmcVWTKg53zAzP2K7Fvh0Y5fNJaDpjzauyw8KyF2b7sm5gZMmNYLYZ91aXy0uj+p325Mql0fmtbnM6KHNsTy984s2J6tvo2lo1P6ImKhreZTPK9lUs+t8FWdmX25KB7Xjw+Os6azM3pwUCrMODmmD0P3/b5XU3pZ/+NtqWsm9Rf3mo/G1iUZK/HV/0I82h7z7YC3wWNsb8o9d8wUjD9lHFzyNfMTX+HY2g==
![image](https://github.com/wowsims/wotlk/assets/136107478/61f5cdb9-0324-4a4b-8b6f-aa68298f6dcf)

Build #2 (~28% hit)
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnNm3J29rHlbJKZNTYcoWShmHbb0oWbyqaKHpV6sHrI/KahYfMlC0KLIn4gQNdp8kAQ1kcoiaQtB0oo1rH2SrEwzJHtyBSPxxc7sqIQ9hKQ9dYbvcn7u+e6Zw7mXZcmoQS7sgiAWQgjLAUbwnfQAsBsgBjAOkO+VQYFMzAYTCiAEtKURoBXgCYBH8LY6L4EjePrI+RPFspM7vZ+BpfC2G6LyLV11dPZgZwSZiz+sE1XRUt28lWIj6arYlbCGqkXlx5yVwtspNm3lRXBgFlky76sTlSsZqkQOgXH+jHbXpqlO2t1leVJ4x3VRdTVHcSiC7VGL4i5RTNgUNufNa6JSn6Y67Byqpb1atM9z8dHKOVXijypFWltodfPLlNK/UGL9L5bEw1Wimmw1LSgVSCVQAXAHvyPrRuG//JV4tKVmXHDLwFFBGkcayhqoBVbKwbuFoSwSkCARgJBEcBCSCS4CI6wiOJmgYV6CzSwzdyaUUIu52z7ggBmkkT9le6+axWk0DV/q7GkYjqDHzRvIekNWRwRLwJsqI90UyMYcRpWJlq5BFWzSArqma1ogZ7OuBejTLUPT/Doput+v+2nVAv5RcMs9vcif9qLyegzHQYqDMww7GGeS/DUOHtkuK9Vc5DGDv3kOm8xhe56j8B6EMApqtehKBMuLzNXzTGvDtyyJGnYThJiRVZSQASPnA2buV2TfCo92/KK5HDTl0d5l4VkJsXvbNTE3YMK0UQj7Eo/Gx0T3J43bjUm160PTxnxG9NCGWP7emQXbs9W3sXR0ylhELLTVfIrntUwauRW+qjOzLxfF48bxwXHWdHbGCAxKhRknx4xh6L7f92rKKOt/vC11zaTx4l7z0di6JHMl/vpfiEfbE3w74G3wmNubcs8dCwrmnzIOLvmZ+QmGZtjg
![image](https://github.com/wowsims/wotlk/assets/136107478/d816b16e-3299-4bd8-81e2-411e2f50b30d)

Build #3 (~29% hit)
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE9IFGEUn/dm3J39WPNrkZg2NR2iRChmHbb0UDN5quiw1MXqkP2TgorFSxaCFkX+iQhRo82DJKSJVBZFWwiSVqxh7UmyMs2Q7OQKRuLF3syohB1C0k69md/H+/O93/fm8eZjWTJqkAc7IIRFEMYKgGF8J90H7AKIA4wBFPhlUCATs8GEQggDbWkCaAV4AuAT/K3uC+AKnTx09liJ7OZu/2dgKbztmqh8S1ddj7vxcRSZhz+oF1XRUr28lWLD6arYaVuDNaLyY9ZK4e0Um7Lyotg/gyyZ99aLyqUMVSKHwDh/Rrvr0lQ37e60PCm846qoegaj2B6zXnLcIYpxh8LhvH5FVBrSVJeTQ7W014jOeR4+UjWrSvxhlUhrC61efpFS+uZLbPjFknikWlSTraaFpEKpFCoBbuF3ZF0o/Je/Ep+22IxzXhk4KkjjSENZC3XAyjj4NzGURQISJAIQkgguQjLBQ2CEFQQ3EzTMt9nMcnO7rYRbzJ3OAfvMEI38Ccd72SxJo2n4Uu9Mw1AUfV7eSNYbsjqiWAr+VBnpT4FszGVUmWjpGlTDBi2oa7qmBXM36lqQHt0yNC2gk6IHAnqAVi0YGAGv3N2D/GkPKq9HcQykBLgjsI1xJslfE+CTnbJSzQUeM/Sb56DJXI7nOQrvQYigoNaIHjtYUWyunGNaHblhScxwmiDEjaxiW/qN3A+YuVeRc5Z5tBPnzaWgqYj1LAnPcojT287x2QETpowi2GNfGh/t7k8YN5uS6taGp4y5jNiBdfGC3dPztm9zzvqykUljAbHQVvspkd8yYeRV5lSfmnm5IJ4wjg6MsebT00ZwQCrKOD5qDEHXvd5Xk0Z536MtqasmjBd3bx+Or0kyl+Or/4X4tF2ht/3+Rp+5tTnvzJGQYP4pY/+ir5mfrP3Y5g==
![image](https://github.com/wowsims/wotlk/assets/136107478/f484ec1e-7de7-4ded-9408-e9e9a4f6f012)

Build #4 (30% hit)
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnNm3J29rHkbJKZNTYcoEYpZly19qJl8quhhqBerh+xPCioWX7IQtCjyJyJEjTYfJCFNpLJI2kKQtGINa58k+9MMyZ5cwUh8sbMzKmEPIWlPnZnvcn7u+e6Zw5nLsmTUIQ92gIVFEMIKgGF8K90H7AaIAYwBFPhkUCETs8GEQggBbWkCaAV4DKAIvlb3BXBZJw+dPVYiu7nb9xlYCm+7Jqrf0jVXZw92RpB5+IN6URMTqpe3Umw4XRO7bOtjjaj+mLVSeDvFphJ5ERyYQZbM++pF9VKGJpFDYJw/pd11aZqbdnclPCm846qoedqj6LzkuEMU4w6Fw3n9iqg2pGkuJ4dqaa8RnfM8fKRqVpX4wyqR1hZavfwipfTPl9jwiyXxcLWoJSeaZkmFUilUAtzC78i6UfgvfyWKvtiMc14ZOKpI40hDWQt1wMo4+DYxlEUCEiQCEJIILkIywUNghBUENxN0zLfZzHJzu62EWsydzgH7TItG/oTjvWyWpNE0fKl3pmEogoqXN5L1mqyOCJaCL1VG+lMgG3MZVSYmdB2qYYMeDOgBXQ/mbgzoQXoCCUPX/QFSAn5/wE+rHvSPgFfu6UX+pBfVV6M4BlIc3GHYxjiT5K9xUGSnrFRzgce0fvMcNJnL8TxD4R0IYRS0GtFjByuKzZVzTKvDNxISNZwmCDEjq9iWASP3PWbuVeWcZR7t+HlzKWgqor1LwrMc4vS2a3x2wIQpowj22JfGB7v7E8bNpqS6taEpYy4jemBdrGD39LytbM5ZXzYyaSwgFtpqP8XzWyaMvMqc6lMzLxbE48bRwTHWfHraCA5KRRnHR40h6L7X93LSKO9/tCV11YTx/O7tw7E1SeZyfPW/EEXfZb0Z8DUq5tbmvDNHLMH8U8b+RV8zPwHawNjF
![image](https://github.com/wowsims/wotlk/assets/136107478/ad2def6f-6231-4289-be02-448650a663e8)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser: Opera GX
 - Version: LVL5 (core: 102.0.4880.90)
 - Chromium: 116.0.5845.188

English is not my native language bit i hope you will understand all my takes on this question. Thanks!

**Comment by jarveson** [comment]
clicking on ur first link shows `Melee Hit	808 (24.63%)` , may have been a display issue thats been fixed or a browser issue?

but the reason you see misses is because 'item swap' is enabled, but your offhand is needed to get hit cap, so the first few hits with the snapshot weapons you are not at hitcap, the other sets where you no longer see misses are where you dont need the hit in the offhand/weapon gems
