### ISSUE TITLE
No longer able to overwrite previously saved gear sets

### ISSUE THREAD

**Issue by jasonhesse** [wowsims/wotlk#3848]
**Describe the bug**
Overwriting previous gear sets with the same name no longer works in browsers (still functioning in the downloaded exe).

**To Reproduce**
1. Open Wowsims in the browser.
2. Load a saved gear set by clicking on the preset on the right-hand side.
3. Change one item/gem/enchant.
4. Click "Save Gear Set" with the same name in the "Gear Set Name" box to overwrite the saved gear set.
5. No save occurs (gear set overwrite doesn't happen).

**Expected behavior**
Previously, this behavior would overwrite the saved gear set in the same location in the saved preset list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 118.0.1 (64-bit) & Chrome 117.0.5938.134 (Official Build) (64-bit)

**Comment by Foknetics** [comment]
```
Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at rl.addSavedData (https://wowsims.github.io/wotlk/bundle/individual_sim_ui-4ca9acdb.chunk.js:1:351620)
    at HTMLButtonElement.<anonymous> (https://wowsims.github.io/wotlk/bundle/individual_sim_ui-4ca9acdb.chunk.js:1:354410)
addSavedData @ saved_data_manager.ts:93
(anonymous) @ saved_data_manager.ts:250
```
