### ISSUE TITLE
Crash Report 1499469420

### ISSUE THREAD

**Issue by jasskin** [wowsims/wotlk#3860]
Link:
https://wowsims.github.io/wotlk/shadow_priest/index.html#eJztVF1IFFEU3nPuuM1erb07pkyDG9tAKIIwu9tCvTRrTz2F6Yv4kkr1YBJiRSk9mFSmayERhYtUiFCUlPsQtUUk4oI/GSIRomLiQ5mZLEG0gWV3Z1YzDEtS6KHDcLnnO9/33TNnmEuzRWSo4U7YC4VQgTUATQATOCzcBugA7AQYBBgGmALYkyaCDC7UwA95nF0MFcBZkkV5KdaCNa+8pOpQpWhjSco4UDt72ETkGadqjXRhJIzUxtoaiUpCfJvCwrw26VTJqJF1B4jckMjs7AmvxbiOM+PARjbKyy2SKvDMwtNHvH4lQxVC8dTOHgSIauN786ESO99I5DqngUVMCzsLcOxqhuEZMnqZCiR6sbHxemIeLbD2esLXp3xNYfe45IXTJAnsRiPh1LmASVWZCBrkCYVJp4BP7AJAK35C2omW//FXIWmrVVQni8BQxor4h8jfRAWRMFCsHAQXNMB2zad5PZrXnZPj9fg0j1fb4fbwlS8er9vn5juvzz0JsnirH9n9fpRb+9H1fgizZoZQmx3CKRCikByEIsq4d3gAJNE8OKobyJu7ZAkic+TMRZTYTz36y/xUoZvE+nTX/EIs8enCOpQJdVCrIlCUHeoGmkRJjvsYTaWiYjUPWQ7yXhZBiSomeDOGkqQwap1GQsFtYO1fUHIpWxewWkjlYEsMFdsdSGiyQNqsSFTsAu4nBk8auq+fUZKV9GV87sf5aUoqtT02gEgXMQTzXGDYlCVsF1v6gXLxYlMOxU6T+hBFU349hj3YA4N4cAQsQbSorcRmjKiz1O8wh7XbvyXYHI9efZeJDOrbDhvxSvd8xIqzl7Dalnv0RGlmSWXJEVeBLGav81+ZVe9fC5ua3u7f+BSsVJ8Yma3KXYs+fhXGqIvPzfibYeB5PMb0xFkxPX/Fe+9bVcd4y/Eevbwg8/TlA691E43qk42Ruf1vQ88WeGUZbddqLdN6X3hubN+7D/p6vcm/Gqu/94oSiugfz+o7yWv7mw==

RNG Seed: 2002195143

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 45 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x10
panic({0x11b4e0, 0x1755870})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*APLActionSequence).IsReady(...)
	/home/runner/work/wotlk/wotlk/sim/core/apl_actions_sequences.go:45
github.com/wowsims/wotlk/sim...

**Comment by jarveson** [comment]
'Sequence is Ready' needs a valid sequence created with that name. Or click 'Default' to reset apl
![image](https://github.com/wowsims/wotlk/assets/536093/79c27b59-e971-4528-916c-0b1e7cff57a3)
