### ISSUE TITLE
cant overwrite saved presets

### ISSUE THREAD

**Issue by Barrelush** [wowsims/wotlk#3861]
**Describe the bug**
When trying to overwrite a existing prewrite by saving a new gear set with the same name, nothing happens when pressing the "Save Gear Set" button.

**To Reproduce**
1. Save any gear set
2. Alter the gear of the set
3. Make sure the name under "Gear Set Name" is the same and press "Save Gear Set"
4. See error: Old gear set doesn't get overwriten

**Expected behavior**
The old gear set should be overwritten, making the giving the gear set color on the gear set chooser to the right (as the gear equipped in the sim corresponds to the gear in the gear set).

**Sim Links and Screenshots**
https://gyazo.com/a46367529902ccf7b1a0e8cdcd823016 Have gear set "Babbelush" equiped

https://gyazo.com/777e5f8f6e28a452ace0a1b1e0557206 Switched neck from "Charge of the Demon Lord" to "Charge of the Eredar", button on the right for the gear set "Babbelush" stops being green as it is no longer the same as the gear selected.

At this point, clicking "Save Gear Set" does nothing. 

**Desktop (please complete the following information):**
 - OS: Windows 10, downloaded "wowsimwotlk-windows.exe.zip" from "https://github.com/wowsims/wotlk/releases"

**Comment by blooblahguy** [comment]
Also getting this issue. The console error is:
`Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at nl.addSavedData (http://localhost:3333/wotlk/bundle/individual_sim_ui-53b011db.chunk.js:1:351859)
    at HTMLButtonElement.<anonymous> (http://localhost:3333/wotlk/bundle/individual_sim_ui-53b011db.chunk.js:1:354649)`

**Comment by jarveson** [comment]
should be fixed in newest release
