### ISSUE TITLE
Crash Report -45378932

### ISSUE THREAD

**Issue by hUSER1337** [wowsims/wotlk#3864]
Custom Rotation is empty
Stack Trace:
goroutine 150 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:62 +0x98
panic({0x1a197a0?, 0x3a1dd30?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/common.(*CustomRotation).Cast(0xc000e076b0?, 0xc0009a0fc0?)
	/home/runner/work/wotlk/wotlk/sim/common/custom_rotation.go:124 +0xcb
github.com/wowsims/wotlk/sim/warrior/protection.(*ProtectionWarrior).doRotation(0xc000558060, 0xc0009c4b00)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/rotation.go:20 +0x30
github.com/wowsims/wotlk/sim/warrior/protection.NewProtectionWarrior.func1(0xc0009c4b00)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/protection_warrior.go:62 +0x6b
github.com/wowsims/wotlk/sim/core.(*rageBar).AddRage(0xc001154b10, 0xc0009c4b00, 0x4034000000000000, 0xc000668080)
	/home/runner/work/wotlk/wotlk/sim/core/rage.go:138 +0x29c
github.com/wowsims/wotlk/sim/warrior.(*Warrior).registerBloodrageCD.func1(0x29312328206e6f69?, 0xc00081db5d?, 0xc000667900?)
	/home/runner/work/wotlk/wotlk/sim/warrior/bloodrage.go:27 +0x4d
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x1b4f1a0?, 0xc0009c4b00?, 0x1bfb4cd?)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:530 +0x4f
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func3(0xc0009c4b00, 0xc0009c4b00?)
...

**Comment by jimmyt857** [comment]
Fixed by #3866
