### ISSUE TITLE
Crash Report -1047537812

### ISSUE THREAD

**Issue by kidburg123** [wowsims/wotlk#3871]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVmtoHFUU3nNmHzOnedzcvCaXbFxHNOlowuxs1yaVsmu01CpItIhF/KGC/SEK0fllBYn+0VjESotiKFhjKajFNkF/VA3GsEqjTYjS1mgkaGtrUIuhTUhNBL3z2jwqarX+Ee8uO9/9zuOec+65d4fqVGyFm2AHwNc4oxwEHAQYA5gCaC9RQYcUNkEHbAEeEQtlT0K848F7H73/ETXBEuIroHI28jPqPyaN+IdDOHEISWNnTqOhuLCEfSJlJ5KG0ufNen5BfWeDL+Ns5hzq55OGVjjk2rkapWzXSdR3cyMqZxE5HZXmu+qN6BfutJwd/BYNbc8w+l9JHJHybrl0n29fzubPov5CvREv+ITGnpgLYtHY5HcSSk8UZbNn3d/Rk0gJtiBN5pMyunEJplRfO8r6Z9BYpYIFHbEtsacBenEWaRAj/49/NLh1sRbb4iow7IT71pAhSGJFV1JyX1TY5Mm7OvK3+SCfz4MoUyHQwhRa8AxcYWUzGctKZ+2Mnc5ksumMbWestATNlpWVHyuTPgG6+m4B2dgp1AcLmFqYxKb5z9AaOYZTEJ2GRA9EhvCcugdAV6iSVBGnqPriqGIkKEZKc9ah6oA83qUYGkm6OdMi6QqKiyihXhFoph2qCTTnpCaRSvHmdItlOTwn1tNq3kjMLFPjHNdFXC1Cy6HKXmBUpnbXpH4NB4gLGH61TL2RGnj9She2Q2ovyOWlgfAf3BYWNfIrQ8G+x6nOrJVGWg8GaQgZGkVlbI7wNfgGcQO18bWk9YKrc/oNhWqNaqrsvzA8qjDLgxC8xNekHRHY8B0onkX6AfgUhMuP1tAEiHEgrd91zd5/B0P4/UAR7t5XhO7ZDeD+15UQvrcIz0wXFfqLuurRA9GQHegu6r62CPcuwkkJa8wqFbg25BF93YpbCYK25fz+Rb7WrC7y6kfjil//tGUng01/5Sn0EXtbuk8IP3neIW6lG3k7lbgd0R+WxJvZrtnYx8rKiqZtK6RuDijb8osstfk60UoGTy3x8WmX4jVGzDPwAss47dyXsHC7rYccfqe4g27hm8J9lo26vDnmwuZoaZOtxU0W+Ay4VodKjVWh9fZjStjufKPYQNfxNtLNGmmiPhCEtcTw95ytcCSfPCsy3lnxRWynbBdh6svb1zuF3tESgQ6/RpiU4g2hR3cz3BLGFqt6bVBCKeJ1opZKeZgIe34ERfDkTeIqquciFL38AS5JuagpaX6ZSFKlWREkFcRkZ53wsuANot7LOro067W+/GiXchgPw5cQ6cGIsV3R/Itua77Cvxur8nU9L7ljONfmM2O5y7d643jOnsDUZj1m/st/Wk3d+Uvhpmu48Cd+Nl+Sdf7O8Gs78FP+en9+PncP3P6HrwOr735uaLbpSG45O517rOrNjd9se6vIP7yePn+181Rub6cLZnIr/fzXx8W/DtwVWEz/5Vr9Bma/azg=

RNG Seed: 2472111555

{SpellID: 58757} failed to cast: casting/channeling {SpellID: 49271} for 62.830065ms, curTime = 0s
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src...

**Comment by jarveson** [comment]
link seems to be fixed
