### ISSUE TITLE
Talent Tree Respecing

### ISSUE THREAD

**Issue by Turbine2k5** [wowsims/wotlk#3878]
**Is your feature request related to a problem? Please describe.**
You cannot pull points out of a talent if this would cause the talent tree to be invalid. This means you have to clear talents all the way down to the talent you are trying to remove points from.

**Describe the solution you'd like**
I would like there to be an error message if the talent tree has an invalid arrangement. This would allow an easier time for respecing. There should be a count of points in each tier to let the user know if they are missing points or if everything is present.

**Describe alternatives you've considered**
The only other way to utilize this is by using an outside talent tree calculator and it seems redundant to respec in one calculator just to move to the other.

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the suggestion! Unfortunately, this matches the behavior of wowhead's talent calculator, and it's done that way because it prevents users from making easy mistakes.
