### ISSUE TITLE
Nerubian Leg Reinforcements - alert shown even though it works in game.

### ISSUE THREAD

**Issue by BorniPL** [wowsims/wotlk#3879]
**Describe the bug**
Shows alert "Nerubian Leg Reinforcements requires Leatherworking, but it is not selected.".
You don't have to have Leatherworking in order for this enhancement to work.
I swapped off Leatherworking few days ago.
The wrist enhancement - yes, for this you have to have Leatherworking for it to work.

**To Reproduce**
1. Be Leatherworker
2. Put "Nerubian Leg Reinforcements" on your leg piece
3. Swap off leatherworking
4. The enhancement still works

**Expected behavior**
It shouldn't show an error for this enhancement.

**Sim Links and Screenshots**
![image](https://github.com/wowsims/wotlk/assets/1348887/f9297588-db6f-47f0-8dcd-e1dcd3e24dea)
![image](https://github.com/wowsims/wotlk/assets/1348887/82394942-403f-4bd1-b6ab-9c92f01e1679)

**Desktop (please complete the following information):**
 - OS: Windows 10 2009
 - Browser: Firefox
 - Version: 118.0.2

**Comment by jarveson** [comment]
warning maybe could be rephrased but theres no way to detect someone that 'actually' has the enchant vs someone that applied the enchant but then swapped off the profession. the amount of people doing that is prolly low enough as well to where this shouldnt be that bad of an issue

**Comment by BorniPL** [comment]
For this particular enhancement you could drop the profession check - the stats are the same as the enhancement that does not require being LW to apply.
