### ISSUE TITLE
Missing sigil of the hanged man proc

### ISSUE THREAD

**Issue by dgamerx** [wowsims/wotlk#3883]
**Describe the bug**
Missing sigil of the hanged man proc buff, not showing at all
**To Reproduce**
Equip the sigil in the sim and run the sim, it won't show any buff and will be as if there isn't a sigil.

**Expected behavior**
The sigil to provide a buff.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
win 11

**Comment by Shaklor** [comment]
Hi dgamerx, the Sigil of the Hanged Man displays as the buff “Indomitable”. Please double check to see if this is displaying.

**Comment by dgamerx** [comment]
When using it, results in a DPS loss from the 245 sigil, as well, this is what shows for the buff. 
![image](https://github.com/wowsims/wotlk/assets/6371564/23eaa679-b4dc-4111-b80c-3b40dfa1df54)

**Comment by Shaklor** [comment]
What spec / rotation are you using? There are specific APLs that should be used for optimizing Sigil of the Hanged Man. If you are using the default Unholy rotation it wont use Scourge Strike to proc it.
