### ISSUE TITLE
Crash Report -436671721

### ISSUE THREAD

**Issue by silverselo** [wowsims/wotlk#3887]
Custom Rotation is empty
Stack Trace:
goroutine 227 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:81 +0x98
panic({0x17e4900?, 0x37e0de0?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/common.(*CustomRotation).Cast(0xc0012e2f40?, 0xc000f7d710?)
	/home/runner/work/wotlk/wotlk/sim/common/custom_rotation.go:124 +0xcb
github.com/wowsims/wotlk/sim/warrior/protection.(*ProtectionWarrior).doRotation(0xc000386ca0, 0xc0012045b0)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/rotation.go:20 +0x30
github.com/wowsims/wotlk/sim/warrior/protection.NewProtectionWarrior.func1(0xc0012045b0)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/protection_warrior.go:62 +0x6b
github.com/wowsims/wotlk/sim/core.(*rageBar).AddRage(0xc000e1cb10, 0xc0012045b0, 0x4034000000000000, 0xc000f3c7c0)
	/home/runner/work/wotlk/wotlk/sim/core/rage.go:138 +0x29c
github.com/wowsims/wotlk/sim/warrior.(*Warrior).registerBloodrageCD.func1(0x29392328206e6f69?, 0xc0012e2f5d?, 0xc000f46500?)
	/home/runner/work/wotlk/wotlk/sim/warrior/bloodrage.go:27 +0x4d
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x191a2e0?, 0xc0012045b0?, 0x19c6c50?)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:537 +0x4f
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFuncSimple.func4(0xc0012045b0, 0xc0012045b0?)
...

**Comment by lime-green** [comment]
Prot warrior no longer has a custom rotation
