### ISSUE TITLE
Crash Report -1807708912

### ISSUE THREAD

**Issue by Allnyn747** [wowsims/wotlk#3893]
Link:
http://localhost:3333/wotlk/warlock/#eJztVFtIFFEY3vPP7DhzUnZ2TJwd2bDpIVlcm511Q62Y0YKiJ8kI8SGQSMgyxSUin8wK0R4i6CG3xLALkRBtL11eMi+BBGVpgQaCmphkuiQbViSduQibSCXZS/Q/HM7/Xf7znzNzDvaywIMCeWgXKkU1UI/QHQSdCPUj9A6hIjeLRJSJFKQbNLqJkEC00hTbgJjiI+UnDtayTp6VBhF28e1xEKe9MtPbBb0PAHN84zjI1BsyTeavE27Ma2VJ/OnzlNjsxQLfEgNx3itzRE+YKCFT+NE5EC8LMk0wB0lvEOdtj0xHjdTFRz+BzFlaQ+7irxH+yjqZiZolCPB5lgAe0oal4PiRSbsNjr9ndGQ0R/PPxo0xMm70c4pYvnhJeitmqGZGLYPMsmTnxXSpsx3igDvB8T/+KARlpY468gl4EKEGVWLskBiS0SJqRhvVYEhRFFUJkiEYCihqyACCwUAgFPD7QwapKKHAGBLZ1kaKH5oAcWACMhsGIGvhJSgnB4D83jG0JoIcXdBMiRROxazEYJod7qHkJOzElD83TEBGojGIbpnDBPSrOaEwTrOVj+OQAAu0BAUOAUsW2XqWErxSBnb7XKxTgN0OySy6WQmb9Nc4CGlSapGbzHvjwCOLVqrCwjZpCw4Im3CyjDGr2uKEbJ5kS6qqqlWVUEKBlIdzhGyc7ktjKYF7iAxiaIYyBBiC4aXegN0R2bewVSrAipCDPb504mUrDbw7DhIXAXtqupkEt71yt7UfzN0113v0wVyPffEj/K2DNuERAi8e1OOEOemhyb5l+fowckTAIbdRnAnolbrbotbqnkiLEX1avoX0a+srzHitqbNQM30O6pid1bVV1YczS0TG95dvblaTvhpl6vt6flGn5Ge8fv9SReFq9LFcWOe8b1xvQYeqY2f69r7S7LXmtT3Lvo3vMybnsjd0abMdC2XRJ4NabuGx50cvTmgWG9MWdSlPj+MDVz9q2wfL97cVvdU6dlSkN16Y0pbW+9dj5W9jme2I/fZZfQe4Gu8U

RNG Seed: 2266273992

simulation failed: Active aura during reset: Reign of the Unliving
Stack Trace:
goroutine 11694 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:81 +0x98
panic({0xad4900?, 0xc00c0b40b0?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0xc0028a2d00?, 0xc0060d1640?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:125 +0xe5
github.com/wowsims/wotlk...

**Comment by lime-green** [comment]
Doesn't seem like an issue anymore (possible fixed by vigo's recent aura stuff)
