### ISSUE TITLE
Crash Report -1033390837 [Mage]

### ISSUE THREAD

**Issue by mrbiggens** [wowsims/wotlk#3895]
**To Reproduce**
1. Import my gearset with sim link below
2. Enable batch sim and "Import from bags" this list of items:

{"items":[{"enchant":2332,"gems":[40155],"id":47927},{"id":47921,"gems": [40125,40113,40113]},{"id":47977,"gems":[40155,40155]},{"id":50990,"gems":[]},{"id":50807,"gems":[]}, {"id":51554,"gems":[]},{"enchant":3604,"gems":[40113,40113],"id":45665}, {"id":40255,"gems":[]},{"id":51016,"gems":[]},{"id":47732,"gems":[]}, {"id":51326,"gems":[]},{"id":47922,"gems":[]}, {"id":51910,"gems":[]},{"enchant":3832,"gems": [40133,40113,40155],"id":46993},{"id":47957,"gems":[40133]}, {"id":46046,"gems":[40113]}]}

3. Simulate batch

Link:
http://localhost:3333/wotlk/mage/#eJztVE9IFFEYn++b2XHmme3b2RWmYddsTrIkvNl1wYKYzUvRyfQi0cGoPBVIe8qTRB1WCSMicOkgdamLuCeVCBZJUMLVJKxcElcLBEMXzDAi6s3MHspDZSl06AczfN/v+31/3uO9R8IKNsJJWMQP4kOAIcAcwAzAIuAKQBNRQAcGSWgDTWLQCMbnimsgN186d/XiFcVHRWMBiJ/2bKL+PmLK42M4PopEpY+LaIpZbu6jN3lsKWKK466X20C9J+LFNNpfQn0rYqo89noUHa6KrnDunmZKnBO4m+bpd8KmlHVcP/2yhq4868n99BaPD9SYcmEUCy4xvYj63bApZz1CpcPL6HWX6Ju0yP8vSo6dX3bmub6Oer48nUrnPnKpl7VW9EyTbwGrbJbapHa8j5tIcij8x19BYzvN6FIVoNjJjyc/kkQwZAX186bQA22xOGP8i1sWY4zbP6KesUSCxWPMcjRxHk/ErZijiyes+u3q77EEIWVjCunXKdQfvcPat7NY92yW3wmpBJUZEMZwAXSRBIliyERSBodEs4L4iFgfS5EAkQ2JoB4oU1ZKkww8KmhhwyB0HquIqExecPIINqTc/NU8atVGkKi3RccdKKBL906jdtiIkmotSAJRv+LT8JRguFWtWKopwCW5IZESj2KXU9pBI0KC0YAiuUo1g+XqbrlPvIs7Q3R/WbB9BmJ463mexwmcgHT5rDck50HIoGD2iqpLdHckA14olDyQ6XcwaR/xmBn7UIeLOTtWwNpW3Rfd4ztTl07uRpnuyae/qNO6K33+BN7ePllPHvf8LbsdWn76Go3U3Fg9PbJgF7tCgyeK87bHlmzy8kHnMTJst7iCV3bf2Gbd2b4l21F1hdbsPV/KP4adv0Znyhml396rb3Fn1RQ=

RNG Seed: 2791199586

simulation failed: Active aura during reset: Reign of the Unliving H
Stack Trace:
goroutine 29110 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:81 +0x98
panic({0x1894900?, 0xc0f7f05c40?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0x18d7000?, 0xc0dfb27bb0?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:125 +0xe5
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0xc0f704e4d8, 0x8?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go...

**Comment by lime-green** [comment]
Seems like this may have been fixed by vigo's aura changes
