### ISSUE TITLE
Crash Report 1686012839

### ISSUE THREAD

**Issue by Chim1312** [wowsims/wotlk#3897]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE1EQ3pndbjaLNc+QwxraEhcPoafFkx7krYLosbaXIh7sweLBQ/Vk6yWIkZYIepCa5mhFchDxEmnQQGm8BJTmkLSgHrRF2CLamBoMxb/Z99ZjadTqyYFvd2befN/M2/fWtA1k6OA5GIMUQB7gIcA8QBXAA2gDVhGPsgQ64MIw1UyKmqgSv6ZfAX3g/Mj42YsGMDNeBzPCvE201npt/VEZC0U0wyx/XbXVRXJ3seZN1Xrda6sFEbUyqvWZovsVJN4HWmsTj9aWvqPZzVZpOd1naytFVEzGNii81WOHSKngZyLsSUa1wyUR+oIR9pEk1qWETCwSZ7rH1mURzZL2ZykJ91UucDX2eEqlp9f0h7q3gVY+LkdUKFv8hHbEQKf7IAxow9olf/d3sIXmPCr/7Y8s6vwqY0IzwMJNGDGPZekYYL+JRpgABCSoBJ3QRQgRNMJug67tCbggFRp8XLwny24VMG7t+ZlOQL/iwJGgkbsCljFdQ3a7htb7t5jI1jCZraMzU0cPtAaEcqAsoPIClBwqdkYNC1pq1A0EY+7e3IxvFX5IZqp836iwJX7gJSaGrK7+v3yFklPuTsikKk+30RnakT6/Y/Lbltbd4ODa/AwMip+z3EqevrEQdpdnxw6by6u8U0V5amtc8utb8Bp8ri/97uTcNz4oHI9L3ld+12836/HYg+NvJmLNLfteFgVXO57rX1vUef7MN8OVO/qy7aSngt+50fGefgAx4cDm

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x11b6e0, 0x17598b0})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).SetupRotations(0x30e9e40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:195 +0xac
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Initialize(0x30e9e40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:210 +0x1a
github.com/wowsims/wotlk/sim/core.(*Environment).initialize(0x294d560, 0x2b79b80, 0x2b519d0)
	...

**Comment by jarveson** [comment]
fixed with #3925
