### ISSUE TITLE
Crash Report -1026446527

### ISSUE THREAD

**Issue by tylerthardy** [wowsims/wotlk#3905]
Link:
http://localhost:3333/wotlk/elemental_shaman/#eJztVm9oW1UUz7kvf16O/fNy26Yvl6TGB9rsacrLe4trJiOxOuY2kLghDvGDCu6DKFTfJydIEETiUCdzimXgrGOgDmfDhG20rNYqq2iIY5ubhaGTzTIVA+us2xe971/SdkWdzi/iScj7vd/5c88599yXhzGR9MNdsA3gGzIrfABkHKAGMAMw0CKCDEmSgiJsAsrN2I72ZyFYfOyhpx55UiRSiFUB26WPLxH5x4QS/GSCTB8kGJaO/0IUYdcUwRZpnOvOJJy7kPTceSJv7+Euo5zeH1OCIwfJJHdplU7tEOSdVPFzwsdv584R+dW44uduPm4+9ZKghHnsEfvLicPcv5yw/R3iREmQX4srwQsHyKkDVg6nv+c5WOn4pVpZ4L/nxyxcrROk0iG+2uWEEh5phPRxXWWWKKIIGhT9mwLD5CLBceL7X/6RUO1qPbYERZDIIDy8HBWGHAuykOSbIsJaW18qFu5xQKFQANYmQsOKaPACbNCyhqFpmaxu6BnDyGYMXTe0DAdpTcvyj2ZktCUkvRTpyBnoFEcniTQ+SeTaWZK8dJSkLh8lM+CvQ2gIfBPkgrgLQBawA0UWRL/4elVQQhhAIZ01scsl+YwqYeR02ujjdASDzI9EjriWGROjruUct0QUMZjO9GmaSfNsFS6jvSipbWKQkpU+ywqJZmLHMEjYJpajyd88AXYFQ2/mXerFHhpfHEI3URwGvjx3YM6F6kzDXnqjp9jzDMbUbu4UHiJuGYynhn6em8kcC7qa3YE5ugLDw2DZnHtPwG6lCzsqV6aHEbXdTcEufHnGZK4P3UbYiwR/ADoD3vLVKE4DOwkYrlihpcOHiAetI+3CnXsasPpdA+59V/DgaBP+VG8YVBq24rF9fo8dKzds32nC3U14msOo2ikCDU/YxEhZsDqBkFvI723y3WpXgxc/PSk4/c9oesLd9LeeJw6SPuThQ8wpnhbZ3XgnHcAWayIqXkvsO91yq30mLO5oRtc8ap1L6ZrTZG5NV7J+VGhyXowvS4I9GAHbwU7MMAeoo5G87dYeN+l97F5cT9d6+8wHdeFwzHnD0Zfjo0VVyY3pcv0mtirXed5bjwveuNM1bDXeRnMoq1HuIj7qpjXPcalgiwLxK80ywz4rjkrazseFqfLC8bVPoX20mGtDb2EqJmmPF9HaDKuFgWZXb3VbyFU0xrqxlXqFSK98QZh7pSl2E8Yp81RvfkTmldyw5DS9niWwQ424Rbk56VnTe1jQHha3q/bPr3qFoz9WEo6QI/A1+IaIT9kqhJ1n4uZCxHmMdhZiQ29YMpXPOUwtf8NmW07k9WmS3CgH1H/5/y1VLlyLMKWpyT+Js/GarPN3xOnt2M+F2537X/MPwoY/fHNY9sDLExdTn+cXsvX8053vr/l2y/4G/8Qq/OrtwbP53YMWmM0vjvNfl6t/c7jf9aj/5V79DiZ4aes=

RNG Seed: 3150165743

{SpellID: 58757} failed to cast: casting/channeling {SpellID: 49271} for 83.337273ms, curTime = 0s
Stack Trace:
goroutine 645 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src...

**Comment by jarveson** [comment]
link doesnt seem to crash, can also go into rotation and choose auto
