### ISSUE TITLE
Crash Report 2098421473

### ISSUE THREAD

**Issue by aksdee** [wowsims/wotlk#3908]
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVl1sFFUU3nNnup090vb2trTTm926TiKto21mZ1y7xZhZq4hoNLVEJT6p0T6gBMK+KA9m44tufcAGIrHgX2MqKonQaAJiY6nVWA3NCkgQtRGq0DRgGhLSUkz0zt9uWxpMI74Yz252zv3OOd+cc+6Zu4NRhaTgXngV4BdyQt4NsBfIIEAeYAKgjSmgQpwYkII0tMM6eBxYiP9e/iKE25994vmnNyultJSfBKygX18i6rmYFv5yiPx4gGCEnrtANOkHoS6j3wrb6ZgmvT3irH66QNRt9ZrkuFXQr4RtRsQJ27AAyuj2caLuYposgJBYjgr79qgmC+8QMrr3V6JujWqRg2fIvgPOV2DTgjAX0yIesM+lPSVYXotqYbFyaGX6c04SSY2d9ZOS6ei487tHwKX00FmizsZEbicE1YTi5SbTni5JK1PAgPaSdSXPwcsAveQiwUES+l/+kTBjqRFbwgpQsgmeXIHVClnjYtn29EOekk7zcgU4Ch9JlZyB7YIOI2lZhpFImpaZsKxkwjJNy0gIpckwkuJjWAljEWlaDPTkNKhK/jdCPx4m6uAwiV8eI42XjhBj9giZAHkKSnsgNERGFFXCGlR4GGVlx6ikISoYbrKaW5KZAn48G+Bmc9Io4tMFPNFsWBlm8zvwJtaAVC9XwoysDDleSEREVS9QLFdyNfE/AwF+BcJuFn1pwHoWXUhhZlDphRKURAD3LszkBjawGwND3wtYp9eKoEgP8ZPmIjWURW4Z7nmwVfwubGUtGOkFx+fMhxLWasuxqv/K9LBSr/BTKEURfmsiw/0YNgP8IuBRYHkIbj9ag18AHwSM9DvU9PNPSaBODhTUXX0F1XmkfXXPB1KgflZUz08VHPoLvsqxj+QAHcgVfN8vqu8W1TGh1ujVCrDIkHejnOR0AqEVa/XlRXzqIPH6nDDMmL+577xEPI1+4hw73CuStfMH8W7Whsucne8PSndXphOW/0Za2LmEaQTQfT5kGl4zhTdbyVOosfgcju+ykjsAJW6Am5iVaWOehQbbamzIsEf5w3g/WxPspxjI+UMwHQxBc6sYIaZTn9PHUhks064Lol/5XgrGmq3mq/B21oqqXiNClPV+WnMCFyNbQCSuLMkt95nwTHSbGAuuq/PHNIKiKWJMvaY4PuwWrmOc1QeMzmY4LSwpdvU2v4XCxOp4LZaxoBDafdjdTufKGvkKjDIemN46ROaUXPAUMLuex7BKr/SL8nMyk5ngCGD1POpWLc+tusWzH8tKJyHUQ0JatxTxzrnOdKV3HFan63ped2TEbvWQvH1DpyvHbfMU2RJevXHzho3PxNeqiv4v/1815tLXgiY7Mvw3PGuvZk/v39l557XIYzHxevzIeNq/w4zdcdX3gNRTHW9kt47Z89Ep+57pHfsnBo7a1d2z5u7Z9+ydZP1h84FJu+v8m1N/9E3ai7P9d2Xp7wGPLTniL4Lqd1s=

RNG Seed: 3207617563

{SpellID: 58757} failed to cast: casting/channeling {SpellID: 49271} for 8.084872ms, curTime = 0s
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src...

**Comment by jarveson** [comment]
In rotation tab change rotation type to auto
