### ISSUE TITLE
New Hallow's End items ilvl update

### ISSUE THREAD

**Issue by craignagovan** [wowsims/wotlk#3909]
**Is your feature request related to a problem? Please describe.**
Per https://www.wowhead.com/wotlk/news/hallows-end-holiday-event-guide-wotlk-classic-335605 the new ilevel on Hallow's End items is 232. Confirmed this is true for the rings by witnessing them in game. Have not seen a helm or sword. 

**Describe the solution you'd like**
Updated stat blocks for these items. 

**Describe alternatives you've considered**
I don't know if it's possible to manually add items or not, I suspect not. If so, that would work too. 

**Additional context**
n/a

**Comment by jarveson** [comment]
added in #3923
