### ISSUE TITLE
Missing items: [ITEMS]

### ISSUE THREAD

**Issue by silverselo** [wowsims/wotlk#3913]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item=211817/ring-of-ghoulish-glee
https://www.wowhead.com/wotlk/item=211844/the-horsemans-seal
https://www.wowhead.com/wotlk/item=211847/wicked-witchs-band

**Comment by jarveson** [comment]
added in #3923
