### ISSUE TITLE
Crash Report 200367456

### ISSUE THREAD

**Issue by psychomantium** [wowsims/wotlk#3914]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EY3fd1TTaDodsQZAxNiXsqhcJiL3qQWb3oMdaLiAc9WDx4KJ60XlKxIO0hF9E2goj10JMIBVlrC6H1YMBqwKQB9eAPlQ21dBGKQVSc2fFabLH15GP4mO/nvfn7hjkW2eTSeQyiAEwBD4EyUAUCoAWqEh3ZkyMXHk7qmuvA3agyZWT8XVcRy184e/ncRStus8w0WLv9qUG8mXVijxboxSKxhN16S07brE9st706S/xdVntx+9UT4l+ziiLDLUm5UyE5WNIelZmRLseUniHdQOZvdDqmpBlSZWmGnJicK5V2+7NMrmWjwHIkW5wjfrOTmfbYY5K2Oa1seUbZlZeqoCzVpzLMkIGilEpa5CYPIG9eUoe7R+vEymT8x18h5W6VMRS3wEn21jf0Mi77Elx23THk4QPPVE9SCGQ6OnR5KDhy6DFcjMJ0+3r7PoBbt2tk36oRX12m3HiNusfr5E7UKYAZIlGCMU/GaxglMpyxtkQkUxjwfgumvb2lCYWKOKgjVbFvIMKS2P+Gcie41bPDjREOe9shU6g83RadnYC+27k177D2W+IM+qMvt7Defbo4n/Aak4OHWOOj2KyifrWm0Pz6BrxQ+F0jK8f9n6I/mgRC836I+2q5yUCkHxx9P5T+suG6V6KCa5ve179Gyl18rmB5+kTf/7jTU1v+pL8AwEGzKA==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x11a000, 0x17348b0})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).SetupRotations(0x2871ce0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:195 +0xac
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Initialize(0x2871ce0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:210 +0x1a
github.com/wowsims/wotlk/sim/core.(*Environment).initialize(0x2b74000, 0x285d000, 0x2b48620)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go...

**Comment by jarveson** [comment]
fixed #3925
