### ISSUE TITLE
New tier set creates high miss percentage and lowers dps

### ISSUE THREAD

**Issue by DRG3484** [wowsims/wotlk#3915]
**Describe the bug**
When I change from my ToGC 245 tier to 251 in the slots I use, it drops my dps and creates a really high miss percentage on Whirlwind. It also has me casting less than half the amount of Slams for some reason.

**To Reproduce**
(https://wowsims.github.io/wotlk/warrior/#eJztVF1IFFEUnnN2HGcuq86ORuO02jYQboJwd6YlDGKmeqhHfyIyfKiHpIceRJ/ySYKlVPqD/twgyHrwSSFIVApCDdxAW5AM7KV6CBdBlzV/KMLuzKxLBWE/21vn4c653znfd869c+8lmogUz0IrdAL0AyQB5gHWAZOIh0pCaLPIJTcyDKBw2oB4AYS6c6fPn2kTC2VJWwBSInd9QjVVoQtD4zg1gkSSExnUfY+Z65d7WOxthe4bdGejy6jeDHqxEvkii60z3uwGDrrAUAbVWKUuvBxxAUW+vobqjaAuDbqAl/SciUvTIzi9CXQzmSUmkwNeMZlbwRwgyauLrB82I7yc+eiMCx+c8W7ayZ5l2VOMnitwe+07QJInnOUwVxfZZhXV+U7wfbiC5Bly/+2vTKG/y+jgRVCxzSJRGUIYxoMeHLbrPafJbvKcWjt7qNnpvQ8ettfWBEZjAt1QZRqUGiaNGKZZY9IojZqU0qhBzQj7mBGDQdSMRt6DKvbPoByfQfXODIaebGA4lfTT2AzOA58GjAM3hpdR9ZEAETSeoBrQC0kB8dVE2hVJK9SYK8ZLleMiaA1knxIlgTksJrx4ZRk1gTCC0U583cARubpYFBRs47IwJVIfCF6msp3gscOKp9ZbqojaZoAwXaGad8O8hvs5ZZtWSqRHLnNi0a0hLmdYouaREqOQ6+takVKl7SY7lHIiOV2/QBSB+HVCRMPJTWU8fuob/hLzK7Xgj+2aVBOJIM5lMASTOAlzwMWR03t8krv3nS12wPsLZXZ5vNexhFXrIUlrV4trs5bxBkONakH1P75b4S47HzKdiYktdBrzUudPzNvbp0t29oqsW6egwX21xlfCzVfHCuydsYX64covVn7rpq2j7zrKBo6krFWnzApnu2Viny1nFm4G2/vXvP0zBZbMGPfy3Ff+TKF73KWU2w9bD5DXD/z2VoyT2Xcu/ctr+gqw6ek2)
 That is what I have on now.
**Expected behavior**
Going from 245 to 251 gear with the appropriate adjustments to hit caps should increase my dps. I had a friend do it and it worked for him.
**Sim Links and Screenshots**
![image](https://github.com/wowsims/wotlk/assets/148459129/057b4a23-2640-43b9-97f3-bd95f95046ec)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jarveson** [comment]
don;t see the issue happening with ur link
