### ISSUE TITLE
Incorrect calculation of Spell Hit and Melee Hit 

### ISSUE THREAD

**Issue by Kaljurei** [wowsims/wotlk#3916]
**Describe the bug**
The Spell Hit values and Melee Hit values are off by a value of 46 in my sim.

**To Reproduce**
My sim link - https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE1IFHEUn/dm3J0d1vw3LDFtu6ZDlAjFrMOWHmomTxUdlrpYHbJPCkoWL1kIWhRtWodEg8yDJWh16JMkg2BJK7aw9iSplbom2aVdQcG82Jsdt4MdQtJOveE3vO//m8dv/lK+iBoUwzYIYTmEsRZgGD8IDwCjAHGAcYBSrwgK5GEBmFAGYaCUVoDbAE8BZM5703kOHKETB04fqRSROb0DIOWwkR+ofPOrjs5uHOpCycV6R1Hlo6S62RDFhv0Z61M9rzT5VL49hpLMpr6jMu1XXZ1d2DeLVkY2SyRRuZCrCpTBkTlI5Y0+VaAgRxVXmnjlqk91kUlFVkUOG6aUJJ0ezTgeU9I1n+pI2A6BjVziaajR5NxQAusgh8DufLFGOn+ZV3r99khOFolYFgUfTaKabW0rJJQJVRABuIVTKEWR+y9/JbK20IozbhEYKkg8JDY2QCNI1Qy8GyQUeQISBAIQsggOQjbBRZAIywhOidOwJN3NrDG3ppVwh7ndPmCPGSKuH7e9F81KH9FitMmmBRFadrMWst6R9bALq8DrEZF+ESjAIokm4y1dgzpYpwV1Tde0YNF6XQvSo1uGpgV0UvRAQA/QWwsGEuAWu3uQPetB5e0YjoOQAmczbJGYJIhfUyCL9lgec57HDP3m2W9KDtvzArkB4JqRU+t5l92gwlye6bSy+bolMcNeAhc38o+mpc8oGsS83YpYuMTUTp01F6NNbaxnUfoshdi7fZ6cIxg3bZTDrvSl8TG9/QnjRmtW4+rwtJGpiO1bEy/dOfPLljcWrq1OTBrzGnN3Gz6nSjomjOJIYd3J2Vfz4injcP+41FYxYwT7hfLcY2PGEETvv3k9adT0PtnkWTFhvLzXfjC+Kstciq/+FyJrO0Lv+7wtsrm5rfjUoRBn/qli74KvmZ/NztsM

**Expected behavior**
My SpellHit rating value should be displayed as 444 (with appropriate % conversions)
My MeleeHit rating value should be displayed as 569 (with appropriate % conversions)

**Sim Links and Screenshots**
Sim Link above. Screenshots below.

![image](https://github.com/wowsims/wotlk/assets/148468038/5c299b0e-7755-475d-85bf-3ca20cca4fd7)
![image](https://github.com/wowsims/wotlk/assets/148468038/fc32996e-cd9a-4d62-9b86-47ad3574c67d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Version 118.0.5993.88 (Official Build) (64-bit)

**Additional context**
Other users reported that reloading the page was fixing the issue but it didn't for me.

**Comment by Kaljurei** [comment]
Additionally my expertise value also appears to be incorrectly calculated.

![image](https://github.com/wowsims/wotlk/assets/148468038/52c96b5c-6ea9-4b42-8d1c-bd05600981b6)


https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1oHFUUnnPm7mb2uDE31yWd3O7G7SBaVwuzWbbdCjJjn2rxYdGXqg9G6x9iS+g+tIpgIoox1YeWVjD6UKw06oNKxGIKwtJGSyppI9ZgWjU/tRhfmg2kkPalnpnJ7kN8kGLjk2dg5p7vfN+Zc+8999I6C10owVYoYxd0Yw/ANP4svgCsAowDzAFs0RbYkMX14MN26AamHAb4GOBrAGXo44nXIF5+8cmXntltoWzS54Fa5MxVtP/MOPFjJ3FqGCkhxy6iY1Z5mJRTHJvO1L1f95n2obRjHh1FUvLKZbSXMk7i2DBOXMeA0Sxn59F+o8MRzDDYvcDyg2lHcNBgxTuHTHt/2kmwy6JA0SKnmTLPf6/WgS+Z9G7aic9GgJAzb5lc1MX55aKEHGRAyE9+D0p6/W3THstEJTXJvr7A4+DQIjrNwWqVxXaxF/oAPsQrSFU0/rd/Zcq9UcXLSQsk2sh9yN14AMpUkvBAGOoe9B+MSI/6Ze7X3elgR7mFxqKWU0m5fw7tM+xxZ+4FnbKQuxvWYydxUjMYu9APd7nFgltw3WLnhoJb5KcQOK6bL/CgkM8X8vx2i/lZSFonR1AeH0H7+0s4B6IGTQOwlSQJ648aKCuqJuWvQPzy35AnViLZ5/wT+CPagm4jS8c5NtAvnCaKkbmhUKFWimtBaLcuQ/mKEhrvM1RJb6R7VY7acilLKOuFQPlDjxlkIHQrJHO3WnGF24wIKVX0MkM5OhuqQCVOQAAOf2Rqzk1QDDkTzMnotdTqtFDzEJBCGWP43JsQhvmrSEelnmVqVndQKqcsU8X6TbSEDgvtdCv1yTTYgXKTLtI96m5qz61plH35tKkTxLK86+6sUNIhsoaAk1hn2vQyoZFkcsZU7XoNNTu3UGIorL+3N5x28G3QTv1kngdjAA1nn5mItmeX31rfp/aB9wIb9TZHyLi37tnQJrzOC5h9xLZyq3zma73+zUjTMzpyU/KshkVr+828H51aY8nrgofD2/SXcPUXvPcPxw7e3r3k1RWjj98xvuWhaw1fbczd+crsorcisfHpgd9qmwcXvFJfrn/n9e9WxGve05NzdGTXNa84Kbo6nr/kTUH189OnFr1Xx77alGpb8L797OhT42tj/mrM+r8w5W4rn53QHyj//iOlPTvKhv9Pisdu+P79C6yyB18=

**Comment by jarveson** [comment]
rotation -> item swap, the stats are shown with swapped weapons
