### ISSUE TITLE
Crash Report -1116332747

### ISSUE THREAD

**Issue by RaverJay** [wowsims/wotlk#3917]
Link:
http://localhost:3333/wotlk/warlock/#eJztU0FIFGEUnvd2dpmZiv2d0++its1JAunfXQb0YDN1kk5bXsQIKshDdVg6mV1WI0pPBRG5JERReMhoSVChYFkyEKK0Bakkwd0sMXEHQrGg6M3OeAqDJbtE3+Hnfe+97/2P/71fiyrIUGAztEEHpDANcBXgEWAOYBpgCeBgWIEoCrAhCSkYBtApOTIT6oNQ8uyJ86fOKUGmROZBC7ORNeQr9UZoMo+TE6ipbNhBIzBH5k52j2LF+k2W+4J8gFiWmM4GHeQjtYZKIgq7vl1sbB35Ld2QiUlE75P8ep1Pw+z7KlbSs156mD2k+O0GI5StlCDH1zLyG3XUi5ehsrESevfJ7H1/gM6XJdfOlNx+nl8L8G9+PyqbXffbVtnqgmcaugICmiEpdwS7gV7pCsAdXEMth9J//BF0Ua2iR1GAIccUnG7VEmTLnFa00R0QttGadu6mkQ7Rir2gkT6ZQF1mb8oY8ad59xNGQp5oANrjCVOIeFyImCCTDtN1JBKxmBlrElujyTRdjTB/DRWBK0OXA6ywiPztIkZ/vMbG3gKKvgIugezAjgxIeZT6/c1psd+BlEHJKKFacaS77BovtN+uzQy6mLJaPM+0taerglkr/hij7Ty49+bf3UCn196OMumpZ9tSpxp4b/a0bB/w+IZ1HI789s+ewY3RY62vrKPp0ZMXPy5YntexNuMrh8cbLn2esfZdGH/Q/aFo5ee1Q3PLy9ZW9f5VVP9nO6tW/ASBw7vJ

RNG Seed: 4234593622

No item with id: 47517
Stack Trace:
goroutine 1251 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:81 +0x98
panic({0xe44000?, 0xc000451390?})
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/core.NewItem({_, _, {_, _, _}})
	/home/runner/work/wotlk/wotlk/sim/core/database.go:227 +0x486
github.com/wowsims/wotlk/sim/core.toItem(...)
	/home/runner/work/wotlk/wotlk/sim/core/item_swaps.go:268
github.com/wowsims/wotlk/sim/core.getItems(_)
	/home/runner/work/wotlk/wotlk/sim/core/item_swaps.go:255 +0xae
github.com/wowsims/wotlk/sim...

http://localhost:3333/wotlk/warlock/#eJztU0FIFGEUnvd2dpmZiv2d0++its1JAunfXQb0YDN1kk5bXsQIKshDdVg6mV1WI0pPBRG5JERReMhoSVChYFkyEKK0Bakkwd0sMXEHQrGg6M3OeAqDJbtE3+Hnfe+97/2P/71fiyrIUGAztEEHpDANcBXgEWAOYBpgCeBgWIEoCrAhCSkYBtApOTIT6oNQ8uyJ86fOKUGmROZBC7ORNeQr9UZoMo+TE6ipbNhBIzBH5k52j2LF+k2W+4J8gFiWmM4GHeQjtYZKIgq7vl1sbB35Ld2QiUlE75P8ep1Pw+z7KlbSs156mD2k+O0GI5StlCDH1zLyG3XUi5ehsrESevfJ7H1/gM6XJdfOlNx+nl8L8G9+PyqbXffbVtnqgmcaugICmiEpdwS7gV7pCsAdXEMth9J//BF0Ua2iR1GAIccUnG7VEmTLnFa00R0QttGadu6mkQ7Rir2gkT6ZQF1mb8oY8ad59xNGQp5oANrjCVOIeFyImCCTDtN1JBKxmBlrElujyTRdjTB/DRWBK0OXA6ywiPztIkZ/vMbG3gKKvgIugezAjgxIeZT6/c1psd+BlEHJKKFacaS77BovtN+uzQy6mLJaPM+0taerglkr/hij7Ty49+bf3UCn196OMumpZ9tSpxp4b/a0bB/w+IZ1HI789s+ewY3RY62vrKPp0ZMXPy5YntexNuMrh8cbLn2esfZdGH/Q/aFo5ee1Q3PLy9ZW9f5VVP9nO6tW/ASBw7vJ

**Comment by lime-green** [comment]
Doesn't seem like an issue anymore, probably fixed in the recent item DB update
