### ISSUE TITLE
Missing items: [ITEMS]My bad miss clicked off crafted

### ISSUE THREAD

**Issue by urzafyffe** [wowsims/wotlk#3941]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:

**Comment by urzafyffe** [comment]
https://www.wowhead.com/wotlk/item=49890/deathfrost-boots
https://www.wowhead.com/wotlk/item=49893/sandals-of-consecration
https://www.wowhead.com/wotlk/item=49892/lightweave-leggings
https://www.wowhead.com/wotlk/item=49891/leggings-of-woven-death

**Comment by jarveson** [comment]
these are already in
