### ISSUE TITLE
Crash Report 943290196

### ISSUE THREAD

**Issue by LuisG0nzalez** [wowsims/wotlk#3945]
Link:
https://wowsims.github.io/wotlk/retribution_paladin/#eJzj0uVgEmCyYPRgDGDMYCxgamBknMDIOIOR8QHTHJYNjEw7GBkPMDJeAPIZmV4wMjoJcjBKMCowGQCVRzAWMK5gZBRikPrJ2sTIFpCTWJlaxMEpwCI1iZGLR+DgIyYltm2HmQ7vYOLiFPhxh0mJ+RqYeQQowbwHyGQR6HjKBFQ5+SNQJVAAJMYu8OorkxIjAxeXwLffTEosT3cwMQAFe5+CBVkEDj8HGXHhI9yIWXtA5K7nIPLZQxD5Zi9IyUOYEpCutV+YlHg5GIGuZolgrWDsYGRcxPSViesAE8MooAgIGZCqo4qbg1GAKYNrBSNXAaMXCxeDFEMXY4iBqYGxkYGRoQEWoItNECZnbGRqYGRsYGpoBCQNgYYYG5qCWMamho8YJTiWn2YS2PmUSWL9aSaF15eYNN5dYjJ4dQmYklk+MHLPYtTjEuBi4WjsZRLigDrPgUuKi4+jU0zhPwwwwuQ4HA4xMdxiZJjFxHATmnDUHJS6mTnBzIY0B0GIoIiD5KyZIHDS3hIicsFeMQ0Mrtkb3WZSCJZg1aJx0vvQ6EANYxpOHqGKObQAkLDd+97BEcL/YZ/AGIQ3U2vG9B/6qrHHXmSd+8MqkXv2ENEP9jD564sLbLmuv7YHS697bg+Js1/2uMwbroD0TB1Fsg4ALTGg9w==

RNG Seed: 3707002573

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:106 +0x10
panic({0x11a940, 0x1746990})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.FillTalentsProto({0x3b31d8, 0x2b83340}, {0x2840180, 0x54}, {0x1a, 0x1a, 0x1a})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:702 +0x1d
github.com/wowsims/wotlk/sim/paladin.NewPaladin(0x2bd4000, {0x2840180, 0x54})
	/home/runner/work/wotlk/wotlk/sim/paladin/paladin.go:177 +0xc
github.com/wowsims/wotlk/sim/paladin/retribution.NewRetributionPaladin(0x2bd4000, 0x2bbe000)
	/home/runner/work/wotlk/wotlk...

**Comment by jimmyt857** [comment]
The talent string is invalid (has too many talent numbers). Try restoring defaults.
