### ISSUE TITLE
Hit rating not updating in tooltip for character

### ISSUE THREAD

**Issue by DrakusKyp** [wowsims/wotlk#3946]
**Describe the bug**
The hit rating is not updating in the tooltip.

**To Reproduce**
Just move it around and it happens. Already reloaded the website and it keeps happening.

**Expected behavior**
It should updated and reflect.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome
 - Version 118.0.5993.89 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
![HIT bug](https://github.com/wowsims/wotlk/assets/148843241/b015f970-a427-49fb-a675-a74d9e74749a)

**Comment by liniim** [comment]
I've also noticed hit rating is wrong as well (also using warlock sim). Using an incognito browser seems to work.

**Comment by Tharre** [comment]
Can't reproduce, it's likely though that it was some issue that crashed the sim and thus it stopped updating the tooltip.
