### ISSUE TITLE
Windows Defender reports a Trojan

### ISSUE THREAD

**Issue by Ageous27** [wowsims/wotlk#3948]
Downloading https://github.com/wowsims/wotlk/releases/download/v0.1.53/wowsimwotlk-windows.exe.zip and Windows Defender is reporting a Trojan in the file.

Trojan:Script/Wacatac.B!ml

**Comment by jarveson** [comment]
false positive, you can put the download through virustotal if you would like to check as well

**Comment by Ageous27** [comment]
VirusTotal also reports a Trojan with the file I linked.  I still have the file I downloaded from last month of v1.48 and it reports clean.  But 1.53 reports a trojan.

Screen shot of VirusTotal output attached.
![WowSimTrojan](https://github.com/wowsims/wotlk/assets/123048923/6f0f530d-9440-487b-8289-ef2758d58525)

**Comment by jarveson** [comment]
k that ones new, but again, false positive, its 1 out of 89, they dont agree even on the 'name' of it and 'suprisingly' microsoft doesnt flag it here
