### ISSUE TITLE
Swap Button is setting the Rotation to an APL

### ISSUE THREAD

**Issue by transphenomenal** [wowsims/wotlk#3959]
**Describe the bug**
The Swap Button is changing the Hunter (not sure about other classes) rotation from Simple Default to an APL rotation. This change happens even if you have only done a single simulation and there is nothing to swap to.

**To Reproduce**
1. As a Hunter select the Simple Default rotation.
2. Simulate a gearset.
3. Save as Reference.
4. Press Swap.

**Expected behavior**
Rotation should not be changing. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox release 119.0 (64-bit)

**Comment by jimmyt857** [comment]
This is a tricky one... it's because the `Simple` rotation is actually just a UI convenience which generates an APL rotation, and the resulting config sent to the sim is what we store internally.
