### ISSUE TITLE
Crash Report -301615083

### ISSUE THREAD

**Issue by jcandresen** [wowsims/wotlk#3989]
Link:
https://wowsims.github.io/wotlk/protection_warrior/#eJztVF1IFFEYne+b3XF2WPG2SI0L2TSUiCLND0IFcqcgojdToughEFGECjYJso1gs8RVeq3QAjMNyiiCKNbCkJTSHkpcUSyCVgk3Ilgz05B+7sxaEbVmZW8dmJnz3e/nnLncGWmtiAQ1rIIAhgAuAQwAhBHiAAnAWcABxBDC5hUEFLQgAGGn6DzCczsNG5GAj/O/ddeCULyv7HBFtegmHn8bSF7SOONVhfYefBxByUXqOlHykK6bqPJjzsL4IEo+MjGFcmuG6pmLYFOnU5pOBtna1ZWqi0WcJJEzoyjX+lXgWP9sjPXbVV5y8gXKn7KSURppCfPyDZGNfdDAs3vHoC1xJ2zzu8M2f8N4GrlSx8sN2Sx8X8+rGcQlu7X0Yn4XX2O/2AWcRqkbuf/4K/i03+0ICiLIqEAHCBLnRwUbYaepGQa7NMM0zUJd03TGdcPQTcPUjUK9wNQKtRQoMDTTTJEbAyKejiJpj6JSH8XcE1GMg5gAqRm4e4gy9GEfRACeQKZnh42WLmtZ0iVaitCM3Oj8Acmx1Fbe49BQ5ZeaTCuruclGP92QXBmgqysdDFNjEgPnjgY9xWUHy6sOVVTvVUplMe8fH7jcBmspxoT6e38xp3ShvLY+L7BpKXz8DM5Oh3wxqwmSm99J57XitMT5pGPBzGtbY7N0z+1tXswXrPGLZ3uV67iQ40XhiD02OERvTX0Yqnn5jiblX9N1z9YIx049pUndBJVG2gJF0gxNNcd3vPth65b7X/MHiuwOyVpV92p7JHua5tcvH300M02ZecZc1kemlqO7/9i/Y2ekJ6WfH/xp+yfmLk+WyItW3J3iJ5Cg3z+/4TMNSdaL

RNG Seed: 2731147436

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x11ad80, 0x1749990})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Spell).Dot(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:325
github.com/wowsims/wotlk/sim/warrior.(*Warrior).applyBloodFrenzy.func4(0x2bec820, 0x3059320, 0x3054780, 0x3054940)
	/home/runner/work/wotlk/wotlk/sim/warrior/talents.go:344 +0x16
github.com/wowsims/wotlk/sim...

**Comment by jimmyt857** [comment]
Fixed now, thanks!
