### ISSUE TITLE
Crash Report -249499139

### ISSUE THREAD

**Issue by fdbva** [wowsims/wotlk#3991]
Link:
http://localhost:3333/wotlk/shadow_priest/#eJztU0FoE0EU3f93m85urRlTlE1sZF2oBqGw2RCsF3f11OIltJfSg2hRD+KhSA/VUxWRpK3owRQMHqQXBRHtSXKyrfYQSiVGENNItQmWQmsJqUWRgM7uJqVelGgLHnyH4f83778/M/yRDhKkqGEbtEM39OEgwC2AD/hWeADwBHACIA2wBHB8NwEFA6BBG5gQscTAJB7O9951FVyRC6cvnb1IRFrny4LkpsWbvLziV13TUzidREmknxZR5XMs3EHfxXg5769myRLKQ5XMTee+oPyV1Y0n7bpGml9D+a5HFRjBSZSOjfDy7Wa1Pmfvc6xiNM6rIttlzLhtkWUW9/ZtWLjpQgHl0eYNQqTzMd7pJ9LECAstVqAvC9a6XkKpnpbZEb/5WTpbslSrC87hVTexHyAidNcNQBRgDNdRmkDuP/4KHq3WistNBCjK2AcDwGY2ao9tp1dqJDwFr6PpMH2EqUCBAAxBixbWQroWCra2hvSwpoe0cFBna1BncTBsRaFwMA8yuT+D9PEMysmPqCxnMLCSQW01g0sgFKEhAT0SlQSSnAUPcfoUDZtZfMhvYmTGXLmBHvrTsc3zpuSTdpLYHuV7FZt8ppBL45k54BLIZStTdcBUh3nRDid6zV0OedT0Ju5YSBlHHCZt7D9n442h51Dpksmh7Z7LfnMrXAZTL37jc2JL+vwJnLeNPjePVQjzFHT+8sfn4ty1p/0po6ysfW6anDcctmicbHn0qpyZfFbVdTV0CK97l43D8b3tw9cLxvbd4d9E7T++p+aKH62QvaY=

RNG Seed: 1990065814

simulation failed: Active aura during reset: Reign of the Dead H
Stack Trace:
goroutine 36214 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:106 +0x98
panic({0x17b6a40?, 0xc003ba34d0?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/wotlk/sim/core.(*Aura).reset(0xc002388870?, 0x0?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:125 +0xe5
github.com/wowsims/wotlk/sim/core.(*auraTracker).reset(0xc00367c4e0, 0x59682f00?)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:477 +0x105
github.com/wowsims/wotlk/sim/core.(*Unit).reset(0xc00367c000, 0xc002590b00, ...

**Comment by jimmyt857** [comment]
Seems to be fixed now, thanks for the report!
