### ISSUE TITLE
Devouring Plague odd SpellDmg% modifier behaviour

### ISSUE THREAD

**Issue by InDebt** [wowsims/wotlk#3995]
**Describe the bug**
Devouring Plague deals significant less damage in the sim when choosing some other % damage debuff than the DK debuff.

**To Reproduce**
1. Go to Shadow Sim
2. Click on P4 Preset
3. Sim
4. Go To Settings
5. Switch from DK Spell % debuff to curse of elements or moonkin debuff
6. Sim
7. ~600 DPS less overall

**Expected behavior**
As far as I am aware all those three debuffs should behave the same in terms of % modifier.

**Sim Links and Screenshots**
[DK Debuff](https://wowsims.github.io/wotlk/shadow_priest/#eJztVV1oHFUUnnPvZHvnJGZnb5pkcpPFdWwkjt04O8u6TRVnowix+hCaPhQpQS2tjWgNXUENPsQitelGKMWqXSoVKfhSqylIjSJtt81D6Eu7glQDQSNCsFUKbW0ssXrnZ6MpIRJswQcPy+Wec757vnO+vdzBVkZ0sgq6YAv0k0GA3QDfkQvqJ0COA5yTDsA0wEO1DAywYRXkoBvWA1fEr9XbIdL93FOvbNrGNL1KTAJG9aO7qXEhbkbGSmRslKCmHxymJh2R2xp9VOam4iad8L1TBWrsCr2o/oXMzTAzIpFe4DZ9Qqb3c1OVniLdz2T+rRZTHfHcqP5pgZqaJBjxf8j1HcPUeCNuatIbC0pE9YKMvd0iewlAmj5dCHvR9MkhGlCr+qEhKtcv5VqjH5ZHrsUDkKofGKYSOlsIoGY1kwJ0q+urdgJ8QK4QPE6U/+1fGbeXemKgjoFODNIPL4O8rTv9C7uWoSJUmYBdsM7O2GnHTqfsBSy5ULCSSzsZ20nbTsqRa8pJO+lUxtulM6kpMNjoj0T/+DQxPjxNEj+VSdsvZWKfL5NpUC9CdRGUEjlbZVCMYUSoSIyYuQyrkCZTeWxAJiKosvdniInIMJK02zuyed4iBOpWLYtwskbxEEjsvI987U3CG8TySnZ1mE3lVyu8WTRhzIqGcZ/kvlQ+4OS3izjWWTGm+iU1lOlUezYTVD30G+GvigHs51uxxuvE8aK/XyXYKzbgSm5hvSXl5bIiQkawEsgdK75UoVsT0sl6c2g1QKdvQNN5aBHy8PtFB97Lk9hkNcqT7NlQFaEVSbi9UZB0viIdN0TD39qWw8wN9QgD0YlZnkFhGfJ0WO6PqySQIJuxn89jo1UvSbXPwcuNlWhAEHYnsbxNllmxWIk5ZLtYGWo1N7YIVHPqcJm3ZQfy4b++X7aeFPdgnDfPm9sbwC/t2LK0N1clzJ8UvfggfwBbrTvnyVR/hHDJ+ZdagpapEgriiaeVaEhptqA4QhoZWVBl7xJth4YAKmqtGklD94Di1+Mogs6/v0TOEPwWlCJRvgnfurty5mGq+dvBzblYEFyeayru82zc7QgiZ9w7Nvv2tetcJ/1X3iMD/PG+jVsSj/VtfSbR1rVp2wt9G+9O9BjMusWvaNtQ7maUGRw/9Q91ehbLXz73zrudN6OPhczXnE1B5z7Ys+H6w9d+PumGXDOufCPXLvqpmtirvH70xXF3NnHpct2JSTeIXnR7Wz86O1s+cayC66l+VP3q6fNudm9zV2HHD+6tGua/akv/VD2x5BN/Al8vLNE=) vs [Moonkin Debuff](https://wowsims.github.io/wotlk/shadow_priest/#eJztVV1oHFUUnnPvZHvnZO3O3jTJ5CaL29FIHLtxdpZ1myrORhHS6kNofChSglpaG9EauoIafIhFatONUIpVu1QqUvClVlOQGkVs1+Yh9KVdQaqBoBEh2CqFtjaWWL3zs9GUEAm24IOH5XLPOd893znfXu5gKyM6WQ1dsBX6ySDAHoDvyHn1IyDHAc5KB2Aa4IEoAwNWQx66YQNwRfxauwMi3c888dLm7UzTa8QkYEw/toca5xNmZKxMxkYJavqhYWrSEbmN6qMyN5Uw6YTvnSxSY3foxfTPZG6GmRGJ9AK36BMyfYCbqvQU6X4i82+0mOqI58b0j4vU1CTBiP9Dru8cpsZrCVOT3lhQIqYXZezNFtlLANL06WLYi6ZPDtGAWtUPD1G5fi7XqH5EHrmaCECqfnCYSuhsMYCatQxs6FY31OwCeI9cJnicKP/bvzJuL/XEQB0DnRikH14EeVd3+dd1PUNFqDIBu+FRO2tnHDuTthew1ELBai7jZG0nYztpR65pJ+Nk0llvl8mmp8Bgoz8S/cNTxHj/FEn+VCFtv1SIfa5CpkG9ALUlUMrkTI1BMY4RoSIx4uYyrEGaShewAZmIoMrenSEmIsNIym7vyBV4ixCoW8tZhJN1iodAYhd85CuvE94gVlSza8JsurBG4c2iCeNWLIz7JPekCwEnv1UksM6KM9UvqaFMp9tz2aDq4d8If1kMYD/fhlGvE8eL/n6FYK/YiKu4hfWWlJfLighZwcogd6z0QpVuXUgn682h1QCduQ5N56FFyMPvFR14N09hk9UoT7KnQ1WEViLh9npBMoWqdNwQDX9rWw4zN9RDDEQn5ngWhWXI02G5P66QQIJc1n62gI1WvSTVPgUvN1amAUHYncTyNlnm9sVKzCHbxapQq7mxRaCaU4fLvC07WAj/9QOy9ZS4CxO8ed7c3gB+aceWpb25qmH+uOjF+/l92GrdNk+m+qOES86/1BK0QpVQEE88rUxDSrMFxVHSyMiCKnuXaAc0BFCx3IpKGroXFL8eRxF0/v1Fcprgt6CUiPJN+NbdkTePUM3fDm7Jx4PginxTab9n425HEDntrtzi29euc430X36HDPBH+jZtTT7ct+2pZFvX5u3P9W26M9ljMOsmv6JtQ/kbUWZw/OQ/1OlZLH/p7Ftvd96IPhYyX3M2BZ37Ye/Gaw9e/flLN+SaceUbuX7RT9XEPuXVY8+Pu7PJi5fqTky6QfSC29v6wZnZyokvqrie2rXqV0+ec3P7mruKO39wb9Yw/1Vb+qfqsSWf+BNutCye)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox 
 - Version 119

**Comment by lime-green** [comment]
EP and Crypt Fever increase disease damage taken by the target by 30% 

https://www.wowhead.com/wotlk/spell=49632/crypt-fever
https://www.wowhead.com/wotlk/spell=51161/ebon-plaguebringer
