### ISSUE TITLE
crush enh apl

### ISSUE THREAD

**Issue by Volkinaz** [wowsims/wotlk#4001]
[**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
](https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVFFoHFUU3Xvf7Gb2mjWT55JOXrtxO5QStwRmdlmbCjJjvlT8WOpPrT+xVSliJSQfVhHcCGK76YeEorgKFiu1rlI1qBilZdtGy1ZiY9BgWjVpoJD+2ARajPmpd2Y2q+RHio1fXva+eee+e8677+2doY062tAN90MBe6EPiwCz+JP2MWAVYAJgHqBH6WBCGjvBgx3QB5xyGOAYwBcAErtBVeMvQazw9GPPPdGvo9GkLgG1GJVXhXklZcU+P4Mzo0hxozYkLOFPm41jvDabssTUDR/9MiTM3xlVeU0as4yWUlacUfijhPFpRZgvd1gasyMMP2D6oQ112GIUDworfrSGlRryyIH3ef0qbz0T8luM1w8K87UNVoxRWMuHfi3VYDp3oD7VjJMVweNXBwQX9QlTxlMrBf8daUa5JKyEf20FbYe2D/YDvIPXkaoY+d/+lUn7ZhnP366DgSbuIW5Jbsxh2Ek9BqpNhDqyC3ZgT7ATe5Q9xt7EHn8g1HjEK0D/bdwKx7mRxMgo7gOV1DENnZhtZnnBzQ82t34Jttv5nJ2znXzWXmVddjZv52075/ijk8txnuPknKwfcLpWp/9lc2DqX46h8e1lNM+MYXp5EjuvT6L9xyTOg7YATWUwKMZd9/Yp9J/6+LA4jSfQ1OgO0pUfKZc0q4miJLpyA9RKMaURmq31kDMgNYX3RKSl0tSWSeog46fBp42+KxRnEOQDlamikKRCxR9egUa+JvWn/Nj3ReGvEdoDqo5lSq2nVquFEiNAEo1oSG1IrMid59S06qBkRupCRksCdU0F5WXrYnwEuVXlaYu8i9oz6xqb/nZOqDhxqmPbeweo2SLSR4CJ+ndtqp7Q2Gb6kpDtah0lLP43R4IzDg4GRfvPRtrZH8UFiJQxMl1/YTd71pCIB9Nqv9caBpNee/kN32rutjAy4W58MrApN3sR0w+bemaNX/mFQe9WyBRrY7dEZy0svNsTV737Qrzk9sL24GP6c3D7i+6bh6OH7uxbclcYtUc3TfQ8tNzA8u7M5hfmrrmrhCOV4V8Xtr236Hbvz5T23vhm1fqC+/j0PB15ZtnNT2u9HXsuuzNQ/ejc2Wvui+OfbU22LbpfHz+6a2J91FuLU/8XJu0HC+en1FvSu/dI97O7CxHvnxg7b/rz+yfQngYw)

**Comment by jarveson** [comment]
link doesnt crash
