### ISSUE TITLE
Hit rating miscalculation

### ISSUE THREAD

**Issue by rehaynes62** [wowsims/wotlk#4002]
**Warlock - Hit rating miscalculation**
On an affliction warlock: 
1. Added the helm for Gaze of the Unknown
2. Socket a scarlet ruby in the red socket
3. Left the meta socket empty
4. ISSUE#1 - The hit rating increased by 65 (equip 57 + (socket bonus) 8) even though no meta gem had yet been socketed.
5. ISSUE#2 - per the image, the red gem displays in the meta slot and the red slot empty

The +hit increase should be 57 only.

![image](https://github.com/wowsims/wotlk/assets/23059755/d7af5e49-c18f-4914-a2f2-f6dca88f43c3)

**Comment by Tharre** [comment]
This is neither specific to affliction warlocks nor to the item, seems to happen with every item with a meta socket.

**Comment by omccabe** [comment]
@rehaynes62 Fixed as of https://github.com/wowsims/wotlk/releases/tag/v0.1.63
