### ISSUE TITLE
Crash Report 1095123673

### ISSUE THREAD

**Issue by kjaerthree** [wowsims/wotlk#4005]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztVE1oE1EQ3pmN+Vla8gyCa5qUuIhIofCSpVBPu/WieArGQ6kiilgEf5Be/AEhVgvVClaRkkYUrSAREQVFW60l2AoNQhtK2qKVUs0lldbE1GIQRGez6UVBCVbw4LAs88038723b79dSbEjQ4774QiEAWIA9wHiAEmADEABMIm4ifmQgw6N1NNe7HEJ7jlrK1iDB/cc39ditzHJPQWSk+U6RXnWq1gfDeK9PpQcbLJDVEQjrWB54ma8S2ixQ5Q/Exoj5GQfiCvQHHEGXcnSRLdVKxaiBYJZ4i97StDJ+knVMVbsNdpdLE7tWe9SbeKboTlKtS6PYjVrtJe286K5noO9iZZSC8vkjfvTsyLJTJ4W5ZhbcVxLoHlJAnF9n1Bx2pFX1kPQ0mg5ZpxBDy6iFEfhf/xRuHi5EydsdpDxOsAXCEk6eRdkcuYWCEJn0bq9AMOGe3EG4D14yGmxBTRequE7VwVbyKM8YrowB+B2rjRlc5oPagQO56CJ/yJq1QDnqlpn5IGf2YDK/SpXOfFqwF/np5qfcr/qV1WC70C2d6WQRVMoX02hL5LCDZFx5N3jmAFLDmxRsEjkuecovAYhisKrksHW60oaHcU03KyXtrxKXxPtNiKhbTQrSW1tczEmtMAD9IXkFTWRv2vR3Cl9OWTCiaFl0SknzDN7ltUbTFzQdsO24kedVm/uWH3boe9M3T1TdWtWK1fZru3KPHRNaXcuncwmXg78MJ/TLlb1rKvHj5pv+sL2xKF5rWXvi+qBfkEffHxj89jIvNYqDE0ffpsve91/JVz8wJPauVCvpG9tODp8pf3rb5+kqezfwHfCdde/

RNG Seed: 2113915618

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x11b440, 0x174fb10})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*WeaponAttack).setWeapon(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:250
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).SetOH(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:180
github.com/wowsims/wotlk/sim/core.(*ItemSwap).swapWeapon(0x315f0e8, 0xf)
	/home/runner/work/wotlk...

**Comment by jimmyt857** [comment]
This is related to the item swap settings

**Comment by jimmyt857** [comment]
Reorganizing into #4082
