### ISSUE TITLE
Crash Report 821201632

### ISSUE THREAD

**Issue by Maansson1** [wowsims/wotlk#4006]
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x11b480, 0x174fb10})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Spell).PhysicalHitChance(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell_result.go:94
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).setup.func1()
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:49 +0x11
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).setup.func6(0x28b37a0, 0x31a2000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:115 +0x1f
github.com/wowsims/wotlk/sim/rogue.(*rotation_combat).run(0x402cc80, 0x28b37a0, 0x31a2000)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation_combat.go:398 +0xa
github.com/wowsims/wotlk/sim/rogue.(*Rogue).OnGCDReady(0x31a2000, 0x28b37a0)
	/home/runner/work/wotlk/wotlk/sim/rogue/rotation.go:57 +0xf
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x28b37a0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:449 +0x21
github.com/wowsims/wotlk/sim/core.(*Simulation).Step(0x28b37a0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:508 +0x25
github.com/wowsims/wotlk/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:465
github.com...

**Comment by Maansson1** [comment]
https://wowsims.github.io/wotlk/raid/#eJztmWtsFFUUx+femV2mw8OBIAxr0WWMusGumdnpKG1Cuq1A+EKsbJOCxoShTNuR6c46O9vySBMkIcrjAyZqsMagPIKQEDAxIojhGXlJIC1UwIiEUAQlQkJM0A/iObNdWCpKWddve9rMnnvv3Nub9nf+95xbYWulcP4xoZtbSrg603D5oEhCssA86EseKfLSEIWtZ2excwILyNuErKO/UWEvZUr2n2yU8rAzFjHdpFwYzo8TybhsTzgeGiowI7ONyvgKEonqihbTYio+YoqqaLqmxhRNUTRV01U1Cr6uKIp6kUj8vj1U3PAzlfbuoeFvumnkYDdVDnTTK4S7QYZ0kbKRzb711uynVCKH6WHyJSHnCA0Huyhzth+Ap+PCFoBq6Ewz7Tmu4VlOctBsBXmikHpaAqooVghQW2hQYEJUYAAdRddiyAlAE43GAJmYBuyomqr7nqIjQ4ruo7PuEhWP7qHS+ks03HWaRgAb5dBddJg7xJwjzL2wnAwMgIWKQx4ClhElWIpihcCyi/IAC8cTkawgT0Y1JYZMRFFPdABEQ62BHlWN+eRkSdl6kIon+qi04yAN/w4i8weQcvx0PilbiETkjURYRxbLnuOZbWm5erEMZ5TXKlfLCc81ky1e60vNU7GnAV+QK2TDcmGwERiCkVrLzfU3W64JA9Nso830nGRLxsyNdBieiXOmm4ZtJVtwXaMtO9hZIWfSpr9+otUy7XlytedmTL93ppXyrHlmtqfzvkifH7KU8ImM2261GzaIHw1dJsIjYu9qVro6Xg5+cYBu30mFMvHISlZm0R0mnoGxC+NzrV03qfReucyuPUJh3lkYuwXzYAyHh4s/rmSlZY/LHLQYaJ6G8XfL+5ujxCWrWOmdcrns1E4K83GJUeJpmHF9vFzWexuX6N2Jy26DvvfL5SC8d8rfzi7czo7L6F5cDi72cuJXy1l4fngDl9kGS9+EZbI7wc0wsNut0Lum3N+7zPNUIZNIPVcKy6JYIWFZPRmisgp09InQGHiSCImz09k1hOwl7GFCzhAyIfvqjZqq49+iXaup9Tvia+MRCOVnohjAoOyK6gczZBD4oYFBvwqJg6ZAdPvh/PEJKm6EcN7QR8PfQTgfhXDuvUf4d2M47yDC5xjOC1MYjQmIN9tsMNwW04NITHvQxm7TTZlJL+E3K2TPNVKNptFu5qKv3UqZbsKDsJxhJI16022Ct+Vq5Tn1zpiTGjCkgTTYttMxdUHKdtJWu5lodbwpTkfSNZLzcwu3ZWzPmuJ492zgXwJ8PZxZfENDY3gaqAvPieygDiwBDqyh9dwsbk4pwymOFRIddSMgOgSeSk0yJxKJW0GexdzGz2ZUpBzh1zFDVqFf8xOdbMqMCTMif/M4FW8fp9JmQP4SIH8BkL91Pov8UB/5ZiB+rjBnsTzXNtJeo+W1OhlvhpVOW7ZZZ7iu0WLWznXazQGsxipkJ2kv1GrdJiNp1uFcoL1pfrrOBIIHMq/7bC7vh6gyPpDSUYzQN1Y4D6gK9S4ca01+dhUQuUHByvOcMhyLvBKqRbFCUD1K/GRcYrGOA0BBkTUdUnIs5kCFkU0s7aJQx2HupWK2joD+0EvFVfuo9BkAegUA/QkA7btHk7ehJm8hwibQ5PQbGdNcZE537IV++pQTxQ7D8hI24CdXQzBUyE0ZyNHbZjqen6ZjSpZOmbYNydmr/a5c/XxnxR1/Up5flefH8nwtz38hz1fzfL3ztc7Ofy42t0OxGXzRaZtreAB3cJBKTJWAr8SlPKU4Vgjer4AMi1Sik7g4FxoBHgmPVlazUyEnmYzlp19/qkqlWhlVYsC9jsUEXleoChQUKkp2tqgYxu/vo+IhyELOnhhMyXkAkBFqm5ttK6eJ/KAPcExuA7MCJWyKYoVg8/oYqDk4gIVG8M9BQ0EoQKENeWvMv8vyr7fABUx07ACZVHU1GtX9XLb/wuKjt1jxLBDTAxq5tIdG/gSNfLMn/xBn8o/Xqr8dr8I5vDqdlnEXAj9lgzxTqRKEM7UkOsWxQuhxawRdRHZotuRhIvGXs87s+OysUxVvJSmyhODd9ick21cZDwVhGpEoYIbXYpAbwuGrRaEiwloJsALsUJMwV/Rlysfs0x4qdvVQaU0PDe++TSNXTw5TlvXkixRzX4najKdaotWY53TwrBgYJF54IcaVxKlIVgheM0cIlGdDPN6JhQkW009hZYFsRKNYRsewro4hPXgvD7p0t67YdIyK245RaSdI0i+Qtl0DSfq1+4GsQJ4/7C4FxWqJtJqZyMhUJH6ZFAjNE8YKj5L7GQ5wHEfhGwweAfwAwwHYIof75DgmwHEB1t90/8Bdy7Eqr2TLfGdJc7z/vxij4+O6PkA7UlOV7TlZMyH3j4jY9zSckAIT/2fYI8vjxVhmyZGDD1gnUZSfU4hlf7dfX4/3y+KtmjnkL06r3jY=

**Comment by jimmyt857** [comment]
Seems to be fixed now. Thanks for the report!
