### ISSUE TITLE
Missing items: [ITEMS] T10 4 set bonus to blood rage

### ISSUE THREAD

**Issue by Anvarynn** [wowsims/wotlk#4010]
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
https://www.wowhead.com/wotlk/item-set=-240/sanctified-ymirjar-lords-battlegear

It doesn't appear that the bonus absorb from T10 4 set for warriors is applied in the simulator, so I figured I would send a request just in case.

**Comment by jimmyt857** [comment]
Looks like this is implemented: https://github.com/wowsims/wotlk/blob/master/sim/warrior/talents.go#L604
