### ISSUE TITLE
[Rogue] Hemorrhage Debuff doesn't seem to get applied at all.

### ISSUE THREAD

**Issue by Skurrio** [wowsims/wotlk#4015]
**Describe the bug**
Hemorrhage should increase the Damage of the next 10 physical Attacks by 75. Currently this Debuff is neither visible, trackable nor does it seem to increase the Damage of physical Attacks at all.

**To Reproduce**
1.  Run Sim with only Autos
2.  Run Sim with only Autos and Hemorrhage
3.  Compare DPS from Autos
4.  See that Hermorrhage didn't increased DPS from Autos

**Expected behavior**
Hemorrhage should apply 10 Stacks of the Hemorrhage Debuff which are used by every physical Attack hitting the Target and increasing the Damage of said Attack by 75 (105 with Glyph).

**Sim Links and Screenshots**
Sim with only Autos: https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRidJBSYLRgfGCMYKRqBUByPjArCCDUyMQgxSb1mbGNkCchIrU4s4OAXYpM4zcvELbJnALPFSVolt22GmrTuZuDgFTnYzKzGDmDwC24ByD2RhvLtTmSWmykB4/AKbgHI/gPpWnmR6BBTgFdiyilmiVU6JBSjNwCUg8LmbWWKKjBL73p1MYBF+gck9zEqc1/4zAXUAEVBgK9CI90AjgPJ7wWauB+r5BBQAGvgI7JYNq4BuATEZwBAo0AN1HKfA3m6oHKfAWqioEj8wXFgCWCJYElgqQL5fxPSViesAE8MooAgIGZCqo4qdg1GCCZj4osS42BSYNJg8WKV4BIBCBhOYXc+eOWPbxahtqGtgYGpkYGpgYAxEuqYGRkaGBkZAjjGQYWRobGpgCJQ0NjQyNXzEyMNx8zyTwMXzTBLHnzK9YGT5wMg+i5HhEBOTBPMJphOMF4D4FiPDLCaGm9DYVnNQmsfMCWY2pDkIQgRFHCQhjAv2ljCGomZM/6GvGk/sjd4xVXEGJJYkZ5SnFmUrBEtwaNE46Wh0OlDDmIaTRwiYE0wVe8gB4GBuEHroMJNx1kwQ2GnvCJF5YR8Ezpy2XNcXF9h+sj/8VQMYEX/tiTW5WmSd+8OqLfZvAnfItb6+iEPfB3uI+d/s5VtfA1V+tQfpEln33R5Euj98ZQ+O/Zj3RNs72ICQAdhjrewOkABmdiCkIwqanT8Q7WcAS3W+9A==

Sim with Autos and Hemorrhage:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRidJBSYLRgfGCMYKRqBUByPjArCCDUyMQgxSP1mbGNkCchIrU4s4OAXYpM4zcvELbJnALPFSVolt22GmrTuZuDgFTnYzKzGDmDwC24ByD2RhvLtTmSWmykB4/AKbgHI/gPpWnmR6BBTgFdiyilmiVU6JBSjNwCUg8LmbWWKKjBL73p1MYBF+gck9zEqc1/4zAXUAEVBgK9CI90AjgPJ7wWauB+r5BBQAGggykwHomg2rgK6BcMDcHqjjOAX2dkNlOAXWQkWV+IHhwhLAEsGSwFIB8v0ipq9MXAeYGEYBRUDIgFQdVewcjBJMwMQXJcbFpsCkweTBKsUjABQymMDsevbMGdsuRm1DXQMDUyMDUwMDYyDSNTUwMjI0MAJyjIEMI0NjUwNDoKSxoZGp4SNGHo6b55kELp5nkjj+lOkFI8sHRvZZjAyHmPgkmIW4pDik2LhYOKb8YTrBdILxAhDfYmSYxcRwExrzag5K85g5wcyGNAdBiKCIgySEccHeEsZQ1IzpP/RV44m90TumKs6AxJLkjPLUomyFYAkOLRonI41OB2oY03DyCAFzgqliDzkAHMwNQg8dZjLOmgkCO+0dITIv7IPAGdWW6/riAttP9oe/agAj4q89sSZXi6xzf1i1xf5N4A651tcXcej7YA8x/5u9fOtroMqv9iBdIuu+24NI94ev7MGxH/OeaHsHGxAyAHusld0BEsDMDoR0REGz9gei/QwAobPBEg==

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.59.124

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vigo2** [comment]
The hemorrhage debuff was explicitly disabled for non-raid sims, since its contribution to personal DPS can't be modelled sensibly. See the discussion around https://discord.com/channels/891730968493305867/944495169657524255/1079892138243915847.

**Comment by jarveson** [comment]
ill revert it then as its intended

**Comment by Skurrio** [comment]
Could you implement the Option to turn it on and off and have it deactivated by default?

**Comment by vigo2** [comment]
Thank you @jarveson. There's a new issue to implement that feature, Skurrio (https://github.com/wowsims/wotlk/issues/4060), maybe I'll get around doing this over the weekend.
