### ISSUE TITLE
Improve how Demonic Pact is applied during simulation

### ISSUE THREAD

**Issue by RaverJay** [wowsims/wotlk#4019]
**Is your feature request related to a problem? Please describe.**

Currently Demonic Pact spellpower is applied as a static average for the whole encounter, but this is not how Demonic Pact behaves, especially as Demonology Warlocks utilize spellpower proc trinkets to maximize Pacts.
E.g. usually the very first pact is big due to procs+pot aligning, and it's active for the full lust on pull, benefiting DPS more than a static DP does.

**Describe the solution you'd like**

Add an option to simulate a more realistic Demonic Pact behavior with each iteration.
Could make it a function that takes the DPASP value as input and then approximates how DP usually behaves if you have a Demo with proc trinkets. Should take into account that a large pact will be up for at least 35 sec before it can be overwritten, etc

**Describe alternatives you've considered**

Options range from a very simple step function up to a very intricate randomized simulation of how pacts look over time, which could be informed with log data. At some point it will obviously be overkill.

**Additional context**

The difference might not be that large, but it would be interesting to see for sure. Will be valuable for RaidSim down the line.

Cheers

**Comment by jimmyt857** [comment]
Thanks for the suggestion; Demonic Pact has realistic behavior in the Raid Sim, which is our typical solution for extremely fine-grained questions. So I'm closing this as we do support it in some way, and we wouldn't want to add extra UI options to support it in the individual sim.
