### ISSUE TITLE
wowsims/wotlk | mage 

### ISSUE THREAD

**Issue by VitaliiShyliuk** [wowsims/wotlk#4024]
on a mage in crit in buffs it shows +0.36 crit even if you take off clothes, cancel all raid buffs and talents

in crit in buffs it shows +0.36 crit even if you remove clothes, cancel all raid buffs and talents
and accordingly, in the end it shows 0.36% more crit than I actually have if I put on clothes, add raid buffs and talents

troll mage without any clothes, buffs, talents:
![image](https://github.com/wowsims/wotlk/assets/71257918/b14f166b-4f73-4b00-8fb7-8eeb7ef95202)

____________________________
* It's probably [Arcane Intellect](https://www.wowhead.com/wotlk/spell=42995/arcane-intellect)
But I switch of it in buffs

**Comment by CyberQuackGames** [comment]
Classes receive their own buffs be default as it's assumed you'd have them. This logic is from the raid sim, but I get why it's confusing from a UI aspect.

**Comment by jimmyt857** [comment]
Yep, working as intended. Sorry for the confusion!
