### ISSUE TITLE
Crash Report -834776274

### ISSUE THREAD

**Issue by TheMEFFER** [wowsims/wotlk#4037]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztVF1IFFEU3nNm2XaHwmkzGM222z7IKhqzDj4UxN0kqB4Cf14iemjamdWhdXZbV0gfYguktECQijRKqIh6kaBCjYqwHjIKLNasHsKfDKMfjRJ87M7MrhT0J9pb3zB3zjnfd849czlcfp0bBZSwDuKQArgCMAQwBTAHOISYQqhYI4AIBCQIMcmxjARHAecANqEAXkf+adcRcFVGlSYt4eYEPv8F8DnCnXZOvOzzuy7dx4F+5D3C61Ocn+tl5nLhFuNO+LLeyDSKpwpsL0e4y7ixPL+Led3dyK8Qrh/nxDaf38kCDubeZvzJrJsjvJlGv4fZGblXuMHkn9Z+H8sRzrIdThdYNXutXron0N7PI9ycyZhOYWraXPtbOTPlC4pHffMpDkb0fUX/CrdT4iq5XdxB8ywu4Czy99DxH4uCV1poRrPLDSISOII8z0yBDWi+ow1KJKm8PCgFy2VZlmQ5GCyTghJ75VJZKrcehjKZRUqlsnEQ3R8nUTifRrEjjeRMGgPtaZQ6h3EKnDOwrAscA4iisw/gFRR6tjKkrw2FVtotTNEi25ihedkIcXWh42VmHgpD/mdOj2WmItms3FBeV6eJQbrRjgzR9RELz2nZBWd8thubV9XohppQamMNCgls1xIxPVxEakR38T8etUBraCnKpAYf/KFOze94cuhzy5al6ONnsA49lZoNdYIdGKWZveboXvMG7IBz4F29wwhHG1WN7GxqSOphUtEYiWjJ4sOwM6ZqUZKs00hCqY/rRi2pV2qZQFXYVyNJZb9mEFXbx/REicejuqYStTFhCivrlAaNyCQWsfI1IxxrNJJaooToBlFUVU/qMYMkYxZrxBL1SjSTEyT1WrhOMfRwwwYRqq0rZ13L+6o+3zCVLUxQ+x9m6GLPp89nFu6hBzbzIxfjk/RDlRl5Sseac3u2jT2i1Zbg4Tz/qzr2kF+lP/rvaHbU7XrjGf8tbR+YDexpH190/38Lr/TksQl36G8zdi/4kvoGaOYZTg==

RNG Seed: 1734277595

{SpellID: 45529} failed to cast: still on cooldown for 56.639283048s, curTime = 3.360716952s
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0xe1760, 0x2ae2490})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Spell).castFailureHelper(0x338d180, 0x338a360, 0x0, {0x27a32d, 0x26}, {0x387fbc8, 0x2, 0x2})
	...

**Comment by TheMEFFER** [comment]
The error is occuring when I run the sim with DK tanking 4-set. 3 set-pieces or less generate no issues.

**Comment by jimmyt857** [comment]
This seems to have been fixed.
