### ISSUE TITLE
cant select mage offhand

### ISSUE THREAD

**Issue by SpreadYourButter** [wowsims/wotlk#4063]
**Describe the bug**
cant select a new or change mage offhand gear piece

**To Reproduce**
try to change mage offhand, no options show up under "items".
the list of enchants still pops up though

**Expected behavior**
items should show up.

**Sim Links and Screenshots**
no item: https://i.imgur.com/uYCG4KU.png
trying to add offhand: https://i.imgur.com/co6iy1m.png
switching between the phases and ticking the ep value box didn't change anything.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Brave
 - 22H2

**Additional context**
im using version v0.1.57 of wowsims

**Comment by jimmyt857** [comment]
Check your filters, you're probably restricting the item types.

**Comment by SpreadYourButter** [comment]
i wasnt. and now theres more people saying the same thing is broke. so lets not mark this as "solved" when it isnt.
