### ISSUE TITLE
import broken

### ISSUE THREAD

**Issue by greppy** [wowsims/wotlk#4066]
**Describe the bug**
Clicking on import does nothing.

**To Reproduce**
Open website, click on import.

**Expected behavior**
A drop down with options to import.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : firefox and brave

**Comment by Thraxs** [comment]
Not sure if it's the same issue, but in my case the import feature also stopped working recently.

Turns out my pi-hole adlist was blocking the domains "cdn.jsdelivr.net" and "ajax.googleapis.com".
After whitelisting those domains, import started working again.

**Comment by greppy** [comment]
> Not sure if it's the same issue, but in my case the import feature also stopped working recently.
> 
> Turns out my pi-hole adlist was blocking the domains "cdn.jsdelivr.net" and "ajax.googleapis.com". After whitelisting those domains, import started working again.

Same issue for me.
