### ISSUE TITLE
Base stats calculated different from game

### ISSUE THREAD

**Issue by baelrayneVessdren** [wowsims/wotlk#4097]
**Describe the bug**
Feral Druid (Cat): According to the simulator I should have 1875 Agility. In-game I only have 1839. When I reduce the amount in the simulator manually by 36 points, it reduces the Agility to 1836 instead.
Also: I have disabled every visible buff to see the absolute base stats of my character and for some reason the Agility tool tip adds some 55 Agility to the whole and I am using the recommended gems from the simulation. 

**To Reproduce**
Import my character (in-game screenshots and sim screenshots added additionally)

**Expected behavior**
In-game major stats with a maybe +/- 1 point difference

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/feral_druid/#eJztVE9IFFEYf+/NuuggOG0Go6i95hCrpMzO4KGDzOhFOwiWtyBo2pnVod2ZZXY20ENMwQoq/SEqdCOKtKtBkeipSCUFJVlIMYhMKhIPbtDCXqLezG63MCvr1I+Z977v932/73s8Hh8N2kAAVF/0X4T+rqjSp1mlfgZWr0G6ghm6RLGbtZx/cgY9nkZ0GZMbpDjKNcuZ2SsUu1773Xs9TLE3ajjqBfEqmDkSy7u6aVQgbg9SbKqO8xOPcHSAeT9AsddruLKMR0x6SY8uUx7xwPsIkckjdpuUId7KV7fLm23E3iRdMt5hNtzDFMzNgaLpY7Y+uOtw1i2QJ12WCgXcioAERoYoDtxDOUQ/ReA//ggB/lcV/eAhbKKDDGRLMAzCFgAcWS7pqLoKK0YgdQoAudWBdffh0uJiyxSE1YgJDsH6xmZeFHghJAqiIPAhgW8WycKLvBjim0OhRkKQDBLYgGzp56VyZvwdYueeIJx+iYLPM4ifyaCP0JeFKA3BMwTm0TxcJv8rCNIIrBXfwWGZW/aVeaZzTt5XICvlqvSoiwXpaIFZlg5FPKxIwl1fPHcH9e/v1g3VUnrMhIKDHZpl6uF63M2WNvzlJxYclPeijLMw+5M63TvF8flPqda9OMeP4F264+TkUVgg1qVir7x0GjoQXoO3YODAMSMcTaoa7uxL2HoYtyUjEc1uuAA7TVWLYrtXw5YSi+tGD44pPSRBVciuYVs5qxlY1c6QfKzE41FdU7GatNzErl4loWERmxFPrxlhM2nYmnUE6wZWVFW3ddPAtulFDdOKKdGiJoRjWrhXMfRwoumEN2hED5R8MLV1fKqO2uk2fwNZqXKi/W1/pU9eHYu30KtQ7iDeRPsXadx1x4DstU3tdd9/h+KgcXh5t4qTxdGUlXar+AbYEuvH

![ingameCat](https://github.com/wowsims/wotlk/assets/131447339/e79bcfb4-8912-4ff6-83f5-810557053ae2)
![simAgiNegative](https://github.com/wowsims/wotlk/assets/131447339/42e00757-fb74-441c-8dab-ae845bfa8005)
![simAgiNeutral](https://github.com/wowsims/wotlk/assets/131447339/916e376e-55f1-4a54-bb7f-4fd6add977fb)
![agiBuffAdded](https://github.com/wowsims/wotlk/assets/131447339/73d13b73-82fe-4f84-8ebd-d7393c129ede)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - Browser: Firefox
 - Version: 120.0.1 (64-bit)

**Comment by Tharre** [comment]
> In-game I only have 1839. When I reduce the amount in the simulator manually by 36 points, it reduces the Agility to 1836 instead.

That's expected, the reduction is before % modifiers from buffs and talents, in your case improved mark of the wild and survival of the fittest: `36 * 1.06 * 1.02 ~= 39`.

> Also: I have disabled every visible buff to see the absolute base stats of my character and for some reason the Agility tool tip adds some 55 Agility to the whole and I am using the recommended gems from the simulation.

That's MotW, you can't disable it since it's not a raid buff but a self buff.

**Comment by jarveson** [comment]
as said, compare with motw on, is its always 'enabled'
