### ISSUE TITLE
Crash Report -900956924

### ISSUE THREAD

**Issue by M4a1verick** [wowsims/wotlk#4102]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjUuRgMmC0YPRgDGBKYCxgamBkfMB0g2UDI9MBRsYLjIwvGBmdpDgYJRgVmDQYHRgjGAsYgUoWMDKuYGTcwcgoxCDVwdbEyBaQk1iZWsTBLsAuZcHFL/D6J5PEZVkltqOHmC7uYOJiF1jSw6zEyMCFFyrxgpwSwBLBUsHYwci4iOkrE9cBJoZRQBEQMiBVRxUPB6MAkwQTMJKBUT2JcQojV40Ao5QeFxMHMxAzATELEDMCMSsQswExLxBzAjEXEPMBMTsXgwGTJdg0h3oHRzCjYLmDJ8SCSIcAYELKhIi2OxTJcPEIrOthljgrq8R8fyeTEI/AnKnMEueAvI07mSoYpUQ4mIDpj1GDyYgL6DJmENuAsYtR3cDU2MDYwMDUSNfYwBQIjUEcAwNDYyDD2NDQ2BBIGpgaPmLk4Th8hElg1xEmidNPmV4wsnxgZJ/FaMclwMXC8fwDoxAHxFkiDmgiDgEYIvEOXGwQkUNMDLcYGWYxMdyEJlE1B6VuZk4wsyHNQRBmpuSsmSBw0h4SHAwX7BXTwOCavdFtJoVgCQ4tGifyD40O1DCm4eQRqphDCwAJ273voUmN4Yd9AmMQuPi4Aw79j/azF7BOkS/4YQ/TcTJa5YKTzy84X8hMS63m0Rd7NIMZVk2698Fy+Ud7iw6trtz/x9DkP9in3HzBtTjvl73pTZYEuYyn9vcZD6w/dfyLff3ZreYiYh/tj65blnRBmtWBFr6mBxAy8Ao4f01qjpCD7WKL8uQABgdCOqJILnAAHJiefg==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x116a80, 0x173dd70})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*WeaponAttack).setWeapon(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:250
github.com/wowsims/wotlk/sim/core.(*AutoAttacks).SetOH(...)
	/home/runner/work/wotlk/wotlk/sim/core/attack.go:180
github.com/wowsims/wotlk/sim/core.(*ItemSwap).swapWeapon(0x30990e8, 0xf)
	/home/runner/work/wotlk/wotlk/sim/core/item_swaps.go:215 +0x21
github.com/wowsims/wotlk/sim...

**Comment by jimmyt857** [comment]
I think this should be fixed now, thanks!
