### ISSUE TITLE
Crash Report 1392606670

### ISSUE THREAD

**Issue by Tkashi1-1** [wowsims/wotlk#4105]
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVF1IFFEUnnNmdnf2suptsZg2LR3CRChmXbb0oWbyqaKHpV6sHrQ/KahYeski0CLIn6AQs9qkJCHNh4okyaJa0n4spH0SjFAzROvFtYzEoO3M7K4P9hCS9tSZ+13O+e4959yfM5dly6hBAWyCAJZCECsBhrDJfhcwDBABGAMoSpdBgSzMBQOKIQitAA8A3ILnluM02AOHdh/ff1R2cIfnA7A03nZBVD5lqvaOLhzsRObkw7WiKoZJdfHYeVEZykxaT7+i8p0sc1oa/0FjU6ZfJ/bFkKXwWK2oNLpViSYLjPNHZNZnqA4yO0wmjQ9eFFUnmdeum42InxRinELc68SwFfPSOVFpyFDt4Tjh5B3JtTj5QHVClXh7tUh9C/UufoZcemeW2JCwzPgSD9WIaop5XAGp2FYOVQA38BuyMAr/5a/Erc3VI4rwGVPphp58QeuGmkfxhEsGjgq2AqMqroNyVsLBs4ahLBKQIBGAYCPYCSkEJ4ERUgkOJmhYaCUwKoyNlhJsMTbHc+4wAlT/B+PsWYNyeBbLmAW5mJ9CmUX6R4Bq4xXUwCrN79N8mtefv9qn+enTfF6z9/p8xHu9VtP83mFwyQ+7kb8ZQaWrG8dAioIjBBsYZ5I8GgW3HE+dbsxijMBvTInB7HHmGQrvQAih0J+ozBxD/YhOS60sMxYlYy4NXTGlR49vWYjo2WWW9On57Zi1XbHlXV7Y2o6eMuYjTGVP97zEmYvEz+zxeKJMhCm9FLZZr8F761Qn9KtNtvoVwSk96dGza2WkaOv0jO1em5dzcnhSnxVYaKsbiBa2TOgFVXk1h2MvZo1H9X39Y6z5yLTu75dKlx8Y0QchfOf1y0m9ovf+uvQlE/rz2zf3RJbZjIXY9b8Qt7Yl8LbP0+g21jcXHNsbEIw/eeyc8/vxCwGm2ME=

RNG Seed: 1433339710

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x116b40, 0x1738ed0})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/core.(*Unit).AddStatsDynamic(0x310e000, 0x3192360, {0x0, 0x0, 0xc03e000000000000, 0x4050400000000000, 0x0, 0x408d2e6666666666, 0x0, 0x4051c00000000000, ...})
	/home/runner/work/wotlk/wotlk/sim/core/unit.go...

**Comment by jimmyt857** [comment]
I think this should be fixed now, thanks!
