### ISSUE TITLE
Crash Report -428312336

### ISSUE THREAD

**Issue by Philiphogfeldt** [wowsims/wotlk#4131]
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjEudgMmDKYCxgamBkXMHIuIOR8QIj4wtGRicBBSYLRgfGCMYCxg6wlBCD1Ay2Jka2gJzEytQiDi4BNqn3jFz8Ap/7mSVeyiqxbTvMdO0/ExenwKapzErMm3YycfEIfATKPZCF8eb8YZKYKgPhCQk86GaW+CGrxAnkQRAXr8DcTmaJVjkllvs7mRi4BAQ+A5VMkVFivw+WZwBq2tzHLNEvo8S55iTTvPlMQBIo1tnDLPEexSB+gfVAndNklNiAOoEI6KhmmKM4BR51ApkgURaB5Z3MQHLlE5DrPgC1nIW79R6UB9F9rhuiRYkfGFyMASwRLAksFaBwWcT0lYnrABPDKKAICBmQquMVE0MVCwejBFOUMhefAJMEkwYwHVuwOLB4sEoJCgDFFUQM/sMAYxejhoGBqbGRAZA0NNE1MDI1AjKAPANjUwNDUyMjYyAHyDIyNXzEKMFx6jyTwPGnTBKHnjIpfLjEpPHlEpPBp0tMLxhZPjCyz2JkOMTEJMFyi5HhJjTi1RyUupk5wcyGNAdBiKCIg+SsmSBw0t4SInLBXjENDK7ZG91mUgiWYNWicdL50OhADWMaTh6hijm0AJCw3fvewRHC/2GfwAgAYRmZfg==

RNG Seed: 2904984457

interface conversion: *rogue.Rogue is not hunter.HunterAgent: missing method GetHunter
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x11d8c0, 0x29ed2f0})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/hunter.init.1.func1.1({0x39b680, 0x2994000})
	/home/runner/work/wotlk/wotlk/sim/hunter/wotlk_items.go:219 +0x2
github.com/wowsims/wotlk/sim/core.(*Character).applyItemEffects(0x2994000, {0x39b680, 0x2994000})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:314 +0xb
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x2994000, {0x39b680, 0x2994000}, 0x30d5ad0, 0x3094900, 0x2bba400)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:265...

**Comment by jimmyt857** [comment]
Looks like you somehow loaded a hunter-sim config into the rogue sim :)

Try restoring defaults (top-right --> Show Sim Options --> Restore Defaults).
