### ISSUE TITLE
Missing items: [Ruby Sanctum Backs - Cloak of Burning Dusk norm/heroic]

### ISSUE THREAD

**Issue by RisaAudr** [wowsims/wotlk#4158]
Link to [Cloak of Burning Dusk (heroic)](https://www.wowhead.com/wotlk/item=54583/cloak-of-burning-dusk) for each item:
- [Cloak of Burning Dusk (heroic)](https://www.wowhead.com/wotlk/item=54583/cloak-of-burning-dusk)
- [Cloak of Burning Dusk (normal)](https://www.wowhead.com/wotlk/item=53489/cloak-of-burning-dusk)

Back pieces, noticed they're missing from mage sim, WotLK Ruby Sanctum. From poking around, it seems like more backs might be missing from RS, i'm not sure if they're just filtered away or something i missed. But I know these two are not showing.

**Comment by jimmyt857** [comment]
They're both in the sim, but they're marked as Phase 5. Make sure you change the Phase filter to see them!

**Comment by RisaAudr** [comment]
OMG I feel stupid haha, thought I checked all the filters, that totally makes sense, and yep I see them now. Thanks @jimmyt857 !
