### ISSUE TITLE
Feral Druid Sim Crashes with Runtime Error (Online version)

### ISSUE THREAD

**Issue by gilp456** [wowsims/wotlk#4172]
**Describe the bug**

Runtime error when attempting to use online version of druid feral sim

https://wowsims.github.io/wotlk/feral_druid/#eJzjkuRgMmCyYAxgSmBsYGRcwch4gZHxASPjC0ZGJxEORgUmB8YCkMQCsNwORkYhoGKpJ6xNjGwBOYmVqUUcHAKMUrcZufgFHkxglngpq8S27TDT1p1MXJwCJ7uZlZhBTB6Bx0C5B7Iw3s7PTBJTZSA8foFHQLkfQH1A3l6gAK/Au25miVY5JRYgj4FLQOAzkDtFRon90U6QuQxAHZN7mJU4t4K5ECMeAo14DzHiEVhgPVDPNBkltvM7mc6D3bIG5BYI81EnlMkisLuTGUguB5JCAut7mCXOyoLNvfYfrIsBKDeji1mJDRhEvAEsi5i+MnEdYGIYBRQBIQNSdbxiYqhi4WCUYNrEyCbFIpCiwNjFqKlramJsZGBkaGxkbGRkYGhgYGpsaGRgYGxgbGhgamioa2RgbArkGRo9YpTg+HKWR2DJEyaJo/uZFGZdZdI4fonJ4PAlpheMLB8Y2WcxMhxiYpJgPMF0gvEWI8NNaAyrOSh1M3OCmQ1pDoIQQREHyVkzQeCkvSVE5IK9YhoYXLM3us2kECzBoUXjNKLR6UANYxp6TxIwJxiv/IfNVY7UcAc2AAnbve8doDb8sE9gBAAGK4t+

**To Reproduce**
1. Go to 'https://wowsims.github.io/wotlk/feral_druid/'
2. Click on ''
![image](https://github.com/wowsims/wotlk/assets/30399315/5d25a626-7906-4aca-9009-94eff50dced0)

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Thanks for the report; fixed this just a moment ago in #4171. Should be rolled out soon!
