### ISSUE TITLE
Crash Report -1863482290

### ISSUE THREAD

**Issue by Goodlake436751** [wowsims/wotlk#4173]
Link:
https://wowsims.github.io/wotlk/feral_druid/#eJztU01oE0EU3jcb022odAwe1phInIMUaWV2Y0BzSaySk9DQBrxJN3ZilzZN2KTYKkIRBNv0UPAHzUlE0INQECoGKYpVpIfSUrBQe6nRQ/VghVaoJ33ZbSsiKGq9+cEO73vv+759DIxnt0I4OQQJ0g45GAC4CzADsAiwBNDsUyBIYs7gEsAIwE1b8RDAK/mGlAvgTnQb/cJSFAq+BfDU08URWX0XYO4HE2SsTDy1dLIoM7la1tE3OFsMbLDyClGv+h1WTys4W0MfsnFsbKcfirJ6cQ9zIZM8lK4gveJnNZVyNVdCx+VhmdWO2dSJeI0Ry05ExW6Mouean7mny2Ta3uVedRenrAyuly76aFDG8w6eXjo6LKtTATt37ovtknB2fUhmCl6UnHD1wS3yiXieEOk//gpe/ruO90Q661aAgkrug9vnoh1BGIIT/CdoCvOQznU8QrrONc7DIQ1ZiIc0Hta0Jp2HUcGx9wMqoCrPHxO6OlWn3n5LgqWXpGFilvAXs2QJXB+hpgTSU/IZl2Gr4FmGcyxjmD0F/OKGsEwRNy3BIgWrVzSyjNlzNJtJZfPxrNVq5lgk3Mh686LV6NqUIG02C5s0hXXSzCA/+L3dEaE/Jay8sLqqPNlpiXwni+jf2vH0RlPDpmXmjgtxxuhnkZAd15o1rJZ0Oi8KKNBRYJgdScM6LQp5lHDUGH3x9DHRXbXwA1ojy1kikc21ZE85G573Sq9Aml9/BftirCjXOvXJ2A6n2BnbVbpRxWT0sNOZie5N25iL6gsk2KZu2/+P31HDYGwrYgYmn/0ip21L/vMncO52fDl2xOFr0Xb4Cg4Q5hg=

RNG Seed: 1498557267

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0x102440, 0x1591cb0})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/druid/feral.NewFeralDruid(0x2bf6000, 0x2b26d20)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/feral.go:44 +0x2c
github.com/wowsims/wotlk/sim/druid/feral.RegisterFeralDruid.func1(0x2bf6000, 0x2b26d20)
	/home/runner/work/wotlk/wotlk/sim/druid/feral/feral.go:16 +0x2
github.com/wowsims/wotlk...

**Comment by jimmyt857** [comment]
Thanks for the report; fixed this just a moment ago in https://github.com/wowsims/wotlk/pull/4171. Should be rolled out soon!
