### ISSUE TITLE
Crash Report -2047665862

### ISSUE THREAD

**Issue by KidGalaxy99** [wowsims/wotlk#4222]
Link:
https://wowsims.github.io/wotlk/warrior/#eJztUs8rRFEUfufc5/Xei+aaLK5p1HgLSak77zULq3n8BcqCJQuysJAdq0nGr0EUYjYkC2WhLERRwoIFTb1SSGQhbEip2XHnvYdEya+dr+4953zfPd+53a4eUpFjK7RDAmABIANwBZAFzCDWFEaQgy20fldbBQhKoVmlG5TatqbO5g41j2qhS9ADdGiUsOsSQ1nZxqU11DU6P0wMkksDdLuXsHOhiSpH5NPTFGETYYMcuPKIaM168uEj6jo9SxFDFpWkF9BhIY6H/TJI10XnWNjQPCvPPiWO3L7aB2hyhrDJ8Auh0YsB/y4aTQ75qaTLdFmMC9JF4blf8tbzPOlyzxYyve8lhipeSqklDfIcPqC+idI/foQg/2rHDUpdsgoMO9SQQiEiskGot7jJTYuLJbb3qLTMGOdCiuVCVEQravIYj1qxaOVHDT4ugKkLDtIpB1nawcj6I5b3OMj7HLwC+Q60NEhbiAx2cReOQTryP0SZbaSI5qaJFrvQI4vs4vR0DnvxKo/JxEtbXBzGzROM1LG8ij/+UuUD9m/YJPZ2PvGp+5U534H3thu3drVXZ+ON8ARouZLm

RNG Seed: 824636956

interface conversion: *dps.DpsWarrior is not hunter.HunterAgent: missing method GetHunter
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0x105fe0, 0x2a48870})
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/wotlk/sim/hunter.init.1.func1.1({0x34c488, 0x2becfc0})
	/home/runner/work/wotlk/wotlk/sim/hunter/wotlk_items.go:219 +0x2
github.com/wowsims/wotlk/sim/core.(*Character).applyItemEffects(0x2bb4000, {0x34c488, 0x2becfc0})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:310 +0xb
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x2bb4000, {0x34c488, 0x2becfc0}, 0x3028a00, 0x298ba40, 0x3027500)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:261 +0xa
github.com/wowsims/wotlk/sim...

**Comment by kayla-glick** [comment]
Fixed by https://github.com/wowsims/wotlk/pull/4225
