### ISSUE TITLE
cookies are clashing between sims

### ISSUE THREAD

**Issue by owensands** [wowsims/wotlk#4223]
**Describe the bug**
its seems the SOD alpa warrior sim cookies have overwritten or clashed with my wrath sim cookies. All my wrath profiles are gone and my sod talent setup is now in my wrath one. Cookies are probably being named the same between the two maybe and that is why there is some bugginess going on there? Not sure. I didnt clear my application vars for the wrath sim and the  profiles I had are just gone. Latest chrome broswer.
**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kayla-glick** [comment]
Caused by https://github.com/wowsims/sod/issues/203

Finalizing the updates today with https://github.com/wowsims/sod/pull/244

**Comment by kayla-glick** [comment]
Should be separate now

**Comment by owensands** [comment]
so you named the cookies the same between sims? Was that the issue?
