### ISSUE TITLE
Missing Recklessness: [Recklessness]

### ISSUE THREAD

**Issue by Halroc** [wowsims/wotlk#4230]
https://www.wowhead.com/wotlk/spell=1719/recklessness

Seems the sim isn't recognizing this as a spell, even when i try to manually add it to the pre pull actions the option just isn't there.
![Recklessnessbug](https://github.com/wowsims/wotlk/assets/73409697/8c14ddb5-1a3d-42f7-bf43-70a98eeba7bb)

**Comment by kayla-glick** [comment]
Hey @Halroc 👋 it looks like there's a Recklessness toggle in the player settings section of the Settings tab. When I disabled this I got the issue you're seeing. Re-enabling it fixed the issue

![Image](https://github.com/wowsims/wotlk/assets/12898988/b9ba3bff-2c07-48bf-9233-64b390f9b437)
