### ISSUE TITLE
Gems are no longer always visible in hover-tooltip of an item

### ISSUE THREAD

**Issue by Annoa** [wowsims/wotlk#4236]
**Describe the bug**
Gems are no longer always visible in hover-tooltip of an item
![image](https://github.com/wowsims/wotlk/assets/1454488/a02a04ea-ab94-4abb-a15e-97edd5322a3a)

**To Reproduce**
1. Go to '[wowsims.github.io](https://wowsims.github.io/wotlk/)'
2. Click on any sim
3. Hover over an item that has gems set in the sim
4. Notice no gems in the tooltip, (if you do see gems try another item because it's messed up with around 95% consistency from my testing)

**Expected behavior**
A view of what gems are chosen for the sim without having to click on the item and then checking each gem slot individually. 

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 and iOS
 - Browser Chrome, Edge and Safari on iOS 
 - Chrome Version 122.0.6261.112, iOS 17.3.1

**Comment by kayla-glick** [comment]
Hey @Annoa 👋 we started getting reports of this last night. It seems like wowhead broke something on their end with how gems are displayed in their tooltips. We've reported the issue to them but at the moment there's nothing we can do to fix this

**Comment by kayla-glick** [comment]
I got a message back from wowhead today that they fixed this issue and confirmed it seems to be working again
