### ISSUE TITLE
Wotlk DK Armor error?

### ISSUE THREAD

**Issue by Omalich** [wowsims/wotlk#4241]
I am currently using the tanking simulator for my Blood DK in WotLK.  In game with no external buffs I have 31160 armor in frost presence.  On the SIM with full raid buffs I only have 25534.  Doing the math it seems that the simulator is not taking into account the full bonus armor from Frost Presence (60% of current armor value).

My base armor in game is 20767 (not in frost presence), and on the SIM it is showing as 20766 (armor value minus buffs).

Without trying to figure all the percentages from talents etc., if I just add all the values from my armor contributions (not trinkets, rings, or cloak), I get 17334 armor times 60% should be a bonus armor value of around 10400 armor.

20767 armor not in frost presence
10400 bonus armor
31167 total (very close to my in game value of 31160) in frost presence

I am not sure if certain armor slot items are not being calculated in the simulator or of the % is being calculated wrong?  The SIM is only currently giving me 4768 in bonus armor from frost presence which is about 2.75% not 6%.

https://wowsims.github.io/wotlk/tank_deathknight/#eJztVM1LVFEUf+fcN883F8Xna5Dr9aPxUSFDQ3dmVMzNTP0FggQtbZFEtIhc1cokNUdEihCdRUMWUotqkaBZA5UtNBBmoUIGYVoqRllUYPRBd+6bCRdiVLbrvA/OOb/f+Z17z3tcustECxkIPAYnoRXgOsAoQBpgBWAdMI3YinCw1AIGfhAQk6zzipUGnAdcB6hHC2yNX6VtYDScOHL66Ckzz6L8GdBCK9VL2FCFY1wbx6m7SL3WzUV0SEq6+daYxBbLHTKiokQnYc9LHLIko0LrRg9hL0ocQxZl4ALrTjdh8QpHl7Amw/uy9lIutK2PHYRdKHO8kp5MqgrbGpYVb8tVbnQJF5RsV5KwvjLHGHFlvVZvnLgtvdbLrqyrW8NdRL7H3mdK5tsJ65Q7kLryppoELsuiAlMX3gZymDR55DgG8RPSB6j9t78yW/xuxSpqZwwTGPqhDZFrcdgrRE11KByqiUQiQkREOCxCmScSjIgadUkLh4KSJsILwMy+abTevEI2OI3+3mms6p9BMTCDK6C/g7wEaI/wis4I9VGTG1Q3Oz+jY1LpBUOihe7IZhNT6ORRDyXB2hZaRA2uU2RF2VSoxdY51mt2BS+jdsAydZvMgcYVWi12K4X+b7gl/vA22RSvzeKz3zevz+HjX7fGlyVezktpUaDQNGzyROIyTbFaKHjtHrEZL6b5DqVmOJMZuUUU8mWK2JyzDciQROSIzLMdxA+2w/20OOCTTc3jOVQpR1rc0fUQu47X0oBdpRbnsT0XEU3kcnEUxMYcyeaU+jmlntuSZKwCmnqOkVvZPh6klXznRhVwOSHqHYQMLf0BlWBcCVLuftH11/jTl4xNZ1Pn9lluJxM4kTk258DnPZSxZCpW5P6hGPMbT7Mnw56Y0028ym1tzhF8sZLEQMYmo/vdTDpa2axsNhp+hv5G5gn847Olqiu2HTKtk49/odO4LX3+xNzZptZiB9x4PdoEPwAl5dlt

This is my current gear in sim and attached is a screen shot in game.
![WoWScrnShot_040624_095702](https://github.com/wowsims/wotlk/assets/166241428/13f19b36-7057-491c-a344-2c1a416d241b)

Thank you for your help

**Comment by Teebown** [comment]
![Screenshot_20240407-074148](https://github.com/wowsims/wotlk/assets/108202746/f17e2854-b54f-43b8-9483-890e08db4c12)
The sim casts frost presence for you.  If you look at results->log your first few casts should include something like this.

**Comment by Omalich** [comment]
Thank you for the explanation and assistance.  I appreciate it!
