### ISSUE TITLE
Mage Arcane Talent "Presence of Mind" not able to be talented. 

### ISSUE THREAD

**Issue by pilotchute** [wowsims/wotlk#425]
**Describe the bug**
Presence of Mind cannot be talented on the mage arcane tree

**To Reproduce**
1. Go to mage talents
2. Add enough points to arcane tree to enable the row containing Presence of Mind
3. See error

**Expected behavior**
Presence of Mind can be talented on the mage arcane tree

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/mage/#eJzj4uZgOsDI+ICR6QUjoxMbB6MEowajEJMBo1QbaxMjW0BOYmVqEQejALPUNUYuAYGnPUwS7U8YldjWdDMd+c3IxSLQ2MIEFG96wyhx7SFQ/MxvxutAcV6BQ91MEv+amJSYgSJcwgL3gRoP72ZU4oQoAAnyCfT3Mkm0bWBUYgFyGbi4Bf6+ZpT4cIdRCcjhEvjbywSVEBa4BNR9aS9Q9xGw1jNgG/r6mCQeTobawCGwDWhhxwYQa1cPhMUi8PgviGz4ABJdABRdABZt7mbi4hRY3QPRqsTBwWjAGMCUwKx1golhFFAFVAFTkgBTAKOTHJeYkIgAs+SsmSBw0l4RIv/AXohBiomDsYtR0MjYwMDA1MDY2NAASACZjxgZXjCyfGBkn8XIcIuRQWkyMydYT0OagyBEt4gD3DxLiMgFe8U0MLhmb/SYSSFYgmnQRmaJAzVMaTh5hIA53lSxBwQgYdxx2MERKuCQwAgAxLN1Cw==)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by jimmyt857** [comment]
We haven't started work on the mage sim at all yet, so that page isn't really functional.

I think we'll be starting soon though!

**Comment by jimmyt857** [comment]
Fixed now.
