### ISSUE TITLE
WLK sim Retribution Paladin DPS Rotation Missing Spell Reckoning

### ISSUE THREAD

**Issue by xjc520** [wowsims/wotlk#4257]
WLK sim Retribution Paladin DPS Rotation Missing Spell Reckoning
![QQ20240717-065143](https://github.com/user-attachments/assets/f5a2e362-cdd6-4d91-892e-ae888434d43b)

**Comment by xjc520** [comment]
![QQ20240717-065401](https://github.com/user-attachments/assets/c3f5aeea-b767-417c-8290-07e379a670ea)
Because rotation missing a spell Reckoning so the Results keep miss Reckoning at the same time.

**Comment by 1337LutZ** [comment]
@xjc520 Are you sure it's missing? `Reckoning` is a passive talent for Prot: https://www.wowhead.com/wotlk/spell=20182/reckoning

Hand of Reckoning is the ability Ret paladins used with the Glyph that was added: https://www.wowhead.com/wotlk/spell=62124/hand-of-reckoning

**Comment by xjc520** [comment]
hand-of-reckoning，yes，this one

**Comment by 1337LutZ** [comment]
@xjc520 So it's not missing, since you can clearly see it in your dropdown.

**Comment by xjc520** [comment]
> @xjc520 So it's not missing, since you can clearly see it in your dropdown and sim results.

YEAH,Thank you
