### ISSUE TITLE
Gear selection and links does not work for me

### ISSUE THREAD

**Issue by NoCement** [wowsims/wotlk#486]
**Describe the bug**
In sims (warlock and hunter tested), I am unable to choose gear. When I click on slot icon, nothing happens. Other tabs (settings etc.) works fine.

I am also unable to use links to build - when I open the link, the whole sim is empty - no items, nothing is set up in settings etc

**To Reproduce**
1. Hard to tell, no sure if someone else reported it.

**Expected behavior**
I would like to be able to choose gear and open links :)

**Sim Links and Screenshots**

This si how following link looks on my end:

https://wowsims.github.io/wotlk/warlock/#eJztUj1IHEEU3u/tes4tKKOkGK/abBMJCHN7LJjK1UqwObC50hRaBAuRNEl1uUax0dYDSZvGEMTC31PUw59EFCVK7sTCRLKlIdiKb87rba6w8GP4eN/73nszMM/1BEnS1I1+5DBGeWAG+AbaBI6BGOhrE/BII0LWVOAL0G6lik0FJLKjbz8Mj4tmKVLrcKW8XiV1eEl+orxFpSVyk/L2gny7wmGLjNk8YNM2jpA/WVYWbO76y9ER1yXY+M9eq4zPSZ1UyXc4Y7H+wxXn83ZdJ+W/tfoYKZfYKpQfmiu1wV9LpOJ523XkdImYZ5YN36wa3lgxFT+4Z7dq9OcFw4VF8oWARtbJOa/3yHpGQ/AxKSBJmZ16l3JbWdgKHjphlol3KMGZJoUpvNJBV6AzfDI6rTOhTgchR5kwMJTuCkNtEF5BiV/XJOcmbFX9Tl7hlDrvTkh/OqUYzg2ai7AqsPwpO1l7QH4kant4youoozhrsN/zcqSGs57gN3mDip7sh7+PGjElv7/zyJyBhtxj8KbGk9tRbz0RDeEegQZ51A==

![image](https://user-images.githubusercontent.com/106964902/183067904-5f2a7d85-58a7-4663-821c-6708c1555cad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 104.0.5112.81 (64-bit

**Additional context**
I tried opening it in IE also, but same problem. Links does not work at all, it just does not open, no error message.

**Comment by NoCement** [comment]
You can contact me via Discord - TheNameLess#7783 if that would be better.

**Comment by Glandaaalf** [comment]
Hey mate, did you ever get to fix that issue? Or found a workaround?

**Comment by NoCement** [comment]
Sadly not. 99% of times, when I open the sim, it just won't load. Nothing is inputted (buffs, gear etc.). I can select buffs but I am not able to select gear and when I click on the icon, nothing happens. Also when I press DPS button to sim, it is just endless loading.

There is very low chance for me that it loads properly but I have to spend legit 5-10 minutes refreshing the page, "fishing" for proper load. Once I close my browser, it is gone again.

My plan is to reinstall Windows fairly soon, so I hope it might change something.
