### ISSUE TITLE
Crash Report -102123497

### ISSUE THREAD

**Issue by s4dio** [wowsims/wotlk#494]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUjFIHEEU3f9nPXcHzvwzFqMgXLYS4WB2F8FUt9raCDZXmkKxSBHEJlaHEjBqIaTxLigpw6kogpLgoYWCucorToUkKCgJVwQ5sQlpzN/bS9o0V6TwzTDMe///94eZkd0WapyAF5AFeA+wBVAGqAL8BCwjDlISNQSQ4YS5ekK70XXQMgOx4efPXo5NWkCy6xIkUW1JqJMLdGK7h3h2j9KmnYJwxOZHlBat34I6vkAZp+Idqg9f0BGrJeSqG64qMY0xDVPb6GZBqCNWTKaGTNAd8/MN4bQyr0uPqLggHDuiYQ3RLbt8X2OXv8p2QagqV/1RbHq12DiNTV/zja1Je68Fr/sFIR/T+axQl+/Yms8STWlw8O28cCRfUrwfhs2M2fsJjQc0BdOmBQp/QaeMESj+Zfy34okoVksrSMI8pFK+p3UfD4aX8nytfe27TH3P7eOQDveu7/osulegrJUK0o9vqPIVTC5XsGf5FHXuFKtg1qA1D8ZnMJw3wq53yY4HjX4dQWc+F6KUfhop5fST8TrO0t41JkcU/rdPPxU0wyVbOvqHz1BT+oSI7njuMBhoCMEo/AbC7Ikn

RNG Seed: 1394102375

interface conversion: *dps.DpsDeathknight is not hunter.HunterAgent: missing method GetHunter
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xc9da0, 0xa3882d0})
	/opt/hostedtoolcache/go/1.18.4/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/hunter.init.1.func2({0x2d2140, 0xa2205a0})
	/home/runner/work/wotlk/wotlk/sim/hunter/items.go:98 +0x2
github.com/wowsims/wotlk/sim/core.(*Character).applyItemEffects(0xa282000, {0x2d2140, 0xa2205a0})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:173 +0xa
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0xa282000, {0x2d2140, 0xa2205a0}, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, ...}, ...}, ...)
	/home/runner

**Comment by lologarithm** [comment]
i believe this was fixed a while back by adding class requirements to those items
