### ISSUE TITLE
Necrosis Unholy Blight and Wandering Plague have damage modifiers applied to them.

### ISSUE THREAD

**Issue by Akmandorr** [wowsims/wotlk#495]
**Describe the bug**
Necrosis Unholy Blight and Wandering Plague have damage modifiers applied to them.
**To Reproduce**
Check the damage calculation in the log section of the sim and see that the base damage of those abilities is being modified.

**Expected behavior**
They should not interact with modfiers as the attack theyre generating the base damage from already interacted with them. This is according to what we know from retail and current beta behaviour

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/deathknight/#eJztUk0oRFEUfue8hzc3o0vKNaXGrKSm7nuPYjWPrY2ysWRhsrCQbFgNK7GwUEKRpZJSSjN+shjFbMyUMZOfJKIRYiklzp0Za5tZWPhu3c75vu9+53bfYw0mShyEYYgArAFsAqQAcgDvgCnETu5HCS70kmEqb6jBNvAtl01CefdQ/9jAiOnhzHcAjPOHLIrkNQbKt+OY+UJm8IkYMi9/2UNxRLy+kkBm8tNdFNFLVAdISF7RARL2osiq+DRpx+d6wKBWoz5HjuzGT1/JMzvkplolcf5M6sN6gTmJquzZfRS5DZ1Gz8TUBR631P66q/anpHJ8xlDcrOrFKnmplFlKZfQM3jboNnqN5mPU/lESjBsmCPyAOmYI+otqNJ+3uqC8hQT4YRqCQceWssVplQQ7aDtSOrSodWyrlSRpUW05lkOkdQvCXE4jf75HMZ9G/0IamxbOUC6eYQ6MN6hYAu0CtMCc7slPiYTd4rxat35pUSERai8wqVBjOI9MyL5Df4/AP/vhR91SpEQSh7/kdJVkjkLhjafibkeRcPvgG8JCf/M=

[0.40] [Player (#1)] Casting Attack (Off Hand) (Cast time = 0.00s, Cost = 0.0).[
0.40] [Player (#1)] [Target 1] {OtherID: 3, Tag: 2} [DEBUG] BaseDamage:931.5, AfterAttackerMods:1122.6, AfterResistances:699.7, AfterTargetMods:727.6, AfterOutcome:1498.9
[0.40] [Player (#1)] Attack (Off Hand) Crit Target 1 for 1498.95. (1199.16 Threat)[0.40] [Player (#1)] Aura refreshed: Fury of the Five Flights.
[0.40] [Player (#1)] Fury of the Five Flights stacks: 1 --> 2.[0.40] [Player (#1)] Casting Necrosis (Cast time = 0.00s, Cost = 0.0).[0.40] [Player (#1)] [Target 1] {SpellID: 51460} [DEBUG] BaseDamage:299.8, AfterAttackerMods:390.2, AfterResistances:390.2, AfterTargetMods:440.9, AfterOutcome:440.9
[0.40] [Player (#1)] Necrosis Hit Target 1 for 440.90. (352.72 Threat)
Its correctly passing the 1498.9 swing damage on as 299.8 base damage for necrosis however its then also affected by attacker and target mods, this is not the case in game, behaviour is the same on Unholy Blight and Wandering Plague.
**Desktop (please complete the following information):**
Win 10
Firefox

**Comment by rosenrusinov** [comment]
Fixed by #513
