### ISSUE TITLE
Consumes

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/wotlk#5]
Which consumes do we need to include in the sim? Which TBC consumes stay?

**Comment by CharWS** [comment]
Potions: change to being only usable once in combat (can use one just prior to combat start and another during combat)
https://wotlk.evowow.com/?items=0.1 

Elixirs: can benefit from the mixology perk for alchemists
https://wotlk.evowow.com/?items=0.2

Flasks: can benefit from the mixology perk for alchemists
https://wotlk.evowow.com/?items=0.3 

Food: 
https://www.mmorpg.com/guides/70-80-food-buffs-2000117040

Drums: there's 2 new drums in wotlk that provide lesser versions of blessing of kings and mark of the wild (not stacking with the buffs themselves) 
https://wotlk.evowow.com/?item=49633
https://wotlk.evowow.com/?item=49634

Weapon Imbues: no new weapon oils and stones, old oils & stonesare are set to work only on items of ilvl <165
https://wotlkdb.com/?item=22522
https://wotlkdb.com/?item=28421
https://wotlkdb.com/?item=23529
https://wotlkdb.com/?item=18262

Engineering: new gadgets attached to equipment glove rockets and frag belt, along with new explosives
https://wotlk.evowow.com/?spell=54998
https://wotlk.evowow.com/?spell=54793
https://wotlkdb.com/?items=7.2

**Comment by jimmyt857** [comment]
Pet food option: https://www.wowhead.com/wotlk/item=43005/spiced-mammoth-treats

**Comment by Ocisly1** [comment]
I am not sure if this is the right section for it (didn't find any other category) - but in the gem selection "nightmare tear" (+10 all stats; https://www.wowhead.com/wotlk/item=49110/nightmare-tear) , "enchanted tear" (+6 all stats; https://www.wowhead.com/wotlk/item=42702/enchanted-tear) and "enchanted pearl" (+4 all stats; https://www.wowhead.com/wotlk/item=42701/enchanted-pearl) are missing. please include these ones.

**Comment by lologarithm** [comment]
> I am not sure if this is the right section for it (didn't find any other category) - but in the gem selection "nightmare tear" (+10 all stats; https://www.wowhead.com/wotlk/item=49110/nightmare-tear) , "enchanted tear" (+6 all stats; https://www.wowhead.com/wotlk/item=42702/enchanted-tear) and "enchanted pearl" (+4 all stats; https://www.wowhead.com/wotlk/item=42701/enchanted-pearl) are missing. please include these ones.

Those are included now. Thanks for the note!

**Comment by jimmyt857** [comment]
Just missing new explosives now.
