### ISSUE TITLE
DK Frost 2H Threat of Thassarian Talent

### ISSUE THREAD

**Issue by n9664475** [wowsims/wotlk#504]
**Describe the bug**
While having a 2H weapon equipped in gear, if talented in Threat of Thassarian DPS increases significantly. This is a strictly 1H/DW talent and should not be increasing DPS for 2H sims.

**To Reproduce**
1. Equip 2H
2. Test without Threat of Thassarian talented
3. Test with Threat of Thassarian talented

**Expected behavior**
DPS should not increase while 2H is equipped with Threat of Thassarian talented.

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Browser: Chrome
 - Version: 102

**Comment by rosenrusinov** [comment]
Fixed by #512
