### ISSUE TITLE
Spell hit debuff

### ISSUE THREAD

**Issue by TeamSpeakUser1** [wowsims/wotlk#514]
**Describe the bug**
Cannot change which debuffs to use on "settings"  also cannot de-select the debuffs.

**To Reproduce**
1. Go to "settings
2. Click on 'debuffs
3. Try to change which to use, or to not use any

**Expected behavior**
To change what debuff to use for simulation, or to de-select if not present.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](https://wowsims.github.io/wotlk/warlock/#eJztUTFIG1EYvu+/JFxOKq8i+BoQ4i1KQXh3x4FOOZ0KQhG6OMZBEXEI0qHtZDOJS4dCoU6OLgHpUEIiWtqKtVESIyrEIrQq3iQp4lr6Xy57lwwO/Yaf7/++7/3v8T9zwCBBikbwBFPI0RKwhmLfBugTUAMCYLzfgESaFHyOZDGHHF5gHSgCHOrhs6l38TwSkwvTL2cWjbgwUiWYQlyVSR6ck5XY+Uy3RTKT4u4HWXqD6QMRsPmdTX2r1V6dkmx80CNXiGt2qxxOsBse7RYBB+pnZMVY0bi/5MRpQW/3SfF7sz3LEM1NkvmdkN0wCwq6GRPVMnF9sxXWZotvl8LEPo/ZPQv7w1JY1z6SZRhQmIxPxR9/I+0/OoJXvFRBknKYT5ndzHVJaV7zCHzq0VIJViBpBYPDynVtpVxl2+6w8hzlOrbnOC3Vs5XrKdd2PfsXpHFSIfGzQvK4Qun8EQ39qZN6fUQBYk10rUJrQLPe6snoAU/9hxHp9R+tvg+xlxmNlFpmYLaFk4xzQelnku7txz/3OzFlae/rP+ZMdOSeENGOl7/4Y23Bz+Iv9gZ+jQ==)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 103.0.5060.134

**Smartphone (please complete the following information):**
-

**Additional context**
I tried to change spell hit debuff, it worked the first time. But after that all debuffs broke.

**Comment by CyberQuackGames** [comment]
This sounds like a UX issue more so than a bug. My guess is a icon is being selected which "enables" it, but the previous one was not right clicked to "disable" which frees up the slot for the enabled one. May be something to discuss on usability for these settings since it's not clear to disable ones which have higher priority in the list.

**Comment by lologarithm** [comment]
I might try to add some help in the tooltips to make this easier
