### ISSUE TITLE
Crash Report 1757577229

### ISSUE THREAD

**Issue by KAAzadi** [wowsims/wotlk#538]
Link:
https://wowsims.github.io/wotlk/raid/#eJztmG9sU1UUwN+573V9ffvjHSPm2S88+kEbkiWvffYDJqYdEDNjJBOMRj8xZSCJsKRuUfdpjhBhIBqIBAYBHIQREAMm4EY3Am6EjTCmq9loN7ZV1jkiZosaJYrBc+7r1pXEgKQxxPR09757z/3X7P56/jztjl9rcWtJpQEKllavf6OyxlhRvba2SnXyPPcx0Dg/cYjpfSPMk3emk+1uY5rCky1MK+Q7m5l+CfXyXxHQVB49yPT4CRlbH8dxwTDT8vnxGNO7Y7IHJOx8dpjpd+yOxi83M49ytZVJOH/bEaZPHGfY2oIrfx8Gzcl/+ZbRRIU3HqETtx+m+otmmtSB0w+cpCPHWuyWwi/hdgVcNvK9mgkVyiplUTeTcpIVqZNeL9JUHTh4wZDnSW6pEbymGbD8pqhLTX/AbwZ82DOtgOkL+P0WdrDlD/i+B2kSlGlwNoEUxwvNcZaTf5CscnbL0QCula8Y5bUbaqrCCBlznyXI2trTkA22Ms3Fbw8jWtQs5JH2FGkdrQRANGKTxvnIoCDNk4cDNLWIx8/axCm72hhBdx2XDp4Q0Ll4/5nUHpxvjQjmZleqPIkzJ3FXRE5A3tRO9VSE6usxmtGFawaQa2L2Arb7LuB6lRFwOdyyJnXSM+9qZeXgZcWiHzoQWmJoTHVgcWJxYVGxaFhkLAwL+Jr2kLQFF1tCokHk1FQZX+B+HGskNySXy7sBzoPcDXANYKF92nRwsb30ZtALjfAUwWwRzL7SgADaTw/a0kSufRYO+iwfYq2rB/sYP5Rk+uEkMwb7mfdyPzMH+lkO95z8C/lf4f4rRhGupRhCLAvXrlutqhzcXeTN95Tpm8fJT19MEv2f3wD9WgI8ecMRGBbBQ/0Y6N9tYVoJP4pjnRHwuOwxGs7n58ZB/zMGhHUhj4+Ax2kPUffq2JxuCb+IO41OZKzn/INRoLhizoE3UfOhCCJ+nrZbCt+fEKFEUmhxfB9qKQS5mgSPxgsNh/lYhboKcvBnTeqkL4FjNAg6eB2moxzs6GIBwmghiz7LbyGFJlGIsUSpGUA9tu8JKuZJ2qRT+0lugPyy8JuVG6qMFyvXVqkuLrs9eIH3+XhUFcx8jBlZ7mKzJnXSEjRYXMH7RJPVCIv8FgWLPosiQ7pCvEiKEtHciAjSQkOEapwkbM3eUcanepl+t5cZ42hrxtDW3B7JtDW5+36E5D+4b/HBn/o5h3YKo6qCinB1jVFR+Xbl6nUbVOCKO0aWfhu6j4ZxtPSJCBy9TPZ8fIT021E/lbD1CeEB9sVAv9NALqcRx07H0WXYYzRcxAdGQN90EjxKgvxKMZ/A/jS6EKc9gzzPrtE53RLeiy5jbCJjG5WfmgI9sZPCqVH0YZuFx9k4ZrcUPj1C9b6zpG1IgL4XtYV8D7b+wKNk2kLhV9D9qKrTUMz5FQU5ZrMmdRLyQdEUQavLmNSigxHQYjpLrJIDQvEhyxQeEdIiy7UI2esDjG+7wPRTGA5NIrI/ILLJdDjkKl4jZCDYCjCLrwD4o3ytmwB+rjb8vvFqZTi8rpoyA5e7l0A91pnODAbuUmbwaS+G8ft7iKFDMZEZ0DuWIzNJwZnTTO8ZwgU4pb115q1L15B4f1LE207bGYGSpJctBfy3jvRUznuaU3kBdm3NjrjIC2Y1Lr6DzsfVsy9jfuyj+lYHfY/hFqZfGcpsXWpOJwtKhZxDNmtSJ4Wf1SwOBqYLZbZqWeh5u7E89JJ4nl8Res3WqKFV8Ba8B/VAiCsUZWHIb5l

**Comment by jimmyt857** [comment]
Thanks for the report! Unfortunately the raid sim is not working yet. There's a warning in the top-right that says its not ready.  :)

**Comment by KAAzadi** [comment]
I apologize, it was something I left open thinking it was for a personal project of mine and not the sim. Sure would help if I read the title or other data rather than just blindly submit.

On Aug 7, 2022, at 3:28 PM, James Tanner ***@***.***> wrote:

﻿

Thanks for the report! Unfortunately the raid sim is not working yet. There's a warning in the top-right that says its not ready. :)
