### ISSUE TITLE
Incisor Fragment is incorrectly granting 291 passive armor penetration

### ISSUE THREAD

**Issue by Palmie** [wowsims/wotlk#551]
**Describe the bug**
When selecting the trinket "Incisor Fragment", your character is granted 291 armor penetration in the character stats section.

**To Reproduce**
1. Go to any sim
2. Equip Incisor Fragment in either trinket slot
3. Look at Armor Penetration in character stats and notice it has increased by 291

**Expected behavior**
Incisor Fragment should only give passive attack power, and the active should grant 291 armor penetration.  Those two effects seem to be working, but it is also granting passive 291 armor penetration

**Sim Links and Screenshots**
Without Incisor Fragment equipped: https://i.imgur.com/k8SzGeS.png
With Incisor Fragment Equipped: https://i.imgur.com/HnSbSJr.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2
 - Browser: Chrome
 - Version 104.0.5112.80 (Official Build) (64-bit)

**Comment by jimmyt857** [comment]
Looks like this is fixed now.
