### ISSUE TITLE
Warlock pet food

### ISSUE THREAD

**Issue by Putridbeast** [wowsims/wotlk#578]
**Is your feature request related to a problem? Please describe.**
Warlocks do not have a pet food option like hunters do despite all specs using pet

**Describe the solution you'd like**
Add the option for mammoth treats in the same location as hunters

**Comment by Putridbeast** [comment]
Since destro uses the imp, it may be more valuable for them to use sporeling snack for a little extra spirit on the pet

https://www.wowhead.com/wotlk/spell=33285/sporeling-snack

**Comment by Glandaaalf** [comment]
Thanks for reporting the missing buff 👍 
This will be in our upcoming patch.
