### ISSUE TITLE
Warlock IDT too high

### ISSUE THREAD

**Issue by Putridbeast** [wowsims/wotlk#581]
**Describe the bug**
Improved demonic tactics is increasing the pet's crit too much, 65% over expected value.
 
**To Reproduce**
select base demonology talents, then remove points in intensity. add them to IDT for testing. 
run each iteration and check the FG crit rate in detailed results, then increase IDT and compare the different rates.
consistent between sets, used the P1 bis +3% set for these numbers:
32.25% player crit
0/2 27.54% FG crit
1/2 36.55% FG crit
2/2 45.42% FG crit

**Expected behavior**
Each level should increase by 10% of the player's crit, about 3.2% in P1 bis
instead it's increasing by 8-9% making it much stronger.

**Comment by Glandaaalf** [comment]
I just fixed this issue and it will all good in the upcoming patch. Thank you for your report. :)
