### ISSUE TITLE
Blinkstrike issues

### ISSUE THREAD

**Issue by lologarithm** [wowsims/wotlk#597]
With 2x blinkstrikes a nil pointer error is thrown.

https://wowsims.github.io/wotlk/deathknight/#eJztUk0oRFEUft+ZZ7x5mrrYXEqNt5CUuvNer1jNY2ujbCxZkIWFZMPGNDaShZIMUoqFkrKwmLJQfmJIZjEo4y9/TUpZSFLkvnlkaTMLC1+30/n57vlu5x69QiNBXehBFFgEVoAUkAVeQSmiRhYiAQetkjCcI5Qo5QsFMfibu9v7O3q1ANPL96EzdvAOfnhBhn97g17WoKts6dnNTwwR33HzmTXIowfZdYx4IkOGz6WVslVJSMow4BFcThFLfIBvySQUvZjtjRI/WfYZhV5ZkT1SD/gJNZZ4Ab9fIik3dgaeldxvOZXNPrp2/ty10ZyNZSDv3D6DX875vrwr6cknr5Ohy4EE69Cstqo1u6T8Iy8YUDVwekOZ7mfgcqPkHgWLvdpThCOEEVSZlrCFEHatZUpr2cKyTVNYIiwLQlhWWIQtO3wNrs2kiU2miT/eUSiepur4EYmpI8pCfULhNJRTKMa4L5BrH+10PCFn0CmbnnKRjNR70qlIZWcOxxHzhkItnP7sn/c5+egSTW790qcpLzouvBkPbzoNXwmnDZ+aFYTa

**Comment by lologarithm** [comment]
Oh, duration variation is > base duration. Negative time could be causing the issue with the infinite loop with single BS.

**Comment by jimmyt857** [comment]
Note that if we fix this, should consider backporting it to the TBC sim, as it was reported there too: https://github.com/wowsims/tbc/issues/1084

**Comment by jimmyt857** [comment]
Blinkstrike is no longer included in the wotlk sim so this bug is irrelevant.
