### ISSUE TITLE
Crash Report -790387441

### ISSUE THREAD

**Issue by buriedalien125** [wowsims/wotlk#628]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUjFIHEEU3fdvPdfRC2NIMV61XiXCwewuQqxuY5tGSGOZFJEUFiI2Wh02iikChoAeJIiaQyOBNIErlERPSLa6K04FBRUl4UCLK0WL5M+dYGlzhYVv4DPz3vv/DzNfuA5peoNRZIFV4BvwEygDVeASVCYakC5phBhiz0zd89hK5lumEB8ceTXxesxplSK5ASHllyKp0hGl4oUi7f0jYcsPKyQS8vozqV/MxzYKJBz5Lk+qcEicsPWdVHTICZ8iMlq7fMsldpiBJR7JbZb3v8ZSNmuW6JC1Tbbynt2cHC2R+rt+myzl3AGpKvuNxzC2nM2bOH1s4sWmieclc4W1bVInizFhMbP8g1KCHyHxFIP2kN37m6wHNAWTtgNFV+gScQnFI8SDk+hsaLWMgotZpNOBr3UfL4af9gOtAx14fAx8r48lbfZe4AVMeqdQzscKyYs/pHIVcucr1DO/S3phl6qwa2jNQfCnmkXCOoCVeh9rq/fLDoc3nZ+EXbkFgyjT32DKme7hOvYy/hm5LxTd2yEYD5tRJRvt3FHneVP6GDTeeKYYPrshwpf4D6L3fUo=

RNG Seed: 233750771

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xc6460, 0xf23950})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*majorCooldownManager).finalize(0xa36b238, 0xa364000)
	/home/runner/work/wotlk/wotlk/sim/core/major_cooldown.go:196 +0x1b
github.com/wowsims/wotlk/sim/core.(*Character).Finalize(0xa364000, 0xa3401e0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:347 +0xc
github.com/wowsims/wotlk/sim/core.(*Environment).finalize(0xa219200, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, 0x0}, {0xa33ea40, ...}, ...}, ...)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:122 +0x33

**Comment by Deathdock** [comment]
This mistake happens if you don't select Vampiric Blood and Rune Tap they are probably in the rotation regardless of the skillung and there is no check before they are executed.

**Comment by rosenrusinov** [comment]
I think this happens when you have a major cooldown configured to be cast at a specific time but then you spec out of that skill. Thats the only way I could reproduce the error but I could be wrong.

**Comment by Deathdock** [comment]
I could reproduce it with no buffs no cd's the standard custom enemy and no skill point´s used. I tryed it on my phone and to different browser(chrome and firefox) and i cold replicate his issue.

**Comment by rosenrusinov** [comment]
opening your link and then removing the broken setup you have in the major cooldowns dialog gets rid of the error. Have you done that?

**Comment by rosenrusinov** [comment]
@Deathdock can you confirm if the above message is true for you? I still cant get the error in any other way except with a broken Cooldowns configuration

**Comment by Deathdock** [comment]
Yes I have don it but today it worked for no particular reason

**Comment by rosenrusinov** [comment]
Ok, we will follow up on fixing the crash for the cooldown interface so it removes any major cooldown if you spec out of it so this doesnt happen anymore.
