### ISSUE TITLE
Hunter explosive trap / frost trap LnL procs

### ISSUE THREAD

**Issue by deadmage** [wowsims/wotlk#635]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please sim explosive trap casts instead of black arrow, since the DPS increase is way better with the glyph. Also frost trap to proc Lock n Load + Snake trap for small dps increase.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jimmyt857** [comment]
Not sure what the problem is here, there is already an option for 'Trap Weaving', which uses Explosive Trap. You can also create a Custom Rotation and add Explosive Trap there.

**Comment by deadmage** [comment]
Ah, could not find that option, ill look into it again. Sorry
