### ISSUE TITLE
Spell hit is not taken into account in statistics, and also a very high priority to hit and sockets even if it is

### ISSUE THREAD

**Issue by Landate** [wowsims/wotlk#639]
**Describe the bug**
Spell Hit in debuffs does not count towards spell hit in the stats window. Also, when choosing the best item for a Sim, the one with more hit or sockets is taken into account.

**To Reproduce**
(Spell Hit Problem)
1. Go to 'Settings'
2. Click on 'Spell Hit'
3. Scroll down to 'Stats window'
4. See error does not count
(Very high priority for items with hit and sockets)
1. Go to 'Gear'
2. Click on 'Choose an item and see'
3. Scroll down to 'View stats items'

**Expected behavior**
Fix this problem

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
Screenshot as an example that ronin's robe is weaker than t6 honest, although ronin's robe is much better in terms of dps (there is a t6 bonus)
[1](https://i.imgur.com/Vwow3Kl.png)
[2](https://i.imgur.com/rzGj2vq.png)
[3](https://i.imgur.com/1d8zS86.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [103]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
Spell hit from debuffs is included in the bottom-left stats panel. This is easy to see by mousing over the magnifying glass icon and it will show `Debuffs: 3%`.

As for the EP values, they are controlled by the options in the Stat Weights menu. If you don't like the defaults you can change them there.
