### ISSUE TITLE
Crash Report -1952536294

### ISSUE THREAD

**Issue by Scrapa05** [wowsims/wotlk#640]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1IW1EUft95z/T5aORaHK6ZnplEEG7eI6BTnq4uQpeMdag4dJDiYqfgJOmQoUviIHYriFAoSOIPCAZshjaBagK1qFhiI43gKILQc5MHjl0ydOg3HM453/edA+dex7VJ0QIWkQE+AB+BA6AGtIA7UI1oWrikECDNmtWO5pkRe9+3gsjsq7nll69tCCdWhiPEVYNk9Yzike1D+vqFnH5x94Pi5l6RnKi42SN5dBaWtvi2S7J4StrFROWUXesV0tyAyDJX5o7FpcF1ixWNLTOsn4r6Dqs5ZwP728xebT76bZHbJ9naMh1LXH8ijm9LOh7s6Pi7qhUPJZLnG2aYXWxobY6nOnyM6ARmrbQ19pmM/+gJ3lg2JN1j2IkISP5K/IGig13uNiXhIosxz1dJ5amkr5TyfeV7fiLBPZXwk4nxcc48T2mJ8i8h7XaTxE2T5K8mufljGs2fkCqcUAvWLZ6swfgOI/7O7O+syMwH4bKhYHitoFFJTXY7tdTIfAf1lPeT3OeS/tl3Xwp6MSVTKf9lzkxP9mh0b7x6GEyFjeAF/gAXD4JN

RNG Seed: 1815803215

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xc64e0, 0xf249b0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).CanUnbreakableArmor(0xa2f6000, 0x24a36c0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/unbreakable_armor.go:58 +0x6
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).CastUnbreakableArmor(0xa2f6000, 0x24a36c0, 0xa279500)
	/home/runner/work/wotlk/wotlk/sim/deathknight/unbreakable_armor.go:62 +0x2
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_UA_Frost(0xa2d40f0, 0x24a36c0, 0xa279500, 0xa2e3aa0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:138 +0x4

**Comment by JooperGH** [comment]
This happens because the frost rotations assume you have Unbreakable Armor talented. Just as the UH ones assume you have Gargoyle.

**Comment by JooperGH** [comment]
Fixed.
