### ISSUE TITLE
Crash Report -1050107737

### ISSUE THREAD

**Issue by Atgeirrr** [wowsims/wotlk#642]
Link:
https://wowsims.github.io/wotlk/protection_warrior/#eJztkr1LAzEYxu9JT3sXP4htkegg9UAQoZDrcYMuPV1dBP8BHezkIOKiU1XE07WTXVzFycFBcGwHaymIFsEPqK0fuLU4ODiZeCo4uXRw8Am8JO/v/SIJ7TUIgyAzWCA+yDPQBPEJJoy4POMIGNMiWn+2bQ3tU/Ozy3OLMt7sPwdl7KIO7j/Aat87Re0Y1GSVW1ih100iYVXCRk1CSRQ0WOYOvLJFaJRVJMsfwzIDpnA3K0jnxgEsXeZrtIMdNsBX14kFjYZZvg61ibJyFfzu6UcqYyVZuZYl37109tJUtvqg7NWNsqVHNUNZRu4egHaxnRr4mxo3SMipUY1OEZvqHDkh2r9aohXdACf7iFDDAMMw+ID8THqcDGMbQ44rhHCE7YhkQjgJIVzXtW3hSJdariSuXYf2DL2JcA5mT/pDlyn5La+hWdmQ+dEmk/Z6goYxry+3o1RMjQaes9TgV1bynsSnOfmz77vktaJKplj4pc5kS/ooBXfs573xT4c3g3cHV3vS

RNG Seed: 3901371997

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0x134b40, 0x245a5b8})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.ThunderClapAura(0xa1e8000, 0x5)
	/home/runner/work/wotlk/wotlk/sim/core/debuffs.go:846 +0xe
github.com/wowsims/wotlk/sim/warrior.(*Warrior).registerThunderClapSpell(0xa1ec000)
	/home/runner/work/wotlk/wotlk/sim/warrior/thunder_clap.go:39 +0x38
github.com/wowsims/wotlk/sim/warrior.(*Warrior).Initialize(0xa1ec000)
	/home/runner/work/wotlk/wotlk/sim/warrior/warrior.go:125 +0x40
github.com/wowsims/wotlk/sim/warrior/protection.(*ProtectionWarrior).Initialize(0xa1fc100)
	/home/runner/work/wotlk/wotlk/sim/warrior/protection/protection_warrior.go:72 +0x4
github.com

**Comment by jimmyt857** [comment]
Thanks for the report! Protection warrior is still pre-alpha though, so crashes are expected.

We'll actually start looking at bugs once alpha is released.
