### ISSUE TITLE
Massacre weapon enchant adds 0 AP rather than 110.

### ISSUE THREAD

**Issue by KansasCodeGuy** [wowsims/wotlk#652]
The Massacre two-handed weapon enchant on the hunter sim is providing 0 AP when it should be 110. Currently the sim defaults to Greater Savagery which provides 85 AP instead.

**Comment by jimmyt857** [comment]
I'm toggling this enchant in the hunter sim right now, and it's definitely working (adding the appropriate stats). Thanks to your comment though, I noticed that Massacre is not flagged as a 2H-only enchant though. Fixing that.
