### ISSUE TITLE
Warlock: Drain soul does not snapshot haste

### ISSUE THREAD

**Issue by jarcangeli** [wowsims/wotlk#653]
**Describe the bug**
Drain soul dynamically changes tick rate based on current haste buffs. Should snapshot to cast start for whole duration.

**To Reproduce**
1. Use below sim
2. Iterate until you get a haste buff expiring during a drain channel
3. Observe next tick gap is longer when it should be constant

**Expected behavior**
DS should snapshot haste + sp at cast start for whole duration.

**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.]

![image](https://user-images.githubusercontent.com/14232622/184735058-4ebe5b87-6e54-480f-8397-a8309afef9c2.png)

(https://wowsims.github.io/wotlk/warlock/#eJztUj9oE1EYz++7a3i5WnmNDs9M5y0WofAu50E79eokCBJw6VgpdhAHERc7pQGppB0Eh9JClwoqWkHEQYQEUYNGqK0NWJqWUpSW4CBmKJQO0u9dFHFyydDB3/Dxfn/e9z7uPscVJElTH85hCNcoD9wBnoJeActAAzjbLeCSRoScSeAhkOZ4ZqujgGTu6qWbl68LW4rMEhwpv2+SWtwkL1l5TeUX5KTk9CJ5VpOPUs5PkvpgTHY+siJksUKq/sxir/qc1NLGH69TNu+RWlknDwkm41VSq08sQ47IvRLnOGQeOCZvcddChbxUOVbM5S75aI1Ug/NWPR5i9xO1jrYs3zf1W8nU5gMzxNwWqXfrhu+XTHhhisPcyRMCGjl7qOP0e0r8R1swlhKQpMyeXck4R5nYiterh790H6UTmWRLKeJUNgi11lkdcAlCX2dDIwSB74d+b29oTK1D/wuUmJuw5No2qdo2uYUa9fxcIT1eowbsH+icxRlH8s+9+5LSIp5heCRyXMcWO4+ttPp7vAvR70QdCa9opWKaH426W/7x6MTsjEF14ORojM8D2a/kXlR0aJfkRtSOLvnq23/0Od+Wdwz643r7TTT4S4iGcQAry4aq)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: See link?

**Comment by Glandaaalf** [comment]
Thank you for documenting this issue.
Yes there is indeed a problem with Drain Soul and it shall be our next fix.

**Comment by lologarithm** [comment]
https://github.com/wowsims/wotlk/pull/1722
