### ISSUE TITLE
Crash Report -703648935

### ISSUE THREAD

**Issue by Luxor44** [wowsims/wotlk#673]
Link:
https://wowsims.github.io/wotlk/raid/#eJztml9IHEccx/c3u6t7m1PGM5TNQdrLQukROJjdZSH25c60D0JfpCltyVNsqiVtGuFQCj4ZQ0hiH4OQCK0l7UOxBIQGGz3TNjkhmsRaPBurJhptDCmUKn0oJQ+lv9/eJf6hYApXetb5nje3M7+Z2eW+n1t/s7tm30Hzgm526R0Qrk83t8TeaEinjzSnDZ2HohNgcp5bBOv0fbDLPr8BCxkwQ3zyDtjq76cYBucxuLyAQYxQ0ODt98CaPMPMaj6JsWwG7FA+RuFKPoyNJ/vA1nC8Yu7gl5bBOn6C2aCY5Ty7CLRRzcfmwbr3YN1Qzm/izAtn2ZN9afy3FSrn71M5PUvlzSU6hjHs2dMHZgU/vwDWIzrc/IBuOlQjLHbWh/eOMEWqKGpTeiFiGgZwiIP1bESJajEWh0543vOFEJ5wPOEmhJcQwvd9xxEeNtHLx4jvLILyELQVKO+GUFVToNvJywAziELhFVHMExHzhtoBFfsbjjYcO9wYezndeuRto4xD1DaVzV5oOgio16TpRVOb4oZNZgC5jZ96J+z2HSFc13NcX3horEuFk0j4LjLgrXFZIWelmSWkDWaWSTO3sDaYWS7N3MLaYKYhzdzC2mBm6B+aiVnQV7vNXzFVDx14PVbXeqylMY1usuggpccDQ8wan8P0uD/Lzg0wzNP/uMNstWeUYR6cweD1uULV4LkMs2YuqjhqbopZo7M4CgNXLjPM0GcGmTUyrdoaVilDv4tDpy6qlJiH+EQ/zkH9OP8Q53jwBY7EKrUYfAl7PsRZNd6J+8dse4jK5QyVd6epxzCOyc4yxMvgV3F7/CqzDYMJ2CdBK6balBc/MGvrIM6qgnqqJ7U/Rlka/T8g8uhUgm8T3yq+GVHpdJ8nDSRrvEC5JHIqDMafiz6DJeb2KbVOPQfwLagjAD8C7MnvbSVZkx/6c5Ky/hcSwvU9gWQ7Ccr/hecGywCU8F0XAacVgYN5v2V8Ms74p0vM+myJxaYmWPzGBBO3J9i6U5gEXmozSeAl8NtKEngJ/LaSBF4Cv630fwIeV669u8yTdJPppeb332poib3a/E5ro6HzsujXBP6Xa8D/buwJ+L0B+P2Pwf+4Zy34FXx2KA9+EKjkP/QzaxirWpaor+R9Beq1R1QP8eFB7PpNAP6loQL42DUbgN/V/3fg/3JlFfwL2OPWLG1dy+S3NPoBBPDr9dohCX/x1KYcjOAXrVlMqPsYXS/hzEIu40L4nosk+q5HiLqEKJLp+cIJrqNgRDgu3VQKG9eWGL+OYE6Prz/7Sg6lnlKSQ8lhKUhyKDksBUkOJYeloH+TQ1ysdIXNDq0DdtQ2NdEDcUebD7+HLBpPddvUCG6b6m/q0u6iqU151zLDaDfQg2UCAsvLDKAWXKy6wXNmrvCw8NBwXLqS57g+De6lBgtY4QeL1Y9OqXwaPc/hYrUjx+J/4mL1eG7V/zMFz2pSdEaSEJSQJARS/xkECj2EGlH2KrYSfc2sNqtgo6hR0zSGfygsdPygRpxDo4k0TdE1TVeVQuOqaE/2WTUUVNqbUoXoztSu/DW50WRNvuX75J7HD8i6P7HYAYuVLFotqWLM0j46vMk8rxRlP6T8d3w6m6otNKQOwV+HMzxY

RNG Seed: 0

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 7

**Comment by jimmyt857** [comment]
Thanks for the report! The raid sim has not been released for alpha yet though, so we aren't trying to fix any bugs there yet. Will look more when we actually start supporting it.
