### ISSUE TITLE
Remorse doesn't get diplayed under the correct phase

### ISSUE THREAD

**Issue by SkullCandyTV** [wowsims/wotlk#676]
**Describe the bug**
Remorse and other weapons don't show up under the correct Phase but show up under the wrong one ( Phase 3 instead of 2)

**To Reproduce**
Chose DK DPS
Chose Phase 2
Chose Weapon
Can't find Remore under Phase 2
Can find it when selecting Phase 3

**Expected behavior**
Remorse to show up under phase 2

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
Chrome Browser latest version

**Additional context**

![Screenshot 2022-08-17 210724](https://user-images.githubusercontent.com/89059544/185222555-2fc7b2cf-5f6f-4fc7-8561-a0a70cc1e45d.png)

**Comment by rosenrusinov** [comment]
Should be fixed from latest DB update
