### ISSUE TITLE
Crash Report 1913362581

### ISSUE THREAD

**Issue by bjsmithxyz** [wowsims/wotlk#686]
Link:
https://wowsims.github.io/wotlk/raid/#eJztlk1IVFEUx++5c0ffPEe7Oi5esyh7EIgwcOc9HtTKiVoEbaSCoJVGGS1CGHTjygyx3EYLJZJaRR8gFWKNGTkjNpUaZR86kzqjIwWB4qKiNp0zM5W6iWKCFnPe48y9538/3pv74z+jp6v1K9X6RXcneBvCLa01R5rC4VMtYc0tPf4XoEv5Mg3GuSUwS649gVQEdI+cToLp+tTNUZxHcSWFIiokarJjAYzp81z3yWnUohEwPTmN5AoZw2LXAJgC5zO9TN5dAePMWW4C00tlNA3U8MmJeTAWljdMlfIprpy6wH/uJeTaKuX5JcozCcpPM/QMEziyfwD0ctmbAuMrPW5uQh89quZV1Q3eusecFaMg0c6uQ5WuaSChFoxtVcwvangt9MBO21FK2SpoKyug7IBSjuMEg8rGEl0OKk4wDew9iFUo7QNPZXM2XtcPAcwiCmuiEzx7m1pr9oXbTh3XSiT4Y4Ck9O4hJvFExzKExs1FMN7S2SYjkNyE4bXFPIY5jeQyObIExreZLG3lcnYOzNKcRN3JhXVdnxzDleaXN8yX8gwC+jm5fsMPWOkeoBZSmW0JeTlFeTzL5Brql7DKsDKZAVOT5WpLg9YIRRALFu3sNkhdl2BArVu59wOiyHpge8BBCG0raFu2ZQWVg/hZTjCANGZRXAcgI+i6yAz3tpw+htwdbDnZdgLNsMQ/Qud+Z5gbU3PoQYNRPjnB0Qy/JLnpuh7nCM4giuMoui73czzxlxFuzN5yoZBAIZ7ICxXy1SA3YtgV0SH0wAo5gPKbWy5TfKW+R8bu49CHQ+Svd1FavoH74VC8cdWLOPk9ripkzz1OljZM+eMDyu9maMRVHPEsQa3RSK4l5KMINzWNK3eDaBRF4goW7ewoOp8UBleuXZycT3IDna8Wrc620PwcC23PcizlIHfohWh5yrLsICpZCNPg1UYzHE2CGzNTvMhhMf4m/imHrIrpXvzhyl9/0qtidcxk/sO6T6+EzUFFIQTHGwOTGz+oiC8k6K2EYG4h3C6WL/4KAse84PJkOx3NobxaHdra10sRr9+dqzyv3/HjL4W1yGsOGfy/pa41VIhVOuKx36xzoCD7UOS+43PR0J58IdQI3wERMogz

RNG Seed: 0

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:45 +0x10
panic({0x1395c0, 0x245a6f0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.ThunderClapAura(0xa22f500, 0x5)
	/home/runner/work/wotlk/wotlk/sim/core/debuffs.go:846 +0xe

**Comment by jimmyt857** [comment]
Thanks for the report! Raid sim isn't supported yet though, its pre-alpha. We'll start taking bug reports later.
