### ISSUE TITLE
improper gemming does not disable the meta gem and the thundering skyflare diamond has the wrong requirements.

### ISSUE THREAD

**Issue by tbullsurvey** [wowsims/wotlk#704]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment]
We're currently using 1 gem of each color as the requirement, based on https://wotlkdb.com/?item=41787.

If you think the requirement should be different, please explain what you think it should be instead, and why.

**Comment by tbullsurvey** [comment]
Should it grey out when you miss your socket requirements or does it just not work in the sim. With that particular meta its hard to tell if its not working.
________________________________

**Comment by jimmyt857** [comment]
A warning icon appears in the top-right, which says that the meta gem is disabled and also shows the meta requirements.
