### ISSUE TITLE
Crash Report 729050552

### ISSUE THREAD

**Issue by shravanshetty1** [wowsims/wotlk#714]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJzjUuBgMmDKYCxgbGBkXMHIuIGR8QAj4wVGxheMjD8YmS4wMTkJKDAZMDowRgDVdIDVCDFIHWRtYmQLyEmsTC3iYBfgknrByCUg8GECs8T5e0xKbNsOM23dycTFKbB1FbMS8yUgk1fgE1DyOFCSeSuYu+czk8SO21CugMA7oOxJIJcNyL32HyTyuJtZ4ghIBKh9PVCNsMBnoMifm8xKnECRrWDExS+wpxtFQEDgI9CkZ6shJkFENq1iljh1GyHCKdDaA3UWp8CdWVAmi8C+VcxAcncnM9Cu683MEg8WAI1eeZIJgrgYgJKzu5iVuIABxmvBGMASwaJ1golhFFAFVLFwMEow/WIU5WIBJjUmYBLjFoTIfLBXYOxi1DIyNjA1MDIwNTYwMDA2NjQ2MjY0AIoZGBqbGurqAllGRgYgJQbGjxglODZfYxJ4+5RJ4s1TJoUZV5g0ZlxlMph5lekFI9MHRvZZjAy3GBmUJjNzgi1oSHOAWiXiIDlrJgictLeEiFywV0wDg2v2Ro+ZFIIlmAZtnJc4UMOUhpNHCJjjTRV7QAASxh2HHRyhAg4JjAAwQI/d

RNG Seed: 3931210247

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 27 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xcbc20, 0xfbb190})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x24a28c0, 0xc7d4000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:84 +0x2
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_UA_Frost(0xc7bd8c0, 0x24a28c0, 0xc7d4000, 0xc7fc6f0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:134 +0x6
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:187
github.com/wowsims/wotlk/sim

**Comment by JooperGH** [comment]
This happens when you dont spec into UA. Assumes you're frost from HB.

**Comment by shravanshetty1** [comment]
Was trying blood - intentional - no sims for blood?
