### ISSUE TITLE
Crash Report 1760743719

### ISSUE THREAD

**Issue by norbert-me** [wowsims/wotlk#716]
Link:
https://wowsims.github.io/wotlk/warlock/#eJztUj1II1EQ3m+yyW3WU54/xVMQ4haHCMLLhgWtsloJNoKNpRZnIRbhuOK0ilEv3iXaiIiioGAhaJHKwh8QTaEIhyh4nNp43oGNILaiOJuNtU0KCz8ej5lvZr7ZnTdmvUGCFLWgAz1IUBLIgXaBY+AGaC83ECEFFwmsAlVaXT6YQqhrsG/o8xcDwqi7hCnESpZk+h+s0HqGfj/A1MVChpj/dQ95dsU8k7lZMsvFXobkU4qsQJ7TqsU2F+5vwQqzuzRDHlkhxiZJfs/B0rlEMyvFKifdXcL6wD5naKYpbiepGK4W4yx5suNr5F/6jE2RvJrmPp5riE2WmMiBrY2Mb+ni+tG7H7NefInjywV2lD88LNayfqnF/6/QFewJfgOPpumAtHeUBMMGrw9JSmBAmh+FLnnPGnnWLcRLFuJYUOInPjXbKsYnpqIq5qio7bAVc2zvijY7jvLg2H8hjT//SSymA/LiiCKpU2p8OiE1cko30O9QNg/tR/HpWt1zaNZ0IFzwkv1upc/XuLXzcx4O460+cxxv6C/gLG5fU6Rb0pt9/69uKVSSh/lXdDpL0seDP+OJfbetSLi9eAaIAYMI

RNG Seed: 239694426

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xcbbc0, 0xfbb170})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0xa334000, 0x24a36c0)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:99 +0x46
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0xa334000, 0x24a36c0)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:25 +0x2
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x24a36c0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:325 +0xe
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x24a36c0)
	/home/runner/work/wotlk

**Comment by Glandaaalf** [comment]
Can't reproduce, must have been fixed since then.
