### ISSUE TITLE
Howling Blast coefficient

### ISSUE THREAD

**Issue by viliustank** [wowsims/wotlk#719]
**Describe the bug**
Howling Blast AP coefficient is 0.1 in the code but should be 0.2

**To Reproduce**
I detailed this and other ability tests in #beta-findings on the discord but in short, make a talent spec that reaches HB with no modifiers, cast naked and in full gear noting the APs, coeff = (dmgGeared - dmgNaked) / (APgeared - APnaked), modulo dmg range.  I verified it's still the same on build 45189

**Expected behavior**
AP coeff 0.2 instead of 0.1

**Comment by JooperGH** [comment]
Fixed.
