### ISSUE TITLE
Crash Report -476715443

### ISSUE THREAD

**Issue by Wanderriett** [wowsims/wotlk#730]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUjFIG2EUvu/dGc+jkd9Mf5XCmUkEy587AnbK2anFReri2IAGwZZKcVAn6VTiENzUoQhdCkUodUnSKEILNpMBNYIWEcE0RQVH66LvT+xqHRwcfPz34L3v+97HPZ7zyCZFwxjFFPAJ+AKUgCpwBioRPRUuKQQYYML7GiFitH5seIdQ36vkxNBbu0E4rQU4QlS2Sa7vUTSU/U7lC3KaxNkvipqFLDlhcVIgubZ3Vdpi4xvJ7C5pFQPFXVZ9KJLGmkWasR/csbg0uK4yY3vRjFoVXT8Q5XydzY/1x4xWPnOH2fXZmWWS1UXTscSfJeI8ndN5Na/z0bpmrLLD/oLpGNzJ8LQIbyDcjT5rwBrXW+D/7PxJxn3cSkxaNiSdo82xbQhIPiY+oXBLHT1NSLhIo9PzVVx5Ku4rpXxf+Z4fU/qL+fFYVxejnqc0RfkHkPbvQxJLZZInh+TOblLH7BapuS2qwjpF4zyMHRjRBbOpZjGVCh7Oz+koJp7UXUuJ9lQtygnvL43mvmKyuX84OTjkvkm5PSPJ10n3uQzd2SMYC25ljLXynzm91+LuzOOem1rV9u6+2Aj+KYJneIlLYxmGog==

RNG Seed: 1289102579

Trying to cast {SpellID: 49895} but GCD on cooldown for 1.32535185s, curTime = 1m21.6507037s
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xac580, 0xc416aa0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func1(0x24a3ce0, 0xbdd4a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:209 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x24a3ce0, 0xbdd4a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:197 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncResources.func5(0x24a3ce0, 0xbdd4a00)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:179 +0x17
github.com/wowsims/wotlk/sim

**Comment by JooperGH** [comment]
Hey. The blood dps stuff is not working yet. No real point testing it even.

**Comment by rosenrusinov** [comment]
This should be fixed now from #590
