### ISSUE TITLE
Crash Report 1152195933

### ISSUE THREAD

**Issue by vampiratic** [wowsims/wotlk#742]
Link:
https://wowsims.github.io/wotlk/warlock/#eJztUj1IQlEUfuc8tecj4xYNtyCwN4QEwfXJA5t8NQUtQUtjDTlEg0RLTebSz9LQlCA0tgTREFFhUUn/FApKGg2V9KYwojU6V91bHBr6eBy+n3PPg3Ov3qUhQ4FhGIIxiGEcYBvwGOAewAEY9GngRwE2xGAToE3pTLkT4BmZnpibnNGAaZ37oDNWPkB++4SGJ3OCn3uoe9nXIxpqkaiPORReUaimq7JcQF7cUWspY2+U3lGzh1J5tIU51JAtoeEiRyH9Sh2FLbWuvezjsD5LY5VD5ImMZO/EnC1Vd7G7A6S6mpa1UuVH+7Ljhsacl6TO78q6sYuGpoGAEfeYu/cClX80BPO0VIYcYzDF9Wbm4vSAArTmMNLr8VBGzgr09JkiRF9IBEXIEkHTIhayTFmCfZYlJCzzGbj2UEaWWlR56Rr9iRwGvrMoFnLogKsCTUlQlutX128XQTHWVG9VxaN2a81vtzuS6xKXkf6acx/pjlaRj5gv6B/l+Gfvf9ZuxJT45dkvc4Yb8h+J2o6XTu2BumGPww+ddXqC

RNG Seed: 2878500287

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xd0680, 0x1008530})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).tryUseGCD(0xa236000, 0x24a35e0)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:99 +0x46
github.com/wowsims/wotlk/sim/warlock.(*Warlock).OnGCDReady(0xa236000, 0x24a35e0)
	/home/runner/work/wotlk/wotlk/sim/warlock/rotations.go:25 +0x2
github.com/wowsims/wotlk/sim/core.(*Character).initialize.func1(0x24a35e0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:325 +0xe
github.com/wowsims/wotlk/sim/core.(*Simulation).runOnce(0x24a35e0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:298 +0x14
github.com/wowsims/wotlk/sim

**Comment by Glandaaalf** [comment]
Can't reproduce, must have been fixed since then.
