### ISSUE TITLE
Crit Chance for Feral Druid look overstated.  Perhaps the critical chance from gear is the root to what is causing the overstatement.  In P2 Ulduar gear, it shows over 100% crit chance (with raid buffs). 

### ISSUE THREAD

**Issue by kpoundz** [wowsims/wotlk#743]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jarveson** [comment]
should be all set now after a lot of feral fixes that have happened. things were a bit wonky still from tbc initially
