### ISSUE TITLE
Power infusion Cooldown

### ISSUE THREAD

**Issue by beckzudian** [wowsims/wotlk#747]
**Describe the bug**
Power Infusion (discipline priest tier7 talent) does not use the WOTLK cooldown of 2 minutes (tested in Shadow Priest and Smite Priest Sim the casts are 3 min apart even when selecting cooldowns manually).
Also the cd is not affected by the cd reduction when speccing into Aspiration (discipline priest tier8 talent)

**To Reproduce**
Run any Sim with Power Infustion active.
go to detailed results > timeline > DPS and verify cd usage

**Expected behavior**
Power Infusion should be up every 2 minutes (or less when speccing into aspiration)

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Win10
 - Browser Firefox
 - Version 103.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by jimmyt857** [comment]
This was fixed a few hours ago. Thanks!
