### ISSUE TITLE
Agility gives too much melee crit rate

### ISSUE THREAD

**Issue by Algelius** [wowsims/wotlk#766]
**Describe the bug**
Melee Crit Rate contribution from Agility seems to be far higher than it should be (Warrior). 

**To Reproduce**
1. Simply add agility and see the melee crit rate increase.

**Expected behavior**
Warrior should be getting 1% crit per 62.5 agility.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Win10Pro
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by telia-martin** [comment]
looks to be the tbc conversion (30Agi=>1%crit)
