### ISSUE TITLE
json import failed

### ISSUE THREAD

**Issue by shama82** [wowsims/wotlk#767]
**Describe the bug**
Importing .json file from 80upgrades doesn't work.
Import error: Error: Found unknown field while reading proto.IndividualSimSettings from JSON format. JSON key: name

copy from clipboard works with the same data.

JSON file 
{
    "name": "Phase 1 BIS RAID 10",
    "phase": 1,
    "links": {
        "set": "https://eightyupgrades.com/set/2RESwQDmVfYRDRETovqe5E",
        "talents": "https://eightyupgrades.com/talents/rogue/0CFDIJKMLp4QpSUVXWZ6A2AC1CFi3?g=0Btr"
    },
    "character": {
        "name": "Shamrog WOTLK 80",
        "level": 80,
        "gameClass": "ROGUE",
        "race": "BLOODELF",
        "faction": "HORDE"
    },
    "items": [
        {
            "name": "Heroes' Bonescythe Helmet",
            "id": 39561,
            "enchant": {
                "name": "Arcanum of Torment",
                "id": 3817,
                "itemId": 50367
            },
            "gems": [
                {
                    "name": "Relentless Earthsiege Diamond",
                    "id": 41398
                },
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                }
            ],
            "slot": "HEAD"
        },
        {
            "name": "Collar of Dissolution",
            "id": 39146,
            "slot": "NECK"
        },
        {
            "name": "Heroes' Bonescythe Pauldrons",
            "id": 39565,
            "enchant": {
                "name": "Greater Inscription of the Axe",
                "id": 3808,
                "itemId": 50335
            },
            "gems": [
                {
                    "name": "Bright Dragon's Eye",
                    "id": 36766
                }
            ],
            "slot": "SHOULDERS"
        },
        {
            "name": "Tunic of Dislocation",
            "id": 39386,
            "enchant": {
                "name": "Enchant Chest - Powerful Stats",
                "id": 3832,
                "spellId": 60692
            },
            "gems": [
                {
                    "name": "Bright Dragon's Eye",
                    "id": 36766
                },
                {
                    "name": "Balanced Twilight Opal",
                    "id": 40029
                }
            ],
            "slot": "CHEST"
        },
        {
            "name": "Jorach's Crocolisk Skin Belt",
            "id": 40694,
            "enchant": {
                "name": "Frag Belt",
                "id": 3601,
                "spellId": 54793
            },
            "gems": [
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                },
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                }
            ],
            "slot": "WAIST"
        },
        {
            "name": "Heroes' Bonescythe Legplates",
            "id": 39564,
            "enchant": {
                "name": "Icescale Leg Armor",
                "id": 3823,
                "itemId": 38374
            },
            "gems": [
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                },
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                }
            ],
            "slot": "LEGS"
        },
        {
            "name": "Boots of the Neverending Path",
            "id": 44297,
            "enchant": {
                "name": "Nitro Boosts",
                "id": 3606,
                "itemId": 41118
            },
            "slot": "FEET"
        },
        {
            "name": "Bindings of the Tunneler",
            "id": 37183,
            "enchant": {
                "name": "Enchant Bracers - Greater Assault",
                "id": 3845,
                "spellId": 44575
            },
            "slot": "WRISTS"
        },
        {
            "name": "Heroes' Bonescythe Gauntlets",
            "id": 39560,
            "enchant": {
                "name": "Hyperspeed Accelerators",
                "id": 3604,
                "spellId": 54999
            },
            "gems": [
                {
                    "name": "Bright Scarlet Ruby",
                    "id": 39999
                }
            ],
            "slot": "HANDS"
        },
        {
            "name": "Surge Needle Ring",
            "id": 40474,
            "slot": "FINGER_1"
        },
        {
            "name": "Hemorrhaging Circle",
            "id": 37642,
            "slot": "FINGER_2"
        },
        {
            "name": "Coren's Chromium Coaster",
            "id": 49074,
            "slot": "TRINKET_1"
        },
        {
            "name": "Figurine - Twilight Serpent",
            "id": 42395,
            "gems": [
                {
                    "name": "Bright Dragon's Eye",
                    "id": 36766
                },
                {
                    "name": "Rigid Autumn's Glow",
                    "id": 40014
                }
            ],
            "slot": "TRINKET_2"
        },
        {
            "name": "Cloak of Mastery",
            "id": 39404,
            "enchant": {
                "name": "Flexweave Underlay",
                "id": 3605,
                "itemId": 41111
            },
            "slot": "BACK"
        },
        {
            "name": "Omen of Ruin",
            "id": 39427,
            "enchant": {
                "name": "Enchant Weapon - Berserking",
                "id": 3789,
                "spellId": 59621
            },
            "slot": "MAIN_HAND"
        },
        {
            "name": "Anarchy",
            "id": 39420,
            "enchant": {
                "name": "Enchant Weapon - Berserking",
                "id": 3789,
                "spellId": 59621
            },
            "slot": "OFF_HAND"
        },
        {
            "name": "Accursed Bow of the Elite",
            "id": 39296,
            "slot": "RANGED"
        }
    ],
    "consumables": [],
    "buffs": [],
    "talents": [
        {
            "name": "Precision",
            "id": 181,
            "rank": 5,
            "spellId": 13845
        },
        {
            "name": "Close Quarters Combat",
            "id": 182,
            "rank": 3,
            "spellId": 13805
        },
        {
            "name": "Dual Wield Specialization",
            "id": 221,
            "rank": 5,
            "spellId": 13852
        },
        {
            "name": "Opportunity",
            "id": 261,
            "rank": 2,
            "spellId": 14072
        },
        {
            "name": "Improved Poisons",
            "id": 268,
            "rank": 5,
            "spellId": 14117
        },
        {
            "name": "Lethality",
            "id": 269,
            "rank": 5,
            "spellId": 14137
        },
        {
            "name": "Malice",
            "id": 270,
            "rank": 5,
            "spellId": 14142
        },
        {
            "name": "Ruthlessness",
            "id": 273,
            "rank": 3,
            "spellId": 14161
        },
        {
            "name": "Murder",
            "id": 274,
            "rank": 2,
            "spellId": 14159
        },
        {
            "name": "Puncturing Wounds",
            "id": 277,
            "rank": 3,
            "spellId": 13866
        },
        {
            "name": "Cold Blood",
            "id": 280,
            "rank": 1,
            "spellId": 14177
        },
        {
            "name": "Overkill",
            "id": 281,
            "rank": 1,
            "spellId": 58426
        },
        {
            "name": "Seal Fate",
            "id": 283,
            "rank": 5,
            "spellId": 14195
        },
        {
            "name": "Vile Poisons",
            "id": 682,
            "rank": 3,
            "spellId": 16515
        },
        {
            "name": "Master Poisoner",
            "id": 1715,
            "rank": 3,
            "spellId": 58410
        },
        {
            "name": "Find Weakness",
            "id": 1718,
            "rank": 3,
            "spellId": 31236
        },
        {
            "name": "Mutilate",
            "id": 1719,
            "rank": 1,
            "spellId": 1329
        },
        {
            "name": "Fleet Footed",
            "id": 1721,
            "rank": 2,
            "spellId": 31209
        },
        {
            "name": "Focused Attacks",
            "id": 2069,
            "rank": 3,
            "spellId": 51636
        },
        {
            "name": "Cut to the Chase",
            "id": 2070,
            "rank": 5,
            "spellId": 51669
        },
        {
            "name": "Hunger For Blood",
            "id": 2071,
            "rank": 1,
            "spellId": 51662
        },
        {
            "name": "Relentless Strikes",
            "id": 2244,
            "rank": 5,
            "spellId": 58425
        }
    ],
    "glyphs": [
        {
            "name": "Glyph of Tricks of the Trade",
            "id": 45767,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Mutilate",
            "id": 45768,
            "type": "MAJOR"
        },
        {
            "name": "Glyph of Hunger for Blood",
            "id": 45761,
            "type": "MAJOR"
        }
    ],
    "points": [
        {
            "name": "Assassination",
            "stats": {
                "attackPower": 1,
                "agility": 2.3,
                "strength": 1.1,
                "armorPenRating": 1.5,
                "critRating": 1.5,
                "hasteRating": 1.8,
                "hitRating": 2,
                "expertiseRating": 2,
                "dps": 8,
                "metaSockets": 100,
                "redSockets": 36.8,
                "yellowSockets": 36.8,
                "blueSockets": 36.8,
                "prismaticSockets": 36.8
            }
        }
    ],
    "stats": {
        "agility": 951,
        "arcaneResist": 5,
        "armor": 5288,
        "armorPen": 3.14,
        "armorPenRating": 44,
        "attackPower": 3398,
        "crit": 28.96,
        "critRating": 452,
        "defense": 400,
        "dodge": 21.94,
        "expertise": 26,
        "expertiseRating": 216,
        "fireResist": 5,
        "frostResist": 5,
        "haste": 4.51,
        "hasteRating": 148,
        "health": 16854,
        "hit": 14.61,
        "hitRating": 315,
        "intellect": 57,
        "mainHandSpeed": 1.5,
        "mana": 575,
        "natureResist": 5,
        "offHandSpeed": 1.8,
        "parry": 5,
        "rangedAttackPower": 4279,
        "rangedCrit": 28.96,
        "rangedCritRating": 452,
        "rangedHit": 14.61,
        "rangedHitRating": 315,
        "shadowResist": 5,
        "spellCrit": 9.85,
        "spellHaste": 4.51,
        "spellHit": 17.01,
        "spirit": 76,
        "stamina": 943,
        "strength": 120
    },
    "exportOptions": {
        "buffs": true,
        "talents": true
    }
}

**Comment by shama82** [comment]
another thing is talents are not copied fully (some points missing after copy)

**Comment by jimmyt857** [comment]
When importing from 80U, you need to use the 80U import option instead of the JSON option!
