### ISSUE TITLE
Crash Report 259158363

### ISSUE THREAD

**Issue by telias82** [wowsims/wotlk#773]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUjlIA0EU3f83ht1FcTyKMVXcRhEC44aAVlltbQQbSy0MFhYiFmoVIkIUT2xiQBsbLQTRwqMTFY8ipDCJV+EVEUFMISaoiH83WtuksPAxDG/evHl/+DOaS0GB3dALQYAlgDjAA0AOMI7YzNwowIR22g3bu+WSa6EoBM7Wns7Brj6liGmufdAYWxtHPnoHunPzFHfeQVPZ8CjqskUVtv0J/PnaYrk95NkzWatgG5PILxdRV8lC45CMJWyTjCOrkD9XwY4pNLUi257XkJ1byuKPoKtkj9nnqPTHNPKreyq986Nkp5BnLtBWrGAH2xpHmlMvFl+asPgyzQo7mEEeS8uapEl6MfVBbcBWud0xAHWHKP2jIBhyKsDRDW9QTH0Hbv0hWo5BjRA+r8crfB7hNQyvIFZvCEP4DEMIm5FG4g1w5SmNLHqCfD2J7sgJ1kYSKOYS+ACODGAUFM1J2fNbeA6SPiurduFgwCzLX6HSrIrOWTjyN+aVuL86YCPpN27R3cbxz754v1mIlODR3i85LQWpYyHf4/Cu2fQtmB3wBZglhUg=

RNG Seed: 1477221133

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xd24e0, 0x103a690})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*RuneSpell).Cast(0x0, 0x24a37a0, 0xa30d500)
	/home/runner/work/wotlk/wotlk/sim/deathknight/runespell.go:89 +0x2
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_UA_Frost(0xa3f8780, 0x24a37a0, 0xa30d500, 0xa3d7e90)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:129 +0x6
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(0xa3d7e90, 0x24a37a0, 0xa30d500, 0xb208000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:218 +0x13
github.com/wowsims/wotlk

**Comment by JooperGH** [comment]
Fixed.
