### ISSUE TITLE
Flametongue Weapon

### ISSUE THREAD

**Issue by MaxxSrini** [wowsims/wotlk#794]
**Describe the bug**
when swapping from Wf(mh), FT(oh) to FT(mh), FT(oh) while wearing two 2.6 speed weapons on a 180 sec fight changes the total flametongue procs from 172 to 216. It seems like the sim believes that there is an icd on flametongue weapon. On the beta currently there is no such icd.

**To Reproduce**

**Expected behavior**
i would expect the number of flametongue procs to nearly double.

**Sim Links and Screenshots**
(https://wowsims.github.io/wotlk/enhancement_shaman/#eJzFUjFoFEEU3fd3vZubmDCkkDWFrtsYRGX3lgO1udVKsAnYpIyFqayCRbQ60picXay8KmmCkAStwpmcJnALZjVqUIiYRIUI5xUW1whiE//MxjqFB3kD/w//vf/+MHx5WlBAl3AdIxhHBZjBbs8z0BqwCbSBa/0CHgtiDGeCJ0C/NdA6NoHc0J1b926PibzKDzQhlfrWIPf9V/JzCw9pISVZUL92ybff1Un2qg0mXzFpb+2TFOrjCrnbizZ3vWEi3eGuvbrp6lEzL8lNuAJL9ql1pj8t2r7DNhZbflhij1W2VOo1U6157vxTp7lUD3nKrm0Wm5mOqjV0rD7X8ecLHb98NsOXyN3Y0bffaXZz1MQK+b38GRhyhp1xTALn1sk6EnRWu+Pjxd3x+X/cLwgocon3Zxrn5SmZU7YLj8+gHRrF2lh8OdNejHm/hCDND1IVZ4NSFERBWCpeCIISn2IUcgzCKOJ6GEahKYR7OC6aCalGQu5yQm04HeRruCJz0hGzD8jkt9O2yT86vLCyT0yd8Pb/AZpRj5YzZWve3oblV+2CeVVlND5Ze6yRlg8eulk+M2qwVS5+J++mS0e2MYfhbtwNl0qaHOJzoytzNLI/nmzGVw8K8Qj+Aop1kT8=)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version Version 104.0.5112.102 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Wumblesnarf** [comment]
when this was last tested, flametongue did in fact have an ICD on it, albeit a very very small one. the sim behaviour is done to match the in-game behaviour, if it has changed i will change it in the sim but i have seen no evidence that it doesnt work that way on beta (it works like that on live tbc as well)

**Comment by Wumblesnarf** [comment]
it seems the beta is more forgiving with auto attacks now but stormstrike still only procs once with the same rank, and some autos will as well

**Comment by Wumblesnarf** [comment]
after a bit of extra testing on the beta, i can confirm that the sim does in fact work the same way as the beta, with flametongue having a very tiny (likely 1ms) icd, only preventing multiple procs from the same rank at the exact same moment (which is why rank 9 is implemented in the sim)
