### ISSUE TITLE
Glyph of Rending not working in rotation

### ISSUE THREAD

**Issue by ambiwar** [wowsims/wotlk#823]
**Describe the bug**
Rend duration is not being extended by Glyph of Rending

**To Reproduce**
1. Equip glyph of rending
2. sim DPS
3. View results timeline
4. Rend is cast every 15 seconds

**Expected behavior**
Rend should be cast every 21 seconds with glyph of rending.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Comment by TheGroxEmpire** [comment]
Thanks for the report, this has been fixed in ``3bdf2139``.
