### ISSUE TITLE
[Warlock]Molten Core / Conflag /Incinerate Problems

### ISSUE THREAD

**Issue by ugurkc** [wowsims/wotlk#838]
**Describe the bug**

- When a Molten Core procs mid Incinerate cast, even though that incinerate doesn't benefit from Molten Core's speed and damage buffs, it consumes a stack.
- Conflag is cast before an Immolate is up on the target, which shouldn't be possible.
- Incinerate's damage numbers seem off, seeing they fluctuate  between 2k and 4k non crit damage, might not be a bug but an oddity, requires an investigation.
-New Rotation still sometimes drops Haunt, possibly dropping SE's.

<img width="1117" alt="Screen Shot 2022-08-25 at 13 30 20" src="https://user-images.githubusercontent.com/32737088/186642594-7577a91c-849e-48bd-aff3-371fdff6e3ae.png">
<img width="1117" alt="Screen Shot 2022-08-25 at 13 30 46" src="https://user-images.githubusercontent.com/32737088/186642751-510f9aef-f2ca-4c64-933b-b6f4cc961bbc.png">
<img width="1117" alt="Screen Shot 2022-08-25 at 13 16 36" src="https://user-images.githubusercontent.com/32737088/186642865-7170b4d1-e7a4-4275-96c6-5f0239f7db67.png">

**Comment by Tharre** [comment]
> When a Molten Core procs mid Incinerate cast, even though that incinerate doesn't benefit from Molten Core's speed and damage buffs, it consumes a stack.

Incinerate not benefiting from the haste but still consuming a charge is not a bug, that's how it works in-game too. And it should get a damage increase, or do you have any examples where it doesn't?

**Comment by jimmyt857** [comment]
No response from OP, closing.
