### ISSUE TITLE
[PET] Wolverine Bite does not appear in the dps ?

### ISSUE THREAD

**Issue by Francoporto** [wowsims/wotlk#848]
Cannot see the spell Wolverine Bite in the detailed result, also no icone

1. Go to Hunter Simlator
2. Click on 'Talents'
3. Change Player talent to Pet
4. Click on the Wolverine Bite talent
5. Check result

**Expected behavior**
We normaly have to see the spell and the damage in the detailed result, display bug or the spell isn't in the sim ?

Also, i think it's the same with :

https://www.wowhead.com/wotlk/spell=53512/feeding-frenzy
https://www.wowhead.com/wotlk/spell=53517/roar-of-recovery

**Comment by jimmyt857** [comment]
Fixed by #1144
