### ISSUE TITLE
Bladestorm pauses auto-attacks

### ISSUE THREAD

**Issue by ambiwar** [wowsims/wotlk#853]
**Describe the bug**
For the duration of bladestorm, there are no auto-attacks

**To Reproduce**
1. sim arms dps
2. go to timeline
3. find bladestorm
4. no auto attacks for duration of bladestorm

**Expected behavior**
Auto attacks should continue during bladestorm.

**Sim Links and Screenshots**
![image](https://user-images.githubusercontent.com/111925369/186775999-8c06d8fd-4d2e-4d03-a0f0-b14f72615229.png)

**Comment by jimmyt857** [comment]
This should be fixed now!
