### ISSUE TITLE
wastewalker shoulderpads socket bonus does not calc correctly

### ISSUE THREAD

**Issue by galhast** [wowsims/wotlk#870]
I was testing for prepatch, with a bunch of 70 gear. I put on the wastewalker shoulderpads (replacing a higher ilvl item) and got a dps upgrade, which was suprising. I already had 2 pieces of the wastewalker set equipped, and putting on a third shouldn't have made a big different (there is no 3 set bonus). 
On further investigation, the huge dps increase (about 40, when I was expecting a -10 or -20 decrease) was from having a socket bonus. The socket bonus itself was only meant to be +3 crit strike rating. 

1. To test, I put in the wastewalker shoulderpads. 
2. I took out the gems. And saw a baseline dps: 
![1](https://user-images.githubusercontent.com/11327853/186858847-f7be0e0c-75d4-40c1-b7a3-5c3f982928c6.PNG)

3. I put in correct coloured gems, but with no offensive stats. Got 40+ dps increase from only the +3 crit bonus.
![2](https://user-images.githubusercontent.com/11327853/186858940-4b4e51f2-24d5-4589-bfc1-69c9eb35dc76.PNG)

Expected result: Would have seen a very small increase in dps (+2). Actual result: Saw 47 dps increase.

Additionally I tested with two crit gems (+20 crit strike rating total). This did not satisfy the gem bonus condition, but should have given a much larger amount of crit than the gem bonus provides (20 > 3). But lost DPS instead.
![3](https://user-images.githubusercontent.com/11327853/186859997-ab3de20a-7b05-4b62-a967-bfdce8313615.PNG)

Using up to date chrome browser in win 10.

Settings and talents:
![4](https://user-images.githubusercontent.com/11327853/186860381-fdf89978-1a81-4904-98bd-4662a43d2d5c.PNG)
![5](https://user-images.githubusercontent.com/11327853/186860401-747c62c6-a049-4ec6-8734-3a021de96c2a.PNG)

**Comment by jimmyt857** [comment]
This bug was fixed a few days ago, we weren't properly scraping set bonus names so there were cases of TBC items granting bonuses from WOTLK sets. Going to close this but feel free to reopen if you encounter this again.
