### ISSUE TITLE
Ret Sim Talents (damage modifiers) Bugs

### ISSUE THREAD

**Issue by rettest** [wowsims/wotlk#878]
**Two-Handed weapon specialization**
Holy Vengeance (DoT)
**should not** benefit from the Two-Handed Weapon Specialization talent (+6% dmg) - it does at the moment.

**Sanctified Retribution**
Holy Vengeance (DoT)
**should benefit** from the Sanctified Retribution talent (or equivalent aura +3% dmg) - does not at the moment.

**Vengeance**
Holy Vengeance (DoT)
**should benefit** from the Vengeance talent (+3-9% dmg) - does not at the moment.

**Crusade**
vs none/mechanical etc
is NOT working properly (gives +0% dmg)
vs undead/demon/humanoid/elemental
is NOT working properly (gives only +3% dmg)
Talent is just in TBC version, needs to be updated to the WOTLK version.

**The Art of War**
Judgement of Vengeance
**should benefit** from The Art of War talent (+5/10% dmg) - does not at the moment.

**Comment by TheSorm** [comment]
Hey tanks for your contribution! :)

Crusade Talent and The Art of War will get fixed soon!

Do you have any data or tests from beta/ptr for the "Two-Handed weapon specialization", "Sanctified Retribution", "Vengeance"?
Sounds all reasonable but having some tests/data would be perfect so it will be actually correct than! :)

**Comment by TheSorm** [comment]
Thanks a lot for your help, i tested everything and we are working on the fix :)
