### ISSUE TITLE
Crash Report 3922089

### ISSUE THREAD

**Issue by Zykiemoo** [wowsims/wotlk#883]
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztUj0sQ1EUfue853m9KbkVw8Wg3iSkyX19OrD0sVqaWIwMxGAQsTA1psbgd6GJNBGDRKzip7HU4CehQ9sIAyFNahBSETbO0wqbpYPBN5zc853vO+fk3suaDeQocQTGIAqwAZAGKAC8AaYRowg9TRwE+EGCQ5JYWYI3gG8AXUqd0hivmgY9Mjo4OTRuVHPWmALG+UsSxfuCZurrKUwkkGk8tY+shi9vo1i9RlM92kFm8OQeisstlXn5YxJNncgc8bW8SPw8yTRiFMqfqV28qJZzLz/fLqndLpy/UjW/+c0Y/J78p1fu2NkDN27uIrkSF6ShbdyFvDx/8tOR20dxlleZQuq5PTQNQ5M1EbVfbTtC5R8VwZRugEA/TKPO3J+jzEB7wJZBGbJD0u6ggy2toC2ltG1LWnbICgTdMtEhCrcgjIc88rUMisUM+pez2DqXQbmSxQJoT+CJg8c3/IlceAfgEhRzSfV8jo4OO77SEvVOQ3zFxXG4s8Skwy1fruAd+vsE/tk3n3Aq0SV6fPhLn96KzHFRuuNYyukuE84AfACYx4P7

RNG Seed: 3166346543

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:55 +0x10
panic({0xd8120, 0x10e91a0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight/tank.(*TankDeathknight).RotationActionCallback_TankBlood_PrioRotation(0x987a400, 0x24a2c40, 0x9292a00, 0x984e9c0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/tank/rotation_blood_tank_default.go:37 +0x21
github.com/wowsims/wotlk/sim/deathknight.(*Sequence).DoAction(...)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:206
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).DoRotation(0x981a000, 0x24a2c40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/rotation.go:235 +0x13
github.com/wowsims/wotlk/sim

**Comment by jimmyt857** [comment]
This sim isn't ready for use yet!
