### ISSUE TITLE
Missing Icons for Flasks/Potions and some other items

### ISSUE THREAD

**Issue by Rignorock** [wowsims/wotlk#893]
**Describe the bug**
Icons are missing from a number of the right hand options and from the cool downs menu, specifically for the haste potions and saronite bombs.  There's also no option to swap to a more tank oriented flask or mix and match elixirs while on the DK's sim.

**To Reproduce**
Icons were missing on load.  Not much in the way of reproducing said issue.

**Expected behavior**
Icons and optional icons should be showing when hovering over the square or when an item is selected.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
Firefox (Most current version as of 8/27) on Windows 11 OS (Most current updates as of same date)

**Additional context**

**Comment by rosenrusinov** [comment]
This should be fixed now. Pls re-open if you find more missing icons
