### ISSUE TITLE
Darkmoon card Greatness  :  wrong stat

### ISSUE THREAD

**Issue by shama82** [wowsims/wotlk#900]
the card is configured with 90 strength instead of 90 agility for rogue
when i select it in a trinket slot, i see clearly an upgrade in my strength stat, but not in my agility stat
![darkmoon_card_greatness](https://user-images.githubusercontent.com/111847137/187046676-f896d81d-1284-44da-bde1-6897eeb59052.png)

**Comment by rosenrusinov** [comment]
There are 4 different cards with all the stat types. You just need to select the correct one. Not a bug
