### ISSUE TITLE
UI bug: Wrists slot having more gem than gem socket that is available

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/wotlk#929]
![image](https://user-images.githubusercontent.com/47816228/187172649-4794e720-2b90-4e27-b672-0455731d46fb.png)

Sim setting link: https://wowsims.github.io/wotlk/warrior/#eJztUk0oRFEYfd/3hnnzJJcsnlmNt5LCffc2C6u57KREVnYsyMJCssBqIiUlyoYpsSTZIob8FVN+hlfkd0FpysbSRnxv3ljbzMLCWdzuPefcc7q3zwwbyLEX+jEOsAyQBsgAfACmERtLIqigHyYAZrJimRbeKBiFwta+ruHuASPIQuEdMBlLJ9G6eEK7cP0QV1JohtjHA9r6wSaaxeyKxGMS9Vc6GszdRutuTadbZySk7ukW+TwrY5OkHeWYJDFF7JE8N2u6DRqFfm5RipfP2CXxr6vkpOP5mZc7vYNWhnJD7PYm1x1gU7ve+nbhrXtbnm2PKk7v0dSI2d9Gu4ieX9waGKJHYvUJav/IC0aCBli4BDAQNesYRKDB55tUk79pUW0/TIe/qVU0hRDPTpk2CVWSC8Gl4EJKGXU4d7jgjhCOFNIRUadG8mgNGeQzWMaii2zBRWvOxciYi1XJL+TjLmYg8A7BBGh3oNmzeijbE+9RpX5juapIzHtIxep9Jh2r7MniOiZeMNJu/d2ZGFT5SImnjn7Jac5Ljwf/jycOVW4WNNUJ3/2ZgCc=

**Comment by jimmyt857** [comment]
This looks like a visual bug, with the blacksmithing gem slot showing when it shouldn't (because BS isn't selected).
