### ISSUE TITLE
Feature Request: Put % in armor pen and expertise stats

### ISSUE THREAD

**Issue by TheGroxEmpire** [wowsims/wotlk#947]
**Is your feature request related to a problem? Please describe.**
Easier way to know reducible armor pen that is left and dodge reduction that the expertise gives.

**Describe the solution you'd like**
Showing the amount of reduced reducible armor pen and dodge by percentage.

**Additional context**
Current UI without percentage on these stats:
![image](https://user-images.githubusercontent.com/47816228/187359569-420366ad-dcf4-493e-878a-abdfda81f7f2.png)

**Comment by Beannaa** [comment]
If the expertise converted to percentage could also include points in the talent Weapon Mastery (1/2% dodge reduction), that would be awesome.
