### ISSUE TITLE
Crash Report -941815796

### ISSUE THREAD

**Issue by Kopernian** [wowsims/wotlk#971]
Link:
https://wowsims.github.io/wotlk/raid/#eJztm21wVNUZx+85ezfc3CR4jJRe1057TVvZ0m57967bQmdsNkgd1NqJMK20M50aIUhaSOgSquZTjG8QRB0dkRcxVGm1iopA02R3kwAJ8hKSYALBgCaALOLISxA7Y1OVPs859+4bm8hM17Ef9iS7e+45596b2f3t//yf55yoDy9Qt1+jdjnrSH5psKpaLy1bUDa3olJxMtk1QFTGHn2PaHUnSFHOsTB5aS9RZXZiENsfg/Zzx0Q7/KoKe3aAaJ/WUfUqVg99/zhMinJFH3aPZ/2DRHtoEymS4VBSr2Qn4Xj4HVI0ToyQ1AK2cijh8CrWNUS0oyeTLqOwN84R7dhTFGpDJ4i2dBO2PXBU1GQ2PIjPz4awte4Y0dZCawFbDbURuJUDLyGzfVH4s5VxxoTS/Mm7qZQtGSk10l7iVnWFFH5Dpco4eCjwyIEHgQeFhwMezkLJRTVHPXF7DL9h+L0+v2n4vIbpM70+KF7TZ3g9fjjGTsMwfMeJprzbT9mj26n2RpTqp3qp+/1eakR76SkiD5Nxa0julfN46S9uIuQwsDMQ4/mOsmCwoioIPOe6diK3xyNU6x6kRTkb2unxJgo4tIcpMLKqkWrrhmiRY3cTwhUJUe3wqw444SicsOcInAAd2JfHDsDQJ2Ao3Gg8Owbdaz5yFMn9F6kEw3ugc9lGBx/e0ICXWtFCtegrWPsALtp5BO+5OYzPj7Xi8/YQVfNZw9twCzhhdTOO7A1TrYGzvR9qS4eomsv2b4e/DkYUXcFkzWkUlDpmO+4lSwnJQpyxUiO9TG5QfS63hSyi67RwzrGQRoxleOTCQ71WnPezAHAt69RN6slk04/cGsCwx2eYwLnP5/eavNXwmn7TC51eoN30Itt/6aPsWJRqz/RR/aE+6n6kjxqRi6Oz/U9kuyS4cHES2y3I9n5gsQfZbmynkSZk5pN3gBmsFrBe6NwFnY4RDnhf2Aa8ywb8uT0UfqGlHvo6sAXOjHDk34Uxh151IPK57LMQXEWMfAvaT74iRsIXAK77ONB+Cq6bywYOWfeW2QoO+oc9+LwthMO2wS32wVdBwi9AmBYpChVEZ2HOWKmRglPVHzHyBCFuUiLafhm4WVRuDvxGVH4YKBOV4eL55F6CHDOiUVBogBe02QSOEWBg1zCBX9BpE2Ta7wW4/R4YwBW6AShe10e1VUDxA0AxEGwAzTbFEpL7GpCr3BSsWlytT78VqFVdHUjtyUNxaru7Uqg9Y1MbiVHbdATJO5lALfaNj1ErwyEq8ymLWXGcz/pDglNB7mmbXOv8OLky+2ALgrq82cZVoKuwz5qpNrTeYdWOrsexj8NVr0B4p5BSebacFeTMlhpphExSJwbIDPIn0TJcfB9/XdqOmpt3pd2qg/ReB7YBZdbvAWxBd/0G2AsT5Rb9BKDqNcBwcNlde4CyZw5Q7QxYilUHqHvVQWqsPpgM7F9Raqffof+qcn7VgvtsaCNJ0DYJaGX22Zb/kde14TS8WpqssJMhzivcYk0j5zRZWwWsj21IhvUoh/UVnBa47fh0XxbWL7EgrNfAG04Q11KU0oIYnhpBQD0czOt93AuYHqTSZ3BmwQ2AEwaRhbrXB+7AEJyuA05Pgz1YeWBUTgsl9d8utR9gzZtZnhzCbUFWa1viAhuN2wLkqoDVtVjAiuk7bgs+TwE2j400C2Dhm5HiCFaELOIZu78lrqsn+Xfg6UZbVwWkayJxM3AunGoGTnQLMwCA3pllM3OlRrrlbvX3yscO9rHjatF0qliX3WSaZvlch+VxqeV35Zk

**Comment by jimmyt857** [comment]
Sorry, raid sim isn't supported yet!
