### ISSUE TITLE
Backdraft Global Cooldown Reduction

### ISSUE THREAD

**Issue by Cuppincakes** [wowsims/wotlk#987]
**Describe the bug**
The destruction talent "Backdraft" should reduce the global cooldown and cast time of your next 3 destruction spells. According to the "timeline" under the "detailed results" tab, the cast time is being correctly reduced however the global cooldown is not, leading to ~.3 seconds of lost uptime after every conflag cast

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Sim Presets'
3. Scroll down to 'Destruction'
4. Go to 'Detailed Results'
5. Click on 'Timeline'
6. See Error

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
https://wowsims.github.io/wotlk/warlock/#eJztUjFoFEEU3ff2ck42RkZRGFOt2xiEwNwtB7HJbawCNgeCpIyFFmIRxEKtzoNAtApYGRAEG5tAsNDkEpKgRo1RjAkmmIiFEtxKLoKt+Gc3vc0VFj6Yx5///vw/8+cHoaKmZT+GMIxR1oEJYBpcAtaAFDhzTCFkLyz6kaDmovAIOOL13O9ooFi7cuHGxavqgFY9TxFo/XOe5t0XRsXlZ1yYYdCpf31m5D+cZdCt0zmaNyL6TunWu1s024/9XNX6u6gvb8tRUfck4JBOJWB9h1FBPF7QpceaNFtTfgRP8u7N7ydSuiVFG8vO+iFWOuUHBf1+jsITs45bmb3YdBFvpcqrHbf/0HT84Amjoyp7Xq0w3DHC65AmjAOnXtP7j7bgplLQNBzFZRMc1L5hmM8TZYyKosHwDk722TguWRtbWX22UrZxWbiUeSulOK6UYxtXSl9h1OYq9addmo+rDBsb7P29TntrgykKLXRNwtuGF931O7Pq9fPJ4fweA8nxyXsOK9XTuWeteuJShs1q+RvDc4b/7LdfS9qRpb7y4i95zraljkPe4/HnyeC+IxnBH7STe1s=

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [105.0.5195.102]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Tharre** [comment]
Backdraft does not reduce the GCD below the 1s cap, this is working identically to how it does in-game.

See [here](https://github.com/JamminL/wotlk-classic-bugs/issues/396) for some additional discussions around that mechanic.
