### ISSUE TITLE
Missing Dragonspine

### ISSUE THREAD

**Issue by Halroc** [wowsims/wotlk#989]
Dragonspine trophy, berserker's call isn't available in trinkets, also onslaught belt has 2 gem slots, when it actually only has 1. Makes pre patch simming difficult.

**Comment by jimmyt857** [comment]
Dragonspine and berserker's call have been added back in. The extra gem slot is for blacksmithing belt buckles. We don't do prepatch sims, would require a lot of extra work. Every spell/ability/scaling/etc would change, even the rotations.
