### ISSUE TITLE
Crash Report -1006416749

### ISSUE THREAD

**Issue by CharWS** [wowsims/wotlk#993]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1IHEEU3u/tRtdN1FFERqvzikQEYW6XBa1utRLSCDaWSaFYWCTBQq0OK9HCIkX8AbEURBAE8RcED+IV6oGnggYVQ+REBUsJCL65W7G0ucLCr3gz7/t5w+6ME7VJkKIefEMCmAUWgE0gDWSBe1CaqFVESCFAJ3uGc55Ko3bh3RCK2nu/DnT9sCGc2iQcIS6PSO6dUrRoaYt2d8gpEfd/KGquL5NTKm7XSf4+DVtb7K+RXD4hnWIhdcKp6RRprUyMsJZkxuLW4D7LjqN5M+w/iMNVdvOeA5y/YfVy7jlvi7ENktl507HE1SJxHV3RdXNV1+s97XhYIXk2Y4a78xntHeOp5Tap0ia0W51Wv/7Yhm0y3lAQDFo2JP3HJ6c6QBu+59m7+EBuHd4K+FW9r3hiIxjBR9dTvlLKb/Rcrp6vPN91ladiLCjleTEV8/zYBaQ9lSHxK0Py9h9FxjNUP35AauKAsrDuUDwJ4xhG9KdZkhue6A7CY6qCmskJjVS8Oc+k43XdORzG3b8U6ZD0al9AX1CIKYlU8oU5nwtyjkb+H/NNt4RE8AWPz6qFug==

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xdc3e0, 0x1136ac0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).applyKillingMachine(0x524e000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_frost.go:148 +0xd
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyFrostTalents(0x524e000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_frost.go:44 +0x37
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyTalents(0x524e000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/deathknight.go:227 +0x8
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x524e000, {0x2efea8, 0x20ab600}, {{{},

**Comment by JooperGH** [comment]
Fixed some time ago, forgot to close.
