### ISSUE TITLE
Crash Report -1033382428

### ISSUE THREAD

**Issue by saimpot** [wowsims/wotlk#997]
Link:
https://wowsims.github.io/wotlk/deathknight/#eJzjUuJgEmAyYMpgLGBsYGRcwci4gZHxACPjBUbGF4yMPxiZLjAxOQkrMBkwOjBGQNR0gJUJMVkwSl1laWJkC8hJrEwt4mAV4JJK5WJAgnwCs3czSVxfy6zEsmcHEwMXj8C1XUxKbPNOMgERF4fAs11MEs9WM3HxCszaxiTxAqiOGaiOi0Wgdx+I7N4JIvuWgMjX55nARrII/DnDpCTCwWTAa8EYwBLBksBUAXETk9YJJoZRQBVQxcLBKMH0i1GdS8yB0YOxECL6wb4STHccdhBikOIWhIkqMHYxqhkZG5gaGBiY6hobAUljUwNjUyMjA2MDQ6CEgYGxsaGBobGp4SNGCY7ZV5gEpl9hknj7lElhxhUmjRlXmQxmXmV6wcjygZF9FiPDLUYGpcnMnGDDG8ocoNaIOEjOmgkCJ+0tISIX7BXTwOCavdFjJoVgicGbAkocqGFKw8kjBMzxpoo9IAAJY2BMO0IFHBIYAaQwYFU=

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xdc3c0, 0x1136ac0})
	/opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).applyKillingMachine(0x8368000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_frost.go:148 +0xd
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyFrostTalents(0x8368000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/talents_frost.go:44 +0x37
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).ApplyTalents(0x8368000)
	/home/runner/work/wotlk/wotlk/sim/deathknight/deathknight.go:227 +0x8
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x8368000, {0x2efee8, 0x8358840}, {{{}, {}, {}, 0x0}, 0x0, {0x0, 0x0, ...}, ...}, ...)
	/home/runner/work

**Comment by JooperGH** [comment]
Thanks this is fixed now.
